-- ============================================================================
-- Fluentia LMS — Seed Data for Local Development
-- ============================================================================
--
-- IMPORTANT: Auth users CANNOT be created via SQL in hosted Supabase.
-- You must create auth users FIRST via one of these methods:
--   1. Supabase Dashboard → Authentication → Users → Add User
--   2. Supabase Auth API (supabase.auth.signUp)
--   3. Supabase CLI for local development (supabase auth create-user)
--
-- After creating auth users, replace the placeholder UUIDs below with
-- the real UUIDs assigned by Supabase Auth.
--
-- This seed file populates the PUBLIC tables only (profiles, students,
-- trainers, groups, settings, achievements).
-- ============================================================================


-- ============================================================================
-- PLACEHOLDER UUIDs
-- Replace these with real UUIDs after creating auth users.
-- ============================================================================

-- Admin / Trainer: Dr. Ali (founder, also the first trainer)
-- Create in Supabase Auth: admin@fluentia.academy
DO $$
DECLARE
  admin_id       uuid := '00000000-0000-0000-0000-000000000001';

  -- Students — create each in Supabase Auth with an email/password
  student_nadia  uuid := '00000000-0000-0000-0000-000000000010';
  student_alhanf uuid := '00000000-0000-0000-0000-000000000011';
  student_hawazn uuid := '00000000-0000-0000-0000-000000000012';
  student_manar  uuid := '00000000-0000-0000-0000-000000000013';

  -- Groups
  group_1a       uuid := gen_random_uuid();
  group_2a       uuid := gen_random_uuid();
  group_3        uuid := gen_random_uuid();

BEGIN

-- ============================================================================
-- 1. PROFILES
-- These would normally be auto-created by the on_auth_user_created trigger.
-- For seeding, we insert them directly.
-- ============================================================================

INSERT INTO public.profiles (id, full_name, display_name, role, email) VALUES
  (admin_id,       'Dr. Ali',                    'Dr. Ali',   'admin',   'admin@fluentia.academy'),
  (student_nadia,  'نادية خيار القحطاني',         'نادية',     'student', 'nadia@example.com'),
  (student_alhanf, 'الهنوف البقمي',               'الهنوف',    'student', 'alhanoof@example.com'),
  (student_hawazn, 'هوازن العتيبي',               'هوازن',     'student', 'hawazin@example.com'),
  (student_manar,  'منار العتيبي',                'منار',      'student', 'manar@example.com')
ON CONFLICT (id) DO NOTHING;


-- ============================================================================
-- 2. TRAINERS
-- Dr. Ali is both the admin and the initial trainer.
-- ============================================================================

INSERT INTO public.trainers (id, specialization, per_session_rate, is_active) VALUES
  (admin_id, ARRAY['general_english', 'ielts', 'speaking'], 150, true)
ON CONFLICT (id) DO NOTHING;


-- ============================================================================
-- 3. GROUPS
-- Real groups from the academy's current schedule.
-- ============================================================================

INSERT INTO public.groups (id, name, code, level, trainer_id, max_students, is_active, schedule) VALUES
  (group_1a, 'Group 1A', 'G1A', 2, admin_id, 7, true,
    '{"sunday": "18:00-19:30", "tuesday": "18:00-19:30", "thursday": "18:00-19:30"}'::jsonb),
  (group_2a, 'Group 2A', 'G2A', 2, admin_id, 7, true,
    '{"sunday": "20:00-21:30", "tuesday": "20:00-21:30", "thursday": "20:00-21:30"}'::jsonb),
  (group_3,  'Group 3',  'G3',  1, admin_id, 7, true,
    '{"monday": "18:00-19:30", "wednesday": "18:00-19:30"}'::jsonb)
ON CONFLICT (id) DO NOTHING;


-- ============================================================================
-- 4. STUDENTS
-- Real student data with custom pricing.
-- Note: referral_code is auto-generated by the on_student_generate_referral trigger.
-- ============================================================================

INSERT INTO public.students (id, academic_level, package, track, group_id, status, custom_price, enrollment_date) VALUES
  -- نادية خيار القحطاني — Level 2, Group 2A, 600 SAR
  (student_nadia,  2, 'asas', 'foundation', group_2a, 'active', 600, '2025-09-01'),
  -- الهنوف البقمي — Level 2, Group 2A, 800 SAR
  (student_alhanf, 2, 'talaqa', 'development', group_2a, 'active', 800, '2025-09-01'),
  -- هوازن العتيبي — Level 2, Group 3, 500 SAR
  (student_hawazn, 2, 'asas', 'foundation', group_3,  'active', 500, '2025-10-15'),
  -- منار العتيبي — Level 1, Group 3, 500 SAR
  (student_manar,  1, 'asas', 'foundation', group_3,  'active', 500, '2025-10-15')
ON CONFLICT (id) DO NOTHING;


-- ============================================================================
-- 5. SETTINGS
-- System-wide configuration values.
-- ============================================================================

INSERT INTO public.settings (key, value) VALUES
  ('xp_values', '{
    "assignment_on_time": 10,
    "assignment_late": 5,
    "class_attendance": 15,
    "correct_answer": 5,
    "helped_peer": 10,
    "shared_summary": 15,
    "streak_7": 50,
    "streak_14": 100,
    "streak_30": 200,
    "first_submission": 25,
    "voice_note_bonus": 5,
    "writing_bonus": 5,
    "daily_challenge": 5,
    "early_bird": 5,
    "reaction_received": 2,
    "penalty_absent": -20,
    "penalty_unknown_word": -5,
    "penalty_pronunciation": -5
  }'::jsonb),

  ('package_prices', '{
    "asas": 750,
    "talaqa": 1100,
    "tamayuz": 1500,
    "ielts": 2000
  }'::jsonb),

  ('writing_limits', '{
    "asas": 2,
    "talaqa": 4,
    "tamayuz": 8,
    "ielts": 8
  }'::jsonb),

  ('chatbot_limits', '{
    "asas": 10,
    "talaqa": 20,
    "tamayuz": 999,
    "ielts": 20
  }'::jsonb),

  ('ai_monthly_budget_sar', '50'::jsonb),

  ('moyasar_payment_link', '""'::jsonb),

  ('academy_info', '{
    "name": "Fluentia Academy",
    "name_ar": "أكاديمية طلاقة",
    "phone": "+966 55 866 9974",
    "tiktok": "@fluentia_",
    "instagram": "@fluentia__"
  }'::jsonb)
ON CONFLICT (key) DO NOTHING;


-- ============================================================================
-- 6. ACHIEVEMENTS
-- Gamification badges from the product spec.
-- ============================================================================

INSERT INTO public.achievements (code, name_ar, name_en, description_ar, icon, xp_reward, is_active) VALUES
  ('fire_starter',    'شعلة البداية',    'Fire Starter',    'أكمل أول واجب لك',                              '🔥', 25,  true),
  ('bookworm',        'دودة الكتب',      'Bookworm',        'أكمل 10 واجبات قراءة',                          '📚', 50,  true),
  ('voice_hero',      'بطل الصوت',       'Voice Hero',      'أرسل 20 ملاحظة صوتية',                          '🎤', 50,  true),
  ('grammar_guru',    'خبير القواعد',     'Grammar Guru',    'احصل على تقييم ممتاز في 5 واجبات قواعد',          '✍️', 75,  true),
  ('helper',          'المساعد',         'Helper',          'ساعد 5 زملاء في المجموعة',                       '🤝', 50,  true),
  ('mvp',             'نجم الأسبوع',     'MVP',             'احصل على أعلى XP في المجموعة لأسبوع',            '🏆', 100, true),
  ('streak_master',   'سيد الاستمرارية',  'Streak Master',   'حافظ على سلسلة 30 يوم',                         '⚡', 200, true),
  ('level_up',        'ترقية المستوى',    'Level Up',        'انتقل إلى مستوى أكاديمي أعلى',                   '📈', 150, true),
  ('sniper',          'القناص',          'Sniper',          'أجب على 10 أسئلة صحيحة متتالية في الكويزات',      '🎯', 75,  true),
  ('note_taker',      'كاتب الملاحظات',   'Note Taker',      'شارك 5 ملخصات حصص',                             '📝', 50,  true),
  ('perfect_week',    'أسبوع مثالي',     'Perfect Week',    'أكمل جميع الواجبات وحضر كل الحصص في أسبوع',      '🌟', 100, true),
  ('diamond_student', 'الطالب الألماسي',  'Diamond Student', 'وصل إلى مستوى اللعب 10',                        '💎', 200, true),
  ('ambassador',      'السفير',          'Ambassador',      'قم بإحالة 3 طلاب جدد للأكاديمية',                '🎖️', 150, true),
  ('social_warrior',  'محارب السوشال',    'Social Warrior',  'شارك 10 إنجازات على وسائل التواصل الاجتماعي',    '📱', 50,  true)
ON CONFLICT (code) DO NOTHING;


END $$;


-- ============================================================================
-- NEXT STEPS (for the developer)
-- ============================================================================
-- 1. Create auth users in Supabase Dashboard for:
--    - admin@fluentia.academy (admin role)
--    - nadia@example.com, alhanoof@example.com, etc. (student role)
--
-- 2. Copy the generated UUIDs from Supabase Auth into the variables above.
--
-- 3. Re-run this seed: supabase db reset
--    (This drops and recreates the database, runs migrations, then seeds.)
--
-- 4. Alternatively, for production:
--    - Create users via the Supabase Auth API
--    - The on_auth_user_created trigger auto-creates profiles
--    - Then run INSERT statements for students, trainers, groups, etc.
-- ============================================================================
