const {Client} = require('pg');

// Simple A1/A2 level English definitions for each word
const DEFS = {
  // Unit 1: Cultural Festivals
  "festival": "a special event with music, food, and fun",
  "tradition": "something people do the same way for many years",
  "celebration": "a party or event to show happiness",
  "culture": "the beliefs and way of life of a group of people",
  "holiday": "a day when people do not work or go to school",
  "decoration": "something pretty you put up to make a place look nice",
  "guest": "a person who visits your home or event",
  "costume": "special clothes worn for a festival or show",
  "parade": "a group of people walking together in the street",
  "ceremony": "a formal event for a special occasion",
  "decorate": "to make a place look nice with pretty things",
  "dress up": "to wear nice or special clothes",
  "religious": "related to a religion or belief in God",
  "annual": "happening once every year",
  "national": "related to the whole country",
  "event": "something that happens, especially something important",
  "fireworks": "colorful lights that explode in the sky",
  "mask": "something you wear on your face to hide it",
  "feast": "a very large and special meal",
  "custom": "a way of doing things that has existed for a long time",
  "flag": "a piece of cloth with colors that represents a country",
  "lantern": "a light you can carry, often used outdoors",
  "pray": "to talk to God",
  "march": "to walk together in a group",
  "honor": "to show respect for someone",
  "joyful": "very happy",
  "festive": "happy and fun, like a celebration",
  "sacred": "very holy and special in a religion",
  "lively": "full of energy and excitement",
  "exchange": "to give something and get something back",
  "harvest": "the time when crops are picked from the fields",
  "anthem": "an important song for a country or group",
  "ritual": "a set of actions done the same way each time",
  "heritage": "important things passed down from the past",
  "unity": "the state of being together as one",
  "blessing": "something good given by God or luck",
  "gratitude": "the feeling of being thankful",
  "preserve": "to keep something safe so it does not change",
  "generous": "willing to give and share with others",
  "memorable": "something you will remember for a long time",

  // Unit 2: Ocean Life
  "ocean": "the very large area of salt water on Earth",
  "wave": "water that moves up and down in the sea",
  "whale": "a very large animal that lives in the ocean",
  "shark": "a large fish with sharp teeth",
  "shell": "the hard outside cover of some sea animals",
  "island": "a piece of land with water all around it",
  "coral": "a hard colorful thing that grows in warm seas",
  "dolphin": "a smart sea animal that jumps out of water",
  "turtle": "a slow animal with a hard shell on its back",
  "sand": "tiny pieces of rock found on beaches",
  "deep": "going far down from the top",
  "shallow": "not deep, close to the surface",
  "salty": "having the taste of salt",
  "dive": "to jump or go down into water",
  "float": "to stay on top of water without sinking",
  "sink": "to go down below the surface of water",
  "reef": "a line of rocks or coral near the water surface",
  "tide": "the rise and fall of the sea level",
  "seaweed": "a plant that grows in the sea",
  "coast": "the land next to the sea",
  "current": "water that moves in one direction in the sea",
  "creature": "any living animal",
  "seahorse": "a small sea animal shaped like a horse",
  "underwater": "below the surface of the water",
  "marine": "related to the sea",
  "endangered": "at risk of disappearing from the world",
  "flow": "to move smoothly in one direction",
  "breathe": "to take air in and out of your body",
  "freeze": "to become very cold and turn to ice",
  "ecosystem": "all the plants and animals living together in an area",
  "predator": "an animal that hunts and eats other animals",
  "migration": "when animals move to a different place each season",
  "species": "a group of similar plants or animals",
  "oxygen": "a gas in the air that all living things need",
  "pollution": "harmful things put into the air, water, or land",
  "habitat": "the natural home of an animal or plant",
  "vast": "very large in size",
  "extinct": "no longer existing; all have died",
  "absorb": "to take in or soak up",
  "anchor": "a heavy object that keeps a ship in place",

  // Unit 3: Space Exploration
  "planet": "a large round object that moves around a star",
  "star": "a bright point of light in the night sky",
  "moon": "the round object that goes around the Earth at night",
  "earth": "the planet where we live",
  "rocket": "a vehicle that flies into space",
  "astronaut": "a person who travels to space",
  "space": "the area beyond Earth where stars and planets are",
  "satellite": "an object that goes around a planet",
  "telescope": "a tool used to see things that are far away",
  "gravity": "the force that pulls things toward the ground",
  "orbit": "to move in a circle around something",
  "distant": "far away",
  "tiny": "very small",
  "bright": "giving out a lot of light",
  "scientist": "a person who studies science",
  "universe": "everything that exists, including all space",
  "galaxy": "a very large group of stars in space",
  "comet": "an object in space with a bright tail",
  "astronomer": "a scientist who studies stars and planets",
  "mission": "an important task or journey",
  "atmosphere": "the layer of air around a planet",
  "solar": "related to the sun",
  "weightless": "having no weight; floating in space",
  "mysterious": "strange and hard to understand",
  "rotate": "to turn around in a circle",
  "observe": "to watch carefully",
  "expand": "to get bigger",
  "scientific": "related to science",
  "visible": "able to be seen",
  "constellation": "a group of stars that form a shape",
  "meteor": "a piece of rock that burns in the sky",
  "spacecraft": "a vehicle that travels in space",
  "crater": "a large round hole in the ground",
  "infinite": "having no end; going on forever",
  "calculate": "to find an answer using math",
  "transmit": "to send a signal or message",
  "discovery": "finding something new for the first time",
  "existence": "the state of being real or alive",
  "lunar": "related to the moon",
  "probe": "a device sent to explore space",
  "asteroid": "a small rocky object in space",

  // Unit 4: Music & Art
  "instrument": "a thing you use to make music",
  "guitar": "a musical instrument with strings",
  "drum": "a musical instrument you hit to make sound",
  "piano": "a large musical instrument with black and white keys",
  "artist": "a person who creates art like paintings or music",
  "singer": "a person who sings songs",
  "concert": "a live music show",
  "painting": "a picture made with paint",
  "rhythm": "a regular pattern of sounds or beats",
  "melody": "a series of musical notes that sound nice together",
  "perform": "to do something in front of people, like sing or act",
  "compose": "to write music or a song",
  "record": "to save sound or video so you can play it again",
  "quiet": "making little or no sound",
  "voice": "the sound you make when you speak or sing",
  "band": "a group of people who play music together",
  "stage": "the raised area where people perform",
  "choir": "a group of people who sing together",
  "sculpture": "a piece of art made from stone, wood, or metal",
  "exhibition": "a public show of art or objects",
  "audience": "the people watching a show or performance",
  "gallery": "a building where art is shown",
  "sketch": "a quick simple drawing",
  "classical": "traditional and formal, especially about music",
  "visual": "related to seeing or sight",
  "express": "to show your thoughts or feelings",
  "rehearse": "to practice before a performance",
  "applaud": "to clap your hands to show you liked something",
  "emotional": "causing strong feelings",
  "tune": "a series of musical notes; a melody",
  "masterpiece": "an excellent piece of art or work",
  "harmony": "when different sounds go well together",
  "composer": "a person who writes music",
  "lyrics": "the words of a song",
  "abstract": "art that uses shapes and colors, not real things",
  "original": "the first or earliest version of something",
  "illustrate": "to draw pictures for a book",
  "portray": "to show or describe something in a picture",
  "creativity": "the ability to make new and interesting things",
  "talent": "a natural ability to do something well",

  // Unit 5: Famous Places
  "tower": "a tall narrow building or part of a building",
  "museum": "a building where you can see old or important things",
  "castle": "a large strong building from the past",
  "monument": "a building or statue made to remember someone",
  "statue": "a figure of a person or animal made from stone",
  "temple": "a building where people go to pray",
  "palace": "a very large house where a king or queen lives",
  "pyramid": "a building with a flat bottom and pointed top",
  "landmark": "a famous building or place that is easy to recognize",
  "wonder": "something amazing that surprises you",
  "guide": "a person who shows you around a place",
  "entrance": "the door or way into a building",
  "ancient": "very old, from thousands of years ago",
  "historic": "important in history",
  "stunning": "extremely beautiful or impressive",
  "build": "to make something by putting parts together",
  "cathedral": "a very large church",
  "fortress": "a strong building made to protect people",
  "ruins": "what is left of an old building that fell apart",
  "architecture": "the style and design of buildings",
  "column": "a tall round post that holds up a building",
  "dome": "a round roof shaped like half a ball",
  "arch": "a curved shape over a door or window",
  "construct": "to build something large",
  "restore": "to fix something old so it looks new again",
  "surround": "to be all around something",
  "magnificent": "very beautiful and impressive",
  "massive": "very large and heavy",
  "iconic": "very famous and recognized by many people",
  "civilization": "a group of people with their own culture and laws",
  "inscription": "words carved or written on a surface",
  "excavate": "to dig up something from the ground",
  "archaeological": "related to the study of old things from the past",
  "majestic": "looking grand and impressive",
  "marble": "a smooth hard stone used in buildings",
  "renovation": "the act of fixing and improving a building",
  "fountain": "a structure that sends water up into the air",
  "balcony": "a small area outside a window on an upper floor",
  "courtyard": "an open area inside a building",
  "staircase": "a set of stairs inside a building",
  "pillar": "a tall post that supports a building",
  "mosaic": "a picture made from small colored pieces",

  // Unit 6: Inventions
  "invention": "a new thing that someone creates for the first time",
  "machine": "a piece of equipment that does work",
  "engine": "the part of a car or machine that makes it move",
  "electricity": "the power used to make lights and machines work",
  "battery": "a small thing that gives power to a device",
  "wheel": "a round thing that turns to help something move",
  "tool": "something you use to do a job",
  "device": "a small machine that does a special job",
  "invent": "to create something new for the first time",
  "design": "to plan and draw how something will look",
  "solve": "to find the answer to a problem",
  "modern": "new and from the present time",
  "automatic": "working by itself without human help",
  "electronic": "using electricity and small parts to work",
  "powerful": "having a lot of strength or force",
  "laboratory": "a room where scientists do tests",
  "patent": "a document that protects your invention",
  "prototype": "the first model of something new",
  "switch": "a button or lever that turns something on or off",
  "wire": "a thin piece of metal that carries electricity",
  "signal": "a sign or message sent using light, sound, or radio",
  "replace": "to put something new in place of something old",
  "attach": "to join or connect one thing to another",
  "operate": "to make a machine work",
  "efficient": "working well without wasting time or energy",
  "portable": "easy to carry and move around",
  "wireless": "working without wires or cables",
  "technical": "related to machines and technology",
  "manual": "done by hand, not by machine",
  "revolution": "a big change in how things are done",
  "breakthrough": "an important discovery that solves a problem",
  "innovation": "a new idea or method",
  "transform": "to change something completely",
  "manufacture": "to make products in a factory",
  "automate": "to make something work without human help",
  "mechanical": "related to machines and their parts",
  "genius": "a very smart person",
  "inventor": "a person who creates new things",
  "remarkable": "very unusual and impressive",
  "circuit": "a path that electricity flows through",
  "sensor": "a device that detects changes like heat or light",
  "turbine": "a machine that spins to make electricity",

  // Unit 7: Sports Stars
  "champion": "the winner of a competition",
  "athlete": "a person who is good at sports",
  "medal": "a round piece of metal given as a prize",
  "coach": "a person who trains athletes or teams",
  "stadium": "a large place where people watch sports",
  "race": "a competition to see who is fastest",
  "goal": "the point scored in a game; or something you want to achieve",
  "match": "a game between two teams or players",
  "score": "to get a point in a game",
  "win": "to come first in a game or competition",
  "lose": "to not win a game or competition",
  "kick": "to hit something with your foot",
  "throw": "to send something through the air with your hand",
  "catch": "to grab something that is moving through the air",
  "fit": "healthy and strong because of exercise",
  "final": "the last and most important game in a competition",
  "tournament": "a set of games to find the best team",
  "opponent": "the person or team you play against",
  "trophy": "a prize given to the winner",
  "referee": "the person who makes sure rules are followed",
  "captain": "the leader of a team",
  "fan": "a person who likes a team or player very much",
  "defeat": "to win against someone",
  "sprint": "to run very fast for a short time",
  "defend": "to protect something from attack",
  "cheer": "to shout to show support",
  "competitive": "wanting to win very much",
  "athletic": "strong and good at sports",
  "professional": "doing something as a paid job",
  "determination": "the strong will to do something",
  "endurance": "the ability to keep going for a long time",
  "strategy": "a plan to reach a goal",
  "legend": "a very famous person or old story",
  "overcome": "to succeed in dealing with a problem",
  "achieve": "to succeed in doing something",
  "retire": "to stop working because of age",
  "dedication": "hard work and strong focus on something",
  "sportsmanship": "fair and respectful behavior in sports",
  "penalty": "a punishment or free kick given for breaking a rule",
  "marathon": "a very long running race of about 42 km",
  "semifinal": "the game before the final",

  // Unit 8: Ancient Civilizations
  "king": "a man who rules a country",
  "queen": "a woman who rules a country",
  "empire": "a group of countries ruled by one leader",
  "warrior": "a brave person who fights in battles",
  "treasure": "a collection of valuable things like gold",
  "tomb": "a place where a dead person is put",
  "weapon": "something used to fight, like a sword",
  "trade": "buying and selling goods",
  "clay": "a type of earth used to make pots",
  "scroll": "a long roll of paper with writing",
  "conquer": "to take control of a place by force",
  "rule": "to control a country as a leader",
  "worship": "to show love and respect for God",
  "mighty": "very strong and powerful",
  "royal": "related to a king or queen",
  "pharaoh": "an ancient Egyptian king",
  "dynasty": "a family that rules for many years",
  "merchant": "a person who buys and sells things",
  "pottery": "pots and dishes made from clay",
  "armor": "metal clothes worn to protect the body in battle",
  "chariot": "a vehicle with wheels pulled by horses",
  "carve": "to cut a shape out of wood or stone",
  "bury": "to put something in the ground and cover it",
  "invade": "to enter a country with an army to take control",
  "wealthy": "having a lot of money",
  "golden": "made of gold or having the color of gold",
  "hieroglyph": "a picture symbol used in ancient Egyptian writing",
  "archaeology": "the study of old things found in the ground",
  "mummy": "a dead body kept from the past using special methods",
  "decipher": "to figure out the meaning of something hard to read",
  "thrive": "to grow well and be successful",
  "collapse": "to fall down suddenly",
  "legendary": "very famous; told about in old stories",
  "prosperous": "rich and successful",
  "shield": "a large flat object used to protect the body",
  "throne": "the special chair of a king or queen",
  "siege": "surrounding a place to force it to give up",
  "scribe": "a person whose job was to write and copy texts",
  "irrigation": "bringing water to fields to help crops grow",
  "decree": "an official order from a leader",
  "papyrus": "a plant used to make paper in ancient times",

  // Unit 9: Photography
  "photograph": "a picture taken with a camera",
  "lens": "the glass part of a camera that focuses light",
  "flash": "a bright light used when taking photos",
  "focus": "to make an image clear and sharp",
  "shoot": "to take a photo or video",
  "zoom": "to make something look closer or bigger",
  "angle": "the direction from which you look at something",
  "background": "the part of a picture behind the main subject",
  "portrait": "a photo or painting of a person",
  "landscape": "a photo or picture of nature and scenery",
  "image": "a picture or photo",
  "filter": "something that changes the color or look of a photo",
  "sharp": "very clear and easy to see",
  "blurry": "not clear; hard to see the details",
  "natural": "found in nature; not made by people",
  "digital": "using computer technology",
  "exposure": "how much light reaches the camera",
  "frame": "the border around a picture",
  "shadow": "a dark shape made when something blocks light",
  "contrast": "the difference between light and dark areas",
  "resolution": "how clear and detailed a photo is",
  "tripod": "a stand with three legs for holding a camera",
  "crop": "to cut the edges of a photo",
  "edit": "to change or improve a photo or text",
  "adjust": "to change something slightly to make it better",
  "vivid": "very bright and strong in color",
  "scenic": "having beautiful natural views",
  "outdoor": "done or used outside",
  "candid": "natural and not planned; taken without posing",
  "composition": "how things are arranged in a photo",
  "perspective": "the way you see something from a certain position",
  "monochrome": "using only one color or black and white",
  "silhouette": "a dark shape seen against a light background",
  "panorama": "a very wide view of an area",
  "shutter": "the part of a camera that opens to let in light",
  "overexpose": "to let too much light into a photo",
  "enhance": "to improve the quality of something",
  "illuminate": "to light up something",
  "aesthetic": "related to beauty and good taste",
  "vintage": "from the past; old-fashioned but stylish",
  "aperture": "the opening in a camera lens that lets in light",
  "macro": "very close-up, showing tiny details",
  "timelapse": "a video that shows time moving very fast",

  // Unit 10: World Cuisines
  "dish": "food prepared and served in a certain way",
  "chef": "a person who cooks food professionally",
  "flavor": "the taste of food or drink",
  "sauce": "a liquid put on food to add taste",
  "grill": "to cook food over a fire or hot surface",
  "bake": "to cook food in an oven",
  "boil": "to heat water until it bubbles",
  "fry": "to cook food in hot oil",
  "mix": "to put things together and stir",
  "stir": "to move a spoon around in something",
  "spicy": "having a hot, burning taste",
  "sour": "having a sharp taste like a lemon",
  "bitter": "having a strong unpleasant taste",
  "raw": "not cooked",
  "oven": "a box-shaped machine used for baking food",
  "ingredient": "one of the things used to make food",
  "cuisine": "a style of cooking from a particular country",
  "appetizer": "a small dish eaten before the main meal",
  "portion": "the amount of food on your plate",
  "dough": "a thick mixture of flour and water used to make bread",
  "herb": "a plant used to add flavor to food",
  "roast": "to cook food in an oven or over a fire",
  "chop": "to cut food into small pieces",
  "marinate": "to soak food in sauce before cooking",
  "garnish": "to add something to food to make it look nice",
  "authentic": "real and true to its origin",
  "aromatic": "having a strong pleasant smell",
  "nutritious": "good for your health; full of nutrients",
  "savory": "having a salty or meat-like taste, not sweet",
  "seasonal": "available only at certain times of year",
  "gastronomy": "the art and science of cooking and eating well",
  "ferment": "to change chemically, like milk becoming cheese",
  "infuse": "to add flavor by soaking something in liquid",
  "simmer": "to cook slowly at a low temperature",
  "exquisite": "extremely beautiful or of very high quality",
  "gourmet": "very high quality food or cooking",
  "organic": "grown without chemicals",
  "texture": "how food feels in your mouth",
  "aroma": "a pleasant smell, especially from food",
  "blanch": "to put food briefly in boiling water",

  // Unit 11: Social Media
  "account": "your personal page on a website or app",
  "profile": "a page with your name and information online",
  "follower": "a person who sees your posts on social media",
  "content": "the things you post online like photos and videos",
  "notification": "a message telling you something happened on your phone",
  "comment": "something you write in response to a post",
  "hashtag": "a word with # used to group posts about a topic",
  "upload": "to send a file from your device to the internet",
  "follow": "to choose to see someone's posts on social media",
  "like": "to click a button to show you enjoy a post",
  "block": "to stop someone from seeing your posts",
  "reply": "to write back to someone's message",
  "viral": "spreading very quickly on the internet",
  "private": "only for you; not shared with everyone",
  "public": "open for everyone to see",
  "trending": "very popular right now",
  "influencer": "a popular person on social media",
  "algorithm": "a set of rules a computer follows to sort content",
  "platform": "a website or app where people share things",
  "privacy": "the right to keep your personal things secret",
  "feed": "the list of posts you see on social media",
  "stream": "to send video or audio live on the internet",
  "subscribe": "to sign up to receive updates from someone",
  "tag": "to mention someone in a post or photo",
  "unfollow": "to stop seeing someone's posts",
  "anonymous": "without showing your name",
  "interactive": "allowing people to participate and respond",
  "addictive": "something hard to stop doing",
  "cyberbullying": "being mean to someone online",
  "broadcast": "to send out a program or message to many people",
  "misinformation": "false information that is spread to others",
  "verification": "checking that something is true or correct",
  "engagement": "how much people interact with a post",
  "curate": "to carefully choose and organize content",
  "monetize": "to make money from something",
  "moderate": "to check content and remove bad posts",
  "influential": "having the power to change what people think",
  "controversial": "causing a lot of disagreement",
  "meme": "a funny image or video shared on the internet",
  "screenshot": "a picture of what is on your screen",
  "repost": "to share someone else's post again",
  "troll": "a person who tries to make others angry online",

  // Unit 12: Green Living
  "recycle": "to make old things into new things",
  "energy": "the power used to make things work",
  "waste": "things that are thrown away",
  "plastic": "a light material used to make bags and bottles",
  "environment": "the natural world around us",
  "nature": "the world of plants, animals, and the outdoors",
  "climate": "the usual weather in a place over many years",
  "soil": "the top layer of earth where plants grow",
  "plant": "to put seeds in the ground to grow",
  "reuse": "to use something again instead of throwing it away",
  "reduce": "to make something smaller or use less of it",
  "green": "good for the environment",
  "renewable": "can be used again and again, like wind or sun",
  "harmful": "causing damage or hurt",
  "eco-friendly": "not harmful to the environment",
  "solar panel": "a flat device that turns sunlight into electricity",
  "carbon": "a chemical found in all living things and in fuels",
  "greenhouse": "a glass building used to grow plants",
  "compost": "old food and plants that become soil",
  "footprint": "the effect your actions have on the environment",
  "conserve": "to use something carefully and not waste it",
  "pollute": "to make air, water, or land dirty",
  "decompose": "to break down and become part of the earth",
  "generate": "to produce or create something",
  "sustainable": "able to continue for a long time without harm",
  "biodegradable": "able to break down naturally",
  "toxic": "poisonous; harmful to living things",
  "global warming": "the slow rise in Earth's temperature",
  "emission": "gas or other substance released into the air",
  "deforestation": "cutting down large areas of trees",
  "biodiversity": "the variety of plants and animals in a place",
  "extinction": "when a type of animal or plant dies out completely",
  "conservation": "protecting nature and natural resources",
  "advocate": "to speak in support of something",
  "offset": "to balance the effect of something harmful",
  "ecological": "related to the environment and living things",
  "vulnerable": "easily hurt or at risk of danger",
  "landfill": "a place where waste is buried in the ground",
  "drought": "a long time without rain",
  "fossil fuel": "fuel like oil or coal formed from old plants and animals",
  "wildlife": "wild animals and plants in their natural home",
  "glacier": "a large mass of ice that moves slowly",
  "ozone": "a gas in the atmosphere that protects us from the sun",
};

async function main() {
  const c = new Client({
    host:'aws-1-eu-central-1.pooler.supabase.com',
    port:5432, database:'postgres',
    user:'postgres.nmjexpuycmqcxuxljier',
    password:'Ali-al-ahmad2000',
    ssl:{rejectUnauthorized:false}
  });
  await c.connect();

  // Add definition_en column to staging if not exists
  await c.query(`ALTER TABLE vocab_staging_l1 ADD COLUMN IF NOT EXISTS definition_en text`);

  const staged = await c.query('SELECT word FROM vocab_staging_l1');
  let updated = 0, missing = [];
  for (const r of staged.rows) {
    const def = DEFS[r.word.toLowerCase()] || DEFS[r.word];
    if (!def) {
      missing.push(r.word);
      continue;
    }
    await c.query('UPDATE vocab_staging_l1 SET definition_en = $1 WHERE word = $2', [def, r.word]);
    updated++;
  }
  console.log(`Updated definitions: ${updated}`);
  if (missing.length > 0) console.log(`Missing definitions for: ${missing.join(', ')}`);

  // Check for nulls
  const nulls = await c.query('SELECT COUNT(*) AS c FROM vocab_staging_l1 WHERE definition_en IS NULL');
  console.log(`Staging rows with NULL definition_en: ${nulls.rows[0].c}`);

  await c.end();
}

main().catch(e => { console.error(e); process.exit(1); });
