const {Client} = require('pg');

const EXISTING_WORDS = new Set(); // Will be populated from DB

const L1_ID = '2755b494-c7ff-4bdc-96ac-7ab735dc038c';
const L0_ID = 'cd96175e-76d4-48dc-b34f-83f3228a28b8';

// Unit themes: 1=Cultural Festivals, 2=Ocean Life, 3=Space Exploration, 4=Music & Art,
// 5=Famous Places, 6=Inventions, 7=Sports Stars, 8=Ancient Civilizations,
// 9=Photography, 10=World Cuisines, 11=Social Media, 12=Green Living

const ALL_WORDS = [
// ===== UNIT 1: Cultural Festivals =====
{w:"festival",c:"A1",s:"CEFR-J",p:"noun",ar:"مهرجان",een:"The festival starts in June.",ear:"يبدأ المهرجان في يونيو.",t:"core",u:1},
{w:"tradition",c:"A1",s:"CEFR-J",p:"noun",ar:"تقليد",een:"This is an old tradition.",ear:"هذا تقليد قديم.",t:"core",u:1},
{w:"celebration",c:"A1",s:"CEFR-J",p:"noun",ar:"احتفال",een:"The celebration was very big.",ear:"كان الاحتفال كبيراً جداً.",t:"core",u:1},
{w:"culture",c:"A1",s:"CEFR-J",p:"noun",ar:"ثقافة",een:"I love learning about culture.",ear:"أحب تعلم الثقافة.",t:"core",u:1},
{w:"holiday",c:"A1",s:"CEFR-J",p:"noun",ar:"عطلة",een:"Tomorrow is a holiday.",ear:"غداً عطلة.",t:"core",u:1},
{w:"decoration",c:"A1",s:"CEFR-J",p:"noun",ar:"زينة",een:"The decoration looks nice.",ear:"تبدو الزينة جميلة.",t:"core",u:1},
{w:"guest",c:"A1",s:"CEFR-J",p:"noun",ar:"ضيف",een:"We have a guest today.",ear:"لدينا ضيف اليوم.",t:"core",u:1},
{w:"costume",c:"A2",s:"CEFR-J",p:"noun",ar:"زي",een:"She wore a beautiful costume.",ear:"ارتدت زياً جميلاً.",t:"core",u:1},
{w:"parade",c:"A2",s:"CEFR-J",p:"noun",ar:"موكب",een:"The parade went down the street.",ear:"مر الموكب في الشارع.",t:"core",u:1},
{w:"ceremony",c:"A2",s:"CEFR-J",p:"noun",ar:"حفل",een:"The ceremony started at noon.",ear:"بدأ الحفل عند الظهر.",t:"core",u:1},
{w:"decorate",c:"A2",s:"CEFR-J",p:"verb",ar:"يُزين",een:"We decorate the house for Eid.",ear:"نزين البيت للعيد.",t:"core",u:1},
{w:"dress up",c:"A1",s:"CEFR-J",p:"verb",ar:"يتأنق",een:"Children dress up for the party.",ear:"يتأنق الأطفال للحفلة.",t:"core",u:1},
{w:"religious",c:"A2",s:"CEFR-J",p:"adjective",ar:"ديني",een:"It is a religious holiday.",ear:"إنها عطلة دينية.",t:"core",u:1},
{w:"annual",c:"A2",s:"CEFR-J",p:"adjective",ar:"سنوي",een:"This is an annual event.",ear:"هذا حدث سنوي.",t:"core",u:1},
{w:"national",c:"A1",s:"CEFR-J",p:"adjective",ar:"وطني",een:"Today is a national holiday.",ear:"اليوم عطلة وطنية.",t:"core",u:1},
{w:"event",c:"A1",s:"CEFR-J",p:"noun",ar:"حدث",een:"The event is next week.",ear:"الحدث الأسبوع القادم.",t:"core",u:1},
{w:"fireworks",c:"A2",s:"CEFR-J",p:"noun",ar:"ألعاب نارية",een:"We watched the fireworks at night.",ear:"شاهدنا الألعاب النارية ليلاً.",t:"extended",u:1},
{w:"mask",c:"A2",s:"CEFR-J",p:"noun",ar:"قناع",een:"He wore a funny mask.",ear:"ارتدى قناعاً مضحكاً.",t:"extended",u:1},
{w:"feast",c:"A2",s:"CEFR-J",p:"noun",ar:"وليمة",een:"The family had a big feast.",ear:"أقامت العائلة وليمة كبيرة.",t:"extended",u:1},
{w:"custom",c:"A2",s:"CEFR-J",p:"noun",ar:"عادة",een:"This custom is very old.",ear:"هذه العادة قديمة جداً.",t:"extended",u:1},
{w:"flag",c:"A1",s:"CEFR-J",p:"noun",ar:"علم",een:"The flag is green and white.",ear:"العلم أخضر وأبيض.",t:"extended",u:1},
{w:"lantern",c:"A2",s:"CEFR-J",p:"noun",ar:"فانوس",een:"The lantern gives warm light.",ear:"يعطي الفانوس ضوءاً دافئاً.",t:"extended",u:1},
{w:"pray",c:"A1",s:"CEFR-J",p:"verb",ar:"يصلي",een:"They pray together every day.",ear:"يصلون معاً كل يوم.",t:"extended",u:1},
{w:"march",c:"A2",s:"CEFR-J",p:"verb",ar:"يسير",een:"The people march in the street.",ear:"يسير الناس في الشارع.",t:"extended",u:1},
{w:"honor",c:"A2",s:"CEFR-J",p:"verb",ar:"يُكرم",een:"We honor our parents every day.",ear:"نكرم والدينا كل يوم.",t:"extended",u:1},
{w:"joyful",c:"A2",s:"CEFR-J",p:"adjective",ar:"بهيج",een:"It was a joyful moment.",ear:"كانت لحظة بهيجة.",t:"extended",u:1},
{w:"festive",c:"A2",s:"CEFR-J",p:"adjective",ar:"احتفالي",een:"The room looked festive.",ear:"بدت الغرفة احتفالية.",t:"extended",u:1},
{w:"sacred",c:"A2",s:"CEFR-J",p:"adjective",ar:"مقدس",een:"This is a sacred place.",ear:"هذا مكان مقدس.",t:"extended",u:1},
{w:"lively",c:"A2",s:"CEFR-J",p:"adjective",ar:"حيوي",een:"The music was very lively.",ear:"كانت الموسيقى حيوية جداً.",t:"extended",u:1},
{w:"exchange",c:"A2",s:"CEFR-J",p:"verb",ar:"يتبادل",een:"They exchange gifts on Eid.",ear:"يتبادلون الهدايا في العيد.",t:"extended",u:1},
{w:"harvest",c:"A2",s:"CEFR-J",p:"noun",ar:"حصاد",een:"The harvest was good this year.",ear:"كان الحصاد جيداً هذا العام.",t:"mastery",u:1},
{w:"anthem",c:"A2",s:"NGSL",p:"noun",ar:"نشيد",een:"They sang the national anthem.",ear:"غنوا النشيد الوطني.",t:"mastery",u:1},
{w:"ritual",c:"A2",s:"CEFR-J",p:"noun",ar:"طقس",een:"The morning ritual takes one hour.",ear:"يستغرق الطقس الصباحي ساعة.",t:"mastery",u:1},
{w:"heritage",c:"A2",s:"CEFR-J",p:"noun",ar:"تراث",een:"We must protect our heritage.",ear:"يجب أن نحمي تراثنا.",t:"mastery",u:1},
{w:"unity",c:"A2",s:"NGSL",p:"noun",ar:"وحدة",een:"The festival shows unity.",ear:"يظهر المهرجان الوحدة.",t:"mastery",u:1},
{w:"blessing",c:"A2",s:"CEFR-J",p:"noun",ar:"بركة",een:"Health is a great blessing.",ear:"الصحة نعمة عظيمة.",t:"mastery",u:1},
{w:"gratitude",c:"A2",s:"NGSL",p:"noun",ar:"امتنان",een:"She showed gratitude to her teacher.",ear:"أظهرت امتناناً لمعلمتها.",t:"mastery",u:1},
{w:"preserve",c:"A2",s:"CEFR-J",p:"verb",ar:"يحافظ على",een:"We preserve old traditions.",ear:"نحافظ على التقاليد القديمة.",t:"mastery",u:1},
{w:"generous",c:"A2",s:"CEFR-J",p:"adjective",ar:"كريم",een:"My uncle is very generous.",ear:"عمي كريم جداً.",t:"mastery",u:1},
{w:"memorable",c:"A2",s:"NGSL",p:"adjective",ar:"لا يُنسى",een:"It was a memorable day.",ear:"كان يوماً لا يُنسى.",t:"mastery",u:1},

// ===== UNIT 2: Ocean Life =====
{w:"ocean",c:"A1",s:"CEFR-J",p:"noun",ar:"محيط",een:"The ocean is very deep.",ear:"المحيط عميق جداً.",t:"core",u:2},
{w:"wave",c:"A1",s:"CEFR-J",p:"noun",ar:"موجة",een:"The wave was very big.",ear:"كانت الموجة كبيرة جداً.",t:"core",u:2},
{w:"whale",c:"A1",s:"CEFR-J",p:"noun",ar:"حوت",een:"The whale is the biggest animal.",ear:"الحوت هو أكبر حيوان.",t:"core",u:2},
{w:"shark",c:"A1",s:"CEFR-J",p:"noun",ar:"قرش",een:"The shark swims very fast.",ear:"يسبح القرش بسرعة كبيرة.",t:"core",u:2},
{w:"shell",c:"A1",s:"CEFR-J",p:"noun",ar:"صدفة",een:"I found a shell on the beach.",ear:"وجدت صدفة على الشاطئ.",t:"core",u:2},
{w:"island",c:"A1",s:"CEFR-J",p:"noun",ar:"جزيرة",een:"The island has many trees.",ear:"الجزيرة فيها أشجار كثيرة.",t:"core",u:2},
{w:"coral",c:"A2",s:"CEFR-J",p:"noun",ar:"مرجان",een:"Coral lives in warm water.",ear:"يعيش المرجان في الماء الدافئ.",t:"core",u:2},
{w:"dolphin",c:"A1",s:"CEFR-J",p:"noun",ar:"دلفين",een:"The dolphin jumped out of water.",ear:"قفز الدلفين من الماء.",t:"core",u:2},
{w:"turtle",c:"A1",s:"CEFR-J",p:"noun",ar:"سلحفاة",een:"The turtle moves very slowly.",ear:"تتحرك السلحفاة ببطء شديد.",t:"core",u:2},
{w:"sand",c:"A1",s:"CEFR-J",p:"noun",ar:"رمل",een:"The sand is hot in summer.",ear:"الرمل حار في الصيف.",t:"core",u:2},
{w:"deep",c:"A1",s:"CEFR-J",p:"adjective",ar:"عميق",een:"The pool is very deep.",ear:"المسبح عميق جداً.",t:"core",u:2},
{w:"shallow",c:"A2",s:"CEFR-J",p:"adjective",ar:"ضحل",een:"Children play in shallow water.",ear:"يلعب الأطفال في الماء الضحل.",t:"core",u:2},
{w:"salty",c:"A1",s:"CEFR-J",p:"adjective",ar:"مالح",een:"Sea water is very salty.",ear:"ماء البحر مالح جداً.",t:"core",u:2},
{w:"dive",c:"A2",s:"CEFR-J",p:"verb",ar:"يغوص",een:"He likes to dive in the sea.",ear:"يحب أن يغوص في البحر.",t:"core",u:2},
{w:"float",c:"A2",s:"CEFR-J",p:"verb",ar:"يطفو",een:"Wood can float on water.",ear:"يمكن للخشب أن يطفو على الماء.",t:"core",u:2},
{w:"sink",c:"A2",s:"CEFR-J",p:"verb",ar:"يغرق",een:"Heavy things sink in water.",ear:"الأشياء الثقيلة تغرق في الماء.",t:"core",u:2},
{w:"reef",c:"A2",s:"CEFR-J",p:"noun",ar:"شعاب مرجانية",een:"The reef has many fish.",ear:"الشعاب المرجانية فيها أسماك كثيرة.",t:"extended",u:2},
{w:"tide",c:"A2",s:"CEFR-J",p:"noun",ar:"مد وجزر",een:"The tide comes in the morning.",ear:"يأتي المد في الصباح.",t:"extended",u:2},
{w:"seaweed",c:"A2",s:"NGSL",p:"noun",ar:"أعشاب بحرية",een:"Seaweed grows on the rocks.",ear:"تنمو الأعشاب البحرية على الصخور.",t:"extended",u:2},
{w:"coast",c:"A2",s:"CEFR-J",p:"noun",ar:"ساحل",een:"We drove along the coast.",ear:"قدنا على طول الساحل.",t:"extended",u:2},
{w:"current",c:"A2",s:"CEFR-J",p:"noun",ar:"تيار",een:"The current is strong today.",ear:"التيار قوي اليوم.",t:"extended",u:2},
{w:"creature",c:"A2",s:"CEFR-J",p:"noun",ar:"مخلوق",een:"A strange creature lives here.",ear:"يعيش مخلوق غريب هنا.",t:"extended",u:2},
{w:"seahorse",c:"A2",s:"NGSL",p:"noun",ar:"حصان البحر",een:"The seahorse is very small.",ear:"حصان البحر صغير جداً.",t:"extended",u:2},
{w:"underwater",c:"A2",s:"CEFR-J",p:"adjective",ar:"تحت الماء",een:"We saw underwater animals.",ear:"رأينا حيوانات تحت الماء.",t:"extended",u:2},
{w:"marine",c:"A2",s:"CEFR-J",p:"adjective",ar:"بحري",een:"Marine animals need clean water.",ear:"الحيوانات البحرية تحتاج ماء نظيف.",t:"extended",u:2},
{w:"endangered",c:"A2",s:"CEFR-J",p:"adjective",ar:"مهدد بالانقراض",een:"The whale is endangered.",ear:"الحوت مهدد بالانقراض.",t:"extended",u:2},
{w:"flow",c:"A2",s:"CEFR-J",p:"verb",ar:"يتدفق",een:"Water flows to the sea.",ear:"يتدفق الماء إلى البحر.",t:"extended",u:2},
{w:"breathe",c:"A2",s:"CEFR-J",p:"verb",ar:"يتنفس",een:"Fish breathe under water.",ear:"تتنفس الأسماك تحت الماء.",t:"extended",u:2},
{w:"freeze",c:"A2",s:"CEFR-J",p:"verb",ar:"يتجمد",een:"Water can freeze in winter.",ear:"يمكن للماء أن يتجمد شتاءً.",t:"extended",u:2},
{w:"ecosystem",c:"A2",s:"NGSL",p:"noun",ar:"نظام بيئي",een:"The reef is an ecosystem.",ear:"الشعاب المرجانية نظام بيئي.",t:"mastery",u:2},
{w:"predator",c:"A2",s:"NGSL",p:"noun",ar:"مفترس",een:"The shark is a top predator.",ear:"القرش مفترس من الدرجة الأولى.",t:"mastery",u:2},
{w:"migration",c:"A2",s:"CEFR-J",p:"noun",ar:"هجرة",een:"Bird migration happens in autumn.",ear:"تحدث هجرة الطيور في الخريف.",t:"mastery",u:2},
{w:"species",c:"A2",s:"CEFR-J",p:"noun",ar:"أنواع",een:"Many species live in the ocean.",ear:"تعيش أنواع كثيرة في المحيط.",t:"mastery",u:2},
{w:"oxygen",c:"A2",s:"NGSL",p:"noun",ar:"أكسجين",een:"Fish need oxygen to live.",ear:"تحتاج الأسماك للأكسجين لتعيش.",t:"mastery",u:2},
{w:"pollution",c:"A2",s:"CEFR-J",p:"noun",ar:"تلوث",een:"Pollution kills many fish.",ear:"التلوث يقتل أسماكاً كثيرة.",t:"mastery",u:2},
{w:"habitat",c:"A2",s:"CEFR-J",p:"noun",ar:"موطن",een:"The sea is their habitat.",ear:"البحر هو موطنهم.",t:"mastery",u:2},
{w:"vast",c:"A2",s:"NGSL",p:"adjective",ar:"شاسع",een:"The ocean is vast and blue.",ear:"المحيط شاسع وأزرق.",t:"mastery",u:2},
{w:"extinct",c:"A2",s:"NGSL",p:"adjective",ar:"منقرض",een:"Some fish are almost extinct.",ear:"بعض الأسماك شبه منقرضة.",t:"mastery",u:2},
{w:"absorb",c:"A2",s:"NGSL",p:"verb",ar:"يمتص",een:"The ocean absorbs heat from the sun.",ear:"يمتص المحيط الحرارة من الشمس.",t:"mastery",u:2},

// ===== UNIT 3: Space Exploration =====
{w:"planet",c:"A1",s:"CEFR-J",p:"noun",ar:"كوكب",een:"Earth is our planet.",ear:"الأرض هي كوكبنا.",t:"core",u:3},
{w:"star",c:"A1",s:"CEFR-J",p:"noun",ar:"نجمة",een:"I can see a star at night.",ear:"أستطيع رؤية نجمة في الليل.",t:"core",u:3},
{w:"moon",c:"A1",s:"CEFR-J",p:"noun",ar:"قمر",een:"The moon is bright tonight.",ear:"القمر مضيء الليلة.",t:"core",u:3},
{w:"earth",c:"A1",s:"CEFR-J",p:"noun",ar:"أرض",een:"Earth is the third planet.",ear:"الأرض هي الكوكب الثالث.",t:"core",u:3},
{w:"rocket",c:"A1",s:"CEFR-J",p:"noun",ar:"صاروخ",een:"The rocket flew into space.",ear:"طار الصاروخ إلى الفضاء.",t:"core",u:3},
{w:"astronaut",c:"A2",s:"CEFR-J",p:"noun",ar:"رائد فضاء",een:"The astronaut went to the moon.",ear:"ذهب رائد الفضاء إلى القمر.",t:"core",u:3},
{w:"space",c:"A1",s:"CEFR-J",p:"noun",ar:"فضاء",een:"Space is very dark and big.",ear:"الفضاء مظلم وكبير جداً.",t:"core",u:3},
{w:"satellite",c:"A2",s:"CEFR-J",p:"noun",ar:"قمر صناعي",een:"The satellite goes around Earth.",ear:"يدور القمر الصناعي حول الأرض.",t:"core",u:3},
{w:"telescope",c:"A2",s:"CEFR-J",p:"noun",ar:"تلسكوب",een:"He looks at stars with a telescope.",ear:"ينظر إلى النجوم بالتلسكوب.",t:"core",u:3},
{w:"gravity",c:"A2",s:"CEFR-J",p:"noun",ar:"جاذبية",een:"Gravity keeps us on the ground.",ear:"الجاذبية تبقينا على الأرض.",t:"core",u:3},
{w:"orbit",c:"A2",s:"CEFR-J",p:"verb",ar:"يدور",een:"The moon orbits the Earth.",ear:"يدور القمر حول الأرض.",t:"core",u:3},
{w:"distant",c:"A2",s:"CEFR-J",p:"adjective",ar:"بعيد",een:"Stars are very distant from us.",ear:"النجوم بعيدة جداً عنا.",t:"core",u:3},
{w:"tiny",c:"A1",s:"CEFR-J",p:"adjective",ar:"صغير جداً",een:"Stars look tiny from Earth.",ear:"تبدو النجوم صغيرة جداً من الأرض.",t:"core",u:3},
{w:"bright",c:"A1",s:"CEFR-J",p:"adjective",ar:"ساطع",een:"The star is very bright.",ear:"النجمة ساطعة جداً.",t:"core",u:3},
{w:"scientist",c:"A1",s:"CEFR-J",p:"noun",ar:"عالم",een:"The scientist studies space.",ear:"يدرس العالم الفضاء.",t:"core",u:3},
{w:"universe",c:"A2",s:"CEFR-J",p:"noun",ar:"كون",een:"The universe is very big.",ear:"الكون كبير جداً.",t:"core",u:3},
{w:"galaxy",c:"A2",s:"CEFR-J",p:"noun",ar:"مجرة",een:"Our galaxy is the Milky Way.",ear:"مجرتنا هي درب التبانة.",t:"extended",u:3},
{w:"comet",c:"A2",s:"NGSL",p:"noun",ar:"مذنب",een:"The comet has a long tail.",ear:"للمذنب ذيل طويل.",t:"extended",u:3},
{w:"astronomer",c:"A2",s:"NGSL",p:"noun",ar:"عالم فلك",een:"The astronomer studies stars.",ear:"يدرس عالم الفلك النجوم.",t:"extended",u:3},
{w:"mission",c:"A2",s:"CEFR-J",p:"noun",ar:"مهمة",een:"The space mission took three days.",ear:"استغرقت المهمة الفضائية ثلاثة أيام.",t:"extended",u:3},
{w:"atmosphere",c:"A2",s:"CEFR-J",p:"noun",ar:"غلاف جوي",een:"Earth has a thick atmosphere.",ear:"للأرض غلاف جوي سميك.",t:"extended",u:3},
{w:"solar",c:"A2",s:"CEFR-J",p:"adjective",ar:"شمسي",een:"We live in the solar system.",ear:"نعيش في النظام الشمسي.",t:"extended",u:3},
{w:"weightless",c:"A2",s:"NGSL",p:"adjective",ar:"عديم الوزن",een:"Astronauts feel weightless in space.",ear:"يشعر رواد الفضاء بانعدام الوزن.",t:"extended",u:3},
{w:"mysterious",c:"A2",s:"CEFR-J",p:"adjective",ar:"غامض",een:"Space is mysterious and beautiful.",ear:"الفضاء غامض وجميل.",t:"extended",u:3},
{w:"rotate",c:"A2",s:"CEFR-J",p:"verb",ar:"يدور حول نفسه",een:"The Earth rotates every 24 hours.",ear:"تدور الأرض كل 24 ساعة.",t:"extended",u:3},
{w:"observe",c:"A2",s:"CEFR-J",p:"verb",ar:"يراقب",een:"Scientists observe the sky at night.",ear:"يراقب العلماء السماء ليلاً.",t:"extended",u:3},
{w:"expand",c:"A2",s:"CEFR-J",p:"verb",ar:"يتوسع",een:"The universe continues to expand.",ear:"يستمر الكون في التوسع.",t:"extended",u:3},
{w:"scientific",c:"A2",s:"CEFR-J",p:"adjective",ar:"علمي",een:"This is a scientific fact.",ear:"هذه حقيقة علمية.",t:"extended",u:3},
{w:"visible",c:"A2",s:"CEFR-J",p:"adjective",ar:"مرئي",een:"The moon is visible tonight.",ear:"القمر مرئي الليلة.",t:"extended",u:3},
{w:"constellation",c:"A2",s:"NGSL",p:"noun",ar:"كوكبة",een:"I can see one constellation.",ear:"أستطيع رؤية كوكبة واحدة.",t:"mastery",u:3},
{w:"meteor",c:"A2",s:"NGSL",p:"noun",ar:"نيزك",een:"A meteor fell from the sky.",ear:"سقط نيزك من السماء.",t:"mastery",u:3},
{w:"spacecraft",c:"A2",s:"NGSL",p:"noun",ar:"مركبة فضائية",een:"The spacecraft reached Mars.",ear:"وصلت المركبة الفضائية إلى المريخ.",t:"mastery",u:3},
{w:"crater",c:"A2",s:"NGSL",p:"noun",ar:"فوهة",een:"The moon has a big crater.",ear:"للقمر فوهة كبيرة.",t:"mastery",u:3},
{w:"infinite",c:"A2",s:"NGSL",p:"adjective",ar:"لا نهائي",een:"Space seems infinite.",ear:"يبدو الفضاء لا نهائياً.",t:"mastery",u:3},
{w:"calculate",c:"A2",s:"CEFR-J",p:"verb",ar:"يحسب",een:"Scientists calculate the distance.",ear:"يحسب العلماء المسافة.",t:"mastery",u:3},
{w:"transmit",c:"A2",s:"NGSL",p:"verb",ar:"يُرسل",een:"The satellite transmits signals.",ear:"يرسل القمر الصناعي إشارات.",t:"mastery",u:3},
{w:"discovery",c:"A2",s:"CEFR-J",p:"noun",ar:"اكتشاف",een:"It was a great discovery.",ear:"كان اكتشافاً عظيماً.",t:"mastery",u:3},
{w:"existence",c:"A2",s:"NGSL",p:"noun",ar:"وجود",een:"They proved the existence of water.",ear:"أثبتوا وجود الماء.",t:"mastery",u:3},
{w:"orbit",c:"A2",s:"CEFR-J",p:"noun",ar:"مدار",een:"The satellite is in orbit.",ear:"القمر الصناعي في مداره.",t:"mastery",u:3},

// ===== UNIT 4: Music & Art =====
{w:"instrument",c:"A1",s:"CEFR-J",p:"noun",ar:"آلة موسيقية",een:"She plays a musical instrument.",ear:"تعزف على آلة موسيقية.",t:"core",u:4},
{w:"guitar",c:"A1",s:"CEFR-J",p:"noun",ar:"جيتار",een:"He plays the guitar well.",ear:"يعزف الجيتار جيداً.",t:"core",u:4},
{w:"drum",c:"A1",s:"CEFR-J",p:"noun",ar:"طبل",een:"The drum is very loud.",ear:"الطبل صوته عالٍ جداً.",t:"core",u:4},
{w:"piano",c:"A1",s:"CEFR-J",p:"noun",ar:"بيانو",een:"She practices piano every day.",ear:"تتدرب على البيانو كل يوم.",t:"core",u:4},
{w:"artist",c:"A1",s:"CEFR-J",p:"noun",ar:"فنان",een:"The artist painted a picture.",ear:"رسم الفنان لوحة.",t:"core",u:4},
{w:"singer",c:"A1",s:"CEFR-J",p:"noun",ar:"مغني",een:"The singer has a nice voice.",ear:"صوت المغني جميل.",t:"core",u:4},
{w:"concert",c:"A2",s:"CEFR-J",p:"noun",ar:"حفل موسيقي",een:"We went to a concert.",ear:"ذهبنا إلى حفل موسيقي.",t:"core",u:4},
{w:"painting",c:"A1",s:"CEFR-J",p:"noun",ar:"لوحة",een:"The painting is very beautiful.",ear:"اللوحة جميلة جداً.",t:"core",u:4},
{w:"rhythm",c:"A2",s:"CEFR-J",p:"noun",ar:"إيقاع",een:"The rhythm is fast.",ear:"الإيقاع سريع.",t:"core",u:4},
{w:"melody",c:"A2",s:"CEFR-J",p:"noun",ar:"لحن",een:"The melody is very pretty.",ear:"اللحن جميل جداً.",t:"core",u:4},
{w:"perform",c:"A2",s:"CEFR-J",p:"verb",ar:"يؤدي",een:"They perform on the stage.",ear:"يؤدون على المسرح.",t:"core",u:4},
{w:"compose",c:"A2",s:"CEFR-J",p:"verb",ar:"يؤلف",een:"He composed a new song.",ear:"ألف أغنية جديدة.",t:"core",u:4},
{w:"record",c:"A2",s:"CEFR-J",p:"verb",ar:"يسجل",een:"She recorded a new album.",ear:"سجلت ألبوماً جديداً.",t:"core",u:4},
{w:"quiet",c:"A1",s:"CEFR-J",p:"adjective",ar:"هادئ",een:"The room is very quiet.",ear:"الغرفة هادئة جداً.",t:"core",u:4},
{w:"voice",c:"A1",s:"CEFR-J",p:"noun",ar:"صوت",een:"She has a beautiful voice.",ear:"لديها صوت جميل.",t:"core",u:4},
{w:"band",c:"A1",s:"CEFR-J",p:"noun",ar:"فرقة موسيقية",een:"The band plays every Friday.",ear:"تعزف الفرقة كل جمعة.",t:"core",u:4},
{w:"stage",c:"A2",s:"CEFR-J",p:"noun",ar:"مسرح",een:"The band is on the stage.",ear:"الفرقة على المسرح.",t:"extended",u:4},
{w:"choir",c:"A2",s:"NGSL",p:"noun",ar:"جوقة",een:"The choir sings every Friday.",ear:"تغني الجوقة كل جمعة.",t:"extended",u:4},
{w:"sculpture",c:"A2",s:"CEFR-J",p:"noun",ar:"تمثال",een:"The sculpture is made of stone.",ear:"التمثال مصنوع من الحجر.",t:"extended",u:4},
{w:"exhibition",c:"A2",s:"CEFR-J",p:"noun",ar:"معرض",een:"We visited an art exhibition.",ear:"زرنا معرضاً فنياً.",t:"extended",u:4},
{w:"audience",c:"A2",s:"CEFR-J",p:"noun",ar:"جمهور",een:"The audience clapped loudly.",ear:"صفق الجمهور بصوت عالٍ.",t:"extended",u:4},
{w:"gallery",c:"A2",s:"CEFR-J",p:"noun",ar:"معرض فني",een:"We went to an art gallery.",ear:"ذهبنا إلى معرض فني.",t:"extended",u:4},
{w:"sketch",c:"A2",s:"CEFR-J",p:"noun",ar:"رسم تخطيطي",een:"He made a quick sketch.",ear:"رسم رسماً تخطيطياً سريعاً.",t:"extended",u:4},
{w:"classical",c:"A2",s:"CEFR-J",p:"adjective",ar:"كلاسيكي",een:"She likes classical music.",ear:"تحب الموسيقى الكلاسيكية.",t:"extended",u:4},
{w:"visual",c:"A2",s:"CEFR-J",p:"adjective",ar:"بصري",een:"This is a visual art form.",ear:"هذا شكل من الفن البصري.",t:"extended",u:4},
{w:"express",c:"A2",s:"CEFR-J",p:"verb",ar:"يعبر",een:"Art helps us express feelings.",ear:"يساعدنا الفن على التعبير.",t:"extended",u:4},
{w:"rehearse",c:"A2",s:"NGSL",p:"verb",ar:"يتمرن",een:"The band rehearses every week.",ear:"تتمرن الفرقة كل أسبوع.",t:"extended",u:4},
{w:"applaud",c:"A2",s:"NGSL",p:"verb",ar:"يُصفق",een:"The crowd applauded the singer.",ear:"صفق الجمهور للمغني.",t:"extended",u:4},
{w:"emotional",c:"A2",s:"CEFR-J",p:"adjective",ar:"عاطفي",een:"The song is very emotional.",ear:"الأغنية عاطفية جداً.",t:"extended",u:4},
{w:"tune",c:"A2",s:"CEFR-J",p:"noun",ar:"نغمة",een:"I know this tune very well.",ear:"أعرف هذه النغمة جيداً.",t:"extended",u:4},
{w:"masterpiece",c:"A2",s:"NGSL",p:"noun",ar:"تحفة فنية",een:"This painting is a masterpiece.",ear:"هذه اللوحة تحفة فنية.",t:"mastery",u:4},
{w:"harmony",c:"A2",s:"NGSL",p:"noun",ar:"انسجام",een:"The voices sang in harmony.",ear:"غنت الأصوات بانسجام.",t:"mastery",u:4},
{w:"composer",c:"A2",s:"NGSL",p:"noun",ar:"ملحن",een:"The composer wrote the symphony.",ear:"ألف الملحن السيمفونية.",t:"mastery",u:4},
{w:"lyrics",c:"A2",s:"NGSL",p:"noun",ar:"كلمات أغنية",een:"I love the lyrics of this song.",ear:"أحب كلمات هذه الأغنية.",t:"mastery",u:4},
{w:"abstract",c:"A2",s:"NGSL",p:"adjective",ar:"تجريدي",een:"This is abstract art.",ear:"هذا فن تجريدي.",t:"mastery",u:4},
{w:"original",c:"A2",s:"CEFR-J",p:"adjective",ar:"أصلي",een:"Is this the original painting?",ear:"هل هذه اللوحة الأصلية؟",t:"mastery",u:4},
{w:"illustrate",c:"A2",s:"NGSL",p:"verb",ar:"يرسم توضيحياً",een:"She illustrates children books.",ear:"ترسم توضيحات لكتب الأطفال.",t:"mastery",u:4},
{w:"portray",c:"A2",s:"NGSL",p:"verb",ar:"يُصور",een:"The painting portrays a woman.",ear:"تصور اللوحة امرأة.",t:"mastery",u:4},
{w:"creativity",c:"A2",s:"CEFR-J",p:"noun",ar:"إبداع",een:"Art needs a lot of creativity.",ear:"يحتاج الفن إلى الكثير من الإبداع.",t:"mastery",u:4},
{w:"talent",c:"A2",s:"CEFR-J",p:"noun",ar:"موهبة",een:"She has great musical talent.",ear:"لديها موهبة موسيقية كبيرة.",t:"mastery",u:4},

// ===== UNIT 5: Famous Places =====
{w:"tower",c:"A1",s:"CEFR-J",p:"noun",ar:"برج",een:"The tower is very tall.",ear:"البرج مرتفع جداً.",t:"core",u:5},
{w:"museum",c:"A1",s:"CEFR-J",p:"noun",ar:"متحف",een:"We visited the museum today.",ear:"زرنا المتحف اليوم.",t:"core",u:5},
{w:"castle",c:"A1",s:"CEFR-J",p:"noun",ar:"قلعة",een:"The castle is on the hill.",ear:"القلعة على التل.",t:"core",u:5},
{w:"monument",c:"A2",s:"CEFR-J",p:"noun",ar:"نصب تذكاري",een:"The monument is very old.",ear:"النصب التذكاري قديم جداً.",t:"core",u:5},
{w:"statue",c:"A2",s:"CEFR-J",p:"noun",ar:"تمثال",een:"The statue is made of stone.",ear:"التمثال مصنوع من الحجر.",t:"core",u:5},
{w:"temple",c:"A2",s:"CEFR-J",p:"noun",ar:"معبد",een:"The temple is very beautiful.",ear:"المعبد جميل جداً.",t:"core",u:5},
{w:"palace",c:"A1",s:"CEFR-J",p:"noun",ar:"قصر",een:"The king lives in a palace.",ear:"يعيش الملك في قصر.",t:"core",u:5},
{w:"pyramid",c:"A2",s:"CEFR-J",p:"noun",ar:"هرم",een:"The pyramid is in Egypt.",ear:"الهرم في مصر.",t:"core",u:5},
{w:"landmark",c:"A2",s:"CEFR-J",p:"noun",ar:"معلم بارز",een:"The bridge is a famous landmark.",ear:"الجسر معلم بارز شهير.",t:"core",u:5},
{w:"wonder",c:"A2",s:"CEFR-J",p:"noun",ar:"عجيبة",een:"It is one of the seven wonders.",ear:"إنها إحدى العجائب السبع.",t:"core",u:5},
{w:"guide",c:"A1",s:"CEFR-J",p:"noun",ar:"مرشد",een:"The guide showed us the city.",ear:"أرانا المرشد المدينة.",t:"core",u:5},
{w:"entrance",c:"A2",s:"CEFR-J",p:"noun",ar:"مدخل",een:"The entrance is on the left.",ear:"المدخل على اليسار.",t:"core",u:5},
{w:"ancient",c:"A2",s:"CEFR-J",p:"adjective",ar:"قديم",een:"This is an ancient building.",ear:"هذا مبنى قديم.",t:"core",u:5},
{w:"historic",c:"A2",s:"CEFR-J",p:"adjective",ar:"تاريخي",een:"This is a historic place.",ear:"هذا مكان تاريخي.",t:"core",u:5},
{w:"stunning",c:"A2",s:"CEFR-J",p:"adjective",ar:"مذهل",een:"The view is stunning.",ear:"المنظر مذهل.",t:"core",u:5},
{w:"build",c:"A1",s:"CEFR-J",p:"verb",ar:"يبني",een:"They build houses with stone.",ear:"يبنون البيوت بالحجر.",t:"core",u:5},
{w:"cathedral",c:"A2",s:"CEFR-J",p:"noun",ar:"كاتدرائية",een:"The cathedral is very large.",ear:"الكاتدرائية كبيرة جداً.",t:"extended",u:5},
{w:"fortress",c:"A2",s:"NGSL",p:"noun",ar:"حصن",een:"The fortress protected the city.",ear:"حمى الحصن المدينة.",t:"extended",u:5},
{w:"ruins",c:"A2",s:"CEFR-J",p:"noun",ar:"أطلال",een:"We visited the old ruins.",ear:"زرنا الأطلال القديمة.",t:"extended",u:5},
{w:"architecture",c:"A2",s:"CEFR-J",p:"noun",ar:"هندسة معمارية",een:"The architecture is amazing.",ear:"الهندسة المعمارية مذهلة.",t:"extended",u:5},
{w:"column",c:"A2",s:"CEFR-J",p:"noun",ar:"عمود",een:"The column is made of marble.",ear:"العمود مصنوع من الرخام.",t:"extended",u:5},
{w:"dome",c:"A2",s:"NGSL",p:"noun",ar:"قبة",een:"The dome is gold in color.",ear:"القبة ذهبية اللون.",t:"extended",u:5},
{w:"arch",c:"A2",s:"NGSL",p:"noun",ar:"قوس",een:"The arch is above the door.",ear:"القوس فوق الباب.",t:"extended",u:5},
{w:"construct",c:"A2",s:"CEFR-J",p:"verb",ar:"يشيد",een:"They constructed the wall in a year.",ear:"شيدوا الجدار في سنة.",t:"extended",u:5},
{w:"restore",c:"A2",s:"CEFR-J",p:"verb",ar:"يرمم",een:"They restored the old building.",ear:"رمموا المبنى القديم.",t:"extended",u:5},
{w:"surround",c:"A2",s:"CEFR-J",p:"verb",ar:"يحيط",een:"Trees surround the castle.",ear:"الأشجار تحيط بالقلعة.",t:"extended",u:5},
{w:"magnificent",c:"A2",s:"CEFR-J",p:"adjective",ar:"رائع",een:"The palace is magnificent.",ear:"القصر رائع.",t:"extended",u:5},
{w:"massive",c:"A2",s:"CEFR-J",p:"adjective",ar:"ضخم",een:"The wall is massive.",ear:"الجدار ضخم.",t:"extended",u:5},
{w:"iconic",c:"A2",s:"NGSL",p:"adjective",ar:"أيقوني",een:"The tower is an iconic symbol.",ear:"البرج رمز أيقوني.",t:"extended",u:5},
{w:"sacred",c:"A2",s:"CEFR-J",p:"adjective",ar:"مقدس",een:"The temple is a sacred site.",ear:"المعبد موقع مقدس.",t:"extended",u:5},
{w:"civilization",c:"A2",s:"CEFR-J",p:"noun",ar:"حضارة",een:"The Egyptian civilization is old.",ear:"الحضارة المصرية قديمة.",t:"mastery",u:5},
{w:"heritage",c:"A2",s:"CEFR-J",p:"noun",ar:"تراث",een:"This is a world heritage site.",ear:"هذا موقع تراث عالمي.",t:"mastery",u:5},
{w:"inscription",c:"A2",s:"NGSL",p:"noun",ar:"نقش",een:"The inscription is in Arabic.",ear:"النقش باللغة العربية.",t:"mastery",u:5},
{w:"excavate",c:"A2",s:"NGSL",p:"verb",ar:"ينقب",een:"They excavated old walls.",ear:"نقبوا عن جدران قديمة.",t:"mastery",u:5},
{w:"preserve",c:"A2",s:"CEFR-J",p:"verb",ar:"يحافظ",een:"We must preserve this building.",ear:"يجب أن نحافظ على هذا المبنى.",t:"mastery",u:5},
{w:"archaeological",c:"A2",s:"NGSL",p:"adjective",ar:"أثري",een:"This is an archaeological site.",ear:"هذا موقع أثري.",t:"mastery",u:5},
{w:"majestic",c:"A2",s:"NGSL",p:"adjective",ar:"مهيب",een:"The mountain looks majestic.",ear:"يبدو الجبل مهيباً.",t:"mastery",u:5},
{w:"marble",c:"A2",s:"NGSL",p:"noun",ar:"رخام",een:"The floor is made of marble.",ear:"الأرضية مصنوعة من الرخام.",t:"mastery",u:5},
{w:"renovation",c:"A2",s:"NGSL",p:"noun",ar:"تجديد",een:"The renovation took two years.",ear:"استغرق التجديد سنتين.",t:"mastery",u:5},
{w:"ancient",c:"A2",s:"CEFR-J",p:"adjective",ar:"عريق",een:"The city has ancient history.",ear:"المدينة ذات تاريخ عريق.",t:"mastery",u:5},

// ===== UNIT 6: Inventions =====
{w:"invention",c:"A2",s:"CEFR-J",p:"noun",ar:"اختراع",een:"The car was a great invention.",ear:"كانت السيارة اختراعاً عظيماً.",t:"core",u:6},
{w:"machine",c:"A1",s:"CEFR-J",p:"noun",ar:"آلة",een:"The machine works very fast.",ear:"تعمل الآلة بسرعة كبيرة.",t:"core",u:6},
{w:"engine",c:"A2",s:"CEFR-J",p:"noun",ar:"محرك",een:"The engine makes the car move.",ear:"المحرك يجعل السيارة تتحرك.",t:"core",u:6},
{w:"electricity",c:"A2",s:"CEFR-J",p:"noun",ar:"كهرباء",een:"We use electricity every day.",ear:"نستخدم الكهرباء كل يوم.",t:"core",u:6},
{w:"battery",c:"A1",s:"CEFR-J",p:"noun",ar:"بطارية",een:"The battery is empty.",ear:"البطارية فارغة.",t:"core",u:6},
{w:"wheel",c:"A2",s:"CEFR-J",p:"noun",ar:"عجلة",een:"The wheel was invented long ago.",ear:"اختُرعت العجلة منذ زمن بعيد.",t:"core",u:6},
{w:"tool",c:"A1",s:"CEFR-J",p:"noun",ar:"أداة",een:"This tool is very useful.",ear:"هذه الأداة مفيدة جداً.",t:"core",u:6},
{w:"device",c:"A2",s:"CEFR-J",p:"noun",ar:"جهاز",een:"This device can take photos.",ear:"يمكن لهذا الجهاز التقاط الصور.",t:"core",u:6},
{w:"invent",c:"A2",s:"CEFR-J",p:"verb",ar:"يخترع",een:"He invented a new machine.",ear:"اخترع آلة جديدة.",t:"core",u:6},
{w:"design",c:"A2",s:"CEFR-J",p:"verb",ar:"يصمم",een:"She designed a new phone.",ear:"صممت هاتفاً جديداً.",t:"core",u:6},
{w:"build",c:"A1",s:"CEFR-J",p:"verb",ar:"يبني",een:"They build robots at school.",ear:"يبنون الروبوتات في المدرسة.",t:"core",u:6},
{w:"solve",c:"A2",s:"CEFR-J",p:"verb",ar:"يحل",een:"We can solve this problem.",ear:"يمكننا حل هذه المشكلة.",t:"core",u:6},
{w:"modern",c:"A2",s:"CEFR-J",p:"adjective",ar:"حديث",een:"This is a modern invention.",ear:"هذا اختراع حديث.",t:"core",u:6},
{w:"automatic",c:"A2",s:"CEFR-J",p:"adjective",ar:"آلي",een:"The door is automatic.",ear:"الباب آلي.",t:"core",u:6},
{w:"electronic",c:"A2",s:"CEFR-J",p:"adjective",ar:"إلكتروني",een:"I bought an electronic device.",ear:"اشتريت جهازاً إلكترونياً.",t:"core",u:6},
{w:"powerful",c:"A2",s:"CEFR-J",p:"adjective",ar:"قوي",een:"The engine is very powerful.",ear:"المحرك قوي جداً.",t:"core",u:6},
{w:"laboratory",c:"A2",s:"CEFR-J",p:"noun",ar:"مختبر",een:"He works in a laboratory.",ear:"يعمل في مختبر.",t:"extended",u:6},
{w:"patent",c:"A2",s:"NGSL",p:"noun",ar:"براءة اختراع",een:"He got a patent for his idea.",ear:"حصل على براءة اختراع لفكرته.",t:"extended",u:6},
{w:"prototype",c:"A2",s:"NGSL",p:"noun",ar:"نموذج أولي",een:"They made a prototype first.",ear:"صنعوا نموذجاً أولياً أولاً.",t:"extended",u:6},
{w:"switch",c:"A1",s:"CEFR-J",p:"noun",ar:"مفتاح",een:"Press the switch to start.",ear:"اضغط المفتاح للبدء.",t:"extended",u:6},
{w:"wire",c:"A2",s:"CEFR-J",p:"noun",ar:"سلك",een:"The wire connects the two parts.",ear:"السلك يربط الجزأين.",t:"extended",u:6},
{w:"signal",c:"A2",s:"CEFR-J",p:"noun",ar:"إشارة",een:"The signal is very strong.",ear:"الإشارة قوية جداً.",t:"extended",u:6},
{w:"replace",c:"A2",s:"CEFR-J",p:"verb",ar:"يستبدل",een:"We replaced the old machine.",ear:"استبدلنا الآلة القديمة.",t:"extended",u:6},
{w:"attach",c:"A2",s:"CEFR-J",p:"verb",ar:"يربط",een:"Attach the wire to the battery.",ear:"اربط السلك بالبطارية.",t:"extended",u:6},
{w:"operate",c:"A2",s:"CEFR-J",p:"verb",ar:"يشغل",een:"I can operate this machine.",ear:"أستطيع تشغيل هذه الآلة.",t:"extended",u:6},
{w:"efficient",c:"A2",s:"CEFR-J",p:"adjective",ar:"كفؤ",een:"This engine is very efficient.",ear:"هذا المحرك كفؤ جداً.",t:"extended",u:6},
{w:"portable",c:"A2",s:"CEFR-J",p:"adjective",ar:"محمول",een:"The device is small and portable.",ear:"الجهاز صغير ومحمول.",t:"extended",u:6},
{w:"wireless",c:"A2",s:"NGSL",p:"adjective",ar:"لاسلكي",een:"I have wireless headphones.",ear:"لدي سماعات لاسلكية.",t:"extended",u:6},
{w:"technical",c:"A2",s:"CEFR-J",p:"adjective",ar:"تقني",een:"This is a technical problem.",ear:"هذه مشكلة تقنية.",t:"extended",u:6},
{w:"manual",c:"A2",s:"CEFR-J",p:"adjective",ar:"يدوي",een:"This is a manual tool.",ear:"هذه أداة يدوية.",t:"extended",u:6},
{w:"revolution",c:"A2",s:"CEFR-J",p:"noun",ar:"ثورة",een:"It was a technology revolution.",ear:"كانت ثورة تكنولوجية.",t:"mastery",u:6},
{w:"breakthrough",c:"A2",s:"NGSL",p:"noun",ar:"اختراق",een:"It was a big breakthrough.",ear:"كان اختراقاً كبيراً.",t:"mastery",u:6},
{w:"innovation",c:"A2",s:"NGSL",p:"noun",ar:"ابتكار",een:"Innovation changes our lives.",ear:"يغير الابتكار حياتنا.",t:"mastery",u:6},
{w:"transform",c:"A2",s:"CEFR-J",p:"verb",ar:"يحول",een:"Technology transforms our world.",ear:"تحول التكنولوجيا عالمنا.",t:"mastery",u:6},
{w:"manufacture",c:"A2",s:"NGSL",p:"verb",ar:"يصنع",een:"They manufacture cars here.",ear:"يصنعون السيارات هنا.",t:"mastery",u:6},
{w:"automate",c:"A2",s:"NGSL",p:"verb",ar:"يؤتمت",een:"Robots automate many tasks.",ear:"تؤتمت الروبوتات مهاماً كثيرة.",t:"mastery",u:6},
{w:"mechanical",c:"A2",s:"CEFR-J",p:"adjective",ar:"ميكانيكي",een:"It is a mechanical system.",ear:"إنه نظام ميكانيكي.",t:"mastery",u:6},
{w:"genius",c:"A2",s:"NGSL",p:"noun",ar:"عبقري",een:"The inventor was a genius.",ear:"كان المخترع عبقرياً.",t:"mastery",u:6},
{w:"inventor",c:"A2",s:"CEFR-J",p:"noun",ar:"مخترع",een:"The inventor won an award.",ear:"فاز المخترع بجائزة.",t:"mastery",u:6},
{w:"remarkable",c:"A2",s:"CEFR-J",p:"adjective",ar:"ملفت",een:"This is a remarkable invention.",ear:"هذا اختراع ملفت.",t:"mastery",u:6},

// ===== UNIT 7: Sports Stars =====
{w:"champion",c:"A2",s:"CEFR-J",p:"noun",ar:"بطل",een:"He is the new champion.",ear:"هو البطل الجديد.",t:"core",u:7},
{w:"athlete",c:"A2",s:"CEFR-J",p:"noun",ar:"رياضي",een:"The athlete runs every day.",ear:"يركض الرياضي كل يوم.",t:"core",u:7},
{w:"medal",c:"A2",s:"CEFR-J",p:"noun",ar:"ميدالية",een:"She won a gold medal.",ear:"فازت بميدالية ذهبية.",t:"core",u:7},
{w:"coach",c:"A2",s:"CEFR-J",p:"noun",ar:"مدرب",een:"The coach trains the team.",ear:"يدرب المدرب الفريق.",t:"core",u:7},
{w:"stadium",c:"A2",s:"CEFR-J",p:"noun",ar:"ملعب",een:"The stadium is very big.",ear:"الملعب كبير جداً.",t:"core",u:7},
{w:"race",c:"A1",s:"CEFR-J",p:"noun",ar:"سباق",een:"He won the race.",ear:"فاز بالسباق.",t:"core",u:7},
{w:"goal",c:"A1",s:"CEFR-J",p:"noun",ar:"هدف",een:"He scored a goal.",ear:"سجل هدفاً.",t:"core",u:7},
{w:"match",c:"A1",s:"CEFR-J",p:"noun",ar:"مباراة",een:"The match starts at five.",ear:"تبدأ المباراة الساعة الخامسة.",t:"core",u:7},
{w:"score",c:"A1",s:"CEFR-J",p:"verb",ar:"يسجل",een:"She scored two goals.",ear:"سجلت هدفين.",t:"core",u:7},
{w:"win",c:"A1",s:"CEFR-J",p:"verb",ar:"يفوز",een:"Our team will win today.",ear:"سيفوز فريقنا اليوم.",t:"core",u:7},
{w:"lose",c:"A1",s:"CEFR-J",p:"verb",ar:"يخسر",een:"They lost the game.",ear:"خسروا المباراة.",t:"core",u:7},
{w:"kick",c:"A1",s:"CEFR-J",p:"verb",ar:"يركل",een:"He kicked the ball hard.",ear:"ركل الكرة بقوة.",t:"core",u:7},
{w:"throw",c:"A1",s:"CEFR-J",p:"verb",ar:"يرمي",een:"She threw the ball far.",ear:"رمت الكرة بعيداً.",t:"core",u:7},
{w:"catch",c:"A1",s:"CEFR-J",p:"verb",ar:"يمسك",een:"He can catch the ball.",ear:"يستطيع إمساك الكرة.",t:"core",u:7},
{w:"fit",c:"A1",s:"CEFR-J",p:"adjective",ar:"لائق بدنياً",een:"The athlete is very fit.",ear:"الرياضي لائق بدنياً جداً.",t:"core",u:7},
{w:"final",c:"A2",s:"CEFR-J",p:"adjective",ar:"نهائي",een:"This is the final match.",ear:"هذه المباراة النهائية.",t:"core",u:7},
{w:"tournament",c:"A2",s:"CEFR-J",p:"noun",ar:"بطولة",een:"The tournament is in May.",ear:"البطولة في مايو.",t:"extended",u:7},
{w:"opponent",c:"A2",s:"CEFR-J",p:"noun",ar:"خصم",een:"The opponent was very strong.",ear:"كان الخصم قوياً جداً.",t:"extended",u:7},
{w:"trophy",c:"A2",s:"NGSL",p:"noun",ar:"كأس",een:"The team won the trophy.",ear:"فاز الفريق بالكأس.",t:"extended",u:7},
{w:"referee",c:"A2",s:"NGSL",p:"noun",ar:"حكم",een:"The referee stopped the game.",ear:"أوقف الحكم المباراة.",t:"extended",u:7},
{w:"captain",c:"A2",s:"CEFR-J",p:"noun",ar:"قائد",een:"The captain leads the team.",ear:"يقود القائد الفريق.",t:"extended",u:7},
{w:"fan",c:"A1",s:"CEFR-J",p:"noun",ar:"مشجع",een:"The fan cheered loudly.",ear:"هتف المشجع بصوت عالٍ.",t:"extended",u:7},
{w:"defeat",c:"A2",s:"CEFR-J",p:"verb",ar:"يهزم",een:"They defeated the other team.",ear:"هزموا الفريق الآخر.",t:"extended",u:7},
{w:"sprint",c:"A2",s:"NGSL",p:"verb",ar:"يعدو بسرعة",een:"He sprints to the finish line.",ear:"يعدو بسرعة نحو خط النهاية.",t:"extended",u:7},
{w:"defend",c:"A2",s:"CEFR-J",p:"verb",ar:"يدافع",een:"The player defends the goal.",ear:"يدافع اللاعب عن المرمى.",t:"extended",u:7},
{w:"cheer",c:"A2",s:"CEFR-J",p:"verb",ar:"يشجع",een:"The fans cheer for the team.",ear:"يشجع المشجعون الفريق.",t:"extended",u:7},
{w:"competitive",c:"A2",s:"CEFR-J",p:"adjective",ar:"تنافسي",een:"The game was very competitive.",ear:"كانت المباراة تنافسية جداً.",t:"extended",u:7},
{w:"athletic",c:"A2",s:"NGSL",p:"adjective",ar:"رياضي",een:"He has an athletic body.",ear:"لديه جسم رياضي.",t:"extended",u:7},
{w:"professional",c:"A2",s:"CEFR-J",p:"adjective",ar:"محترف",een:"She is a professional player.",ear:"هي لاعبة محترفة.",t:"extended",u:7},
{w:"record",c:"A2",s:"CEFR-J",p:"noun",ar:"رقم قياسي",een:"He broke the world record.",ear:"حطم الرقم القياسي العالمي.",t:"extended",u:7},
{w:"determination",c:"A2",s:"NGSL",p:"noun",ar:"عزيمة",een:"She has great determination.",ear:"لديها عزيمة كبيرة.",t:"mastery",u:7},
{w:"endurance",c:"A2",s:"NGSL",p:"noun",ar:"تحمل",een:"Running needs endurance.",ear:"الجري يحتاج تحملاً.",t:"mastery",u:7},
{w:"strategy",c:"A2",s:"CEFR-J",p:"noun",ar:"استراتيجية",een:"The coach has a good strategy.",ear:"لدى المدرب استراتيجية جيدة.",t:"mastery",u:7},
{w:"legend",c:"A2",s:"CEFR-J",p:"noun",ar:"أسطورة",een:"He is a football legend.",ear:"هو أسطورة كرة القدم.",t:"mastery",u:7},
{w:"overcome",c:"A2",s:"CEFR-J",p:"verb",ar:"يتغلب على",een:"She overcame many challenges.",ear:"تغلبت على تحديات كثيرة.",t:"mastery",u:7},
{w:"achieve",c:"A2",s:"CEFR-J",p:"verb",ar:"يحقق",een:"He achieved his dream.",ear:"حقق حلمه.",t:"mastery",u:7},
{w:"retire",c:"A2",s:"CEFR-J",p:"verb",ar:"يتقاعد",een:"The player will retire soon.",ear:"سيتقاعد اللاعب قريباً.",t:"mastery",u:7},
{w:"inspire",c:"A2",s:"CEFR-J",p:"verb",ar:"يلهم",een:"Champions inspire young players.",ear:"يلهم الأبطال اللاعبين الصغار.",t:"mastery",u:7},
{w:"dedication",c:"A2",s:"NGSL",p:"noun",ar:"تفاني",een:"Success needs dedication.",ear:"يحتاج النجاح إلى تفانٍ.",t:"mastery",u:7},
{w:"sportsmanship",c:"A2",s:"NGSL",p:"noun",ar:"روح رياضية",een:"He showed great sportsmanship.",ear:"أظهر روحاً رياضية عالية.",t:"mastery",u:7},

// ===== UNIT 8: Ancient Civilizations =====
{w:"king",c:"A1",s:"CEFR-J",p:"noun",ar:"ملك",een:"The king ruled for many years.",ear:"حكم الملك لسنوات كثيرة.",t:"core",u:8},
{w:"queen",c:"A1",s:"CEFR-J",p:"noun",ar:"ملكة",een:"The queen wore a gold crown.",ear:"ارتدت الملكة تاجاً ذهبياً.",t:"core",u:8},
{w:"empire",c:"A2",s:"CEFR-J",p:"noun",ar:"إمبراطورية",een:"The empire was very large.",ear:"كانت الإمبراطورية كبيرة جداً.",t:"core",u:8},
{w:"warrior",c:"A2",s:"CEFR-J",p:"noun",ar:"محارب",een:"The warrior was very brave.",ear:"كان المحارب شجاعاً جداً.",t:"core",u:8},
{w:"treasure",c:"A2",s:"CEFR-J",p:"noun",ar:"كنز",een:"They found a treasure in the sand.",ear:"وجدوا كنزاً في الرمال.",t:"core",u:8},
{w:"tomb",c:"A2",s:"CEFR-J",p:"noun",ar:"قبر",een:"The tomb is underground.",ear:"القبر تحت الأرض.",t:"core",u:8},
{w:"weapon",c:"A2",s:"CEFR-J",p:"noun",ar:"سلاح",een:"The sword was an old weapon.",ear:"كان السيف سلاحاً قديماً.",t:"core",u:8},
{w:"trade",c:"A2",s:"CEFR-J",p:"noun",ar:"تجارة",een:"Trade was important for the city.",ear:"كانت التجارة مهمة للمدينة.",t:"core",u:8},
{w:"clay",c:"A2",s:"CEFR-J",p:"noun",ar:"طين",een:"They made pots from clay.",ear:"صنعوا الأواني من الطين.",t:"core",u:8},
{w:"scroll",c:"A2",s:"NGSL",p:"noun",ar:"لفافة",een:"The scroll has old writing.",ear:"اللفافة فيها كتابة قديمة.",t:"core",u:8},
{w:"conquer",c:"A2",s:"CEFR-J",p:"verb",ar:"يغزو",een:"The army conquered the land.",ear:"غزا الجيش الأرض.",t:"core",u:8},
{w:"rule",c:"A1",s:"CEFR-J",p:"verb",ar:"يحكم",een:"The king ruled the country.",ear:"حكم الملك البلاد.",t:"core",u:8},
{w:"worship",c:"A2",s:"CEFR-J",p:"verb",ar:"يعبد",een:"They worship in the temple.",ear:"يعبدون في المعبد.",t:"core",u:8},
{w:"ancient",c:"A2",s:"CEFR-J",p:"adjective",ar:"قديم جداً",een:"This is an ancient city.",ear:"هذه مدينة قديمة جداً.",t:"core",u:8},
{w:"mighty",c:"A2",s:"CEFR-J",p:"adjective",ar:"عظيم",een:"The army was mighty.",ear:"كان الجيش عظيماً.",t:"core",u:8},
{w:"royal",c:"A2",s:"CEFR-J",p:"adjective",ar:"ملكي",een:"This is the royal palace.",ear:"هذا هو القصر الملكي.",t:"core",u:8},
{w:"pharaoh",c:"A2",s:"NGSL",p:"noun",ar:"فرعون",een:"The pharaoh built the pyramid.",ear:"بنى الفرعون الهرم.",t:"extended",u:8},
{w:"dynasty",c:"A2",s:"NGSL",p:"noun",ar:"سلالة",een:"The dynasty lasted 200 years.",ear:"استمرت السلالة 200 سنة.",t:"extended",u:8},
{w:"merchant",c:"A2",s:"CEFR-J",p:"noun",ar:"تاجر",een:"The merchant sold silk.",ear:"باع التاجر الحرير.",t:"extended",u:8},
{w:"pottery",c:"A2",s:"NGSL",p:"noun",ar:"فخار",een:"They made beautiful pottery.",ear:"صنعوا فخاراً جميلاً.",t:"extended",u:8},
{w:"armor",c:"A2",s:"NGSL",p:"noun",ar:"درع",een:"The warrior wore heavy armor.",ear:"ارتدى المحارب درعاً ثقيلاً.",t:"extended",u:8},
{w:"chariot",c:"A2",s:"NGSL",p:"noun",ar:"عربة حربية",een:"The chariot was pulled by horses.",ear:"جرت الخيول العربة الحربية.",t:"extended",u:8},
{w:"carve",c:"A2",s:"CEFR-J",p:"verb",ar:"ينحت",een:"They carved statues from stone.",ear:"نحتوا تماثيل من الحجر.",t:"extended",u:8},
{w:"bury",c:"A2",s:"CEFR-J",p:"verb",ar:"يدفن",een:"They buried the treasure.",ear:"دفنوا الكنز.",t:"extended",u:8},
{w:"invade",c:"A2",s:"CEFR-J",p:"verb",ar:"يغزو",een:"The army invaded the city.",ear:"غزا الجيش المدينة.",t:"extended",u:8},
{w:"wealthy",c:"A2",s:"CEFR-J",p:"adjective",ar:"ثري",een:"The merchant was wealthy.",ear:"كان التاجر ثرياً.",t:"extended",u:8},
{w:"golden",c:"A1",s:"CEFR-J",p:"adjective",ar:"ذهبي",een:"The mask was golden.",ear:"كان القناع ذهبياً.",t:"extended",u:8},
{w:"mysterious",c:"A2",s:"CEFR-J",p:"adjective",ar:"غامض",een:"The tomb was mysterious.",ear:"كان القبر غامضاً.",t:"extended",u:8},
{w:"powerful",c:"A2",s:"CEFR-J",p:"adjective",ar:"قوي",een:"The empire was powerful.",ear:"كانت الإمبراطورية قوية.",t:"extended",u:8},
{w:"sacred",c:"A2",s:"CEFR-J",p:"adjective",ar:"مقدس",een:"The river was sacred to them.",ear:"كان النهر مقدساً لديهم.",t:"extended",u:8},
{w:"hieroglyph",c:"A2",s:"NGSL",p:"noun",ar:"هيروغليفية",een:"The wall has hieroglyphs.",ear:"الجدار عليه كتابة هيروغليفية.",t:"mastery",u:8},
{w:"archaeology",c:"A2",s:"NGSL",p:"noun",ar:"علم الآثار",een:"She studies archaeology.",ear:"تدرس علم الآثار.",t:"mastery",u:8},
{w:"mummy",c:"A2",s:"NGSL",p:"noun",ar:"مومياء",een:"The mummy is in the museum.",ear:"المومياء في المتحف.",t:"mastery",u:8},
{w:"legend",c:"A2",s:"CEFR-J",p:"noun",ar:"أسطورة",een:"There is a legend about the king.",ear:"هناك أسطورة عن الملك.",t:"mastery",u:8},
{w:"ruins",c:"A2",s:"CEFR-J",p:"noun",ar:"أطلال",een:"The ruins tell us about the past.",ear:"تخبرنا الأطلال عن الماضي.",t:"mastery",u:8},
{w:"decipher",c:"A2",s:"NGSL",p:"verb",ar:"يفك رموز",een:"They deciphered the old writing.",ear:"فكوا رموز الكتابة القديمة.",t:"mastery",u:8},
{w:"thrive",c:"A2",s:"NGSL",p:"verb",ar:"يزدهر",een:"The city thrived for centuries.",ear:"ازدهرت المدينة لقرون.",t:"mastery",u:8},
{w:"collapse",c:"A2",s:"CEFR-J",p:"verb",ar:"ينهار",een:"The empire collapsed in the end.",ear:"انهارت الإمبراطورية في النهاية.",t:"mastery",u:8},
{w:"legendary",c:"A2",s:"CEFR-J",p:"adjective",ar:"أسطوري",een:"The warrior became legendary.",ear:"أصبح المحارب أسطورياً.",t:"mastery",u:8},
{w:"prosperous",c:"A2",s:"NGSL",p:"adjective",ar:"مزدهر",een:"The kingdom was prosperous.",ear:"كانت المملكة مزدهرة.",t:"mastery",u:8},

// ===== UNIT 9: Photography =====
{w:"photograph",c:"A1",s:"CEFR-J",p:"noun",ar:"صورة فوتوغرافية",een:"This photograph is beautiful.",ear:"هذه الصورة الفوتوغرافية جميلة.",t:"core",u:9},
{w:"lens",c:"A2",s:"CEFR-J",p:"noun",ar:"عدسة",een:"The lens is very clear.",ear:"العدسة واضحة جداً.",t:"core",u:9},
{w:"flash",c:"A2",s:"CEFR-J",p:"noun",ar:"فلاش",een:"The flash was too bright.",ear:"كان الفلاش ساطعاً جداً.",t:"core",u:9},
{w:"focus",c:"A2",s:"CEFR-J",p:"verb",ar:"يركز",een:"Focus the camera on the bird.",ear:"ركز الكاميرا على الطائر.",t:"core",u:9},
{w:"shoot",c:"A2",s:"CEFR-J",p:"verb",ar:"يصور",een:"She shoots photos every day.",ear:"تصور كل يوم.",t:"core",u:9},
{w:"zoom",c:"A2",s:"CEFR-J",p:"verb",ar:"يقرب",een:"Zoom in to see the details.",ear:"قرب لترى التفاصيل.",t:"core",u:9},
{w:"angle",c:"A2",s:"CEFR-J",p:"noun",ar:"زاوية",een:"Take the photo from this angle.",ear:"التقط الصورة من هذه الزاوية.",t:"core",u:9},
{w:"background",c:"A2",s:"CEFR-J",p:"noun",ar:"خلفية",een:"The background is very nice.",ear:"الخلفية جميلة جداً.",t:"core",u:9},
{w:"portrait",c:"A2",s:"CEFR-J",p:"noun",ar:"صورة شخصية",een:"She took a family portrait.",ear:"التقطت صورة عائلية.",t:"core",u:9},
{w:"landscape",c:"A2",s:"CEFR-J",p:"noun",ar:"منظر طبيعي",een:"The landscape photo is amazing.",ear:"صورة المنظر الطبيعي مذهلة.",t:"core",u:9},
{w:"image",c:"A1",s:"CEFR-J",p:"noun",ar:"صورة",een:"The image is very sharp.",ear:"الصورة واضحة جداً.",t:"core",u:9},
{w:"filter",c:"A2",s:"CEFR-J",p:"noun",ar:"فلتر",een:"She added a filter to the photo.",ear:"أضافت فلتراً للصورة.",t:"core",u:9},
{w:"sharp",c:"A2",s:"CEFR-J",p:"adjective",ar:"حاد",een:"The photo is very sharp.",ear:"الصورة حادة جداً.",t:"core",u:9},
{w:"blurry",c:"A2",s:"NGSL",p:"adjective",ar:"ضبابي",een:"The photo is blurry.",ear:"الصورة ضبابية.",t:"core",u:9},
{w:"natural",c:"A1",s:"CEFR-J",p:"adjective",ar:"طبيعي",een:"The light looks natural.",ear:"يبدو الضوء طبيعياً.",t:"core",u:9},
{w:"digital",c:"A2",s:"CEFR-J",p:"adjective",ar:"رقمي",een:"I have a digital camera.",ear:"لدي كاميرا رقمية.",t:"core",u:9},
{w:"exposure",c:"A2",s:"NGSL",p:"noun",ar:"تعريض ضوئي",een:"The exposure was too long.",ear:"كان التعريض الضوئي طويلاً جداً.",t:"extended",u:9},
{w:"frame",c:"A2",s:"CEFR-J",p:"noun",ar:"إطار",een:"Put the photo in a frame.",ear:"ضع الصورة في إطار.",t:"extended",u:9},
{w:"shadow",c:"A2",s:"CEFR-J",p:"noun",ar:"ظل",een:"The shadow makes the photo nice.",ear:"يجعل الظل الصورة جميلة.",t:"extended",u:9},
{w:"contrast",c:"A2",s:"CEFR-J",p:"noun",ar:"تباين",een:"The contrast is very strong.",ear:"التباين قوي جداً.",t:"extended",u:9},
{w:"resolution",c:"A2",s:"NGSL",p:"noun",ar:"دقة",een:"The resolution is very high.",ear:"الدقة عالية جداً.",t:"extended",u:9},
{w:"tripod",c:"A2",s:"NGSL",p:"noun",ar:"حامل ثلاثي",een:"Put the camera on the tripod.",ear:"ضع الكاميرا على الحامل الثلاثي.",t:"extended",u:9},
{w:"crop",c:"A2",s:"CEFR-J",p:"verb",ar:"يقص",een:"Crop the photo to make it smaller.",ear:"قص الصورة لتصغيرها.",t:"extended",u:9},
{w:"edit",c:"A2",s:"CEFR-J",p:"verb",ar:"يعدل",een:"He edits photos on the computer.",ear:"يعدل الصور على الحاسوب.",t:"extended",u:9},
{w:"adjust",c:"A2",s:"CEFR-J",p:"verb",ar:"يضبط",een:"Adjust the brightness of the photo.",ear:"اضبط سطوع الصورة.",t:"extended",u:9},
{w:"vivid",c:"A2",s:"NGSL",p:"adjective",ar:"حي",een:"The colors are very vivid.",ear:"الألوان حية جداً.",t:"extended",u:9},
{w:"scenic",c:"A2",s:"NGSL",p:"adjective",ar:"خلاب",een:"The view is very scenic.",ear:"المنظر خلاب جداً.",t:"extended",u:9},
{w:"outdoor",c:"A2",s:"CEFR-J",p:"adjective",ar:"خارجي",een:"I prefer outdoor photography.",ear:"أفضل التصوير الخارجي.",t:"extended",u:9},
{w:"candid",c:"A2",s:"NGSL",p:"adjective",ar:"عفوي",een:"I like candid photos.",ear:"أحب الصور العفوية.",t:"extended",u:9},
{w:"composition",c:"A2",s:"CEFR-J",p:"noun",ar:"تكوين",een:"Good composition makes a good photo.",ear:"التكوين الجيد يصنع صورة جيدة.",t:"extended",u:9},
{w:"perspective",c:"A2",s:"CEFR-J",p:"noun",ar:"منظور",een:"Change your perspective.",ear:"غير منظورك.",t:"mastery",u:9},
{w:"monochrome",c:"A2",s:"NGSL",p:"adjective",ar:"أحادي اللون",een:"The photo is monochrome.",ear:"الصورة أحادية اللون.",t:"mastery",u:9},
{w:"silhouette",c:"A2",s:"NGSL",p:"noun",ar:"صورة ظلية",een:"The silhouette looks beautiful.",ear:"الصورة الظلية جميلة.",t:"mastery",u:9},
{w:"panorama",c:"A2",s:"NGSL",p:"noun",ar:"بانوراما",een:"He took a panorama photo.",ear:"التقط صورة بانورامية.",t:"mastery",u:9},
{w:"shutter",c:"A2",s:"NGSL",p:"noun",ar:"مصراع",een:"Press the shutter button.",ear:"اضغط زر المصراع.",t:"mastery",u:9},
{w:"overexpose",c:"A2",s:"NGSL",p:"verb",ar:"يعرض للضوء بإفراط",een:"Do not overexpose the photo.",ear:"لا تعرض الصورة للضوء بإفراط.",t:"mastery",u:9},
{w:"enhance",c:"A2",s:"CEFR-J",p:"verb",ar:"يحسن",een:"Filters enhance the photo.",ear:"تحسن الفلاتر الصورة.",t:"mastery",u:9},
{w:"illuminate",c:"A2",s:"NGSL",p:"verb",ar:"ينير",een:"The sun illuminates the scene.",ear:"تنير الشمس المشهد.",t:"mastery",u:9},
{w:"aesthetic",c:"A2",s:"NGSL",p:"adjective",ar:"جمالي",een:"The photo has an aesthetic feel.",ear:"للصورة إحساس جمالي.",t:"mastery",u:9},
{w:"vintage",c:"A2",s:"NGSL",p:"adjective",ar:"عتيق",een:"She likes the vintage style.",ear:"تحب الأسلوب العتيق.",t:"mastery",u:9},

// ===== UNIT 10: World Cuisines =====
{w:"dish",c:"A1",s:"CEFR-J",p:"noun",ar:"طبق",een:"This dish is very tasty.",ear:"هذا الطبق لذيذ جداً.",t:"core",u:10},
{w:"chef",c:"A2",s:"CEFR-J",p:"noun",ar:"طاهٍ",een:"The chef made a great meal.",ear:"أعد الطاهي وجبة رائعة.",t:"core",u:10},
{w:"flavor",c:"A2",s:"CEFR-J",p:"noun",ar:"نكهة",een:"The flavor is very good.",ear:"النكهة جيدة جداً.",t:"core",u:10},
{w:"sauce",c:"A2",s:"CEFR-J",p:"noun",ar:"صلصة",een:"Add sauce to the pasta.",ear:"أضف صلصة للمعكرونة.",t:"core",u:10},
{w:"grill",c:"A2",s:"CEFR-J",p:"verb",ar:"يشوي",een:"We grill meat on the fire.",ear:"نشوي اللحم على النار.",t:"core",u:10},
{w:"bake",c:"A1",s:"CEFR-J",p:"verb",ar:"يخبز",een:"She bakes bread every morning.",ear:"تخبز الخبز كل صباح.",t:"core",u:10},
{w:"boil",c:"A2",s:"CEFR-J",p:"verb",ar:"يغلي",een:"Boil the water first.",ear:"اغلِ الماء أولاً.",t:"core",u:10},
{w:"fry",c:"A1",s:"CEFR-J",p:"verb",ar:"يقلي",een:"She fried the chicken.",ear:"قلت الدجاج.",t:"core",u:10},
{w:"mix",c:"A1",s:"CEFR-J",p:"verb",ar:"يخلط",een:"Mix the ingredients together.",ear:"اخلط المكونات معاً.",t:"core",u:10},
{w:"stir",c:"A2",s:"CEFR-J",p:"verb",ar:"يحرك",een:"Stir the soup slowly.",ear:"حرك الحساء ببطء.",t:"core",u:10},
{w:"spicy",c:"A2",s:"CEFR-J",p:"adjective",ar:"حار",een:"This food is very spicy.",ear:"هذا الطعام حار جداً.",t:"core",u:10},
{w:"sour",c:"A2",s:"CEFR-J",p:"adjective",ar:"حامض",een:"The lemon is sour.",ear:"الليمون حامض.",t:"core",u:10},
{w:"bitter",c:"A2",s:"CEFR-J",p:"adjective",ar:"مر",een:"The coffee is very bitter.",ear:"القهوة مرة جداً.",t:"core",u:10},
{w:"raw",c:"A2",s:"CEFR-J",p:"adjective",ar:"نيء",een:"Do not eat raw meat.",ear:"لا تأكل اللحم النيء.",t:"core",u:10},
{w:"oven",c:"A1",s:"CEFR-J",p:"noun",ar:"فرن",een:"Put the cake in the oven.",ear:"ضع الكعكة في الفرن.",t:"core",u:10},
{w:"ingredient",c:"A2",s:"CEFR-J",p:"noun",ar:"مكون",een:"This recipe has five ingredients.",ear:"هذه الوصفة فيها خمسة مكونات.",t:"core",u:10},
{w:"cuisine",c:"A2",s:"CEFR-J",p:"noun",ar:"مطبخ",een:"I love Italian cuisine.",ear:"أحب المطبخ الإيطالي.",t:"extended",u:10},
{w:"appetizer",c:"A2",s:"NGSL",p:"noun",ar:"مقبلات",een:"We ordered an appetizer.",ear:"طلبنا مقبلات.",t:"extended",u:10},
{w:"portion",c:"A2",s:"CEFR-J",p:"noun",ar:"حصة",een:"The portion is very big.",ear:"الحصة كبيرة جداً.",t:"extended",u:10},
{w:"dough",c:"A2",s:"NGSL",p:"noun",ar:"عجين",een:"Roll the dough flat.",ear:"افرد العجين.",t:"extended",u:10},
{w:"herb",c:"A2",s:"CEFR-J",p:"noun",ar:"عشبة",een:"Add fresh herbs to the salad.",ear:"أضف أعشاباً طازجة للسلطة.",t:"extended",u:10},
{w:"roast",c:"A2",s:"CEFR-J",p:"verb",ar:"يحمص",een:"Roast the chicken for one hour.",ear:"حمص الدجاج لمدة ساعة.",t:"extended",u:10},
{w:"chop",c:"A2",s:"CEFR-J",p:"verb",ar:"يقطع",een:"Chop the onions into small pieces.",ear:"قطع البصل قطعاً صغيرة.",t:"extended",u:10},
{w:"marinate",c:"A2",s:"NGSL",p:"verb",ar:"ينقع",een:"Marinate the meat for two hours.",ear:"انقع اللحم لمدة ساعتين.",t:"extended",u:10},
{w:"garnish",c:"A2",s:"NGSL",p:"verb",ar:"يزين الطبق",een:"Garnish the dish with parsley.",ear:"زين الطبق بالبقدونس.",t:"extended",u:10},
{w:"authentic",c:"A2",s:"CEFR-J",p:"adjective",ar:"أصيل",een:"This is authentic Arabic food.",ear:"هذا طعام عربي أصيل.",t:"extended",u:10},
{w:"aromatic",c:"A2",s:"NGSL",p:"adjective",ar:"عطري",een:"The spices are very aromatic.",ear:"التوابل عطرية جداً.",t:"extended",u:10},
{w:"nutritious",c:"A2",s:"NGSL",p:"adjective",ar:"مغذي",een:"Vegetables are nutritious.",ear:"الخضروات مغذية.",t:"extended",u:10},
{w:"savory",c:"A2",s:"NGSL",p:"adjective",ar:"مالح ولذيذ",een:"I prefer savory food.",ear:"أفضل الطعام المالح واللذيذ.",t:"extended",u:10},
{w:"seasonal",c:"A2",s:"CEFR-J",p:"adjective",ar:"موسمي",een:"We use seasonal vegetables.",ear:"نستخدم خضروات موسمية.",t:"extended",u:10},
{w:"gastronomy",c:"A2",s:"NGSL",p:"noun",ar:"فن الطهي",een:"He studies gastronomy.",ear:"يدرس فن الطهي.",t:"mastery",u:10},
{w:"cuisine",c:"A2",s:"CEFR-J",p:"noun",ar:"فنون الطبخ",een:"Each country has its own cuisine.",ear:"لكل بلد فنون طبخ خاصة.",t:"mastery",u:10},
{w:"ferment",c:"A2",s:"NGSL",p:"verb",ar:"يخمر",een:"They ferment the milk to make cheese.",ear:"يخمرون الحليب لصنع الجبن.",t:"mastery",u:10},
{w:"infuse",c:"A2",s:"NGSL",p:"verb",ar:"ينقع بالنكهة",een:"Infuse the tea with mint.",ear:"انقع الشاي بالنعناع.",t:"mastery",u:10},
{w:"simmer",c:"A2",s:"NGSL",p:"verb",ar:"يطهي على نار هادئة",een:"Simmer the soup for ten minutes.",ear:"اطهِ الحساء على نار هادئة لعشر دقائق.",t:"mastery",u:10},
{w:"exquisite",c:"A2",s:"NGSL",p:"adjective",ar:"رفيع",een:"The taste is exquisite.",ear:"الطعم رفيع.",t:"mastery",u:10},
{w:"gourmet",c:"A2",s:"NGSL",p:"adjective",ar:"فاخر",een:"This is a gourmet restaurant.",ear:"هذا مطعم فاخر.",t:"mastery",u:10},
{w:"organic",c:"A2",s:"CEFR-J",p:"adjective",ar:"عضوي",een:"I buy organic vegetables.",ear:"أشتري خضروات عضوية.",t:"mastery",u:10},
{w:"texture",c:"A2",s:"CEFR-J",p:"noun",ar:"قوام",een:"The bread has a soft texture.",ear:"للخبز قوام ناعم.",t:"mastery",u:10},
{w:"aroma",c:"A2",s:"NGSL",p:"noun",ar:"رائحة زكية",een:"The aroma of coffee fills the room.",ear:"تملأ رائحة القهوة الغرفة.",t:"mastery",u:10},

// ===== UNIT 11: Social Media =====
{w:"account",c:"A1",s:"CEFR-J",p:"noun",ar:"حساب",een:"I have a new account.",ear:"لدي حساب جديد.",t:"core",u:11},
{w:"profile",c:"A2",s:"CEFR-J",p:"noun",ar:"ملف شخصي",een:"Update your profile picture.",ear:"حدث صورة ملفك الشخصي.",t:"core",u:11},
{w:"follower",c:"A2",s:"CEFR-J",p:"noun",ar:"متابع",een:"She has many followers.",ear:"لديها متابعون كثيرون.",t:"core",u:11},
{w:"content",c:"A2",s:"CEFR-J",p:"noun",ar:"محتوى",een:"The content is very useful.",ear:"المحتوى مفيد جداً.",t:"core",u:11},
{w:"notification",c:"A2",s:"CEFR-J",p:"noun",ar:"إشعار",een:"I got a new notification.",ear:"حصلت على إشعار جديد.",t:"core",u:11},
{w:"comment",c:"A1",s:"CEFR-J",p:"noun",ar:"تعليق",een:"She left a nice comment.",ear:"تركت تعليقاً لطيفاً.",t:"core",u:11},
{w:"hashtag",c:"A2",s:"NGSL",p:"noun",ar:"هاشتاغ",een:"Use a hashtag for the post.",ear:"استخدم هاشتاغاً للمنشور.",t:"core",u:11},
{w:"upload",c:"A2",s:"CEFR-J",p:"verb",ar:"يرفع",een:"Upload the photo to the site.",ear:"ارفع الصورة إلى الموقع.",t:"core",u:11},
{w:"follow",c:"A1",s:"CEFR-J",p:"verb",ar:"يتابع",een:"Follow me on social media.",ear:"تابعني على وسائل التواصل.",t:"core",u:11},
{w:"like",c:"A1",s:"CEFR-J",p:"verb",ar:"يعجب بـ",een:"Many people liked the photo.",ear:"أُعجب كثيرون بالصورة.",t:"core",u:11},
{w:"block",c:"A2",s:"CEFR-J",p:"verb",ar:"يحظر",een:"You can block rude people.",ear:"يمكنك حظر الأشخاص الوقحين.",t:"core",u:11},
{w:"reply",c:"A1",s:"CEFR-J",p:"verb",ar:"يرد",een:"Please reply to my message.",ear:"من فضلك رد على رسالتي.",t:"core",u:11},
{w:"viral",c:"A2",s:"NGSL",p:"adjective",ar:"منتشر",een:"The video went viral.",ear:"انتشر الفيديو بشكل واسع.",t:"core",u:11},
{w:"private",c:"A2",s:"CEFR-J",p:"adjective",ar:"خاص",een:"My account is private.",ear:"حسابي خاص.",t:"core",u:11},
{w:"public",c:"A1",s:"CEFR-J",p:"adjective",ar:"عام",een:"The post is public.",ear:"المنشور عام.",t:"core",u:11},
{w:"trending",c:"A2",s:"NGSL",p:"adjective",ar:"رائج",een:"This topic is trending now.",ear:"هذا الموضوع رائج الآن.",t:"core",u:11},
{w:"influencer",c:"A2",s:"NGSL",p:"noun",ar:"مؤثر",een:"The influencer has many fans.",ear:"المؤثر لديه معجبون كثيرون.",t:"extended",u:11},
{w:"algorithm",c:"A2",s:"NGSL",p:"noun",ar:"خوارزمية",een:"The algorithm shows popular posts.",ear:"تعرض الخوارزمية المنشورات الشعبية.",t:"extended",u:11},
{w:"platform",c:"A2",s:"CEFR-J",p:"noun",ar:"منصة",een:"This is a popular platform.",ear:"هذه منصة شعبية.",t:"extended",u:11},
{w:"privacy",c:"A2",s:"CEFR-J",p:"noun",ar:"خصوصية",een:"Privacy is very important.",ear:"الخصوصية مهمة جداً.",t:"extended",u:11},
{w:"feed",c:"A2",s:"CEFR-J",p:"noun",ar:"موجز أخبار",een:"I scroll through my feed.",ear:"أتصفح موجز الأخبار.",t:"extended",u:11},
{w:"stream",c:"A2",s:"CEFR-J",p:"verb",ar:"يبث مباشرة",een:"She streams live every Friday.",ear:"تبث مباشرة كل جمعة.",t:"extended",u:11},
{w:"subscribe",c:"A2",s:"CEFR-J",p:"verb",ar:"يشترك",een:"Subscribe to the channel.",ear:"اشترك في القناة.",t:"extended",u:11},
{w:"tag",c:"A2",s:"CEFR-J",p:"verb",ar:"يُشير إلى",een:"Tag me in the photo.",ear:"أشر إليّ في الصورة.",t:"extended",u:11},
{w:"unfollow",c:"A2",s:"NGSL",p:"verb",ar:"يلغي المتابعة",een:"I will unfollow that page.",ear:"سألغي متابعة تلك الصفحة.",t:"extended",u:11},
{w:"anonymous",c:"A2",s:"CEFR-J",p:"adjective",ar:"مجهول الهوية",een:"The comment was anonymous.",ear:"كان التعليق مجهول الهوية.",t:"extended",u:11},
{w:"interactive",c:"A2",s:"CEFR-J",p:"adjective",ar:"تفاعلي",een:"The website is very interactive.",ear:"الموقع تفاعلي جداً.",t:"extended",u:11},
{w:"addictive",c:"A2",s:"NGSL",p:"adjective",ar:"مسبب للإدمان",een:"Social media can be addictive.",ear:"وسائل التواصل يمكن أن تسبب الإدمان.",t:"extended",u:11},
{w:"cyberbullying",c:"A2",s:"NGSL",p:"noun",ar:"تنمر إلكتروني",een:"Cyberbullying is a big problem.",ear:"التنمر الإلكتروني مشكلة كبيرة.",t:"extended",u:11},
{w:"broadcast",c:"A2",s:"CEFR-J",p:"verb",ar:"يذيع",een:"They broadcast the news live.",ear:"يذيعون الأخبار مباشرة.",t:"extended",u:11},
{w:"misinformation",c:"A2",s:"NGSL",p:"noun",ar:"معلومات مضللة",een:"Be careful of misinformation.",ear:"احذر من المعلومات المضللة.",t:"mastery",u:11},
{w:"verification",c:"A2",s:"NGSL",p:"noun",ar:"توثيق",een:"Account verification is important.",ear:"توثيق الحساب مهم.",t:"mastery",u:11},
{w:"engagement",c:"A2",s:"NGSL",p:"noun",ar:"تفاعل",een:"The post has high engagement.",ear:"المنشور له تفاعل عالٍ.",t:"mastery",u:11},
{w:"curate",c:"A2",s:"NGSL",p:"verb",ar:"ينتقي",een:"She curates her content carefully.",ear:"تنتقي محتواها بعناية.",t:"mastery",u:11},
{w:"monetize",c:"A2",s:"NGSL",p:"verb",ar:"يحقق ربحاً",een:"He monetizes his channel.",ear:"يحقق ربحاً من قناته.",t:"mastery",u:11},
{w:"moderate",c:"A2",s:"CEFR-J",p:"verb",ar:"يراقب المحتوى",een:"They moderate the comments.",ear:"يراقبون التعليقات.",t:"mastery",u:11},
{w:"authentic",c:"A2",s:"CEFR-J",p:"adjective",ar:"حقيقي",een:"Be authentic on social media.",ear:"كن حقيقياً على وسائل التواصل.",t:"mastery",u:11},
{w:"influential",c:"A2",s:"NGSL",p:"adjective",ar:"مؤثر",een:"She is very influential online.",ear:"هي مؤثرة جداً على الإنترنت.",t:"mastery",u:11},
{w:"controversial",c:"A2",s:"NGSL",p:"adjective",ar:"مثير للجدل",een:"The post was controversial.",ear:"كان المنشور مثيراً للجدل.",t:"mastery",u:11},
{w:"viral",c:"A2",s:"NGSL",p:"adjective",ar:"فيروسي الانتشار",een:"The challenge became viral.",ear:"أصبح التحدي فيروسي الانتشار.",t:"mastery",u:11},

// ===== UNIT 12: Green Living =====
{w:"recycle",c:"A2",s:"CEFR-J",p:"verb",ar:"يعيد تدوير",een:"We recycle paper and plastic.",ear:"نعيد تدوير الورق والبلاستيك.",t:"core",u:12},
{w:"energy",c:"A1",s:"CEFR-J",p:"noun",ar:"طاقة",een:"Solar energy is clean.",ear:"الطاقة الشمسية نظيفة.",t:"core",u:12},
{w:"waste",c:"A2",s:"CEFR-J",p:"noun",ar:"نفايات",een:"Do not throw waste in the sea.",ear:"لا ترمِ النفايات في البحر.",t:"core",u:12},
{w:"plastic",c:"A1",s:"CEFR-J",p:"noun",ar:"بلاستيك",een:"Plastic is bad for the ocean.",ear:"البلاستيك ضار بالمحيط.",t:"core",u:12},
{w:"environment",c:"A2",s:"CEFR-J",p:"noun",ar:"بيئة",een:"We must protect the environment.",ear:"يجب أن نحمي البيئة.",t:"core",u:12},
{w:"nature",c:"A1",s:"CEFR-J",p:"noun",ar:"طبيعة",een:"I love being in nature.",ear:"أحب أن أكون في الطبيعة.",t:"core",u:12},
{w:"climate",c:"A2",s:"CEFR-J",p:"noun",ar:"مناخ",een:"The climate is changing.",ear:"المناخ يتغير.",t:"core",u:12},
{w:"soil",c:"A2",s:"CEFR-J",p:"noun",ar:"تربة",een:"The soil here is very rich.",ear:"التربة هنا غنية جداً.",t:"core",u:12},
{w:"pollution",c:"A2",s:"CEFR-J",p:"noun",ar:"تلوث",een:"Air pollution is a problem.",ear:"تلوث الهواء مشكلة.",t:"core",u:12},
{w:"plant",c:"A1",s:"CEFR-J",p:"verb",ar:"يزرع",een:"We plant trees in the park.",ear:"نزرع أشجاراً في الحديقة.",t:"core",u:12},
{w:"reuse",c:"A2",s:"CEFR-J",p:"verb",ar:"يعيد استخدام",een:"Reuse old bags when shopping.",ear:"أعد استخدام الأكياس القديمة عند التسوق.",t:"core",u:12},
{w:"reduce",c:"A2",s:"CEFR-J",p:"verb",ar:"يقلل",een:"Reduce the use of plastic.",ear:"قلل استخدام البلاستيك.",t:"core",u:12},
{w:"green",c:"A1",s:"CEFR-J",p:"adjective",ar:"أخضر/صديق للبيئة",een:"Use green energy at home.",ear:"استخدم الطاقة الخضراء في المنزل.",t:"core",u:12},
{w:"renewable",c:"A2",s:"CEFR-J",p:"adjective",ar:"متجدد",een:"Wind is a renewable energy.",ear:"الرياح طاقة متجددة.",t:"core",u:12},
{w:"harmful",c:"A2",s:"CEFR-J",p:"adjective",ar:"ضار",een:"Smoke is harmful to health.",ear:"الدخان ضار بالصحة.",t:"core",u:12},
{w:"eco-friendly",c:"A2",s:"NGSL",p:"adjective",ar:"صديق للبيئة",een:"Buy eco-friendly products.",ear:"اشترِ منتجات صديقة للبيئة.",t:"core",u:12},
{w:"solar panel",c:"A2",s:"NGSL",p:"noun",ar:"لوح شمسي",een:"We installed solar panels.",ear:"ركبنا ألواحاً شمسية.",t:"extended",u:12},
{w:"carbon",c:"A2",s:"CEFR-J",p:"noun",ar:"كربون",een:"We must reduce carbon.",ear:"يجب أن نقلل الكربون.",t:"extended",u:12},
{w:"greenhouse",c:"A2",s:"CEFR-J",p:"noun",ar:"بيت زجاجي",een:"Plants grow in the greenhouse.",ear:"تنمو النباتات في البيت الزجاجي.",t:"extended",u:12},
{w:"compost",c:"A2",s:"NGSL",p:"noun",ar:"سماد عضوي",een:"We make compost from food waste.",ear:"نصنع سماداً عضوياً من بقايا الطعام.",t:"extended",u:12},
{w:"footprint",c:"A2",s:"NGSL",p:"noun",ar:"بصمة",een:"Reduce your carbon footprint.",ear:"قلل بصمتك الكربونية.",t:"extended",u:12},
{w:"conserve",c:"A2",s:"CEFR-J",p:"verb",ar:"يحافظ على",een:"Conserve water every day.",ear:"حافظ على الماء كل يوم.",t:"extended",u:12},
{w:"pollute",c:"A2",s:"CEFR-J",p:"verb",ar:"يلوث",een:"Factories pollute the air.",ear:"تلوث المصانع الهواء.",t:"extended",u:12},
{w:"decompose",c:"A2",s:"NGSL",p:"verb",ar:"يتحلل",een:"Paper can decompose easily.",ear:"يمكن للورق أن يتحلل بسهولة.",t:"extended",u:12},
{w:"generate",c:"A2",s:"CEFR-J",p:"verb",ar:"يولد",een:"Wind turbines generate electricity.",ear:"تولد توربينات الرياح الكهرباء.",t:"extended",u:12},
{w:"sustainable",c:"A2",s:"CEFR-J",p:"adjective",ar:"مستدام",een:"We need sustainable solutions.",ear:"نحتاج حلولاً مستدامة.",t:"extended",u:12},
{w:"biodegradable",c:"A2",s:"NGSL",p:"adjective",ar:"قابل للتحلل",een:"Use biodegradable bags.",ear:"استخدم أكياساً قابلة للتحلل.",t:"extended",u:12},
{w:"toxic",c:"A2",s:"CEFR-J",p:"adjective",ar:"سام",een:"This waste is toxic.",ear:"هذه النفايات سامة.",t:"extended",u:12},
{w:"global warming",c:"A2",s:"CEFR-J",p:"noun",ar:"الاحتباس الحراري",een:"Global warming is getting worse.",ear:"الاحتباس الحراري يزداد سوءاً.",t:"extended",u:12},
{w:"emission",c:"A2",s:"NGSL",p:"noun",ar:"انبعاث",een:"We must cut emissions.",ear:"يجب أن نخفض الانبعاثات.",t:"extended",u:12},
{w:"deforestation",c:"A2",s:"NGSL",p:"noun",ar:"إزالة الغابات",een:"Deforestation harms animals.",ear:"إزالة الغابات تضر بالحيوانات.",t:"mastery",u:12},
{w:"biodiversity",c:"A2",s:"NGSL",p:"noun",ar:"تنوع بيولوجي",een:"We must protect biodiversity.",ear:"يجب أن نحمي التنوع البيولوجي.",t:"mastery",u:12},
{w:"extinction",c:"A2",s:"NGSL",p:"noun",ar:"انقراض",een:"Pollution causes extinction.",ear:"التلوث يسبب الانقراض.",t:"mastery",u:12},
{w:"ecosystem",c:"A2",s:"NGSL",p:"noun",ar:"نظام بيئي",een:"The forest is a rich ecosystem.",ear:"الغابة نظام بيئي غني.",t:"mastery",u:12},
{w:"conservation",c:"A2",s:"CEFR-J",p:"noun",ar:"حماية البيئة",een:"Conservation is very important.",ear:"حماية البيئة مهمة جداً.",t:"mastery",u:12},
{w:"restore",c:"A2",s:"CEFR-J",p:"verb",ar:"يستعيد",een:"We can restore the forest.",ear:"يمكننا استعادة الغابة.",t:"mastery",u:12},
{w:"advocate",c:"A2",s:"NGSL",p:"verb",ar:"يدعو لـ",een:"She advocates for clean energy.",ear:"تدعو للطاقة النظيفة.",t:"mastery",u:12},
{w:"offset",c:"A2",s:"NGSL",p:"verb",ar:"يعوض",een:"Plant trees to offset carbon.",ear:"ازرع أشجاراً لتعويض الكربون.",t:"mastery",u:12},
{w:"ecological",c:"A2",s:"NGSL",p:"adjective",ar:"بيئي",een:"This is an ecological problem.",ear:"هذه مشكلة بيئية.",t:"mastery",u:12},
{w:"vulnerable",c:"A2",s:"NGSL",p:"adjective",ar:"معرض للخطر",een:"Many animals are vulnerable.",ear:"حيوانات كثيرة معرضة للخطر.",t:"mastery",u:12},
];

module.exports = ALL_WORDS;
