module.exports = [
// ============ UNIT 5: Hidden History ============
// CORE (34)
{w:"mystery",c:"A2",s:"CEFR-J",p:"noun",ar:"لُغز",een:"The old house is full of mystery.",ear:"البيت القديم مليء بالألغاز.",def:"something strange that is hard to explain",t:"core",u:5},
{w:"evidence",c:"A2",s:"NGSL",p:"noun",ar:"دليل",een:"They found evidence of an old village.",ear:"وجدوا دليلاً على قرية قديمة.",def:"facts that show something is true",t:"core",u:5},
{w:"hidden",c:"A2",s:"CEFR-J",p:"adjective",ar:"مخفيّ",een:"The hidden treasure was under the old tree.",ear:"كان الكنز المخفيّ تحت الشجرة القديمة.",def:"not easy to see or find",t:"core",u:5},
{w:"origin",c:"A2",s:"NGSL",p:"noun",ar:"أصل",een:"Nobody knows the origin of this tradition.",ear:"لا أحد يعرف أصل هذا التقليد.",def:"where something first came from",t:"core",u:5},
{w:"clue",c:"A2",s:"CEFR-J",p:"noun",ar:"دليل إرشادي",een:"The map gave us an important clue.",ear:"أعطتنا الخريطة دليلاً إرشادياً مهماً.",def:"a piece of information that helps solve something",t:"core",u:5},
{w:"era",c:"A2",s:"NGSL",p:"noun",ar:"حِقبة",een:"That building is from the Roman era.",ear:"ذلك المبنى من الحقبة الرومانية.",def:"a long period of time in history",t:"core",u:5},
{w:"figure",c:"A2",s:"NGSL",p:"noun",ar:"شخصية",een:"She was an important figure in history.",ear:"كانت شخصية مهمة في التاريخ.",def:"a person who is well known",t:"core",u:5},
{w:"passage",c:"A2",s:"CEFR-J",p:"noun",ar:"ممر",een:"We walked through a dark passage underground.",ear:"مشينا عبر ممر مظلم تحت الأرض.",def:"a narrow path or way through something",t:"core",u:5},
{w:"investigate",c:"A2",s:"NGSL",p:"verb",ar:"يُحقّق",een:"Scientists want to investigate the old site.",ear:"يريد العلماء التحقيق في الموقع القديم.",def:"to try to find out the truth about something",t:"core",u:5},
{w:"recognize",c:"A2",s:"NGSL",p:"verb",ar:"يتعرّف على",een:"I did not recognize the old symbol.",ear:"لم أتعرّف على الرمز القديم.",def:"to know something because you have seen it before",t:"core",u:5},
{w:"dig",c:"A1",s:"CEFR-J",p:"verb",ar:"يحفر",een:"They dig carefully to find old objects.",ear:"يحفرون بعناية للعثور على أشياء قديمة.",def:"to make a hole in the ground",t:"core",u:5},
{w:"uncover",c:"A2",s:"CEFR-J",p:"verb",ar:"يكشف",een:"Workers uncovered a hidden room under the floor.",ear:"كشف العمال غرفة مخفية تحت الأرض.",def:"to find something that was hidden",t:"core",u:5},
{w:"trail",c:"A2",s:"CEFR-J",p:"noun",ar:"أثر",een:"The explorer followed the trail through the forest.",ear:"تتبّع المستكشف الأثر عبر الغابة.",def:"marks or signs left behind by someone",t:"core",u:5},
{w:"tale",c:"A2",s:"CEFR-J",p:"noun",ar:"حكاية",een:"Grandma told us a tale about a king.",ear:"أخبرتنا جدتي حكاية عن ملك.",def:"a story, especially one from long ago",t:"core",u:5},
{w:"beneath",c:"A2",s:"CEFR-J",p:"preposition",ar:"تحت",een:"There is a tunnel beneath the old church.",ear:"يوجد نفق تحت الكنيسة القديمة.",def:"under or below something",t:"core",u:5},
{w:"prove",c:"A2",s:"NGSL",p:"verb",ar:"يُثبت",een:"Can you prove that the story is true?",ear:"هل تستطيع إثبات أن القصة حقيقية؟",def:"to show that something is true",t:"core",u:5},
{w:"remain",c:"A2",s:"NGSL",p:"verb",ar:"يبقى",een:"Only a few walls remain from the old city.",ear:"لم يبقَ سوى بضعة جدران من المدينة القديمة.",def:"to stay or continue to exist",t:"core",u:5},
{w:"stone",c:"A1",s:"CEFR-J",p:"noun",ar:"حَجَر",een:"The walls were made of heavy stone.",ear:"كانت الجدران مصنوعة من حجر ثقيل.",def:"a hard material found in the ground",t:"core",u:5},
{w:"incident",c:"A2",s:"NGSL",p:"noun",ar:"حادثة",een:"That incident changed the country forever.",ear:"تلك الحادثة غيّرت البلاد إلى الأبد.",def:"something that happens, often something unusual",t:"core",u:5},
{w:"trace",c:"A2",s:"NGSL",p:"noun",ar:"أثر",een:"There was no trace of the missing ship.",ear:"لم يكن هناك أي أثر للسفينة المفقودة.",def:"a small sign that something existed",t:"core",u:5},
{w:"belong",c:"A2",s:"NGSL",p:"verb",ar:"ينتمي",een:"These tools belong to an ancient people.",ear:"هذه الأدوات تنتمي إلى شعب قديم.",def:"to be owned by or part of something",t:"core",u:5},
{w:"truth",c:"A2",s:"NGSL",p:"noun",ar:"حقيقة",een:"Historians are still searching for the truth.",ear:"لا يزال المؤرخون يبحثون عن الحقيقة.",def:"what is real and correct",t:"core",u:5},
{w:"forgotten",c:"A2",s:"CEFR-J",p:"adjective",ar:"مَنسيّ",een:"They visited a forgotten village in the mountains.",ear:"زاروا قرية منسيّة في الجبال.",def:"not remembered by anyone",t:"core",u:5},
{w:"site",c:"A2",s:"NGSL",p:"noun",ar:"موقع",een:"This is an important archaeological site.",ear:"هذا موقع أثري مهم.",def:"a place where something is or was",t:"core",u:5},
{w:"object",c:"A2",s:"NGSL",p:"noun",ar:"شيء",een:"They found a strange object in the ground.",ear:"وجدوا شيئاً غريباً في الأرض.",def:"a thing that you can see or touch",t:"core",u:5},
{w:"century",c:"A2",s:"NGSL",p:"noun",ar:"قَرن",een:"The castle was built in the tenth century.",ear:"بُنيت القلعة في القرن العاشر.",def:"a period of one hundred years",t:"core",u:5},
{w:"journal",c:"A2",s:"NGSL",p:"noun",ar:"مذكّرات",een:"She kept a journal of her travels in Egypt.",ear:"احتفظت بمذكّرات عن رحلاتها في مصر.",def:"a book where you write about your daily life",t:"core",u:5},
{w:"disappear",c:"A2",s:"CEFR-J",p:"verb",ar:"يختفي",een:"Many old languages have disappeared over time.",ear:"اختفت لغات قديمة كثيرة مع مرور الوقت.",def:"to stop being seen or to go away",t:"core",u:5},
{w:"historian",c:"A2",s:"NGSL",p:"noun",ar:"مؤرّخ",een:"The historian wrote a book about the lost city.",ear:"كتب المؤرّخ كتاباً عن المدينة المفقودة.",def:"a person who studies and writes about the past",t:"core",u:5},
{w:"seek",c:"A2",s:"NGSL",p:"verb",ar:"يسعى",een:"Explorers seek lost cities in the jungle.",ear:"يسعى المستكشفون للعثور على مدن مفقودة في الأدغال.",def:"to try to find or get something",t:"core",u:5},
{w:"knowledge",c:"A2",s:"NGSL",p:"noun",ar:"معرفة",een:"She has great knowledge of world history.",ear:"لديها معرفة كبيرة بتاريخ العالم.",def:"facts and information that you know",t:"core",u:5},
{w:"exist",c:"A2",s:"NGSL",p:"verb",ar:"يوجد",een:"Did this kingdom really exist long ago?",ear:"هل وُجدت هذه المملكة حقاً قديماً؟",def:"to be real or to be present",t:"core",u:5},
{w:"claim",c:"A2",s:"NGSL",p:"verb",ar:"يدّعي",een:"Some people claim they saw a ghost there.",ear:"يدّعي بعض الناس أنهم رأوا شبحاً هناك.",def:"to say something is true without proof",t:"core",u:5},
{w:"region",c:"A2",s:"NGSL",p:"noun",ar:"منطقة",een:"This region has many old temples and tombs.",ear:"تحتوي هذه المنطقة على معابد ومقابر كثيرة.",def:"a large area of land",t:"core",u:5},
// EXTENDED (29)
{w:"archaeologist",c:"B1",s:"CEFR-J",p:"noun",ar:"عالم آثار",een:"The archaeologist found pottery from three thousand years ago.",ear:"وجد عالم الآثار فخاراً عمره ثلاثة آلاف سنة.",def:"a person who studies old objects and buildings",t:"extended",u:5},
{w:"manuscript",c:"B1",s:"CEFR-J",p:"noun",ar:"مخطوطة",een:"The old manuscript was written by hand.",ear:"كُتبت المخطوطة القديمة باليد.",def:"a very old book or document written by hand",t:"extended",u:5},
{w:"chamber",c:"B1",s:"CEFR-J",p:"noun",ar:"حُجرة",een:"They entered a secret chamber inside the pyramid.",ear:"دخلوا حجرة سرية داخل الهرم.",def:"a large room used for a special purpose",t:"extended",u:5},
{w:"seal",c:"A2",s:"CEFR-J",p:"noun",ar:"خَتم",een:"The letter had a royal seal on it.",ear:"كان على الرسالة ختم ملكي.",def:"a mark pressed into something to close or prove it",t:"extended",u:5},
{w:"relic",c:"B1",s:"CEFR-J",p:"noun",ar:"أثر تاريخي",een:"The museum showed a relic from the old kingdom.",ear:"عرض المتحف أثراً تاريخياً من المملكة القديمة.",def:"an old object from a past time",t:"extended",u:5},
{w:"myth",c:"A2",s:"CEFR-J",p:"noun",ar:"أسطورة",een:"Is it a true story or just a myth?",ear:"هل هي قصة حقيقية أم مجرد أسطورة؟",def:"an old story that may not be true",t:"extended",u:5},
{w:"servant",c:"A2",s:"CEFR-J",p:"noun",ar:"خادم",een:"The king had many servants in his palace.",ear:"كان لدى الملك خدم كثيرون في قصره.",def:"a person who works in someone's house",t:"extended",u:5},
{w:"rumor",c:"A2",s:"CEFR-J",p:"noun",ar:"إشاعة",een:"There is a rumor about treasure in that cave.",ear:"هناك إشاعة عن كنز في ذلك الكهف.",def:"a story people tell that may not be true",t:"extended",u:5},
{w:"spy",c:"A2",s:"CEFR-J",p:"noun",ar:"جاسوس",een:"The spy carried secret messages across the border.",ear:"حمل الجاسوس رسائل سرية عبر الحدود.",def:"a person who secretly collects information",t:"extended",u:5},
{w:"noble",c:"A2",s:"CEFR-J",p:"adjective",ar:"نبيل",een:"The noble family lived in a large castle.",ear:"عاشت العائلة النبيلة في قلعة كبيرة.",def:"belonging to a high social class",t:"extended",u:5},
{w:"decode",c:"A2",s:"CEFR-J",p:"verb",ar:"يفكّ الشفرة",een:"They tried to decode the secret message.",ear:"حاولوا فكّ شفرة الرسالة السرية.",def:"to find the meaning of a hidden message",t:"extended",u:5},
{w:"kingdom",c:"A2",s:"NGSL",p:"noun",ar:"مملكة",een:"The kingdom stretched from the river to the sea.",ear:"امتدت المملكة من النهر إلى البحر.",def:"a country ruled by a king or queen",t:"extended",u:5},
{w:"scatter",c:"A2",s:"CEFR-J",p:"verb",ar:"يُبعثر",een:"The wind scattered the old papers everywhere.",ear:"بعثرت الرياح الأوراق القديمة في كل مكان.",def:"to spread things in different directions",t:"extended",u:5},
{w:"grave",c:"A2",s:"CEFR-J",p:"noun",ar:"قبر",een:"They found a grave from two thousand years ago.",ear:"وجدوا قبراً عمره ألفا سنة.",def:"the place where a dead person is put",t:"extended",u:5},
{w:"abandon",c:"A2",s:"NGSL",p:"verb",ar:"يهجر",een:"The people had to abandon the city quickly.",ear:"اضطر الناس إلى هجر المدينة بسرعة.",def:"to leave a place and not go back",t:"extended",u:5},
{w:"document",c:"A2",s:"NGSL",p:"noun",ar:"وثيقة",een:"This document tells us about life long ago.",ear:"تخبرنا هذه الوثيقة عن الحياة قديماً.",def:"an official paper with important information",t:"extended",u:5},
{w:"scholar",c:"B1",s:"NGSL",p:"noun",ar:"عالِم",een:"The scholar spent years studying old texts.",ear:"أمضى العالم سنوات في دراسة النصوص القديمة.",def:"a person who studies and knows a lot",t:"extended",u:5},
{w:"curse",c:"A2",s:"CEFR-J",p:"noun",ar:"لعنة",een:"People believed there was a curse on the tomb.",ear:"اعتقد الناس أن هناك لعنة على المقبرة.",def:"words meant to bring bad luck to someone",t:"extended",u:5},
{w:"suspect",c:"A2",s:"NGSL",p:"verb",ar:"يشتبه",een:"Police suspect the painting is a fake.",ear:"تشتبه الشرطة في أن اللوحة مزيّفة.",def:"to think something might be true",t:"extended",u:5},
{w:"survivor",c:"A2",s:"CEFR-J",p:"noun",ar:"ناجٍ",een:"The survivor told the story of the shipwreck.",ear:"روى الناجي قصة حطام السفينة.",def:"a person who lives through a dangerous event",t:"extended",u:5},
{w:"witness",c:"A2",s:"NGSL",p:"noun",ar:"شاهد",een:"The witness saw everything that happened that night.",ear:"رأى الشاهد كل ما حدث تلك الليلة.",def:"a person who sees an event happen",t:"extended",u:5},
{w:"border",c:"A2",s:"NGSL",p:"noun",ar:"حدود",een:"They crossed the border between the two countries.",ear:"عبروا الحدود بين البلدين.",def:"the line that separates two countries",t:"extended",u:5},
{w:"underground",c:"A2",s:"CEFR-J",p:"adjective",ar:"تحت الأرض",een:"There is an underground city in Turkey.",ear:"توجد مدينة تحت الأرض في تركيا.",def:"below the surface of the ground",t:"extended",u:5},
{w:"conflict",c:"A2",s:"NGSL",p:"noun",ar:"صراع",een:"The conflict between the two kingdoms lasted years.",ear:"استمر الصراع بين المملكتين لسنوات.",def:"a fight or disagreement between groups",t:"extended",u:5},
{w:"retreat",c:"B1",s:"CEFR-J",p:"verb",ar:"ينسحب",een:"The army had to retreat from the battle.",ear:"اضطر الجيش إلى الانسحاب من المعركة.",def:"to move back and away from danger",t:"extended",u:5},
{w:"rob",c:"A2",s:"CEFR-J",p:"verb",ar:"يسرق",een:"Thieves tried to rob the king's treasure.",ear:"حاول اللصوص سرقة كنز الملك.",def:"to steal something from a person or place",t:"extended",u:5},
{w:"astonishing",c:"B1",s:"CEFR-J",p:"adjective",ar:"مذهل",een:"The discovery was truly astonishing.",ear:"كان الاكتشاف مذهلاً حقاً.",def:"very surprising in a way that is hard to believe",t:"extended",u:5},
{w:"permanently",c:"B1",s:"NGSL",p:"adverb",ar:"بشكل دائم",een:"The village was permanently abandoned after the flood.",ear:"هُجرت القرية بشكل دائم بعد الفيضان.",def:"lasting forever, not changing",t:"extended",u:5},
{w:"warfare",c:"B1",s:"NGSL",p:"noun",ar:"حرب",een:"Ancient warfare used swords and shields.",ear:"استخدمت الحروب القديمة السيوف والدروع.",def:"the activity of fighting in a war",t:"extended",u:5},
// MASTERY (25)
{w:"excavation",c:"B1",s:"CEFR-J",p:"noun",ar:"تنقيب",een:"The excavation took more than five years.",ear:"استغرق التنقيب أكثر من خمس سنوات.",def:"the process of digging to find old things",t:"mastery",u:5},
{w:"deception",c:"B1",s:"CEFR-J",p:"noun",ar:"خِداع",een:"The letter was full of lies and deception.",ear:"كانت الرسالة مليئة بالأكاذيب والخداع.",def:"making someone believe something that is not true",t:"mastery",u:5},
{w:"betrayal",c:"B1",s:"CEFR-J",p:"noun",ar:"خيانة",een:"The story is about betrayal and broken trust.",ear:"القصة عن الخيانة والثقة المكسورة.",def:"when someone you trust hurts you",t:"mastery",u:5},
{w:"rebellion",c:"B1",s:"CEFR-J",p:"noun",ar:"تمرّد",een:"The rebellion against the king started at night.",ear:"بدأ التمرّد ضد الملك ليلاً.",def:"a fight against the people in power",t:"mastery",u:5},
{w:"overthrow",c:"B1",s:"CEFR-J",p:"verb",ar:"يُسقط",een:"The people wanted to overthrow the cruel ruler.",ear:"أراد الشعب إسقاط الحاكم القاسي.",def:"to remove a leader from power by force",t:"mastery",u:5},
{w:"quest",c:"B1",s:"CEFR-J",p:"noun",ar:"سعي",een:"The quest for the lost treasure lasted many years.",ear:"استمر السعي للكنز المفقود سنوات عديدة.",def:"a long search for something important",t:"mastery",u:5},
{w:"genuine",c:"B1",s:"NGSL",p:"adjective",ar:"حقيقي أصيل",een:"Experts confirmed the old coin is genuine.",ear:"أكد الخبراء أن العملة القديمة حقيقية.",def:"real and not fake",t:"mastery",u:5},
{w:"smuggle",c:"B1",s:"CEFR-J",p:"verb",ar:"يُهرّب",een:"They tried to smuggle gold out of the country.",ear:"حاولوا تهريب الذهب خارج البلاد.",def:"to move things secretly and against the law",t:"mastery",u:5},
{w:"artifact",c:"B1",s:"CEFR-J",p:"noun",ar:"قطعة أثرية",een:"Each artifact tells a story about the past.",ear:"كل قطعة أثرية تروي قصة عن الماضي.",def:"an old object made by people long ago",t:"mastery",u:5},
{w:"conceal",c:"B1",s:"CEFR-J",p:"verb",ar:"يُخفي",een:"She tried to conceal the map from the soldiers.",ear:"حاولت إخفاء الخريطة عن الجنود.",def:"to hide something so others cannot find it",t:"mastery",u:5},
{w:"unveil",c:"B1",s:"CEFR-J",p:"verb",ar:"يكشف النقاب عن",een:"The museum will unveil the new exhibit tomorrow.",ear:"سيكشف المتحف النقاب عن المعرض الجديد غداً.",def:"to show something to the public for the first time",t:"mastery",u:5},
{w:"descendant",c:"B1",s:"CEFR-J",p:"noun",ar:"حفيد / سليل",een:"He is a descendant of a famous explorer.",ear:"هو سليل مستكشف مشهور.",def:"a person related to someone who lived before",t:"mastery",u:5},
{w:"forbidden",c:"B1",s:"CEFR-J",p:"adjective",ar:"محظور",een:"The forbidden room was behind a locked door.",ear:"كانت الغرفة المحظورة خلف باب مُقفل.",def:"not allowed by rules or law",t:"mastery",u:5},
{w:"heir",c:"B1",s:"CEFR-J",p:"noun",ar:"وريث",een:"The heir to the throne was only twelve.",ear:"كان وريث العرش في الثانية عشرة فقط.",def:"a person who receives something after someone dies",t:"mastery",u:5},
{w:"chronicle",c:"B1",s:"CEFR-J",p:"noun",ar:"سِجِلّ تاريخي",een:"The chronicle described life in the medieval period.",ear:"وصف السجل التاريخي الحياة في العصور الوسطى.",def:"a written record of events in time order",t:"mastery",u:5},
{w:"blockade",c:"B1",s:"CEFR-J",p:"noun",ar:"حصار",een:"The blockade stopped all ships from entering the port.",ear:"أوقف الحصار جميع السفن من دخول الميناء.",def:"when an area is closed off to stop people or goods",t:"mastery",u:5},
{w:"plague",c:"B1",s:"CEFR-J",p:"noun",ar:"وباء",een:"The plague killed thousands of people in Europe.",ear:"قتل الوباء آلاف الأشخاص في أوروبا.",def:"a very serious disease that spreads quickly",t:"mastery",u:5},
{w:"loot",c:"B1",s:"CEFR-J",p:"verb",ar:"ينهب",een:"Soldiers would often loot villages after battles.",ear:"كان الجنود غالباً ينهبون القرى بعد المعارك.",def:"to steal things during a war or disaster",t:"mastery",u:5},
{w:"forge",c:"B1",s:"CEFR-J",p:"verb",ar:"يُزوّر",een:"Someone tried to forge the king's signature.",ear:"حاول شخص ما تزوير توقيع الملك.",def:"to make a fake copy of something",t:"mastery",u:5},
{w:"riddle",c:"B1",s:"CEFR-J",p:"noun",ar:"لُغز",een:"The ancient riddle was carved into the wall.",ear:"كان اللغز القديم محفوراً على الجدار.",def:"a question that is fun and hard to answer",t:"mastery",u:5},
{w:"oath",c:"B1",s:"CEFR-J",p:"noun",ar:"قَسَم",een:"The knight took an oath to protect the king.",ear:"أقسم الفارس قَسَماً لحماية الملك.",def:"a serious promise to do something",t:"mastery",u:5},
{w:"lineage",c:"B1",s:"CEFR-J",p:"noun",ar:"نسب",een:"The royal lineage goes back five hundred years.",ear:"يعود النسب الملكي إلى خمسمئة سنة.",def:"the family members who came before you",t:"mastery",u:5},
{w:"allegiance",c:"B1",s:"CEFR-J",p:"noun",ar:"ولاء",een:"The soldiers swore allegiance to their new leader.",ear:"أقسم الجنود الولاء لقائدهم الجديد.",def:"loyalty and support for a leader or group",t:"mastery",u:5},
{w:"sovereign",c:"B1",s:"CEFR-J",p:"noun",ar:"حاكم",een:"The sovereign made all the important decisions.",ear:"اتخذ الحاكم جميع القرارات المهمة.",def:"a king or queen who rules a country",t:"mastery",u:5},
{w:"conspiracy",c:"B1",s:"CEFR-J",p:"noun",ar:"مؤامرة",een:"The conspiracy to steal the crown was discovered.",ear:"اكتُشفت المؤامرة لسرقة التاج.",def:"a secret plan by a group to do something wrong",t:"mastery",u:5},

// ============ UNIT 6: Future Cities ============
// CORE (34)
{w:"urban",c:"A2",s:"NGSL",p:"adjective",ar:"حَضَري",een:"Urban areas have more people than villages.",ear:"المناطق الحضرية بها سكان أكثر من القرى.",def:"related to towns and cities",t:"core",u:6},
{w:"citizen",c:"A2",s:"NGSL",p:"noun",ar:"مواطن",een:"Every citizen should help keep the city clean.",ear:"يجب على كل مواطن المساعدة في نظافة المدينة.",def:"a person who lives in a city or country",t:"core",u:6},
{w:"vehicle",c:"A2",s:"NGSL",p:"noun",ar:"مركبة",een:"Electric vehicles are better for the environment.",ear:"المركبات الكهربائية أفضل للبيئة.",def:"a machine used to carry people or things",t:"core",u:6},
{w:"project",c:"A2",s:"NGSL",p:"noun",ar:"مشروع",een:"The new housing project will start next year.",ear:"سيبدأ مشروع الإسكان الجديد العام المقبل.",def:"a planned piece of work with a goal",t:"core",u:6},
{w:"population",c:"A2",s:"NGSL",p:"noun",ar:"سكان",een:"The city's population is growing very fast.",ear:"يتزايد عدد سكان المدينة بسرعة كبيرة.",def:"the number of people living in a place",t:"core",u:6},
{w:"solution",c:"A2",s:"NGSL",p:"noun",ar:"حَلّ",een:"We need a smart solution for traffic problems.",ear:"نحتاج حلاً ذكياً لمشاكل المرور.",def:"an answer to a problem",t:"core",u:6},
{w:"resident",c:"A2",s:"NGSL",p:"noun",ar:"مقيم",een:"Residents want more parks in their neighborhood.",ear:"يريد المقيمون المزيد من الحدائق في حيّهم.",def:"a person who lives in a particular place",t:"core",u:6},
{w:"commute",c:"A2",s:"CEFR-J",p:"verb",ar:"يتنقل للعمل",een:"Many people commute to the city by train.",ear:"يتنقل كثير من الناس إلى المدينة بالقطار.",def:"to travel between home and work every day",t:"core",u:6},
{w:"district",c:"A2",s:"NGSL",p:"noun",ar:"حَيّ",een:"The shopping district is in the city center.",ear:"حيّ التسوق في وسط المدينة.",def:"a part of a city with a special purpose",t:"core",u:6},
{w:"lane",c:"A2",s:"CEFR-J",p:"noun",ar:"مسار",een:"The city added a new bike lane on this road.",ear:"أضافت المدينة مساراً جديداً للدراجات في هذا الطريق.",def:"a narrow path or part of a road",t:"core",u:6},
{w:"maintain",c:"A2",s:"NGSL",p:"verb",ar:"يُحافظ على",een:"It costs a lot to maintain old buildings.",ear:"يكلّف الكثير الحفاظ على المباني القديمة.",def:"to keep something in good condition",t:"core",u:6},
{w:"concept",c:"A2",s:"NGSL",p:"noun",ar:"مفهوم",een:"The concept of a smart city is very exciting.",ear:"مفهوم المدينة الذكية مثير جداً.",def:"an idea or plan in your mind",t:"core",u:6},
{w:"power",c:"A1",s:"NGSL",p:"noun",ar:"طاقة",een:"Solar panels give power to many homes.",ear:"تمنح الألواح الشمسية الطاقة للعديد من المنازل.",def:"energy used to make machines work",t:"core",u:6},
{w:"resource",c:"A2",s:"NGSL",p:"noun",ar:"مورد",een:"Water is our most important natural resource.",ear:"الماء هو أهم مورد طبيعي لدينا.",def:"something useful that a place or person has",t:"core",u:6},
{w:"structure",c:"A2",s:"NGSL",p:"noun",ar:"هيكل",een:"The tall structure can be seen from far away.",ear:"يمكن رؤية الهيكل الطويل من بعيد.",def:"something that has been built",t:"core",u:6},
{w:"network",c:"A2",s:"NGSL",p:"noun",ar:"شبكة",een:"The city has a fast internet network.",ear:"لدى المدينة شبكة إنترنت سريعة.",def:"a system of connected things or people",t:"core",u:6},
{w:"install",c:"A2",s:"NGSL",p:"verb",ar:"يُركّب",een:"They will install solar panels on every roof.",ear:"سيُركّبون ألواحاً شمسية على كل سطح.",def:"to put a new thing in place so it works",t:"core",u:6},
{w:"area",c:"A1",s:"NGSL",p:"noun",ar:"منطقة",een:"This area of the city is very modern.",ear:"هذه المنطقة من المدينة حديثة جداً.",def:"a part of a place",t:"core",u:6},
{w:"material",c:"A2",s:"NGSL",p:"noun",ar:"مادة",een:"They use recycled material to build new homes.",ear:"يستخدمون مواد مُعاد تدويرها لبناء منازل جديدة.",def:"what something is made from",t:"core",u:6},
{w:"produce",c:"A2",s:"NGSL",p:"verb",ar:"يُنتج",een:"These farms produce food for the whole city.",ear:"تُنتج هذه المزارع طعاماً للمدينة بأكملها.",def:"to make or grow something",t:"core",u:6},
{w:"demand",c:"A2",s:"NGSL",p:"noun",ar:"طلب",een:"There is high demand for clean water.",ear:"هناك طلب كبير على المياه النظيفة.",def:"when many people want or need something",t:"core",u:6},
{w:"vision",c:"A2",s:"NGSL",p:"noun",ar:"رؤية",een:"The mayor shared her vision for the city.",ear:"شاركت العمدة رؤيتها للمدينة.",def:"an idea about what the future should be like",t:"core",u:6},
{w:"rubbish",c:"A2",s:"CEFR-J",p:"noun",ar:"نفايات",een:"The city turns rubbish into energy every day.",ear:"تحوّل المدينة النفايات إلى طاقة كل يوم.",def:"things that people throw away",t:"core",u:6},
{w:"detect",c:"A2",s:"NGSL",p:"verb",ar:"يكتشف",een:"Sensors detect problems in the city water system.",ear:"تكتشف المستشعرات مشاكل في نظام مياه المدينة.",def:"to notice or find something",t:"core",u:6},
{w:"decrease",c:"A2",s:"NGSL",p:"verb",ar:"يُقلّل",een:"New buses help decrease air pollution in town.",ear:"تساعد الحافلات الجديدة في تقليل تلوّث الهواء.",def:"to become smaller in number or amount",t:"core",u:6},
{w:"location",c:"A2",s:"NGSL",p:"noun",ar:"موقع",een:"The location of the new park is perfect.",ear:"موقع الحديقة الجديدة مثالي.",def:"the place where something is",t:"core",u:6},
{w:"budget",c:"A2",s:"NGSL",p:"noun",ar:"ميزانية",een:"The city budget includes money for new schools.",ear:"تتضمن ميزانية المدينة أموالاً لمدارس جديدة.",def:"the amount of money available to spend",t:"core",u:6},
{w:"feature",c:"A2",s:"NGSL",p:"noun",ar:"ميزة",een:"The best feature of this building is the garden.",ear:"أفضل ميزة في هذا المبنى هي الحديقة.",def:"an important or interesting part of something",t:"core",u:6},
{w:"plan",c:"A1",s:"NGSL",p:"verb",ar:"يُخطّط",een:"The government plans to build more green spaces.",ear:"تخطّط الحكومة لبناء مزيد من المساحات الخضراء.",def:"to decide what you are going to do",t:"core",u:6},
{w:"service",c:"A2",s:"NGSL",p:"noun",ar:"خدمة",een:"The city offers a free bus service.",ear:"تقدّم المدينة خدمة حافلات مجانية.",def:"work done to help people",t:"core",u:6},
{w:"approve",c:"A2",s:"NGSL",p:"verb",ar:"يوافق",een:"The council must approve every new building plan.",ear:"يجب أن يوافق المجلس على كل خطة بناء جديدة.",def:"to say yes and agree to something officially",t:"core",u:6},
{w:"link",c:"A2",s:"NGSL",p:"verb",ar:"يربط",een:"New roads link the suburbs to the city center.",ear:"تربط الطرق الجديدة الضواحي بوسط المدينة.",def:"to join two things or places together",t:"core",u:6},
{w:"accessible",c:"A2",s:"NGSL",p:"adjective",ar:"سهل الوصول",een:"The new park is accessible to everyone.",ear:"الحديقة الجديدة سهلة الوصول للجميع.",def:"easy to reach or use",t:"core",u:6},
{w:"community",c:"A2",s:"NGSL",p:"noun",ar:"مجتمع محلي",een:"The community planted trees in every street.",ear:"زرع المجتمع المحلي أشجاراً في كل شارع.",def:"a group of people living in the same area",t:"core",u:6},
// EXTENDED (29)
{w:"infrastructure",c:"B1",s:"NGSL",p:"noun",ar:"بنية تحتية",een:"Good infrastructure makes a city work well.",ear:"البنية التحتية الجيدة تجعل المدينة تعمل بشكل جيد.",def:"basic systems like roads and water that a city needs",t:"extended",u:6},
{w:"skyscraper",c:"A2",s:"CEFR-J",p:"noun",ar:"ناطحة سحاب",een:"The new skyscraper is the tallest in the country.",ear:"ناطحة السحاب الجديدة هي الأطول في البلاد.",def:"a very tall building in a city",t:"extended",u:6},
{w:"rooftop",c:"A2",s:"CEFR-J",p:"noun",ar:"سطح المبنى",een:"They grow vegetables on the rooftop garden.",ear:"يزرعون الخضروات في حديقة سطح المبنى.",def:"the top surface of a building",t:"extended",u:6},
{w:"subway",c:"A2",s:"CEFR-J",p:"noun",ar:"مترو أنفاق",een:"The subway is the fastest way to travel here.",ear:"المترو هو أسرع وسيلة للتنقل هنا.",def:"a train that runs underground in a city",t:"extended",u:6},
{w:"pedestrian",c:"B1",s:"CEFR-J",p:"noun",ar:"مُشاة",een:"This street is only for pedestrians, not cars.",ear:"هذا الشارع للمشاة فقط وليس للسيارات.",def:"a person who is walking in the street",t:"extended",u:6},
{w:"drone",c:"A2",s:"CEFR-J",p:"noun",ar:"طائرة بدون طيار",een:"A drone delivered the package to her door.",ear:"أوصلت طائرة بدون طيار الطرد إلى بابها.",def:"a small flying machine without a person inside",t:"extended",u:6},
{w:"congestion",c:"B1",s:"CEFR-J",p:"noun",ar:"ازدحام",een:"Traffic congestion is worse during morning hours.",ear:"ازدحام المرور أسوأ خلال ساعات الصباح.",def:"when there are too many cars on the road",t:"extended",u:6},
{w:"panel",c:"A2",s:"NGSL",p:"noun",ar:"لوح",een:"Each panel on the roof collects sunlight.",ear:"كل لوح على السطح يجمع ضوء الشمس.",def:"a flat piece that is part of something larger",t:"extended",u:6},
{w:"architect",c:"A2",s:"CEFR-J",p:"noun",ar:"مهندس معماري",een:"The architect designed a beautiful new library.",ear:"صمّم المهندس المعماري مكتبة جديدة جميلة.",def:"a person who designs buildings",t:"extended",u:6},
{w:"permit",c:"A2",s:"NGSL",p:"noun",ar:"تصريح",een:"You need a permit to build in this area.",ear:"تحتاج تصريحاً للبناء في هذه المنطقة.",def:"an official paper that allows you to do something",t:"extended",u:6},
{w:"vertical",c:"B1",s:"CEFR-J",p:"adjective",ar:"عمودي",een:"Vertical gardens grow on the side of buildings.",ear:"الحدائق العمودية تنمو على جوانب المباني.",def:"going straight up, not sideways",t:"extended",u:6},
{w:"density",c:"B1",s:"NGSL",p:"noun",ar:"كثافة",een:"High population density makes cities very crowded.",ear:"الكثافة السكانية العالية تجعل المدن مزدحمة جداً.",def:"how close together things or people are",t:"extended",u:6},
{w:"regulate",c:"B1",s:"NGSL",p:"verb",ar:"يُنظّم",een:"New laws regulate how much noise factories can make.",ear:"تُنظّم قوانين جديدة مقدار الضوضاء التي يمكن للمصانع إصدارها.",def:"to control something with rules",t:"extended",u:6},
{w:"hub",c:"A2",s:"CEFR-J",p:"noun",ar:"مركز",een:"The airport is a major transport hub.",ear:"المطار مركز نقل رئيسي.",def:"the central and most important part of something",t:"extended",u:6},
{w:"zone",c:"A2",s:"CEFR-J",p:"noun",ar:"منطقة محددة",een:"Cars are not allowed in the pedestrian zone.",ear:"لا يُسمح بالسيارات في منطقة المشاة.",def:"an area used for a particular purpose",t:"extended",u:6},
{w:"allocate",c:"B1",s:"NGSL",p:"verb",ar:"يُخصّص",een:"The city will allocate money for new parks.",ear:"ستُخصّص المدينة أموالاً لحدائق جديدة.",def:"to give something for a particular purpose",t:"extended",u:6},
{w:"integrate",c:"B1",s:"NGSL",p:"verb",ar:"يدمج",een:"They want to integrate nature into city design.",ear:"يريدون دمج الطبيعة في تصميم المدينة.",def:"to combine things so they work together",t:"extended",u:6},
{w:"layout",c:"A2",s:"CEFR-J",p:"noun",ar:"تخطيط",een:"The layout of the new district is very open.",ear:"تخطيط الحيّ الجديد مفتوح جداً.",def:"the way things are arranged in a space",t:"extended",u:6},
{w:"municipal",c:"B1",s:"NGSL",p:"adjective",ar:"بلدي",een:"The municipal government provides many city services.",ear:"تقدّم الحكومة البلدية خدمات كثيرة للمدينة.",def:"related to the government of a city or town",t:"extended",u:6},
{w:"commuter",c:"B1",s:"CEFR-J",p:"noun",ar:"مسافر يومي",een:"Thousands of commuters use the train every day.",ear:"يستخدم آلاف المسافرين اليوميين القطار كل يوم.",def:"a person who travels to work every day",t:"extended",u:6},
{w:"zoning",c:"B1",s:"CEFR-J",p:"noun",ar:"تقسيم المناطق",een:"Zoning laws decide what can be built where.",ear:"تحدد قوانين تقسيم المناطق ما يمكن بناؤه وأين.",def:"rules about how land in a city can be used",t:"extended",u:6},
{w:"sprawl",c:"B1",s:"CEFR-J",p:"noun",ar:"امتداد عمراني",een:"Urban sprawl is a growing problem in big cities.",ear:"الامتداد العمراني مشكلة متزايدة في المدن الكبرى.",def:"when a city spreads out in an unplanned way",t:"extended",u:6},
{w:"sidewalk",c:"A2",s:"CEFR-J",p:"noun",ar:"رصيف",een:"The new sidewalk is wide enough for everyone.",ear:"الرصيف الجديد عريض بما يكفي للجميع.",def:"a path next to the road where people walk",t:"extended",u:6},
{w:"low-carbon",c:"B1",s:"CEFR-J",p:"adjective",ar:"منخفض الكربون",een:"Low-carbon buildings use less energy and water.",ear:"المباني منخفضة الكربون تستخدم طاقة ومياه أقل.",def:"producing less harmful gas",t:"extended",u:6},
{w:"exhaust",c:"B1",s:"NGSL",p:"noun",ar:"عادم",een:"Car exhaust makes the air dirty in cities.",ear:"يجعل عادم السيارات الهواء ملوثاً في المدن.",def:"gas or smoke that comes out of a vehicle",t:"extended",u:6},
{w:"economical",c:"A2",s:"NGSL",p:"adjective",ar:"اقتصادي",een:"Electric cars are more economical than old ones.",ear:"السيارات الكهربائية أكثر اقتصادية من القديمة.",def:"using little money or resources",t:"extended",u:6},
{w:"inexpensive",c:"A2",s:"NGSL",p:"adjective",ar:"غير مكلف",een:"We need more inexpensive housing in the city.",ear:"نحتاج المزيد من المساكن غير المكلفة في المدينة.",def:"not costing a lot of money",t:"extended",u:6},
{w:"solar-powered",c:"A2",s:"CEFR-J",p:"adjective",ar:"يعمل بالطاقة الشمسية",een:"Solar-powered lights save electricity at night.",ear:"الأضواء العاملة بالطاقة الشمسية توفر الكهرباء ليلاً.",def:"using energy from the sun to work",t:"extended",u:6},
{w:"smog",c:"A2",s:"CEFR-J",p:"noun",ar:"ضباب دخاني",een:"Heavy smog covered the city this morning.",ear:"غطى ضباب دخاني كثيف المدينة هذا الصباح.",def:"dirty air caused by smoke and car fumes",t:"extended",u:6},
// MASTERY (25)
{w:"blueprint",c:"B1",s:"CEFR-J",p:"noun",ar:"مخطط",een:"The architect showed us the blueprint of the house.",ear:"أرانا المهندس المعماري مخطط المنزل.",def:"a detailed plan or drawing of something to build",t:"mastery",u:6},
{w:"self-sufficient",c:"B1",s:"CEFR-J",p:"adjective",ar:"مكتفٍ ذاتياً",een:"The building is self-sufficient in energy.",ear:"المبنى مكتفٍ ذاتياً في الطاقة.",def:"able to provide everything you need by yourself",t:"mastery",u:6},
{w:"autonomous",c:"B1",s:"CEFR-J",p:"adjective",ar:"ذاتي القيادة",een:"Autonomous buses drive without a human driver.",ear:"تسير الحافلات ذاتية القيادة بدون سائق بشري.",def:"able to work or move by itself",t:"mastery",u:6},
{w:"grid",c:"B1",s:"CEFR-J",p:"noun",ar:"شبكة كهربائية",een:"The power grid supplies electricity to the city.",ear:"تزوّد الشبكة الكهربائية المدينة بالكهرباء.",def:"a system of wires that carries electricity",t:"mastery",u:6},
{w:"metropolitan",c:"B1",s:"NGSL",p:"adjective",ar:"حضري كبير",een:"The metropolitan area has over five million people.",ear:"المنطقة الحضرية الكبرى بها أكثر من خمسة ملايين نسمة.",def:"relating to a large city and its surrounding area",t:"mastery",u:6},
{w:"urbanization",c:"B1",s:"NGSL",p:"noun",ar:"تحضّر",een:"Urbanization means more people move to cities.",ear:"التحضّر يعني أن المزيد من الناس ينتقلون إلى المدن.",def:"the growth of cities as people move to them",t:"mastery",u:6},
{w:"surveillance",c:"B1",s:"CEFR-J",p:"noun",ar:"مراقبة",een:"Surveillance cameras help keep the streets safe.",ear:"تساعد كاميرات المراقبة في الحفاظ على أمان الشوارع.",def:"watching people or places to prevent crime",t:"mastery",u:6},
{w:"congested",c:"B1",s:"CEFR-J",p:"adjective",ar:"مزدحم",een:"The congested highway made everyone late for work.",ear:"الطريق السريع المزدحم جعل الجميع يتأخرون عن العمل.",def:"too full of cars or people to move easily",t:"mastery",u:6},
{w:"demolish",c:"B1",s:"CEFR-J",p:"verb",ar:"يهدم",een:"They had to demolish the unsafe old bridge.",ear:"اضطروا إلى هدم الجسر القديم غير الآمن.",def:"to destroy a building completely",t:"mastery",u:6},
{w:"pedestrianize",c:"B1",s:"CEFR-J",p:"verb",ar:"يحوّل لمنطقة مشاة",een:"The city plans to pedestrianize the main street.",ear:"تخطط المدينة لتحويل الشارع الرئيسي لمنطقة مشاة.",def:"to close a street to cars so people can walk",t:"mastery",u:6},
{w:"suburb",c:"B1",s:"CEFR-J",p:"noun",ar:"ضاحية",een:"Many families prefer to live in the suburbs.",ear:"تفضّل عائلات كثيرة العيش في الضواحي.",def:"an area outside the center of a city",t:"mastery",u:6},
{w:"outskirts",c:"B1",s:"CEFR-J",p:"noun",ar:"أطراف المدينة",een:"The factory is on the outskirts of the city.",ear:"المصنع على أطراف المدينة.",def:"the parts of a city that are far from the center",t:"mastery",u:6},
{w:"waterfront",c:"B1",s:"CEFR-J",p:"noun",ar:"واجهة بحرية",een:"The waterfront area has many restaurants and cafes.",ear:"منطقة الواجهة البحرية بها مطاعم ومقاهٍ كثيرة.",def:"the part of a city next to water",t:"mastery",u:6},
{w:"prosperity",c:"B1",s:"NGSL",p:"noun",ar:"ازدهار",een:"Good planning brings prosperity to a city.",ear:"التخطيط الجيد يجلب الازدهار للمدينة.",def:"the state of being successful and having money",t:"mastery",u:6},
{w:"catalyst",c:"B1",s:"CEFR-J",p:"noun",ar:"حافز",een:"The new railway was a catalyst for growth.",ear:"كانت السكك الحديدية الجديدة حافزاً للنمو.",def:"something that makes change happen faster",t:"mastery",u:6},
{w:"retrofit",c:"B1",s:"CEFR-J",p:"verb",ar:"يُعيد تجهيز",een:"They will retrofit old buildings with solar panels.",ear:"سيُعيدون تجهيز المباني القديمة بألواح شمسية.",def:"to add new parts to an old building or machine",t:"mastery",u:6},
{w:"walkable",c:"B1",s:"CEFR-J",p:"adjective",ar:"صالح للمشي",een:"A walkable city has wide sidewalks and shade.",ear:"المدينة الصالحة للمشي بها أرصفة عريضة وظل.",def:"easy and pleasant to walk around in",t:"mastery",u:6},
{w:"revitalize",c:"B1",s:"CEFR-J",p:"verb",ar:"يُنعش",een:"The project will revitalize the old neighborhood.",ear:"سيُنعش المشروع الحيّ القديم.",def:"to give new life and energy to something",t:"mastery",u:6},
{w:"intersection",c:"B1",s:"CEFR-J",p:"noun",ar:"تقاطع",een:"There is a traffic light at every intersection.",ear:"يوجد إشارة مرور عند كل تقاطع.",def:"the place where two roads cross each other",t:"mastery",u:6},
{w:"inclusive",c:"B1",s:"NGSL",p:"adjective",ar:"شامل للجميع",een:"An inclusive city is designed for all people.",ear:"المدينة الشاملة مصممة لجميع الناس.",def:"welcoming and open to everyone",t:"mastery",u:6},
{w:"livable",c:"B1",s:"CEFR-J",p:"adjective",ar:"صالح للعيش",een:"Clean air and parks make a city livable.",ear:"الهواء النظيف والحدائق تجعل المدينة صالحة للعيش.",def:"good enough to live in comfortably",t:"mastery",u:6},
{w:"overcrowded",c:"B1",s:"CEFR-J",p:"adjective",ar:"مكتظ",een:"Overcrowded buses are a problem in many cities.",ear:"الحافلات المكتظة مشكلة في كثير من المدن.",def:"having too many people in a small space",t:"mastery",u:6},
{w:"relocate",c:"B1",s:"NGSL",p:"verb",ar:"ينتقل",een:"Many companies relocate to cities with good transport.",ear:"تنتقل شركات كثيرة إلى مدن بها نقل جيد.",def:"to move to a new place",t:"mastery",u:6},
{w:"gentrification",c:"B1",s:"CEFR-J",p:"noun",ar:"تحسين الأحياء",een:"Gentrification made the old neighborhood more expensive.",ear:"جعل تحسين الأحياء الحي القديم أكثر تكلفة.",def:"when a poor area becomes expensive after improvements",t:"mastery",u:6},
{w:"carbon footprint",c:"B1",s:"CEFR-J",p:"noun",ar:"بصمة كربونية",een:"Smart cities try to lower their carbon footprint.",ear:"تحاول المدن الذكية تقليل بصمتها الكربونية.",def:"the amount of harmful gas a person or place makes",t:"mastery",u:6},

// ============ UNIT 7: Digital Detox ============
// CORE (34)
{w:"habit",c:"A2",s:"NGSL",p:"noun",ar:"عادة",een:"Checking your phone every minute is a bad habit.",ear:"التحقق من هاتفك كل دقيقة عادة سيئة.",def:"something you do often without thinking about it",t:"core",u:7},
{w:"distract",c:"A2",s:"NGSL",p:"verb",ar:"يُشتّت الانتباه",een:"Loud notifications distract me when I study.",ear:"الإشعارات الصاخبة تشتت انتباهي عندما أدرس.",def:"to take someone's attention away from something",t:"core",u:7},
{w:"balance",c:"A2",s:"NGSL",p:"noun",ar:"توازن",een:"You need a good balance between work and rest.",ear:"تحتاج توازناً جيداً بين العمل والراحة.",def:"when two things are equal in amount",t:"core",u:7},
{w:"limit",c:"A2",s:"NGSL",p:"verb",ar:"يُحدّد",een:"I try to limit my screen time to two hours.",ear:"أحاول تحديد وقت الشاشة بساعتين.",def:"to control how much of something is allowed",t:"core",u:7},
{w:"mental",c:"A2",s:"NGSL",p:"adjective",ar:"عقلي",een:"Too much screen time can affect your mental health.",ear:"الوقت الطويل أمام الشاشة يؤثر على صحتك العقلية.",def:"related to your mind and thinking",t:"core",u:7},
{w:"stress",c:"A2",s:"NGSL",p:"noun",ar:"إجهاد",een:"Social media can cause a lot of stress.",ear:"وسائل التواصل الاجتماعي قد تسبب الكثير من الإجهاد.",def:"a feeling of worry caused by problems",t:"core",u:7},
{w:"aware",c:"A2",s:"NGSL",p:"adjective",ar:"مُدرك",een:"Are you aware of how much time you spend online?",ear:"هل أنت مدرك لمقدار الوقت الذي تقضيه على الإنترنت؟",def:"knowing that something exists or is happening",t:"core",u:7},
{w:"affect",c:"A2",s:"NGSL",p:"verb",ar:"يؤثّر",een:"Bad sleep can affect your mood all day.",ear:"النوم السيئ يمكن أن يؤثر على مزاجك طوال اليوم.",def:"to cause a change in someone or something",t:"core",u:7},
{w:"mood",c:"A2",s:"CEFR-J",p:"noun",ar:"مزاج",een:"A walk outside can improve your mood quickly.",ear:"المشي في الخارج يمكن أن يحسّن مزاجك بسرعة.",def:"the way you feel at a particular time",t:"core",u:7},
{w:"bored",c:"A1",s:"CEFR-J",p:"adjective",ar:"يشعر بالملل",een:"I feel bored when I cannot use my phone.",ear:"أشعر بالملل عندما لا أستطيع استخدام هاتفي.",def:"feeling tired because nothing is interesting",t:"core",u:7},
{w:"advantage",c:"A2",s:"NGSL",p:"noun",ar:"فائدة",een:"One advantage of reading is better sleep.",ear:"إحدى فوائد القراءة هي نوم أفضل.",def:"something good that helps you",t:"core",u:7},
{w:"instead",c:"A2",s:"NGSL",p:"adverb",ar:"بدلاً من ذلك",een:"Turn off your phone and read a book instead.",ear:"أطفئ هاتفك واقرأ كتاباً بدلاً من ذلك.",def:"in place of something else",t:"core",u:7},
{w:"cut down",c:"A2",s:"CEFR-J",p:"verb",ar:"يُقلّل",een:"She wants to cut down her daily screen time.",ear:"تريد تقليل وقت الشاشة اليومي.",def:"to do less of something",t:"core",u:7},
{w:"purpose",c:"A2",s:"NGSL",p:"noun",ar:"هدف",een:"Use your phone with a clear purpose.",ear:"استخدم هاتفك بهدف واضح.",def:"the reason why you do something",t:"core",u:7},
{w:"notice",c:"A2",s:"NGSL",p:"verb",ar:"يلاحظ",een:"Did you notice how quiet the room is?",ear:"هل لاحظت كم الغرفة هادئة؟",def:"to see or become aware of something",t:"core",u:7},
{w:"lonely",c:"A2",s:"CEFR-J",p:"adjective",ar:"وحيد",een:"Some people feel lonely after too much social media.",ear:"يشعر بعض الناس بالوحدة بعد كثرة وسائل التواصل.",def:"feeling sad because you are alone",t:"core",u:7},
{w:"pressure",c:"A2",s:"NGSL",p:"noun",ar:"ضغط",een:"There is pressure to look perfect online.",ear:"هناك ضغط لتبدو مثالياً على الإنترنت.",def:"a feeling that you must do something",t:"core",u:7},
{w:"swap",c:"A2",s:"CEFR-J",p:"verb",ar:"يُبدّل",een:"Can you swap gaming with outdoor activities?",ear:"هل يمكنك تبديل الألعاب بأنشطة خارجية؟",def:"to give one thing and get another in return",t:"core",u:7},
{w:"daily",c:"A2",s:"NGSL",p:"adjective",ar:"يومي",een:"I set a daily limit for social media use.",ear:"وضعت حداً يومياً لاستخدام وسائل التواصل.",def:"happening every day",t:"core",u:7},
{w:"ignore",c:"A2",s:"NGSL",p:"verb",ar:"يتجاهل",een:"Try to ignore your phone during dinner.",ear:"حاول تجاهل هاتفك أثناء العشاء.",def:"to not pay attention to something on purpose",t:"core",u:7},
{w:"conversation",c:"A2",s:"NGSL",p:"noun",ar:"محادثة",een:"Put your phone away and have a real conversation.",ear:"ضع هاتفك جانباً وأجرِ محادثة حقيقية.",def:"when people talk to each other",t:"core",u:7},
{w:"suggest",c:"A2",s:"NGSL",p:"verb",ar:"يقترح",een:"Doctors suggest taking breaks from screens every hour.",ear:"يقترح الأطباء أخذ استراحات من الشاشات كل ساعة.",def:"to give an idea for someone to think about",t:"core",u:7},
{w:"boost",c:"A2",s:"CEFR-J",p:"verb",ar:"يعزّز",een:"Less screen time can boost your sleep quality.",ear:"تقليل وقت الشاشة يمكن أن يعزّز جودة نومك.",def:"to make something better or increase it",t:"core",u:7},
{w:"negative",c:"A2",s:"NGSL",p:"adjective",ar:"سلبي",een:"Too many negative comments online can hurt.",ear:"الكثير من التعليقات السلبية على الإنترنت قد تؤذي.",def:"bad or harmful",t:"core",u:7},
{w:"measure",c:"A2",s:"NGSL",p:"verb",ar:"يقيس",een:"There are apps that measure your screen time.",ear:"هناك تطبيقات تقيس وقت شاشتك.",def:"to find out the size or amount of something",t:"core",u:7},
{w:"avoid",c:"A2",s:"NGSL",p:"verb",ar:"يتجنّب",een:"I try to avoid using my phone in bed.",ear:"أحاول تجنّب استخدام هاتفي في السرير.",def:"to stay away from something",t:"core",u:7},
{w:"activity",c:"A2",s:"NGSL",p:"noun",ar:"نشاط",een:"Choose a fun activity that does not need a screen.",ear:"اختر نشاطاً ممتعاً لا يحتاج شاشة.",def:"something that you do for fun or a purpose",t:"core",u:7},
{w:"addict",c:"A2",s:"CEFR-J",p:"noun",ar:"مُدمن",een:"He became a phone addict without realizing it.",ear:"أصبح مدمناً على الهاتف دون أن يدرك.",def:"a person who cannot stop doing something",t:"core",u:7},
{w:"cope",c:"A2",s:"NGSL",p:"verb",ar:"يتعامل مع",een:"Many teenagers find it hard to cope without phones.",ear:"يجد كثير من المراهقين صعوبة في التعامل بدون هواتف.",def:"to deal with a difficult situation",t:"core",u:7},
{w:"calm",c:"A2",s:"CEFR-J",p:"adjective",ar:"هادئ",een:"I feel calm after spending time without my phone.",ear:"أشعر بالهدوء بعد قضاء وقت بدون هاتفي.",def:"peaceful and not worried",t:"core",u:7},
{w:"real",c:"A1",s:"NGSL",p:"adjective",ar:"حقيقي",een:"Real friendships are more important than online ones.",ear:"الصداقات الحقيقية أهم من صداقات الإنترنت.",def:"true and not imagined or online",t:"core",u:7},
{w:"opinion",c:"A2",s:"NGSL",p:"noun",ar:"رأي",een:"Everyone has an opinion about screen time.",ear:"لكل شخص رأي حول وقت الشاشة.",def:"what you think about something",t:"core",u:7},
{w:"attention",c:"A2",s:"NGSL",p:"noun",ar:"انتباه",een:"Social media wants to keep your attention all day.",ear:"تريد وسائل التواصل الحفاظ على انتباهك طوال اليوم.",def:"when you watch or listen to something carefully",t:"core",u:7},
{w:"alone",c:"A1",s:"NGSL",p:"adverb",ar:"وحيداً",een:"Spending time alone without screens can be healthy.",ear:"قضاء الوقت وحيداً بدون شاشات يمكن أن يكون صحياً.",def:"without other people around you",t:"core",u:7},
// EXTENDED (29)
{w:"unplug",c:"A2",s:"CEFR-J",p:"verb",ar:"يفصل الاتصال",een:"I try to unplug from technology every weekend.",ear:"أحاول فصل الاتصال بالتكنولوجيا كل نهاية أسبوع.",def:"to stop using electronic devices for a while",t:"extended",u:7},
{w:"mindful",c:"B1",s:"CEFR-J",p:"adjective",ar:"واعٍ",een:"Be mindful of how you spend your free time.",ear:"كن واعياً لكيفية قضاء وقت فراغك.",def:"paying careful attention to what you are doing",t:"extended",u:7},
{w:"overwhelm",c:"A2",s:"NGSL",p:"verb",ar:"يُرهق",een:"Too many messages can overwhelm you easily.",ear:"كثرة الرسائل يمكن أن تُرهقك بسهولة.",def:"to give someone too much to deal with",t:"extended",u:7},
{w:"boundary",c:"B1",s:"NGSL",p:"noun",ar:"حدود",een:"Set clear boundaries for your phone use.",ear:"ضع حدوداً واضحة لاستخدام هاتفك.",def:"a line or limit that separates two things",t:"extended",u:7},
{w:"refresh",c:"A2",s:"CEFR-J",p:"verb",ar:"يُنعش",een:"A break from screens will refresh your mind.",ear:"الاستراحة من الشاشات ستُنعش عقلك.",def:"to make something feel new and fresh again",t:"extended",u:7},
{w:"peer",c:"A2",s:"NGSL",p:"noun",ar:"قرين",een:"Peer pressure can make teens use more social media.",ear:"ضغط الأقران يمكن أن يجعل المراهقين يستخدمون وسائل التواصل أكثر.",def:"a person who is the same age as you",t:"extended",u:7},
{w:"productive",c:"A2",s:"NGSL",p:"adjective",ar:"مُنتِج",een:"I am more productive when my phone is off.",ear:"أكون أكثر إنتاجية عندما يكون هاتفي مغلقاً.",def:"doing a lot of useful work",t:"extended",u:7},
{w:"interrupt",c:"A2",s:"NGSL",p:"verb",ar:"يقاطع",een:"Phone calls always interrupt my study time.",ear:"المكالمات الهاتفية تقاطع دائماً وقت دراستي.",def:"to stop something from continuing",t:"extended",u:7},
{w:"resist",c:"A2",s:"NGSL",p:"verb",ar:"يقاوم",een:"It is hard to resist checking your phone.",ear:"من الصعب مقاومة التحقق من هاتفك.",def:"to stop yourself from doing something",t:"extended",u:7},
{w:"willpower",c:"B1",s:"CEFR-J",p:"noun",ar:"قوة إرادة",een:"You need willpower to stay off social media.",ear:"تحتاج قوة إرادة للابتعاد عن وسائل التواصل.",def:"the strength to control your own actions",t:"extended",u:7},
{w:"tempt",c:"A2",s:"CEFR-J",p:"verb",ar:"يُغري",een:"Bright notifications tempt you to check your phone.",ear:"الإشعارات الملونة تُغريك للتحقق من هاتفك.",def:"to make someone want to do something",t:"extended",u:7},
{w:"consequence",c:"A2",s:"NGSL",p:"noun",ar:"نتيجة",een:"Poor sleep is a consequence of too much screen time.",ear:"النوم السيئ نتيجة لكثرة وقت الشاشة.",def:"the result of something that happened",t:"extended",u:7},
{w:"urge",c:"A2",s:"NGSL",p:"noun",ar:"رغبة ملحّة",een:"I felt a strong urge to check my messages.",ear:"شعرت برغبة ملحّة للتحقق من رسائلي.",def:"a strong wish to do something",t:"extended",u:7},
{w:"interact",c:"A2",s:"NGSL",p:"verb",ar:"يتفاعل",een:"Children should interact with people face to face.",ear:"يجب أن يتفاعل الأطفال مع الناس وجهاً لوجه.",def:"to talk to or spend time with others",t:"extended",u:7},
{w:"patience",c:"A2",s:"NGSL",p:"noun",ar:"صبر",een:"A digital detox requires a lot of patience.",ear:"يتطلب التخلص من الأجهزة الرقمية الكثير من الصبر.",def:"being able to wait calmly for something",t:"extended",u:7},
{w:"routine",c:"A2",s:"NGSL",p:"noun",ar:"روتين",een:"A good morning routine should not include phones.",ear:"الروتين الصباحي الجيد يجب ألا يتضمن الهواتف.",def:"the usual things you do every day",t:"extended",u:7},
{w:"socialize",c:"A2",s:"CEFR-J",p:"verb",ar:"يتواصل اجتماعياً",een:"It is important to socialize without screens.",ear:"من المهم التواصل الاجتماعي بدون شاشات.",def:"to spend time talking with other people",t:"extended",u:7},
{w:"wellbeing",c:"B1",s:"CEFR-J",p:"noun",ar:"رفاهية",een:"Your wellbeing matters more than your follower count.",ear:"رفاهيتك أهم من عدد متابعيك.",def:"the state of being healthy and happy",t:"extended",u:7},
{w:"expose",c:"A2",s:"NGSL",p:"verb",ar:"يُعرّض",een:"Do not expose children to too much screen time.",ear:"لا تُعرّض الأطفال لوقت شاشة كثير.",def:"to put someone in a situation that may be harmful",t:"extended",u:7},
{w:"self-control",c:"B1",s:"CEFR-J",p:"noun",ar:"ضبط النفس",een:"Self-control helps you use your phone less.",ear:"ضبط النفس يساعدك على استخدام هاتفك أقل.",def:"the ability to control your feelings and actions",t:"extended",u:7},
{w:"detach",c:"B1",s:"CEFR-J",p:"verb",ar:"ينفصل",een:"Try to detach from your devices at night.",ear:"حاول الانفصال عن أجهزتك في الليل.",def:"to separate yourself from something",t:"extended",u:7},
{w:"therapy",c:"B1",s:"NGSL",p:"noun",ar:"علاج",een:"Some people need therapy for phone addiction.",ear:"يحتاج بعض الناس علاجاً لإدمان الهاتف.",def:"treatment to help with mental or physical problems",t:"extended",u:7},
{w:"distraction",c:"A2",s:"NGSL",p:"noun",ar:"تشتيت",een:"Social media is the biggest distraction for students.",ear:"وسائل التواصل الاجتماعي أكبر تشتيت للطلاب.",def:"something that takes your attention away",t:"extended",u:7},
{w:"alert",c:"A2",s:"NGSL",p:"noun",ar:"تنبيه",een:"I turned off all alerts on my phone.",ear:"أطفأت جميع التنبيهات على هاتفي.",def:"a message that tells you about something",t:"extended",u:7},
{w:"uneasy",c:"A2",s:"CEFR-J",p:"adjective",ar:"غير مرتاح",een:"She feels uneasy when her phone battery dies.",ear:"تشعر بعدم الارتياح عندما تنفد بطارية هاتفها.",def:"feeling slightly worried or uncomfortable",t:"extended",u:7},
{w:"method",c:"A2",s:"NGSL",p:"noun",ar:"طريقة",een:"This method helps you use your phone less.",ear:"هذه الطريقة تساعدك على استخدام هاتفك أقل.",def:"a way of doing something",t:"extended",u:7},
{w:"silence",c:"A2",s:"NGSL",p:"noun",ar:"صمت",een:"Enjoy the silence when you turn off your phone.",ear:"استمتع بالصمت عندما تطفئ هاتفك.",def:"when there is no sound at all",t:"extended",u:7},
{w:"rely",c:"A2",s:"NGSL",p:"verb",ar:"يعتمد",een:"We rely too much on our phones these days.",ear:"نعتمد كثيراً على هواتفنا هذه الأيام.",def:"to need and depend on something",t:"extended",u:7},
{w:"harm",c:"A2",s:"NGSL",p:"noun",ar:"ضرر",een:"Too much screen time can cause real harm.",ear:"كثرة وقت الشاشة يمكن أن تسبب ضرراً حقيقياً.",def:"damage or injury",t:"extended",u:7},
// MASTERY (25)
{w:"compulsive",c:"B1",s:"CEFR-J",p:"adjective",ar:"قهري",een:"Compulsive phone checking is a modern problem.",ear:"التحقق القهري من الهاتف مشكلة حديثة.",def:"doing something again and again and unable to stop",t:"mastery",u:7},
{w:"overstimulate",c:"B1",s:"CEFR-J",p:"verb",ar:"يُفرط في تحفيز",een:"Bright screens overstimulate your brain before sleep.",ear:"الشاشات الساطعة تُفرط في تحفيز دماغك قبل النوم.",def:"to give too much activity to the mind or senses",t:"mastery",u:7},
{w:"dopamine",c:"B1",s:"CEFR-J",p:"noun",ar:"دوبامين",een:"Social media likes give you a small dopamine rush.",ear:"إعجابات وسائل التواصل تمنحك دفعة دوبامين صغيرة.",def:"a chemical in the brain that makes you feel good",t:"mastery",u:7},
{w:"withdrawal",c:"B1",s:"CEFR-J",p:"noun",ar:"أعراض انسحاب",een:"He felt withdrawal symptoms after quitting social media.",ear:"شعر بأعراض انسحاب بعد ترك وسائل التواصل.",def:"bad feelings when you stop doing something you need",t:"mastery",u:7},
{w:"moderation",c:"B1",s:"CEFR-J",p:"noun",ar:"اعتدال",een:"Using technology in moderation is the key.",ear:"استخدام التكنولوجيا باعتدال هو المفتاح.",def:"not doing too much or too little of something",t:"mastery",u:7},
{w:"log off",c:"A2",s:"CEFR-J",p:"verb",ar:"يسجّل الخروج",een:"I log off from all social media every Sunday.",ear:"أسجّل الخروج من جميع وسائل التواصل كل يوم أحد.",def:"to stop using a computer or website",t:"mastery",u:7},
{w:"excessive",c:"B1",s:"NGSL",p:"adjective",ar:"مُفرط",een:"Excessive phone use can cause eye problems.",ear:"الاستخدام المفرط للهاتف قد يسبب مشاكل في العيون.",def:"more than what is normal or needed",t:"mastery",u:7},
{w:"impulse",c:"B1",s:"CEFR-J",p:"noun",ar:"اندفاع",een:"She resisted the impulse to check her phone.",ear:"قاومت اندفاعها للتحقق من هاتفها.",def:"a sudden strong wish to do something",t:"mastery",u:7},
{w:"meditation",c:"B1",s:"CEFR-J",p:"noun",ar:"تأمّل",een:"Meditation helps calm your mind after a long day.",ear:"يساعد التأمّل على تهدئة عقلك بعد يوم طويل.",def:"sitting quietly to make your mind calm and clear",t:"mastery",u:7},
{w:"fatigue",c:"B1",s:"CEFR-J",p:"noun",ar:"إرهاق",een:"Screen fatigue makes your eyes feel dry and tired.",ear:"إرهاق الشاشة يجعل عينيك تشعران بالجفاف والتعب.",def:"a feeling of being very tired",t:"mastery",u:7},
{w:"conscious",c:"B1",s:"NGSL",p:"adjective",ar:"واعٍ",een:"Be conscious of how much you use your phone.",ear:"كن واعياً لمقدار استخدامك لهاتفك.",def:"knowing and paying attention to something",t:"mastery",u:7},
{w:"validate",c:"B1",s:"CEFR-J",p:"verb",ar:"يُصادق على",een:"You do not need likes to validate your worth.",ear:"لا تحتاج إعجابات لتصادق على قيمتك.",def:"to make someone feel that they are important",t:"mastery",u:7},
{w:"isolate",c:"B1",s:"NGSL",p:"verb",ar:"يعزل",een:"Too much screen time can isolate you from friends.",ear:"كثرة وقت الشاشة يمكن أن تعزلك عن الأصدقاء.",def:"to keep someone apart from other people",t:"mastery",u:7},
{w:"prioritize",c:"B1",s:"NGSL",p:"verb",ar:"يُعطي الأولوية",een:"Prioritize real experiences over online ones.",ear:"أعطِ الأولوية للتجارب الحقيقية على تلك الإلكترونية.",def:"to decide what is most important to do first",t:"mastery",u:7},
{w:"normalize",c:"B1",s:"CEFR-J",p:"verb",ar:"يُطبّع",een:"Society has normalized being online all the time.",ear:"طبّع المجتمع البقاء على الإنترنت طوال الوقت.",def:"to make something seem normal and acceptable",t:"mastery",u:7},
{w:"deprive",c:"B1",s:"CEFR-J",p:"verb",ar:"يحرم",een:"Phone use at night can deprive you of sleep.",ear:"استخدام الهاتف ليلاً يمكن أن يحرمك من النوم.",def:"to stop someone from having something they need",t:"mastery",u:7},
{w:"restless",c:"B1",s:"CEFR-J",p:"adjective",ar:"قلِق",een:"I feel restless when I cannot check my messages.",ear:"أشعر بالقلق عندما لا أستطيع التحقق من رسائلي.",def:"unable to stay still or relax",t:"mastery",u:7},
{w:"intentional",c:"B1",s:"CEFR-J",p:"adjective",ar:"مقصود",een:"Be intentional about how you use your time online.",ear:"كن مقصوداً في كيفية استخدامك لوقتك على الإنترنت.",def:"done on purpose and with a plan",t:"mastery",u:7},
{w:"self-esteem",c:"B1",s:"CEFR-J",p:"noun",ar:"تقدير الذات",een:"Too much social media can lower your self-esteem.",ear:"كثرة وسائل التواصل يمكن أن تقلّل تقدير ذاتك.",def:"how much you like and value yourself",t:"mastery",u:7},
{w:"stimulate",c:"B1",s:"NGSL",p:"verb",ar:"يحفّز",een:"Outdoor activities stimulate your mind better than screens.",ear:"الأنشطة الخارجية تحفّز عقلك أفضل من الشاشات.",def:"to make something more active or interested",t:"mastery",u:7},
{w:"obsess",c:"B1",s:"CEFR-J",p:"verb",ar:"يستحوذ على",een:"Do not obsess over how many likes you get.",ear:"لا تهتم بشكل مفرط بعدد الإعجابات التي تحصل عليها.",def:"to think about something too much",t:"mastery",u:7},
{w:"procrastinate",c:"B1",s:"CEFR-J",p:"verb",ar:"يُماطل",een:"I procrastinate by watching videos on my phone.",ear:"أُماطل بمشاهدة مقاطع فيديو على هاتفي.",def:"to delay doing something you should do",t:"mastery",u:7},
{w:"ping",c:"A2",s:"CEFR-J",p:"noun",ar:"تنبيه هاتفي",een:"Every ping from my phone breaks my focus.",ear:"كل تنبيه من هاتفي يكسر تركيزي.",def:"a short sound from a phone or computer",t:"mastery",u:7},
{w:"detox",c:"B1",s:"CEFR-J",p:"noun",ar:"تخلّص من السموم",een:"A digital detox means no screens for a few days.",ear:"التخلّص الرقمي يعني لا شاشات لبضعة أيام.",def:"a period of avoiding something unhealthy",t:"mastery",u:7},
{w:"screentime",c:"B1",s:"CEFR-J",p:"noun",ar:"وقت الشاشة",een:"Reducing screentime helps you sleep much better.",ear:"تقليل وقت الشاشة يساعدك على النوم بشكل أفضل.",def:"the time spent looking at a phone or computer",t:"mastery",u:7},

// ============ UNIT 8: Mountain Adventures ============
// CORE (34)
{w:"peak",c:"A2",s:"CEFR-J",p:"noun",ar:"قمة",een:"We reached the peak of the mountain at noon.",ear:"وصلنا إلى قمة الجبل عند الظهيرة.",def:"the very top of a mountain",t:"core",u:8},
{w:"valley",c:"A2",s:"CEFR-J",p:"noun",ar:"وادي",een:"A beautiful river flows through the green valley.",ear:"يتدفق نهر جميل عبر الوادي الأخضر.",def:"low land between two mountains or hills",t:"core",u:8},
{w:"cliff",c:"A2",s:"CEFR-J",p:"noun",ar:"جُرف",een:"Do not stand too close to the edge of the cliff.",ear:"لا تقف قريباً جداً من حافة الجرف.",def:"a high steep face of rock",t:"core",u:8},
{w:"steep",c:"A2",s:"CEFR-J",p:"adjective",ar:"شديد الانحدار",een:"The path was very steep and hard to climb.",ear:"كان المسار شديد الانحدار وصعب التسلّق.",def:"going up at a very sharp angle",t:"core",u:8},
{w:"rope",c:"A1",s:"CEFR-J",p:"noun",ar:"حبل",een:"The climbers used a strong rope for safety.",ear:"استخدم المتسلقون حبلاً قوياً للسلامة.",def:"thick strong string used for tying or climbing",t:"core",u:8},
{w:"camp",c:"A1",s:"CEFR-J",p:"noun",ar:"مخيّم",een:"We set up camp near the river.",ear:"أقمنا المخيّم بالقرب من النهر.",def:"a place where people stay in tents",t:"core",u:8},
{w:"scenery",c:"A2",s:"CEFR-J",p:"noun",ar:"مناظر طبيعية",een:"The mountain scenery was absolutely amazing.",ear:"كانت المناظر الطبيعية الجبلية مذهلة تماماً.",def:"the natural beauty you see around you outside",t:"core",u:8},
{w:"slope",c:"A2",s:"CEFR-J",p:"noun",ar:"منحدر",een:"Children were playing on the grassy slope.",ear:"كان الأطفال يلعبون على المنحدر العشبي.",def:"ground that goes up or down at an angle",t:"core",u:8},
{w:"altitude",c:"B1",s:"CEFR-J",p:"noun",ar:"ارتفاع",een:"It is hard to breathe at high altitude.",ear:"من الصعب التنفس على ارتفاع عالٍ.",def:"how high a place is above the sea",t:"core",u:8},
{w:"tent",c:"A1",s:"CEFR-J",p:"noun",ar:"خيمة",een:"We slept in a small tent near the lake.",ear:"نمنا في خيمة صغيرة بالقرب من البحيرة.",def:"a cover made of cloth used for camping",t:"core",u:8},
{w:"gear",c:"A2",s:"CEFR-J",p:"noun",ar:"معدّات",een:"Make sure you have the right gear for hiking.",ear:"تأكد أن لديك المعدّات المناسبة للتنزه.",def:"equipment and clothes for a particular activity",t:"core",u:8},
{w:"path",c:"A1",s:"CEFR-J",p:"noun",ar:"طريق",een:"Follow the path and you will reach the waterfall.",ear:"اتبع الطريق وستصل إلى الشلال.",def:"a narrow way for walking",t:"core",u:8},
{w:"wander",c:"A2",s:"CEFR-J",p:"verb",ar:"يتجوّل",een:"We wandered through the forest for hours.",ear:"تجوّلنا في الغابة لساعات.",def:"to walk slowly without a clear direction",t:"core",u:8},
{w:"summit",c:"B1",s:"CEFR-J",p:"noun",ar:"قمة الجبل",een:"The view from the summit was incredible.",ear:"كان المنظر من القمة مذهلاً.",def:"the highest point of a mountain",t:"core",u:8},
{w:"waterfall",c:"A2",s:"CEFR-J",p:"noun",ar:"شلال",een:"The waterfall drops fifty meters into the pool below.",ear:"ينزل الشلال خمسين متراً إلى البركة أسفله.",def:"water that falls from a high place to a low place",t:"core",u:8},
{w:"danger",c:"A2",s:"NGSL",p:"noun",ar:"خطر",een:"There is a danger of falling rocks on this path.",ear:"هناك خطر سقوط صخور على هذا المسار.",def:"a situation that could hurt you",t:"core",u:8},
{w:"rock",c:"A1",s:"CEFR-J",p:"noun",ar:"صخرة",een:"Be careful of the loose rocks on the trail.",ear:"احذر من الصخور المتحركة على المسار.",def:"a large hard piece of stone",t:"core",u:8},
{w:"range",c:"A2",s:"NGSL",p:"noun",ar:"سلسلة جبال",een:"The mountain range stretches for hundreds of kilometers.",ear:"تمتد سلسلة الجبال لمئات الكيلومترات.",def:"a line of mountains connected together",t:"core",u:8},
{w:"view",c:"A2",s:"NGSL",p:"noun",ar:"منظر",een:"The view from the top is worth the long walk.",ear:"المنظر من الأعلى يستحق المشي الطويل.",def:"what you can see from a particular place",t:"core",u:8},
{w:"survival",c:"A2",s:"NGSL",p:"noun",ar:"بقاء",een:"Learning survival skills is important for hikers.",ear:"تعلّم مهارات البقاء مهم للمتنزهين.",def:"staying alive in a dangerous situation",t:"core",u:8},
{w:"forecast",c:"A2",s:"CEFR-J",p:"noun",ar:"توقعات جوية",een:"Always check the forecast before hiking.",ear:"تحقّق دائماً من التوقعات الجوية قبل التنزه.",def:"a report about what the weather will be",t:"core",u:8},
{w:"compass",c:"A2",s:"CEFR-J",p:"noun",ar:"بوصلة",een:"A compass helps you find your way in the woods.",ear:"تساعدك البوصلة في إيجاد طريقك في الغابة.",def:"a tool that shows which direction is north",t:"core",u:8},
{w:"sunrise",c:"A2",s:"CEFR-J",p:"noun",ar:"شروق الشمس",een:"We woke up early to watch the sunrise.",ear:"استيقظنا باكراً لمشاهدة شروق الشمس.",def:"when the sun comes up in the morning",t:"core",u:8},
{w:"sunset",c:"A2",s:"CEFR-J",p:"noun",ar:"غروب الشمس",een:"The sunset painted the sky orange and pink.",ear:"لوّن الغروب السماء بالبرتقالي والوردي.",def:"when the sun goes down in the evening",t:"core",u:8},
{w:"hiker",c:"A2",s:"CEFR-J",p:"noun",ar:"متنزّه",een:"The hiker carried a big backpack up the mountain.",ear:"حمل المتنزّه حقيبة ظهر كبيرة إلى أعلى الجبل.",def:"a person who walks long distances in nature",t:"core",u:8},
{w:"descend",c:"B1",s:"CEFR-J",p:"verb",ar:"ينزل",een:"It took three hours to descend from the mountain.",ear:"استغرق الأمر ثلاث ساعات للنزول من الجبل.",def:"to go down from a high place",t:"core",u:8},
{w:"effort",c:"A2",s:"NGSL",p:"noun",ar:"جهد",een:"The climb to the top took a lot of effort.",ear:"استغرق التسلق إلى القمة الكثير من الجهد.",def:"the energy and work needed to do something",t:"core",u:8},
{w:"adventure",c:"A2",s:"CEFR-J",p:"noun",ar:"مغامرة",een:"Climbing that mountain was a great adventure.",ear:"كان تسلّق ذلك الجبل مغامرة رائعة.",def:"an exciting experience that may be dangerous",t:"core",u:8},
{w:"wilderness",c:"B1",s:"CEFR-J",p:"noun",ar:"بَريّة",een:"They spent a week alone in the wilderness.",ear:"أمضوا أسبوعاً وحدهم في البريّة.",def:"a wild natural area with no people living in it",t:"core",u:8},
{w:"creek",c:"A2",s:"CEFR-J",p:"noun",ar:"جدول مائي",een:"We drank clean water from the mountain creek.",ear:"شربنا ماءً نظيفاً من الجدول الجبلي.",def:"a small narrow river or stream",t:"core",u:8},
{w:"risk",c:"A2",s:"NGSL",p:"noun",ar:"مخاطرة",een:"There is always a risk when climbing mountains.",ear:"هناك دائماً مخاطرة عند تسلّق الجبال.",def:"the chance that something bad might happen",t:"core",u:8},
{w:"exhausted",c:"A2",s:"CEFR-J",p:"adjective",ar:"منهك",een:"We were exhausted after the ten-hour hike.",ear:"كنا منهكين بعد التنزه لعشر ساعات.",def:"extremely tired with no energy left",t:"core",u:8},
{w:"pine",c:"A2",s:"CEFR-J",p:"noun",ar:"صنوبر",een:"Tall pine trees grow on the mountainside.",ear:"تنمو أشجار صنوبر طويلة على جانب الجبل.",def:"a tree with thin sharp leaves that stays green all year",t:"core",u:8},
{w:"helmet",c:"A2",s:"CEFR-J",p:"noun",ar:"خوذة",een:"Always wear a helmet when climbing rocks.",ear:"ارتدِ دائماً خوذة عند تسلّق الصخور.",def:"a hard hat that protects your head",t:"core",u:8},
// EXTENDED (29)
{w:"terrain",c:"B1",s:"CEFR-J",p:"noun",ar:"تضاريس",een:"The rocky terrain made walking very difficult.",ear:"جعلت التضاريس الصخرية المشي صعباً جداً.",def:"the type of land in an area",t:"extended",u:8},
{w:"boulder",c:"B1",s:"CEFR-J",p:"noun",ar:"صخرة كبيرة",een:"A huge boulder blocked the mountain path.",ear:"سدّت صخرة كبيرة المسار الجبلي.",def:"a very large round rock",t:"extended",u:8},
{w:"ridge",c:"B1",s:"CEFR-J",p:"noun",ar:"حافة جبلية",een:"We walked along the narrow ridge carefully.",ear:"مشينا على الحافة الجبلية الضيقة بعناية.",def:"a long narrow top of a mountain",t:"extended",u:8},
{w:"plateau",c:"B1",s:"CEFR-J",p:"noun",ar:"هضبة",een:"The plateau was flat and covered with grass.",ear:"كانت الهضبة مسطحة ومغطاة بالعشب.",def:"a large flat area of high land",t:"extended",u:8},
{w:"avalanche",c:"B1",s:"CEFR-J",p:"noun",ar:"انهيار ثلجي",een:"An avalanche can happen after heavy snowfall.",ear:"يمكن أن يحدث انهيار ثلجي بعد تساقط ثلوج كثيفة.",def:"a large amount of snow falling down a mountain",t:"extended",u:8},
{w:"navigate",c:"A2",s:"NGSL",p:"verb",ar:"يتنقّل",een:"It is hard to navigate in fog without a compass.",ear:"من الصعب التنقّل في الضباب بدون بوصلة.",def:"to find your way from one place to another",t:"extended",u:8},
{w:"elevation",c:"B1",s:"CEFR-J",p:"noun",ar:"ارتفاع عن سطح البحر",een:"The camp is at an elevation of 3000 meters.",ear:"يقع المخيم على ارتفاع 3000 متر.",def:"the height of a place above the sea",t:"extended",u:8},
{w:"trek",c:"A2",s:"CEFR-J",p:"verb",ar:"يقطع مسافة طويلة سيراً",een:"We trekked for five days through the mountains.",ear:"سِرنا لخمسة أيام عبر الجبال.",def:"to walk a long distance over difficult land",t:"extended",u:8},
{w:"gorge",c:"B1",s:"CEFR-J",p:"noun",ar:"مضيق",een:"The river runs through a deep gorge.",ear:"يجري النهر عبر مضيق عميق.",def:"a narrow valley with steep sides",t:"extended",u:8},
{w:"ledge",c:"B1",s:"CEFR-J",p:"noun",ar:"حافة صخرية",een:"The climber rested on a small ledge.",ear:"استراح المتسلق على حافة صخرية صغيرة.",def:"a narrow flat surface on the side of a cliff",t:"extended",u:8},
{w:"harness",c:"B1",s:"CEFR-J",p:"noun",ar:"حزام أمان",een:"Always wear a harness when rock climbing.",ear:"ارتدِ دائماً حزام أمان عند تسلّق الصخور.",def:"straps worn around the body for safety",t:"extended",u:8},
{w:"foothold",c:"B1",s:"CEFR-J",p:"noun",ar:"موطئ قدم",een:"The climber searched for a foothold on the rock.",ear:"بحث المتسلق عن موطئ قدم على الصخرة.",def:"a place where you can put your foot when climbing",t:"extended",u:8},
{w:"foggy",c:"A2",s:"CEFR-J",p:"adjective",ar:"ضبابي",een:"It was too foggy to see the mountain top.",ear:"كان الجو ضبابياً جداً لرؤية قمة الجبل.",def:"full of thick cloud close to the ground",t:"extended",u:8},
{w:"rough",c:"A2",s:"NGSL",p:"adjective",ar:"وعِر",een:"The rough ground made the hike very slow.",ear:"جعلت الأرض الوعرة التنزه بطيئاً جداً.",def:"not smooth or even",t:"extended",u:8},
{w:"slippery",c:"A2",s:"CEFR-J",p:"adjective",ar:"زَلِق",een:"The rocks were wet and very slippery.",ear:"كانت الصخور مبللة وزلقة جداً.",def:"smooth and hard to stand on without falling",t:"extended",u:8},
{w:"campfire",c:"A2",s:"CEFR-J",p:"noun",ar:"نار المخيم",een:"We sat around the campfire and told stories.",ear:"جلسنا حول نار المخيم وروينا قصصاً.",def:"a fire made outside where people camp",t:"extended",u:8},
{w:"backpack",c:"A2",s:"CEFR-J",p:"noun",ar:"حقيبة ظهر",een:"My backpack was heavy with food and water.",ear:"كانت حقيبة ظهري ثقيلة بالطعام والماء.",def:"a bag you carry on your back",t:"extended",u:8},
{w:"rescue",c:"A2",s:"NGSL",p:"verb",ar:"ينقذ",een:"A helicopter came to rescue the injured climber.",ear:"جاءت مروحية لإنقاذ المتسلق المصاب.",def:"to save someone from a dangerous situation",t:"extended",u:8},
{w:"cautious",c:"B1",s:"CEFR-J",p:"adjective",ar:"حذِر",een:"Be cautious when walking near the edge.",ear:"كن حذراً عند المشي بالقرب من الحافة.",def:"being very careful to avoid problems",t:"extended",u:8},
{w:"endure",c:"B1",s:"NGSL",p:"verb",ar:"يتحمّل",een:"Climbers must endure cold and strong winds.",ear:"يجب على المتسلقين تحمّل البرد والرياح القوية.",def:"to suffer through something difficult",t:"extended",u:8},
{w:"isolated",c:"B1",s:"NGSL",p:"adjective",ar:"معزول",een:"The village is very isolated and hard to reach.",ear:"القرية معزولة جداً ويصعب الوصول إليها.",def:"far away from other places and people",t:"extended",u:8},
{w:"stamina",c:"B1",s:"CEFR-J",p:"noun",ar:"قدرة على التحمّل",een:"You need good stamina to climb for eight hours.",ear:"تحتاج قدرة تحمّل جيدة للتسلّق لثماني ساعات.",def:"the energy to do something for a long time",t:"extended",u:8},
{w:"overnight",c:"A2",s:"CEFR-J",p:"adverb",ar:"طوال الليل",een:"We stayed overnight at the mountain cabin.",ear:"بقينا طوال الليل في كوخ الجبل.",def:"for the whole night",t:"extended",u:8},
{w:"exposed",c:"B1",s:"NGSL",p:"adjective",ar:"مكشوف",een:"The exposed hilltop gets very strong winds.",ear:"تلقى قمة التل المكشوفة رياحاً قوية جداً.",def:"not protected from weather or danger",t:"extended",u:8},
{w:"cabin",c:"A2",s:"CEFR-J",p:"noun",ar:"كوخ",een:"The wooden cabin was warm and cozy inside.",ear:"كان الكوخ الخشبي دافئاً ومريحاً من الداخل.",def:"a small simple house made of wood",t:"extended",u:8},
{w:"marker",c:"A2",s:"CEFR-J",p:"noun",ar:"علامة",een:"Follow the red marker to stay on the trail.",ear:"اتبع العلامة الحمراء للبقاء على المسار.",def:"a sign that shows you where to go",t:"extended",u:8},
{w:"huddle",c:"A2",s:"CEFR-J",p:"verb",ar:"يتكوّم",een:"We huddled together to stay warm in the cold.",ear:"تكوّمنا معاً للبقاء دافئين في البرد.",def:"to get close together for warmth or safety",t:"extended",u:8},
{w:"blizzard",c:"B1",s:"CEFR-J",p:"noun",ar:"عاصفة ثلجية",een:"A sudden blizzard trapped the hikers on the mountain.",ear:"حاصرت عاصفة ثلجية مفاجئة المتنزهين على الجبل.",def:"a severe snowstorm with strong winds",t:"extended",u:8},
{w:"hydrate",c:"B1",s:"CEFR-J",p:"verb",ar:"يروي عطشه",een:"Remember to hydrate often when climbing in the heat.",ear:"تذكر أن تروي عطشك كثيراً عند التسلق في الحر.",def:"to drink enough water to stay healthy",t:"extended",u:8},
// MASTERY (25)
{w:"crevasse",c:"B1",s:"CEFR-J",p:"noun",ar:"شقّ جليدي",een:"The climber almost fell into a deep crevasse.",ear:"كاد المتسلق أن يسقط في شقّ جليدي عميق.",def:"a deep crack in thick ice or rock",t:"mastery",u:8},
{w:"acclimatize",c:"B1",s:"CEFR-J",p:"verb",ar:"يتأقلم",een:"Climbers must acclimatize to the thin air slowly.",ear:"يجب على المتسلقين التأقلم مع الهواء الرقيق ببطء.",def:"to get used to a new climate or conditions",t:"mastery",u:8},
{w:"treacherous",c:"B1",s:"CEFR-J",p:"adjective",ar:"غادر",een:"The icy road was treacherous in winter.",ear:"كان الطريق الجليدي غادراً في الشتاء.",def:"dangerous and difficult to deal with",t:"mastery",u:8},
{w:"precipice",c:"B1",s:"CEFR-J",p:"noun",ar:"هاوية",een:"One wrong step near the precipice could be fatal.",ear:"خطوة واحدة خاطئة بالقرب من الهاوية قد تكون قاتلة.",def:"a very steep side of a high mountain or cliff",t:"mastery",u:8},
{w:"frostbite",c:"B1",s:"CEFR-J",p:"noun",ar:"قضمة الصقيع",een:"Wear thick gloves to prevent frostbite on your fingers.",ear:"ارتدِ قفازات سميكة لمنع قضمة الصقيع على أصابعك.",def:"damage to skin caused by extreme cold",t:"mastery",u:8},
{w:"traverse",c:"B1",s:"CEFR-J",p:"verb",ar:"يعبر",een:"They had to traverse a narrow mountain bridge.",ear:"اضطروا إلى عبور جسر جبلي ضيّق.",def:"to go across or through a difficult area",t:"mastery",u:8},
{w:"alpine",c:"B1",s:"CEFR-J",p:"adjective",ar:"ألبي / جبلي عالٍ",een:"Alpine flowers bloom in summer above the treeline.",ear:"تتفتح الأزهار الألبية في الصيف فوق خط الأشجار.",def:"found in or related to high mountains",t:"mastery",u:8},
{w:"rappel",c:"B1",s:"CEFR-J",p:"verb",ar:"ينزل بالحبل",een:"We learned how to rappel down the cliff safely.",ear:"تعلّمنا كيف ننزل بالحبل من الجرف بأمان.",def:"to go down a cliff using a rope",t:"mastery",u:8},
{w:"altitude sickness",c:"B1",s:"CEFR-J",p:"noun",ar:"داء المرتفعات",een:"Altitude sickness can cause headaches and dizziness.",ear:"يمكن أن يسبب داء المرتفعات صداعاً ودوخة.",def:"illness from being too high above sea level",t:"mastery",u:8},
{w:"crampon",c:"B1",s:"CEFR-J",p:"noun",ar:"مسمار تسلّق",een:"Crampons help you walk on ice without slipping.",ear:"تساعدك مسامير التسلّق على المشي على الجليد بدون انزلاق.",def:"metal spikes attached to boots for walking on ice",t:"mastery",u:8},
{w:"cairn",c:"B1",s:"CEFR-J",p:"noun",ar:"كومة حجارة",een:"Follow the cairns to stay on the right path.",ear:"اتبع أكوام الحجارة للبقاء على المسار الصحيح.",def:"a pile of stones used as a trail marker",t:"mastery",u:8},
{w:"treeline",c:"B1",s:"CEFR-J",p:"noun",ar:"خط الأشجار",een:"No trees grow above the treeline on this mountain.",ear:"لا تنمو أشجار فوق خط الأشجار على هذا الجبل.",def:"the height on a mountain above which trees cannot grow",t:"mastery",u:8},
{w:"icefall",c:"B1",s:"CEFR-J",p:"noun",ar:"شلال جليدي",een:"The icefall was one of the most dangerous parts.",ear:"كان الشلال الجليدي من أخطر الأجزاء.",def:"a steep part of a glacier like a frozen waterfall",t:"mastery",u:8},
{w:"hypothermia",c:"B1",s:"CEFR-J",p:"noun",ar:"انخفاض حرارة الجسم",een:"Hypothermia is a serious risk in cold mountains.",ear:"انخفاض حرارة الجسم خطر جدّي في الجبال الباردة.",def:"a dangerous condition when the body gets too cold",t:"mastery",u:8},
{w:"bivouac",c:"B1",s:"CEFR-J",p:"noun",ar:"مبيت مؤقت",een:"They made a bivouac on the mountainside overnight.",ear:"أقاموا مبيتاً مؤقتاً على جانب الجبل طوال الليل.",def:"a temporary camp without tents",t:"mastery",u:8},
{w:"abseil",c:"B1",s:"CEFR-J",p:"verb",ar:"ينزل بحبل من ارتفاع",een:"We learned to abseil down a thirty-meter wall.",ear:"تعلّمنا النزول بحبل من جدار ارتفاعه ثلاثون متراً.",def:"to go down a steep surface using a rope",t:"mastery",u:8},
{w:"switchback",c:"B1",s:"CEFR-J",p:"noun",ar:"منعطف حاد",een:"The trail has many switchbacks up the steep hill.",ear:"يحتوي المسار على منعطفات حادة كثيرة صعوداً.",def:"a sharp turn in a path that goes back and forth",t:"mastery",u:8},
{w:"orienteering",c:"B1",s:"CEFR-J",p:"noun",ar:"رياضة التوجيه",een:"Orienteering teaches you how to use a map and compass.",ear:"تعلّمك رياضة التوجيه كيفية استخدام الخريطة والبوصلة.",def:"a sport where you find your way using a map",t:"mastery",u:8},
{w:"crag",c:"B1",s:"CEFR-J",p:"noun",ar:"صخرة حادة",een:"Climbers practiced on the granite crag all morning.",ear:"تدرّب المتسلقون على الصخرة الحادة طوال الصباح.",def:"a steep rough rock or cliff face",t:"mastery",u:8},
{w:"ravine",c:"B1",s:"CEFR-J",p:"noun",ar:"وادٍ ضيّق",een:"A deep ravine separated the two mountain paths.",ear:"فصل وادٍ ضيّق عميق بين مسارَي الجبل.",def:"a deep narrow valley with steep sides",t:"mastery",u:8},
{w:"snowcap",c:"B1",s:"CEFR-J",p:"noun",ar:"قمة مكسوة بالثلج",een:"The snowcap on the mountain shines in the sunlight.",ear:"تلمع القمة المكسوة بالثلج في ضوء الشمس.",def:"a covering of snow on top of a mountain",t:"mastery",u:8},
{w:"dehydration",c:"B1",s:"CEFR-J",p:"noun",ar:"جفاف",een:"Drink plenty of water to avoid dehydration while hiking.",ear:"اشرب الكثير من الماء لتجنّب الجفاف أثناء التنزه.",def:"when your body does not have enough water",t:"mastery",u:8},
{w:"moraine",c:"B1",s:"CEFR-J",p:"noun",ar:"ركام جليدي",een:"The moraine was left behind when the ice melted.",ear:"خلّفت الركام الجليدي عندما ذاب الجليد.",def:"rocks and earth pushed along by a moving glacier",t:"mastery",u:8},
{w:"ascent",c:"B1",s:"CEFR-J",p:"noun",ar:"صعود",een:"The final ascent to the peak took six hours.",ear:"استغرق الصعود الأخير إلى القمة ست ساعات.",def:"the act of climbing or going up",t:"mastery",u:8},
{w:"base camp",c:"B1",s:"CEFR-J",p:"noun",ar:"معسكر القاعدة",een:"The team rested at base camp before the final climb.",ear:"استراح الفريق في معسكر القاعدة قبل التسلّق الأخير.",def:"the main camp at the bottom of a mountain",t:"mastery",u:8}
];
