// L2 Vocabulary - Units 1-4 (352 words)
// Unit 1: Brain & Memory | Unit 2: Endangered Species
// Unit 3: Extreme Weather | Unit 4: Fashion & Identity

module.exports = [

// ============================================================
// UNIT 1: Brain & Memory
// ============================================================

// --- Unit 1 Core ---
{w:"brain",c:"A2",s:"CEFR-J",p:"noun",ar:"دماغ",een:"Your brain controls everything your body does.",ear:"دماغك يتحكم في كل ما يفعله جسمك.",def:"the organ inside your head that thinks",t:"core",u:1},
{w:"memory",c:"A2",s:"CEFR-J",p:"noun",ar:"ذاكرة",een:"She has a very good memory for names.",ear:"لديها ذاكرة جيدة جداً للأسماء.",def:"the ability to remember things",t:"core",u:1},
{w:"think",c:"A1",s:"CEFR-J",p:"verb",ar:"يفكر",een:"I think this is the right answer.",ear:"أعتقد أن هذه هي الإجابة الصحيحة.",def:"to use your mind to have ideas",t:"core",u:1},
{w:"idea",c:"A1",s:"CEFR-J",p:"noun",ar:"فكرة",een:"That is a great idea for the project.",ear:"هذه فكرة رائعة للمشروع.",def:"a thought or plan in your mind",t:"core",u:1},
{w:"attention",c:"A2",s:"CEFR-J",p:"noun",ar:"انتباه",een:"Please pay attention to the teacher.",ear:"من فضلك انتبه للمعلم.",def:"when you watch or listen carefully",t:"core",u:1},
{w:"repeat",c:"A2",s:"CEFR-J",p:"verb",ar:"يكرر",een:"Can you repeat the question, please?",ear:"هل يمكنك تكرار السؤال من فضلك؟",def:"to say or do something again",t:"core",u:1},
{w:"information",c:"A2",s:"NGSL",p:"noun",ar:"معلومات",een:"You can find this information online.",ear:"يمكنك العثور على هذه المعلومات عبر الإنترنت.",def:"facts or details about something",t:"core",u:1},
{w:"remind",c:"A2",s:"CEFR-J",p:"verb",ar:"يُذكّر",een:"Please remind me to call my mother.",ear:"من فضلك ذكّرني بالاتصال بأمي.",def:"to help someone remember something",t:"core",u:1},
{w:"skill",c:"A2",s:"NGSL",p:"noun",ar:"مهارة",een:"Reading is an important skill for everyone.",ear:"القراءة مهارة مهمة للجميع.",def:"something you can do well after practice",t:"core",u:1},
{w:"knowledge",c:"A2",s:"NGSL",p:"noun",ar:"معرفة",een:"She has a lot of knowledge about science.",ear:"لديها الكثير من المعرفة عن العلوم.",def:"what you know from learning or experience",t:"core",u:1},
{w:"confused",c:"A2",s:"CEFR-J",p:"adjective",ar:"مرتبك",een:"I am confused about the homework instructions.",ear:"أنا مرتبك بشأن تعليمات الواجب.",def:"not able to understand something clearly",t:"core",u:1},
{w:"test",c:"A1",s:"CEFR-J",p:"noun",ar:"اختبار",een:"We have a test in English tomorrow.",ear:"لدينا اختبار في اللغة الإنجليزية غداً.",def:"questions to check what you know",t:"core",u:1},
{w:"decision",c:"A2",s:"NGSL",p:"noun",ar:"قرار",een:"It was a difficult decision to make.",ear:"كان قراراً صعباً لاتخاذه.",def:"a choice you make about something",t:"core",u:1},
{w:"recognize",c:"A2",s:"NGSL",p:"verb",ar:"يتعرف على",een:"I did not recognize her with short hair.",ear:"لم أتعرف عليها بشعرها القصير.",def:"to know someone or something you saw before",t:"core",u:1},
{w:"curious",c:"A2",s:"CEFR-J",p:"adjective",ar:"فضولي",een:"Children are always curious about the world.",ear:"الأطفال دائماً فضوليون عن العالم.",def:"wanting to know or learn more",t:"core",u:1},
{w:"notice",c:"A2",s:"NGSL",p:"verb",ar:"يلاحظ",een:"Did you notice the new painting on the wall?",ear:"هل لاحظت اللوحة الجديدة على الحائط؟",def:"to see or become aware of something",t:"core",u:1},
{w:"clever",c:"A2",s:"CEFR-J",p:"adjective",ar:"ذكي",een:"She is a very clever student.",ear:"هي طالبة ذكية جداً.",def:"quick at learning and understanding things",t:"core",u:1},
{w:"mistake",c:"A2",s:"NGSL",p:"noun",ar:"خطأ",een:"Everyone makes mistakes when they are learning.",ear:"الجميع يرتكب أخطاء عندما يتعلمون.",def:"something wrong that you do by accident",t:"core",u:1},
{w:"nervous",c:"A2",s:"CEFR-J",p:"adjective",ar:"متوتر",een:"He feels nervous before every exam.",ear:"يشعر بالتوتر قبل كل امتحان.",def:"feeling worried or afraid about something",t:"core",u:1},
{w:"mental",c:"A2",s:"NGSL",p:"adjective",ar:"عقلي",een:"Mental health is just as important as physical health.",ear:"الصحة العقلية لا تقل أهمية عن الصحة البدنية.",def:"related to the mind and thinking",t:"core",u:1},
{w:"review",c:"A2",s:"NGSL",p:"verb",ar:"يراجع",een:"Let us review the lesson before the test.",ear:"دعنا نراجع الدرس قبل الاختبار.",def:"to look at something again to remember it",t:"core",u:1},
{w:"explain",c:"A2",s:"CEFR-J",p:"verb",ar:"يشرح",een:"Can you explain how this machine works?",ear:"هل يمكنك شرح كيف تعمل هذه الآلة؟",def:"to make something clear so others understand",t:"core",u:1},
{w:"aware",c:"A2",s:"NGSL",p:"adjective",ar:"واعٍ",een:"Are you aware of the new school rules?",ear:"هل أنت على علم بقوانين المدرسة الجديدة؟",def:"knowing that something exists or is happening",t:"core",u:1},
{w:"reason",c:"A2",s:"NGSL",p:"noun",ar:"سبب",een:"What is the reason for your absence?",ear:"ما سبب غيابك؟",def:"why something happens or is done",t:"core",u:1},
{w:"wise",c:"A2",s:"CEFR-J",p:"adjective",ar:"حكيم",een:"My grandmother always gives wise advice.",ear:"جدتي تقدم دائماً نصائح حكيمة.",def:"having good judgment from experience",t:"core",u:1},
{w:"guess",c:"A2",s:"CEFR-J",p:"verb",ar:"يخمّن",een:"Can you guess the answer to this question?",ear:"هل يمكنك تخمين إجابة هذا السؤال؟",def:"to give an answer without being sure",t:"core",u:1},
{w:"note",c:"A2",s:"NGSL",p:"noun",ar:"ملاحظة",een:"I wrote a note to help me remember.",ear:"كتبت ملاحظة لمساعدتي على التذكر.",def:"words you write down to remember",t:"core",u:1},
{w:"response",c:"A2",s:"NGSL",p:"noun",ar:"استجابة",een:"His response to the question was correct.",ear:"كانت استجابته للسؤال صحيحة.",def:"an answer or reaction to something",t:"core",u:1},
{w:"believe",c:"A2",s:"CEFR-J",p:"verb",ar:"يعتقد",een:"I believe you can pass this exam.",ear:"أعتقد أنك تستطيع اجتياز هذا الامتحان.",def:"to think that something is true",t:"core",u:1},
{w:"habit",c:"A2",s:"NGSL",p:"noun",ar:"عادة",een:"Studying every day is a good habit.",ear:"الدراسة كل يوم عادة جيدة.",def:"something you do often and regularly",t:"core",u:1},
{w:"ponder",c:"A2",s:"CEFR-J",p:"verb",ar:"يتأمل",een:"She sat quietly to ponder the difficult question.",ear:"جلست بهدوء لتتأمل السؤال الصعب.",def:"to think carefully about something for a long time",t:"core",u:1},
{w:"retrieve",c:"A2",s:"NGSL",p:"verb",ar:"يسترجع",een:"It is hard to retrieve old memories sometimes.",ear:"من الصعب أحياناً استرجاع الذكريات القديمة.",def:"to get something back, especially from memory",t:"core",u:1},
{w:"puzzle",c:"A2",s:"CEFR-J",p:"noun",ar:"لغز",een:"Solving puzzles is a great way to train your brain.",ear:"حل الألغاز طريقة رائعة لتدريب دماغك.",def:"a game or problem that makes you think",t:"core",u:1},
// --- Unit 1 Extended ---
{w:"intelligence",c:"A2",s:"NGSL",p:"noun",ar:"ذكاء",een:"There are many different types of intelligence.",ear:"هناك أنواع كثيرة مختلفة من الذكاء.",def:"the ability to learn and understand things",t:"extended",u:1},
{w:"complex",c:"A2",s:"NGSL",p:"adjective",ar:"معقد",een:"The human brain is very complex.",ear:"الدماغ البشري معقد جداً.",def:"having many parts and hard to understand",t:"extended",u:1},
{w:"distract",c:"A2",s:"CEFR-J",p:"verb",ar:"يشتّت",een:"Loud music can distract you from studying.",ear:"الموسيقى الصاخبة يمكن أن تشتتك عن الدراسة.",def:"to take your attention away from something",t:"extended",u:1},
{w:"lecture",c:"A2",s:"CEFR-J",p:"noun",ar:"محاضرة",een:"The professor gave a lecture about the brain.",ear:"ألقى الأستاذ محاضرة عن الدماغ.",def:"a talk given to teach a group",t:"extended",u:1},
{w:"research",c:"A2",s:"NGSL",p:"noun",ar:"بحث",een:"Scientists do research to learn new things.",ear:"يجري العلماء بحوثاً لتعلم أشياء جديدة.",def:"careful study to find new facts",t:"extended",u:1},
{w:"connection",c:"A2",s:"NGSL",p:"noun",ar:"اتصال",een:"There is a strong connection between sleep and memory.",ear:"هناك اتصال قوي بين النوم والذاكرة.",def:"a link or relationship between things",t:"extended",u:1},
{w:"reaction",c:"A2",s:"NGSL",p:"noun",ar:"ردة فعل",een:"What was your reaction when you heard the news?",ear:"ما كانت ردة فعلك عندما سمعت الخبر؟",def:"what you do or feel because of something",t:"extended",u:1},
{w:"logical",c:"A2",s:"NGSL",p:"adjective",ar:"منطقي",een:"His explanation was clear and logical.",ear:"كان شرحه واضحاً ومنطقياً.",def:"making sense and based on reason",t:"extended",u:1},
{w:"doubt",c:"A2",s:"NGSL",p:"noun",ar:"شك",een:"I have no doubt that she will succeed.",ear:"ليس لدي شك أنها ستنجح.",def:"a feeling of not being sure",t:"extended",u:1},
{w:"task",c:"A2",s:"NGSL",p:"noun",ar:"مهمة",een:"She finished the task in just ten minutes.",ear:"أنهت المهمة في عشر دقائق فقط.",def:"a piece of work you need to do",t:"extended",u:1},
{w:"analyze",c:"A2",s:"NGSL",p:"verb",ar:"يحلل",een:"We need to analyze the results carefully.",ear:"نحتاج لتحليل النتائج بعناية.",def:"to study something closely to understand it",t:"extended",u:1},
{w:"behavior",c:"A2",s:"NGSL",p:"noun",ar:"سلوك",een:"Sleep affects your behavior during the day.",ear:"النوم يؤثر على سلوكك خلال النهار.",def:"the way a person acts",t:"extended",u:1},
{w:"ignore",c:"A2",s:"NGSL",p:"verb",ar:"يتجاهل",een:"Try to ignore the noise and keep working.",ear:"حاول تجاهل الضوضاء واستمر في العمل.",def:"to not pay attention to something on purpose",t:"extended",u:1},
{w:"calm",c:"A2",s:"CEFR-J",p:"adjective",ar:"هادئ",een:"Stay calm and take a deep breath.",ear:"ابقَ هادئاً وخذ نفساً عميقاً.",def:"peaceful and not worried or angry",t:"extended",u:1},
{w:"deeply",c:"A2",s:"NGSL",p:"adverb",ar:"بعمق",een:"He was thinking deeply about the problem.",ear:"كان يفكر بعمق في المشكلة.",def:"in a strong or serious way",t:"extended",u:1},
{w:"examine",c:"A2",s:"NGSL",p:"verb",ar:"يفحص",een:"The doctor will examine your eyes today.",ear:"سيفحص الطبيب عينيك اليوم.",def:"to look at something very carefully",t:"extended",u:1},
{w:"method",c:"A2",s:"NGSL",p:"noun",ar:"طريقة",een:"This is the best method for learning vocabulary.",ear:"هذه هي أفضل طريقة لتعلم المفردات.",def:"a way of doing something",t:"extended",u:1},
{w:"emotion",c:"A2",s:"NGSL",p:"noun",ar:"عاطفة",een:"Music can bring up strong emotions.",ear:"يمكن للموسيقى أن تثير عواطف قوية.",def:"a strong feeling like happiness or sadness",t:"extended",u:1},
{w:"actively",c:"A2",s:"NGSL",p:"adverb",ar:"بنشاط",een:"You should actively participate in class.",ear:"يجب أن تشارك بنشاط في الصف.",def:"in a way that involves doing things",t:"extended",u:1},
{w:"nerve",c:"A2",s:"CEFR-J",p:"noun",ar:"عصب",een:"Nerves carry messages to your brain.",ear:"الأعصاب تنقل الرسائل إلى دماغك.",def:"a thin thread in your body that sends signals",t:"extended",u:1},
{w:"progress",c:"A2",s:"NGSL",p:"noun",ar:"تقدم",een:"You are making great progress in English.",ear:"أنت تحرز تقدماً كبيراً في اللغة الإنجليزية.",def:"movement forward toward a goal",t:"extended",u:1},
{w:"capable",c:"A2",s:"NGSL",p:"adjective",ar:"قادر",een:"Your brain is capable of amazing things.",ear:"دماغك قادر على أشياء مذهلة.",def:"having the ability to do something",t:"extended",u:1},
{w:"struggle",c:"A2",s:"NGSL",p:"verb",ar:"يكافح",een:"Many students struggle with math at first.",ear:"كثير من الطلاب يكافحون مع الرياضيات في البداية.",def:"to try hard to do something difficult",t:"extended",u:1},
{w:"memorize",c:"A2",s:"CEFR-J",p:"verb",ar:"يحفظ",een:"I need to memorize fifty new words this week.",ear:"أحتاج لحفظ خمسين كلمة جديدة هذا الأسبوع.",def:"to learn something so you remember it exactly",t:"extended",u:1},
{w:"concentration",c:"A2",s:"NGSL",p:"noun",ar:"تركيز",een:"Good concentration helps you learn faster.",ear:"التركيز الجيد يساعدك على التعلم بشكل أسرع.",def:"the ability to think about one thing carefully",t:"extended",u:1},
{w:"confuse",c:"A2",s:"CEFR-J",p:"verb",ar:"يُربك",een:"Too many rules can confuse young learners.",ear:"كثرة القواعد يمكن أن تربك المتعلمين الصغار.",def:"to make someone unable to understand clearly",t:"extended",u:1},
{w:"alert",c:"A2",s:"NGSL",p:"adjective",ar:"يقظ",een:"Drink water to stay alert during class.",ear:"اشرب الماء لتبقى يقظاً أثناء الحصة.",def:"awake and ready to pay attention",t:"extended",u:1},
{w:"steadily",c:"A2",s:"NGSL",p:"adverb",ar:"بثبات",een:"Her reading skills improved steadily over time.",ear:"تحسنت مهارات القراءة لديها بثبات بمرور الوقت.",def:"in a regular and continuous way",t:"extended",u:1},
{w:"keen",c:"A2",s:"CEFR-J",p:"adjective",ar:"شديد الاهتمام",een:"She has a keen interest in how the brain works.",ear:"لديها اهتمام شديد بكيفية عمل الدماغ.",def:"very interested and eager to learn",t:"extended",u:1},
// --- Unit 1 Mastery ---
{w:"cognitive",c:"B1",s:"NGSL",p:"adjective",ar:"إدراكي",een:"Reading improves your cognitive abilities.",ear:"القراءة تحسن قدراتك الإدراكية.",def:"related to thinking and understanding",t:"mastery",u:1},
{w:"neuron",c:"B1",s:"CEFR-J",p:"noun",ar:"خلية عصبية",een:"Your brain has billions of neurons.",ear:"يحتوي دماغك على مليارات الخلايا العصبية.",def:"a cell in the brain that sends signals",t:"mastery",u:1},
{w:"conscious",c:"B1",s:"NGSL",p:"adjective",ar:"واعٍ",een:"He was still conscious after the accident.",ear:"كان لا يزال واعياً بعد الحادث.",def:"awake and able to think and notice things",t:"mastery",u:1},
{w:"stimulate",c:"B1",s:"NGSL",p:"verb",ar:"يحفز",een:"Puzzles stimulate your brain and keep it active.",ear:"الألغاز تحفز دماغك وتبقيه نشطاً.",def:"to make something more active or interested",t:"mastery",u:1},
{w:"hypothesis",c:"B1",s:"NGSL",p:"noun",ar:"فرضية",een:"The scientist tested her hypothesis in the lab.",ear:"اختبرت العالمة فرضيتها في المختبر.",def:"an idea that you test to see if it is true",t:"mastery",u:1},
{w:"subconscious",c:"B1",s:"CEFR-J",p:"adjective",ar:"لاواعي",een:"Some learning happens at a subconscious level.",ear:"بعض التعلم يحدث على مستوى لاواعي.",def:"happening in the mind without you knowing",t:"mastery",u:1},
{w:"perception",c:"B1",s:"NGSL",p:"noun",ar:"إدراك",een:"Our perception of time changes when we are busy.",ear:"يتغير إدراكنا للوقت عندما نكون مشغولين.",def:"the way you understand or see things",t:"mastery",u:1},
{w:"retain",c:"B1",s:"NGSL",p:"verb",ar:"يحتفظ بـ",een:"She can retain facts for a very long time.",ear:"يمكنها الاحتفاظ بالحقائق لفترة طويلة جداً.",def:"to keep something in your memory",t:"mastery",u:1},
{w:"trigger",c:"B1",s:"NGSL",p:"verb",ar:"يُثير",een:"A smell can trigger old memories.",ear:"يمكن لرائحة أن تثير ذكريات قديمة.",def:"to cause something to start or happen",t:"mastery",u:1},
{w:"theory",c:"A2",s:"NGSL",p:"noun",ar:"نظرية",een:"He has an interesting theory about dreams.",ear:"لديه نظرية مثيرة عن الأحلام.",def:"an idea that explains how something works",t:"mastery",u:1},
{w:"psychology",c:"B1",s:"NGSL",p:"noun",ar:"علم النفس",een:"She is studying psychology at university.",ear:"تدرس علم النفس في الجامعة.",def:"the study of the mind and how people behave",t:"mastery",u:1},
{w:"associate",c:"B1",s:"NGSL",p:"verb",ar:"يربط",een:"People often associate red with danger.",ear:"غالباً ما يربط الناس اللون الأحمر بالخطر.",def:"to connect one thing with another in your mind",t:"mastery",u:1},
{w:"instinct",c:"B1",s:"CEFR-J",p:"noun",ar:"غريزة",een:"Animals follow their instincts to find food.",ear:"تتبع الحيوانات غرائزها للعثور على الطعام.",def:"a natural feeling that makes you act a certain way",t:"mastery",u:1},
{w:"interpret",c:"B1",s:"NGSL",p:"verb",ar:"يُفسّر",een:"How do you interpret these results?",ear:"كيف تفسر هذه النتائج؟",def:"to explain or understand the meaning of something",t:"mastery",u:1},
{w:"phenomenon",c:"B1",s:"NGSL",p:"noun",ar:"ظاهرة",een:"Memory loss is a common phenomenon in old age.",ear:"فقدان الذاكرة ظاهرة شائعة في الشيخوخة.",def:"something that happens or exists in nature",t:"mastery",u:1},
{w:"reliable",c:"B1",s:"NGSL",p:"adjective",ar:"موثوق",een:"Is this a reliable source of information?",ear:"هل هذا مصدر موثوق للمعلومات؟",def:"something you can trust to be good or correct",t:"mastery",u:1},
{w:"tendency",c:"B1",s:"NGSL",p:"noun",ar:"ميل",een:"He has a tendency to forget people's names.",ear:"لديه ميل لنسيان أسماء الناس.",def:"something you are likely to do often",t:"mastery",u:1},
{w:"sensory",c:"B1",s:"NGSL",p:"adjective",ar:"حسي",een:"We receive sensory information through our five senses.",ear:"نتلقى المعلومات الحسية من خلال حواسنا الخمس.",def:"related to the five senses like sight and hearing",t:"mastery",u:1},
{w:"outcome",c:"B1",s:"NGSL",p:"noun",ar:"نتيجة",een:"The outcome of the experiment surprised everyone.",ear:"فاجأت نتيجة التجربة الجميع.",def:"the result of an action or event",t:"mastery",u:1},
{w:"critical",c:"B1",s:"NGSL",p:"adjective",ar:"نقدي",een:"Critical thinking is an important life skill.",ear:"التفكير النقدي مهارة حياتية مهمة.",def:"involving careful judgment and analysis",t:"mastery",u:1},
{w:"scan",c:"B1",s:"CEFR-J",p:"verb",ar:"يمسح",een:"Doctors can scan the brain using special machines.",ear:"يمكن للأطباء مسح الدماغ باستخدام أجهزة خاصة.",def:"to look at or read something quickly",t:"mastery",u:1},
{w:"function",c:"A2",s:"NGSL",p:"noun",ar:"وظيفة",een:"Each part of the brain has a different function.",ear:"كل جزء من الدماغ له وظيفة مختلفة.",def:"the purpose or job of something",t:"mastery",u:1},
{w:"digest",c:"B1",s:"NGSL",p:"verb",ar:"يهضم (معلومات)",een:"Give yourself time to digest all this new information.",ear:"امنح نفسك وقتاً لهضم كل هذه المعلومات الجديدة.",def:"to think about something until you understand it",t:"mastery",u:1},
{w:"modify",c:"B1",s:"NGSL",p:"verb",ar:"يعدّل",een:"You can modify your study habits to learn better.",ear:"يمكنك تعديل عادات الدراسة لتتعلم بشكل أفضل.",def:"to change something slightly to improve it",t:"mastery",u:1},
{w:"imagination",c:"A2",s:"CEFR-J",p:"noun",ar:"خيال",een:"Children use their imagination when they play.",ear:"يستخدم الأطفال خيالهم عندما يلعبون.",def:"the ability to create pictures and ideas in your mind",t:"mastery",u:1},
{w:"technique",c:"A2",s:"NGSL",p:"noun",ar:"تقنية",een:"This memory technique helps you remember long lists.",ear:"تقنية الذاكرة هذه تساعدك على تذكر القوائم الطويلة.",def:"a special way of doing something skillfully",t:"mastery",u:1},

// ============================================================
// UNIT 2: Endangered Species
// ============================================================

// --- Unit 2 Core ---
{w:"forest",c:"A1",s:"CEFR-J",p:"noun",ar:"غابة",een:"Many animals live in the tropical forest.",ear:"تعيش حيوانات كثيرة في الغابة الاستوائية.",def:"a large area with many trees",t:"core",u:2},
{w:"danger",c:"A2",s:"CEFR-J",p:"noun",ar:"خطر",een:"Many sea animals are in danger today.",ear:"كثير من حيوانات البحر في خطر اليوم.",def:"a situation where harm is possible",t:"core",u:2},
{w:"disappear",c:"A2",s:"CEFR-J",p:"verb",ar:"يختفي",een:"Some animal species may disappear in fifty years.",ear:"قد تختفي بعض أنواع الحيوانات خلال خمسين عاماً.",def:"to stop being seen or to go away",t:"core",u:2},
{w:"population",c:"A2",s:"NGSL",p:"noun",ar:"تعداد",een:"The tiger population is getting smaller.",ear:"تعداد النمور يتناقص.",def:"the total number of people or animals in a place",t:"core",u:2},
{w:"river",c:"A1",s:"CEFR-J",p:"noun",ar:"نهر",een:"Fish cannot survive in a polluted river.",ear:"لا يمكن للأسماك البقاء في نهر ملوث.",def:"a long flow of water across land",t:"core",u:2},
{w:"destroy",c:"A2",s:"NGSL",p:"verb",ar:"يدمر",een:"Fires can destroy large parts of the forest.",ear:"يمكن للحرائق تدمير أجزاء كبيرة من الغابة.",def:"to damage something so badly it is gone",t:"core",u:2},
{w:"remain",c:"A2",s:"NGSL",p:"verb",ar:"يبقى",een:"Only a few hundred of these birds remain.",ear:"لا يتبقى سوى بضع مئات من هذه الطيور.",def:"to stay or continue to exist",t:"core",u:2},
{w:"threat",c:"A2",s:"NGSL",p:"noun",ar:"تهديد",een:"Pollution is a major threat to ocean life.",ear:"التلوث تهديد كبير للحياة البحرية.",def:"something that can cause harm or danger",t:"core",u:2},
{w:"trap",c:"A2",s:"CEFR-J",p:"verb",ar:"يحاصر",een:"Some animals get trapped in fishing nets.",ear:"بعض الحيوانات تعلق في شباك الصيد.",def:"to catch something so it cannot move",t:"core",u:2},
{w:"fur",c:"A2",s:"CEFR-J",p:"noun",ar:"فراء",een:"Some people still buy coats made of fur.",ear:"لا يزال بعض الناس يشترون معاطف مصنوعة من الفراء.",def:"the soft thick hair on an animal's body",t:"core",u:2},
{w:"nest",c:"A2",s:"CEFR-J",p:"noun",ar:"عش",een:"The bird built a nest high in the tree.",ear:"بنى الطائر عشاً عالياً في الشجرة.",def:"a home that birds build for their eggs",t:"core",u:2},
{w:"jungle",c:"A2",s:"CEFR-J",p:"noun",ar:"أدغال",een:"Gorillas live in the jungles of Africa.",ear:"تعيش الغوريلا في أدغال أفريقيا.",def:"a thick tropical forest with many plants",t:"core",u:2},
{w:"warn",c:"A2",s:"CEFR-J",p:"verb",ar:"يحذر",een:"Scientists warn that many species could disappear.",ear:"يحذر العلماء من أن أنواعاً كثيرة قد تختفي.",def:"to tell someone about a possible danger",t:"core",u:2},
{w:"feather",c:"A2",s:"CEFR-J",p:"noun",ar:"ريشة",een:"The parrot has colorful feathers.",ear:"يمتلك الببغاء ريشاً ملوناً.",def:"one of the light soft things covering a bird",t:"core",u:2},
{w:"harm",c:"A2",s:"NGSL",p:"verb",ar:"يؤذي",een:"Plastic in the ocean can harm sea animals.",ear:"البلاستيك في المحيط يمكن أن يؤذي الحيوانات البحرية.",def:"to cause pain or damage to something",t:"core",u:2},
{w:"cage",c:"A2",s:"CEFR-J",p:"noun",ar:"قفص",een:"The bird looked sad inside the small cage.",ear:"بدا الطائر حزيناً داخل القفص الصغير.",def:"a structure with bars for keeping animals",t:"core",u:2},
{w:"alive",c:"A2",s:"CEFR-J",p:"adjective",ar:"حي",een:"We want to keep these species alive.",ear:"نريد أن نبقي هذه الأنواع حية.",def:"living and not dead",t:"core",u:2},
{w:"bear",c:"A1",s:"CEFR-J",p:"noun",ar:"دب",een:"The polar bear needs ice to survive.",ear:"يحتاج الدب القطبي للجليد للبقاء.",def:"a large strong animal with thick fur",t:"core",u:2},
{w:"law",c:"A2",s:"NGSL",p:"noun",ar:"قانون",een:"New laws protect endangered animals from hunting.",ear:"القوانين الجديدة تحمي الحيوانات المهددة من الصيد.",def:"a rule made by the government",t:"core",u:2},
{w:"release",c:"A2",s:"NGSL",p:"verb",ar:"يُطلق",een:"They will release the healed bird back to nature.",ear:"سيطلقون الطائر المتعافي إلى الطبيعة مجدداً.",def:"to set free or let go",t:"core",u:2},
{w:"male",c:"A2",s:"NGSL",p:"adjective",ar:"ذكر",een:"The male lion has a large mane.",ear:"الأسد الذكر لديه لبدة كبيرة.",def:"belonging to the sex that does not have babies",t:"core",u:2},
{w:"female",c:"A2",s:"NGSL",p:"adjective",ar:"أنثى",een:"The female elephant leads the group.",ear:"أنثى الفيل تقود المجموعة.",def:"belonging to the sex that can have babies",t:"core",u:2},
{w:"claw",c:"A2",s:"CEFR-J",p:"noun",ar:"مخلب",een:"The eagle catches fish with its sharp claws.",ear:"يصطاد النسر السمك بمخالبه الحادة.",def:"a sharp curved nail on an animal's foot",t:"core",u:2},
{w:"horn",c:"A2",s:"CEFR-J",p:"noun",ar:"قرن",een:"The rhinoceros has a large horn on its nose.",ear:"وحيد القرن لديه قرن كبير على أنفه.",def:"a hard pointed part on an animal's head",t:"core",u:2},
{w:"wander",c:"A2",s:"CEFR-J",p:"verb",ar:"يتجول",een:"Elephants wander long distances to find water.",ear:"تتجول الفيلة مسافات طويلة للعثور على الماء.",def:"to walk around without a clear direction",t:"core",u:2},
{w:"rescue",c:"A2",s:"CEFR-J",p:"verb",ar:"ينقذ",een:"The team worked hard to rescue the injured whale.",ear:"عمل الفريق بجد لإنقاذ الحوت المصاب.",def:"to save someone or something from danger",t:"core",u:2},
{w:"guard",c:"A2",s:"CEFR-J",p:"verb",ar:"يحرس",een:"Dogs guard the sheep from wolves at night.",ear:"تحرس الكلاب الأغنام من الذئاب في الليل.",def:"to watch over and keep safe from danger",t:"core",u:2},
{w:"tiger",c:"A1",s:"CEFR-J",p:"noun",ar:"نمر",een:"The tiger is one of the most beautiful big cats.",ear:"النمر واحد من أجمل القطط الكبيرة.",def:"a large wild cat with orange and black stripes",t:"core",u:2},
{w:"surroundings",c:"A2",s:"NGSL",p:"noun",ar:"محيط",een:"Animals need clean surroundings to stay healthy.",ear:"تحتاج الحيوانات لمحيط نظيف لتبقى بصحة جيدة.",def:"everything that is around you in a place",t:"core",u:2},
{w:"untamed",c:"A2",s:"CEFR-J",p:"adjective",ar:"غير مروّض",een:"Untamed areas are home to many special animals.",ear:"المناطق غير المروّضة موطن لحيوانات مميزة كثيرة.",def:"not controlled by humans, still in a natural state",t:"core",u:2},
{w:"at risk",c:"A2",s:"NGSL",p:"adjective",ar:"معرّض للخطر",een:"Many at risk animals need special protection.",ear:"كثير من الحيوانات المعرّضة للخطر تحتاج حماية خاصة.",def:"likely to be harmed or lost if nothing is done",t:"core",u:2},
{w:"scarce",c:"A2",s:"NGSL",p:"adjective",ar:"شحيح",een:"Clean water is becoming scarce in many places.",ear:"المياه النظيفة أصبحت شحيحة في أماكن كثيرة.",def:"not enough of something, hard to find",t:"core",u:2},
{w:"fierce",c:"A2",s:"CEFR-J",p:"adjective",ar:"شرس",een:"The fierce lion chased away the other animals.",ear:"طارد الأسد الشرس الحيوانات الأخرى.",def:"strong, powerful, and sometimes dangerous",t:"core",u:2},
// --- Unit 2 Extended ---
{w:"mammal",c:"A2",s:"CEFR-J",p:"noun",ar:"حيوان ثديي",een:"A whale is a mammal, not a fish.",ear:"الحوت حيوان ثديي وليس سمكة.",def:"an animal that feeds milk to its babies",t:"extended",u:2},
{w:"territory",c:"A2",s:"NGSL",p:"noun",ar:"إقليم",een:"Lions protect their territory from other animals.",ear:"تحمي الأسود إقليمها من الحيوانات الأخرى.",def:"an area of land that an animal controls",t:"extended",u:2},
{w:"breed",c:"A2",s:"CEFR-J",p:"verb",ar:"يتكاثر",een:"Pandas do not breed easily in zoos.",ear:"لا يتكاثر الباندا بسهولة في حدائق الحيوان.",def:"to have babies or produce young animals",t:"extended",u:2},
{w:"poacher",c:"B1",s:"CEFR-J",p:"noun",ar:"صياد غير شرعي",een:"Poachers kill elephants for their ivory tusks.",ear:"يقتل الصيادون غير الشرعيين الفيلة من أجل أنيابها العاجية.",def:"a person who kills animals illegally",t:"extended",u:2},
{w:"diversity",c:"A2",s:"NGSL",p:"noun",ar:"تنوع",een:"The rainforest has amazing diversity of life.",ear:"الغابة المطيرة تتمتع بتنوع مذهل في الحياة.",def:"many different types of things or people",t:"extended",u:2},
{w:"decline",c:"A2",s:"NGSL",p:"verb",ar:"ينخفض",een:"Bee populations have declined in recent years.",ear:"انخفضت أعداد النحل في السنوات الأخيرة.",def:"to become less or smaller in number",t:"extended",u:2},
{w:"campaign",c:"A2",s:"NGSL",p:"noun",ar:"حملة",een:"The zoo started a campaign to save tigers.",ear:"بدأت حديقة الحيوان حملة لإنقاذ النمور.",def:"organized actions to achieve a goal",t:"extended",u:2},
{w:"ivory",c:"B1",s:"CEFR-J",p:"noun",ar:"عاج",een:"Selling ivory from elephants is against the law.",ear:"بيع العاج من الفيلة مخالف للقانون.",def:"the hard white material from elephant tusks",t:"extended",u:2},
{w:"wetland",c:"B1",s:"CEFR-J",p:"noun",ar:"أرض رطبة",een:"Many birds depend on wetlands for food.",ear:"تعتمد طيور كثيرة على الأراضي الرطبة للغذاء.",def:"an area of land that is very wet or flooded",t:"extended",u:2},
{w:"migrate",c:"A2",s:"CEFR-J",p:"verb",ar:"يهاجر",een:"Birds migrate south when winter comes.",ear:"تهاجر الطيور جنوباً عندما يأتي الشتاء.",def:"to move from one place to another regularly",t:"extended",u:2},
{w:"captivity",c:"B1",s:"CEFR-J",p:"noun",ar:"أسر",een:"Some animals cannot survive in captivity.",ear:"بعض الحيوانات لا تستطيع البقاء في الأسر.",def:"the state of being kept in a cage or enclosed area",t:"extended",u:2},
{w:"reserve",c:"A2",s:"NGSL",p:"noun",ar:"محمية",een:"The nature reserve protects hundreds of species.",ear:"تحمي المحمية الطبيعية مئات الأنواع.",def:"an area where animals and plants are protected",t:"extended",u:2},
{w:"volunteer",c:"A2",s:"NGSL",p:"noun",ar:"متطوع",een:"Volunteers help clean the beach every weekend.",ear:"يساعد المتطوعون في تنظيف الشاطئ كل عطلة أسبوع.",def:"a person who works without pay to help others",t:"extended",u:2},
{w:"illegal",c:"A2",s:"NGSL",p:"adjective",ar:"غير قانوني",een:"Trading in endangered species is illegal.",ear:"تجارة الأنواع المهددة بالانقراض غير قانونية.",def:"not allowed by the law",t:"extended",u:2},
{w:"pond",c:"A2",s:"CEFR-J",p:"noun",ar:"بركة",een:"Frogs live near the pond in our garden.",ear:"تعيش الضفادع بالقرب من البركة في حديقتنا.",def:"a small area of still water",t:"extended",u:2},
{w:"offspring",c:"B1",s:"NGSL",p:"noun",ar:"نسل",een:"The mother bear protects her offspring.",ear:"تحمي الدبة نسلها.",def:"the young of an animal",t:"extended",u:2},
{w:"awareness",c:"A2",s:"NGSL",p:"noun",ar:"وعي",een:"We need more awareness about endangered species.",ear:"نحتاج لمزيد من الوعي حول الأنواع المهددة بالانقراض.",def:"knowing about and understanding a problem",t:"extended",u:2},
{w:"affect",c:"A2",s:"NGSL",p:"verb",ar:"يؤثر على",een:"Climate change affects animals all over the world.",ear:"يؤثر تغير المناخ على الحيوانات في كل أنحاء العالم.",def:"to cause a change in something",t:"extended",u:2},
{w:"tusk",c:"B1",s:"CEFR-J",p:"noun",ar:"ناب",een:"Elephants use their tusks to dig for water.",ear:"تستخدم الفيلة أنيابها للحفر بحثاً عن الماء.",def:"a long pointed tooth that sticks out",t:"extended",u:2},
{w:"poison",c:"A2",s:"CEFR-J",p:"noun",ar:"سم",een:"Some frogs produce poison to protect themselves.",ear:"تنتج بعض الضفادع سماً لحماية نفسها.",def:"a substance that can kill or make you sick",t:"extended",u:2},
{w:"frog",c:"A1",s:"CEFR-J",p:"noun",ar:"ضفدع",een:"Many frog species are disappearing from our planet.",ear:"أنواع كثيرة من الضفادع تختفي من كوكبنا.",def:"a small green animal that jumps and lives near water",t:"extended",u:2},
{w:"stripe",c:"A2",s:"CEFR-J",p:"noun",ar:"خط",een:"Every tiger has a unique pattern of stripes.",ear:"كل نمر لديه نمط فريد من الخطوط.",def:"a long line of color on a surface",t:"extended",u:2},
{w:"ranger",c:"B1",s:"CEFR-J",p:"noun",ar:"حارس محمية",een:"The ranger watches over the animals in the park.",ear:"يراقب حارس المحمية الحيوانات في المنتزه.",def:"a person whose job is to protect a natural area",t:"extended",u:2},
{w:"chain",c:"A2",s:"NGSL",p:"noun",ar:"سلسلة",een:"Every animal is part of a food chain.",ear:"كل حيوان هو جزء من سلسلة غذائية.",def:"a series of connected things",t:"extended",u:2},
{w:"paw",c:"A2",s:"CEFR-J",p:"noun",ar:"كف (حيوان)",een:"The cat cleaned its paws after eating.",ear:"نظفت القطة كفيها بعد الأكل.",def:"the foot of an animal that has claws",t:"extended",u:2},
{w:"fund",c:"A2",s:"NGSL",p:"verb",ar:"يموّل",een:"The government will fund the conservation project.",ear:"ستموّل الحكومة مشروع الحفظ.",def:"to provide money for something",t:"extended",u:2},
{w:"roam",c:"A2",s:"CEFR-J",p:"verb",ar:"يتجول بحرية",een:"Buffalo used to roam across the open plains.",ear:"كان الجاموس يتجول بحرية عبر السهول المفتوحة.",def:"to move around freely in a large area",t:"extended",u:2},
{w:"woodland",c:"A2",s:"CEFR-J",p:"noun",ar:"أرض حرجية",een:"Many birds build their nests in the woodland.",ear:"تبني طيور كثيرة أعشاشها في الأرض الحرجية.",def:"land covered with trees, smaller than a forest",t:"extended",u:2},
{w:"nourish",c:"B1",s:"NGSL",p:"verb",ar:"يغذّي",een:"Mother animals nourish their babies with milk.",ear:"تغذي الحيوانات الأمهات صغارها بالحليب.",def:"to give food and care to help something grow",t:"extended",u:2},
// --- Unit 2 Mastery ---
{w:"sanctuary",c:"B1",s:"CEFR-J",p:"noun",ar:"محمية",een:"The elephant sanctuary cares for injured animals.",ear:"تعتني محمية الفيلة بالحيوانات المصابة.",def:"a safe place where animals are protected",t:"mastery",u:2},
{w:"food web",c:"B1",s:"CEFR-J",p:"noun",ar:"شبكة غذائية",een:"Every animal plays a role in the food web.",ear:"يلعب كل حيوان دوراً في الشبكة الغذائية.",def:"the connected food chains in a natural area",t:"mastery",u:2},
{w:"hunter",c:"A2",s:"CEFR-J",p:"noun",ar:"صياد",een:"The owl is a skilled night hunter.",ear:"البومة صياد ماهر في الليل.",def:"an animal or person that catches other animals",t:"mastery",u:2},
{w:"prey",c:"B1",s:"NGSL",p:"noun",ar:"فريسة",een:"Small fish are prey for bigger fish.",ear:"الأسماك الصغيرة فريسة للأسماك الأكبر.",def:"an animal that is hunted by another animal",t:"mastery",u:2},
{w:"camouflage",c:"B1",s:"CEFR-J",p:"noun",ar:"تمويه",een:"The lizard uses camouflage to hide from enemies.",ear:"يستخدم السحلية التمويه للاختباء من الأعداء.",def:"colors or patterns that help an animal hide",t:"mastery",u:2},
{w:"poaching",c:"B1",s:"CEFR-J",p:"noun",ar:"صيد غير شرعي",een:"Poaching is the biggest threat to rhinos.",ear:"الصيد غير الشرعي هو أكبر تهديد لوحيد القرن.",def:"the illegal hunting or catching of animals",t:"mastery",u:2},
{w:"wilderness",c:"B1",s:"NGSL",p:"noun",ar:"برية",een:"Few animals can live outside the wilderness.",ear:"قليل من الحيوانات يمكنها العيش خارج البرية.",def:"a wild natural area where few people live",t:"mastery",u:2},
{w:"reproduce",c:"B1",s:"NGSL",p:"verb",ar:"يتكاثر",een:"Some animals cannot reproduce well in zoos.",ear:"بعض الحيوانات لا تتكاثر جيداً في حدائق الحيوان.",def:"to produce young animals or new plants",t:"mastery",u:2},
{w:"vegetation",c:"B1",s:"NGSL",p:"noun",ar:"غطاء نباتي",een:"Elephants eat large amounts of vegetation every day.",ear:"تأكل الفيلة كميات كبيرة من الغطاء النباتي يومياً.",def:"plants in general, especially in a particular area",t:"mastery",u:2},
{w:"endanger",c:"B1",s:"NGSL",p:"verb",ar:"يعرّض للخطر",een:"Pollution can endanger the lives of sea creatures.",ear:"يمكن للتلوث أن يعرّض حياة الكائنات البحرية للخطر.",def:"to put someone or something in danger",t:"mastery",u:2},
{w:"fragile",c:"B1",s:"NGSL",p:"adjective",ar:"هش",een:"Coral reefs are very fragile ecosystems.",ear:"الشعاب المرجانية أنظمة بيئية هشة جداً.",def:"easy to break or damage",t:"mastery",u:2},
{w:"hatch",c:"B1",s:"CEFR-J",p:"verb",ar:"يفقس",een:"The baby turtles hatch on the sandy beach.",ear:"تفقس صغار السلاحف على الشاطئ الرملي.",def:"to come out of an egg",t:"mastery",u:2},
{w:"dense",c:"B1",s:"NGSL",p:"adjective",ar:"كثيف",een:"The gorillas hide in the dense forest.",ear:"تختبئ الغوريلا في الغابة الكثيفة.",def:"thick and packed closely together",t:"mastery",u:2},
{w:"flourish",c:"B1",s:"NGSL",p:"verb",ar:"يزدهر",een:"Animals flourish when their habitat is protected.",ear:"تزدهر الحيوانات عندما يكون موطنها محمياً.",def:"to grow well and be healthy",t:"mastery",u:2},
{w:"conservationist",c:"B1",s:"CEFR-J",p:"noun",ar:"عالم حفظ البيئة",een:"The conservationist spent years studying gorillas.",ear:"أمضى عالم حفظ البيئة سنوات في دراسة الغوريلا.",def:"a person who works to protect nature",t:"mastery",u:2},
{w:"deforest",c:"B1",s:"CEFR-J",p:"verb",ar:"يزيل الغابات",een:"Companies deforest land to build farms.",ear:"تزيل الشركات الغابات لبناء المزارع.",def:"to cut down all trees in an area",t:"mastery",u:2},
{w:"native",c:"A2",s:"NGSL",p:"adjective",ar:"أصلي",een:"Kangaroos are native to Australia.",ear:"الكنغر حيوان أصلي في أستراليا.",def:"originally from a particular place",t:"mastery",u:2},
{w:"gene",c:"B1",s:"NGSL",p:"noun",ar:"جين",een:"Genes control the color of an animal's fur.",ear:"تتحكم الجينات في لون فراء الحيوان.",def:"a tiny part of a cell that controls how you look",t:"mastery",u:2},
{w:"tracker",c:"B1",s:"CEFR-J",p:"noun",ar:"متتبع",een:"The tracker followed the footprints of the leopard.",ear:"تتبع المتتبع آثار أقدام الفهد.",def:"a person who follows animal signs to find them",t:"mastery",u:2},
{w:"survival",c:"B1",s:"NGSL",p:"noun",ar:"بقاء",een:"Water is essential for the survival of all life.",ear:"الماء ضروري لبقاء كل أشكال الحياة.",def:"the state of continuing to live",t:"mastery",u:2},
{w:"biologist",c:"B1",s:"NGSL",p:"noun",ar:"عالم أحياء",een:"The biologist studies rare insects in the jungle.",ear:"يدرس عالم الأحياء الحشرات النادرة في الأدغال.",def:"a scientist who studies living things",t:"mastery",u:2},
{w:"rehabilitate",c:"B1",s:"NGSL",p:"verb",ar:"يعيد تأهيل",een:"The center works to rehabilitate injured animals.",ear:"يعمل المركز على إعادة تأهيل الحيوانات المصابة.",def:"to help someone become healthy or normal again",t:"mastery",u:2},
{w:"earth-friendly",c:"B1",s:"CEFR-J",p:"adjective",ar:"صديق للبيئة",een:"We should use earth-friendly products every day.",ear:"يجب أن نستخدم منتجات صديقة للبيئة كل يوم.",def:"not harmful to the natural world",t:"mastery",u:2},
{w:"dying out",c:"A2",s:"CEFR-J",p:"noun",ar:"اندثار",een:"The dying out of bees would affect our food supply.",ear:"اندثار النحل سيؤثر على إمدادات غذائنا.",def:"the process of a species slowly disappearing forever",t:"mastery",u:2},
{w:"water shortage",c:"A2",s:"CEFR-J",p:"noun",ar:"شح المياه",een:"The water shortage forced animals to move away.",ear:"أجبر شح المياه الحيوانات على الرحيل.",def:"when there is not enough water for people or animals",t:"mastery",u:2},
{w:"patrol",c:"B1",s:"NGSL",p:"verb",ar:"يقوم بدوريات",een:"Rangers patrol the park to stop poachers.",ear:"يقوم الحراس بدوريات في المنتزه لوقف الصيادين.",def:"to walk around an area to guard it",t:"mastery",u:2},

// ============================================================
// UNIT 3: Extreme Weather
// ============================================================

// --- Unit 3 Core ---
{w:"flood",c:"A2",s:"CEFR-J",p:"noun",ar:"فيضان",een:"The heavy rain caused a terrible flood.",ear:"تسبب المطر الغزير في فيضان رهيب.",def:"when water covers land that is usually dry",t:"core",u:3},
{w:"damage",c:"A2",s:"NGSL",p:"noun",ar:"ضرر",een:"The storm caused a lot of damage to homes.",ear:"تسببت العاصفة بالكثير من الضرر للمنازل.",def:"harm done to something so it is broken or weaker",t:"core",u:3},
{w:"shake",c:"A2",s:"CEFR-J",p:"verb",ar:"يهتز",een:"The whole house began to shake during the earthquake.",ear:"بدأ المنزل بأكمله يهتز أثناء الزلزال.",def:"to move quickly back and forth",t:"core",u:3},
{w:"blow",c:"A2",s:"CEFR-J",p:"verb",ar:"يهب",een:"The wind blows very hard near the coast.",ear:"تهب الرياح بشدة بالقرب من الساحل.",def:"when air moves with force",t:"core",u:3},
{w:"warning",c:"A2",s:"NGSL",p:"noun",ar:"تحذير",een:"The government sent a warning about the storm.",ear:"أرسلت الحكومة تحذيراً بشأن العاصفة.",def:"a message telling you about danger ahead",t:"core",u:3},
{w:"heavy",c:"A1",s:"CEFR-J",p:"adjective",ar:"غزير",een:"Heavy rain fell all day and all night.",ear:"هطل مطر غزير طوال النهار والليل.",def:"a lot of something, strong and intense",t:"core",u:3},
{w:"rise",c:"A2",s:"NGSL",p:"verb",ar:"يرتفع",een:"Sea levels continue to rise every year.",ear:"تستمر مستويات البحر في الارتفاع كل عام.",def:"to go up or increase",t:"core",u:3},
{w:"heat",c:"A2",s:"NGSL",p:"noun",ar:"حرارة",een:"The summer heat was difficult for everyone.",ear:"كانت حرارة الصيف صعبة على الجميع.",def:"the quality of being very warm or hot",t:"core",u:3},
{w:"disaster",c:"A2",s:"NGSL",p:"noun",ar:"كارثة",een:"The earthquake was a terrible natural disaster.",ear:"كان الزلزال كارثة طبيعية فظيعة.",def:"a very bad event that causes much harm",t:"core",u:3},
{w:"forecast",c:"A2",s:"CEFR-J",p:"noun",ar:"توقعات الطقس",een:"The weather forecast says it will rain tomorrow.",ear:"توقعات الطقس تقول أنها ستمطر غداً.",def:"a report about what the weather will be",t:"core",u:3},
{w:"thunder",c:"A2",s:"CEFR-J",p:"noun",ar:"رعد",een:"We could hear loud thunder during the storm.",ear:"سمعنا رعداً عالياً أثناء العاصفة.",def:"the loud sound you hear after lightning",t:"core",u:3},
{w:"lightning",c:"A2",s:"CEFR-J",p:"noun",ar:"برق",een:"Lightning lit up the dark sky.",ear:"أضاء البرق السماء المظلمة.",def:"a bright flash of light in the sky during a storm",t:"core",u:3},
{w:"melt",c:"A2",s:"CEFR-J",p:"verb",ar:"يذوب",een:"The ice is melting because of rising temperatures.",ear:"الجليد يذوب بسبب ارتفاع درجات الحرارة.",def:"to change from solid to liquid by heating",t:"core",u:3},
{w:"predict",c:"A2",s:"NGSL",p:"verb",ar:"يتنبأ",een:"Scientists try to predict when storms will happen.",ear:"يحاول العلماء التنبؤ بموعد حدوث العواصف.",def:"to say what will happen in the future",t:"core",u:3},
{w:"emergency",c:"A2",s:"NGSL",p:"noun",ar:"طوارئ",een:"Call this number in case of an emergency.",ear:"اتصل بهذا الرقم في حالة الطوارئ.",def:"a serious and dangerous situation needing fast action",t:"core",u:3},
{w:"victim",c:"A2",s:"NGSL",p:"noun",ar:"ضحية",een:"Many flood victims lost their homes.",ear:"فقد كثير من ضحايا الفيضان منازلهم.",def:"a person who is hurt by an event or crime",t:"core",u:3},
{w:"spread",c:"A2",s:"NGSL",p:"verb",ar:"ينتشر",een:"The fire spread quickly because of the strong wind.",ear:"انتشرت النار بسرعة بسبب الرياح القوية.",def:"to cover a larger area or reach more people",t:"core",u:3},
{w:"fog",c:"A2",s:"CEFR-J",p:"noun",ar:"ضباب",een:"Thick fog made it hard to see the road.",ear:"جعل الضباب الكثيف من الصعب رؤية الطريق.",def:"a thick cloud of tiny water drops near the ground",t:"core",u:3},
{w:"severe",c:"A2",s:"NGSL",p:"adjective",ar:"شديد",een:"Severe weather warnings were sent to everyone.",ear:"أُرسلت تحذيرات طقس شديدة للجميع.",def:"very bad or very serious",t:"core",u:3},
{w:"crack",c:"A2",s:"CEFR-J",p:"verb",ar:"يتشقق",een:"The ground cracked because it was so dry.",ear:"تشقق الأرض لأنها كانت جافة جداً.",def:"to break without separating into parts",t:"core",u:3},
{w:"mud",c:"A2",s:"CEFR-J",p:"noun",ar:"وحل",een:"After the rain, the streets were full of mud.",ear:"بعد المطر كانت الشوارع مليئة بالوحل.",def:"soft wet earth",t:"core",u:3},
{w:"hail",c:"A2",s:"CEFR-J",p:"noun",ar:"بَرَد",een:"Hail the size of golf balls fell from the sky.",ear:"سقط برد بحجم كرات الغولف من السماء.",def:"small hard balls of ice that fall like rain",t:"core",u:3},
{w:"earthquake",c:"A2",s:"CEFR-J",p:"noun",ar:"زلزال",een:"The earthquake destroyed many buildings in the city.",ear:"دمر الزلزال مبانٍ كثيرة في المدينة.",def:"a sudden shaking of the ground",t:"core",u:3},
{w:"relief",c:"A2",s:"NGSL",p:"noun",ar:"إغاثة",een:"Relief supplies were sent to the disaster area.",ear:"أُرسلت مواد الإغاثة إلى منطقة الكارثة.",def:"help given to people who need it",t:"core",u:3},
{w:"extreme",c:"A2",s:"NGSL",p:"adjective",ar:"شديد",een:"Extreme heat can be dangerous for old people.",ear:"الحرارة الشديدة يمكن أن تكون خطيرة على كبار السن.",def:"very great or strong, much more than usual",t:"core",u:3},
{w:"downpour",c:"A2",s:"CEFR-J",p:"noun",ar:"هطول غزير",een:"A sudden downpour flooded the streets in minutes.",ear:"أغرق هطول غزير مفاجئ الشوارع في دقائق.",def:"a very heavy fall of rain",t:"core",u:3},
{w:"thermometer",c:"A2",s:"CEFR-J",p:"noun",ar:"ميزان حرارة",een:"The thermometer showed forty degrees outside.",ear:"أظهر ميزان الحرارة أربعين درجة بالخارج.",def:"a tool that measures how hot or cold it is",t:"core",u:3},
{w:"bunker",c:"A2",s:"CEFR-J",p:"noun",ar:"ملجأ",een:"The family hid in a bunker during the tornado.",ear:"اختبأت العائلة في ملجأ أثناء الإعصار القمعي.",def:"a strong safe room built to protect people",t:"core",u:3},
{w:"parched",c:"A2",s:"CEFR-J",p:"adjective",ar:"يابس",een:"The parched land cracked under the hot sun.",ear:"تشققت الأرض اليابسة تحت الشمس الحارقة.",def:"extremely dry because of no water or rain",t:"core",u:3},
{w:"damp",c:"A2",s:"CEFR-J",p:"adjective",ar:"رطب",een:"The walls of the old house were cold and damp.",ear:"كانت جدران المنزل القديم باردة ورطبة.",def:"slightly wet, often in an unpleasant way",t:"core",u:3},
{w:"shoreline",c:"A2",s:"CEFR-J",p:"noun",ar:"خط الشاطئ",een:"The waves crashed against the rocky shoreline.",ear:"تحطمت الأمواج على خط الشاطئ الصخري.",def:"the edge of land where it meets the sea",t:"core",u:3},
{w:"secure",c:"A2",s:"NGSL",p:"adjective",ar:"آمن",een:"Make sure you are in a secure place before the storm.",ear:"تأكد أنك في مكان آمن قبل العاصفة.",def:"protected from danger or risk",t:"core",u:3},
{w:"weather station",c:"A2",s:"CEFR-J",p:"noun",ar:"محطة أرصاد",een:"The weather station tracks storms across the country.",ear:"تتبع محطة الأرصاد العواصف عبر البلاد.",def:"a place with tools that measure and record weather",t:"core",u:3},
// --- Unit 3 Extended ---
{w:"hurricane",c:"B1",s:"CEFR-J",p:"noun",ar:"إعصار",een:"The hurricane damaged thousands of homes.",ear:"دمر الإعصار آلاف المنازل.",def:"a very strong storm with fast circular winds",t:"extended",u:3},
{w:"tornado",c:"B1",s:"CEFR-J",p:"noun",ar:"إعصار قمعي",een:"A tornado can destroy everything in its path.",ear:"يمكن للإعصار القمعي تدمير كل شيء في طريقه.",def:"a violent spinning column of air",t:"extended",u:3},
{w:"volcano",c:"A2",s:"CEFR-J",p:"noun",ar:"بركان",een:"The volcano erupted and lava flowed down the mountain.",ear:"ثار البركان وتدفقت الحمم أسفل الجبل.",def:"a mountain that can send out fire and hot rock",t:"extended",u:3},
{w:"evacuate",c:"B1",s:"NGSL",p:"verb",ar:"يُخلي",een:"Police told everyone to evacuate the town immediately.",ear:"أخبرت الشرطة الجميع بإخلاء البلدة فوراً.",def:"to leave a dangerous place to stay safe",t:"extended",u:3},
{w:"moisture",c:"B1",s:"NGSL",p:"noun",ar:"رطوبة",een:"There is a lot of moisture in the air today.",ear:"هناك الكثير من الرطوبة في الهواء اليوم.",def:"small drops of water in the air or on a surface",t:"extended",u:3},
{w:"humid",c:"A2",s:"CEFR-J",p:"adjective",ar:"رطب",een:"It is very hot and humid in summer here.",ear:"الجو حار جداً ورطب في الصيف هنا.",def:"when the air has a lot of water in it",t:"extended",u:3},
{w:"breeze",c:"A2",s:"CEFR-J",p:"noun",ar:"نسيم",een:"A cool breeze came from the sea.",ear:"جاء نسيم بارد من البحر.",def:"a light gentle wind",t:"extended",u:3},
{w:"cyclone",c:"B1",s:"CEFR-J",p:"noun",ar:"إعصار مداري",een:"The cyclone brought heavy rains to the island.",ear:"جلب الإعصار المداري أمطاراً غزيرة للجزيرة.",def:"a large powerful storm with circular winds",t:"extended",u:3},
{w:"erupt",c:"B1",s:"CEFR-J",p:"verb",ar:"يثور",een:"No one knows when the volcano will erupt again.",ear:"لا أحد يعرف متى سيثور البركان مرة أخرى.",def:"when a volcano throws out fire, smoke, and rock",t:"extended",u:3},
{w:"landslide",c:"B1",s:"CEFR-J",p:"noun",ar:"انهيار أرضي",een:"The heavy rain caused a dangerous landslide.",ear:"تسبب المطر الغزير في انهيار أرضي خطير.",def:"a mass of earth falling down a hill",t:"extended",u:3},
{w:"radar",c:"A2",s:"NGSL",p:"noun",ar:"رادار",een:"Radar helps us see storms before they arrive.",ear:"يساعدنا الرادار على رؤية العواصف قبل وصولها.",def:"a system that uses radio waves to find objects",t:"extended",u:3},
{w:"debris",c:"B1",s:"NGSL",p:"noun",ar:"حطام",een:"Debris from the storm blocked many roads.",ear:"سدّ الحطام من العاصفة طرقاً كثيرة.",def:"broken pieces left after something is destroyed",t:"extended",u:3},
{w:"layer",c:"A2",s:"NGSL",p:"noun",ar:"طبقة",een:"Wear several layers of clothes in cold weather.",ear:"ارتدِ عدة طبقات من الملابس في الطقس البارد.",def:"one of several flat pieces on top of each other",t:"extended",u:3},
{w:"measure",c:"A2",s:"NGSL",p:"verb",ar:"يقيس",een:"Scientists measure the speed of the wind.",ear:"يقيس العلماء سرعة الرياح.",def:"to find the size or amount of something",t:"extended",u:3},
{w:"crisis",c:"B1",s:"NGSL",p:"noun",ar:"أزمة",een:"The flood created a serious water crisis.",ear:"خلق الفيضان أزمة مياه خطيرة.",def:"a very difficult or dangerous time",t:"extended",u:3},
{w:"dust",c:"A2",s:"CEFR-J",p:"noun",ar:"غبار",een:"A dust storm covered the whole city.",ear:"غطت عاصفة غبارية المدينة بأكملها.",def:"tiny dry pieces of dirt in the air",t:"extended",u:3},
{w:"aid",c:"A2",s:"NGSL",p:"noun",ar:"مساعدة",een:"Many countries sent aid after the earthquake.",ear:"أرسلت دول كثيرة مساعدات بعد الزلزال.",def:"help or support given to people in need",t:"extended",u:3},
{w:"recover",c:"A2",s:"NGSL",p:"verb",ar:"يتعافى",een:"It took years for the city to recover.",ear:"استغرق الأمر سنوات لتتعافى المدينة.",def:"to get better after a bad experience",t:"extended",u:3},
{w:"drown",c:"B1",s:"CEFR-J",p:"verb",ar:"يغرق",een:"Many animals drowned during the flood.",ear:"غرقت حيوانات كثيرة أثناء الفيضان.",def:"to die because you cannot breathe underwater",t:"extended",u:3},
{w:"ash",c:"A2",s:"CEFR-J",p:"noun",ar:"رماد",een:"Volcanic ash covered the nearby villages.",ear:"غطى الرماد البركاني القرى المجاورة.",def:"the grey powder left after something burns",t:"extended",u:3},
{w:"rooftop",c:"A2",s:"CEFR-J",p:"noun",ar:"سطح المبنى",een:"People waited on rooftops for rescue helicopters.",ear:"انتظر الناس على أسطح المباني طائرات الإنقاذ.",def:"the top surface of a building",t:"extended",u:3},
{w:"inland",c:"B1",s:"NGSL",p:"adverb",ar:"نحو الداخل",een:"The storm moved inland from the coast.",ear:"تحركت العاصفة نحو الداخل من الساحل.",def:"away from the sea toward the middle of a country",t:"extended",u:3},
{w:"bolt",c:"A2",s:"CEFR-J",p:"noun",ar:"صاعقة",een:"A bolt of lightning hit the tall tree.",ear:"أصابت صاعقة برق الشجرة الطويلة.",def:"a flash of lightning",t:"extended",u:3},
{w:"tremble",c:"B1",s:"CEFR-J",p:"verb",ar:"يرتجف",een:"The ground began to tremble before the earthquake.",ear:"بدأت الأرض ترتجف قبل الزلزال.",def:"to shake slightly because of fear or cold",t:"extended",u:3},
{w:"blizzard",c:"B1",s:"CEFR-J",p:"noun",ar:"عاصفة ثلجية",een:"The blizzard made it impossible to drive.",ear:"جعلت العاصفة الثلجية القيادة مستحيلة.",def:"a bad winter storm with strong winds and snow",t:"extended",u:3},
{w:"deficit",c:"B1",s:"NGSL",p:"noun",ar:"عجز",een:"The flood caused a food deficit in the area.",ear:"تسبب الفيضان في عجز غذائي في المنطقة.",def:"when there is less of something than you need",t:"extended",u:3},
{w:"alarm",c:"A2",s:"CEFR-J",p:"noun",ar:"إنذار",een:"The flood alarm went off early in the morning.",ear:"انطلق إنذار الفيضان في الصباح الباكر.",def:"a warning sound that tells you about danger",t:"extended",u:3},
{w:"swirl",c:"A2",s:"CEFR-J",p:"verb",ar:"يدور",een:"Dust swirled around during the sandstorm.",ear:"دار الغبار حولنا أثناء العاصفة الرملية.",def:"to move around and around quickly",t:"extended",u:3},
{w:"uproot",c:"B1",s:"CEFR-J",p:"verb",ar:"يقتلع",een:"The strong wind uprooted several large trees.",ear:"اقتلعت الرياح القوية عدة أشجار كبيرة.",def:"to pull a plant out of the ground completely",t:"extended",u:3},
// --- Unit 3 Mastery ---
{w:"catastrophe",c:"B1",s:"NGSL",p:"noun",ar:"كارثة",een:"The tsunami was the worst catastrophe in decades.",ear:"كان تسونامي أسوأ كارثة منذ عقود.",def:"a terrible event that causes great damage",t:"mastery",u:3},
{w:"erosion",c:"B1",s:"NGSL",p:"noun",ar:"تآكل",een:"Water erosion is changing the shape of the coast.",ear:"تآكل المياه يغير شكل الساحل.",def:"the slow wearing away of rock or soil",t:"mastery",u:3},
{w:"magnitude",c:"B1",s:"NGSL",p:"noun",ar:"قوة",een:"The earthquake had a magnitude of seven.",ear:"كانت قوة الزلزال سبع درجات.",def:"how strong or big something is",t:"mastery",u:3},
{w:"devastation",c:"B1",s:"NGSL",p:"noun",ar:"دمار",een:"The hurricane left devastation across the whole island.",ear:"ترك الإعصار دماراً في الجزيرة بأكملها.",def:"severe and widespread damage or destruction",t:"mastery",u:3},
{w:"evacuee",c:"B1",s:"CEFR-J",p:"noun",ar:"شخص تم إخلاؤه",een:"Evacuees were taken to a safe school building.",ear:"تم نقل الأشخاص الذين تم إخلاؤهم إلى مبنى مدرسة آمن.",def:"a person who leaves a dangerous place for safety",t:"mastery",u:3},
{w:"aftershock",c:"B1",s:"CEFR-J",p:"noun",ar:"هزة ارتدادية",een:"Several aftershocks followed the main earthquake.",ear:"تبعت عدة هزات ارتدادية الزلزال الرئيسي.",def:"a smaller earthquake that happens after a big one",t:"mastery",u:3},
{w:"famine",c:"B1",s:"NGSL",p:"noun",ar:"مجاعة",een:"The drought led to a terrible famine.",ear:"أدى الجفاف إلى مجاعة رهيبة.",def:"when many people have no food in an area",t:"mastery",u:3},
{w:"precipitation",c:"B1",s:"NGSL",p:"noun",ar:"هطول",een:"Precipitation levels have increased this year.",ear:"ارتفعت مستويات الهطول هذا العام.",def:"rain, snow, or hail that falls from the sky",t:"mastery",u:3},
{w:"surge",c:"B1",s:"NGSL",p:"noun",ar:"موجة عارمة",een:"A storm surge flooded the coastal town.",ear:"أغرقت موجة عارمة البلدة الساحلية.",def:"a sudden strong rise in water level",t:"mastery",u:3},
{w:"siren",c:"B1",s:"CEFR-J",p:"noun",ar:"صفارة إنذار",een:"The tornado siren warned people to take cover.",ear:"حذرت صفارة إنذار الإعصار الناس للاحتماء.",def:"a device that makes a loud warning sound",t:"mastery",u:3},
{w:"infrastructure",c:"B1",s:"NGSL",p:"noun",ar:"بنية تحتية",een:"The storm destroyed roads and other infrastructure.",ear:"دمرت العاصفة الطرق والبنية التحتية الأخرى.",def:"basic systems like roads, water, and electricity",t:"mastery",u:3},
{w:"displacement",c:"B1",s:"NGSL",p:"noun",ar:"نزوح",een:"The flood caused the displacement of thousands.",ear:"تسبب الفيضان في نزوح الآلاف.",def:"when people are forced to leave their homes",t:"mastery",u:3},
{w:"tsunami",c:"B1",s:"CEFR-J",p:"noun",ar:"تسونامي",een:"A tsunami can travel across the entire ocean.",ear:"يمكن لتسونامي أن يعبر المحيط بأكمله.",def:"a huge ocean wave caused by an earthquake",t:"mastery",u:3},
{w:"barometer",c:"B1",s:"CEFR-J",p:"noun",ar:"مقياس ضغط جوي",een:"A barometer measures the pressure of the air.",ear:"يقيس مقياس الضغط الجوي ضغط الهواء.",def:"a tool that measures air pressure",t:"mastery",u:3},
{w:"lava",c:"B1",s:"CEFR-J",p:"noun",ar:"حمم بركانية",een:"Hot lava flowed slowly down the mountain.",ear:"تدفقت الحمم البركانية الساخنة ببطء أسفل الجبل.",def:"hot melted rock that comes from a volcano",t:"mastery",u:3},
{w:"reconstruct",c:"B1",s:"NGSL",p:"verb",ar:"يعيد بناء",een:"It will take years to reconstruct the damaged city.",ear:"سيستغرق سنوات لإعادة بناء المدينة المتضررة.",def:"to build something again after it was destroyed",t:"mastery",u:3},
{w:"celsius",c:"A2",s:"CEFR-J",p:"noun",ar:"مئوية",een:"Water boils at one hundred degrees Celsius.",ear:"يغلي الماء عند مئة درجة مئوية.",def:"a scale for measuring temperature",t:"mastery",u:3},
{w:"gust",c:"B1",s:"CEFR-J",p:"noun",ar:"هبّة رياح",een:"A strong gust of wind blew my hat off.",ear:"أطارت هبة رياح قوية قبعتي.",def:"a sudden strong burst of wind",t:"mastery",u:3},
{w:"avalanche",c:"B1",s:"CEFR-J",p:"noun",ar:"انهيار ثلجي",een:"The loud noise caused an avalanche on the mountain.",ear:"تسبب الصوت العالي في انهيار ثلجي على الجبل.",def:"a large mass of snow falling down a mountain",t:"mastery",u:3},
{w:"heatwave",c:"B1",s:"CEFR-J",p:"noun",ar:"موجة حر",een:"The heatwave lasted for two whole weeks.",ear:"استمرت موجة الحر لأسبوعين كاملين.",def:"a long period of unusually hot weather",t:"mastery",u:3},
{w:"funnel",c:"B1",s:"CEFR-J",p:"noun",ar:"قمع",een:"We saw a funnel cloud forming in the sky.",ear:"رأينا سحابة قمعية تتشكل في السماء.",def:"a cone shape, narrow at the bottom and wide at the top",t:"mastery",u:3},
{w:"meteorologist",c:"B1",s:"CEFR-J",p:"noun",ar:"عالم أرصاد جوية",een:"The meteorologist predicted rain for the weekend.",ear:"توقع عالم الأرصاد الجوية مطراً في نهاية الأسبوع.",def:"a scientist who studies and predicts weather",t:"mastery",u:3},
{w:"sandbag",c:"B1",s:"CEFR-J",p:"noun",ar:"كيس رمل",een:"People placed sandbags near the river to stop flooding.",ear:"وضع الناس أكياس الرمل بالقرب من النهر لمنع الفيضان.",def:"a bag filled with sand used to block water",t:"mastery",u:3},
{w:"unpredictable",c:"B1",s:"NGSL",p:"adjective",ar:"لا يمكن التنبؤ به",een:"The weather here is very unpredictable.",ear:"الطقس هنا لا يمكن التنبؤ به.",def:"impossible to know what will happen next",t:"mastery",u:3},
{w:"windshield",c:"B1",s:"CEFR-J",p:"noun",ar:"زجاج أمامي",een:"Hail cracked the car's windshield during the storm.",ear:"كسر البرد الزجاج الأمامي للسيارة أثناء العاصفة.",def:"the front glass window of a car",t:"mastery",u:3},
{w:"submerge",c:"B1",s:"NGSL",p:"verb",ar:"يغمر",een:"The rising water submerged several houses.",ear:"غمرت المياه المرتفعة عدة منازل.",def:"to go or put under water completely",t:"mastery",u:3},

// ============================================================
// UNIT 4: Fashion & Identity
// ============================================================

// --- Unit 4 Core ---
{w:"fashion",c:"A2",s:"CEFR-J",p:"noun",ar:"موضة",een:"Fashion changes every season.",ear:"تتغير الموضة كل موسم.",def:"the style of clothes that is popular now",t:"core",u:4},
{w:"style",c:"A2",s:"NGSL",p:"noun",ar:"أسلوب",een:"Everyone has their own personal style.",ear:"لكل شخص أسلوبه الشخصي.",def:"a way of doing or looking at things",t:"core",u:4},
{w:"dress",c:"A1",s:"CEFR-J",p:"noun",ar:"فستان",een:"She bought a beautiful red dress.",ear:"اشترت فستاناً أحمر جميلاً.",def:"a piece of women's clothing for the whole body",t:"core",u:4},
{w:"choose",c:"A2",s:"CEFR-J",p:"verb",ar:"يختار",een:"It is hard to choose what to wear today.",ear:"من الصعب اختيار ما ترتديه اليوم.",def:"to pick one thing from several options",t:"core",u:4},
{w:"pocket",c:"A2",s:"CEFR-J",p:"noun",ar:"جيب",een:"He put his keys in his jacket pocket.",ear:"وضع مفاتيحه في جيب سترته.",def:"a small bag sewn into clothes for carrying things",t:"core",u:4},
{w:"brand",c:"A2",s:"NGSL",p:"noun",ar:"علامة تجارية",een:"This brand makes very comfortable shoes.",ear:"هذه العلامة التجارية تصنع أحذية مريحة جداً.",def:"the name of a company that makes products",t:"core",u:4},
{w:"tight",c:"A2",s:"CEFR-J",p:"adjective",ar:"ضيق",een:"These jeans are too tight for me.",ear:"هذا الجينز ضيق جداً عليّ.",def:"fitting very closely to your body",t:"core",u:4},
{w:"loose",c:"A2",s:"CEFR-J",p:"adjective",ar:"واسع",een:"I prefer wearing loose clothes in summer.",ear:"أفضل ارتداء ملابس واسعة في الصيف.",def:"not tight, fitting with extra space",t:"core",u:4},
{w:"cotton",c:"A2",s:"CEFR-J",p:"noun",ar:"قطن",een:"This T-shirt is made of soft cotton.",ear:"هذا القميص مصنوع من قطن ناعم.",def:"a natural material used to make clothes",t:"core",u:4},
{w:"silk",c:"A2",s:"CEFR-J",p:"noun",ar:"حرير",een:"She wore a beautiful silk scarf.",ear:"ارتدت وشاحاً حريرياً جميلاً.",def:"a smooth soft material made by silkworms",t:"core",u:4},
{w:"trend",c:"A2",s:"NGSL",p:"noun",ar:"اتجاه",een:"Bright colors are the latest fashion trend.",ear:"الألوان الزاهية هي أحدث اتجاه في الموضة.",def:"what is popular at a certain time",t:"core",u:4},
{w:"suit",c:"A2",s:"CEFR-J",p:"noun",ar:"بذلة",een:"He wore a dark blue suit to the meeting.",ear:"ارتدى بذلة زرقاء داكنة للاجتماع.",def:"a set of jacket and pants worn together",t:"core",u:4},
{w:"material",c:"A2",s:"NGSL",p:"noun",ar:"مادة",een:"What material is this jacket made from?",ear:"من أي مادة صُنعت هذه السترة؟",def:"the substance that something is made of",t:"core",u:4},
{w:"confidence",c:"A2",s:"NGSL",p:"noun",ar:"ثقة",een:"Wearing nice clothes gives her more confidence.",ear:"ارتداء ملابس جميلة يمنحها مزيداً من الثقة.",def:"a feeling of being sure about yourself",t:"core",u:4},
{w:"jewelry",c:"A2",s:"CEFR-J",p:"noun",ar:"مجوهرات",een:"She likes to wear simple gold jewelry.",ear:"تحب ارتداء مجوهرات ذهبية بسيطة.",def:"rings, necklaces, and other pretty things you wear",t:"core",u:4},
{w:"hat",c:"A1",s:"CEFR-J",p:"noun",ar:"قبعة",een:"He always wears a hat when it is sunny.",ear:"يرتدي دائماً قبعة عندما يكون الطقس مشمساً.",def:"something you wear on your head",t:"core",u:4},
{w:"leather",c:"A2",s:"CEFR-J",p:"noun",ar:"جلد",een:"He bought a brown leather jacket.",ear:"اشترى سترة جلدية بنية.",def:"material made from animal skin",t:"core",u:4},
{w:"sew",c:"A2",s:"CEFR-J",p:"verb",ar:"يخيط",een:"My mother taught me how to sew a button.",ear:"علمتني أمي كيف أخيط زراً.",def:"to join cloth using a needle and thread",t:"core",u:4},
{w:"heel",c:"A2",s:"CEFR-J",p:"noun",ar:"كعب",een:"She cannot walk in high heels all day.",ear:"لا تستطيع المشي بالكعب العالي طوال اليوم.",def:"the raised part at the back of a shoe",t:"core",u:4},
{w:"plain",c:"A2",s:"CEFR-J",p:"adjective",ar:"سادة",een:"I prefer plain shirts without any design.",ear:"أفضل القمصان السادة بدون أي تصميم.",def:"simple, without decoration or pattern",t:"core",u:4},
{w:"appearance",c:"A2",s:"NGSL",p:"noun",ar:"مظهر",een:"First impressions are often based on appearance.",ear:"الانطباعات الأولى غالباً ما تعتمد على المظهر.",def:"how someone or something looks",t:"core",u:4},
{w:"outfit",c:"A2",s:"CEFR-J",p:"noun",ar:"طقم ملابس",een:"She planned her outfit for the wedding.",ear:"خططت لطقم ملابسها لحفل الزفاف.",def:"a set of clothes worn together",t:"core",u:4},
{w:"sleeve",c:"A2",s:"CEFR-J",p:"noun",ar:"كُم",een:"Roll up your sleeves before you start cooking.",ear:"اطوِ أكمامك قبل أن تبدأ الطبخ.",def:"the part of clothing that covers your arm",t:"core",u:4},
{w:"iron",c:"A2",s:"CEFR-J",p:"verb",ar:"يكوي",een:"You should iron your shirt before the interview.",ear:"يجب أن تكوي قميصك قبل المقابلة.",def:"to make clothes flat and smooth using heat",t:"core",u:4},
{w:"scarf",c:"A2",s:"CEFR-J",p:"noun",ar:"وشاح",een:"She wrapped a warm scarf around her neck.",ear:"لفّت وشاحاً دافئاً حول رقبتها.",def:"a piece of cloth worn around the neck or head",t:"core",u:4},
{w:"personal",c:"A2",s:"NGSL",p:"adjective",ar:"شخصي",een:"Clothing is a form of personal expression.",ear:"الملابس شكل من أشكال التعبير الشخصي.",def:"belonging to or about one person",t:"core",u:4},
{w:"put on",c:"A1",s:"CEFR-J",p:"verb",ar:"يلبس",een:"Put on a jacket because it is cold outside.",ear:"البس سترة لأن الجو بارد بالخارج.",def:"to place clothing on your body",t:"core",u:4},
{w:"cozy",c:"A2",s:"CEFR-J",p:"adjective",ar:"دافئ ومريح",een:"This sweater feels so warm and cozy.",ear:"هذه الكنزة دافئة ومريحة جداً.",def:"warm and comfortable in a nice way",t:"core",u:4},
{w:"clasp",c:"A2",s:"CEFR-J",p:"noun",ar:"مشبك",een:"The clasp on her necklace was hard to open.",ear:"كان المشبك على عقدها صعب الفتح.",def:"a small device that holds things closed",t:"core",u:4},
{w:"shrink",c:"A2",s:"CEFR-J",p:"verb",ar:"ينكمش",een:"My shirt will shrink if I wash it in hot water.",ear:"سينكمش قميصي إذا غسلته بالماء الساخن.",def:"to become smaller, especially after washing",t:"core",u:4},
{w:"coordinate",c:"A2",s:"NGSL",p:"verb",ar:"ينسّق",een:"She likes to coordinate her shoes with her bag.",ear:"تحب تنسيق حذائها مع حقيبتها.",def:"to make things go well together",t:"core",u:4},
{w:"print",c:"A2",s:"NGSL",p:"noun",ar:"طبعة",een:"I love the flower print on this fabric.",ear:"أحب الطبعة الزهرية على هذا القماش.",def:"a design printed on cloth or paper",t:"core",u:4},
{w:"plaid",c:"A2",s:"CEFR-J",p:"noun",ar:"نقش مربعات",een:"He wore a plaid shirt to the countryside.",ear:"ارتدى قميصاً بنقش المربعات إلى الريف.",def:"a pattern of crossed lines forming squares",t:"core",u:4},
// --- Unit 4 Extended ---
{w:"fabric",c:"A2",s:"NGSL",p:"noun",ar:"قماش",een:"This fabric feels very soft and smooth.",ear:"هذا القماش ناعم وأملس جداً.",def:"cloth or material used to make clothes",t:"extended",u:4},
{w:"designer",c:"A2",s:"NGSL",p:"noun",ar:"مصمم",een:"The designer showed her new collection in Paris.",ear:"عرضت المصممة مجموعتها الجديدة في باريس.",def:"a person who plans how things will look",t:"extended",u:4},
{w:"casual",c:"A2",s:"NGSL",p:"adjective",ar:"غير رسمي",een:"You can wear casual clothes to the party.",ear:"يمكنك ارتداء ملابس غير رسمية للحفلة.",def:"relaxed and not formal",t:"extended",u:4},
{w:"elegant",c:"B1",s:"CEFR-J",p:"adjective",ar:"أنيق",een:"She looked very elegant in her black dress.",ear:"بدت أنيقة جداً في فستانها الأسود.",def:"beautiful and stylish in a graceful way",t:"extended",u:4},
{w:"accessory",c:"A2",s:"CEFR-J",p:"noun",ar:"إكسسوار",een:"A nice bag is the perfect fashion accessory.",ear:"الحقيبة الجميلة هي الإكسسوار المثالي.",def:"an extra item worn with clothes like a bag or belt",t:"extended",u:4},
{w:"wardrobe",c:"A2",s:"CEFR-J",p:"noun",ar:"خزانة ملابس",een:"She has a very big wardrobe full of clothes.",ear:"لديها خزانة ملابس كبيرة جداً مليئة بالملابس.",def:"a large closet for keeping clothes",t:"extended",u:4},
{w:"denim",c:"A2",s:"CEFR-J",p:"noun",ar:"قماش جينز",een:"Denim jackets are popular all over the world.",ear:"سترات الجينز شائعة في جميع أنحاء العالم.",def:"a strong cotton cloth used to make jeans",t:"extended",u:4},
{w:"stitch",c:"A2",s:"CEFR-J",p:"noun",ar:"غرزة",een:"The tailor made small neat stitches.",ear:"صنع الخياط غرزاً صغيرة ومتقنة.",def:"one loop of thread in sewing",t:"extended",u:4},
{w:"collar",c:"A2",s:"CEFR-J",p:"noun",ar:"ياقة",een:"This shirt has a very stiff collar.",ear:"هذا القميص لديه ياقة صلبة جداً.",def:"the part of a shirt around your neck",t:"extended",u:4},
{w:"identity",c:"A2",s:"NGSL",p:"noun",ar:"هوية",een:"Clothes can be part of your identity.",ear:"يمكن أن تكون الملابس جزءاً من هويتك.",def:"who a person is and what makes them special",t:"extended",u:4},
{w:"collection",c:"A2",s:"NGSL",p:"noun",ar:"مجموعة",een:"The new spring collection looks amazing.",ear:"مجموعة الربيع الجديدة تبدو مذهلة.",def:"a group of things gathered together",t:"extended",u:4},
{w:"trendy",c:"A2",s:"CEFR-J",p:"adjective",ar:"عصري",een:"This shop sells very trendy clothes.",ear:"يبيع هذا المتجر ملابس عصرية جداً.",def:"very fashionable and popular right now",t:"extended",u:4},
{w:"label",c:"A2",s:"NGSL",p:"noun",ar:"ملصق",een:"Always read the care label before washing clothes.",ear:"اقرأ دائماً ملصق العناية قبل غسل الملابس.",def:"a piece of paper or cloth with information on it",t:"extended",u:4},
{w:"model",c:"A2",s:"NGSL",p:"noun",ar:"عارض أزياء",een:"The model walked down the runway in a red dress.",ear:"مشت عارضة الأزياء على المنصة بفستان أحمر.",def:"a person who wears clothes to show them",t:"extended",u:4},
{w:"thread",c:"A2",s:"CEFR-J",p:"noun",ar:"خيط",een:"I need a needle and thread to fix this tear.",ear:"أحتاج إبرة وخيطاً لإصلاح هذا التمزق.",def:"a thin piece of cotton used in sewing",t:"extended",u:4},
{w:"occasion",c:"A2",s:"NGSL",p:"noun",ar:"مناسبة",een:"This dress is perfect for a special occasion.",ear:"هذا الفستان مثالي لمناسبة خاصة.",def:"an important event or time",t:"extended",u:4},
{w:"personality",c:"A2",s:"NGSL",p:"noun",ar:"شخصية",een:"Your clothes say a lot about your personality.",ear:"تقول ملابسك الكثير عن شخصيتك.",def:"the qualities that make a person unique",t:"extended",u:4},
{w:"tailor",c:"A2",s:"CEFR-J",p:"noun",ar:"خياط",een:"The tailor made the suit fit perfectly.",ear:"جعل الخياط البذلة تناسب تماماً.",def:"a person who makes or fixes clothes",t:"extended",u:4},
{w:"fold",c:"A2",s:"CEFR-J",p:"verb",ar:"يطوي",een:"Please fold your clothes and put them away.",ear:"من فضلك اطوِ ملابسك وضعها في مكانها.",def:"to bend something so one part covers another",t:"extended",u:4},
{w:"formal",c:"A2",s:"NGSL",p:"adjective",ar:"رسمي",een:"You must wear formal clothes to the dinner.",ear:"يجب أن ترتدي ملابس رسمية للعشاء.",def:"following official rules about dress or behavior",t:"extended",u:4},
{w:"runway",c:"B1",s:"CEFR-J",p:"noun",ar:"منصة عرض أزياء",een:"The models walked down the runway one by one.",ear:"مشت عارضات الأزياء على المنصة واحدة تلو الأخرى.",def:"a long narrow stage for fashion shows",t:"extended",u:4},
{w:"secondhand",c:"A2",s:"CEFR-J",p:"adjective",ar:"مستعمل",een:"Buying secondhand clothes is better for the planet.",ear:"شراء الملابس المستعملة أفضل للكوكب.",def:"previously owned or used by someone else",t:"extended",u:4},
{w:"bold",c:"A2",s:"NGSL",p:"adjective",ar:"جريء",een:"She made a bold choice with her bright red coat.",ear:"قامت باختيار جريء بمعطفها الأحمر الزاهي.",def:"strong, bright, and not afraid to be noticed",t:"extended",u:4},
{w:"sweatshirt",c:"A2",s:"CEFR-J",p:"noun",ar:"كنزة رياضية",een:"He wore a grey sweatshirt to school.",ear:"ارتدى كنزة رياضية رمادية للمدرسة.",def:"a warm soft top usually made of cotton",t:"extended",u:4},
{w:"influence",c:"A2",s:"NGSL",p:"noun",ar:"تأثير",een:"Social media has a big influence on fashion.",ear:"لوسائل التواصل الاجتماعي تأثير كبير على الموضة.",def:"the power to change how someone thinks or acts",t:"extended",u:4},
{w:"zipper",c:"A2",s:"CEFR-J",p:"noun",ar:"سحّاب",een:"The zipper on my jacket is broken.",ear:"السحاب على سترتي مكسور.",def:"a device with teeth used to close clothes or bags",t:"extended",u:4},
{w:"mixture",c:"A2",s:"NGSL",p:"noun",ar:"مزيج",een:"Her style is a mixture of modern and classic.",ear:"أسلوبها مزيج من الحديث والكلاسيكي.",def:"a combination of different things together",t:"extended",u:4},
{w:"convey",c:"B1",s:"NGSL",p:"verb",ar:"ينقل",een:"Your clothes can convey a message about who you are.",ear:"يمكن لملابسك أن تنقل رسالة عن هويتك.",def:"to communicate a message or feeling",t:"extended",u:4},
{w:"symbolize",c:"B1",s:"NGSL",p:"verb",ar:"يرمز إلى",een:"In some cultures, red clothes symbolize good luck.",ear:"في بعض الثقافات ترمز الملابس الحمراء للحظ الجيد.",def:"to be a sign or symbol of something",t:"extended",u:4},
// --- Unit 4 Mastery ---
{w:"couture",c:"B1",s:"CEFR-J",p:"noun",ar:"أزياء راقية",een:"Paris is famous for its haute couture fashion houses.",ear:"باريس مشهورة بدور أزيائها الراقية.",def:"expensive custom-made clothes of high quality",t:"mastery",u:4},
{w:"textile",c:"B1",s:"NGSL",p:"noun",ar:"نسيج",een:"The country exports many different textiles.",ear:"يصدّر البلد أنسجة مختلفة كثيرة.",def:"any type of cloth or woven material",t:"mastery",u:4},
{w:"embroider",c:"B1",s:"CEFR-J",p:"verb",ar:"يطرّز",een:"She learned to embroider flowers on fabric.",ear:"تعلمت تطريز الزهور على القماش.",def:"to sew a design onto cloth with thread",t:"mastery",u:4},
{w:"garment",c:"B1",s:"NGSL",p:"noun",ar:"ثوب",een:"Each garment in the store is handmade.",ear:"كل ثوب في المتجر مصنوع يدوياً.",def:"a piece of clothing",t:"mastery",u:4},
{w:"tailor-made",c:"B1",s:"CEFR-J",p:"adjective",ar:"مفصّل",een:"He ordered a tailor-made suit for his wedding.",ear:"طلب بذلة مفصلة لحفل زفافه.",def:"made specially for one person",t:"mastery",u:4},
{w:"hem",c:"B1",s:"CEFR-J",p:"noun",ar:"حاشية",een:"The hem of her dress was too long.",ear:"كانت حاشية فستانها طويلة جداً.",def:"the bottom edge of a piece of clothing",t:"mastery",u:4},
{w:"individualism",c:"B1",s:"NGSL",p:"noun",ar:"فردانية",een:"Fashion can be a way to show individualism.",ear:"يمكن أن تكون الموضة طريقة لإظهار الفردانية.",def:"the idea of being different and unique",t:"mastery",u:4},
{w:"conform",c:"B1",s:"NGSL",p:"verb",ar:"يمتثل",een:"Not everyone wants to conform to fashion rules.",ear:"لا يريد الجميع الامتثال لقواعد الموضة.",def:"to follow rules or behave like most people",t:"mastery",u:4},
{w:"versatile",c:"B1",s:"NGSL",p:"adjective",ar:"متعدد الاستخدامات",een:"A white shirt is the most versatile clothing item.",ear:"القميص الأبيض هو أكثر قطعة ملابس تعدداً في الاستخدام.",def:"useful in many different ways",t:"mastery",u:4},
{w:"exclusive",c:"B1",s:"NGSL",p:"adjective",ar:"حصري",een:"This store sells exclusive designer clothing.",ear:"يبيع هذا المتجر ملابس مصممين حصرية.",def:"only for certain people, very special",t:"mastery",u:4},
{w:"imitate",c:"B1",s:"NGSL",p:"verb",ar:"يقلّد",een:"Young people often imitate celebrities' fashion.",ear:"غالباً ما يقلد الشباب أزياء المشاهير.",def:"to copy someone else's behavior or style",t:"mastery",u:4},
{w:"rebellion",c:"B1",s:"NGSL",p:"noun",ar:"تمرد",een:"Punk fashion started as a form of rebellion.",ear:"بدأت أزياء البانك كشكل من أشكال التمرد.",def:"fighting against rules or authority",t:"mastery",u:4},
{w:"stereotype",c:"B1",s:"NGSL",p:"noun",ar:"صورة نمطية",een:"Fashion can help break gender stereotypes.",ear:"يمكن للموضة أن تساعد في كسر الصور النمطية.",def:"a fixed and often wrong idea about a group",t:"mastery",u:4},
{w:"symbolic",c:"B1",s:"NGSL",p:"adjective",ar:"رمزي",een:"The color white is symbolic of peace.",ear:"اللون الأبيض رمز للسلام.",def:"representing an idea or meaning",t:"mastery",u:4},
{w:"handmade",c:"A2",s:"CEFR-J",p:"adjective",ar:"مصنوع يدوياً",een:"Handmade jewelry is often more expensive.",ear:"المجوهرات المصنوعة يدوياً غالباً أغلى ثمناً.",def:"made by a person's hands, not a machine",t:"mastery",u:4},
{w:"knit",c:"B1",s:"CEFR-J",p:"verb",ar:"يحيك",een:"My grandmother likes to knit warm sweaters.",ear:"جدتي تحب حياكة الكنزات الدافئة.",def:"to make cloth by looping yarn with needles",t:"mastery",u:4},
{w:"folklore",c:"B1",s:"NGSL",p:"noun",ar:"تراث شعبي",een:"Many traditional clothes are inspired by local folklore.",ear:"كثير من الملابس التقليدية مستوحاة من التراث الشعبي المحلي.",def:"old stories and traditions of a group of people",t:"mastery",u:4},
{w:"avant-garde",c:"B1",s:"CEFR-J",p:"adjective",ar:"طليعي",een:"The designer is known for avant-garde fashion shows.",ear:"المصمم معروف بعروض أزياء طليعية.",def:"new and very different from what is normal",t:"mastery",u:4},
{w:"well-known",c:"A2",s:"CEFR-J",p:"adjective",ar:"معروف",een:"Jeans are a well-known symbol of casual fashion.",ear:"الجينز رمز معروف للأزياء غير الرسمية.",def:"famous and recognized by many people",t:"mastery",u:4},
{w:"visual style",c:"B1",s:"CEFR-J",p:"noun",ar:"أسلوب بصري",een:"Her visual style mixes bright colors and simple shapes.",ear:"يمزج أسلوبها البصري الألوان الزاهية والأشكال البسيطة.",def:"the way something looks as a whole",t:"mastery",u:4},
{w:"genuine",c:"B1",s:"NGSL",p:"adjective",ar:"حقيقي",een:"She has a genuine and honest personal style.",ear:"لديها أسلوب شخصي حقيقي وصادق.",def:"real and not fake or copied",t:"mastery",u:4},
{w:"upcycle",c:"B1",s:"CEFR-J",p:"verb",ar:"يعيد تصنيع",een:"She learned to upcycle old jeans into stylish bags.",ear:"تعلمت إعادة تصنيع الجينز القديم إلى حقائب أنيقة.",def:"to make something new and better from old materials",t:"mastery",u:4},
{w:"eco-conscious",c:"B1",s:"CEFR-J",p:"adjective",ar:"واعٍ بيئياً",een:"More people are becoming eco-conscious about fashion.",ear:"أصبح المزيد من الناس واعين بيئياً تجاه الموضة.",def:"thinking about how actions affect the environment",t:"mastery",u:4},
{w:"inclusion",c:"B1",s:"NGSL",p:"noun",ar:"شمولية",een:"The fashion show promoted inclusion of all body types.",ear:"عزز عرض الأزياء شمولية جميع أشكال الجسم.",def:"including everyone and making them feel welcome",t:"mastery",u:4},
{w:"impression",c:"A2",s:"NGSL",p:"noun",ar:"انطباع",een:"Your outfit creates a first impression on people.",ear:"يخلق طقم ملابسك انطباعاً أولياً لدى الناس.",def:"the idea or feeling you get about someone",t:"mastery",u:4},
{w:"transformation",c:"B1",s:"NGSL",p:"noun",ar:"تحوّل",een:"Social media caused a big transformation in fashion.",ear:"تسبب وسائل التواصل الاجتماعي في تحوّل كبير في الموضة.",def:"a big change in how something looks or works",t:"mastery",u:4}
];
