module.exports = [
// ========== UNIT 9: Film & Cinema (88 words) ==========
// Core (33)
{w:"film",c:"A1",s:"NGSL",p:"noun",ar:"فيلم",een:"We watched a great film last night.",ear:"شاهدنا فيلمًا رائعًا الليلة الماضية.",def:"a movie you watch on a screen",t:"core",u:9},
{w:"actor",c:"A2",s:"CEFR-J",p:"noun",ar:"ممثل",een:"The actor performed very well in the movie.",ear:"أدّى الممثل دورًا رائعًا في الفيلم.",def:"a person who acts in films or plays",t:"core",u:9},
{w:"actress",c:"A2",s:"CEFR-J",p:"noun",ar:"ممثلة",een:"She is a famous actress in Egypt.",ear:"هي ممثلة مشهورة في مصر.",def:"a woman who acts in films or plays",t:"core",u:9},
{w:"scene",c:"A2",s:"CEFR-J",p:"noun",ar:"مشهد",een:"The last scene of the movie was very sad.",ear:"المشهد الأخير من الفيلم كان حزينًا جدًا.",def:"a part of a film or play",t:"core",u:9},
{w:"cinema",c:"A2",s:"CEFR-J",p:"noun",ar:"سينما",een:"Let's go to the cinema this weekend.",ear:"لنذهب إلى السينما نهاية هذا الأسبوع.",def:"a place where you go to watch movies",t:"core",u:9},
{w:"direct",c:"A2",s:"NGSL",p:"verb",ar:"يُخرج",een:"He wants to direct his own movie someday.",ear:"يريد أن يُخرج فيلمه الخاص يومًا ما.",def:"to control how a film or play is made",t:"core",u:9},
{w:"director",c:"A2",s:"CEFR-J",p:"noun",ar:"مُخرج",een:"The director told the actors where to stand.",ear:"أخبر المُخرج الممثلين أين يقفون.",def:"the person who controls making a film",t:"core",u:9},
{w:"act",c:"A2",s:"NGSL",p:"verb",ar:"يُمثّل",een:"She learned to act when she was young.",ear:"تعلّمت التمثيل عندما كانت صغيرة.",def:"to pretend to be another person in a film",t:"core",u:9},
{w:"role",c:"A2",s:"NGSL",p:"noun",ar:"دور",een:"He got the main role in the school play.",ear:"حصل على الدور الرئيسي في مسرحية المدرسة.",def:"a character that an actor plays",t:"core",u:9},
{w:"scary",c:"A2",s:"CEFR-J",p:"adjective",ar:"مخيف",een:"I don't like scary movies at night.",ear:"لا أحب الأفلام المخيفة في الليل.",def:"making you feel afraid",t:"core",u:9},
{w:"funny",c:"A1",s:"NGSL",p:"adjective",ar:"مضحك",een:"The comedy film was really funny.",ear:"الفيلم الكوميدي كان مضحكًا حقًا.",def:"making you laugh",t:"core",u:9},
{w:"sad",c:"A1",s:"NGSL",p:"adjective",ar:"حزين",een:"The ending of the story was very sad.",ear:"نهاية القصة كانت حزينة جدًا.",def:"feeling unhappy or making you feel unhappy",t:"core",u:9},
{w:"character",c:"A2",s:"NGSL",p:"noun",ar:"شخصية",een:"My favorite character in the film is the hero.",ear:"شخصيتي المفضلة في الفيلم هي البطل.",def:"a person in a story, film, or play",t:"core",u:9},
{w:"story",c:"A1",s:"NGSL",p:"noun",ar:"قصة",een:"The movie tells the story of a young girl.",ear:"يحكي الفيلم قصة فتاة صغيرة.",def:"a description of events, real or imagined",t:"core",u:9},
{w:"ending",c:"A2",s:"NGSL",p:"noun",ar:"نهاية",een:"I did not expect that ending at all.",ear:"لم أتوقع تلك النهاية على الإطلاق.",def:"the last part of a film or story",t:"core",u:9},
{w:"comedy",c:"A2",s:"CEFR-J",p:"noun",ar:"كوميديا",een:"We love watching comedy films together.",ear:"نحب مشاهدة أفلام الكوميديا معًا.",def:"a funny film or show that makes you laugh",t:"core",u:9},
{w:"action",c:"A2",s:"NGSL",p:"noun",ar:"أكشن",een:"Action movies have a lot of fighting scenes.",ear:"أفلام الأكشن تحتوي على كثير من مشاهد القتال.",def:"exciting and fast events in a film",t:"core",u:9},
{w:"horror",c:"A2",s:"CEFR-J",p:"noun",ar:"رعب",een:"Horror films make me close my eyes.",ear:"أفلام الرعب تجعلني أغلق عيني.",def:"a type of film that is very scary",t:"core",u:9},
{w:"animation",c:"A2",s:"CEFR-J",p:"noun",ar:"رسوم متحركة",een:"Children love watching animation movies.",ear:"يحب الأطفال مشاهدة أفلام الرسوم المتحركة.",def:"a film made with drawings or computer images",t:"core",u:9},
{w:"review",c:"A2",s:"NGSL",p:"noun",ar:"مراجعة",een:"I read the review before watching the movie.",ear:"قرأت المراجعة قبل مشاهدة الفيلم.",def:"an opinion about a film, book, or product",t:"core",u:9},
{w:"plot",c:"A2",s:"NGSL",p:"noun",ar:"حبكة",een:"The plot of this movie is very interesting.",ear:"حبكة هذا الفيلم ممتعة جدًا.",def:"the main events that make up a story",t:"core",u:9},
{w:"series",c:"A2",s:"NGSL",p:"noun",ar:"مسلسل",een:"I am watching a new series on TV.",ear:"أشاهد مسلسلًا جديدًا على التلفاز.",def:"a set of TV shows with the same characters",t:"core",u:9},
{w:"seat",c:"A2",s:"NGSL",p:"noun",ar:"مقعد",een:"We got the best seats in the cinema.",ear:"حصلنا على أفضل المقاعد في السينما.",def:"a place where you sit",t:"core",u:9},
{w:"appear",c:"A2",s:"NGSL",p:"verb",ar:"يظهر",een:"The main actor will appear in the next scene.",ear:"سيظهر الممثل الرئيسي في المشهد التالي.",def:"to be seen or to come into view",t:"core",u:9},
{w:"award",c:"A2",s:"NGSL",p:"noun",ar:"جائزة",een:"The film won the best award this year.",ear:"فاز الفيلم بأفضل جائزة هذا العام.",def:"a prize given for doing something well",t:"core",u:9},
{w:"viewer",c:"A2",s:"NGSL",p:"noun",ar:"مشاهد",een:"The film attracted millions of viewers worldwide.",ear:"جذب الفيلم ملايين المشاهدين حول العالم.",def:"a person who watches a film or TV show",t:"core",u:9},
{w:"dialogue",c:"A2",s:"CEFR-J",p:"noun",ar:"حوار",een:"The dialogue in this movie is very natural.",ear:"الحوار في هذا الفيلم طبيعي جدًا.",def:"the words spoken by characters in a film",t:"core",u:9},
{w:"subtitle",c:"A2",s:"CEFR-J",p:"noun",ar:"ترجمة مرئية",een:"I need subtitles to understand foreign films.",ear:"أحتاج إلى ترجمة مرئية لفهم الأفلام الأجنبية.",def:"translated words shown at the bottom of a screen",t:"core",u:9},
{w:"release",c:"A2",s:"NGSL",p:"verb",ar:"يصدر",een:"They will release the new movie next month.",ear:"سيصدرون الفيلم الجديد الشهر القادم.",def:"to make something available to the public",t:"core",u:9},
{w:"theater",c:"A2",s:"NGSL",p:"noun",ar:"مسرح",een:"We saw a play at the theater downtown.",ear:"شاهدنا مسرحية في المسرح وسط المدينة.",def:"a building where people watch plays or films",t:"core",u:9},
{w:"suggest",c:"A2",s:"NGSL",p:"verb",ar:"يقترح",een:"Can you suggest a good movie to watch tonight?",ear:"هل تقترح فيلمًا جيدًا نشاهده الليلة؟",def:"to tell someone your idea about what to do",t:"core",u:9},
{w:"dull",c:"A2",s:"NGSL",p:"adjective",ar:"ممل",een:"The movie was so dull that I fell asleep.",ear:"كان الفيلم مملًا جدًا حتى أنني نمت.",def:"not interesting or exciting",t:"core",u:9},
{w:"amusing",c:"A2",s:"NGSL",p:"adjective",ar:"مسلٍّ",een:"The film was very amusing and made us laugh.",ear:"كان الفيلم مسليًا جدًا وأضحكنا.",def:"funny and enjoyable to watch",t:"core",u:9},

// Extended (29)
{w:"screenplay",c:"B1",s:"CEFR-J",p:"noun",ar:"سيناريو",een:"She wrote the screenplay for the new movie.",ear:"كتبت السيناريو للفيلم الجديد.",def:"the written text of a movie with all the dialogue",t:"extended",u:9},
{w:"producer",c:"A2",s:"NGSL",p:"noun",ar:"منتج",een:"The producer found the money to make the film.",ear:"وجد المنتج المال لصنع الفيلم.",def:"a person who organizes and pays for a film",t:"extended",u:9},
{w:"sequel",c:"B1",s:"CEFR-J",p:"noun",ar:"جزء ثانٍ",een:"The sequel was even better than the first film.",ear:"كان الجزء الثاني أفضل من الفيلم الأول.",def:"a film that continues the story of an earlier one",t:"extended",u:9},
{w:"fiction",c:"A2",s:"NGSL",p:"noun",ar:"خيال",een:"This story is fiction, not real events.",ear:"هذه القصة خيالية وليست أحداثًا حقيقية.",def:"stories about things that are not real",t:"extended",u:9},
{w:"thriller",c:"A2",s:"CEFR-J",p:"noun",ar:"فيلم إثارة",een:"This thriller keeps you guessing until the end.",ear:"فيلم الإثارة هذا يجعلك تخمّن حتى النهاية.",def:"an exciting film that makes you feel nervous",t:"extended",u:9},
{w:"cast",c:"A2",s:"NGSL",p:"noun",ar:"طاقم تمثيل",een:"The whole cast did an amazing job.",ear:"قام طاقم التمثيل بأكمله بعمل رائع.",def:"all the actors in a film or play",t:"extended",u:9},
{w:"script",c:"A2",s:"CEFR-J",p:"noun",ar:"نص",een:"The actors must learn the script by heart.",ear:"يجب على الممثلين حفظ النص عن ظهر قلب.",def:"the written words of a film or play",t:"extended",u:9},
{w:"trailer",c:"A2",s:"CEFR-J",p:"noun",ar:"إعلان تشويقي",een:"I saw the trailer and I want to watch it.",ear:"شاهدت الإعلان التشويقي وأريد مشاهدته.",def:"a short video that shows parts of a new movie",t:"extended",u:9},
{w:"romantic",c:"A2",s:"CEFR-J",p:"adjective",ar:"رومانسي",een:"She loves watching romantic movies on weekends.",ear:"تحب مشاهدة الأفلام الرومانسية في عطلة نهاية الأسبوع.",def:"relating to love and feelings between people",t:"extended",u:9},
{w:"documentary",c:"A2",s:"CEFR-J",p:"noun",ar:"فيلم وثائقي",een:"We watched a documentary about ocean life.",ear:"شاهدنا فيلمًا وثائقيًا عن الحياة البحرية.",def:"a film that shows real events and facts",t:"extended",u:9},
{w:"studio",c:"A2",s:"NGSL",p:"noun",ar:"استوديو",een:"The movie was made in a big studio.",ear:"صُنع الفيلم في استوديو كبير.",def:"a room or building where films are made",t:"extended",u:9},
{w:"episode",c:"A2",s:"CEFR-J",p:"noun",ar:"حلقة",een:"I watched three episodes of the series today.",ear:"شاهدت ثلاث حلقات من المسلسل اليوم.",def:"one part of a TV series",t:"extended",u:9},
{w:"imagine",c:"A2",s:"NGSL",p:"verb",ar:"يتخيّل",een:"Can you imagine living on another planet?",ear:"هل تستطيع تخيّل العيش على كوكب آخر؟",def:"to make a picture in your mind",t:"extended",u:9},
{w:"villain",c:"B1",s:"CEFR-J",p:"noun",ar:"شرير",een:"The villain in this movie is very clever.",ear:"الشرير في هذا الفيلم ذكي جدًا.",def:"the bad character in a story or film",t:"extended",u:9},
{w:"soundtrack",c:"B1",s:"CEFR-J",p:"noun",ar:"موسيقى تصويرية",een:"The soundtrack of this film is beautiful.",ear:"الموسيقى التصويرية لهذا الفيلم جميلة.",def:"the music that plays during a movie",t:"extended",u:9},
{w:"genre",c:"B1",s:"CEFR-J",p:"noun",ar:"نوع أدبي",een:"What is your favorite movie genre?",ear:"ما هو نوع الأفلام المفضل لديك؟",def:"a type or category of film, book, or music",t:"extended",u:9},
{w:"popcorn",c:"A2",s:"CEFR-J",p:"noun",ar:"فشار",een:"We always eat popcorn at the cinema.",ear:"نأكل الفشار دائمًا في السينما.",def:"a snack made from heated corn seeds",t:"extended",u:9},
{w:"suspense",c:"B1",s:"CEFR-J",p:"noun",ar:"تشويق",een:"The movie is full of suspense and surprise.",ear:"الفيلم مليء بالتشويق والمفاجآت.",def:"a feeling of excitement about what will happen next",t:"extended",u:9},
{w:"entertaining",c:"A2",s:"NGSL",p:"adjective",ar:"ممتع",een:"The show was very entertaining for everyone.",ear:"كان العرض ممتعًا جدًا للجميع.",def:"fun and enjoyable to watch",t:"extended",u:9},
{w:"fantasy",c:"A2",s:"NGSL",p:"noun",ar:"خيال",een:"He likes fantasy movies with magic and dragons.",ear:"يحب أفلام الخيال مع السحر والتنانين.",def:"a story with magical or impossible things",t:"extended",u:9},
{w:"projector",c:"A2",s:"CEFR-J",p:"noun",ar:"جهاز عرض",een:"The projector shows the film on a big screen.",ear:"يعرض جهاز العرض الفيلم على شاشة كبيرة.",def:"a machine that shows images on a wall or screen",t:"extended",u:9},
{w:"mystery",c:"A2",s:"NGSL",p:"noun",ar:"غموض",een:"I love watching mystery films with my family.",ear:"أحب مشاهدة أفلام الغموض مع عائلتي.",def:"something strange that is hard to explain",t:"extended",u:9},
{w:"spoiler",c:"B1",s:"CEFR-J",p:"noun",ar:"حرق أحداث",een:"Don't tell me any spoilers about the movie!",ear:"لا تخبرني بأي تفاصيل عن أحداث الفيلم!",def:"information that tells you what happens in a story",t:"extended",u:9},
{w:"classic",c:"A2",s:"NGSL",p:"adjective",ar:"كلاسيكي",een:"This is a classic film that everyone should see.",ear:"هذا فيلم كلاسيكي يجب على الجميع مشاهدته.",def:"very good and popular for a long time",t:"extended",u:9},
{w:"impressed",c:"A2",s:"NGSL",p:"adjective",ar:"معجب",een:"I was really impressed by her acting skills.",ear:"أُعجبت حقًا بمهاراتها في التمثيل.",def:"feeling admiration because something was very good",t:"extended",u:9},
{w:"volume",c:"A2",s:"NGSL",p:"noun",ar:"مستوى الصوت",een:"Please turn down the volume, it is too loud.",ear:"من فضلك اخفض مستوى الصوت، إنه مرتفع جدًا.",def:"how loud or quiet a sound is",t:"extended",u:9},
{w:"fade",c:"B1",s:"NGSL",p:"verb",ar:"يتلاشى",een:"The screen slowly faded to black at the end.",ear:"تلاشت الشاشة ببطء إلى اللون الأسود في النهاية.",def:"to slowly become less bright or clear",t:"extended",u:9},
{w:"wardrobe",c:"A2",s:"CEFR-J",p:"noun",ar:"خزانة أزياء",een:"The wardrobe for the movie had over fifty outfits.",ear:"احتوت خزانة الأزياء للفيلم على أكثر من خمسين زيًا.",def:"all the clothes used in a film or play",t:"extended",u:9},
{w:"shooting",c:"A2",s:"NGSL",p:"noun",ar:"تصوير",een:"The shooting of the new movie starts next week.",ear:"يبدأ تصوير الفيلم الجديد الأسبوع القادم.",def:"the process of making a film with cameras",t:"extended",u:9},

// Mastery (26)
{w:"premiere",c:"B1",s:"CEFR-J",p:"noun",ar:"عرض أول",een:"The premiere of the film was in London.",ear:"كان العرض الأول للفيلم في لندن.",def:"the first public showing of a new film",t:"mastery",u:9},
{w:"blockbuster",c:"B1",s:"CEFR-J",p:"noun",ar:"فيلم ضخم",een:"The new blockbuster earned millions of dollars.",ear:"حقق الفيلم الضخم الجديد ملايين الدولارات.",def:"a very successful and popular movie",t:"mastery",u:9},
{w:"cinematography",c:"B1",s:"CEFR-J",p:"noun",ar:"تصوير سينمائي",een:"The cinematography in this film is amazing.",ear:"التصوير السينمائي في هذا الفيلم مذهل.",def:"the art of making pictures for a film",t:"mastery",u:9},
{w:"dub",c:"B1",s:"CEFR-J",p:"verb",ar:"يدبلج",een:"They dubbed the movie into five languages.",ear:"دبلجوا الفيلم إلى خمس لغات.",def:"to replace voices in a film with another language",t:"mastery",u:9},
{w:"critic",c:"B1",s:"NGSL",p:"noun",ar:"ناقد",een:"The critic gave the movie a good review.",ear:"أعطى الناقد الفيلم مراجعة جيدة.",def:"a person whose job is to judge films or art",t:"mastery",u:9},
{w:"nomination",c:"B1",s:"CEFR-J",p:"noun",ar:"ترشيح",een:"The film got five nominations for best picture.",ear:"حصل الفيلم على خمسة ترشيحات لأفضل صورة.",def:"being chosen as a possible winner of a prize",t:"mastery",u:9},
{w:"footage",c:"B1",s:"CEFR-J",p:"noun",ar:"لقطات مصوّرة",een:"They showed old footage from the 1950s.",ear:"عرضوا لقطات مصوّرة قديمة من الخمسينيات.",def:"a piece of recorded film or video",t:"mastery",u:9},
{w:"stunt",c:"B1",s:"CEFR-J",p:"noun",ar:"حركة خطيرة",een:"The stunt in the car chase was incredible.",ear:"الحركة الخطيرة في مطاردة السيارة كانت مذهلة.",def:"a dangerous action done in a film",t:"mastery",u:9},
{w:"audition",c:"B1",s:"CEFR-J",p:"noun",ar:"اختبار أداء",een:"She went to an audition for a TV show.",ear:"ذهبت إلى اختبار أداء لبرنامج تلفزيوني.",def:"a test where an actor shows their skills",t:"mastery",u:9},
{w:"narrate",c:"B1",s:"CEFR-J",p:"verb",ar:"يروي",een:"A famous voice narrates the documentary.",ear:"صوت مشهور يروي الفيلم الوثائقي.",def:"to tell a story or explain what is happening",t:"mastery",u:9},
{w:"depict",c:"B1",s:"CEFR-J",p:"verb",ar:"يصوّر",een:"The movie depicts life in a small village.",ear:"يصوّر الفيلم الحياة في قرية صغيرة.",def:"to show or describe something in a picture or story",t:"mastery",u:9},
{w:"prop",c:"B1",s:"CEFR-J",p:"noun",ar:"دعامة مسرحية",een:"The sword in the film was just a prop.",ear:"السيف في الفيلم كان مجرد دعامة مسرحية.",def:"an object used by actors during a film or play",t:"mastery",u:9},
{w:"remake",c:"B1",s:"CEFR-J",p:"noun",ar:"إعادة إنتاج",een:"The remake of the old film was disappointing.",ear:"إعادة إنتاج الفيلم القديم كانت مخيبة للآمال.",def:"a new version of an old movie",t:"mastery",u:9},
{w:"box office",c:"B1",s:"CEFR-J",p:"noun",ar:"شباك التذاكر",een:"The movie did well at the box office.",ear:"نجح الفيلم في شباك التذاكر.",def:"the place where tickets are sold, or total sales",t:"mastery",u:9},
{w:"special effects",c:"A2",s:"CEFR-J",p:"noun",ar:"مؤثرات خاصة",een:"The special effects in this movie look very real.",ear:"المؤثرات الخاصة في هذا الفيلم تبدو حقيقية جدًا.",def:"images or sounds created by computers for films",t:"mastery",u:9},
{w:"freeze frame",c:"B1",s:"CEFR-J",p:"noun",ar:"تجميد الصورة",een:"The director used a freeze frame at the end.",ear:"استخدم المخرج تجميد الصورة في النهاية.",def:"stopping a moving picture to show one still image",t:"mastery",u:9},
{w:"on screen",c:"A2",s:"CEFR-J",p:"adverb",ar:"على الشاشة",een:"The two actors look great together on screen.",ear:"يبدو الممثلان رائعين معًا على الشاشة.",def:"appearing in a film or on television",t:"mastery",u:9},
{w:"behind the scenes",c:"A2",s:"CEFR-J",p:"adverb",ar:"خلف الكواليس",een:"I love watching behind the scenes videos.",ear:"أحب مشاهدة مقاطع الفيديو خلف الكواليس.",def:"the work that happens where the audience cannot see",t:"mastery",u:9},
{w:"opening night",c:"A2",s:"CEFR-J",p:"noun",ar:"ليلة الافتتاح",een:"Opening night of the movie was very exciting.",ear:"كانت ليلة افتتاح الفيلم مثيرة جدًا.",def:"the first night a film or show is presented",t:"mastery",u:9},
{w:"cliff-hanger",c:"B1",s:"CEFR-J",p:"noun",ar:"نهاية مشوّقة",een:"The episode ended with a big cliff-hanger.",ear:"انتهت الحلقة بنهاية مشوّقة كبيرة.",def:"an exciting ending that makes you want to know more",t:"mastery",u:9},
{w:"dubbed",c:"B1",s:"CEFR-J",p:"adjective",ar:"مدبلج",een:"I prefer dubbed movies in my own language.",ear:"أفضّل الأفلام المدبلجة بلغتي.",def:"having voices replaced in a different language",t:"mastery",u:9},
{w:"slow motion",c:"A2",s:"CEFR-J",p:"noun",ar:"حركة بطيئة",een:"They showed the goal in slow motion.",ear:"عرضوا الهدف بالحركة البطيئة.",def:"when a film shows action much slower than normal",t:"mastery",u:9},
{w:"animation studio",c:"A2",s:"CEFR-J",p:"noun",ar:"استوديو رسوم متحركة",een:"The animation studio made many famous cartoons.",ear:"صنع استوديو الرسوم المتحركة عدة أفلام كرتون شهيرة.",def:"a company that makes animated films",t:"mastery",u:9},
{w:"cast a role",c:"A2",s:"CEFR-J",p:"verb",ar:"يختار ممثلًا لدور",een:"The director cast her in the lead role.",ear:"اختارها المخرج للدور الرئيسي.",def:"to choose an actor for a part in a film",t:"mastery",u:9},
{w:"rehearsal",c:"B1",s:"CEFR-J",p:"noun",ar:"بروفة",een:"The rehearsal lasted for three hours yesterday.",ear:"استمرت البروفة لمدة ثلاث ساعات أمس.",def:"a practice session before a real performance",t:"mastery",u:9},
{w:"edit a film",c:"A2",s:"CEFR-J",p:"verb",ar:"يحرّر فيلمًا",een:"It takes months to edit a film properly.",ear:"يستغرق الأمر شهورًا لتحرير فيلم بشكل صحيح.",def:"to cut and arrange parts of a movie",t:"mastery",u:9},

// ========== UNIT 10: Water Crisis (88 words) ==========
// Core (33)
{w:"thirsty",c:"A1",s:"NGSL",p:"adjective",ar:"عطشان",een:"After running, I was very thirsty.",ear:"بعد الجري، كنت عطشانًا جدًا.",def:"feeling that you need to drink something",t:"core",u:10},
{w:"river",c:"A1",s:"NGSL",p:"noun",ar:"نهر",een:"The river flows through the middle of the city.",ear:"يجري النهر عبر وسط المدينة.",def:"a long natural stream of water",t:"core",u:10},
{w:"dirty",c:"A1",s:"NGSL",p:"adjective",ar:"قذر",een:"The water in the pond looks very dirty.",ear:"الماء في البركة يبدو قذرًا جدًا.",def:"not clean, full of unwanted things",t:"core",u:10},
{w:"pipe",c:"A2",s:"NGSL",p:"noun",ar:"أنبوب",een:"Water flows through pipes to our homes.",ear:"يتدفق الماء عبر الأنابيب إلى منازلنا.",def:"a tube that carries water or gas",t:"core",u:10},
{w:"well",c:"A2",s:"NGSL",p:"noun",ar:"بئر",een:"The village gets water from an old well.",ear:"تحصل القرية على الماء من بئر قديمة.",def:"a deep hole in the ground to get water",t:"core",u:10},
{w:"flood",c:"A2",s:"NGSL",p:"noun",ar:"فيضان",een:"The heavy rain caused a flood in the town.",ear:"تسبب المطر الغزير في فيضان في البلدة.",def:"a large amount of water covering dry land",t:"core",u:10},
{w:"tap",c:"A2",s:"CEFR-J",p:"noun",ar:"صنبور",een:"Turn off the tap when you brush your teeth.",ear:"أغلق الصنبور عندما تنظف أسنانك.",def:"a device that controls the flow of water",t:"core",u:10},
{w:"leak",c:"A2",s:"CEFR-J",p:"noun",ar:"تسريب",een:"There is a leak in the water pipe.",ear:"هناك تسريب في أنبوب المياه.",def:"a hole that lets water escape",t:"core",u:10},
{w:"dam",c:"A2",s:"CEFR-J",p:"noun",ar:"سد",een:"The dam holds water for the whole region.",ear:"يحتفظ السد بالمياه للمنطقة بأكملها.",def:"a wall built across a river to hold water",t:"core",u:10},
{w:"pump",c:"A2",s:"CEFR-J",p:"noun",ar:"مضخة",een:"The pump moves water from the well to the tank.",ear:"تنقل المضخة الماء من البئر إلى الخزان.",def:"a machine that moves liquid from one place to another",t:"core",u:10},
{w:"resource",c:"A2",s:"NGSL",p:"noun",ar:"مورد",een:"Water is our most important natural resource.",ear:"الماء هو أهم مورد طبيعي لدينا.",def:"something useful that a country or person has",t:"core",u:10},
{w:"tank",c:"A2",s:"NGSL",p:"noun",ar:"خزان",een:"The water tank on the roof is full.",ear:"خزان المياه على السطح ممتلئ.",def:"a large container for storing water or liquid",t:"core",u:10},
{w:"pour",c:"A2",s:"NGSL",p:"verb",ar:"يصبّ",een:"She poured water into the glass carefully.",ear:"صبّت الماء في الكأس بحرص.",def:"to make a liquid flow from a container",t:"core",u:10},
{w:"fill",c:"A2",s:"NGSL",p:"verb",ar:"يملأ",een:"Please fill the bottle with clean water.",ear:"من فضلك املأ الزجاجة بماء نظيف.",def:"to make something full",t:"core",u:10},
{w:"melt",c:"A2",s:"CEFR-J",p:"verb",ar:"يذوب",een:"The ice will melt if you leave it outside.",ear:"سيذوب الجليد إذا تركته في الخارج.",def:"to change from solid to liquid by warming",t:"core",u:10},
{w:"drop",c:"A2",s:"NGSL",p:"noun",ar:"قطرة",een:"Every drop of water is important.",ear:"كل قطرة ماء مهمة.",def:"a very small amount of liquid",t:"core",u:10},
{w:"bottle",c:"A1",s:"NGSL",p:"noun",ar:"زجاجة",een:"I always carry a water bottle with me.",ear:"أحمل دائمًا زجاجة ماء معي.",def:"a container for holding liquids",t:"core",u:10},
{w:"muddy",c:"A2",s:"CEFR-J",p:"adjective",ar:"موحل",een:"The river water was too muddy to use.",ear:"كانت مياه النهر موحلة جدًا لاستخدامها.",def:"full of mud and not clear",t:"core",u:10},
{w:"pure",c:"A2",s:"NGSL",p:"adjective",ar:"نقي",een:"Mountain springs often have very pure water.",ear:"غالبًا ما تحتوي ينابيع الجبال على مياه نقية جدًا.",def:"clean and not mixed with anything harmful",t:"core",u:10},
{w:"trickle",c:"A2",s:"CEFR-J",p:"verb",ar:"يسيل ببطء",een:"Water trickled slowly from the broken pipe.",ear:"سال الماء ببطء من الأنبوب المكسور.",def:"to flow slowly in a thin stream",t:"core",u:10},
{w:"moisture",c:"A2",s:"CEFR-J",p:"noun",ar:"رطوبة",een:"Plants need moisture in the soil to grow well.",ear:"تحتاج النباتات إلى رطوبة في التربة لتنمو جيدًا.",def:"small amounts of water in the air or on a surface",t:"core",u:10},
{w:"fetch",c:"A2",s:"CEFR-J",p:"verb",ar:"يحضر",een:"She walks two miles every day to fetch water.",ear:"تمشي ميلين كل يوم لإحضار الماء.",def:"to go and get something and bring it back",t:"core",u:10},
{w:"reserve",c:"A2",s:"NGSL",p:"verb",ar:"يحتفظ بـ",een:"Families reserve extra water during the dry season.",ear:"تحتفظ العائلات بمياه إضافية خلال موسم الجفاف.",def:"to keep something for later use",t:"core",u:10},
{w:"dried up",c:"A2",s:"CEFR-J",p:"adjective",ar:"جاف تمامًا",een:"The lake has completely dried up this summer.",ear:"جفّت البحيرة تمامًا هذا الصيف.",def:"having no water left",t:"core",u:10},
{w:"polluted",c:"A2",s:"CEFR-J",p:"adjective",ar:"ملوّث",een:"The polluted water is not safe to drink.",ear:"الماء الملوّث ليس آمنًا للشرب.",def:"dirty and harmful because of chemicals or waste",t:"core",u:10},
{w:"spill",c:"A2",s:"CEFR-J",p:"verb",ar:"يسكب",een:"Be careful not to spill water on the floor.",ear:"كن حذرًا لا تسكب الماء على الأرض.",def:"to accidentally let liquid fall out of a container",t:"core",u:10},
{w:"pond",c:"A2",s:"CEFR-J",p:"noun",ar:"بركة",een:"Ducks swim in the small pond near the park.",ear:"يسبح البط في البركة الصغيرة بالقرب من الحديقة.",def:"a small area of still water",t:"core",u:10},
{w:"swamp",c:"B1",s:"CEFR-J",p:"noun",ar:"مستنقع",een:"The swamp is full of water and tall grass.",ear:"المستنقع مليء بالمياه والعشب الطويل.",def:"an area of soft wet land with lots of water",t:"core",u:10},
{w:"drown",c:"A2",s:"CEFR-J",p:"verb",ar:"يغرق",een:"Never swim alone because you could drown.",ear:"لا تسبح وحدك أبدًا لأنك قد تغرق.",def:"to die because you cannot breathe under water",t:"core",u:10},
{w:"waterfall",c:"A2",s:"CEFR-J",p:"noun",ar:"شلال",een:"The waterfall was so beautiful we stayed for hours.",ear:"كان الشلال جميلًا جدًا فبقينا لساعات.",def:"water that falls from a high place to a lower one",t:"core",u:10},
{w:"splash",c:"A2",s:"CEFR-J",p:"verb",ar:"يرشّ",een:"The children like to splash water at each other.",ear:"يحب الأطفال رشّ الماء على بعضهم البعض.",def:"to make water fly through the air",t:"core",u:10},
{w:"soak",c:"B1",s:"CEFR-J",p:"verb",ar:"ينقع",een:"Soak the beans in water overnight before cooking.",ear:"انقع الفاصوليا في الماء ليلة كاملة قبل الطبخ.",def:"to make something very wet by putting it in water",t:"core",u:10},
{w:"steam",c:"A2",s:"CEFR-J",p:"noun",ar:"بخار",een:"Steam rises from the hot water in the pot.",ear:"يتصاعد البخار من الماء الساخن في القِدر.",def:"the gas that water becomes when it boils",t:"core",u:10},

// Extended (29)
{w:"underground",c:"A2",s:"NGSL",p:"adjective",ar:"تحت الأرض",een:"Underground water is an important source for farming.",ear:"المياه الجوفية مصدر مهم للزراعة.",def:"below the surface of the earth",t:"extended",u:10},
{w:"reservoir",c:"B1",s:"CEFR-J",p:"noun",ar:"خزان مائي",een:"The reservoir provides water for the whole city.",ear:"يزوّد الخزان المائي المدينة بالمياه بالكامل.",def:"a large lake used to store water",t:"extended",u:10},
{w:"treatment",c:"A2",s:"NGSL",p:"noun",ar:"معالجة",een:"Water treatment makes dirty water safe to drink.",ear:"تجعل معالجة المياه المياه القذرة صالحة للشرب.",def:"the process of cleaning or fixing something",t:"extended",u:10},
{w:"distribute",c:"A2",s:"NGSL",p:"verb",ar:"يوزّع",een:"The government distributes water to dry areas.",ear:"توزّع الحكومة المياه على المناطق الجافة.",def:"to give something to many people or places",t:"extended",u:10},
{w:"container",c:"A2",s:"NGSL",p:"noun",ar:"وعاء",een:"She filled the container with clean water.",ear:"ملأت الوعاء بماء نظيف.",def:"a box or object used to hold things",t:"extended",u:10},
{w:"purify",c:"B1",s:"CEFR-J",p:"verb",ar:"ينقّي",een:"This machine can purify ocean water for drinking.",ear:"يمكن لهذه الآلة تنقية مياه المحيط للشرب.",def:"to remove dirty or harmful things from something",t:"extended",u:10},
{w:"sanitation",c:"B1",s:"CEFR-J",p:"noun",ar:"صرف صحي",een:"Good sanitation helps prevent many diseases.",ear:"الصرف الصحي الجيد يساعد في منع كثير من الأمراض.",def:"systems for keeping places clean and healthy",t:"extended",u:10},
{w:"rainwater",c:"A2",s:"CEFR-J",p:"noun",ar:"مياه الأمطار",een:"They collect rainwater in big tanks on rooftops.",ear:"يجمعون مياه الأمطار في خزانات كبيرة على الأسطح.",def:"water that falls from the sky as rain",t:"extended",u:10},
{w:"bucket",c:"A2",s:"CEFR-J",p:"noun",ar:"دلو",een:"She carried a bucket of water from the well.",ear:"حملت دلوًا من الماء من البئر.",def:"a round open container with a handle",t:"extended",u:10},
{w:"crisis",c:"A2",s:"NGSL",p:"noun",ar:"أزمة",een:"The water crisis affects millions of people worldwide.",ear:"تؤثر أزمة المياه على ملايين الأشخاص حول العالم.",def:"a very difficult or dangerous situation",t:"extended",u:10},
{w:"sewage",c:"B1",s:"CEFR-J",p:"noun",ar:"مياه صرف",een:"Sewage must be cleaned before going into rivers.",ear:"يجب تنظيف مياه الصرف قبل وصولها إلى الأنهار.",def:"dirty water and waste from homes and factories",t:"extended",u:10},
{w:"donate",c:"A2",s:"NGSL",p:"verb",ar:"يتبرّع",een:"Many people donate money to build clean water wells.",ear:"يتبرع كثير من الناس بالمال لبناء آبار مياه نظيفة.",def:"to give something, especially money, to help others",t:"extended",u:10},
{w:"spray",c:"A2",s:"NGSL",p:"verb",ar:"يرشّ",een:"The farmer sprays water on the vegetables every morning.",ear:"يرشّ المزارع الماء على الخضروات كل صباح.",def:"to send liquid out in small drops",t:"extended",u:10},
{w:"hose",c:"A2",s:"CEFR-J",p:"noun",ar:"خرطوم",een:"He used a hose to water the garden.",ear:"استخدم خرطومًا لسقاية الحديقة.",def:"a long flexible tube that carries water",t:"extended",u:10},
{w:"humid",c:"B1",s:"CEFR-J",p:"adjective",ar:"رطب",een:"The weather is very hot and humid in summer.",ear:"الطقس حار ورطب جدًا في الصيف.",def:"having a lot of water in the air",t:"extended",u:10},
{w:"evaporate",c:"B1",s:"CEFR-J",p:"verb",ar:"يتبخّر",een:"Water evaporates faster in hot weather.",ear:"يتبخر الماء بشكل أسرع في الطقس الحار.",def:"to change from liquid to gas",t:"extended",u:10},
{w:"usage",c:"A2",s:"NGSL",p:"noun",ar:"استخدام",een:"Water usage in the city has increased greatly.",ear:"ازداد استخدام المياه في المدينة بشكل كبير.",def:"the amount of something that is used",t:"extended",u:10},
{w:"contaminate",c:"B1",s:"CEFR-J",p:"verb",ar:"يلوّث",een:"Chemicals can contaminate drinking water easily.",ear:"يمكن للمواد الكيميائية أن تلوّث مياه الشرب بسهولة.",def:"to make something dirty or unsafe",t:"extended",u:10},
{w:"famine",c:"B1",s:"CEFR-J",p:"noun",ar:"مجاعة",een:"Water shortage can lead to famine in dry areas.",ear:"يمكن أن يؤدي نقص المياه إلى مجاعة في المناطق الجافة.",def:"a time when many people have no food",t:"extended",u:10},
{w:"precious",c:"A2",s:"NGSL",p:"adjective",ar:"ثمين",een:"Water is a precious resource for all living things.",ear:"الماء مورد ثمين لجميع الكائنات الحية.",def:"very valuable and important",t:"extended",u:10},
{w:"maintain",c:"A2",s:"NGSL",p:"verb",ar:"يُصلح",een:"We must maintain the pipes to prevent leaks.",ear:"يجب أن نُصلح الأنابيب لمنع التسريبات.",def:"to keep something in good condition",t:"extended",u:10},
{w:"drip",c:"A2",s:"CEFR-J",p:"verb",ar:"يقطر",een:"The tap is dripping and wasting water all day.",ear:"الصنبور يقطر ويُهدر الماء طوال اليوم.",def:"to fall in small drops",t:"extended",u:10},
{w:"stagnant",c:"B1",s:"CEFR-J",p:"adjective",ar:"راكد",een:"Stagnant water can cause disease in the village.",ear:"يمكن للمياه الراكدة أن تسبب المرض في القرية.",def:"water that does not move and becomes dirty",t:"extended",u:10},
{w:"charity",c:"A2",s:"NGSL",p:"noun",ar:"جمعية خيرية",een:"The charity builds wells in poor communities.",ear:"تبني الجمعية الخيرية آبارًا في المجتمعات الفقيرة.",def:"an organization that helps people in need",t:"extended",u:10},
{w:"essential",c:"A2",s:"NGSL",p:"adjective",ar:"ضروري",een:"Water is essential for all forms of life.",ear:"الماء ضروري لجميع أشكال الحياة.",def:"very important and necessary",t:"extended",u:10},
{w:"aware",c:"A2",s:"NGSL",p:"adjective",ar:"واعٍ",een:"People should be more aware of water problems.",ear:"يجب أن يكون الناس أكثر وعيًا بمشاكل المياه.",def:"knowing about something",t:"extended",u:10},
{w:"harvest water",c:"A2",s:"NGSL",p:"verb",ar:"يجمع مياه",een:"Many communities harvest water from their rooftops.",ear:"تجمع مجتمعات كثيرة المياه من أسطح منازلها.",def:"to collect rainwater for future use",t:"extended",u:10},
{w:"severe",c:"A2",s:"NGSL",p:"adjective",ar:"شديد",een:"The severe drought lasted for three long years.",ear:"استمر الجفاف الشديد لثلاث سنوات طويلة.",def:"very bad or serious",t:"extended",u:10},
{w:"rural",c:"A2",s:"NGSL",p:"adjective",ar:"ريفي",een:"Many rural areas still lack clean drinking water.",ear:"لا تزال مناطق ريفية كثيرة تفتقر إلى مياه شرب نظيفة.",def:"relating to the countryside, not the city",t:"extended",u:10},

// Mastery (26)
{w:"desalination",c:"B1",s:"CEFR-J",p:"noun",ar:"تحلية المياه",een:"Desalination turns sea water into drinking water.",ear:"تحلية المياه تحوّل مياه البحر إلى مياه شرب.",def:"the process of removing salt from ocean water",t:"mastery",u:10},
{w:"groundwater",c:"B1",s:"CEFR-J",p:"noun",ar:"مياه جوفية",een:"Groundwater is found deep under the earth's surface.",ear:"توجد المياه الجوفية عميقًا تحت سطح الأرض.",def:"water that is under the ground in soil or rock",t:"mastery",u:10},
{w:"water cycle",c:"A2",s:"CEFR-J",p:"noun",ar:"دورة المياه",een:"Children learn about the water cycle in science class.",ear:"يتعلم الأطفال عن دورة المياه في حصة العلوم.",def:"the natural process of water moving around Earth",t:"mastery",u:10},
{w:"arid",c:"B1",s:"CEFR-J",p:"adjective",ar:"قاحل",een:"It is hard to grow food in arid regions.",ear:"من الصعب زراعة الطعام في المناطق القاحلة.",def:"very dry with very little rain",t:"mastery",u:10},
{w:"runoff",c:"B1",s:"CEFR-J",p:"noun",ar:"مياه جارية سطحية",een:"Rainwater runoff can carry pollution into the river.",ear:"يمكن لمياه الأمطار الجارية أن تنقل التلوث إلى النهر.",def:"water that flows over land instead of being absorbed",t:"mastery",u:10},
{w:"condensation",c:"B1",s:"CEFR-J",p:"noun",ar:"تكاثف",een:"You can see condensation on cold glass windows.",ear:"يمكنك رؤية التكاثف على النوافذ الزجاجية الباردة.",def:"water drops that form when gas becomes liquid",t:"mastery",u:10},
{w:"watershed",c:"B1",s:"CEFR-J",p:"noun",ar:"مستجمع مائي",een:"The forest is part of an important watershed.",ear:"الغابة جزء من مستجمع مائي مهم.",def:"an area of land where water collects and flows",t:"mastery",u:10},
{w:"ration",c:"B1",s:"CEFR-J",p:"verb",ar:"يقنّن",een:"During the drought, the government rationed water.",ear:"أثناء الجفاف، قنّنت الحكومة المياه.",def:"to limit the amount each person can use",t:"mastery",u:10},
{w:"infrastructure",c:"B1",s:"CEFR-J",p:"noun",ar:"بنية تحتية",een:"The country needs better water infrastructure.",ear:"تحتاج البلاد إلى بنية تحتية أفضل للمياه.",def:"the basic systems a country needs to work well",t:"mastery",u:10},
{w:"wastewater",c:"B1",s:"CEFR-J",p:"noun",ar:"مياه عادمة",een:"The city cleans wastewater before sending it to sea.",ear:"تُنظّف المدينة المياه العادمة قبل إرسالها إلى البحر.",def:"water that has been used and is dirty",t:"mastery",u:10},
{w:"aquifer",c:"B1",s:"CEFR-J",p:"noun",ar:"طبقة مياه جوفية",een:"The aquifer under the desert holds a lot of water.",ear:"تحتوي طبقة المياه الجوفية تحت الصحراء على كثير من المياه.",def:"an underground layer of rock that holds water",t:"mastery",u:10},
{w:"salinity",c:"B1",s:"CEFR-J",p:"noun",ar:"ملوحة",een:"High salinity makes the water unfit for drinking.",ear:"الملوحة العالية تجعل الماء غير صالح للشرب.",def:"the amount of salt in water",t:"mastery",u:10},
{w:"drought-resistant",c:"B1",s:"CEFR-J",p:"adjective",ar:"مقاوم للجفاف",een:"Farmers grow drought-resistant crops to save water.",ear:"يزرع المزارعون محاصيل مقاومة للجفاف لتوفير المياه.",def:"able to survive with very little water",t:"mastery",u:10},
{w:"contamination",c:"B1",s:"CEFR-J",p:"noun",ar:"تلوّث",een:"Water contamination is a serious health problem.",ear:"تلوّث المياه مشكلة صحية خطيرة.",def:"when something harmful gets into water or food",t:"mastery",u:10},
{w:"well water",c:"A2",s:"CEFR-J",p:"noun",ar:"مياه الآبار",een:"Many villages depend on well water for daily life.",ear:"تعتمد كثير من القرى على مياه الآبار في حياتها اليومية.",def:"water taken from a hole dug in the ground",t:"mastery",u:10},
{w:"water table",c:"B1",s:"CEFR-J",p:"noun",ar:"منسوب المياه",een:"The water table has dropped because of the drought.",ear:"انخفض منسوب المياه بسبب الجفاف.",def:"the level below which the ground is full of water",t:"mastery",u:10},
{w:"leakage",c:"B1",s:"CEFR-J",p:"noun",ar:"تسرّب",een:"Pipe leakage wastes millions of liters every year.",ear:"يُهدر تسرّب الأنابيب ملايين اللترات كل عام.",def:"the slow escape of liquid through a hole",t:"mastery",u:10},
{w:"dehydration",c:"B1",s:"CEFR-J",p:"noun",ar:"جفاف الجسم",een:"Drink water often to avoid dehydration in summer.",ear:"اشرب الماء كثيرًا لتجنب جفاف الجسم في الصيف.",def:"when your body does not have enough water",t:"mastery",u:10},
{w:"water scarcity",c:"B1",s:"CEFR-J",p:"noun",ar:"شُح المياه",een:"Water scarcity is getting worse in many countries.",ear:"يزداد شُح المياه سوءًا في كثير من البلدان.",def:"when there is not enough water for people's needs",t:"mastery",u:10},
{w:"drinkable",c:"A2",s:"CEFR-J",p:"adjective",ar:"صالح للشرب",een:"Only one percent of Earth's water is drinkable.",ear:"واحد بالمئة فقط من مياه الأرض صالح للشرب.",def:"clean and safe enough to drink",t:"mastery",u:10},
{w:"water-saving",c:"A2",s:"CEFR-J",p:"adjective",ar:"موفّر للمياه",een:"We installed water-saving taps in the school.",ear:"ركّبنا صنابير موفّرة للمياه في المدرسة.",def:"designed to use less water",t:"mastery",u:10},
{w:"reclaim",c:"B1",s:"CEFR-J",p:"verb",ar:"يستصلح",een:"Engineers reclaim dirty water and make it usable again.",ear:"يستصلح المهندسون المياه القذرة ويجعلونها صالحة مجددًا.",def:"to make something useful again after it was wasted",t:"mastery",u:10},
{w:"divert",c:"B1",s:"CEFR-J",p:"verb",ar:"يحوّل مجرى",een:"They diverted the river to bring water to farms.",ear:"حوّلوا مجرى النهر لجلب المياه إلى المزارع.",def:"to change the direction something is moving",t:"mastery",u:10},
{w:"cistern",c:"B1",s:"CEFR-J",p:"noun",ar:"صهريج",een:"The old cistern under the house stores rainwater.",ear:"يخزّن الصهريج القديم تحت المنزل مياه الأمطار.",def:"a large tank for storing water",t:"mastery",u:10},
{w:"precipitation",c:"B1",s:"CEFR-J",p:"noun",ar:"هطول",een:"Precipitation is low in desert areas all year.",ear:"الهطول منخفض في المناطق الصحراوية طوال العام.",def:"rain, snow, or other water falling from the sky",t:"mastery",u:10},
{w:"tributary",c:"B1",s:"CEFR-J",p:"noun",ar:"رافد",een:"This small tributary flows into the main river.",ear:"يصبّ هذا الرافد الصغير في النهر الرئيسي.",def:"a small river that flows into a larger one",t:"mastery",u:10},

// ========== UNIT 11: Street Art (88 words) ==========
// Core (33)
{w:"wall",c:"A1",s:"NGSL",p:"noun",ar:"جدار",een:"The artist painted a picture on the wall.",ear:"رسم الفنان صورة على الجدار.",def:"a side of a building or room",t:"core",u:11},
{w:"mural",c:"A2",s:"CEFR-J",p:"noun",ar:"جدارية",een:"The mural on the school wall is very large.",ear:"الجدارية على جدار المدرسة كبيرة جدًا.",def:"a large painting done on a wall",t:"core",u:11},
{w:"graffiti",c:"A2",s:"CEFR-J",p:"noun",ar:"كتابات جدارية",een:"Some people think graffiti is art, others disagree.",ear:"يعتقد البعض أن الكتابات الجدارية فن، ويختلف آخرون.",def:"words or pictures drawn on walls in public places",t:"core",u:11},
{w:"spray can",c:"A2",s:"CEFR-J",p:"noun",ar:"علبة بخاخ",een:"He shook the spray can before painting the wall.",ear:"هزّ علبة البخاخ قبل طلاء الجدار.",def:"a metal container that sprays paint",t:"core",u:11},
{w:"permission",c:"A2",s:"NGSL",p:"noun",ar:"إذن",een:"The artist got permission to paint the building.",ear:"حصل الفنان على إذن لطلاء المبنى.",def:"when someone says you are allowed to do something",t:"core",u:11},
{w:"legal",c:"A2",s:"NGSL",p:"adjective",ar:"قانوني",een:"Is street art legal in this city?",ear:"هل فن الشارع قانوني في هذه المدينة؟",def:"allowed by the law",t:"core",u:11},
{w:"illegal",c:"A2",s:"NGSL",p:"adjective",ar:"غير قانوني",een:"Painting on buildings without permission is illegal.",ear:"الرسم على المباني دون إذن غير قانوني.",def:"not allowed by the law",t:"core",u:11},
{w:"bold",c:"A2",s:"NGSL",p:"adjective",ar:"جريء",een:"The artist used bold colors to attract attention.",ear:"استخدم الفنان ألوانًا جريئة لجذب الانتباه.",def:"strong and clear, easy to notice",t:"core",u:11},
{w:"style",c:"A2",s:"NGSL",p:"noun",ar:"أسلوب",een:"Each artist has their own unique style.",ear:"لكل فنان أسلوبه الفريد الخاص.",def:"a particular way of doing or making something",t:"core",u:11},
{w:"ugly",c:"A2",s:"NGSL",p:"adjective",ar:"قبيح",een:"Some people say graffiti makes buildings look ugly.",ear:"يقول بعض الناس إن الكتابات الجدارية تجعل المباني تبدو قبيحة.",def:"not pleasant to look at",t:"core",u:11},
{w:"shape",c:"A2",s:"NGSL",p:"noun",ar:"شكل",een:"The mural is full of interesting shapes and lines.",ear:"الجدارية مليئة بأشكال وخطوط مثيرة.",def:"the form or outline of something",t:"core",u:11},
{w:"symbol",c:"A2",s:"NGSL",p:"noun",ar:"رمز",een:"The dove is a symbol of peace in the mural.",ear:"الحمامة رمز للسلام في الجدارية.",def:"a picture or sign that means something",t:"core",u:11},
{w:"neighborhood",c:"A2",s:"NGSL",p:"noun",ar:"حي",een:"Street art can make a neighborhood look better.",ear:"يمكن لفن الشارع أن يجعل الحي يبدو أفضل.",def:"an area in a town where people live",t:"core",u:11},
{w:"opinion",c:"A2",s:"NGSL",p:"noun",ar:"رأي",een:"What is your opinion about graffiti in cities?",ear:"ما رأيك في الكتابات الجدارية في المدن؟",def:"what you think about something",t:"core",u:11},
{w:"community",c:"A2",s:"NGSL",p:"noun",ar:"مجتمع",een:"The mural brought the community together.",ear:"جمعت الجدارية المجتمع معًا.",def:"a group of people living in the same area",t:"core",u:11},
{w:"urban",c:"A2",s:"NGSL",p:"adjective",ar:"حضري",een:"Urban art has become very popular around the world.",ear:"أصبح الفن الحضري شائعًا جدًا حول العالم.",def:"relating to a city or town",t:"core",u:11},
{w:"cover",c:"A2",s:"NGSL",p:"verb",ar:"يغطّي",een:"The painting covers the entire side of the building.",ear:"تغطّي اللوحة الجانب الكامل من المبنى.",def:"to put something over or on top of something",t:"core",u:11},
{w:"line",c:"A1",s:"NGSL",p:"noun",ar:"خط",een:"She drew a long line across the wall.",ear:"رسمت خطًا طويلًا عبر الجدار.",def:"a long thin mark on a surface",t:"core",u:11},
{w:"detail",c:"A2",s:"NGSL",p:"noun",ar:"تفصيل",een:"The mural has amazing detail in every corner.",ear:"الجدارية فيها تفاصيل مذهلة في كل زاوية.",def:"a small part of something bigger",t:"core",u:11},
{w:"attract",c:"A2",s:"NGSL",p:"verb",ar:"يجذب",een:"Colorful murals attract many tourists to the area.",ear:"تجذب الجداريات الملوّنة كثيرًا من السيّاح إلى المنطقة.",def:"to make someone interested or want to come closer",t:"core",u:11},
{w:"notice",c:"A2",s:"NGSL",p:"verb",ar:"يلاحظ",een:"Did you notice the new mural on that building?",ear:"هل لاحظت الجدارية الجديدة على ذلك المبنى؟",def:"to see something and pay attention to it",t:"core",u:11},
{w:"crowd",c:"A2",s:"NGSL",p:"noun",ar:"حشد",een:"A crowd gathered to watch the artist work.",ear:"تجمّع حشد لمشاهدة الفنان يعمل.",def:"a large group of people in one place",t:"core",u:11},
{w:"giant",c:"A2",s:"NGSL",p:"adjective",ar:"عملاق",een:"The huge mural covers the whole side of the building.",ear:"تغطّي الجدارية الضخمة كل جانب المبنى.",def:"extremely large",t:"core",u:11},
{w:"allow",c:"A2",s:"NGSL",p:"verb",ar:"يسمح",een:"The city allows artists to paint on this wall.",ear:"تسمح المدينة للفنانين بالرسم على هذا الجدار.",def:"to let someone do something",t:"core",u:11},
{w:"erase",c:"A2",s:"NGSL",p:"verb",ar:"يمحو",een:"The city decided to erase the old graffiti.",ear:"قررت المدينة محو الكتابات الجدارية القديمة.",def:"to completely remove marks from a surface",t:"core",u:11},
{w:"sign",c:"A1",s:"NGSL",p:"noun",ar:"لافتة",een:"There is a sign saying this wall is for artists.",ear:"هناك لافتة تقول إن هذا الجدار للفنانين.",def:"a board with words or pictures giving information",t:"core",u:11},
{w:"artwork",c:"A2",s:"CEFR-J",p:"noun",ar:"عمل فني",een:"The artwork on the wall shows a beautiful bird.",ear:"يُظهر العمل الفني على الجدار طائرًا جميلًا.",def:"a piece of art such as a painting or drawing",t:"core",u:11},
{w:"ladder",c:"A2",s:"CEFR-J",p:"noun",ar:"سلّم",een:"The artist used a ladder to reach the top.",ear:"استخدم الفنان سلّمًا للوصول إلى الأعلى.",def:"a tool with steps for climbing up and down",t:"core",u:11},
{w:"mark",c:"A2",s:"NGSL",p:"noun",ar:"علامة",een:"Someone left a mark on the clean white wall.",ear:"ترك شخصٌ ما علامة على الجدار الأبيض النظيف.",def:"a spot or sign left on a surface",t:"core",u:11},
{w:"striking",c:"A2",s:"NGSL",p:"adjective",ar:"لافت للنظر",een:"The striking murals attracted tourists to the area.",ear:"جذبت الجداريات اللافتة للنظر السيّاح إلى المنطقة.",def:"very noticeable and impressive",t:"core",u:11},
{w:"blank",c:"A2",s:"NGSL",p:"adjective",ar:"فارغ",een:"The blank wall was waiting for an artist.",ear:"كان الجدار الفارغ ينتظر فنانًا.",def:"empty, with nothing on it",t:"core",u:11},
{w:"freedom",c:"A2",s:"NGSL",p:"noun",ar:"حرية",een:"Street art is about freedom and self-expression.",ear:"فن الشارع يتعلق بالحرية والتعبير عن الذات.",def:"the right to do or say what you want",t:"core",u:11},
{w:"pattern",c:"A2",s:"NGSL",p:"noun",ar:"نمط",een:"The artist painted a beautiful pattern on the fence.",ear:"رسم الفنان نمطًا جميلًا على السياج.",def:"a repeated design of shapes, colors, or lines",t:"core",u:11},

// Extended (29)
{w:"stencil",c:"B1",s:"CEFR-J",p:"noun",ar:"قالب تلوين",een:"The artist used a stencil to make the design.",ear:"استخدم الفنان قالب تلوين لعمل التصميم.",def:"a sheet with cut-out shapes used for painting",t:"extended",u:11},
{w:"paste",c:"A2",s:"NGSL",p:"verb",ar:"يلصق",een:"She pastes paper art on walls around the city.",ear:"تلصق فنًا ورقيًا على جدران المدينة.",def:"to stick something to a surface using glue",t:"extended",u:11},
{w:"canvas",c:"A2",s:"CEFR-J",p:"noun",ar:"لوحة قماشية",een:"For street artists, the wall is their canvas.",ear:"بالنسبة لفناني الشارع، الجدار هو لوحتهم القماشية.",def:"a strong cloth used for painting on",t:"extended",u:11},
{w:"spray paint",c:"A2",s:"CEFR-J",p:"noun",ar:"طلاء بخاخ",een:"Spray paint dries very quickly on walls.",ear:"يجف طلاء البخاخ بسرعة كبيرة على الجدران.",def:"paint in a can that comes out in small drops",t:"extended",u:11},
{w:"protest",c:"A2",s:"NGSL",p:"noun",ar:"احتجاج",een:"The mural was painted as a form of protest.",ear:"رُسمت الجدارية كشكل من أشكال الاحتجاج.",def:"an action showing that you disagree with something",t:"extended",u:11},
{w:"social",c:"A2",s:"NGSL",p:"adjective",ar:"اجتماعي",een:"Many murals deal with social issues like equality.",ear:"تتناول كثير من الجداريات قضايا اجتماعية مثل المساواة.",def:"relating to people in society",t:"extended",u:11},
{w:"political",c:"A2",s:"NGSL",p:"adjective",ar:"سياسي",een:"Some street art carries a political message.",ear:"يحمل بعض فنون الشارع رسالة سياسية.",def:"relating to government and how a country is run",t:"extended",u:11},
{w:"chalk",c:"A2",s:"CEFR-J",p:"noun",ar:"طباشير",een:"Artists draw with chalk on the sidewalk.",ear:"يرسم الفنانون بالطباشير على الرصيف.",def:"a soft white or colored stick used for drawing",t:"extended",u:11},
{w:"sidewalk",c:"A2",s:"NGSL",p:"noun",ar:"رصيف",een:"The sidewalk art disappears when it rains.",ear:"يختفي فن الرصيف عندما تُمطر.",def:"a path next to a road where people walk",t:"extended",u:11},
{w:"vandalism",c:"B1",s:"CEFR-J",p:"noun",ar:"تخريب",een:"Some people call graffiti vandalism, not art.",ear:"يسمّي بعض الناس الكتابات الجدارية تخريبًا لا فنًا.",def:"damage done to someone's property on purpose",t:"extended",u:11},
{w:"debate",c:"A2",s:"NGSL",p:"noun",ar:"نقاش",een:"There is a big debate about graffiti in cities.",ear:"هناك نقاش كبير حول الكتابات الجدارية في المدن.",def:"a discussion where people share different opinions",t:"extended",u:11},
{w:"label",c:"A2",s:"NGSL",p:"noun",ar:"تسمية",een:"People put different labels on street art.",ear:"يضع الناس تسميات مختلفة على فن الشارع.",def:"a word or phrase used to describe something",t:"extended",u:11},
{w:"exhibit",c:"A2",s:"NGSL",p:"verb",ar:"يعرض",een:"The museum will exhibit street art next month.",ear:"سيعرض المتحف فنون الشارع الشهر القادم.",def:"to show something in public for people to see",t:"extended",u:11},
{w:"layer",c:"A2",s:"NGSL",p:"noun",ar:"طبقة",een:"The artist adds layer after layer of color.",ear:"يضيف الفنان طبقة بعد طبقة من الألوان.",def:"one thickness of something on top of another",t:"extended",u:11},
{w:"praise",c:"A2",s:"NGSL",p:"verb",ar:"يُثني على",een:"Critics praise her work for its powerful message.",ear:"يثني النقاد على عملها لرسالته القوية.",def:"to say good things about someone or something",t:"extended",u:11},
{w:"rough",c:"A2",s:"NGSL",p:"adjective",ar:"خشن",een:"He painted on the rough surface of the old wall.",ear:"رسم على السطح الخشن للجدار القديم.",def:"not smooth, having an uneven surface",t:"extended",u:11},
{w:"warehouse",c:"B1",s:"CEFR-J",p:"noun",ar:"مستودع",een:"Old warehouses are popular places for street art.",ear:"المستودعات القديمة أماكن شائعة لفن الشارع.",def:"a large building used for storing goods",t:"extended",u:11},
{w:"recognize",c:"A2",s:"NGSL",p:"verb",ar:"يتعرّف على",een:"I can recognize her art style from far away.",ear:"أستطيع التعرّف على أسلوبها الفني من بعيد.",def:"to know something because you have seen it before",t:"extended",u:11},
{w:"beautify",c:"A2",s:"CEFR-J",p:"verb",ar:"يجمّل",een:"Murals can beautify a boring wall in just days.",ear:"يمكن للجداريات تجميل جدار ممل في أيام فقط.",def:"to make something more beautiful",t:"extended",u:11},
{w:"motivate",c:"A2",s:"NGSL",p:"verb",ar:"يحفّز",een:"Street art can motivate young people to be creative.",ear:"يمكن لفن الشارع أن يحفّز الشباب على الإبداع.",def:"to give someone a reason to do something",t:"extended",u:11},
{w:"self-expression",c:"A2",s:"NGSL",p:"noun",ar:"تعبير عن الذات",een:"Street art is a powerful form of self-expression.",ear:"فن الشارع شكل قوي من أشكال التعبير عن الذات.",def:"showing your feelings and ideas through art or words",t:"extended",u:11},
{w:"short-lived",c:"A2",s:"NGSL",p:"adjective",ar:"مؤقت",een:"Street art is often short-lived and may disappear.",ear:"غالبًا ما يكون فن الشارع مؤقتًا وقد يختفي قريبًا.",def:"not lasting for a long time",t:"extended",u:11},
{w:"symbolize",c:"A2",s:"CEFR-J",p:"verb",ar:"يرمز إلى",een:"The colors in the mural symbolize hope and peace.",ear:"ترمز الألوان في الجدارية إلى الأمل والسلام.",def:"to be a sign or symbol of something",t:"extended",u:11},
{w:"destroy",c:"A2",s:"NGSL",p:"verb",ar:"يدمّر",een:"They destroyed the mural when they painted the wall white.",ear:"دمّروا الجدارية عندما طلوا الجدار بالأبيض.",def:"to damage something so badly it no longer exists",t:"extended",u:11},
{w:"permission wall",c:"A2",s:"CEFR-J",p:"noun",ar:"جدار مُصرّح",een:"The city built a permission wall for street artists.",ear:"بنت المدينة جدارًا مُصرّحًا لفناني الشارع.",def:"a wall where artists are allowed to paint freely",t:"extended",u:11},
{w:"secretive",c:"B1",s:"CEFR-J",p:"adjective",ar:"سرّي",een:"The secretive artist never shows his face in public.",ear:"لا يُظهر الفنان السرّي وجهه أبدًا في الأماكن العامة.",def:"hiding things and not wanting others to know",t:"extended",u:11},
{w:"react",c:"A2",s:"NGSL",p:"verb",ar:"يتفاعل",een:"People react differently to street art in their area.",ear:"يتفاعل الناس بشكل مختلف مع فن الشارع في منطقتهم.",def:"to respond to something that happens",t:"extended",u:11},
{w:"fence",c:"A2",s:"NGSL",p:"noun",ar:"سياج",een:"Someone painted a mural on the wooden fence.",ear:"رسم شخص ما جدارية على السياج الخشبي.",def:"a barrier around a garden or field",t:"extended",u:11},
{w:"concrete",c:"A2",s:"NGSL",p:"noun",ar:"خرسانة",een:"The artist sprayed colors on the grey concrete wall.",ear:"رشّ الفنان ألوانًا على الجدار الخرساني الرمادي.",def:"a hard building material made from cement and sand",t:"extended",u:11},

// Mastery (26)
{w:"wheat paste",c:"B1",s:"CEFR-J",p:"noun",ar:"لصق ورقي",een:"Wheat paste is used to stick posters on walls.",ear:"يُستخدم اللصق الورقي لتثبيت الملصقات على الجدران.",def:"a glue made from flour and water for sticking paper",t:"mastery",u:11},
{w:"commissioned",c:"B1",s:"CEFR-J",p:"adjective",ar:"بتكليف رسمي",een:"The commissioned mural was paid for by the city.",ear:"الجدارية المُكلَّف بها دفعت المدينة تكاليفها.",def:"officially asked and paid to create something",t:"mastery",u:11},
{w:"installation",c:"B1",s:"CEFR-J",p:"noun",ar:"عمل فني تركيبي",een:"The art installation used lights and recycled metal.",ear:"استخدم العمل الفني التركيبي أضواءً ومعادن مُعاد تدويرها.",def:"a large piece of art made for a specific place",t:"mastery",u:11},
{w:"provocative",c:"B1",s:"CEFR-J",p:"adjective",ar:"استفزازي",een:"His art is often provocative and starts discussions.",ear:"فنه غالبًا استفزازي ويثير نقاشات.",def:"causing strong feelings or arguments on purpose",t:"mastery",u:11},
{w:"revival",c:"B1",s:"CEFR-J",p:"noun",ar:"إحياء",een:"Street art has led to a revival of this neighborhood.",ear:"أدّى فن الشارع إلى إحياء هذا الحي.",def:"the return of something to activity and popularity",t:"mastery",u:11},
{w:"aerosol",c:"B1",s:"CEFR-J",p:"noun",ar:"رذاذ",een:"Aerosol paint comes out as a fine mist.",ear:"يخرج طلاء الرذاذ على شكل ضباب ناعم.",def:"a container that sprays liquid as a fine mist",t:"mastery",u:11},
{w:"mural festival",c:"A2",s:"CEFR-J",p:"noun",ar:"مهرجان جداريات",een:"The mural festival brings artists from many countries.",ear:"يجلب مهرجان الجداريات فنانين من دول كثيرة.",def:"an event where artists create murals in a city",t:"mastery",u:11},
{w:"buff",c:"B1",s:"CEFR-J",p:"verb",ar:"يزيل الطلاء",een:"The city buffed the graffiti off the bridge overnight.",ear:"أزالت المدينة الكتابات الجدارية عن الجسر بين ليلة وضحاها.",def:"to remove paint or graffiti from a surface",t:"mastery",u:11},
{w:"tag name",c:"A2",s:"CEFR-J",p:"noun",ar:"اسم فني",een:"Most graffiti artists use a tag name, not real names.",ear:"يستخدم معظم فناني الكتابات الجدارية اسمًا فنيًا لا أسماءهم الحقيقية.",def:"a fake name an artist uses to stay unknown",t:"mastery",u:11},
{w:"divisive",c:"B1",s:"NGSL",p:"adjective",ar:"مثير للانقسام",een:"Graffiti remains a divisive topic in many cities.",ear:"تظل الكتابات الجدارية موضوعًا مثيرًا للانقسام في مدن كثيرة.",def:"causing people to disagree strongly",t:"mastery",u:11},
{w:"revitalize",c:"B1",s:"CEFR-J",p:"verb",ar:"يُعيد الحيوية",een:"Murals can revitalize old and forgotten neighborhoods.",ear:"يمكن للجداريات أن تُعيد الحيوية للأحياء القديمة والمنسية.",def:"to make something active and strong again",t:"mastery",u:11},
{w:"elaborate",c:"B1",s:"CEFR-J",p:"adjective",ar:"متقن",een:"The elaborate mural took three months to finish.",ear:"استغرقت الجدارية المتقنة ثلاثة أشهر لإتمامها.",def:"very detailed and carefully made",t:"mastery",u:11},
{w:"deface",c:"B1",s:"CEFR-J",p:"verb",ar:"يشوّه",een:"It is a crime to deface public property.",ear:"تشويه الممتلكات العامة جريمة.",def:"to spoil the appearance of something by writing on it",t:"mastery",u:11},
{w:"underpass",c:"B1",s:"CEFR-J",p:"noun",ar:"ممر سفلي",een:"The underpass was decorated with colorful street art.",ear:"زُيّن الممر السفلي بفنون شارع ملوّنة.",def:"a road or path that goes under another road",t:"mastery",u:11},
{w:"mural tour",c:"A2",s:"CEFR-J",p:"noun",ar:"جولة جداريات",een:"We joined a mural tour to explore the city's art.",ear:"انضممنا إلى جولة جداريات لاستكشاف فنون المدينة.",def:"a guided walk to see murals and street art",t:"mastery",u:11},
{w:"realistic",c:"A2",s:"NGSL",p:"adjective",ar:"واقعي",een:"The realistic mural looks like a real photograph.",ear:"تبدو الجدارية الواقعية كصورة فوتوغرافية حقيقية.",def:"looking like real life",t:"mastery",u:11},
{w:"alley",c:"B1",s:"CEFR-J",p:"noun",ar:"زقاق",een:"The narrow alley was full of amazing street art.",ear:"كان الزقاق الضيق مليئًا بفنون شارع مذهلة.",def:"a narrow road between buildings",t:"mastery",u:11},
{w:"petition",c:"B1",s:"CEFR-J",p:"noun",ar:"عريضة",een:"Residents signed a petition to save the mural.",ear:"وقّع السكان عريضة لإنقاذ الجدارية.",def:"a written request signed by many people",t:"mastery",u:11},
{w:"whitewash",c:"B1",s:"CEFR-J",p:"verb",ar:"يطلي بالأبيض",een:"They whitewashed the wall, covering all the art.",ear:"طلوا الجدار بالأبيض وغطّوا كل الفن.",def:"to paint a wall white to cover what is on it",t:"mastery",u:11},
{w:"scaffold",c:"B1",s:"CEFR-J",p:"noun",ar:"سقالة",een:"The artist stood on a scaffold to reach the top.",ear:"وقف الفنان على سقالة للوصول إلى الأعلى.",def:"a frame structure workers stand on to reach high places",t:"mastery",u:11},
{w:"geometric",c:"A2",s:"CEFR-J",p:"adjective",ar:"هندسي",een:"The geometric mural uses circles, squares, and triangles.",ear:"تستخدم الجدارية الهندسية دوائر ومربعات ومثلثات.",def:"made of regular shapes like squares and circles",t:"mastery",u:11},
{w:"caricature",c:"B1",s:"CEFR-J",p:"noun",ar:"رسم كاريكاتوري",een:"The artist drew a funny caricature of the mayor.",ear:"رسم الفنان رسمًا كاريكاتوريًا مضحكًا لرئيس البلدية.",def:"a funny drawing that makes a person look strange",t:"mastery",u:11},
{w:"throw-up",c:"B1",s:"CEFR-J",p:"noun",ar:"رسم سريع",een:"The artist did a quick throw-up on the wall.",ear:"رسم الفنان رسمًا سريعًا على الجدار.",def:"a quick graffiti piece using two or three colors",t:"mastery",u:11},
{w:"safeguard",c:"A2",s:"CEFR-J",p:"verb",ar:"يصون",een:"The city wants to safeguard famous street art pieces.",ear:"تريد المدينة صون قطع فن الشارع الشهيرة.",def:"to protect something from damage or loss",t:"mastery",u:11},
{w:"thought-provoking",c:"B1",s:"CEFR-J",p:"adjective",ar:"مثير للتفكير",een:"The mural tells a thought-provoking story about war.",ear:"تحكي الجدارية قصة مثيرة للتفكير عن الحرب.",def:"making you think carefully about something",t:"mastery",u:11},
{w:"street performer",c:"A2",s:"CEFR-J",p:"noun",ar:"فنان شوارع",een:"The street performer drew a crowd with his act.",ear:"جذب فنان الشوارع حشدًا بأدائه.",def:"a person who does art or music in public places",t:"mastery",u:11},

// ========== UNIT 12: Remarkable Journeys (88 words) ==========
// Core (34)
{w:"adventure",c:"A2",s:"NGSL",p:"noun",ar:"مغامرة",een:"Climbing the mountain was a great adventure.",ear:"كان تسلّق الجبل مغامرة رائعة.",def:"an exciting experience that may be dangerous",t:"core",u:12},
{w:"traveler",c:"A2",s:"NGSL",p:"noun",ar:"مسافر",een:"The traveler visited ten countries in one year.",ear:"زار المسافر عشر دول في عام واحد.",def:"a person who goes to different places",t:"core",u:12},
{w:"destination",c:"A2",s:"CEFR-J",p:"noun",ar:"وجهة",een:"Our final destination is the south of France.",ear:"وجهتنا النهائية هي جنوب فرنسا.",def:"the place where you are going",t:"core",u:12},
{w:"path",c:"A2",s:"NGSL",p:"noun",ar:"مسار",een:"We followed a path through the forest.",ear:"تبعنا مسارًا عبر الغابة.",def:"a way or track for walking",t:"core",u:12},
{w:"compass",c:"A2",s:"CEFR-J",p:"noun",ar:"بوصلة",een:"The compass helped us find the right direction.",ear:"ساعدتنا البوصلة في إيجاد الاتجاه الصحيح.",def:"a tool that shows north, south, east, and west",t:"core",u:12},
{w:"plan",c:"A1",s:"NGSL",p:"verb",ar:"يخطط",een:"We need to plan our trip before we leave.",ear:"نحتاج أن نخطط لرحلتنا قبل أن نغادر.",def:"to decide what you will do in advance",t:"core",u:12},
{w:"depart",c:"A2",s:"NGSL",p:"verb",ar:"يغادر",een:"The train will depart at nine o'clock sharp.",ear:"سيغادر القطار في الساعة التاسعة تمامًا.",def:"to leave a place, especially to start a journey",t:"core",u:12},
{w:"backpack",c:"A2",s:"CEFR-J",p:"noun",ar:"حقيبة ظهر",een:"I put everything I need in my backpack.",ear:"وضعت كل ما أحتاجه في حقيبة ظهري.",def:"a bag you carry on your back",t:"core",u:12},
{w:"mountain",c:"A1",s:"NGSL",p:"noun",ar:"جبل",een:"The mountain was covered with snow at the top.",ear:"كان الجبل مغطى بالثلج في القمة.",def:"a very high area of land",t:"core",u:12},
{w:"forest",c:"A2",s:"NGSL",p:"noun",ar:"غابة",een:"We walked through a dark forest for two hours.",ear:"مشينا عبر غابة مظلمة لمدة ساعتين.",def:"a large area with many trees",t:"core",u:12},
{w:"distance",c:"A2",s:"NGSL",p:"noun",ar:"مسافة",een:"The distance between the two cities is 300 kilometers.",ear:"المسافة بين المدينتين 300 كيلومتر.",def:"how far it is from one place to another",t:"core",u:12},
{w:"route",c:"A2",s:"NGSL",p:"noun",ar:"طريق",een:"We chose the shortest route to the coast.",ear:"اخترنا أقصر طريق إلى الساحل.",def:"the way you take to get somewhere",t:"core",u:12},
{w:"migrate",c:"A2",s:"CEFR-J",p:"verb",ar:"يهاجر",een:"Many birds migrate south in winter.",ear:"تهاجر كثير من الطيور جنوبًا في الشتاء.",def:"to move from one place to another to live",t:"core",u:12},
{w:"danger",c:"A2",s:"NGSL",p:"noun",ar:"خطر",een:"There is some danger when you travel alone.",ear:"هناك بعض الخطر عندما تسافر وحدك.",def:"the possibility of being hurt or harmed",t:"core",u:12},
{w:"camp",c:"A2",s:"NGSL",p:"verb",ar:"يخيّم",een:"We camped near the lake under the stars.",ear:"خيّمنا بالقرب من البحيرة تحت النجوم.",def:"to sleep outdoors in a tent",t:"core",u:12},
{w:"tent",c:"A2",s:"CEFR-J",p:"noun",ar:"خيمة",een:"We set up the tent before it got dark.",ear:"نصبنا الخيمة قبل أن يحلّ الظلام.",def:"a shelter made of cloth used when camping",t:"core",u:12},
{w:"shore",c:"A2",s:"NGSL",p:"noun",ar:"شاطئ",een:"We could see the shore from the boat.",ear:"استطعنا رؤية الشاطئ من القارب.",def:"the land along the edge of the sea or lake",t:"core",u:12},
{w:"valley",c:"A2",s:"NGSL",p:"noun",ar:"وادٍ",een:"The green valley was between two tall mountains.",ear:"كان الوادي الأخضر بين جبلين مرتفعين.",def:"a low area of land between hills or mountains",t:"core",u:12},
{w:"sail",c:"A2",s:"NGSL",p:"verb",ar:"يبحر",een:"They sailed across the sea for three weeks.",ear:"أبحروا عبر البحر لمدة ثلاثة أسابيع.",def:"to travel on water in a boat or ship",t:"core",u:12},
{w:"wander",c:"A2",s:"CEFR-J",p:"verb",ar:"يتجوّل",een:"We wandered through the old streets of the town.",ear:"تجوّلنا في شوارع البلدة القديمة.",def:"to walk slowly without a clear direction",t:"core",u:12},
{w:"scenery",c:"A2",s:"CEFR-J",p:"noun",ar:"مناظر طبيعية",een:"The scenery along the coast was absolutely beautiful.",ear:"كانت المناظر الطبيعية على طول الساحل جميلة للغاية.",def:"the natural things you see around you outside",t:"core",u:12},
{w:"load",c:"A2",s:"NGSL",p:"verb",ar:"يحمّل",een:"We loaded the bags into the car for the trip.",ear:"حمّلنا الحقائب في السيارة للرحلة.",def:"to put things into a vehicle or container",t:"core",u:12},
{w:"land",c:"A2",s:"NGSL",p:"verb",ar:"يهبط",een:"The plane will land in two hours.",ear:"ستهبط الطائرة بعد ساعتين.",def:"to come down to the ground after flying",t:"core",u:12},
{w:"ahead",c:"A2",s:"NGSL",p:"adverb",ar:"إلى الأمام",een:"Keep going ahead and you will reach the village.",ear:"استمر في المضي قدمًا وستصل إلى القرية.",def:"in front of you, further forward",t:"core",u:12},
{w:"direction",c:"A2",s:"NGSL",p:"noun",ar:"اتجاه",een:"Which direction should we go from here?",ear:"في أي اتجاه يجب أن نذهب من هنا؟",def:"the way that something faces or moves toward",t:"core",u:12},
{w:"hill",c:"A1",s:"NGSL",p:"noun",ar:"تلة",een:"We climbed up the hill to see the view.",ear:"صعدنا التلة لرؤية المنظر.",def:"a raised area of land, smaller than a mountain",t:"core",u:12},
{w:"jungle",c:"A2",s:"CEFR-J",p:"noun",ar:"أدغال",een:"They traveled through the thick jungle for many days.",ear:"سافروا عبر الأدغال الكثيفة لأيام عديدة.",def:"a thick tropical forest with many plants",t:"core",u:12},
{w:"lost",c:"A1",s:"NGSL",p:"adjective",ar:"تائه",een:"We got lost in the forest without a map.",ear:"ضللنا الطريق في الغابة بدون خريطة.",def:"not knowing where you are",t:"core",u:12},
{w:"step",c:"A2",s:"NGSL",p:"noun",ar:"خطوة",een:"Every step brought us closer to the mountain top.",ear:"كل خطوة قرّبتنا أكثر إلى قمة الجبل.",def:"the movement of lifting and putting down your foot",t:"core",u:12},
{w:"track",c:"A2",s:"NGSL",p:"noun",ar:"أثر",een:"We followed animal tracks through the mud.",ear:"تتبعنا آثار الحيوانات عبر الوحل.",def:"marks left on the ground by feet or wheels",t:"core",u:12},
{w:"bumpy",c:"A2",s:"CEFR-J",p:"adjective",ar:"وعر",een:"The bumpy road made driving very slow.",ear:"جعل الطريق الوعر القيادة بطيئة جدًا.",def:"having a surface that is not flat or smooth",t:"core",u:12},
{w:"eventually",c:"A2",s:"NGSL",p:"adverb",ar:"في النهاية",een:"We eventually arrived after a very long journey.",ear:"وصلنا في النهاية بعد رحلة طويلة جدًا.",def:"in the end, after a long time",t:"core",u:12},
{w:"abroad",c:"A2",s:"NGSL",p:"adverb",ar:"في الخارج",een:"She wants to study abroad next year.",ear:"تريد أن تدرس في الخارج العام القادم.",def:"in or to a foreign country",t:"core",u:12},
{w:"unforgettable",c:"A2",s:"CEFR-J",p:"adjective",ar:"لا يُنسى",een:"The sunset over the mountains was unforgettable.",ear:"كان غروب الشمس فوق الجبال لا يُنسى.",def:"so good or special that you will always remember it",t:"core",u:12},

// Extended (29)
{w:"voyage",c:"A2",s:"NGSL",p:"noun",ar:"رحلة بحرية",een:"The voyage across the Atlantic took two weeks.",ear:"استغرقت الرحلة البحرية عبر المحيط الأطلسي أسبوعين.",def:"a long journey by sea or in space",t:"extended",u:12},
{w:"navigator",c:"B1",s:"CEFR-J",p:"noun",ar:"ملّاح",een:"The navigator used stars to find the way at night.",ear:"استخدم الملّاح النجوم لإيجاد الطريق في الليل.",def:"a person who plans and directs the route",t:"extended",u:12},
{w:"horizon",c:"A2",s:"NGSL",p:"noun",ar:"أفق",een:"We could see the mountains on the horizon.",ear:"استطعنا رؤية الجبال في الأفق.",def:"the line where the sky and land seem to meet",t:"extended",u:12},
{w:"summit",c:"B1",s:"CEFR-J",p:"noun",ar:"قمة",een:"The climbers reached the summit before noon.",ear:"وصل المتسلقون إلى القمة قبل الظهر.",def:"the highest point of a mountain",t:"extended",u:12},
{w:"trail",c:"A2",s:"NGSL",p:"noun",ar:"درب",een:"We followed the trail through the forest for hours.",ear:"تبعنا الدرب عبر الغابة لساعات.",def:"a rough path through the countryside",t:"extended",u:12},
{w:"border",c:"A2",s:"NGSL",p:"noun",ar:"حدود",een:"We crossed the border between the two countries.",ear:"عبرنا الحدود بين البلدين.",def:"the line that separates two countries",t:"extended",u:12},
{w:"cabin",c:"A2",s:"CEFR-J",p:"noun",ar:"كوخ",een:"We stayed in a small cabin in the mountains.",ear:"أقمنا في كوخ صغير في الجبال.",def:"a small simple house, usually made of wood",t:"extended",u:12},
{w:"campfire",c:"A2",s:"CEFR-J",p:"noun",ar:"نار مخيّم",een:"We sat around the campfire and told stories.",ear:"جلسنا حول نار المخيّم وروينا قصصًا.",def:"a fire made outdoors at a camp",t:"extended",u:12},
{w:"hitchhike",c:"B1",s:"CEFR-J",p:"verb",ar:"يسافر بالتوقف",een:"He hitchhiked from Paris to Rome last summer.",ear:"سافر بالتوقف من باريس إلى روما الصيف الماضي.",def:"to travel by getting free rides in other people's cars",t:"extended",u:12},
{w:"port",c:"A2",s:"NGSL",p:"noun",ar:"ميناء",een:"The ship arrived at the port early in the morning.",ear:"وصلت السفينة إلى الميناء في الصباح الباكر.",def:"a place where ships load and unload things",t:"extended",u:12},
{w:"crew",c:"A2",s:"NGSL",p:"noun",ar:"طاقم",een:"The crew of the ship worked hard during the storm.",ear:"عمل طاقم السفينة بجد أثناء العاصفة.",def:"a group of people who work together on a ship",t:"extended",u:12},
{w:"passage",c:"A2",s:"NGSL",p:"noun",ar:"ممر",een:"They found a secret passage through the mountains.",ear:"وجدوا ممرًا سريًا عبر الجبال.",def:"a way through or a narrow path between places",t:"extended",u:12},
{w:"obstacle",c:"B1",s:"CEFR-J",p:"noun",ar:"عائق",een:"Rocks and rivers were obstacles on their journey.",ear:"كانت الصخور والأنهار عوائق في رحلتهم.",def:"something that blocks your way or makes things hard",t:"extended",u:12},
{w:"nomad",c:"B1",s:"CEFR-J",p:"noun",ar:"بدوي",een:"The nomads travel with their animals across the land.",ear:"يسافر البدو مع حيواناتهم عبر الأرض.",def:"a person who moves from place to place to live",t:"extended",u:12},
{w:"refugee",c:"B1",s:"CEFR-J",p:"noun",ar:"لاجئ",een:"The refugee left his country to find a safe home.",ear:"غادر اللاجئ بلده ليجد منزلًا آمنًا.",def:"a person forced to leave their country for safety",t:"extended",u:12},
{w:"winding",c:"A2",s:"CEFR-J",p:"adjective",ar:"متعرّج",een:"The winding road through the hills was very scenic.",ear:"كان الطريق المتعرّج عبر التلال خلّابًا جدًا.",def:"having many curves and turns",t:"extended",u:12},
{w:"steep",c:"A2",s:"NGSL",p:"adjective",ar:"شديد الانحدار",een:"The path up the mountain was very steep.",ear:"كان المسار إلى أعلى الجبل شديد الانحدار.",def:"rising or falling at a sharp angle",t:"extended",u:12},
{w:"remote",c:"A2",s:"NGSL",p:"adjective",ar:"نائي",een:"They visited a remote village with no electricity.",ear:"زاروا قرية نائية بلا كهرباء.",def:"far away from cities and other people",t:"extended",u:12},
{w:"overnight",c:"A2",s:"NGSL",p:"adverb",ar:"طوال الليل",een:"We traveled overnight and arrived by morning.",ear:"سافرنا طوال الليل ووصلنا بحلول الصباح.",def:"for or during the whole night",t:"extended",u:12},
{w:"aboard",c:"A2",s:"NGSL",p:"preposition",ar:"على متن",een:"There were 200 people aboard the plane.",ear:"كان هناك 200 شخص على متن الطائرة.",def:"on a ship, plane, or other vehicle",t:"extended",u:12},
{w:"curious",c:"A2",s:"NGSL",p:"adjective",ar:"فضولي",een:"The curious traveler asked many questions about the culture.",ear:"سأل المسافر الفضولي أسئلة كثيرة عن الثقافة.",def:"wanting to know or learn about things",t:"extended",u:12},
{w:"gear",c:"A2",s:"NGSL",p:"noun",ar:"معدّات",een:"We packed all our camping gear in the car.",ear:"حزمنا جميع معدّات التخييم في السيارة.",def:"the equipment you need for an activity",t:"extended",u:12},
{w:"sunset",c:"A2",s:"CEFR-J",p:"noun",ar:"غروب الشمس",een:"We watched the sunset from the top of the hill.",ear:"شاهدنا غروب الشمس من قمة التلة.",def:"the time when the sun goes down in the evening",t:"extended",u:12},
{w:"sunrise",c:"A2",s:"CEFR-J",p:"noun",ar:"شروق الشمس",een:"We woke up early to see the beautiful sunrise.",ear:"استيقظنا مبكرًا لرؤية شروق الشمس الجميل.",def:"the time when the sun comes up in the morning",t:"extended",u:12},
{w:"fellow",c:"A2",s:"NGSL",p:"adjective",ar:"رفيق",een:"He shared his food with his fellow travelers.",ear:"شارك طعامه مع رفاق السفر.",def:"used to describe people in the same situation",t:"extended",u:12},
{w:"cliff",c:"A2",s:"CEFR-J",p:"noun",ar:"جرف",een:"We stood on the cliff and looked at the sea below.",ear:"وقفنا على الجرف ونظرنا إلى البحر في الأسفل.",def:"a high steep rock face, often near the sea",t:"extended",u:12},
{w:"exhausted",c:"A2",s:"NGSL",p:"adjective",ar:"منهك",een:"We were exhausted after walking for ten hours.",ear:"كنا منهكين بعد المشي لعشر ساعات.",def:"extremely tired",t:"extended",u:12},
{w:"inn",c:"A2",s:"CEFR-J",p:"noun",ar:"نزل",een:"The tired travelers stopped at a small inn to rest.",ear:"توقف المسافرون المتعبون عند نزل صغير للراحة.",def:"a small hotel, often in the countryside",t:"extended",u:12},
{w:"quest",c:"B1",s:"CEFR-J",p:"noun",ar:"سعي",een:"His quest to reach the South Pole was very difficult.",ear:"كان سعيه للوصول إلى القطب الجنوبي صعبًا جدًا.",def:"a long search for something important",t:"extended",u:12},

// Mastery (25)
{w:"trek",c:"B1",s:"CEFR-J",p:"noun",ar:"رحلة شاقة",een:"The trek through the jungle took four days.",ear:"استغرقت الرحلة الشاقة عبر الأدغال أربعة أيام.",def:"a long difficult walk through rough land",t:"mastery",u:12},
{w:"pilgrim",c:"B1",s:"CEFR-J",p:"noun",ar:"حاج",een:"Pilgrims travel long distances to reach holy places.",ear:"يسافر الحجاج مسافات طويلة للوصول إلى الأماكن المقدسة.",def:"a person who travels to a sacred place for religion",t:"mastery",u:12},
{w:"caravan",c:"B1",s:"CEFR-J",p:"noun",ar:"قافلة",een:"A caravan of merchants crossed the desert together.",ear:"عبرت قافلة من التجار الصحراء معًا.",def:"a group of people traveling together across land",t:"mastery",u:12},
{w:"overland",c:"B1",s:"CEFR-J",p:"adverb",ar:"برًّا",een:"They traveled overland from Turkey to China.",ear:"سافروا برًّا من تركيا إلى الصين.",def:"across the land, not by sea or air",t:"mastery",u:12},
{w:"uncharted",c:"B1",s:"CEFR-J",p:"adjective",ar:"غير مستكشف",een:"The sailors entered uncharted waters far from home.",ear:"دخل البحارة مياهًا غير مستكشفة بعيدًا عن الوطن.",def:"not yet explored or mapped",t:"mastery",u:12},
{w:"perilous",c:"B1",s:"CEFR-J",p:"adjective",ar:"محفوف بالمخاطر",een:"The mountain climb was perilous but beautiful.",ear:"كان تسلّق الجبل محفوفًا بالمخاطر لكنه جميل.",def:"very dangerous",t:"mastery",u:12},
{w:"traverse",c:"B1",s:"CEFR-J",p:"verb",ar:"يجتاز",een:"They traversed the entire continent on foot.",ear:"اجتازوا القارة بأكملها سيرًا على الأقدام.",def:"to travel all the way across an area",t:"mastery",u:12},
{w:"expedition leader",c:"A2",s:"CEFR-J",p:"noun",ar:"قائد البعثة",een:"The expedition leader made all the big decisions.",ear:"اتخذ قائد البعثة جميع القرارات الكبيرة.",def:"the person in charge of an exploration trip",t:"mastery",u:12},
{w:"waypoint",c:"B1",s:"CEFR-J",p:"noun",ar:"نقطة على الطريق",een:"They stopped at each waypoint to check the map.",ear:"توقفوا عند كل نقطة على الطريق للتحقق من الخريطة.",def:"a stopping point on a journey",t:"mastery",u:12},
{w:"terrain",c:"B1",s:"CEFR-J",p:"noun",ar:"تضاريس",een:"The rocky terrain made walking very difficult.",ear:"جعلت التضاريس الصخرية المشي صعبًا جدًا.",def:"the type of land in an area",t:"mastery",u:12},
{w:"endure",c:"B1",s:"CEFR-J",p:"verb",ar:"يتحمّل",een:"The travelers endured cold weather for many weeks.",ear:"تحمّل المسافرون الطقس البارد لعدة أسابيع.",def:"to suffer through something difficult for a long time",t:"mastery",u:12},
{w:"wilderness",c:"B1",s:"CEFR-J",p:"noun",ar:"برّية",een:"They spent a month living in the wilderness.",ear:"أمضوا شهرًا يعيشون في البرّية.",def:"a wild natural area where few people live",t:"mastery",u:12},
{w:"itinerary",c:"B1",s:"CEFR-J",p:"noun",ar:"خط سير الرحلة",een:"Our itinerary includes three cities in ten days.",ear:"يتضمن خط سير رحلتنا ثلاث مدن في عشرة أيام.",def:"a plan that shows where you will go on a trip",t:"mastery",u:12},
{w:"embark",c:"B1",s:"CEFR-J",p:"verb",ar:"يشرع في",een:"They embarked on a journey around the world.",ear:"شرعوا في رحلة حول العالم.",def:"to start a journey or new activity",t:"mastery",u:12},
{w:"altitude",c:"B1",s:"CEFR-J",p:"noun",ar:"ارتفاع",een:"The altitude at the top of the mountain is 4000 meters.",ear:"الارتفاع في قمة الجبل 4000 متر.",def:"how high a place is above the sea",t:"mastery",u:12},
{w:"overnight stay",c:"A2",s:"CEFR-J",p:"noun",ar:"مبيت ليلة",een:"We had an overnight stay at a small hotel.",ear:"قضينا مبيت ليلة في فندق صغير.",def:"sleeping somewhere for one night during a trip",t:"mastery",u:12},
{w:"detour",c:"B1",s:"CEFR-J",p:"noun",ar:"طريق التفافي",een:"We took a detour because the main road was closed.",ear:"أخذنا طريقًا التفافيًا لأن الطريق الرئيسي كان مغلقًا.",def:"a longer way to get somewhere when the usual way is blocked",t:"mastery",u:12},
{w:"fatigue",c:"B1",s:"CEFR-J",p:"noun",ar:"إرهاق",een:"Fatigue made it hard to continue walking.",ear:"جعل الإرهاق الاستمرار في المشي صعبًا.",def:"extreme tiredness after a lot of effort",t:"mastery",u:12},
{w:"homeward",c:"B1",s:"CEFR-J",p:"adverb",ar:"نحو الوطن",een:"After two months, they began the homeward journey.",ear:"بعد شهرين، بدأوا رحلة العودة نحو الوطن.",def:"going towards your home",t:"mastery",u:12},
{w:"seafarer",c:"B1",s:"CEFR-J",p:"noun",ar:"بحّار",een:"Ancient seafarers traveled without modern technology.",ear:"سافر البحّارة القدماء بدون تقنيات حديثة.",def:"a person who travels and works on the sea",t:"mastery",u:12},
{w:"persevere",c:"B1",s:"CEFR-J",p:"verb",ar:"يثابر",een:"You must persevere even when the road is hard.",ear:"يجب أن تثابر حتى عندما يكون الطريق صعبًا.",def:"to keep trying even when things are difficult",t:"mastery",u:12},
{w:"stopover",c:"B1",s:"CEFR-J",p:"noun",ar:"توقف مؤقت",een:"We had a short stopover in Dubai on our way.",ear:"كان لدينا توقف مؤقت قصير في دبي في طريقنا.",def:"a short stop during a long journey",t:"mastery",u:12},
{w:"restless",c:"B1",s:"CEFR-J",p:"adjective",ar:"لا يهدأ",een:"He is a restless traveler who never stays long.",ear:"إنه مسافر لا يهدأ ولا يمكث طويلًا.",def:"unable to stay still or be patient",t:"mastery",u:12},
{w:"off the beaten path",c:"B1",s:"CEFR-J",p:"adverb",ar:"بعيدًا عن المألوف",een:"She likes to visit places off the beaten path.",ear:"تحب زيارة أماكن بعيدة عن المألوف.",def:"in a place that most travelers do not go to",t:"mastery",u:12},
{w:"signpost",c:"A2",s:"CEFR-J",p:"noun",ar:"لافتة إرشادية",een:"The signpost told us we were close to the village.",ear:"أخبرتنا اللافتة الإرشادية أننا قريبون من القرية.",def:"a sign by the road showing direction or distance",t:"mastery",u:12}
];
