/* «محادثات جاهزة» — مصعب جمال العمري (A2, business major, male).
 *
 * 15 scenes he will actually walk into. Rules the content follows:
 *   • A2 English: short sentences, present/past simple, everyday modals. No idiom
 *     he could not decode, no vocabulary above his level.
 *   • Every line is something a real person says — read each one aloud before
 *     adding it. Textbook-stiff lines ("I would like to make an order, please")
 *     are worse than useless: he memorises them and then sounds foreign.
 *   • `ar` is a translation of the ENGLISH line, so its gender follows the scene
 *     (talking to a woman → مؤنث). Everything ADDRESSED TO MOSAB (situation/goal/
 *     note) is masculine — he is male.
 *   • Scenes deliberately re-use the expressions already in his phrase bank
 *     («عبارات جاهزة») so he sees the phrases he memorised actually being said.
 *   • `wrong` = authored distractors for the «دورك» drill. Each one is natural,
 *     plausible English that is WRONG HERE — either the wrong move socially, or
 *     the classic Arabic-speaker slip. That is the whole point of the drill.
 *
 * A is always Mosab. `bVoice` is the other speaker's edge-tts voice.
 */

const GROUPS = {
  uni:   { label_ar: 'الجامعة والدراسة', label_en: 'University' },
  work:  { label_ar: 'العمل والمهنة',     label_en: 'Work' },
  daily: { label_ar: 'الحياة اليومية',    label_en: 'Everyday life' },
}

const A_VOICE = 'en-US-AndrewNeural'

const SCENARIOS = [
  // ───────────────────────────── الجامعة والدراسة ─────────────────────────────
  {
    key: 'uni-classmate',
    group: 'uni',
    title_ar: 'زميل جديد في المحاضرة',
    title_en: 'A new classmate',
    place_ar: 'قاعة المحاضرات',
    situation_ar: 'دخلتَ القاعة مبكرًا وبقي مقعد واحد بجانب طالب لا تعرفه. هذه أول دقيقة معه.',
    goal_ar: 'أن تفتح الحديث، تعرّف بنفسك، وتخرج بمعلومة مفيدة — بدون توتر.',
    b_name: 'Daniel', b_role_ar: 'زميلك في المحاضرة', bVoice: 'en-US-BrianNeural',
    lines: [
      { s: 'A', en: 'Hi. Is this seat taken?', ar: 'مرحبًا. هل هذا المقعد محجوز؟',
        note: 'هذه هي الجملة الجاهزة لأي مقعد في أي مكان. لا تقل «Can I sit?» — تُفهم لكنها تبدو طفولية.',
        wrong: ['Hi. I want to sit here.', 'Hello. This seat is mine?'] },
      { s: 'B', en: 'No, go ahead.', ar: 'لا، تفضّل.',
        note: '«Go ahead» هنا تعني «تفضّل». ستسمعها كثيرًا بمعنى «ابدأ» أو «تفضّل».' },
      { s: 'A', en: "Thanks. I'm Mosab.", ar: 'شكرًا. أنا مصعب.',
        note: 'التعريف بالاسم مباشرةً بعد الشكر هو الأسلوب الطبيعي؛ لا تحتاج مقدمة طويلة.',
        wrong: ['Thanks. My name Mosab.', 'Thanks. I am from Saudi Arabia.'] },
      { s: 'B', en: "Nice to meet you, Mosab. I'm Daniel.", ar: 'تشرّفت بك يا مصعب. أنا دانيال.' },
      { s: 'A', en: 'Nice to meet you too. Is this your first year?', ar: 'وأنا كذلك. هل هذه سنتك الأولى؟',
        note: '«too» في آخر الجملة تكفي لردّ التحية؛ ثم اسأل سؤالًا لتستمر المحادثة.',
        wrong: ['Nice to meet you too. How old are you?', 'Me too. You are first year?'] },
      { s: 'B', en: "My second. I'm studying business too.", ar: 'سنتي الثانية. أنا أدرس إدارة الأعمال أيضًا.' },
      { s: 'A', en: 'Great. Do you know if the professor gives us the slides?', ar: 'جميل. هل تعرف إن كان الدكتور يعطينا الشرائح؟',
        note: '«Do you know if…» طريقة مهذبة للسؤال عن شيء قد لا يعرفه الطرف الآخر.',
        wrong: ['Great. The professor gives us the slides?', 'Great. Tell me about the professor.'] },
      { s: 'B', en: 'Yes, he uploads them after every class.', ar: 'نعم، يرفعها بعد كل محاضرة.' },
      { s: 'A', en: "That's good to hear. Sorry, I didn't catch your name again?", ar: 'يسعدني سماع ذلك. عذرًا، لم أسمع اسمك جيدًا؟',
        note: 'نسيان الاسم طبيعي جدًا. «I didn\'t catch that» أفضل بكثير من الصمت أو التخمين.',
        wrong: ['That is good. What is your name again?', "That's good to hear. Repeat your name."] },
      { s: 'B', en: 'Daniel. D-A-N-I-E-L.', ar: 'دانيال. د-ا-ن-ي-ا-ل.' },
      { s: 'A', en: 'Got it. See you next class, Daniel.', ar: 'فهمت. أراك في المحاضرة القادمة يا دانيال.',
        note: '«Got it» = فهمت/وصلتني. قصيرة وطبيعية جدًا في الكلام اليومي.',
        wrong: ['Okay. Goodbye forever, Daniel.', 'Got it. See you in the next class time.'] },
      { s: 'B', en: 'See you. Have a good one.', ar: 'أراك لاحقًا. يومك سعيد.' },
    ],
    expressions: [
      { en: 'Is this seat taken?', ar: 'هل هذا المقعد محجوز؟', when: 'قبل أن تجلس بجانب أحد في أي مكان: محاضرة، مقهى، طائرة.' },
      { en: 'Go ahead.', ar: 'تفضّل.', when: 'حين تسمح لأحد بأن يفعل شيئًا أو يتكلم أولًا.' },
      { en: "Sorry, I didn't catch that.", ar: 'عذرًا، لم أسمع ذلك جيدًا.', when: 'حين تفوتك كلمة أو اسم — بدلًا من أن تُومئ برأسك وأنت لم تفهم.' },
      { en: 'Got it.', ar: 'فهمت.', when: 'ردّ قصير يؤكد أن المعلومة وصلتك.' },
    ],
  },

  {
    key: 'uni-professor',
    group: 'uni',
    title_ar: 'سؤال الدكتور بعد المحاضرة',
    title_en: 'A question after class',
    place_ar: 'بعد المحاضرة',
    situation_ar: 'لم تفهم جزءًا من المحاضرة، والدكتور يجمع أوراقه قبل أن يخرج. أمامك دقيقة واحدة.',
    goal_ar: 'أن تسأل بأدب، وتتأكد أنك فهمت الإجابة فعلًا قبل أن تنصرف.',
    b_name: 'Dr. Bennett', b_role_ar: 'أستاذ المقرر', bVoice: 'en-US-ChristopherNeural',
    lines: [
      { s: 'A', en: 'Excuse me, Dr. Bennett. Do you have a minute?', ar: 'عذرًا يا دكتور بينيت. هل لديك دقيقة؟',
        note: '«Do you have a minute?» تفتح الباب بلطف وتعطيه فرصة للاعتذار إن كان مستعجلًا.',
        wrong: ['Hello Dr. Bennett. I have a question now.', 'Excuse me, Dr. Bennett. Are you busy or not?'] },
      { s: 'B', en: "Sure, Mosab. What's on your mind?", ar: 'بالتأكيد يا مصعب. ما الذي يشغل بالك؟' },
      { s: 'A', en: "I have a question about today's lecture.", ar: 'لديّ سؤال عن محاضرة اليوم.',
        note: 'حدّد الموضوع أولًا في جملة واحدة، ثم اسأل. هذا يريح من يستمع إليك.',
        wrong: ['I have a question in today lecture.', 'I did not understand your lecture today.'] },
      { s: 'B', en: 'Go ahead.', ar: 'تفضّل.' },
      { s: 'A', en: 'Could you go over the last example again?', ar: 'ممكن تعيد شرح المثال الأخير؟',
        note: '«go over … again» = يعيد الشرح. أفضل من «repeat» لأنها تطلب شرحًا لا مجرد تكرار.',
        wrong: ['Can you repeat the last example again please?', 'Could you go over the last example after?'] },
      { s: 'B', en: 'Of course. Which part was not clear?', ar: 'بالطبع. أي جزء لم يكن واضحًا؟' },
      { s: 'A', en: 'The part about fixed costs.', ar: 'الجزء المتعلق بالتكاليف الثابتة.',
        note: 'عبارة اسمية قصيرة تكفي كإجابة. لا تحتاج جملة كاملة في كل مرة.',
        wrong: ['The part who talks about fixed costs.', 'About the fixed costs I did not understand it.'] },
      { s: 'B', en: 'Fixed costs stay the same every month. Rent, for example.', ar: 'التكاليف الثابتة تبقى كما هي كل شهر. الإيجار، على سبيل المثال.' },
      { s: 'A', en: 'Just to make sure I understood — the rent does not change when we sell more?', ar: 'فقط لأتأكد أنني فهمت — الإيجار لا يتغير حين نبيع أكثر؟',
        note: 'هذه أثمن جملة في المشهد: تعيد الفكرة بكلماتك فيصحّحك الطرف الآخر فورًا إن أخطأت.',
        wrong: ['Just to make sure I understood — what is the rent?', 'So the rent is changing when we sell more, yes?'] },
      { s: 'B', en: "Exactly. You've got it.", ar: 'بالضبط. فهمتها.' },
      { s: 'A', en: "Thank you. That's much clearer now.", ar: 'شكرًا لك. صار الأمر أوضح بكثير.',
        note: 'أغلِق المحادثة بجملة تُشعر الطرف الآخر أن وقته لم يضِع. هذا يجعله يرحّب بك في المرة القادمة.',
        wrong: ['Thank you. Now I am clear.', 'Thank you very much for your time and your effort and your help.'] },
      { s: 'B', en: 'Anytime. Come by my office if you have more questions.', ar: 'في أي وقت. مرّ على مكتبي إن كان لديك مزيد من الأسئلة.' },
    ],
    expressions: [
      { en: 'Do you have a minute?', ar: 'هل لديك دقيقة؟', when: 'قبل أن تشغل وقت أحد — أستاذ، مدير، زميل مشغول.' },
      { en: 'Could you go over that again?', ar: 'ممكن تعيد شرح هذه النقطة؟', when: 'حين تحتاج شرحًا ثانيًا لا مجرد تكرار للكلمات.' },
      { en: 'Just to make sure I understood…', ar: 'فقط لأتأكد أنني فهمت…', when: 'بعد أي شرح مهم — تعيد الفكرة بكلماتك ليصحّحك إن أخطأت.' },
      { en: "That's much clearer now.", ar: 'صار الأمر أوضح بكثير.', when: 'لتشكر شخصًا شرح لك شيئًا، بطريقة تُظهر أن شرحه نفعك فعلًا.' },
    ],
  },

  {
    key: 'uni-project',
    group: 'uni',
    title_ar: 'مشروع جماعي — توزيع المهام',
    title_en: 'Splitting a group project',
    place_ar: 'مكتبة الجامعة',
    situation_ar: 'أنت وزميلتك أمام مشروع من ثلاثة أجزاء، ولديكما عشر دقائق قبل المحاضرة القادمة.',
    goal_ar: 'أن تأخذ نصيبك من العمل، وتتفق على موعد واضح — لا على «إن شاء الله قريبًا».',
    b_name: 'Sarah', b_role_ar: 'زميلتك في المشروع', bVoice: 'en-US-EmmaNeural',
    lines: [
      { s: 'B', en: 'So, we have three parts. How do we split them?', ar: 'إذن، لدينا ثلاثة أجزاء. كيف نقسّمها؟' },
      { s: 'A', en: 'I can take the market research part.', ar: 'أستطيع أن آخذ جزء بحث السوق.',
        note: 'تطوّع بجزء محدد بدلًا من أن تنتظر أن يُوزَّع عليك. هذا يترك انطباعًا ممتازًا.',
        wrong: ['I can take the part of market research one.', 'Anything is fine for me, you choose.'] },
      { s: 'B', en: "Great. I'll do the financial part, then.", ar: 'ممتاز. سآخذ أنا الجزء المالي إذن.' },
      { s: 'A', en: 'What about the presentation?', ar: 'وماذا عن العرض التقديمي؟',
        note: '«What about…?» أسرع طريقة لتنقل الحديث إلى نقطة لم تُبحث بعد.',
        wrong: ['And the presentation what?', 'What about the presentation part of the project?'] },
      { s: 'B', en: 'Maybe we do that one together.', ar: 'ربما نعمله معًا.' },
      { s: 'A', en: 'That works for me.', ar: 'هذا يناسبني.',
        note: 'جملة موافقة قصيرة ومهنية. أفضل من «Okay» وحدها.',
        wrong: ['This is working for me.', 'That works to me.'] },
      { s: 'B', en: 'When can you finish your part?', ar: 'متى تستطيع إنهاء جزئك؟' },
      { s: 'A', en: 'By Sunday, I think. Can we set a deadline for this?', ar: 'بحلول الأحد، على ما أظن. ممكن نحدّد موعدًا نهائيًا؟',
        note: '«By Sunday» = في موعد أقصاه الأحد. «On Sunday» تعني يوم الأحد نفسه — فرق مهم في العمل.',
        wrong: ['In Sunday, I think. Can we set a deadline for this?', 'Sunday maybe. We will see later.'] },
      { s: 'B', en: "Let's say Monday evening. Is that okay?", ar: 'لنقل مساء الاثنين. هل هذا مناسب؟' },
      { s: 'A', en: "Fair enough. I'll keep you posted.", ar: 'لا بأس. سأبقيكِ على اطّلاع.',
        note: '«I\'ll keep you posted» = سأخبرك أولًا بأول. تريح شريكك في أي عمل مشترك.',
        wrong: ['Fair enough. I will tell you the news later.', 'Fair enough. I keep you posted.'] },
      { s: 'B', en: 'Perfect. Message me if you get stuck.', ar: 'ممتاز. راسلني إن واجهتك مشكلة.' },
      { s: 'A', en: 'I will. Thanks, Sarah.', ar: 'سأفعل. شكرًا يا سارة.',
        note: '«I will» وحدها ردّ كامل على طلب — لا تحتاج إعادة الجملة كلها.',
        wrong: ['Yes I will do it. Thanks, Sarah.', 'Of course I am. Thanks, Sarah.'] },
    ],
    expressions: [
      { en: 'That works for me.', ar: 'هذا يناسبني.', when: 'للموافقة على موعد أو خطة بطريقة مهنية قصيرة.' },
      { en: 'Can we set a deadline for this?', ar: 'ممكن نحدّد موعدًا نهائيًا؟', when: 'حين يبقى الاتفاق مفتوحًا بلا تاريخ — وهذا ما يُفشل معظم المشاريع الجماعية.' },
      { en: "I'll keep you posted.", ar: 'سأبقيك على اطّلاع.', when: 'حين تأخذ مهمة على عاتقك وتريد طمأنة الطرف الآخر.' },
      { en: 'Fair enough.', ar: 'كلامك مقبول / لا بأس.', when: 'حين تقبل اقتراحًا وإن لم يكن اختيارك الأول.' },
    ],
  },

  {
    key: 'uni-registration',
    group: 'uni',
    title_ar: 'في عمادة القبول والتسجيل',
    title_en: 'At the registration office',
    place_ar: 'مبنى الإدارة',
    situation_ar: 'محاضرتان في نفس الوقت، وتحتاج حذف مقرر وإضافة آخر قبل انتهاء فترة التعديل.',
    goal_ar: 'أن تشرح مشكلتك بوضوح وتخرج بإجراء مكتمل، لا بوعد.',
    b_name: 'Ms. Reed', b_role_ar: 'موظفة التسجيل', bVoice: 'en-US-AvaNeural',
    lines: [
      { s: 'A', en: 'Excuse me, I have a question about my schedule.', ar: 'عذرًا، لديّ سؤال عن جدولي.',
        note: 'ابدأ بالموضوع في جملة واحدة. الموظف يخدم عشرات الطلاب — الوضوح خدمة له ولك.',
        wrong: ['Excuse me, I have a question in my schedule.', 'Hello, can you help me please with something?'] },
      { s: 'B', en: "Sure. What's your student number?", ar: 'بالتأكيد. ما رقمك الجامعي؟' },
      { s: 'A', en: "It's four-four-one-zero-two-two.", ar: 'إنه ٤٤١٠٢٢.',
        note: 'الأرقام تُقرأ رقمًا رقمًا في الأرقام التعريفية. و«zero» أوضح من «oh» مع من لا يعرفك.',
        wrong: ['It is four hundred forty-one thousand twenty-two.', 'My number four four one zero two two.'] },
      { s: 'B', en: 'Thanks. What do you need?', ar: 'شكرًا. ما الذي تحتاجه؟' },
      { s: 'A', en: "I'd like to drop one course and add another.", ar: 'أودّ حذف مقرر وإضافة آخر.',
        note: '«drop» و«add» هما الفعلان الرسميان للحذف والإضافة في الجامعات.',
        wrong: ['I want to delete one course and put another.', "I'd like to drop one course and add other."] },
      { s: 'B', en: 'Which one do you want to drop?', ar: 'أي مقرر تريد حذفه؟' },
      { s: 'A', en: "Statistics. It's at the same time as my marketing class.", ar: 'الإحصاء. إنه في نفس وقت محاضرة التسويق.',
        note: 'اذكر السبب في جملة قصيرة — يجعل طلبك مفهومًا ومقبولًا فورًا.',
        wrong: ['Statistics. It is in the same time with my marketing class.', 'Statistics, because I do not like it.'] },
      { s: 'B', en: 'I see. The deadline for changes is next Wednesday.', ar: 'فهمت. آخر موعد للتعديل هو الأربعاء القادم.' },
      { s: 'A', en: 'Sorry to bother you, but could you do it now?', ar: 'أعتذر على الإزعاج، لكن هل يمكنكِ تنفيذه الآن؟',
        note: '«Sorry to bother you, but…» تجعل الطلب المستعجل مقبولًا بدل أن يبدو إلحاحًا.',
        wrong: ['Sorry to bother you, but do it now please.', 'Can you do it now? I am in a hurry.'] },
      { s: 'B', en: 'I can. Please sign here.', ar: 'أستطيع. وقّع هنا من فضلك.' },
      { s: 'A', en: 'Done. Will I get a confirmation?', ar: 'تم. هل تصلني رسالة تأكيد؟',
        note: 'اسأل دائمًا عن التأكيد. هذا يحميك إن ضاع الإجراء.',
        wrong: ['Done. I will get a confirmation?', 'Done. Send me a confirmation.'] },
      { s: 'B', en: 'Yes, by email in a few minutes.', ar: 'نعم، عبر البريد خلال دقائق.' },
      { s: 'A', en: 'Thank you so much. Have a good day.', ar: 'شكرًا جزيلًا لكِ. يومك سعيد.',
        note: 'ختام قصير ومهذب يكفي؛ لا تُطِل الشكر أكثر من جملتين.',
        wrong: ['Thank you so much. Have a good day for you.', 'Thanks God. Bye bye.'] },
    ],
    expressions: [
      { en: 'Sorry to bother you, but…', ar: 'أعتذر على الإزعاج، لكن…', when: 'قبل أي طلب يقطع على أحد عمله.' },
      { en: 'to drop / to add a course', ar: 'حذف / إضافة مقرر', when: 'المصطلح الرسمي في أي جامعة ناطقة بالإنجليزية.' },
      { en: 'Will I get a confirmation?', ar: 'هل تصلني رسالة تأكيد؟', when: 'بعد أي إجراء رسمي: تسجيل، حجز، طلب، إرجاع.' },
    ],
  },

  // ───────────────────────────── العمل والمهنة ─────────────────────────────
  {
    key: 'work-interview',
    group: 'work',
    title_ar: 'مقابلة تدريب صيفي',
    title_en: 'An internship interview',
    place_ar: 'مكتب الموارد البشرية',
    situation_ar: 'قدّمتَ على تدريب صيفي، وأمامك عشرون دقيقة مع مسؤولة التوظيف.',
    goal_ar: 'أن تقدّم نفسك بثقة، وتذكر نقطة ضعف بصدق دون أن تُضعف موقفك.',
    b_name: 'Ms. Clark', b_role_ar: 'مسؤولة التوظيف', bVoice: 'en-US-JennyNeural',
    lines: [
      { s: 'B', en: 'Good morning, Mosab. Thanks for coming in.', ar: 'صباح الخير يا مصعب. شكرًا لحضورك.' },
      { s: 'A', en: 'Good morning. Thank you for the opportunity.', ar: 'صباح الخير. شكرًا لكِ على الفرصة.',
        note: 'جملة افتتاح آمنة في أي مقابلة، ولا تحتاج أكثر منها.',
        wrong: ['Good morning. Thank you for this chance to me.', 'Hi. I am very happy to be here today with you.'] },
      { s: 'B', en: 'Tell me a little about yourself.', ar: 'أخبرني قليلًا عن نفسك.' },
      { s: 'A', en: "I'm a business student, and I'm in my second year.", ar: 'أنا طالب إدارة أعمال، وأنا في سنتي الثانية.',
        note: 'ابدأ بجملتين واضحتين. «Tell me about yourself» سؤال مهني، لا سؤال شخصي.',
        wrong: ['I am student in business and I have twenty years old.', 'I am a business student since two years.'] },
      { s: 'B', en: 'Why are you interested in this internship?', ar: 'لماذا أنت مهتم بهذا التدريب؟' },
      { s: 'A', en: 'I want to learn how a real company works, not only from books.', ar: 'أريد أن أتعلّم كيف تعمل شركة حقيقية، لا من الكتب فقط.',
        note: 'سبب صادق ومحدد أقوى بكثير من «أريد أن أطوّر نفسي».',
        wrong: ['Because I need experience for my CV.', 'I want to learn how a real company work.'] },
      { s: 'B', en: 'What are you good at?', ar: 'ما الذي تجيده؟' },
      { s: 'A', en: "I'm good with numbers, and I work well in a team.", ar: 'أنا جيد في الأرقام، وأعمل جيدًا ضمن فريق.',
        note: '«good with numbers» و«work well in a team» تعبيران جاهزان — احفظهما كما هما.',
        wrong: ['I am good in numbers, and I work good in a team.', 'I am the best student in my class.'] },
      { s: 'B', en: 'And what would you like to improve?', ar: 'وما الذي تودّ تحسينه؟' },
      { s: 'A', en: 'My English, to be honest. I practise every day.', ar: 'لغتي الإنجليزية، بصراحة. أتدرّب كل يوم.',
        note: 'الصدق + خطوة عملية. الاعتراف وحده يُضعفك؛ الاعتراف مع «I practise every day» يقوّيك.',
        wrong: ['Nothing, I think I am ready for everything.', 'My English is very bad, sorry for that.'] },
      { s: 'B', en: "That's a good answer. Do you have any questions for me?", ar: 'إجابة جيدة. هل لديك أسئلة لي؟' },
      { s: 'A', en: 'Yes. What does a normal day look like for an intern?', ar: 'نعم. كيف يبدو اليوم المعتاد للمتدرّب؟',
        note: 'اسأل دائمًا سؤالًا واحدًا على الأقل. الصمت هنا يُقرأ قلة اهتمام.',
        wrong: ['No, everything is clear, thank you.', 'Yes. How much is the salary?'] },
      { s: 'B', en: "Mostly reports and team meetings. We'll be in touch this week.", ar: 'غالبًا تقارير واجتماعات فريق. سنتواصل معك هذا الأسبوع.' },
      { s: 'A', en: 'Thank you. I look forward to hearing from you.', ar: 'شكرًا لكِ. أتطلّع لسماع أخبارك.',
        note: '«I look forward to hearing from you» هي جملة الختام القياسية — في المقابلة وفي البريد.',
        wrong: ['Thank you. I wait your call.', 'Thank you. I look forward to hear from you.'] },
    ],
    expressions: [
      { en: "I'm good with numbers.", ar: 'أنا جيد في الأرقام.', when: 'لوصف مهارة — لاحظ «good WITH» للأشياء و«good AT» للأفعال.' },
      { en: 'I work well in a team.', ar: 'أعمل جيدًا ضمن فريق.', when: 'أكثر جملة مطلوبة في المقابلات، وأكثر جملة تُقال بشكل خاطئ.' },
      { en: 'To be honest, …', ar: 'بصراحة، …', when: 'قبل إجابة صادقة عن نقطة ضعف أو رأي مخالف.' },
      { en: 'I look forward to hearing from you.', ar: 'أتطلّع لسماع أخبارك.', when: 'ختام أي مقابلة أو رسالة رسمية. بعد «to» يأتي الفعل بـ ing هنا.' },
    ],
  },

  {
    key: 'work-first-meeting',
    group: 'work',
    title_ar: 'أول اجتماع — عرّف بنفسك',
    title_en: 'Your first team meeting',
    place_ar: 'غرفة الاجتماعات',
    situation_ar: 'أول يوم لك في الفريق. الاجتماع بدأ، ورئيس الفريق طلب منك أن تعرّف بنفسك.',
    goal_ar: 'أن تعرّف بنفسك في ثلاث جمل، وتطلب المساعدة مقدّمًا دون أن تبدو ضعيفًا.',
    b_name: 'Tom', b_role_ar: 'رئيس الفريق', bVoice: 'en-US-GuyNeural',
    lines: [
      { s: 'B', en: 'Before we start, we have a new member. Mosab, would you like to introduce yourself?', ar: 'قبل أن نبدأ، لدينا عضو جديد. مصعب، هل تودّ أن تعرّف بنفسك؟' },
      { s: 'A', en: "Sure. Hi everyone, I'm Mosab. I've just joined the marketing team.", ar: 'بالتأكيد. مرحبًا جميعًا، أنا مصعب. انضممت للتو إلى فريق التسويق.',
        note: '«I\'ve just joined» = انضممت قبل قليل. الحاضر التام مع «just» هو الصيغة الطبيعية هنا.',
        wrong: ['Sure. Hi everyone, I am Mosab. I joined the marketing team from yesterday.', 'Sure. My name is Mosab and I am new here in this company.'] },
      { s: 'B', en: 'Welcome aboard. What will you be working on?', ar: 'أهلًا بك معنا. على ماذا ستعمل؟' },
      { s: 'A', en: "I'll be helping with customer reports for now.", ar: 'سأساعد في تقارير العملاء في الوقت الحالي.',
        note: '«for now» تعني «مبدئيًا» — تحميك من الالتزام بشيء نهائي في يومك الأول.',
        wrong: ['I will help in customer reports for now.', 'I do not know exactly until now.'] },
      { s: 'B', en: 'Great. Feel free to ask if anything is unclear.', ar: 'ممتاز. لا تتردد في السؤال إن كان هناك ما هو غير واضح.' },
      { s: 'A', en: 'Thanks. Can I add something here?', ar: 'شكرًا. ممكن أضيف نقطة هنا؟',
        note: 'هذه الجملة تفتح لك بابًا للكلام في أي اجتماع دون أن تقاطع أحدًا.',
        wrong: ['Thanks. I want to say something.', 'Thanks. Can I add something in here?'] },
      { s: 'B', en: 'Please do.', ar: 'تفضّل.' },
      { s: 'A', en: "I'm still learning the system, so I may be a bit slow at first.", ar: 'ما زلت أتعلّم النظام، لذا قد أكون بطيئًا قليلًا في البداية.',
        note: 'أن تضبط التوقعات مقدّمًا يُقرأ نضجًا، لا ضعفًا — بشرط أن تقولها مرة واحدة.',
        wrong: ['I am still learning the system, so sorry if I make mistakes always.', 'I am still learn the system, so I may be slow.'] },
      { s: 'B', en: "That's completely normal. Take your time.", ar: 'هذا طبيعي تمامًا. خذ وقتك.' },
      { s: 'A', en: 'Thank you. I appreciate it.', ar: 'شكرًا. أقدّر ذلك.',
        note: '«I appreciate it» أدفأ من «thank you» وحدها، وتُستعمل كثيرًا في العمل.',
        wrong: ['Thank you. I appreciate you.', 'Thank you. This is very kind from you.'] },
      { s: 'B', en: "All right, let's move on to the agenda.", ar: 'حسنًا، لننتقل إلى جدول الأعمال.' },
    ],
    expressions: [
      { en: "I've just joined…", ar: 'انضممت للتو إلى…', when: 'للتعريف بنفسك في أول أيامك في مكان جديد.' },
      { en: 'Can I add something here?', ar: 'ممكن أضيف نقطة هنا؟', when: 'لتدخل في نقاش دائر دون مقاطعة فظّة.' },
      { en: 'I appreciate it.', ar: 'أقدّر ذلك.', when: 'شكر أدفأ من «thank you» بعد لطف أو تسهيل من أحد.' },
      { en: 'Welcome aboard.', ar: 'أهلًا بك معنا.', when: 'ستسمعها في أول يوم عمل — تعني «أهلًا بك في الفريق».' },
    ],
  },

  {
    key: 'work-customer-call',
    group: 'work',
    title_ar: 'مكالمة مع عميلة',
    title_en: 'A call with a customer',
    place_ar: 'مكالمة هاتفية',
    situation_ar: 'الهاتف يرن. عميلة وصلها نصف طلبها فقط، وأنت من سيتولى المكالمة.',
    goal_ar: 'أن تعتذر، تجمع المعلومة، وتنهي المكالمة بوعد واضح — والهاتف أصعب من اللقاء المباشر.',
    b_name: 'Linda', b_role_ar: 'عميلة', bVoice: 'en-US-MichelleNeural',
    lines: [
      { s: 'A', en: 'Good afternoon, this is Mosab speaking. How can I help you?', ar: 'مساء الخير، معك مصعب. كيف أستطيع مساعدتكِ؟',
        note: '«this is … speaking» هي صيغة تعريف النفس في الهاتف. لا تقل «I am Mosab» في المكالمات.',
        wrong: ['Good afternoon, I am Mosab. How can I help you?', 'Hello, who is speaking please?'] },
      { s: 'B', en: 'Hi. I ordered two chairs last week and only one arrived.', ar: 'مرحبًا. طلبت كرسيين الأسبوع الماضي ووصل واحد فقط.' },
      { s: 'A', en: "I'm sorry about that. Could I have your order number, please?", ar: 'أعتذر عن ذلك. ممكن رقم طلبكِ من فضلك؟',
        note: 'اعتذار قصير ثم سؤال عملي. الاعتذار الطويل يزيد توتر العميل.',
        wrong: ['I am very very sorry. This is not our mistake.', "I'm sorry about that. Give me your order number."] },
      { s: 'B', en: "It's four-eight-two-one.", ar: 'إنه ٤٨٢١.' },
      { s: 'A', en: "Sorry, I didn't catch that. Could you say it again?", ar: 'عذرًا، لم أسمع ذلك جيدًا. ممكن تعيدينه؟',
        note: 'في الهاتف تفوتك الأرقام كثيرًا. اطلب الإعادة فورًا — التخمين يكلّف أكثر.',
        wrong: ['Sorry, I did not hear. Say again.', 'Sorry, what? Repeat please.'] },
      { s: 'B', en: 'Sure. Four, eight, two, one.', ar: 'بالتأكيد. أربعة، ثمانية، اثنان، واحد.' },
      { s: 'A', en: 'Thank you. Let me check that for you.', ar: 'شكرًا. دعيني أتحقق من ذلك لكِ.',
        note: '«Let me check that for you» تملأ الصمت أثناء بحثك، وتُشعر العميل أنك تعمل.',
        wrong: ['Thank you. Wait a moment please.', 'Thank you. I will check it to you.'] },
      { s: 'B', en: 'Take your time.', ar: 'خذ وقتك.' },
      { s: 'A', en: 'I see the problem. The second chair ships on Thursday.', ar: 'أرى المشكلة. الكرسي الثاني يُشحن يوم الخميس.',
        note: '«ships» هنا فعل: يُشحن. الأفعال القصيرة تجعل كلامك مهنيًا.',
        wrong: ['I see the problem. The second chair will be shipping in Thursday.', 'I found it. Maybe it comes on Thursday.'] },
      { s: 'B', en: "Okay. Will I get a message when it's on the way?", ar: 'حسنًا. هل ستصلني رسالة حين يكون في الطريق؟' },
      { s: 'A', en: "Yes, I'll keep you posted.", ar: 'نعم، سأبقيكِ على اطّلاع.',
        note: 'نفس الجملة التي تستعملها مع زملائك تصلح مع العملاء — احفظ الجمل متعددة الاستعمال.',
        wrong: ['Yes, I will send you a message maybe.', 'Yes, I keep you posted.'] },
      { s: 'B', en: 'Thank you very much.', ar: 'شكرًا جزيلًا.' },
      { s: 'A', en: "You're welcome. Have a good day.", ar: 'على الرحب والسعة. يومك سعيد.',
        note: 'أنهِ المكالمة بجملة ختام واضحة حتى يعرف الطرف الآخر أنها انتهت.',
        wrong: ["You're welcome. Bye bye.", 'No problem. Have a good day.'] },
    ],
    expressions: [
      { en: 'This is Mosab speaking.', ar: 'معك مصعب.', when: 'للتعريف بنفسك في الهاتف — صيغة ثابتة لا تتغير.' },
      { en: 'How can I help you?', ar: 'كيف أستطيع مساعدتك؟', when: 'افتتاح أي مكالمة أو خدمة عميل.' },
      { en: 'Let me check that for you.', ar: 'دعني أتحقق من ذلك لك.', when: 'حين تحتاج وقتًا للبحث وأنت على الخط.' },
      { en: "Sorry, I didn't catch that.", ar: 'عذرًا، لم أسمع ذلك جيدًا.', when: 'في الهاتف تحديدًا — أهم جملة تحميك من الخطأ.' },
    ],
  },

  {
    key: 'work-more-time',
    group: 'work',
    title_ar: 'طلب مهلة إضافية من مديرك',
    title_en: 'Asking your manager for more time',
    place_ar: 'مكتب المدير',
    situation_ar: 'موعد التقرير غدًا، وأنت لن تُنهيه. تذهب إلى مديرك اليوم — لا غدًا.',
    goal_ar: 'أن تطلب مهلة بمهنية: تعترف، تشرح السبب، وتقترح موعدًا جديدًا أنت من يقترحه.',
    b_name: 'Mark', b_role_ar: 'مديرك المباشر', bVoice: 'en-US-SteffanNeural',
    lines: [
      { s: 'A', en: 'Do you have a minute? Sorry to bother you.', ar: 'هل لديك دقيقة؟ أعتذر على الإزعاج.',
        note: 'اطلب الإذن أولًا. الدخول مباشرة في المشكلة يجعل المدير في موقف دفاعي.',
        wrong: ['Do you have a minute? I have a big problem.', 'Sorry, are you free now or after?'] },
      { s: 'B', en: "Of course. What's up?", ar: 'بالتأكيد. ما الأمر؟' },
      { s: 'A', en: "It's about the report. I'm running a bit behind.", ar: 'بخصوص التقرير. أنا متأخر قليلًا.',
        note: '«I\'m running a bit behind» أفضل من «I am late» — تصف الوضع لا تدين نفسك.',
        wrong: ["It's about the report. I am late, I am sorry.", "It's about the report. I am running behind a bit."] },
      { s: 'B', en: 'How far behind are we talking?', ar: 'كم التأخير تقريبًا؟' },
      { s: 'A', en: 'I need two more days, I think.', ar: 'أحتاج يومين إضافيين، على ما أظن.',
        note: 'اذكر رقمًا محددًا. «قليلًا» تترك مديرك في حيرة، والرقم يريحه.',
        wrong: ['I need some more days, I think.', 'I need two days more, I think.'] },
      { s: 'B', en: "What's slowing you down?", ar: 'ما الذي يبطئك؟' },
      { s: 'A', en: "I'm still waiting for the numbers from finance.", ar: 'ما زلت أنتظر الأرقام من قسم المالية.',
        note: 'سبب واقعي خارج عن سيطرتك — لكن لا تتوقف هنا، اتبعه بما ستفعله أنت.',
        wrong: ['Finance did not send me anything, it is their fault.', 'I am still waiting the numbers from finance.'] },
      { s: 'B', en: 'I see. Have you followed up with them?', ar: 'فهمت. هل تابعت معهم؟' },
      { s: 'A', en: "Yes, I emailed them yesterday. I'll follow up again today.", ar: 'نعم، راسلتهم بالأمس. سأتابع معهم مرة أخرى اليوم.',
        note: 'هذه الجملة تغيّر المشهد كله: تُظهر أنك تعالج المشكلة لا تنتظرها.',
        wrong: ['Not yet, I will do it later.', 'Yes, I emailed them yesterday but no answer.'] },
      { s: 'B', en: 'All right. Thursday, then. Can you make that work?', ar: 'حسنًا. الخميس إذن. هل تستطيع الالتزام بذلك؟' },
      { s: 'A', en: 'Yes. Thursday works for me. Thanks for understanding.', ar: 'نعم. الخميس يناسبني. شكرًا لتفهّمك.',
        note: 'أكّد الموعد بصوتك — التأكيد اللفظي يجعل الاتفاق حقيقيًا لكليكما.',
        wrong: ['Yes. Thursday is okay. Thanks for your understand.', 'Inshallah Thursday. Thanks for understanding.'] },
      { s: 'B', en: 'No problem. Just tell me early next time.', ar: 'لا مشكلة. فقط أخبرني مبكرًا في المرة القادمة.' },
    ],
    expressions: [
      { en: "I'm running a bit behind.", ar: 'أنا متأخر قليلًا.', when: 'لتخبر أحدًا بتأخّرك قبل أن يكتشفه بنفسه.' },
      { en: 'Have you followed up with them?', ar: 'هل تابعت معهم؟', when: '«follow up» = يتابع طلبًا سابقًا. من أكثر تعابير العمل استعمالًا.' },
      { en: 'Can you make that work?', ar: 'هل تستطيع الالتزام بذلك؟', when: 'ستسمعها من مديرك حين يقترح موعدًا ويريد تأكيدك.' },
      { en: 'Thanks for understanding.', ar: 'شكرًا لتفهّمك.', when: 'بعد أن يقبل أحد عذرًا أو تأخيرًا منك.' },
    ],
  },

  {
    key: 'work-disagree',
    group: 'work',
    title_ar: 'تعترض على فكرة… بلطف',
    title_en: 'Disagreeing politely',
    place_ar: 'اجتماع الفريق',
    situation_ar: 'زميلتك تقترح فكرة تراها خاطئة، والجميع ينتظر رأيك.',
    goal_ar: 'أن تعترض دون أن تُحرج أحدًا: تعترف بوجهة نظرها، تعطي دليلًا، ثم تقترح بديلًا.',
    b_name: 'Rachel', b_role_ar: 'زميلة في الفريق', bVoice: 'en-US-EmmaNeural',
    lines: [
      { s: 'B', en: 'I think we should send the newsletter every day.', ar: 'أعتقد أننا يجب أن نرسل النشرة البريدية كل يوم.' },
      { s: 'A', en: 'I see your point, but every day may be too much.', ar: 'أفهم وجهة نظركِ، لكن كل يوم قد يكون كثيرًا.',
        note: 'القاعدة الذهبية للاعتراض: اعترف أولًا («I see your point») ثم اعترض. هذا يمنع الخصومة.',
        wrong: ['No, I do not agree with this idea.', 'I see your point, but every day is too much for sure.'] },
      { s: 'B', en: 'Why do you say that?', ar: 'لماذا تقول ذلك؟' },
      { s: 'A', en: 'Last month we sent three, and people opened the first one only.', ar: 'الشهر الماضي أرسلنا ثلاثًا، وفتح الناس الأولى فقط.',
        note: 'رقم واحد حقيقي يقنع أكثر من عشر جمل رأي.',
        wrong: ['Because I feel it is too much for the people.', 'Last month we send three, and people open the first only.'] },
      { s: 'B', en: "That's a fair point. So what do you suggest?", ar: 'نقطة وجيهة. إذن ماذا تقترح؟' },
      { s: 'A', en: 'Maybe once a week, with better content.', ar: 'ربما مرة في الأسبوع، بمحتوى أفضل.',
        note: '«Maybe» تخفّف الاقتراح فيسهل قبوله أو تعديله دون أن يخسر أحد ماء وجهه.',
        wrong: ['Once a week is better, this is the right way.', 'Maybe one time in the week, with better content.'] },
      { s: 'B', en: 'Hmm. Once a week feels slow to me.', ar: 'همم. مرة في الأسبوع تبدو بطيئة بالنسبة لي.' },
      { s: 'A', en: "Let's agree to try it for one month and look at the numbers.", ar: 'لنتفق على تجربتها لشهر واحد وننظر في الأرقام.',
        note: 'حين تتعادل الآراء، اقترح تجربة محدودة بوقت. لا أحد يرفض تجربة شهر.',
        wrong: ['Okay, we do it your way then.', "Let's agree to try it for one month and see the numbers after that and decide."] },
      { s: 'B', en: 'That makes sense. Who will check the numbers?', ar: 'كلام منطقي. من سيتابع الأرقام؟' },
      { s: 'A', en: "I can do that. I'll keep you posted.", ar: 'أستطيع أنا. سأبقيكِ على اطّلاع.',
        note: 'من يقترح التجربة يحملها. هذا ما يجعل اعتراضك مقبولًا في المرة القادمة.',
        wrong: ['Maybe someone from the team can do it.', 'I can do it. I will keep you posted about everything.'] },
      { s: 'B', en: "Great. Let's bring it up in Sunday's meeting.", ar: 'ممتاز. لنطرحها في اجتماع الأحد.' },
      { s: 'A', en: 'Sounds good.', ar: 'يبدو جيدًا.',
        note: '«Sounds good» ردّ موافقة قصير جدًا وشائع جدًا. احفظه.',
        wrong: ['It is sounding good.', 'Good sounds.'] },
    ],
    expressions: [
      { en: 'I see your point, but…', ar: 'أفهم وجهة نظرك، لكن…', when: 'الطريقة الآمنة لبدء أي اعتراض في العمل.' },
      { en: "That's a fair point.", ar: 'نقطة وجيهة.', when: 'لتعترف بحجة الطرف الآخر قبل أن تكمل رأيك.' },
      { en: 'What do you suggest?', ar: 'ماذا تقترح؟', when: 'لتحويل النقاش من «لا» إلى حل.' },
      { en: 'Sounds good.', ar: 'يبدو جيدًا.', when: 'موافقة قصيرة على خطة أو موعد.' },
    ],
  },

  // ───────────────────────────── الحياة اليومية ─────────────────────────────
  {
    key: 'life-cafe',
    group: 'daily',
    title_ar: 'في المقهى',
    title_en: 'At the café',
    place_ar: 'مقهى',
    situation_ar: 'الطابور أمامك انتهى، والباريستا تنتظر طلبك. لديك عشر ثوانٍ.',
    goal_ar: 'أن تطلب وتدفع وتسأل عن مدة الانتظار بثلاث جمل جاهزة لا تفكر فيها.',
    b_name: 'Chloe', b_role_ar: 'باريستا', bVoice: 'en-US-AriaNeural',
    lines: [
      { s: 'B', en: 'Hi there. What can I get you?', ar: 'مرحبًا. ماذا أُحضر لك؟' },
      { s: 'A', en: 'Could I get a medium latte, please?', ar: 'ممكن لاتيه وسط من فضلك؟',
        note: '«Could I get…?» هي صيغة الطلب في المقاهي والمطاعم. أكثر طبيعية من «I want».',
        wrong: ['I want a medium latte please.', 'Give me one latte medium, please.'] },
      { s: 'B', en: 'Sure. For here or to go?', ar: 'بالتأكيد. هنا أم سفري؟' },
      { s: 'A', en: 'To go, please.', ar: 'سفري، من فضلك.',
        note: '«to go» = سفري. في بريطانيا يقولون «takeaway». كلاهما مفهوم.',
        wrong: ['Outside, please.', 'To go out, please.'] },
      { s: 'B', en: 'Anything to eat?', ar: 'أي شيء للأكل؟' },
      { s: 'A', en: 'No, thanks. Just the coffee.', ar: 'لا، شكرًا. القهوة فقط.',
        note: 'الرفض بجملتين قصيرتين هو الأدب الطبيعي هنا — لا تحتاج شرحًا.',
        wrong: ['No, I am not hungry now, thank you very much.', 'No, thanks. Only coffee is enough for me.'] },
      { s: 'B', en: "That's eighteen riyals.", ar: 'ثمانية عشر ريالًا.' },
      { s: 'A', en: 'Can I pay by card?', ar: 'ممكن أدفع بالبطاقة؟',
        note: '«pay by card» / «pay in cash» — لاحظ حرف الجر مع كل واحدة.',
        wrong: ['Can I pay with the card?', 'Is it possible to pay by a card?'] },
      { s: 'B', en: "Of course. Tap here whenever you're ready.", ar: 'بالطبع. المس هنا متى ما كنت جاهزًا.' },
      { s: 'A', en: 'Thanks. How long will it take?', ar: 'شكرًا. كم سيستغرق؟',
        note: '«How long will it take?» صالحة للقهوة والطعام والصيانة وأي انتظار.',
        wrong: ['Thanks. How much time it takes?', 'Thanks. When it will be ready?'] },
      { s: 'B', en: "About five minutes. I'll call your name.", ar: 'حوالي خمس دقائق. سأنادي اسمك.' },
      { s: 'A', en: 'Perfect. Thank you.', ar: 'ممتاز. شكرًا لكِ.',
        note: 'كلمة واحدة + شكر = ختام مثالي لأي تعامل قصير.',
        wrong: ['Perfect. Thank you so much for everything.', 'Okay good. Thanks.'] },
    ],
    expressions: [
      { en: 'Could I get…, please?', ar: 'ممكن … من فضلك؟', when: 'صيغة الطلب في أي مقهى أو مطعم.' },
      { en: 'For here or to go?', ar: 'هنا أم سفري؟', when: 'سؤال سيأتيك أنت — استعدّ للإجابة، لا للسؤال.' },
      { en: 'Can I pay by card?', ar: 'ممكن أدفع بالبطاقة؟', when: 'عند الدفع في أي مكان.' },
      { en: 'How long will it take?', ar: 'كم سيستغرق؟', when: 'حين تحتاج أن تعرف مدة الانتظار.' },
    ],
  },

  {
    key: 'life-airport',
    group: 'daily',
    title_ar: 'في المطار — تسجيل الوصول',
    title_en: 'Airport check-in',
    place_ar: 'مكتب تسجيل الوصول',
    situation_ar: 'أنت أمام مكتب تسجيل الوصول، بحقيبة واحدة ورحلة إلى لندن.',
    goal_ar: 'أن تُنهي التسجيل، وتطلب مقعدًا، وتسأل عن البوابة إن لم تسمعها.',
    b_name: 'Nora', b_role_ar: 'موظفة شركة الطيران', bVoice: 'en-US-AvaNeural',
    lines: [
      { s: 'B', en: 'Good evening. Where are you flying today?', ar: 'مساء الخير. إلى أين تسافر اليوم؟' },
      { s: 'A', en: "To London. Here's my passport.", ar: 'إلى لندن. تفضّلي جواز سفري.',
        note: '«Here\'s my…» هي طريقة تسليم أي شيء لأحد. أقصر وأكثر طبيعية من «Take my passport».',
        wrong: ['To London. Take my passport.', 'London. This is my passport for you.'] },
      { s: 'B', en: 'Thank you. Are you checking any bags?', ar: 'شكرًا. هل لديك حقائب للشحن؟' },
      { s: 'A', en: 'Just one, please.', ar: 'واحدة فقط، من فضلك.',
        note: '«check a bag» = يشحن حقيبة في مخزن الأمتعة. «carry-on» = حقيبة اليد.',
        wrong: ['Only one bag with me.', 'Just one, thanks you.'] },
      { s: 'B', en: 'Could you put it on the belt?', ar: 'ممكن تضعها على السير؟' },
      { s: 'A', en: 'Sure. Is it too heavy?', ar: 'بالتأكيد. هل هي ثقيلة أكثر من اللازم؟',
        note: '«too heavy» = ثقيلة بشكل زائد عن الحد. «very heavy» تعني ثقيلة فقط — فرق مهم.',
        wrong: ['Sure. Is it very heavy?', 'Sure. It is heavy too much?'] },
      { s: 'B', en: "No, you're fine. Window or aisle?", ar: 'لا، وزنها مناسب. نافذة أم ممر؟' },
      { s: 'A', en: "Window, if that's possible.", ar: 'نافذة، إن كان ذلك ممكنًا.',
        note: '«if that\'s possible» تجعل الطلب لطيفًا وتترك لها مجالًا للاعتذار.',
        wrong: ['Window, I want window.', 'Window, if it is possible for you.'] },
      { s: 'B', en: 'Here you go. Your gate is B12, and boarding starts at 7:40.', ar: 'تفضّل. بوابتك B12، والصعود يبدأ الساعة ٧:٤٠.' },
      { s: 'A', en: 'Sorry, which gate was that?', ar: 'عذرًا، أي بوابة قلتِ؟',
        note: 'سؤال قصير جدًا لاسترجاع معلومة فاتتك. لا تخجل — الجميع يسأله في المطار.',
        wrong: ['Sorry, repeat the gate please.', 'Sorry, what is the gate was that?'] },
      { s: 'B', en: "B12. It's on the lower level.", ar: 'B12. إنها في الطابق السفلي.' },
      { s: 'A', en: 'Got it. Thank you very much.', ar: 'فهمت. شكرًا جزيلًا.',
        note: 'أكّد أنك سمعت الرقم قبل أن تنصرف. «Got it» تفعل ذلك في كلمتين.',
        wrong: ['Okay. Thank you very much.', 'Got it. Thanks for you.'] },
      { s: 'B', en: 'Have a good flight.', ar: 'رحلة سعيدة.' },
    ],
    expressions: [
      { en: "Here's my passport.", ar: 'تفضّل جواز سفري.', when: 'عند تسليم أي وثيقة أو شيء لموظف.' },
      { en: 'to check a bag', ar: 'يشحن حقيبة', when: 'الفعل الرسمي في المطار — مقابل «carry-on» لحقيبة اليد.' },
      { en: "…, if that's possible.", ar: '…، إن كان ذلك ممكنًا.', when: 'لتخفيف أي طلب: مقعد، موعد، خدمة.' },
      { en: 'Which gate was that?', ar: 'أي بوابة قلت؟', when: 'حين تفوتك معلومة مهمة وتحتاج تكرارها فورًا.' },
    ],
  },

  {
    key: 'life-doctor',
    group: 'daily',
    title_ar: 'عند الطبيب',
    title_en: 'At the doctor',
    place_ar: 'العيادة',
    situation_ar: 'ثلاثة أيام وأنت تعاني من التهاب في الحلق. دخلتَ على الطبيب الآن.',
    goal_ar: 'أن تصف الأعراض بدقة، وتفهم تعليمات الدواء قبل أن تخرج.',
    b_name: 'Dr. Hall', b_role_ar: 'الطبيب', bVoice: 'en-US-EricNeural',
    lines: [
      { s: 'B', en: 'Hello, Mosab. What brings you in today?', ar: 'أهلًا يا مصعب. ما الذي أتى بك اليوم؟' },
      { s: 'A', en: "I've had a sore throat for three days.", ar: 'لديّ التهاب في الحلق منذ ثلاثة أيام.',
        note: 'الحاضر التام مع «for» = بدأ في الماضي وما زال مستمرًا. هذه صيغة وصف الأعراض.',
        wrong: ['I have a sore throat from three days.', 'I am having sore throat since three days.'] },
      { s: 'B', en: 'Do you have a fever?', ar: 'هل لديك حرارة؟' },
      { s: 'A', en: 'A little, mostly at night.', ar: 'قليلًا، غالبًا في الليل.',
        note: 'إجابة قصيرة + وقت الحدوث. الطبيب يحتاج «متى» بقدر ما يحتاج «ماذا».',
        wrong: ['Yes, I have a small fever in the night.', 'A little, mostly in the night.'] },
      { s: 'B', en: 'Any cough?', ar: 'هل هناك سعال؟' },
      { s: 'A', en: 'Yes, a dry one.', ar: 'نعم، سعال جاف.',
        note: '«a dry one» = سعال جاف. «one» تعوّض الكلمة حتى لا تكررها.',
        wrong: ['Yes, dry cough.', 'Yes, it is a dry.'] },
      { s: 'B', en: 'Let me have a look. Open wide, please.', ar: 'دعني ألقي نظرة. افتح فمك جيدًا من فضلك.' },
      { s: 'A', en: 'Is it serious?', ar: 'هل الأمر خطير؟',
        note: '«serious» هنا تعني «خطير» لا «جاد». سؤال قصير من حقك أن تسأله.',
        wrong: ['Is it dangerous for me?', 'Is it a serious?'] },
      { s: 'B', en: "No, it's a simple infection. I'll write you something.", ar: 'لا، إنه التهاب بسيط. سأكتب لك دواءً.' },
      { s: 'A', en: 'How often should I take it?', ar: 'كم مرة يجب أن آخذه؟',
        note: '«How often» = كم مرة (تكرار). لا تخلطها بـ «How long» = كم مدة.',
        wrong: ['How much I should take it?', 'How many times I take it?'] },
      { s: 'B', en: 'Twice a day, after food, for five days.', ar: 'مرتين يوميًا، بعد الأكل، لمدة خمسة أيام.' },
      { s: 'A', en: 'Just to make sure — after food, not before?', ar: 'فقط لأتأكد — بعد الأكل، لا قبله؟',
        note: 'مع الدواء تحديدًا، أعد التعليمة بصوتك. خطأ واحد هنا يكلّفك أسبوعًا.',
        wrong: ['Okay, I understand everything.', 'Just to make sure — before food or after?'] },
      { s: 'B', en: "Correct. Come back if it's not better by Sunday.", ar: 'صحيح. ارجع إليّ إن لم يتحسّن بحلول الأحد.' },
      { s: 'A', en: 'Thank you, doctor.', ar: 'شكرًا يا دكتور.',
        note: 'في الإنجليزية تُنادى بـ «doctor» بلا اسم، وهذا مقبول تمامًا.',
        wrong: ['Thank you, mister doctor.', 'Thanks a lot, my doctor.'] },
    ],
    expressions: [
      { en: "I've had a sore throat for three days.", ar: 'لديّ التهاب في الحلق منذ ثلاثة أيام.', when: 'قالب وصف أي عرض: I\'ve had + العرض + for + المدة.' },
      { en: 'What brings you in today?', ar: 'ما الذي أتى بك اليوم؟', when: 'سيسألك الطبيب هذا — استعدّ للإجابة لا للسؤال.' },
      { en: 'How often should I take it?', ar: 'كم مرة يجب أن آخذه؟', when: 'عن تكرار الدواء. «How long?» عن مدته.' },
      { en: 'Is it serious?', ar: 'هل الأمر خطير؟', when: 'سؤال مشروع عن أي تشخيص.' },
    ],
  },

  {
    key: 'life-return',
    group: 'daily',
    title_ar: 'إرجاع منتج في المحل',
    title_en: 'Returning something to a shop',
    place_ar: 'محل إلكترونيات',
    situation_ar: 'اشتريت سمّاعة وتعطّلت بعد يومين، ومعك الفاتورة. وقفتَ عند قسم الإرجاع.',
    goal_ar: 'أن تطلب حقك بهدوء: تشرح العطل، تختار الاسترداد، وتتأكد من التفاصيل.',
    b_name: 'Ellie', b_role_ar: 'موظفة المبيعات', bVoice: 'en-US-EmmaNeural',
    lines: [
      { s: 'A', en: "Excuse me. I'd like to return this, please.", ar: 'عذرًا. أودّ إرجاع هذا من فضلك.',
        note: '«I\'d like to…» = أودّ. مهذبة وحازمة في الوقت نفسه — استعملها في كل طلب رسمي.',
        wrong: ['Excuse me. I want to give back this thing.', "Excuse me. I'd like to return this back, please."] },
      { s: 'B', en: 'Sure. Is there a problem with it?', ar: 'بالتأكيد. هل هناك مشكلة فيه؟' },
      { s: 'A', en: 'Yes, it stopped working after two days.', ar: 'نعم، توقف عن العمل بعد يومين.',
        note: '«stopped working» = تعطّل. جملة واحدة تكفي لشرح العطل.',
        wrong: ['Yes, it is broken and it does not work at all now.', 'Yes, it stopped to work after two days.'] },
      { s: 'B', en: 'Do you have the receipt?', ar: 'هل معك الفاتورة؟' },
      { s: 'A', en: 'Here it is.', ar: 'تفضّلي.',
        note: 'ثلاث كلمات تكفي عند تسليم شيء صغير. «Here it is» لشيء واحد محدد، و«Here you go» لأي شيء تسلّمه.',
        wrong: ['Yes, this is it here.', 'Here is it.'] },
      { s: 'B', en: 'Thank you. Would you like a refund or an exchange?', ar: 'شكرًا. هل تودّ استرداد المبلغ أم استبداله؟' },
      { s: 'A', en: 'A refund, please.', ar: 'استرداد المبلغ من فضلك.',
        note: '«refund» = استرداد المال. «exchange» = استبدال بمنتج آخر. كلمتان تحتاجهما كثيرًا.',
        wrong: ['My money back, please.', 'A refund for me, please.'] },
      { s: 'B', en: 'No problem. It goes back to your card in three to five days.', ar: 'لا مشكلة. سيعود إلى بطاقتك خلال ثلاثة إلى خمسة أيام.' },
      { s: 'A', en: 'Just to make sure — the same card I paid with?', ar: 'فقط لأتأكد — نفس البطاقة التي دفعت بها؟',
        note: 'التأكيد قبل المغادرة يوفّر عليك زيارة ثانية. هذه عادة، لا جملة.',
        wrong: ['Okay, no problem, thank you.', 'Just to make sure — which card you will use?'] },
      { s: 'B', en: 'Yes, exactly.', ar: 'نعم، بالضبط.' },
      { s: 'A', en: 'Great. Thank you for your help.', ar: 'ممتاز. شكرًا لكِ على المساعدة.',
        note: '«Thank you for your help» ختام مهذب لأي خدمة تلقّيتها.',
        wrong: ['Great. Thank you for your helping.', 'Great. You helped me so much today.'] },
      { s: 'B', en: "You're welcome. Have a good one.", ar: 'على الرحب. يومك سعيد.' },
    ],
    expressions: [
      { en: "I'd like to return this.", ar: 'أودّ إرجاع هذا.', when: 'افتتاح أي عملية إرجاع.' },
      { en: 'a refund / an exchange', ar: 'استرداد المبلغ / استبدال', when: 'الخياران اللذان سيُعرضان عليك — اعرف الفرق قبل أن تُسأل.' },
      { en: 'It stopped working.', ar: 'توقّف عن العمل.', when: 'لوصف عطل جهاز بأبسط صيغة صحيحة.' },
      { en: 'Here it is.', ar: 'تفضّل.', when: 'عند تسليم شيء طُلب منك.' },
    ],
  },

  {
    key: 'life-smalltalk',
    group: 'daily',
    title_ar: 'حديث خفيف مع شخص جديد',
    title_en: 'Small talk with a stranger',
    place_ar: 'ورشة عمل',
    situation_ar: 'أنت واقف في استراحة ورشة عمل، وشخص لا تعرفه بدأ الكلام معك.',
    goal_ar: 'أن تبقي الحديث حيًّا دقيقتين: تجيب، ثم تردّ السؤال، ثم تعرّف بنفسك.',
    b_name: 'Alex', b_role_ar: 'مشارك في الورشة', bVoice: 'en-US-RogerNeural',
    lines: [
      { s: 'B', en: 'Hey. Is this your first time at this workshop?', ar: 'مرحبًا. هل هذه مرتك الأولى في هذه الورشة؟' },
      { s: 'A', en: 'Yes, it is. How about you?', ar: 'نعم. وأنت؟',
        note: 'سرّ الحديث الخفيف كله: أجب، ثم أعِد السؤال عليه. «How about you?» تفعلها في ثلاث كلمات.',
        wrong: ['Yes, it is my first time here in this workshop.', 'Yes. And you what about?'] },
      { s: 'B', en: 'My third. The speaker is really good.', ar: 'مرتي الثالثة. المتحدث ممتاز فعلًا.' },
      { s: 'A', en: "That's good to know. What do you do?", ar: 'يسعدني معرفة ذلك. ماذا تعمل؟',
        note: '«What do you do?» تعني «ما عملك؟» لا «ماذا تفعل الآن؟». سؤال قياسي بين الغرباء.',
        wrong: ["That's good to know. What are you doing?", 'Good. What is your job?'] },
      { s: 'B', en: 'I work in sales. And you?', ar: 'أعمل في المبيعات. وأنت؟' },
      { s: 'A', en: "I'm still a student. Business, second year.", ar: 'ما زلت طالبًا. إدارة أعمال، السنة الثانية.',
        note: 'إجابة مختصرة بلا جمل كاملة — هذا هو إيقاع الحديث الخفيف الطبيعي.',
        wrong: ['I am still student. Business, second year.', 'I am a student until now in business college.'] },
      { s: 'B', en: "Nice. Long day, isn't it?", ar: 'جميل. يوم طويل، أليس كذلك؟' },
      { s: 'A', en: 'It is. But the coffee helps.', ar: 'بلى. لكن القهوة تساعد.',
        note: 'ردّ خفيف مع لمسة مرح يفتح الباب لبقية الحديث. لا تجب بـ «Yes» وحدها.',
        wrong: ['Yes, very long day today.', 'It is. But coffee is helping.'] },
      { s: 'B', en: "Ha, same here. I'm Alex, by the way.", ar: 'هه، وأنا كذلك. أنا أليكس، بالمناسبة.' },
      { s: 'A', en: 'Mosab. Good to meet you, Alex.', ar: 'مصعب. سعيد بلقائك يا أليكس.',
        note: 'الاسم وحده يكفي ردًّا على اسم. لا تحتاج جملة كاملة.',
        wrong: ['My name is Mosab. Good to meet you, Alex.', 'Mosab. Good to meet you too, Alex.'] },
      { s: 'B', en: "You too. Let's grab a seat before it fills up.", ar: 'وأنا كذلك. لنأخذ مقعدًا قبل أن يمتلئ المكان.' },
      { s: 'A', en: 'Good idea. After you.', ar: 'فكرة جيدة. تفضّل.',
        note: '«After you» = تفضّل قبلي. لفتة صغيرة تُحدث فرقًا كبيرًا في الانطباع.',
        wrong: ['Good idea. You first.', 'Good idea. Go before me.'] },
    ],
    expressions: [
      { en: 'How about you?', ar: 'وأنت؟', when: 'بعد أي إجابة — تُبقي الحديث متبادلًا لا استجوابًا.' },
      { en: 'What do you do?', ar: 'ماذا تعمل؟', when: 'السؤال القياسي عن عمل شخص قابلته للتو.' },
      { en: "That's good to know.", ar: 'يسعدني معرفة ذلك.', when: 'ردّ لطيف على معلومة مفيدة.' },
      { en: 'After you.', ar: 'تفضّل.', when: 'عند باب أو مقعد أو طابور — تُقال ولا تُترجم حرفيًا.' },
    ],
  },

  {
    key: 'life-directions',
    group: 'daily',
    title_ar: 'سؤال عن الطريق',
    title_en: 'Asking for directions',
    place_ar: 'في الشارع',
    situation_ar: 'أنت في مدينة لا تعرفها، وبطارية جوالك نفدت. أوقفتَ أحد المارّة لتسأله.',
    goal_ar: 'أن تسأل بأدب، تعيد ما سمعته للتأكد، وتخرج بالاتجاه الصحيح.',
    b_name: 'Sam', b_role_ar: 'أحد المارّة', bVoice: 'en-US-GuyNeural',
    lines: [
      { s: 'A', en: 'Excuse me, sorry to bother you. Do you happen to know where the train station is?', ar: 'عذرًا، أعتذر على الإزعاج. هل تعرف صدفةً أين محطة القطار؟',
        note: '«Do you happen to know…?» تُخفّف السؤال وتعطي الطرف الآخر مخرجًا إن لم يعرف.',
        wrong: ['Excuse me. Where is the train station?', 'Sorry, do you know where is the train station?'] },
      { s: 'B', en: 'Sure. Go straight for two blocks, then turn left.', ar: 'بالتأكيد. امشِ مستقيمًا مربعين سكنيين، ثم انعطف يسارًا.' },
      { s: 'A', en: 'Straight, then left. Is it far?', ar: 'مستقيمًا، ثم يسارًا. هل هي بعيدة؟',
        note: 'كرّر الاتجاه بكلمتين — هذا يثبّته في ذهنك ويصحّحه الطرف الآخر إن أخطأت.',
        wrong: ['Okay, I understand. Is it far?', 'Straight, then left. Is it far from here or no?'] },
      { s: 'B', en: 'About ten minutes on foot.', ar: 'حوالي عشر دقائق مشيًا.' },
      { s: 'A', en: "Sorry, I didn't catch that. Ten or twenty?", ar: 'عذرًا، لم أسمع جيدًا. عشر أم عشرون؟',
        note: 'ten / twenty ثم thirteen / thirty من أكثر ما يُسمع خطأً. اسأل ولا تخمّن.',
        wrong: ['Sorry, say it again please.', 'Sorry, I did not catch that. How many minutes?'] },
      { s: 'B', en: 'Ten. One-zero.', ar: 'عشر. واحد-صفر.' },
      { s: 'A', en: 'Got it. Is there a bus as well?', ar: 'فهمت. هل هناك حافلة أيضًا؟',
        note: '«as well» = أيضًا، وتأتي في آخر الجملة. مرادف لـ «too».',
        wrong: ['Got it. Is there a bus also?', 'Got it. There is a bus as well?'] },
      { s: 'B', en: 'There is, but walking is faster at this hour.', ar: 'نعم، لكن المشي أسرع في هذه الساعة.' },
      { s: 'A', en: "That's good to know. Thank you very much.", ar: 'يسعدني معرفة ذلك. شكرًا جزيلًا.',
        note: 'اشكر من ساعدك بجملة كاملة — الاختصار الزائد هنا يبدو باردًا.',
        wrong: ['Okay. Thank you very much.', "That's good to know. Thanks God."] },
      { s: 'B', en: 'No worries. Have a good one.', ar: 'ولا يهمك. يومك سعيد.' },
    ],
    expressions: [
      { en: 'Do you happen to know…?', ar: 'هل تعرف صدفةً…؟', when: 'لسؤال غريب عن شيء قد لا يعرفه — أدبها عالٍ جدًا.' },
      { en: 'Go straight, then turn left.', ar: 'امشِ مستقيمًا، ثم انعطف يسارًا.', when: 'قالب الاتجاهات — ستسمعه أكثر مما تقوله.' },
      { en: 'Is it far?', ar: 'هل هي بعيدة؟', when: 'بعد أي اتجاه، لتعرف إن كنت ستمشي أم تركب.' },
      { en: 'No worries.', ar: 'ولا يهمك.', when: 'ردّ ودود جدًا على شكر أو اعتذار.' },
    ],
  },
]

module.exports = { GROUPS, SCENARIOS, A_VOICE }
