// LEGENDARY-B5 Batch 3: Units 5-8
const { Pool } = require('pg');
const pool = new Pool({
  host: 'aws-1-eu-central-1.pooler.supabase.com', port: 5432, database: 'postgres',
  user: 'postgres.nmjexpuycmqcxuxljier', password: 'Ali-al-ahmad2000',
  ssl: { rejectUnauthorized: false }
});

async function insertBatch(client, words, unitNumber, batchId) {
  let inserted = 0;
  for (const w of words) {
    try {
      await client.query(
        `INSERT INTO public.vocab_staging_l4 (word, pos, definition_ar, example_en, example_ar, recommended_tier, cefr_level, source_list, recommended_unit, batch_id) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) ON CONFLICT (word) DO NOTHING`,
        [w[0], w[1], w[2], w[3], w[4], w[5], w[6], w[7], unitNumber, batchId]
      );
      inserted++;
    } catch(e) { console.error(`Error "${w[0]}":`, e.message); }
  }
  return inserted;
}

// Unit 5 - Human Migration
const U5 = [
  ['migration','noun','هجرة','Global migration patterns have changed dramatically in the last century.','تغيرت أنماط الهجرة العالمية بشكل كبير في القرن الماضي.','core','B2','CEFR-J'],
  ['refugee','noun','لاجئ','Millions of refugees have fled conflict zones seeking safety abroad.','فرّ ملايين اللاجئين من مناطق النزاع بحثاً عن الأمان في الخارج.','core','B2','CEFR-J'],
  ['asylum','noun','لجوء','Political asylum protects individuals fleeing persecution in their homeland.','يحمي اللجوء السياسي الأفراد الفارين من الاضطهاد في وطنهم.','core','B2','CEFR-J'],
  ['immigrant','noun','مهاجر','First-generation immigrants often face significant cultural adjustment challenges.','غالباً ما يواجه المهاجرون من الجيل الأول تحديات تكيّف ثقافي كبيرة.','core','B2','CEFR-J'],
  ['emigrate','verb','يهاجر (من بلده)','Economic hardship forced many skilled workers to emigrate overseas.','أجبرت الصعوبات الاقتصادية كثيراً من العمال المهرة على الهجرة للخارج.','core','B2','CEFR-J'],
  ['citizenship','noun','جنسية / مواطنة','Obtaining citizenship in a new country can take several years.','قد يستغرق الحصول على الجنسية في بلد جديد عدة سنوات.','core','B2','CEFR-J'],
  ['displacement','noun','تهجير / نزوح','War and natural disasters are major causes of population displacement.','الحرب والكوارث الطبيعية أسباب رئيسية لتهجير السكان.','core','B2','AWL'],
  ['border','noun','حدود','Thousands of people attempt to cross the border every day.','يحاول آلاف الأشخاص عبور الحدود كل يوم.','core','B1','CEFR-J'],
  ['passport','noun','جواز سفر','A valid passport is required for international travel.','يُشترط جواز سفر صالح للسفر الدولي.','core','B1','CEFR-J'],
  ['visa','noun','تأشيرة','The work visa allows skilled professionals to live abroad temporarily.','تسمح تأشيرة العمل للمهنيين المهرة بالعيش في الخارج مؤقتاً.','core','B2','CEFR-J'],
  ['integration','noun','اندماج','Successful integration requires effort from both newcomers and host communities.','يتطلب الاندماج الناجح جهداً من القادمين الجدد والمجتمعات المضيفة.','core','B2','AWL'],
  ['assimilation','noun','استيعاب / انصهار','Cultural assimilation often occurs gradually across multiple generations.','يحدث الاستيعاب الثقافي عادةً تدريجياً عبر أجيال متعددة.','extended','B2','AWL'],
  ['deportation','noun','ترحيل','Deportation proceedings can separate families who have lived together.','يمكن لإجراءات الترحيل تفريق عائلات عاشت معاً.','extended','B2','CEFR-J'],
  ['persecution','noun','اضطهاد','Religious persecution remains a common reason for seeking asylum.','لا يزال الاضطهاد الديني سبباً شائعاً لطلب اللجوء.','core','B2','CEFR-J'],
  ['repatriation','noun','إعادة إلى الوطن','Voluntary repatriation programs help refugees return home safely.','تُساعد برامج الإعادة الطوعية اللاجئين على العودة لوطنهم بأمان.','extended','C1','CEFR-J'],
  ['diaspora','noun','شتات','The Palestinian diaspora extends across many countries worldwide.','يمتد الشتات الفلسطيني عبر دول كثيرة حول العالم.','extended','C1','CEFR-J'],
  ['nomad','noun','رحّال / بدوي','Digital nomads work remotely while traveling across different countries.','يعمل الرحّالة الرقميون عن بُعد أثناء التنقل بين دول مختلفة.','core','B2','CEFR-J'],
  ['settlement','noun','مستوطنة / استقرار','Early human settlement patterns followed access to water sources.','اتبعت أنماط الاستقرار البشري المبكر الوصول لمصادر المياه.','core','B2','CEFR-J'],
  ['urbanization','noun','تحضّر','Rapid urbanization draws millions from rural areas to cities.','يجذب التحضّر السريع ملايين من المناطق الريفية إلى المدن.','core','B2','NAWL'],
  ['demographic','adjective','ديموغرافي / سكاني','Demographic changes affect labor markets and social services.','تؤثر التغيرات الديموغرافية على أسواق العمل والخدمات الاجتماعية.','extended','B2','AWL'],
  ['multicultural','adjective','متعدد الثقافات','Multicultural societies benefit from diverse perspectives and skills.','تستفيد المجتمعات متعددة الثقافات من وجهات نظر ومهارات متنوعة.','core','B2','CEFR-J'],
  ['indigenous','adjective','أصلي / سكان أصليون','Indigenous communities have a special connection to their ancestral lands.','للمجتمعات الأصلية ارتباط خاص بأراضيهم التاريخية.','extended','B2','AWL'],
  ['humanitarian','adjective','إنساني','Humanitarian organizations provide essential aid to displaced populations.','تُقدّم المنظمات الإنسانية مساعدات أساسية للسكان النازحين.','core','B2','CEFR-J'],
  ['undocumented','adjective','غير موثّق / بدون أوراق','Undocumented migrants often face exploitation and limited legal rights.','غالباً ما يواجه المهاجرون غير الموثقين الاستغلال وحقوقاً قانونية محدودة.','extended','B2','CEFR-J'],
  ['stateless','adjective','عديم الجنسية','Stateless individuals lack the legal protection of any country.','يفتقر الأفراد عديمو الجنسية لحماية قانونية من أي دولة.','extended','C1','CEFR-J'],
  ['xenophobia','noun','كراهية الأجانب','Xenophobia can increase during periods of economic uncertainty.','يمكن أن تزداد كراهية الأجانب خلال فترات عدم اليقين الاقتصادي.','extended','C1','CEFR-J'],
  ['remittance','noun','حوالة مالية','Remittances from workers abroad significantly boost developing economies.','تُعزز الحوالات المالية من العاملين بالخارج اقتصادات الدول النامية بشكل كبير.','extended','C1','NAWL'],
  ['expatriate','noun','مغترب','Many expatriates maintain strong ties with their country of origin.','يحافظ كثير من المغتربين على روابط قوية مع بلدهم الأصلي.','extended','B2','CEFR-J'],
  ['naturalization','noun','تجنيس','The naturalization process varies greatly between different countries.','تختلف عملية التجنيس بشكل كبير بين الدول المختلفة.','extended','C1','CEFR-J'],
  ['trafficking','noun','اتجار (بالبشر)','Human trafficking is a serious crime that exploits vulnerable people.','الاتجار بالبشر جريمة خطيرة تستغل الأشخاص الضعفاء.','core','B2','CEFR-J'],
  ['acculturation','noun','تثاقف / تبادل ثقافي','Acculturation is the gradual adoption of the customs of another culture.','التثاقف هو التبنّي التدريجي لعادات ثقافة أخرى.','mastery','C1','AWL'],
  ['assimilate','verb','يندمج / يستوعب','Second-generation immigrants tend to assimilate more readily.','يميل المهاجرون من الجيل الثاني للاندماج بسهولة أكبر.','extended','B2','AWL'],
  ['relocate','verb','ينتقل / يُعيد التوطين','The company offered to relocate employees to its new headquarters.','عرضت الشركة نقل الموظفين إلى مقرها الجديد.','core','B2','AWL'],
  ['detain','verb','يحتجز','Authorities can detain asylum seekers pending review of their cases.','يمكن للسلطات احتجاز طالبي اللجوء بانتظار مراجعة حالاتهم.','extended','B2','CEFR-J'],
  ['marginalize','verb','يُهمّش','Migrant communities are often marginalized in their host countries.','غالباً ما تُهمّش مجتمعات المهاجرين في بلدان إقامتهم.','extended','B2','NAWL'],
  ['exploit','verb','يستغل','Unscrupulous employers sometimes exploit undocumented workers.','يستغل أصحاب العمل عديمو الضمير أحياناً العمال غير الموثقين.','core','B2','AWL'],
  ['segregate','verb','يفصل / يعزل','History shows the harm caused by policies that segregate communities.','يُظهر التاريخ الضرر الناجم عن سياسات فصل المجتمعات.','extended','C1','AWL'],
  ['repatriate','verb','يُعيد إلى الوطن','International programs help repatriate refugees when conflicts end.','تُساعد البرامج الدولية في إعادة اللاجئين لأوطانهم عند انتهاء النزاعات.','extended','C1','CEFR-J'],
  ['petition','verb','يلتمس / يطلب رسمياً','Immigrants can petition for family members to join them.','يمكن للمهاجرين تقديم التماس لأفراد عائلاتهم للانضمام إليهم.','extended','B2','CEFR-J'],
  ['tolerance','noun','تسامح','Cultural tolerance is essential for peaceful multicultural societies.','التسامح الثقافي ضروري لمجتمعات متعددة الثقافات سلمية.','core','B2','CEFR-J'],
  ['diversity','noun','تنوع','Immigration increases cultural diversity and enriches society.','تزيد الهجرة التنوع الثقافي وتُثري المجتمع.','core','B2','AWL'],
  ['prejudice','noun','تحيّز / تعصب','Prejudice against immigrants often stems from fear and misinformation.','غالباً ما ينبع التحيّز ضد المهاجرين من الخوف والمعلومات المضللة.','core','B2','CEFR-J'],
  ['discrimination','noun','تمييز','Anti-discrimination laws protect immigrants from unfair treatment.','تحمي قوانين مكافحة التمييز المهاجرين من المعاملة غير العادلة.','core','B2','AWL'],
  ['heritage','noun','تراث / إرث','Immigrants often work hard to preserve their cultural heritage.','غالباً ما يعمل المهاجرون بجد للحفاظ على تراثهم الثقافي.','core','B2','CEFR-J'],
  ['bilingual','adjective','ثنائي اللغة','Bilingual education helps immigrant children succeed academically.','يُساعد التعليم ثنائي اللغة أطفال المهاجرين على النجاح أكاديمياً.','core','B2','CEFR-J'],
  ['sovereignty','noun','سيادة','Nations assert their sovereignty over immigration policy decisions.','تؤكد الدول سيادتها على قرارات سياسة الهجرة.','extended','C1','AWL'],
  ['geopolitical','adjective','جيوسياسي','Geopolitical instability is a major driver of forced migration.','عدم الاستقرار الجيوسياسي محرّك رئيسي للهجرة القسرية.','extended','C1','NAWL'],
  ['amnesty','noun','عفو عام','Some countries offer amnesty to long-term undocumented residents.','تُقدّم بعض الدول عفواً عاماً للمقيمين غير الموثقين على المدى الطويل.','extended','C1','CEFR-J'],
  ['quota','noun','حصة','Immigration quotas limit the number of newcomers from each country.','تُحدّد حصص الهجرة عدد القادمين الجدد من كل بلد.','extended','B2','AWL'],
  ['sanctuary','noun','ملاذ آمن','Some cities declare themselves sanctuary zones for undocumented immigrants.','تُعلن بعض المدن نفسها مناطق ملاذ آمن للمهاجرين غير الموثقين.','extended','B2','CEFR-J'],
  ['detention','noun','احتجاز','Immigration detention centers have been criticized for poor conditions.','انتُقدت مراكز احتجاز المهاجرين بسبب الظروف السيئة.','extended','B2','AWL'],
  ['census','noun','إحصاء سكاني','The national census tracks population changes including migration patterns.','يتتبع الإحصاء السكاني الوطني التغيرات السكانية بما فيها أنماط الهجرة.','extended','B2','CEFR-J'],
  ['residency','noun','إقامة','Permanent residency grants immigrants most rights of citizenship.','تمنح الإقامة الدائمة المهاجرين معظم حقوق المواطنة.','core','B2','CEFR-J'],
  ['livelihood','noun','مصدر رزق','Climate change threatens the livelihoods of farming communities.','يُهدد تغير المناخ مصادر رزق المجتمعات الزراعية.','core','B2','CEFR-J'],
  ['resettlement','noun','إعادة توطين','Refugee resettlement programs help families rebuild their lives.','تُساعد برامج إعادة التوطين العائلات في إعادة بناء حياتها.','extended','B2','CEFR-J'],
  ['corridor','noun','ممر / معبر','Major migration corridors connect developing regions to wealthy nations.','تربط ممرات الهجرة الرئيسية المناطق النامية بالدول الغنية.','extended','B2','CEFR-J'],
  ['influx','noun','تدفق','The sudden influx of refugees strained local resources.','أرهق التدفق المفاجئ للاجئين الموارد المحلية.','extended','B2','CEFR-J'],
  ['exodus','noun','نزوح جماعي','The civil war triggered a mass exodus from the country.','أطلقت الحرب الأهلية نزوحاً جماعياً من البلاد.','extended','C1','CEFR-J'],
  ['clandestine','adjective','سري / خفي','Clandestine border crossings put migrants at extreme risk.','يُعرّض عبور الحدود السري المهاجرين لخطر شديد.','mastery','C1','CEFR-J'],
  ['cosmopolitan','adjective','عالمي / متعدد الثقافات','Major cities have become increasingly cosmopolitan through migration.','أصبحت المدن الكبرى متعددة الثقافات بشكل متزايد بفعل الهجرة.','extended','B2','CEFR-J'],
  ['transient','adjective','عابر / مؤقت','Seasonal workers form a transient population in agricultural regions.','يُشكّل العمال الموسميون سكاناً عابرين في المناطق الزراعية.','extended','C1','CEFR-J'],
  ['bureaucracy','noun','بيروقراطية','Immigration bureaucracy can be overwhelming for new applicants.','يمكن أن تكون بيروقراطية الهجرة مُرهقة للمتقدمين الجدد.','core','B2','CEFR-J'],
  ['authorization','noun','تصريح / إذن','Work authorization must be renewed annually for temporary residents.','يجب تجديد تصريح العمل سنوياً للمقيمين المؤقتين.','core','B2','AWL'],
  ['bilateral','adjective','ثنائي','Bilateral agreements between countries facilitate legal migration.','تُسهّل الاتفاقيات الثنائية بين الدول الهجرة القانونية.','extended','B2','AWL'],
  ['upheaval','noun','اضطراب / انقلاب','Political upheaval often triggers waves of mass migration.','غالباً ما يُطلق الاضطراب السياسي موجات هجرة جماعية.','extended','C1','CEFR-J'],
  ['sanctuary','noun','حرم آمن','Churches historically served as sanctuary for people fleeing danger.','خدمت الكنائس تاريخياً كحرم آمن للأشخاص الفارين من الخطر.','extended','B2','CEFR-J'],
  ['persecution','noun','اضطهاد','Many seek asylum due to religious or political persecution.','يطلب كثيرون اللجوء بسبب الاضطهاد الديني أو السياسي.','core','B2','CEFR-J'],
  ['assimilation','noun','انصهار ثقافي','Forced assimilation policies have been widely criticized by historians.','انتُقدت سياسات الانصهار القسري على نطاق واسع من قبل المؤرخين.','extended','B2','AWL'],
  ['itinerant','adjective','متجوّل','Itinerant workers follow seasonal employment across different regions.','يتبع العمال المتجولون التوظيف الموسمي عبر مناطق مختلفة.','mastery','C1','CEFR-J'],
  ['nomadic','adjective','بدوي / رحّال','Nomadic traditions are disappearing as modern borders restrict movement.','تختفي التقاليد البدوية مع تقييد الحدود الحديثة للحركة.','extended','B2','CEFR-J'],
  ['enclave','noun','جيب / منطقة معزولة','Immigrant enclaves preserve cultural traditions in foreign cities.','تحافظ الجيوب المهاجرة على التقاليد الثقافية في المدن الأجنبية.','mastery','C1','CEFR-J'],
  ['populism','noun','شعبوية','Anti-immigration populism has gained support in several Western nations.','اكتسبت الشعبوية المناهضة للهجرة دعماً في عدة دول غربية.','mastery','C1','NAWL'],
  ['assimilate','verb','يندمج','New arrivals gradually assimilate into the local cultural environment.','يندمج القادمون الجدد تدريجياً في البيئة الثقافية المحلية.','extended','B2','AWL'],
  ['emigration','noun','هجرة (من البلد)','Mass emigration from rural areas has depopulated many villages.','أدت الهجرة الجماعية من المناطق الريفية إلى إخلاء قرى كثيرة.','core','B2','CEFR-J'],
  ['immigration','noun','هجرة (إلى البلد)','Immigration policy debates dominate political discussions in many countries.','تسيطر نقاشات سياسة الهجرة على المناقشات السياسية في دول كثيرة.','core','B2','CEFR-J'],
  ['overpopulation','noun','اكتظاظ سكاني','Overpopulation in urban centers creates housing and infrastructure challenges.','يخلق الاكتظاظ السكاني في المراكز الحضرية تحديات إسكان وبنية تحتية.','extended','B2','CEFR-J'],
  ['legislation','noun','تشريع','New immigration legislation aims to attract skilled foreign workers.','يهدف تشريع الهجرة الجديد إلى جذب العمال الأجانب المهرة.','core','B2','AWL'],
  ['testimony','noun','شهادة','The refugee gave powerful testimony about conditions in her homeland.','أدلت اللاجئة بشهادة مؤثرة عن الأوضاع في وطنها.','extended','B2','CEFR-J'],
  ['hardship','noun','مشقة / عسر','Many migrants endure incredible hardship during their journey.','يتحمل كثير من المهاجرين مشقة لا تصدق خلال رحلتهم.','core','B2','CEFR-J'],
  ['reunification','noun','لمّ شمل','Family reunification is a key goal for many immigration policies.','لمّ شمل العائلة هدف رئيسي لكثير من سياسات الهجرة.','extended','C1','CEFR-J'],
  ['allegiance','noun','ولاء','New citizens pledge allegiance to the constitution of their adopted country.','يتعهد المواطنون الجدد بالولاء لدستور بلدهم المُتبنّى.','mastery','C1','CEFR-J'],
  ['fraternity','noun','أخوّة','The spirit of human fraternity should guide our treatment of migrants.','يجب أن توجّه روح الأخوّة الإنسانية معاملتنا للمهاجرين.','mastery','C1','CEFR-J'],
];

// Unit 6 - Cryptocurrency
const U6 = [
  ['cryptocurrency','noun','عملة رقمية مشفرة','Cryptocurrency has transformed the way people think about money.','حوّلت العملة الرقمية المشفرة الطريقة التي يفكر بها الناس في المال.','core','B2','CEFR-J'],
  ['blockchain','noun','سلسلة كتل','Blockchain technology ensures secure and transparent digital transactions.','تضمن تقنية سلسلة الكتل معاملات رقمية آمنة وشفافة.','core','B2','CEFR-J'],
  ['transaction','noun','معاملة / صفقة','Each cryptocurrency transaction is recorded permanently on the blockchain.','تُسجّل كل معاملة عملة رقمية بشكل دائم على سلسلة الكتل.','core','B2','CEFR-J'],
  ['currency','noun','عملة','Digital currency operates independently of traditional banking systems.','تعمل العملة الرقمية بشكل مستقل عن الأنظمة المصرفية التقليدية.','core','B1','CEFR-J'],
  ['investment','noun','استثمار','Cryptocurrency investment carries significant risk due to price volatility.','يحمل الاستثمار في العملات الرقمية مخاطر كبيرة بسبب تقلب الأسعار.','core','B2','AWL'],
  ['wallet','noun','محفظة (رقمية)','A digital wallet stores the private keys for your cryptocurrency.','تُخزّن المحفظة الرقمية المفاتيح الخاصة لعملتك الرقمية.','core','B2','CEFR-J'],
  ['encryption','noun','تشفير','Strong encryption protects digital currency from unauthorized access.','يحمي التشفير القوي العملة الرقمية من الوصول غير المصرح به.','core','B2','CEFR-J'],
  ['decentralized','adjective','لامركزي','Bitcoin operates on a decentralized network without any central authority.','يعمل البيتكوين على شبكة لامركزية بدون أي سلطة مركزية.','core','B2','AWL'],
  ['volatile','adjective','متقلب','Cryptocurrency markets are notoriously volatile and unpredictable.','أسواق العملات الرقمية متقلبة وغير متوقعة بشكل ملحوظ.','core','B2','CEFR-J'],
  ['anonymous','adjective','مجهول الهوية','Some cryptocurrencies offer nearly anonymous transaction capabilities.','توفر بعض العملات الرقمية قدرات معاملات شبه مجهولة الهوية.','core','B2','CEFR-J'],
  ['ledger','noun','سجل / دفتر حسابات','The blockchain acts as a public ledger recording all transactions.','تعمل سلسلة الكتل كسجل عام يُوثّق جميع المعاملات.','core','B2','CEFR-J'],
  ['token','noun','رمز / توكن','Companies issue digital tokens to raise funds for new projects.','تُصدر الشركات رموزاً رقمية لجمع أموال لمشاريع جديدة.','core','B2','CEFR-J'],
  ['mining','noun','تعدين (رقمي)','Cryptocurrency mining requires enormous amounts of electrical energy.','يتطلب تعدين العملات الرقمية كميات هائلة من الطاقة الكهربائية.','core','B2','CEFR-J'],
  ['speculation','noun','مضاربة','Much of the cryptocurrency market is driven by speculation.','كثير من سوق العملات الرقمية مدفوع بالمضاربة.','core','B2','CEFR-J'],
  ['regulate','verb','يُنظّم','Governments worldwide are struggling to regulate cryptocurrency markets.','تكافح الحكومات حول العالم لتنظيم أسواق العملات الرقمية.','core','B2','AWL'],
  ['fluctuate','verb','يتذبذب / يتقلب','Bitcoin prices fluctuate dramatically from day to day.','تتذبذب أسعار البيتكوين بشكل كبير من يوم لآخر.','core','B2','AWL'],
  ['verify','verb','يتحقق / يُصادق','Miners verify transactions by solving complex mathematical problems.','يتحقق المعدّنون من المعاملات بحل مسائل رياضية معقدة.','core','B2','CEFR-J'],
  ['convert','verb','يحوّل','You can convert cryptocurrency to traditional money through exchanges.','يمكنك تحويل العملة الرقمية إلى أموال تقليدية عبر البورصات.','core','B1','AWL'],
  ['fraud','noun','احتيال','Cryptocurrency fraud has cost investors billions of dollars worldwide.','كلّف الاحتيال بالعملات الرقمية المستثمرين مليارات الدولارات عالمياً.','core','B2','CEFR-J'],
  ['transparency','noun','شفافية','Blockchain technology promotes financial transparency and accountability.','تُعزز تقنية سلسلة الكتل الشفافية المالية والمساءلة.','core','B2','AWL'],
  ['portfolio','noun','محفظة استثمارية','Financial advisors recommend including some cryptocurrency in a portfolio.','ينصح المستشارون الماليون بتضمين بعض العملات الرقمية في المحفظة.','core','B2','CEFR-J'],
  ['asset','noun','أصل (مالي)','Cryptocurrency is increasingly recognized as a legitimate digital asset.','تُعترف بالعملة الرقمية بشكل متزايد كأصل رقمي شرعي.','core','B2','AWL'],
  ['inflation','noun','تضخم','Some view cryptocurrency as protection against traditional currency inflation.','يرى البعض العملة الرقمية كحماية ضد تضخم العملة التقليدية.','core','B2','AWL'],
  ['protocol','noun','بروتوكول','Each cryptocurrency operates according to its own unique protocol.','تعمل كل عملة رقمية وفقاً لبروتوكولها الفريد.','core','B2','AWL'],
  ['algorithm','noun','خوارزمية','Complex algorithms secure the cryptocurrency network from attacks.','تحمي خوارزميات معقدة شبكة العملات الرقمية من الهجمات.','core','B2','NAWL'],
  ['consensus','noun','إجماع / توافق','The network reaches consensus on valid transactions automatically.','تصل الشبكة إلى إجماع على المعاملات الصالحة تلقائياً.','extended','B2','AWL'],
  ['liquidity','noun','سيولة','Major cryptocurrencies have much higher liquidity than smaller ones.','تتمتع العملات الرقمية الكبرى بسيولة أعلى بكثير من الصغيرة.','extended','C1','NAWL'],
  ['intermediary','noun','وسيط','Cryptocurrency eliminates the need for financial intermediaries.','تُلغي العملة الرقمية الحاجة للوسطاء الماليين.','extended','B2','AWL'],
  ['capitalization','noun','رسملة','The total market capitalization of cryptocurrencies exceeds two trillion.','تتجاوز القيمة السوقية الإجمالية للعملات الرقمية تريليوني دولار.','extended','B2','NAWL'],
  ['stablecoin','noun','عملة مستقرة','Stablecoins maintain a fixed value tied to traditional currencies.','تُحافظ العملات المستقرة على قيمة ثابتة مرتبطة بالعملات التقليدية.','extended','B2','CEFR-J'],
  ['scalability','noun','قابلية التوسع','Scalability remains one of the biggest challenges for blockchain technology.','تظل قابلية التوسع من أكبر التحديات لتقنية سلسلة الكتل.','extended','C1','NAWL'],
  ['hash','noun','تجزئة / هاش','Each block contains a unique hash that links it to the previous block.','يحتوي كل كتلة على تجزئة فريدة تربطها بالكتلة السابقة.','extended','B2','CEFR-J'],
  ['node','noun','عقدة','Thousands of nodes around the world maintain copies of the blockchain.','تحتفظ آلاف العقد حول العالم بنسخ من سلسلة الكتل.','extended','B2','CEFR-J'],
  ['peer-to-peer','adjective','نظير لنظير','Cryptocurrency enables peer-to-peer transactions without banks.','تُمكّن العملة الرقمية من المعاملات نظير لنظير بدون بنوك.','core','B2','CEFR-J'],
  ['yield','noun','عائد','Staking cryptocurrency can generate passive yield for investors.','يمكن لتخزين العملات الرقمية توليد عائد سلبي للمستثمرين.','extended','B2','AWL'],
  ['audit','noun','تدقيق','Regular security audits help protect cryptocurrency exchanges from hacking.','تُساعد عمليات التدقيق الأمني المنتظمة في حماية بورصات العملات الرقمية.','extended','B2','AWL'],
  ['compliance','noun','امتثال','Cryptocurrency companies must ensure compliance with financial regulations.','يجب على شركات العملات الرقمية ضمان الامتثال للوائح المالية.','extended','B2','AWL'],
  ['derivative','noun','مشتق مالي','Cryptocurrency derivatives allow investors to bet on future prices.','تسمح المشتقات المالية للعملات الرقمية للمستثمرين بالمراهنة على الأسعار.','mastery','C1','AWL'],
  ['fiduciary','adjective','ائتماني','Traditional financial systems rely on fiduciary trust in institutions.','تعتمد الأنظمة المالية التقليدية على الثقة الائتمانية بالمؤسسات.','mastery','C1','NAWL'],
  ['leverage','noun','رافعة مالية','Trading with leverage amplifies both potential profits and losses.','يُضخّم التداول بالرافعة المالية كلاً من الأرباح والخسائر المحتملة.','extended','B2','AWL'],
  ['depreciation','noun','انخفاض القيمة','Rapid depreciation of cryptocurrency can wipe out investments overnight.','يمكن للانخفاض السريع في قيمة العملة الرقمية محو الاستثمارات بين عشية وضحاها.','extended','B2','AWL'],
  ['arbitrage','noun','مراجحة','Traders profit from arbitrage by exploiting price differences across exchanges.','يربح المتداولون من المراجحة باستغلال فروق الأسعار عبر البورصات.','mastery','C1','NAWL'],
  ['smart contract','noun','عقد ذكي','Smart contracts automatically execute when predetermined conditions are met.','تُنفّذ العقود الذكية تلقائياً عند استيفاء شروط محددة مسبقاً.','core','B2','CEFR-J'],
  ['decryption','noun','فك التشفير','Decryption is the process of converting coded data back to readable form.','فك التشفير هو عملية تحويل البيانات المشفرة إلى صيغة قابلة للقراءة.','extended','B2','CEFR-J'],
  ['cybersecurity','noun','أمن سيبراني','Cybersecurity threats are the greatest risk to cryptocurrency holders.','تهديدات الأمن السيبراني هي أكبر خطر على حاملي العملات الرقمية.','core','B2','CEFR-J'],
  ['authentication','noun','مصادقة / توثيق','Two-factor authentication adds an extra layer of security to accounts.','تُضيف المصادقة الثنائية طبقة أمان إضافية للحسابات.','core','B2','NAWL'],
  ['fiscal','adjective','مالي / ضريبي','Governments must develop fiscal policies for taxing cryptocurrency gains.','يجب على الحكومات تطوير سياسات مالية لفرض ضرائب على مكاسب العملات الرقمية.','extended','B2','AWL'],
  ['monetary','adjective','نقدي','Cryptocurrency challenges traditional monetary systems worldwide.','تتحدى العملات الرقمية الأنظمة النقدية التقليدية عالمياً.','core','B2','AWL'],
  ['subsidiary','noun','فرعي / تابع','The tech company created a subsidiary dedicated to blockchain research.','أنشأت شركة التكنولوجيا فرعاً مخصصاً لأبحاث سلسلة الكتل.','extended','B2','AWL'],
  ['deficit','noun','عجز','Some economists argue cryptocurrency could help reduce national deficits.','يُجادل بعض الاقتصاديين بأن العملة الرقمية يمكن أن تُساعد في تقليل العجز الوطني.','extended','B2','AWL'],
  ['commodity','noun','سلعة','Bitcoin is increasingly treated as a commodity similar to gold.','يُعامل البيتكوين بشكل متزايد كسلعة مشابهة للذهب.','core','B2','AWL'],
  ['anonymous','adjective','مجهول','Some privacy coins offer completely anonymous financial transactions.','توفر بعض عملات الخصوصية معاملات مالية مجهولة تماماً.','core','B2','CEFR-J'],
  ['altcoin','noun','عملة بديلة','Thousands of altcoins have emerged since Bitcoin was first created.','ظهرت آلاف العملات البديلة منذ إنشاء البيتكوين لأول مرة.','extended','B2','CEFR-J'],
  ['fork','noun','تفرّع','A blockchain fork creates two separate versions of the transaction history.','يُنشئ تفرّع سلسلة الكتل نسختين منفصلتين من سجل المعاملات.','extended','C1','CEFR-J'],
  ['immutable','adjective','غير قابل للتغيير','Blockchain records are designed to be completely immutable.','صُممت سجلات سلسلة الكتل لتكون غير قابلة للتغيير تماماً.','mastery','C1','CEFR-J'],
  ['deflationary','adjective','انكماشي','Bitcoin limited supply makes it a deflationary asset over time.','يجعل العرض المحدود للبيتكوين منه أصلاً انكماشياً بمرور الوقت.','mastery','C1','CEFR-J'],
  ['fungible','adjective','قابل للاستبدال','Each Bitcoin is fungible meaning one is interchangeable with another.','كل بيتكوين قابل للاستبدال بمعنى أنه يمكن تبديل واحد بآخر.','mastery','C1','NAWL'],
  ['custodial','adjective','حفظي / وصائي','Custodial wallets store your cryptocurrency on behalf of the exchange.','تُخزّن المحافظ الحفظية عملتك الرقمية نيابة عن البورصة.','mastery','C1','CEFR-J'],
  ['interoperability','noun','قابلية التشغيل البيني','Interoperability between blockchains would allow seamless asset transfers.','ستسمح قابلية التشغيل البيني بين سلاسل الكتل بنقل أصول سلس.','mastery','C1','NAWL'],
  ['tokenize','verb','يُرمّز / يحوّل لرمز','Companies can tokenize real assets like property on the blockchain.','يمكن للشركات ترميز أصول حقيقية كالعقارات على سلسلة الكتل.','extended','C1','CEFR-J'],
  ['decentralize','verb','يُلامركز','The goal is to decentralize financial systems away from banks.','الهدف هو لامركزة الأنظمة المالية بعيداً عن البنوك.','extended','B2','AWL'],
  ['speculate','verb','يضارب','Investors speculate on cryptocurrency prices hoping for quick profits.','يُضارب المستثمرون على أسعار العملات الرقمية أملاً في أرباح سريعة.','core','B2','CEFR-J'],
  ['launder','verb','يغسل (أموال)','Criminals sometimes attempt to launder money through cryptocurrency.','يحاول المجرمون أحياناً غسل الأموال من خلال العملات الرقمية.','extended','C1','CEFR-J'],
  ['denominate','verb','يُقوّم (بعملة)','Contracts can be denominated in cryptocurrency rather than dollars.','يمكن تقويم العقود بالعملة الرقمية بدلاً من الدولارات.','mastery','C1','AWL'],
  ['proliferation','noun','انتشار','The proliferation of cryptocurrencies has created a complex market.','خلق انتشار العملات الرقمية سوقاً معقدة.','extended','C1','AWL'],
  ['sovereignty','noun','سيادة','Digital currencies may challenge the monetary sovereignty of nations.','قد تتحدى العملات الرقمية السيادة النقدية للدول.','extended','C1','AWL'],
  ['scam','noun','احتيال / نصب','Cryptocurrency scams have become increasingly sophisticated and common.','أصبحت عمليات احتيال العملات الرقمية أكثر تعقيداً وانتشاراً.','core','B2','CEFR-J'],
  ['decentralization','noun','لامركزية','Decentralization is the core principle behind blockchain technology.','اللامركزية هي المبدأ الأساسي وراء تقنية سلسلة الكتل.','extended','B2','AWL'],
  ['volatility','noun','تقلب','Extreme volatility makes cryptocurrency unsuitable for daily transactions.','يجعل التقلب الشديد العملات الرقمية غير مناسبة للمعاملات اليومية.','core','B2','CEFR-J'],
  ['portfolio','noun','حافظة استثمار','Diversifying your crypto portfolio reduces overall investment risk.','يُقلل تنويع حافظة العملات الرقمية من مخاطر الاستثمار الإجمالية.','core','B2','CEFR-J'],
];

// Unit 7 - Crowd Psychology
const U7 = [
  ['psychology','noun','علم النفس','Social psychology studies how people behave in group settings.','يدرس علم النفس الاجتماعي كيف يتصرف الناس في بيئات جماعية.','core','B2','CEFR-J'],
  ['behavior','noun','سلوك','Crowd behavior can be surprisingly different from individual actions.','يمكن أن يكون سلوك الحشود مختلفاً بشكل مدهش عن التصرفات الفردية.','core','B1','CEFR-J'],
  ['influence','noun','تأثير','Social media has enormous influence on collective human behavior.','لوسائل التواصل الاجتماعي تأثير هائل على السلوك البشري الجماعي.','core','B2','CEFR-J'],
  ['mob','noun','حشد / غوغاء','A peaceful protest can quickly transform into an uncontrollable mob.','يمكن أن يتحول الاحتجاج السلمي بسرعة إلى غوغاء لا يمكن السيطرة عليها.','core','B2','CEFR-J'],
  ['conformity','noun','امتثال / انسياق','Social conformity pressures individuals to adopt group opinions.','يضغط الامتثال الاجتماعي على الأفراد لتبني آراء المجموعة.','core','B2','AWL'],
  ['perception','noun','إدراك / تصوّر','Group perception can distort how individuals evaluate situations.','يمكن لإدراك المجموعة تشويه كيفية تقييم الأفراد للمواقف.','core','B2','CEFR-J'],
  ['stimulus','noun','محفّز / مثير','A single stimulus can trigger a chain reaction in a crowd.','يمكن لمحفّز واحد إطلاق تفاعل متسلسل في الحشد.','extended','B2','AWL'],
  ['anxiety','noun','قلق','Social anxiety prevents many people from speaking in public.','يمنع القلق الاجتماعي كثيراً من الناس من التحدث أمام العامة.','core','B2','CEFR-J'],
  ['empathy','noun','تعاطف','Empathy helps us understand the emotions and experiences of others.','يساعدنا التعاطف على فهم مشاعر وتجارب الآخرين.','core','B2','CEFR-J'],
  ['bias','noun','تحيّز','Confirmation bias causes people to seek information supporting their views.','يدفع التحيز التأكيدي الناس للبحث عن معلومات تدعم وجهات نظرهم.','core','B2','AWL'],
  ['manipulation','noun','تلاعب','Political manipulation of crowds has been documented throughout history.','وُثّق التلاعب السياسي بالجماهير عبر التاريخ.','core','B2','CEFR-J'],
  ['propaganda','noun','دعاية','Propaganda techniques exploit crowd psychology to spread specific messages.','تستغل تقنيات الدعاية علم نفس الجماهير لنشر رسائل محددة.','core','B2','CEFR-J'],
  ['herd','noun','قطيع','Herd mentality explains why people follow trends without thinking.','تُفسر عقلية القطيع لماذا يتبع الناس الاتجاهات دون تفكير.','extended','B2','CEFR-J'],
  ['instinct','noun','غريزة','Self-preservation instinct becomes amplified in emergency crowd situations.','تتضخم غريزة حفظ الذات في حالات الطوارئ الجماهيرية.','core','B2','CEFR-J'],
  ['anonymity','noun','إخفاء الهوية','Online anonymity can lead to more aggressive crowd behavior.','يمكن أن يؤدي إخفاء الهوية عبر الإنترنت إلى سلوك جماعي أكثر عدوانية.','extended','B2','CEFR-J'],
  ['charisma','noun','كاريزما / جاذبية','Leaders with strong charisma can easily sway large crowds.','يمكن للقادة ذوي الكاريزما القوية التأثير بسهولة على الحشود الكبيرة.','extended','B2','CEFR-J'],
  ['persuade','verb','يُقنع','Skilled speakers can persuade audiences to change their minds.','يمكن للمتحدثين المهرة إقناع الجمهور بتغيير آرائهم.','core','B2','CEFR-J'],
  ['provoke','verb','يستفز','Inflammatory speech can provoke violent reactions from angry crowds.','يمكن للخطاب التحريضي استفزاز ردود فعل عنيفة من الحشود الغاضبة.','core','B2','CEFR-J'],
  ['conform','verb','ينسجم / يمتثل','People naturally conform to group norms to avoid social rejection.','ينسجم الناس طبيعياً مع معايير المجموعة لتجنب الرفض الاجتماعي.','core','B2','AWL'],
  ['panic','noun','ذعر','Panic can spread through a crowd faster than accurate information.','يمكن للذعر أن ينتشر في الحشد أسرع من المعلومات الدقيقة.','core','B2','CEFR-J'],
  ['riot','noun','شغب','The peaceful demonstration escalated into a violent riot unexpectedly.','تصاعدت المظاهرة السلمية إلى شغب عنيف بشكل غير متوقع.','core','B2','CEFR-J'],
  ['rally','noun','تجمّع / مسيرة','The political rally attracted thousands of enthusiastic supporters.','جذب التجمع السياسي آلاف المؤيدين المتحمسين.','core','B2','CEFR-J'],
  ['demonstration','noun','مظاهرة','Student demonstrations have historically driven significant social change.','دفعت مظاهرات الطلاب تاريخياً بتغيير اجتماعي كبير.','core','B2','AWL'],
  ['subconscious','adjective','لا واعي','Subconscious biases affect how we respond to different social groups.','تؤثر التحيزات اللاواعية على كيفية استجابتنا لمجموعات اجتماعية مختلفة.','extended','B2','CEFR-J'],
  ['cognitive','adjective','إدراكي','Cognitive biases distort rational thinking in high-pressure situations.','تُشوّه التحيزات الإدراكية التفكير العقلاني في المواقف عالية الضغط.','core','B2','AWL'],
  ['irrational','adjective','غير عقلاني','Fear can cause irrational behavior even in normally calm individuals.','يمكن للخوف أن يُسبب سلوكاً غير عقلاني حتى لدى الأفراد الهادئين عادةً.','core','B2','CEFR-J'],
  ['unanimous','adjective','بالإجماع','The committee reached a unanimous decision after hours of debate.','توصلت اللجنة إلى قرار بالإجماع بعد ساعات من النقاش.','extended','B2','CEFR-J'],
  ['collective','adjective','جماعي','Collective intelligence can solve problems no individual could alone.','يمكن للذكاء الجماعي حل مشاكل لا يستطيع فرد حلها وحده.','core','B2','AWL'],
  ['phenomenon','noun','ظاهرة','Mass hysteria is a psychological phenomenon that affects large groups.','الهستيريا الجماعية ظاهرة نفسية تؤثر على مجموعات كبيرة.','core','B2','AWL'],
  ['trigger','verb','يُطلق / يُحفّز','A single incident can trigger widespread social unrest.','يمكن لحادثة واحدة أن تُطلق اضطراباً اجتماعياً واسع النطاق.','core','B2','CEFR-J'],
  ['suppress','verb','يقمع / يكبت','Governments sometimes suppress protests using crowd control measures.','تقمع الحكومات أحياناً الاحتجاجات باستخدام إجراءات السيطرة على الحشود.','core','B2','CEFR-J'],
  ['manipulate','verb','يتلاعب','Demagogues manipulate crowd emotions to gain political power.','يتلاعب الديماغوجيون بمشاعر الحشود لاكتساب السلطة السياسية.','core','B2','CEFR-J'],
  ['polarize','verb','يُستقطب','Social media algorithms can polarize public opinion on issues.','يمكن لخوارزميات وسائل التواصل الاجتماعي استقطاب الرأي العام حول القضايا.','extended','B2','CEFR-J'],
  ['deindividuation','noun','فقدان الفردية','Deindividuation in crowds reduces personal responsibility for actions.','يُقلل فقدان الفردية في الحشود من المسؤولية الشخصية عن الأفعال.','mastery','C1','CEFR-J'],
  ['groupthink','noun','تفكير جماعي','Groupthink occurs when consensus overrides critical evaluation.','يحدث التفكير الجماعي عندما يتغلب الإجماع على التقييم النقدي.','extended','C1','NAWL'],
  ['bystander','noun','متفرّج / شاهد','The bystander effect explains why witnesses sometimes fail to help.','يُفسر تأثير المتفرج لماذا يفشل الشهود أحياناً في المساعدة.','extended','B2','CEFR-J'],
  ['charismatic','adjective','كاريزمي','Charismatic leaders can unite diverse groups behind a common cause.','يمكن للقادة الكاريزميين توحيد مجموعات متنوعة خلف قضية مشتركة.','extended','B2','CEFR-J'],
  ['euphoria','noun','نشوة','Crowds at concerts often experience a shared sense of euphoria.','غالباً ما تشهد الحشود في الحفلات شعوراً مشتركاً بالنشوة.','extended','C1','CEFR-J'],
  ['contagion','noun','عدوى / انتقال','Emotional contagion causes feelings to spread rapidly through groups.','تُسبب العدوى العاطفية انتشار المشاعر بسرعة عبر المجموعات.','extended','C1','CEFR-J'],
  ['hysteria','noun','هستيريا','Mass hysteria can cause physical symptoms in perfectly healthy people.','يمكن للهستيريا الجماعية أن تُسبب أعراضاً جسدية لدى أشخاص أصحاء تماماً.','extended','B2','CEFR-J'],
  ['obedience','noun','طاعة','Milgram experiments revealed disturbing levels of obedience to authority.','كشفت تجارب ميلغرام عن مستويات مقلقة من الطاعة للسلطة.','core','B2','CEFR-J'],
  ['escalation','noun','تصعيد','Crowd violence follows predictable patterns of gradual escalation.','يتبع عنف الحشود أنماطاً يمكن التنبؤ بها من التصعيد التدريجي.','extended','B2','CEFR-J'],
  ['catalyst','noun','محفّز','A single provocative act can serve as a catalyst for mass protest.','يمكن لفعل استفزازي واحد أن يكون محفّزاً لاحتجاج جماعي.','extended','B2','AWL'],
  ['solidarity','noun','تضامن','Workers showed solidarity by joining the nationwide strike.','أظهر العمال تضامنهم بالانضمام إلى الإضراب الوطني.','core','B2','CEFR-J'],
  ['coercion','noun','إكراه / إجبار','Social coercion pressures individuals to act against their own judgment.','يضغط الإكراه الاجتماعي على الأفراد للتصرف ضد حكمهم الشخصي.','extended','C1','AWL'],
  ['dissent','noun','معارضة','Expressing dissent within a group requires considerable personal courage.','يتطلب التعبير عن المعارضة داخل المجموعة شجاعة شخصية كبيرة.','extended','C1','CEFR-J'],
  ['ideology','noun','أيديولوجيا / عقيدة','Extreme ideology can drive crowds toward destructive collective actions.','يمكن للأيديولوجيا المتطرفة دفع الحشود نحو أفعال جماعية مدمرة.','extended','B2','AWL'],
  ['norm','noun','معيار / قاعدة','Social norms dictate acceptable behavior within a given group.','تُملي المعايير الاجتماعية السلوك المقبول داخل مجموعة معينة.','core','B2','AWL'],
  ['temperament','noun','مزاج / طبع','Individual temperament affects how people respond to crowd pressure.','يؤثر المزاج الفردي على كيفية استجابة الناس لضغط الحشود.','extended','B2','CEFR-J'],
  ['scapegoat','noun','كبش فداء','Groups often seek a scapegoat to blame for collective failures.','غالباً ما تبحث المجموعات عن كبش فداء لإلقاء اللوم عليه.','extended','C1','CEFR-J'],
  ['catharsis','noun','تنفيس / تطهير','Some psychologists view crowd participation as a form of catharsis.','يرى بعض علماء النفس المشاركة الجماهيرية كشكل من أشكال التنفيس.','mastery','C1','CEFR-J'],
  ['altruism','noun','إيثار','Crowd situations can inspire remarkable acts of altruism and bravery.','يمكن للمواقف الجماعية أن تُلهم أفعال إيثار وشجاعة ملحوظة.','mastery','C1','CEFR-J'],
  ['authoritarian','adjective','سلطوي','Authoritarian regimes use crowd control to suppress political opposition.','تستخدم الأنظمة السلطوية السيطرة على الحشود لقمع المعارضة السياسية.','extended','B2','AWL'],
  ['demagogue','noun','ديماغوجي / محرّض','A demagogue exploits fears and prejudices to control public opinion.','يستغل الديماغوجي المخاوف والتحيزات للسيطرة على الرأي العام.','mastery','C1','CEFR-J'],
  ['populist','adjective','شعبوي','Populist rhetoric often oversimplifies complex social and economic issues.','غالباً ما يُبسّط الخطاب الشعبوي القضايا الاجتماعية والاقتصادية المعقدة.','extended','C1','NAWL'],
  ['compliance','noun','امتثال','Social compliance experiments reveal how easily behavior is influenced.','تكشف تجارب الامتثال الاجتماعي عن سهولة التأثير على السلوك.','extended','B2','AWL'],
  ['susceptibility','noun','قابلية التأثر','Individual susceptibility to crowd influence varies with personality.','تتباين قابلية الفرد للتأثر بالحشود حسب الشخصية.','mastery','C1','CEFR-J'],
  ['radicalization','noun','تطرّف','Online radicalization can transform individuals through group dynamics.','يمكن للتطرف عبر الإنترنت تحويل الأفراد من خلال ديناميكيات المجموعة.','mastery','C1','NAWL'],
  ['morale','noun','معنويات','Strong leadership maintains group morale during challenging times.','تُحافظ القيادة القوية على معنويات المجموعة في الأوقات الصعبة.','core','B2','CEFR-J'],
  ['sentiment','noun','مشاعر / عاطفة','Public sentiment can shift rapidly in response to dramatic events.','يمكن للمشاعر العامة أن تتحول بسرعة استجابةً لأحداث درامية.','core','B2','CEFR-J'],
  ['turmoil','noun','اضطراب / فوضى','Social turmoil often leads to unpredictable crowd behavior.','غالباً ما يؤدي الاضطراب الاجتماعي إلى سلوك حشود غير متوقع.','extended','C1','CEFR-J'],
  ['vigilante','noun','مُنتقم شعبي','Vigilante groups sometimes emerge when crowds lose trust in authorities.','تظهر أحياناً مجموعات الانتقام الشعبي عندما تفقد الحشود ثقتها بالسلطات.','mastery','C1','CEFR-J'],
];

// Unit 8 - Forensic Science
const U8 = [
  ['forensic','adjective','جنائي / شرعي','Forensic evidence played a crucial role in solving the case.','لعبت الأدلة الجنائية دوراً حاسماً في حل القضية.','core','B2','CEFR-J'],
  ['evidence','noun','دليل / أدلة','Physical evidence at crime scenes must be collected carefully.','يجب جمع الأدلة المادية في مسارح الجريمة بعناية.','core','B1','AWL'],
  ['investigation','noun','تحقيق','The criminal investigation relied heavily on digital forensic analysis.','اعتمد التحقيق الجنائي بشكل كبير على التحليل الجنائي الرقمي.','core','B2','CEFR-J'],
  ['fingerprint','noun','بصمة','Every person has unique fingerprints that remain unchanged throughout life.','لكل شخص بصمات فريدة تبقى دون تغيير طوال الحياة.','core','B2','CEFR-J'],
  ['suspect','noun','مشتبه به','The suspect was identified through surveillance camera footage.','تم تحديد المشتبه به من خلال لقطات كاميرات المراقبة.','core','B2','CEFR-J'],
  ['autopsy','noun','تشريح الجثة','The autopsy revealed the true cause of the victim death.','كشف تشريح الجثة عن السبب الحقيقي لوفاة الضحية.','extended','B2','CEFR-J'],
  ['toxicology','noun','علم السموم','Toxicology tests detected traces of poison in the victim blood.','كشفت فحوصات علم السموم عن آثار سم في دم الضحية.','extended','B2','CEFR-J'],
  ['ballistics','noun','علم المقذوفات','Ballistics analysis matched the bullet to a specific weapon.','طابق تحليل المقذوفات الرصاصة بسلاح محدد.','extended','C1','CEFR-J'],
  ['testimony','noun','شهادة','The expert witness provided compelling testimony based on forensic findings.','قدّم الشاهد الخبير شهادة مقنعة بناءً على النتائج الجنائية.','core','B2','CEFR-J'],
  ['perpetrator','noun','مرتكب الجريمة','Advanced techniques helped identify the perpetrator decades after the crime.','ساعدت التقنيات المتقدمة في تحديد مرتكب الجريمة بعد عقود.','extended','B2','CEFR-J'],
  ['trace','noun','أثر / علامة','Even the smallest trace of evidence can solve a cold case.','حتى أصغر أثر من الأدلة يمكن أن يحل قضية قديمة.','core','B2','CEFR-J'],
  ['contamination','noun','تلوث','Evidence contamination can completely undermine a criminal case.','يمكن لتلوث الأدلة أن يُقوّض قضية جنائية بالكامل.','core','B2','CEFR-J'],
  ['DNA profiling','noun','تحليل الحمض النووي','DNA profiling has revolutionized modern criminal identification.','أحدث تحليل الحمض النووي ثورة في تحديد الهوية الجنائية الحديثة.','core','B2','CEFR-J'],
  ['pathologist','noun','أخصائي أمراض','The forensic pathologist determined the cause and time of death.','حدد أخصائي الأمراض الجنائي سبب ووقت الوفاة.','extended','B2','CEFR-J'],
  ['jurisdiction','noun','اختصاص قضائي','International crimes may fall under multiple legal jurisdictions.','قد تقع الجرائم الدولية تحت عدة اختصاصات قضائية.','extended','B2','AWL'],
  ['prosecution','noun','ملاحقة قضائية','Strong forensic evidence supports successful criminal prosecution.','تدعم الأدلة الجنائية القوية الملاحقة القضائية الناجحة.','core','B2','CEFR-J'],
  ['acquittal','noun','تبرئة','DNA evidence led to the acquittal of the wrongly convicted prisoner.','أدت أدلة الحمض النووي إلى تبرئة السجين المدان ظلماً.','extended','C1','CEFR-J'],
  ['coroner','noun','طبيب شرعي','The coroner determined that the death was accidental not criminal.','قرر الطبيب الشرعي أن الوفاة كانت عرضية وليست جنائية.','extended','B2','CEFR-J'],
  ['surveillance','noun','مراقبة','Digital surveillance systems have become essential forensic tools.','أصبحت أنظمة المراقبة الرقمية أدوات جنائية أساسية.','core','B2','AWL'],
  ['incriminate','verb','يُدين / يُجرّم','The recovered emails could incriminate the suspect in the fraud.','يمكن للرسائل الإلكترونية المستردة أن تُدين المشتبه به في الاحتيال.','extended','C1','CEFR-J'],
  ['exonerate','verb','يُبرّئ','New DNA evidence can exonerate people who were wrongly imprisoned.','يمكن لأدلة الحمض النووي الجديدة تبرئة أشخاص سُجنوا ظلماً.','extended','C1','CEFR-J'],
  ['interrogate','verb','يستجوب','Detectives interrogated the suspect for several hours.','استجوب المحققون المشتبه به لعدة ساعات.','core','B2','CEFR-J'],
  ['analyze','verb','يحلل','Scientists analyze blood samples to determine genetic markers.','يحلل العلماء عينات الدم لتحديد العلامات الجينية.','core','B2','AWL'],
  ['verify','verb','يتحقق من','Forensic accountants verify financial records to detect fraud.','يتحقق المحاسبون الجنائيون من السجلات المالية لكشف الاحتيال.','core','B2','CEFR-J'],
  ['reconstruct','verb','يُعيد بناء / يُعيد تركيب','Investigators reconstruct crime scenes to understand what happened.','يُعيد المحققون بناء مسارح الجريمة لفهم ما حدث.','extended','B2','AWL'],
  ['tamper','verb','يُعبث / يُزوّر','Anyone who tampers with evidence faces serious criminal charges.','يواجه أي شخص يعبث بالأدلة تهماً جنائية خطيرة.','extended','B2','CEFR-J'],
  ['convict','verb','يُدين','The jury convicted the defendant based on overwhelming evidence.','أدانت هيئة المحلفين المتهم بناءً على أدلة ساحقة.','core','B2','CEFR-J'],
  ['defendant','noun','متهم / مدّعى عليه','The defendant pleaded not guilty to all charges.','أنكر المتهم جميع التهم الموجهة إليه.','core','B2','CEFR-J'],
  ['plaintiff','noun','مدّعي','The plaintiff presented compelling evidence to support their case.','قدّم المدّعي أدلة مقنعة لدعم قضيته.','extended','B2','CEFR-J'],
  ['verdict','noun','حكم / قرار','The jury delivered a guilty verdict after three days of deliberation.','أصدرت هيئة المحلفين حكماً بالإدانة بعد ثلاثة أيام من المداولات.','core','B2','CEFR-J'],
  ['warrant','noun','أمر قضائي / مذكرة','The police obtained a search warrant to examine the property.','حصلت الشرطة على أمر تفتيش لفحص الممتلكات.','core','B2','CEFR-J'],
  ['alibi','noun','حجة غياب','The suspect provided a credible alibi for the night of the crime.','قدّم المشتبه به حجة غياب موثوقة لليلة وقوع الجريمة.','extended','B2','CEFR-J'],
  ['motive','noun','دافع','Establishing a clear motive is crucial in criminal investigations.','تحديد دافع واضح أمر حاسم في التحقيقات الجنائية.','core','B2','CEFR-J'],
  ['circumstantial','adjective','ظرفي (دليل غير مباشر)','Circumstantial evidence alone is rarely sufficient for conviction.','نادراً ما تكون الأدلة الظرفية وحدها كافية للإدانة.','extended','C1','CEFR-J'],
  ['forensics','noun','العلوم الجنائية','Digital forensics is one of the fastest growing fields in law enforcement.','العلوم الجنائية الرقمية من أسرع المجالات نمواً في إنفاذ القانون.','core','B2','CEFR-J'],
  ['crime scene','noun','مسرح الجريمة','Preserving the crime scene is the first priority for investigators.','الحفاظ على مسرح الجريمة هو الأولوية الأولى للمحققين.','core','B2','CEFR-J'],
  ['cadaver','noun','جثة','Cadaver dogs are specially trained to locate human remains.','تُدرّب كلاب الجثث خصيصاً لتحديد موقع الرفات البشرية.','mastery','C1','CEFR-J'],
  ['decomposition','noun','تحلّل','The rate of decomposition helps estimate the time of death.','يُساعد معدل التحلل في تقدير وقت الوفاة.','extended','C1','CEFR-J'],
  ['fiber','noun','ليف','Forensic fiber analysis can link a suspect to a specific location.','يمكن لتحليل الألياف الجنائي ربط مشتبه به بموقع محدد.','core','B2','CEFR-J'],
  ['residue','noun','بقايا / آثار','Gunshot residue on clothing placed the suspect at the scene.','وضعت بقايا الطلقات النارية على الملابس المشتبه به في مكان الحادث.','extended','B2','CEFR-J'],
  ['specimen','noun','عيّنة','Blood specimens must be stored properly to preserve their integrity.','يجب تخزين عينات الدم بشكل صحيح للحفاظ على سلامتها.','core','B2','CEFR-J'],
  ['impersonate','verb','ينتحل شخصية','Identity theft involves someone who impersonates another person.','تتضمن سرقة الهوية شخصاً ينتحل شخصية شخص آخر.','extended','B2','CEFR-J'],
  ['arson','noun','حرق متعمد','Forensic investigators determined that the fire was caused by arson.','قرر المحققون الجنائيون أن الحريق ناجم عن حرق متعمد.','extended','B2','CEFR-J'],
  ['homicide','noun','قتل','The forensic team was called to investigate a suspected homicide.','استُدعي الفريق الجنائي للتحقيق في جريمة قتل مشتبه بها.','extended','B2','CEFR-J'],
  ['forgery','noun','تزوير','Document forgery has become more difficult with modern security features.','أصبح تزوير المستندات أكثر صعوبة مع ميزات الأمان الحديثة.','extended','B2','CEFR-J'],
  ['counterfeit','adjective','مزيّف','Forensic experts can identify counterfeit currency using special tools.','يمكن للخبراء الجنائيين تحديد العملة المزيّفة باستخدام أدوات خاصة.','extended','B2','CEFR-J'],
  ['cybercrime','noun','جريمة إلكترونية','Cybercrime now causes more financial damage than traditional theft.','تُسبب الجريمة الإلكترونية الآن أضراراً مالية أكثر من السرقة التقليدية.','core','B2','CEFR-J'],
  ['culprit','noun','جانٍ / مذنب','Advanced technology helped identify the culprit within hours.','ساعدت التكنولوجيا المتقدمة في تحديد الجاني في غضون ساعات.','core','B2','CEFR-J'],
  ['witness','noun','شاهد','An eyewitness identified the suspect from a police photo lineup.','حدد شاهد عيان المشتبه به من تشكيلة صور الشرطة.','core','B1','CEFR-J'],
  ['accomplice','noun','شريك في الجريمة','The accomplice helped plan the robbery but did not enter the building.','ساعد الشريك في التخطيط للسرقة لكنه لم يدخل المبنى.','extended','C1','CEFR-J'],
  ['probation','noun','مراقبة (قضائية)','The judge sentenced the first-time offender to two years of probation.','حكم القاضي على المجرم لأول مرة بعامين من المراقبة.','extended','B2','CEFR-J'],
  ['parole','noun','إفراج مشروط','The prisoner was released on parole after serving half the sentence.','أُفرج عن السجين إفراجاً مشروطاً بعد قضاء نصف العقوبة.','extended','B2','CEFR-J'],
  ['entomology','noun','علم الحشرات','Forensic entomology uses insect evidence to estimate time of death.','يستخدم علم الحشرات الجنائي أدلة الحشرات لتقدير وقت الوفاة.','mastery','C1','CEFR-J'],
  ['serology','noun','علم المصليات','Serology testing identifies blood types found at crime scenes.','يحدد فحص المصليات أنواع الدم الموجودة في مسارح الجريمة.','mastery','C1','CEFR-J'],
  ['spectroscopy','noun','مطيافية','Spectroscopy can identify unknown chemical substances at crime scenes.','يمكن للمطيافية تحديد المواد الكيميائية المجهولة في مسارح الجريمة.','mastery','C1','NAWL'],
  ['jurisprudence','noun','فقه قانوني','Forensic science has transformed modern criminal jurisprudence.','حوّلت العلوم الجنائية الفقه القانوني الجنائي الحديث.','mastery','C1','AWL'],
  ['perpetrate','verb','يرتكب','The crime was perpetrated by a sophisticated criminal organization.','ارتُكبت الجريمة من قبل منظمة إجرامية متطورة.','mastery','C1','CEFR-J'],
  ['corroborate','verb','يؤكد / يدعم','Physical evidence must corroborate witness testimony for conviction.','يجب أن تؤكد الأدلة المادية شهادة الشهود للإدانة.','mastery','C1','CEFR-J'],
  ['immaculate','adjective','نظيف تماماً','The crime scene appeared immaculate suggesting a professional criminal.','بدا مسرح الجريمة نظيفاً تماماً مما يُشير إلى مجرم محترف.','mastery','C1','CEFR-J'],
  ['clandestine','adjective','سري','The clandestine operation was uncovered through digital forensic analysis.','كُشفت العملية السرية من خلال التحليل الجنائي الرقمي.','mastery','C1','CEFR-J'],
  ['irrefutable','adjective','لا يمكن دحضه','DNA evidence is considered nearly irrefutable in modern courts.','يُعتبر دليل الحمض النووي غير قابل للدحض تقريباً في المحاكم الحديثة.','mastery','C1','CEFR-J'],
  ['premeditated','adjective','متعمّد / مع سبق الإصرار','The evidence showed that the crime was premeditated not impulsive.','أظهرت الأدلة أن الجريمة كانت متعمدة وليست اندفاعية.','extended','C1','CEFR-J'],
];

async function run() {
  const client = await pool.connect();
  try {
    const before = await client.query(`SELECT COUNT(*) AS cnt FROM vocab_staging_l4`);
    console.log('Before:', before.rows[0].cnt, 'words');

    const u5c = await insertBatch(client, U5, 5, 6);
    console.log(`U5: ${u5c} inserted (batch 6)`);

    const u6c = await insertBatch(client, U6, 6, 7);
    console.log(`U6: ${u6c} inserted (batch 7)`);

    const u7c = await insertBatch(client, U7, 7, 8);
    console.log(`U7: ${u7c} inserted (batch 8)`);

    const u8c = await insertBatch(client, U8, 8, 9);
    console.log(`U8: ${u8c} inserted (batch 9)`);

    const after = await client.query(`SELECT recommended_unit, COUNT(*) AS cnt FROM vocab_staging_l4 GROUP BY recommended_unit ORDER BY recommended_unit`);
    console.log('\n=== Per-unit totals ===');
    after.rows.forEach(r => console.log(`U${r.recommended_unit}: ${r.cnt}`));

    const total = await client.query(`SELECT COUNT(*) AS cnt FROM vocab_staging_l4`);
    console.log('\nTotal staged:', total.rows[0].cnt);
  } finally {
    client.release();
    pool.end();
  }
}

run().catch(e => console.error(e));
