// LEGENDARY-B5 Batch 2: Unit 1 remainder + Units 2-4
const { Pool } = require('pg');
const pool = new Pool({
  host: 'aws-1-eu-central-1.pooler.supabase.com', port: 5432, database: 'postgres',
  user: 'postgres.nmjexpuycmqcxuxljier', password: 'Ali-al-ahmad2000',
  ssl: { rejectUnauthorized: false }
});

async function insertBatch(client, words, unitNumber, batchId) {
  let inserted = 0;
  for (const w of words) {
    try {
      await client.query(
        `INSERT INTO public.vocab_staging_l4 (word, pos, definition_ar, example_en, example_ar, recommended_tier, cefr_level, source_list, recommended_unit, batch_id) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) ON CONFLICT (word) DO NOTHING`,
        [w[0], w[1], w[2], w[3], w[4], w[5], w[6], w[7], unitNumber, batchId]
      );
      inserted++;
    } catch(e) { console.error(`Error "${w[0]}":`, e.message); }
  }
  return inserted;
}

// Unit 1 remainder - more Bioethics words
const U1_MORE = [
  ['disposition','noun','استعداد / ميل','A genetic disposition toward anxiety can be managed with therapy.','يمكن إدارة الاستعداد الجيني للقلق بالعلاج.','core','B2','CEFR-J'],
  ['pharmaceutical','noun','منتج دوائي','The new pharmaceutical showed promising results in early trials.','أظهر المنتج الدوائي الجديد نتائج واعدة في التجارب المبكرة.','core','B2','CEFR-J'],
  ['intervention','noun','تدخل','Early medical intervention can prevent complications in premature babies.','يمكن للتدخل الطبي المبكر منع المضاعفات عند الأطفال الخدّج.','core','B2','AWL'],
  ['mortality','noun','معدل وفيات','Childhood mortality rates have decreased significantly in recent decades.','انخفضت معدلات وفيات الأطفال بشكل كبير في العقود الأخيرة.','core','B2','CEFR-J'],
  ['prevalence','noun','انتشار','The prevalence of diabetes has doubled in the past twenty years.','تضاعف انتشار مرض السكري في العشرين سنة الماضية.','extended','B2','AWL'],
  ['malpractice','noun','سوء ممارسة طبية','Medical malpractice lawsuits can result in millions in damages.','يمكن أن تؤدي دعاوى سوء الممارسة الطبية إلى ملايين التعويضات.','extended','C1','CEFR-J'],
  ['euthanasia','noun','القتل الرحيم','The debate over euthanasia involves complex legal and moral issues.','يتضمن النقاش حول القتل الرحيم قضايا قانونية وأخلاقية معقدة.','extended','C1','CEFR-J'],
  ['surrogate','noun','بديل / أم بديلة','Some couples use a surrogate mother to have biological children.','يستخدم بعض الأزواج أماً بديلة لإنجاب أطفال بيولوجيين.','extended','C1','CEFR-J'],
  ['confidentiality','noun','سرية','Patient confidentiality is a fundamental principle of medical ethics.','سرية المريض مبدأ أساسي في أخلاقيات الطب.','extended','B2','NAWL'],
  ['negligence','noun','إهمال','Medical negligence can lead to severe harm or death of patients.','يمكن أن يؤدي الإهمال الطبي إلى ضرر شديد أو وفاة المرضى.','extended','B2','AWL'],
  ['susceptibility','noun','قابلية التأثر','Genetic testing can reveal susceptibility to inherited conditions.','يمكن للفحص الجيني الكشف عن قابلية التأثر بالحالات الوراثية.','extended','C1','CEFR-J'],
  ['longevity','noun','طول العمر','Advances in medicine have greatly increased human longevity.','زادت التطورات في الطب من طول عمر الإنسان بشكل كبير.','extended','B2','CEFR-J'],
  ['advocate','verb','يدافع عن / يناصر','Many doctors advocate for universal access to healthcare services.','يدافع كثير من الأطباء عن الوصول الشامل لخدمات الرعاية الصحية.','core','B2','AWL'],
  ['allocate','verb','يخصص','Governments must allocate sufficient funds for public health research.','يجب أن تخصص الحكومات أموالاً كافية لأبحاث الصحة العامة.','extended','B2','AWL'],
  ['manifest','verb','يتجلى / يظهر','Symptoms of the disease can manifest years after initial infection.','يمكن أن تتجلى أعراض المرض بعد سنوات من العدوى الأولية.','extended','B2','AWL'],
  ['oversight','noun','رقابة / إشراف','Independent oversight ensures research follows ethical standards.','تضمن الرقابة المستقلة اتباع البحث للمعايير الأخلاقية.','core','B2','NAWL'],
  ['stakeholder','noun','صاحب مصلحة','All stakeholders must be involved in decisions about public health policy.','يجب إشراك جميع أصحاب المصلحة في قرارات سياسة الصحة العامة.','extended','B2','NAWL'],
  ['viable','adjective','قابل للحياة / ممكن','Gene therapy is now a viable option for treating certain blood diseases.','أصبح العلاج الجيني الآن خياراً ممكناً لعلاج أمراض دم معينة.','core','B2','AWL'],
  ['comprehensive','adjective','شامل','The hospital provides comprehensive care from diagnosis to recovery.','يقدم المستشفى رعاية شاملة من التشخيص إلى الشفاء.','core','B2','AWL'],
  ['detrimental','adjective','ضار / مؤذٍ','Smoking is detrimental to lung health and overall wellbeing.','التدخين ضار بصحة الرئة والرفاهية العامة.','extended','B2','AWL'],
  ['empirical','adjective','تجريبي / عملي','All medical claims should be supported by empirical evidence.','يجب أن تكون جميع الادعاءات الطبية مدعومة بأدلة تجريبية.','mastery','C1','AWL'],
  ['indigenous','adjective','أصلي / محلي','Indigenous healing practices are being studied by modern researchers.','تُدرس ممارسات الشفاء الأصلية من قبل الباحثين المعاصرين.','extended','B2','AWL'],
  ['stringent','adjective','صارم','Drug approval requires passing stringent safety and efficacy tests.','تتطلب الموافقة على الأدوية اجتياز اختبارات صارمة للسلامة والفعالية.','mastery','C1','CEFR-J'],
  ['unprecedented','adjective','غير مسبوق','The speed of vaccine development was unprecedented in medical history.','كانت سرعة تطوير اللقاح غير مسبوقة في تاريخ الطب.','core','B2','AWL'],
  ['obligatory','adjective','إلزامي','Informed consent is obligatory before any experimental treatment.','الموافقة المستنيرة إلزامية قبل أي علاج تجريبي.','extended','B2','CEFR-J'],
  ['rehabilitation','noun','تأهيل','Physical rehabilitation helps stroke patients regain motor function.','يساعد التأهيل البدني مرضى السكتة الدماغية على استعادة الوظائف الحركية.','core','B2','CEFR-J'],
  ['abnormality','noun','شذوذ / خلل','Genetic screening can identify chromosomal abnormalities before birth.','يمكن للفحص الجيني تحديد الشذوذات الصبغية قبل الولادة.','extended','B2','AWL'],
  ['impairment','noun','ضعف / إعاقة','Hearing impairment affects millions of people worldwide.','يؤثر ضعف السمع على ملايين الأشخاص حول العالم.','core','B2','CEFR-J'],
  ['incidence','noun','معدل حدوث','The incidence of skin cancer has risen due to increased sun exposure.','ارتفع معدل حدوث سرطان الجلد بسبب زيادة التعرض للشمس.','extended','B2','AWL'],
  ['criterion','noun','معيار','The main criterion for organ transplant eligibility is medical urgency.','المعيار الرئيسي لأهلية زراعة الأعضاء هو الحاجة الطبية العاجلة.','core','B2','AWL'],
  ['integrity','noun','نزاهة / سلامة','Scientific integrity requires honest reporting of all research findings.','تتطلب النزاهة العلمية إعداد تقارير صادقة لجميع نتائج البحث.','core','B2','AWL'],
  ['protocol','noun','بروتوكول / إجراء','Clinical research must follow a strict protocol approved by the ethics board.','يجب أن يتبع البحث السريري بروتوكولاً صارماً موافقاً عليه من لجنة الأخلاقيات.','core','B2','AWL'],
  ['pathological','adjective','مَرَضي','The pathological examination revealed damage to multiple organs.','كشف الفحص المرضي عن تلف في أعضاء متعددة.','mastery','C1','CEFR-J'],
  ['endemic','adjective','متوطّن','Malaria remains endemic in many tropical regions of the world.','لا يزال الملاريا متوطناً في كثير من المناطق الاستوائية.','mastery','C1','CEFR-J'],
  ['intravenous','adjective','وريدي','The patient received medication through an intravenous drip.','تلقى المريض الدواء من خلال التنقيط الوريدي.','mastery','C1','CEFR-J'],
  ['postoperative','adjective','بعد العملية','Postoperative care is crucial for preventing infections and complications.','الرعاية بعد العملية ضرورية لمنع العدوى والمضاعفات.','mastery','C1','CEFR-J'],
  ['subcutaneous','adjective','تحت الجلد','Insulin is usually administered through subcutaneous injection.','يُعطى الأنسولين عادة عن طريق الحقن تحت الجلد.','mastery','C1','CEFR-J'],
  ['probiotic','noun','بروبيوتيك / بكتيريا نافعة','Probiotics can help restore healthy gut bacteria after antibiotic use.','يمكن للبروبيوتيك المساعدة في استعادة بكتيريا الأمعاء بعد استخدام المضادات.','extended','B2','CEFR-J'],
  ['dehydration','noun','جفاف','Severe dehydration can lead to kidney failure if left untreated.','يمكن أن يؤدي الجفاف الشديد إلى فشل كلوي إذا لم يُعالج.','core','B2','CEFR-J'],
  ['deficiency','noun','نقص','Vitamin D deficiency is common in regions with limited sunlight.','نقص فيتامين د شائع في المناطق ذات أشعة الشمس المحدودة.','core','B2','CEFR-J'],
  ['inflammation','noun','التهاب','Chronic inflammation increases the risk of developing heart disease.','يزيد الالتهاب المزمن من خطر الإصابة بأمراض القلب.','core','B2','CEFR-J'],
  ['complication','noun','مضاعفة','Post-surgical complications can be minimized with proper monitoring.','يمكن تقليل المضاعفات بعد الجراحة بالمراقبة السليمة.','core','B2','CEFR-J'],
  ['prognosis','noun','توقع طبي','Early detection generally leads to a more favorable prognosis.','يؤدي الكشف المبكر عموماً إلى توقع طبي أفضل.','extended','C1','CEFR-J'],
  ['efficacy','noun','فعالية','The efficacy of the new treatment exceeded all expectations.','تجاوزت فعالية العلاج الجديد كل التوقعات.','extended','B2','AWL'],
  ['potent','adjective','فعّال / قوي','This is one of the most potent antiviral drugs available today.','هذا أحد أقوى الأدوية المضادة للفيروسات المتاحة اليوم.','extended','B2','CEFR-J'],
  ['benevolent','adjective','خيّر / محسن','The hospital was founded by a benevolent organization in the community.','أُسس المستشفى من قبل منظمة خيّرة في المجتمع.','mastery','C1','CEFR-J'],
  ['debilitating','adjective','مُنهك / مُعجز','Chronic fatigue syndrome is a debilitating condition that limits daily life.','متلازمة التعب المزمن حالة منهكة تحدّ من الحياة اليومية.','mastery','C1','CEFR-J'],
];

// Unit 2 - Deep Ocean Discovery
const U2 = [
  ['ocean','noun','محيط','The ocean covers more than seventy percent of the Earth surface.','يغطي المحيط أكثر من سبعين بالمئة من سطح الأرض.','core','B1','CEFR-J'],
  ['marine','adjective','بحري','Marine biologists study underwater ecosystems and ocean life.','يدرس علماء الأحياء البحرية النظم البيئية تحت الماء والحياة في المحيط.','core','B2','CEFR-J'],
  ['submarine','noun','غواصة','The research submarine descended to the deepest part of the ocean.','نزلت الغواصة البحثية إلى أعمق جزء من المحيط.','core','B2','CEFR-J'],
  ['coral','noun','مرجان','Coral reefs provide essential habitats for thousands of marine species.','توفر الشعاب المرجانية موائل أساسية لآلاف الأنواع البحرية.','core','B2','CEFR-J'],
  ['expedition','noun','رحلة استكشافية','The deep-sea expedition discovered several previously unknown species.','اكتشفت الرحلة الاستكشافية للأعماق عدة أنواع لم تكن معروفة سابقاً.','core','B2','CEFR-J'],
  ['ecosystem','noun','نظام بيئي','Deep ocean ecosystems are surprisingly diverse and complex.','النظم البيئية في أعماق المحيط متنوعة ومعقدة بشكل مدهش.','core','B2','CEFR-J'],
  ['species','noun','نوع (أحيائي)','Scientists estimate millions of ocean species remain undiscovered.','يُقدّر العلماء أن ملايين الأنواع البحرية لا تزال غير مكتشفة.','core','B2','CEFR-J'],
  ['depth','noun','عمق','At great depth the pressure makes exploration extremely challenging.','في الأعماق الكبيرة يجعل الضغط الاستكشاف صعباً للغاية.','core','B1','CEFR-J'],
  ['current','noun','تيار (مائي)','Ocean currents play a vital role in regulating global climate.','تلعب التيارات المحيطية دوراً حيوياً في تنظيم المناخ العالمي.','core','B2','CEFR-J'],
  ['pressure','noun','ضغط','Water pressure increases dramatically with every meter of depth.','يزداد ضغط الماء بشكل كبير مع كل متر من العمق.','core','B1','CEFR-J'],
  ['habitat','noun','موطن / بيئة','Pollution threatens the natural habitat of many aquatic creatures.','يُهدد التلوث الموطن الطبيعي للعديد من الكائنات المائية.','core','B2','CEFR-J'],
  ['biodiversity','noun','تنوع بيولوجي','The ocean contains more biodiversity than any terrestrial environment.','يحتوي المحيط على تنوع بيولوجي أكثر من أي بيئة برية.','core','B2','NAWL'],
  ['exploration','noun','استكشاف','Ocean exploration requires advanced technology and significant investment.','يتطلب استكشاف المحيط تقنية متقدمة واستثماراً كبيراً.','core','B2','CEFR-J'],
  ['reef','noun','شعب مرجانية','The Great Barrier Reef is visible from outer space.','الحاجز المرجاني العظيم مرئي من الفضاء الخارجي.','core','B2','CEFR-J'],
  ['sonar','noun','سونار','Scientists use sonar technology to map the ocean floor.','يستخدم العلماء تقنية السونار لرسم خرائط قاع المحيط.','core','B2','CEFR-J'],
  ['abyss','noun','هاوية / أعماق سحيقة','Life exists even in the darkest abyss of the ocean.','توجد حياة حتى في أعمق هاوية من المحيط.','extended','C1','CEFR-J'],
  ['vessel','noun','سفينة / وعاء','The research vessel carried advanced equipment for deep-sea sampling.','حملت سفينة البحث معدات متقدمة لأخذ عينات من الأعماق.','core','B2','CEFR-J'],
  ['tidal','adjective','مدّي / متعلق بالمد','Tidal energy is a promising renewable resource along coastal areas.','طاقة المد مورد متجدد واعد على طول المناطق الساحلية.','extended','B2','CEFR-J'],
  ['aquatic','adjective','مائي','Many aquatic animals have evolved unique adaptations for survival.','طوّرت كثير من الحيوانات المائية تكيفات فريدة للبقاء.','core','B2','CEFR-J'],
  ['navigate','verb','يُبحر / يتنقل','Ancient sailors used stars to navigate across vast oceans.','استخدم البحارة القدماء النجوم للإبحار عبر المحيطات الشاسعة.','core','B2','CEFR-J'],
  ['submerge','verb','يغمر / يغطس','The submersible can submerge to depths exceeding five kilometers.','يمكن للمركبة الغاطسة الغوص إلى أعماق تتجاوز خمسة كيلومترات.','extended','B2','CEFR-J'],
  ['erode','verb','يتآكل','Powerful currents gradually erode underwater rock formations.','تتآكل التكوينات الصخرية تحت الماء تدريجياً بفعل التيارات القوية.','extended','B2','CEFR-J'],
  ['contaminate','verb','يلوث','Industrial waste continues to contaminate coastal waters worldwide.','تستمر النفايات الصناعية في تلويث المياه الساحلية حول العالم.','core','B2','CEFR-J'],
  ['migrate','verb','يهاجر','Whales migrate thousands of kilometers between feeding grounds.','تهاجر الحيتان آلاف الكيلومترات بين مناطق التغذية.','core','B2','CEFR-J'],
  ['flourish','verb','يزدهر','Unique organisms flourish near hydrothermal vents on the ocean floor.','تزدهر كائنات فريدة بالقرب من الفتحات الحرارية في قاع المحيط.','extended','B2','CEFR-J'],
  ['deplete','verb','يستنفد','Overfishing has severely depleted many commercially important fish stocks.','أدى الصيد المفرط إلى استنفاد شديد لمخزونات أسماك مهمة تجارياً.','extended','B2','CEFR-J'],
  ['illuminate','verb','يُنير','Bioluminescent creatures illuminate the pitch-black depths of the ocean.','تُنير الكائنات ذات الإضاءة الحيوية أعماق المحيط الحالكة.','extended','B2','CEFR-J'],
  ['preserve','verb','يحافظ على','International treaties aim to preserve marine habitats from destruction.','تهدف المعاهدات الدولية إلى الحفاظ على الموائل البحرية من التدمير.','core','B2','CEFR-J'],
  ['extract','verb','يستخرج','Companies extract valuable minerals from the deep ocean floor.','تستخرج الشركات معادن قيّمة من أعماق قاع المحيط.','core','B2','AWL'],
  ['adapt','verb','يتكيف','Deep-sea creatures have adapted to survive extreme pressure and cold.','تكيفت مخلوقات الأعماق للبقاء في ظروف ضغط وبرودة شديدة.','core','B1','AWL'],
  ['acidification','noun','تحمّض','Ocean acidification threatens shellfish and coral reef ecosystems.','يُهدد تحمّض المحيط الرخويات ونظم الشعاب المرجانية.','extended','C1','NAWL'],
  ['bioluminescence','noun','إضاءة حيوية','Bioluminescence helps deep-sea creatures attract prey in darkness.','تساعد الإضاءة الحيوية مخلوقات الأعماق في جذب الفرائس في الظلام.','extended','C1','CEFR-J'],
  ['continental','adjective','قارّي','The continental shelf extends from the coast to the deep ocean.','يمتد الرف القارّي من الساحل إلى أعماق المحيط.','core','B2','CEFR-J'],
  ['hydrothermal','adjective','حراري مائي','Hydrothermal vents release superheated water rich in dissolved minerals.','تُطلق الفتحات الحرارية المائية مياهاً فائقة السخونة غنية بالمعادن المذابة.','extended','C1','CEFR-J'],
  ['sediment','noun','رواسب','Ocean sediments contain valuable clues about ancient climate conditions.','تحتوي رواسب المحيط على أدلة قيّمة حول ظروف المناخ القديم.','core','B2','CEFR-J'],
  ['tsunami','noun','تسونامي','A powerful earthquake can trigger a devastating tsunami across the ocean.','يمكن لزلزال قوي أن يُحدث تسونامي مدمر عبر المحيط.','core','B2','CEFR-J'],
  ['plankton','noun','عوالق','Microscopic plankton form the base of the entire marine food chain.','تُشكّل العوالق المجهرية قاعدة سلسلة الغذاء البحرية بأكملها.','extended','B2','CEFR-J'],
  ['predator','noun','مفترس','The great white shark is the ocean most feared apex predator.','القرش الأبيض الكبير هو أكثر المفترسات العليا رهبة في المحيط.','core','B2','CEFR-J'],
  ['prey','noun','فريسة','Small fish often swim in large schools to confuse approaching prey.','غالباً ما تسبح الأسماك الصغيرة في أسراب كبيرة لإرباك الحيوانات المفترسة.','core','B2','CEFR-J'],
  ['conservation','noun','حفظ / صون','Ocean conservation requires cooperation between nations and industries.','يتطلب حفظ المحيط تعاوناً بين الدول والصناعات.','core','B2','CEFR-J'],
  ['sustainability','noun','استدامة','Marine sustainability means using ocean resources without depleting them.','تعني الاستدامة البحرية استخدام موارد المحيط دون استنفادها.','core','B2','NAWL'],
  ['magnitude','noun','حجم / ضخامة','The magnitude of ocean pollution has reached a critical level.','وصل حجم تلوث المحيط إلى مستوى حرج.','extended','B2','AWL'],
  ['phenomenon','noun','ظاهرة','El Nino is a climate phenomenon that affects weather patterns globally.','النينيو ظاهرة مناخية تؤثر على أنماط الطقس عالمياً.','core','B2','AWL'],
  ['erosion','noun','تآكل','Coastal erosion is accelerating due to rising sea levels.','يتسارع التآكل الساحلي بسبب ارتفاع مستوى سطح البحر.','extended','B2','CEFR-J'],
  ['salinity','noun','ملوحة','Ocean salinity varies depending on temperature and rainfall patterns.','تتفاوت ملوحة المحيط حسب أنماط درجات الحرارة والأمطار.','extended','C1','CEFR-J'],
  ['topography','noun','تضاريس','The ocean floor topography includes mountains, valleys, and trenches.','تشمل تضاريس قاع المحيط جبالاً ووديان وخنادق.','extended','B2','NAWL'],
  ['turbulence','noun','اضطراب','Underwater turbulence can scatter equipment and disrupt measurements.','يمكن للاضطراب تحت الماء تشتيت المعدات وتعطيل القياسات.','extended','B2','CEFR-J'],
  ['submersible','noun','مركبة غاطسة','The submersible carried three scientists to the ocean deepest point.','حملت المركبة الغاطسة ثلاثة علماء إلى أعمق نقطة في المحيط.','extended','B2','CEFR-J'],
  ['trench','noun','خندق','The Mariana Trench is the deepest known location on Earth.','خندق ماريانا هو أعمق موقع معروف على الأرض.','core','B2','CEFR-J'],
  ['tide','noun','مدّ وجزر','Tides are caused by the gravitational pull of the moon.','ينتج المد والجزر عن قوة الجاذبية للقمر.','core','B1','CEFR-J'],
  ['glacier','noun','نهر جليدي','Melting glaciers contribute significantly to rising sea levels.','تساهم الأنهار الجليدية الذائبة بشكل كبير في ارتفاع مستوى البحر.','core','B2','CEFR-J'],
  ['fjord','noun','مضيق بحري','Norwegian fjords were carved by ancient glaciers over thousands of years.','نُحتت المضايق البحرية النرويجية بواسطة أنهار جليدية قديمة على مدى آلاف السنين.','extended','C1','CEFR-J'],
  ['photosynthesis','noun','تمثيل ضوئي','Photosynthesis in marine algae produces much of the world oxygen.','ينتج التمثيل الضوئي في الطحالب البحرية كثيراً من أكسجين العالم.','extended','B2','CEFR-J'],
  ['symbiosis','noun','تكافل','Coral reefs demonstrate remarkable examples of marine symbiosis.','تُظهر الشعاب المرجانية أمثلة رائعة على التكافل البحري.','extended','C1','CEFR-J'],
  ['volcanic','adjective','بركاني','Volcanic activity on the ocean floor creates new underwater mountains.','يُنشئ النشاط البركاني في قاع المحيط جبالاً جديدة تحت الماء.','core','B2','CEFR-J'],
  ['microscopic','adjective','مجهري','Microscopic organisms play a crucial role in ocean nutrient cycles.','تلعب الكائنات المجهرية دوراً حاسماً في دورات المغذيات البحرية.','core','B2','CEFR-J'],
  ['catastrophic','adjective','كارثي','Oil spills can have catastrophic effects on marine ecosystems.','يمكن أن يكون للتسربات النفطية تأثيرات كارثية على النظم البيئية البحرية.','core','B2','CEFR-J'],
  ['toxic','adjective','سام','Toxic waste dumped in oceans poses a severe threat to marine life.','تُشكّل النفايات السامة المُلقاة في المحيطات تهديداً خطيراً للحياة البحرية.','core','B2','CEFR-J'],
  ['pristine','adjective','نقي / أصلي','Few pristine ocean environments remain untouched by human activity.','بقيت قلة من البيئات المحيطية النقية دون تأثر بالنشاط البشري.','extended','C1','CEFR-J'],
  ['autonomous','adjective','مستقل / ذاتي','Autonomous underwater vehicles can explore regions too dangerous for divers.','يمكن للمركبات تحت الماء المستقلة استكشاف مناطق خطيرة جداً على الغواصين.','extended','B2','AWL'],
  ['geothermal','adjective','حراري أرضي','Geothermal energy from ocean vents could provide sustainable power.','يمكن للطاقة الحرارية الأرضية من فتحات المحيط توفير طاقة مستدامة.','extended','B2','CEFR-J'],
  ['invertebrate','noun','لافقاري','Most deep-sea creatures are invertebrates without a bony skeleton.','معظم مخلوقات أعماق البحار لافقاريات بدون هيكل عظمي.','extended','B2','CEFR-J'],
  ['camouflage','noun','تمويه','Many ocean creatures use camouflage to hide from predators.','يستخدم كثير من مخلوقات المحيط التمويه للاختباء من المفترسين.','core','B2','CEFR-J'],
  ['migration','noun','هجرة','The annual whale migration covers thousands of kilometers across oceans.','تغطي هجرة الحيتان السنوية آلاف الكيلومترات عبر المحيطات.','core','B2','CEFR-J'],
  ['geology','noun','جيولوجيا','Marine geology studies the structure and composition of the ocean floor.','تدرس الجيولوجيا البحرية بنية وتركيب قاع المحيط.','core','B2','CEFR-J'],
  ['specimen','noun','عيّنة','Researchers collected rare specimens from the deep ocean trench.','جمع الباحثون عينات نادرة من خندق المحيط العميق.','core','B2','CEFR-J'],
  ['satellite','noun','قمر صناعي','Satellites help scientists monitor ocean temperatures from space.','تساعد الأقمار الصناعية العلماء في مراقبة درجات حرارة المحيط من الفضاء.','core','B1','CEFR-J'],
  ['circulation','noun','دوران','Ocean circulation patterns distribute heat across the entire planet.','توزّع أنماط دوران المحيط الحرارة عبر الكوكب بأكمله.','extended','B2','CEFR-J'],
  ['saline','adjective','ملحي','Saline water makes up over ninety-seven percent of Earth water.','يُشكّل الماء الملحي أكثر من سبعة وتسعين بالمئة من مياه الأرض.','extended','C1','CEFR-J'],
  ['maritime','adjective','بحري','Maritime law governs international shipping and ocean resources.','يحكم القانون البحري الشحن الدولي وموارد المحيط.','extended','B2','CEFR-J'],
  ['deterioration','noun','تدهور','The rapid deterioration of coral reefs alarmed marine scientists.','أثار التدهور السريع للشعاب المرجانية قلق علماء البحار.','extended','B2','CEFR-J'],
  ['specimen','noun','نموذج','The preserved specimen was displayed in the natural history museum.','عُرض النموذج المحفوظ في متحف التاريخ الطبيعي.','core','B2','CEFR-J'],
  ['cartography','noun','رسم الخرائط','Ocean cartography has been revolutionized by satellite technology.','أحدثت تقنية الأقمار الصناعية ثورة في رسم خرائط المحيطات.','mastery','C1','CEFR-J'],
  ['bathymetry','noun','قياس أعماق البحار','Bathymetry data reveals the complex topography of the ocean floor.','تكشف بيانات قياس الأعماق عن التضاريس المعقدة لقاع المحيط.','mastery','C1','CEFR-J'],
  ['desalination','noun','تحلية','Desalination plants convert seawater into fresh drinking water.','تحوّل محطات التحلية مياه البحر إلى مياه شرب عذبة.','extended','B2','NAWL'],
  ['oceanography','noun','علم المحيطات','Modern oceanography uses robots and satellites to study the deep sea.','يستخدم علم المحيطات الحديث الروبوتات والأقمار الصناعية لدراسة أعماق البحر.','extended','B2','CEFR-J'],
  ['luminous','adjective','مضيء / متوهج','Luminous creatures light up the midnight zone of the ocean.','تُضيء الكائنات المتوهجة منطقة منتصف الليل في المحيط.','extended','B2','CEFR-J'],
  ['pelagic','adjective','سطحي بحري / بيلاجي','Pelagic fish live in the open ocean rather than near the coast.','تعيش الأسماك السطحية في المحيط المفتوح بدلاً من قرب الساحل.','mastery','C1','CEFR-J'],
  ['endemic','adjective','متوطن (بيئي)','Many endemic species are found only in specific ocean regions.','توجد أنواع متوطنة كثيرة فقط في مناطق محيطية محددة.','mastery','C1','CEFR-J'],
  ['abyssal','adjective','سحيق','The abyssal zone of the ocean receives no sunlight at all.','لا تتلقى المنطقة السحيقة من المحيط أي ضوء شمس على الإطلاق.','mastery','C1','CEFR-J'],
  ['benthic','adjective','قاعي','Benthic organisms live on or near the ocean floor.','تعيش الكائنات القاعية على قاع المحيط أو بالقرب منه.','mastery','C1','CEFR-J'],
  ['phytoplankton','noun','عوالق نباتية','Phytoplankton produce approximately fifty percent of Earth oxygen.','تنتج العوالق النباتية ما يقارب خمسين بالمئة من أكسجين الأرض.','mastery','C1','CEFR-J'],
  ['upwelling','noun','تيار صاعد','Coastal upwelling brings nutrient-rich water from the deep ocean.','يجلب التيار الصاعد الساحلي مياهاً غنية بالمغذيات من أعماق المحيط.','mastery','C1','CEFR-J'],
  ['resilience','noun','مرونة / قدرة على التعافي','The resilience of marine ecosystems depends on biodiversity levels.','تعتمد مرونة النظم البيئية البحرية على مستويات التنوع البيولوجي.','core','B2','NAWL'],
  ['sustainable','adjective','مستدام','Sustainable fishing practices protect ocean resources for future generations.','تحمي ممارسات الصيد المستدام موارد المحيط للأجيال القادمة.','core','B2','NAWL'],
  ['exploit','verb','يستغل','Nations must avoid exploiting deep-sea resources irresponsibly.','يجب على الدول تجنب استغلال موارد أعماق البحار بشكل غير مسؤول.','core','B2','AWL'],
  ['monitor','verb','يرصد / يراقب','Scientists monitor ocean temperature changes using advanced sensors.','يرصد العلماء تغيرات درجة حرارة المحيط باستخدام أجهزة استشعار متقدمة.','core','B2','AWL'],
  ['restore','verb','يستعيد / يرمّم','Conservation efforts aim to restore damaged coral reef ecosystems.','تهدف جهود الحفظ إلى ترميم نظم الشعاب المرجانية المتضررة.','core','B2','AWL'],
  ['accumulate','verb','يتراكم','Plastic waste continues to accumulate in the world oceans.','تستمر النفايات البلاستيكية في التراكم في محيطات العالم.','extended','B2','AWL'],
  ['deteriorate','verb','يتدهور','Water quality near industrial areas continues to deteriorate rapidly.','تستمر جودة المياه بالقرب من المناطق الصناعية في التدهور بسرعة.','extended','B2','CEFR-J'],
  ['propagate','verb','ينتشر / يتكاثر','Sound waves propagate much faster through water than through air.','تنتشر الموجات الصوتية في الماء أسرع بكثير منها في الهواء.','mastery','C1','CEFR-J'],
  ['stratify','verb','يتطبّق / يتراتب','Ocean water stratifies into distinct layers based on temperature and salinity.','يتطبّق ماء المحيط إلى طبقات متميزة بناءً على درجة الحرارة والملوحة.','mastery','C1','CEFR-J'],
  ['bleach','verb','يبيّض','Rising ocean temperatures cause coral reefs to bleach and die.','تتسبب درجات حرارة المحيط المرتفعة في تبييض الشعاب المرجانية وموتها.','extended','B2','CEFR-J'],
  ['undulate','verb','يتموّج','Sea grasses undulate gently in the rhythmic ocean currents.','تتموّج الأعشاب البحرية بلطف في التيارات المحيطية الإيقاعية.','mastery','C1','CEFR-J'],
  ['inhabit','verb','يسكن / يقطن','Bizarre creatures inhabit the extreme environments of ocean trenches.','تسكن مخلوقات غريبة البيئات القاسية لخنادق المحيط.','core','B2','CEFR-J'],
  ['spawn','verb','يُفرخ / يبيض','Salmon return to their birthplace to spawn in freshwater rivers.','يعود السلمون إلى مسقط رأسه لوضع البيض في أنهار المياه العذبة.','extended','C1','CEFR-J'],
  ['thermohaline','adjective','حراري ملحي','The thermohaline circulation drives global ocean current patterns.','تُحرّك الدورة الحرارية الملحية أنماط التيارات المحيطية العالمية.','mastery','C1','CEFR-J'],
  ['intertidal','adjective','بين مدّي','Intertidal zones experience dramatic changes between high and low tides.','تشهد المناطق بين المدّية تغيرات كبيرة بين المد العالي والمنخفض.','mastery','C1','CEFR-J'],
  ['unprecedented','adjective','غير مسبوق','The expedition made unprecedented discoveries at record-breaking depths.','حققت الرحلة الاستكشافية اكتشافات غير مسبوقة في أعماق قياسية.','core','B2','AWL'],
  ['fragile','adjective','هش','Deep-sea ecosystems are extremely fragile and slow to recover.','النظم البيئية في أعماق البحار هشة للغاية وبطيئة التعافي.','core','B2','CEFR-J'],
  ['prolific','adjective','غزير الإنتاج','The coral reef is one of the most prolific ecosystems on Earth.','الشعاب المرجانية من أكثر النظم البيئية غزارة في الإنتاج على الأرض.','extended','C1','CEFR-J'],
  ['desolate','adjective','مقفر / خالٍ','The deepest ocean floors may appear desolate but teem with life.','قد تبدو أعماق قاع المحيط مقفرة لكنها تعج بالحياة.','extended','C1','CEFR-J'],
  ['buoyancy','noun','طفو','Marine animals rely on buoyancy to move efficiently through water.','تعتمد الحيوانات البحرية على الطفو للتحرك بكفاءة في الماء.','extended','B2','CEFR-J'],
  ['archipelago','noun','أرخبيل','The Indonesian archipelago contains some of the richest marine biodiversity.','يحتوي الأرخبيل الإندونيسي على أغنى التنوع البيولوجي البحري.','extended','C1','CEFR-J'],
  ['tributary','noun','رافد','River tributaries carry sediments and nutrients into the ocean.','تحمل الروافد النهرية الرواسب والمغذيات إلى المحيط.','extended','B2','CEFR-J'],
  ['phosphorescent','adjective','فسفوري / متوهج','Phosphorescent waves create a magical glow along tropical beaches.','تخلق الأمواج الفسفورية توهجاً ساحراً على الشواطئ الاستوائية.','mastery','C1','CEFR-J'],
];

// Unit 3 - Food Security
const U3 = [
  ['agriculture','noun','زراعة','Modern agriculture relies heavily on technology and data analysis.','تعتمد الزراعة الحديثة بشكل كبير على التكنولوجيا وتحليل البيانات.','core','B1','CEFR-J'],
  ['harvest','noun','حصاد','The annual wheat harvest was affected by severe drought conditions.','تأثر حصاد القمح السنوي بظروف الجفاف الشديد.','core','B1','CEFR-J'],
  ['irrigation','noun','ري','Efficient irrigation systems conserve water in arid farming regions.','تحافظ أنظمة الري الفعالة على المياه في مناطق الزراعة الجافة.','core','B2','CEFR-J'],
  ['fertilizer','noun','سماد','Organic fertilizers improve soil health without harmful chemicals.','تُحسّن الأسمدة العضوية صحة التربة دون مواد كيميائية ضارة.','core','B2','CEFR-J'],
  ['pesticide','noun','مبيد حشري','Reducing pesticide use protects beneficial insects like honeybees.','يحمي تقليل استخدام المبيدات الحشرية الحشرات المفيدة كنحل العسل.','core','B2','CEFR-J'],
  ['famine','noun','مجاعة','War and climate change are the leading causes of famine today.','الحرب وتغير المناخ هما السببان الرئيسيان للمجاعة اليوم.','core','B2','CEFR-J'],
  ['crop','noun','محصول','Rice is the most important crop for feeding the global population.','الأرز هو أهم محصول لإطعام سكان العالم.','core','B1','CEFR-J'],
  ['drought','noun','جفاف','Prolonged drought has devastated farming communities across the region.','دمّر الجفاف المطوّل المجتمعات الزراعية في جميع أنحاء المنطقة.','core','B2','CEFR-J'],
  ['yield','noun','إنتاجية / محصول','New seed varieties have significantly increased crop yield per hectare.','زادت أصناف البذور الجديدة إنتاجية المحصول لكل هكتار بشكل كبير.','core','B2','AWL'],
  ['livestock','noun','ماشية','Sustainable livestock farming reduces greenhouse gas emissions.','تُقلل تربية الماشية المستدامة من انبعاثات الغازات الدفيئة.','core','B2','CEFR-J'],
  ['nutrition','noun','تغذية','Proper nutrition is essential for children physical and mental development.','التغذية السليمة ضرورية للنمو البدني والعقلي للأطفال.','core','B1','CEFR-J'],
  ['organic','adjective','عضوي','Demand for organic food products has grown steadily in recent years.','نما الطلب على المنتجات الغذائية العضوية بشكل مطّرد في السنوات الأخيرة.','core','B2','CEFR-J'],
  ['sustainable','adjective','مستدام','Sustainable farming practices preserve soil quality for future generations.','تحافظ ممارسات الزراعة المستدامة على جودة التربة للأجيال القادمة.','core','B2','NAWL'],
  ['cultivate','verb','يزرع / يحرث','Farmers in the region cultivate rice using traditional methods.','يزرع المزارعون في المنطقة الأرز باستخدام الطرق التقليدية.','core','B2','CEFR-J'],
  ['distribute','verb','يوزّع','Aid organizations distribute food supplies to disaster-affected areas.','توزّع منظمات الإغاثة الإمدادات الغذائية على المناطق المتضررة من الكوارث.','core','B2','AWL'],
  ['scarcity','noun','ندرة / شُح','Water scarcity is the biggest challenge facing desert farmers.','ندرة المياه هي أكبر تحدٍّ يواجه مزارعي الصحراء.','core','B2','CEFR-J'],
  ['malnutrition','noun','سوء تغذية','Childhood malnutrition remains a serious problem in developing nations.','لا يزال سوء تغذية الأطفال مشكلة خطيرة في الدول النامية.','core','B2','CEFR-J'],
  ['genetically','adverb','وراثياً','Genetically modified crops can resist pests and require less water.','يمكن للمحاصيل المعدّلة وراثياً مقاومة الآفات واستهلاك كميات أقل من الماء.','core','B2','CEFR-J'],
  ['subsistence','noun','كفاف','Millions of farmers still practice subsistence agriculture worldwide.','لا يزال ملايين المزارعين يمارسون زراعة الكفاف حول العالم.','extended','B2','CEFR-J'],
  ['greenhouse','noun','دفيئة / بيت زجاجي','Greenhouse technology enables year-round vegetable production in cold climates.','تُتيح تقنية البيوت الزجاجية إنتاج الخضروات على مدار العام في المناخات الباردة.','core','B2','CEFR-J'],
  ['arable','adjective','صالح للزراعة','Only a small percentage of the Earth land is considered arable.','تُعتبر نسبة صغيرة فقط من أراضي الأرض صالحة للزراعة.','extended','C1','CEFR-J'],
  ['commodity','noun','سلعة','Wheat and corn are among the most traded agricultural commodities.','القمح والذرة من بين أكثر السلع الزراعية تداولاً.','core','B2','AWL'],
  ['contamination','noun','تلوث','Food contamination can cause widespread illness and economic losses.','يمكن أن يسبب تلوث الغذاء مرضاً واسع النطاق وخسائر اقتصادية.','core','B2','CEFR-J'],
  ['preservation','noun','حفظ','Food preservation techniques extend shelf life and reduce waste.','تُطيل تقنيات حفظ الغذاء فترة الصلاحية وتُقلل الهدر.','core','B2','CEFR-J'],
  ['supply chain','noun','سلسلة إمداد','Disruptions to the global supply chain affect food prices everywhere.','تؤثر اضطرابات سلسلة الإمداد العالمية على أسعار الغذاء في كل مكان.','core','B2','NAWL'],
  ['productivity','noun','إنتاجية','Agricultural productivity has increased dramatically with modern technology.','زادت الإنتاجية الزراعية بشكل كبير مع التكنولوجيا الحديثة.','core','B2','AWL'],
  ['subsidize','verb','يدعم مالياً','Many governments subsidize farmers to keep food prices affordable.','تدعم حكومات كثيرة المزارعين للحفاظ على أسعار غذاء معقولة.','extended','B2','AWL'],
  ['deplete','verb','يستنفد / ينضب','Intensive farming practices deplete essential soil nutrients over time.','تستنفد ممارسات الزراعة المكثفة المغذيات الأساسية للتربة بمرور الوقت.','extended','B2','CEFR-J'],
  ['alleviate','verb','يخفف','International aid programs aim to alleviate hunger in affected regions.','تهدف برامج المعونة الدولية إلى تخفيف الجوع في المناطق المتضررة.','core','B2','CEFR-J'],
  ['innovate','verb','يبتكر','Farmers must innovate to produce more food with fewer resources.','يجب على المزارعين الابتكار لإنتاج مزيد من الغذاء بموارد أقل.','core','B2','AWL'],
  ['diversify','verb','ينوّع','Farmers who diversify their crops reduce the risk of total loss.','المزارعون الذين ينوّعون محاصيلهم يُقللون خطر الخسارة الكلية.','extended','B2','AWL'],
  ['stockpile','verb','يُخزّن / يُكدّس','Countries stockpile grain reserves as protection against future shortages.','تُخزّن الدول احتياطيات الحبوب كحماية ضد النقص المستقبلي.','extended','B2','CEFR-J'],
  ['contaminate','verb','يلوّث','Chemical runoff from farms can contaminate nearby water sources.','يمكن لجريان المواد الكيميائية من المزارع تلويث مصادر المياه القريبة.','core','B2','CEFR-J'],
  ['fertile','adjective','خصب','The Nile Delta has some of the most fertile soil in the world.','يمتلك دلتا النيل بعضاً من أخصب التربة في العالم.','core','B2','CEFR-J'],
  ['arid','adjective','قاحل / جاف','Arid regions face unique challenges in achieving food security.','تواجه المناطق القاحلة تحديات فريدة في تحقيق الأمن الغذائي.','extended','B2','CEFR-J'],
  ['perishable','adjective','قابل للتلف','Perishable foods require cold storage to maintain quality and safety.','تتطلب الأطعمة القابلة للتلف تخزيناً بارداً للحفاظ على الجودة والسلامة.','extended','B2','CEFR-J'],
  ['transgenic','adjective','مُعدّل وراثياً','Transgenic crops have been engineered to resist specific pests.','هُندست المحاصيل المعدّلة وراثياً لمقاومة آفات محددة.','mastery','C1','CEFR-J'],
  ['hydroponics','noun','زراعة مائية','Hydroponics allows food production without soil in controlled environments.','تسمح الزراعة المائية بإنتاج الغذاء بدون تربة في بيئات محكومة.','extended','B2','CEFR-J'],
  ['aquaculture','noun','تربية أحياء مائية','Aquaculture now supplies more than half of the world seafood.','توفر تربية الأحياء المائية الآن أكثر من نصف المأكولات البحرية في العالم.','extended','B2','NAWL'],
  ['monoculture','noun','زراعة أحادية','Monoculture farming increases vulnerability to disease and pest outbreaks.','تزيد الزراعة الأحادية من قابلية التأثر بتفشي الأمراض والآفات.','mastery','C1','NAWL'],
  ['permaculture','noun','زراعة مستدامة','Permaculture designs create self-sustaining food production systems.','تُنشئ تصاميم الزراعة المستدامة أنظمة إنتاج غذاء ذاتية الاستدامة.','mastery','C1','CEFR-J'],
  ['agribusiness','noun','أعمال زراعية','Large agribusiness corporations control much of the global food supply.','تسيطر شركات الأعمال الزراعية الكبيرة على كثير من الإمدادات الغذائية العالمية.','extended','B2','NAWL'],
  ['insecticide','noun','مبيد حشرات','Excessive insecticide use has led to declining bee populations.','أدى الاستخدام المفرط للمبيدات الحشرية إلى تراجع أعداد النحل.','extended','B2','CEFR-J'],
  ['herbicide','noun','مبيد أعشاب','Herbicides control weeds but can harm beneficial plants nearby.','تُسيطر مبيدات الأعشاب على الحشائش لكن قد تضر بنباتات مفيدة قريبة.','extended','B2','CEFR-J'],
  ['pollinate','verb','يُلقّح','Bees pollinate approximately one-third of the crops humans consume.','يُلقّح النحل ما يقارب ثلث المحاصيل التي يستهلكها البشر.','extended','B2','CEFR-J'],
  ['compost','noun','سماد عضوي','Kitchen waste can be turned into nutrient-rich compost for gardens.','يمكن تحويل نفايات المطبخ إلى سماد عضوي غني بالمغذيات للحدائق.','extended','B2','CEFR-J'],
  ['terrain','noun','تضاريس','Mountainous terrain makes large-scale farming extremely difficult.','تجعل التضاريس الجبلية الزراعة واسعة النطاق صعبة للغاية.','core','B2','CEFR-J'],
  ['surplus','noun','فائض','Agricultural surplus in wealthy nations contrasts with hunger elsewhere.','يتناقض الفائض الزراعي في الدول الغنية مع الجوع في أماكن أخرى.','core','B2','AWL'],
  ['quota','noun','حصة','Import quotas protect domestic farmers from cheap foreign competition.','تحمي حصص الاستيراد المزارعين المحليين من المنافسة الأجنبية الرخيصة.','extended','B2','AWL'],
  ['logistics','noun','لوجستيات','Efficient logistics ensure fresh food reaches markets before spoiling.','تضمن اللوجستيات الفعالة وصول الغذاء الطازج للأسواق قبل تلفه.','core','B2','NAWL'],
  ['warehouse','noun','مستودع','The food warehouse stores thousands of tons of emergency supplies.','يُخزّن مستودع الغذاء آلاف الأطنان من الإمدادات الطارئة.','core','B1','CEFR-J'],
  ['export','verb','يصدّر','Brazil exports more coffee than any other country in the world.','تصدّر البرازيل قهوة أكثر من أي دولة أخرى في العالم.','core','B1','AWL'],
  ['import','verb','يستورد','Many desert countries import the majority of their food supply.','تستورد كثير من دول الصحراء غالبية إمداداتها الغذائية.','core','B1','AWL'],
  ['regulate','verb','يُنظّم','Governments regulate food safety standards to protect public health.','تُنظّم الحكومات معايير سلامة الغذاء لحماية الصحة العامة.','core','B2','AWL'],
  ['sanitation','noun','صرف صحي / نظافة','Poor sanitation in food processing plants can cause disease outbreaks.','يمكن أن يسبب سوء الصرف الصحي في مصانع تجهيز الأغذية تفشي الأمراض.','core','B2','CEFR-J'],
  ['infrastructure','noun','بنية تحتية','Rural areas often lack the infrastructure for efficient food distribution.','غالباً ما تفتقر المناطق الريفية للبنية التحتية لتوزيع الغذاء بكفاءة.','core','B2','AWL'],
  ['deforestation','noun','إزالة الغابات','Deforestation for farmland threatens global biodiversity and climate.','تُهدد إزالة الغابات من أجل الأراضي الزراعية التنوع البيولوجي والمناخ.','core','B2','NAWL'],
  ['erosion','noun','تآكل التربة','Soil erosion reduces farmland productivity and pollutes waterways.','يُقلل تآكل التربة من إنتاجية الأراضي الزراعية ويُلوّث المجاري المائية.','core','B2','CEFR-J'],
  ['precipitation','noun','هطول','Unpredictable precipitation patterns threaten food production worldwide.','تُهدد أنماط الهطول غير المتوقعة إنتاج الغذاء في جميع أنحاء العالم.','extended','B2','CEFR-J'],
  ['biofortification','noun','تحصين حيوي','Biofortification adds essential vitamins to staple crops through breeding.','يُضيف التحصين الحيوي فيتامينات أساسية للمحاصيل الرئيسية من خلال التهجين.','mastery','C1','NAWL'],
  ['desertification','noun','تصحّر','Desertification threatens millions of hectares of productive farmland.','يُهدد التصحّر ملايين الهكتارات من الأراضي الزراعية المنتجة.','extended','B2','NAWL'],
  ['biodegradable','adjective','قابل للتحلل','Biodegradable packaging reduces environmental impact of food products.','يُقلل التغليف القابل للتحلل من الأثر البيئي للمنتجات الغذائية.','extended','B2','NAWL'],
  ['agronomist','noun','مهندس زراعي','The agronomist recommended new soil management techniques for the farm.','أوصى المهندس الزراعي بتقنيات إدارة تربة جديدة للمزرعة.','mastery','C1','CEFR-J'],
  ['photovoltaic','adjective','كهروضوئي','Photovoltaic panels power irrigation systems in remote desert farms.','تُشغّل الألواح الكهروضوئية أنظمة الري في مزارع الصحراء النائية.','mastery','C1','NAWL'],
  ['pasteurize','verb','يبستر','Milk must be pasteurized to kill harmful bacteria before consumption.','يجب بسترة الحليب لقتل البكتيريا الضارة قبل الاستهلاك.','extended','B2','CEFR-J'],
  ['ferment','verb','يُخمّر','Many cultures ferment vegetables as a traditional preservation method.','تُخمّر ثقافات كثيرة الخضروات كطريقة حفظ تقليدية.','extended','B2','CEFR-J'],
  ['self-sufficient','adjective','مكتفٍ ذاتياً','Very few countries are completely self-sufficient in food production.','قليل جداً من الدول مكتفية ذاتياً بالكامل في إنتاج الغذاء.','core','B2','CEFR-J'],
  ['vulnerable','adjective','هش / معرّض','Developing nations are most vulnerable to global food price spikes.','الدول النامية هي الأكثر عرضة لارتفاعات أسعار الغذاء العالمية.','core','B2','CEFR-J'],
  ['equitable','adjective','عادل / منصف','Equitable food distribution remains one of humanity greatest challenges.','يظل التوزيع العادل للغذاء أحد أكبر تحديات البشرية.','extended','B2','AWL'],
  ['staple','adjective','أساسي / رئيسي','Rice is the staple food for more than half the world population.','الأرز هو الغذاء الأساسي لأكثر من نصف سكان العالم.','core','B2','CEFR-J'],
  ['edible','adjective','صالح للأكل','Many wild plants are edible but require knowledge to identify safely.','كثير من النباتات البرية صالحة للأكل لكن تتطلب معرفة لتحديدها بأمان.','core','B2','CEFR-J'],
  ['nutritious','adjective','مغذٍّ','School lunch programs should provide nutritious meals for all children.','يجب أن توفر برامج وجبات المدرسة وجبات مغذية لجميع الأطفال.','core','B2','CEFR-J'],
  ['perishable','adjective','قابل للتلف','Transporting perishable goods requires specialized refrigerated vehicles.','يتطلب نقل البضائع القابلة للتلف مركبات مبرّدة متخصصة.','extended','B2','CEFR-J'],
  ['degradation','noun','تدهور','Land degradation is reducing the amount of farmable soil worldwide.','يُقلل تدهور الأراضي كمية التربة الصالحة للزراعة عالمياً.','extended','B2','AWL'],
  ['vegetation','noun','غطاء نباتي','Dense vegetation helps prevent soil erosion on hillsides.','يُساعد الغطاء النباتي الكثيف في منع تآكل التربة على التلال.','core','B2','CEFR-J'],
  ['germinate','verb','ينبت / يتبرعم','Seeds need moisture and warmth to germinate successfully.','تحتاج البذور للرطوبة والدفء لتنبت بنجاح.','extended','B2','CEFR-J'],
  ['rotate','verb','يُناوب (المحاصيل)','Farmers rotate crops each season to maintain soil fertility.','يُناوب المزارعون المحاصيل كل موسم للحفاظ على خصوبة التربة.','core','B2','AWL'],
  ['eradicate','verb','يستأصل','International programs aim to eradicate extreme hunger by twenty-thirty.','تهدف البرامج الدولية لاستئصال الجوع المدقع بحلول عام ألفين وثلاثين.','extended','C1','CEFR-J'],
  ['fortify','verb','يُدعّم / يُقوّي','Food manufacturers fortify cereals with essential vitamins and minerals.','يُدعّم مصنّعو الأغذية الحبوب بفيتامينات ومعادن أساسية.','extended','B2','CEFR-J'],
  ['drought-resistant','adjective','مقاوم للجفاف','Scientists have developed drought-resistant wheat varieties for arid regions.','طوّر العلماء أصناف قمح مقاومة للجفاف للمناطق القاحلة.','extended','B2','CEFR-J'],
  ['precision','noun','دقة','Precision agriculture uses GPS and sensors to optimize farming efficiency.','تستخدم الزراعة الدقيقة نظام تحديد المواقع وأجهزة الاستشعار لتحسين الكفاءة.','core','B2','AWL'],
  ['subsidy','noun','دعم / إعانة','Government subsidies help farmers invest in modern equipment.','تُساعد الإعانات الحكومية المزارعين على الاستثمار في المعدات الحديثة.','extended','B2','AWL'],
  ['tariff','noun','تعريفة جمركية','High import tariffs on food products protect local agricultural industries.','تحمي التعريفات الجمركية العالية على المنتجات الغذائية الصناعات الزراعية المحلية.','extended','B2','NAWL'],
  ['traceability','noun','إمكانية التتبع','Food traceability systems help identify the source of contamination quickly.','تُساعد أنظمة تتبع الغذاء في تحديد مصدر التلوث بسرعة.','mastery','C1','NAWL'],
  ['genotype','noun','تركيب وراثي','Selecting the right crop genotype is crucial for maximizing yield.','اختيار التركيب الوراثي المناسب للمحصول أمر حاسم لتعظيم الإنتاجية.','mastery','C1','CEFR-J'],
  ['photosynthesis','noun','عملية التمثيل الضوئي','Improving photosynthesis efficiency could dramatically increase crop yields.','يمكن لتحسين كفاءة التمثيل الضوئي زيادة إنتاجية المحاصيل بشكل كبير.','extended','B2','CEFR-J'],
  ['pathogen','noun','ممرض','New crop pathogens emerge as climate conditions change globally.','تظهر ممرضات محاصيل جديدة مع تغير الظروف المناخية عالمياً.','extended','B2','CEFR-J'],
  ['micronutrient','noun','مغذٍّ دقيق','Micronutrient deficiencies affect billions of people worldwide.','يؤثر نقص المغذيات الدقيقة على مليارات الأشخاص حول العالم.','extended','C1','NAWL'],
  ['agroforestry','noun','حراجة زراعية','Agroforestry combines trees and crops on the same land for mutual benefit.','تجمع الحراجة الزراعية بين الأشجار والمحاصيل على نفس الأرض لمنفعة متبادلة.','mastery','C1','NAWL'],
  ['biofuel','noun','وقود حيوي','Growing crops for biofuel competes with food production for land.','تتنافس زراعة محاصيل الوقود الحيوي مع إنتاج الغذاء على الأرض.','extended','B2','NAWL'],
  ['greenhouse effect','noun','تأثير الدفيئة','The greenhouse effect is accelerating climate change and threatening agriculture.','يُسرّع تأثير الدفيئة تغير المناخ ويُهدد الزراعة.','core','B2','CEFR-J'],
];

// Unit 4 - Biomimicry Design
const U4 = [
  ['biomimicry','noun','محاكاة حيوية','Biomimicry inspires engineers to design solutions based on nature.','تُلهم المحاكاة الحيوية المهندسين لتصميم حلول مستوحاة من الطبيعة.','core','B2','CEFR-J'],
  ['innovation','noun','ابتكار','Nature-inspired innovation has produced some remarkable technologies.','أنتج الابتكار المستوحى من الطبيعة بعض التقنيات الرائعة.','core','B2','AWL'],
  ['design','noun','تصميم','The building design was inspired by the structure of a beehive.','استُلهم تصميم المبنى من بنية خلية النحل.','core','B1','AWL'],
  ['prototype','noun','نموذج أولي','Engineers built a prototype based on the dragonfly wing structure.','بنى المهندسون نموذجاً أولياً مستنداً إلى بنية جناح اليعسوب.','core','B2','CEFR-J'],
  ['aerodynamic','adjective','انسيابي / ديناميكي هوائي','The aerodynamic shape of birds inspired faster train designs.','ألهم الشكل الانسيابي للطيور تصاميم قطارات أسرع.','core','B2','CEFR-J'],
  ['sustainable','adjective','مستدام','Biomimicry offers sustainable alternatives to traditional manufacturing.','تُقدّم المحاكاة الحيوية بدائل مستدامة للتصنيع التقليدي.','core','B2','NAWL'],
  ['mimic','verb','يحاكي / يقلّد','Scientists mimic spider silk to create incredibly strong fibers.','يحاكي العلماء حرير العنكبوت لإنشاء ألياف قوية بشكل لا يصدق.','core','B2','CEFR-J'],
  ['adapt','verb','يكيّف','Engineers adapt natural mechanisms for use in modern technology.','يكيّف المهندسون الآليات الطبيعية لاستخدامها في التكنولوجيا الحديثة.','core','B1','AWL'],
  ['structure','noun','بنية / هيكل','The honeycomb structure provides maximum strength with minimum material.','توفر بنية قرص العسل أقصى قوة بأقل مواد.','core','B1','AWL'],
  ['mechanism','noun','آلية','The gecko climbing mechanism inspired a new type of adhesive tape.','ألهمت آلية تسلق الوزغة نوعاً جديداً من الشريط اللاصق.','core','B2','AWL'],
  ['friction','noun','احتكاك','Shark skin reduces friction and improves swimming efficiency.','يُقلل جلد القرش الاحتكاك ويُحسّن كفاءة السباحة.','core','B2','CEFR-J'],
  ['durability','noun','متانة / دوام','Spider silk combines lightweight properties with remarkable durability.','يجمع حرير العنكبوت بين خفة الوزن والمتانة الرائعة.','core','B2','CEFR-J'],
  ['texture','noun','ملمس / نسيج','The lotus leaf texture repels water and keeps the surface clean.','يطرد ملمس ورقة اللوتس الماء ويُبقي السطح نظيفاً.','core','B2','CEFR-J'],
  ['velocity','noun','سرعة','The kingfisher beak shape allows trains to reach high velocity.','يسمح شكل منقار الرفراف للقطارات بالوصول إلى سرعة عالية.','extended','B2','CEFR-J'],
  ['resilient','adjective','مرن / متين','Bamboo is one of the most resilient natural building materials.','الخيزران أحد أكثر مواد البناء الطبيعية مرونة.','core','B2','CEFR-J'],
  ['synthetic','adjective','صناعي / تركيبي','Synthetic materials based on natural compounds are lighter and stronger.','المواد الصناعية المبنية على مركبات طبيعية أخف وأقوى.','core','B2','CEFR-J'],
  ['thermal','adjective','حراري','Termite mounds inspired thermal regulation systems in modern buildings.','ألهمت تلال النمل الأبيض أنظمة التنظيم الحراري في المباني الحديثة.','core','B2','CEFR-J'],
  ['efficiency','noun','كفاءة','Nature achieves maximum efficiency through millions of years of evolution.','تُحقق الطبيعة أقصى كفاءة عبر ملايين السنين من التطور.','core','B2','AWL'],
  ['photovoltaic','adjective','كهروضوئي','Leaf structures have inspired more efficient photovoltaic cell designs.','ألهمت بنية الأوراق تصاميم خلايا كهروضوئية أكثر كفاءة.','extended','C1','NAWL'],
  ['fiber','noun','ليف / ألياف','Spider silk fiber is five times stronger than steel of equal weight.','ألياف حرير العنكبوت أقوى بخمس مرات من الفولاذ بنفس الوزن.','core','B2','CEFR-J'],
  ['carbon','noun','كربون','Nature produces strong carbon structures without high temperatures.','تُنتج الطبيعة هياكل كربون قوية دون درجات حرارة عالية.','core','B2','CEFR-J'],
  ['organism','noun','كائن حي','Each organism offers potential design solutions for human challenges.','يُقدّم كل كائن حي حلول تصميم محتملة لتحديات بشرية.','core','B2','CEFR-J'],
  ['ecosystem','noun','نظام بيئي','Biomimicry considers entire ecosystem interactions not just single species.','تأخذ المحاكاة الحيوية بعين الاعتبار تفاعلات النظام البيئي بالكامل.','core','B2','CEFR-J'],
  ['adhesive','noun','لاصق','Gecko-inspired adhesives stick to surfaces without leaving residue.','تلتصق المواد اللاصقة المستوحاة من الوزغة بالأسطح دون ترك بقايا.','extended','B2','CEFR-J'],
  ['composite','noun','مادة مركّبة','Natural composites like bone combine flexibility with incredible strength.','تجمع المواد المركبة الطبيعية كالعظام بين المرونة والقوة المذهلة.','extended','B2','CEFR-J'],
  ['membrane','noun','غشاء','Cell membranes inspired new water filtration technology.','ألهمت أغشية الخلايا تقنية جديدة لترشيح المياه.','extended','B2','CEFR-J'],
  ['turbine','noun','توربين','Whale fin shapes improve wind turbine efficiency by twenty percent.','تُحسّن أشكال زعانف الحوت كفاءة توربينات الرياح بنسبة عشرين بالمئة.','core','B2','CEFR-J'],
  ['propulsion','noun','دفع','Jellyfish propulsion systems inspired more efficient underwater robots.','ألهمت أنظمة دفع قناديل البحر روبوتات أكثر كفاءة تحت الماء.','extended','C1','CEFR-J'],
  ['catalyst','noun','عامل محفّز','Natural catalysts work at normal temperatures unlike industrial ones.','تعمل المحفزات الطبيعية في درجات حرارة عادية بخلاف الصناعية.','extended','B2','AWL'],
  ['simulate','verb','يحاكي / يُنمذج','Computers can simulate natural processes to test biomimicry concepts.','يمكن للحواسيب محاكاة العمليات الطبيعية لاختبار مفاهيم المحاكاة الحيوية.','core','B2','AWL'],
  ['optimize','verb','يُحسّن / يُعظّم','Evolution has optimized natural designs over billions of years.','حسّن التطور التصاميم الطبيعية على مدى مليارات السنين.','core','B2','AWL'],
  ['fabricate','verb','يصنع / يُنتج','Researchers fabricate materials that replicate the properties of shells.','يصنع الباحثون مواد تحاكي خصائص الأصداف.','extended','B2','CEFR-J'],
  ['emulate','verb','يحاكي / يقتدي','Engineers emulate biological systems to solve complex design problems.','يحاكي المهندسون الأنظمة البيولوجية لحل مشاكل التصميم المعقدة.','extended','B2','CEFR-J'],
  ['patent','noun','براءة اختراع','The company filed a patent for their butterfly-inspired solar panel.','سجّلت الشركة براءة اختراع لألواحها الشمسية المستوحاة من الفراشة.','core','B2','CEFR-J'],
  ['renewable','adjective','متجدد','Biomimicry contributes to the development of renewable energy solutions.','تساهم المحاكاة الحيوية في تطوير حلول الطاقة المتجددة.','core','B2','NAWL'],
  ['biodegradable','adjective','قابل للتحلل الحيوي','Nature-inspired biodegradable plastics break down harmlessly in soil.','تتحلل البلاستيكيات القابلة للتحلل المستوحاة من الطبيعة دون ضرر في التربة.','extended','B2','NAWL'],
  ['waterproof','adjective','مقاوم للماء','Lotus-inspired coatings create naturally waterproof surfaces.','تُنشئ الطلاءات المستوحاة من اللوتس أسطحاً مقاومة للماء طبيعياً.','core','B2','CEFR-J'],
  ['lightweight','adjective','خفيف الوزن','Bird bone structure creates incredibly lightweight yet strong frameworks.','تُنشئ بنية عظام الطيور هياكل خفيفة الوزن لكن قوية بشكل لا يصدق.','core','B2','CEFR-J'],
  ['modular','adjective','نمطي / قابل للتجزئة','Modular design inspired by coral allows flexible building construction.','يسمح التصميم النمطي المستوحى من المرجان بإنشاء مبانٍ مرنة.','extended','B2','NAWL'],
  ['resin','noun','راتنج','Tree resin has inspired the development of new industrial adhesives.','ألهم راتنج الأشجار تطوير مواد لاصقة صناعية جديدة.','extended','B2','CEFR-J'],
  ['locomotion','noun','حركة / تنقل','Snake locomotion patterns inspired flexible robot designs.','ألهمت أنماط حركة الأفاعي تصاميم روبوتات مرنة.','mastery','C1','CEFR-J'],
  ['morphology','noun','علم الشكل / مورفولوجيا','Studying wing morphology helps design more efficient aircraft.','تُساعد دراسة مورفولوجيا الأجنحة في تصميم طائرات أكثر كفاءة.','mastery','C1','AWL'],
  ['tensile','adjective','شد / قوة شد','Spider silk has exceptional tensile strength relative to its weight.','لحرير العنكبوت قوة شد استثنائية بالنسبة لوزنه.','mastery','C1','CEFR-J'],
  ['hydrophobic','adjective','كاره للماء','Hydrophobic surfaces inspired by nature repel water effectively.','تطرد الأسطح الكارهة للماء المستوحاة من الطبيعة الماء بفعالية.','mastery','C1','CEFR-J'],
  ['piezoelectric','adjective','كهرضغطي','Piezoelectric materials in nature convert pressure into electrical energy.','تحوّل المواد الكهرضغطية في الطبيعة الضغط إلى طاقة كهربائية.','mastery','C1','NAWL'],
  ['nanotube','noun','أنبوب نانوي','Carbon nanotubes mimic the strength properties found in natural fibers.','تحاكي الأنابيب النانوية الكربونية خصائص القوة الموجودة في الألياف الطبيعية.','mastery','C1','CEFR-J'],
  ['elasticity','noun','مرونة','The elasticity of spider silk exceeds that of most synthetic materials.','تتجاوز مرونة حرير العنكبوت مرونة معظم المواد الصناعية.','extended','B2','CEFR-J'],
  ['rigid','adjective','صلب / جامد','Unlike rigid man-made structures nature uses flexible designs.','على عكس الهياكل الصلبة من صنع الإنسان تستخدم الطبيعة تصاميم مرنة.','core','B2','CEFR-J'],
  ['transparent','adjective','شفاف','Butterfly wing structures create transparent surfaces with unique properties.','تُنشئ بنية أجنحة الفراشات أسطحاً شفافة ذات خصائص فريدة.','core','B2','CEFR-J'],
  ['pigment','noun','صبغة','Structural color in butterflies comes from light not from chemical pigment.','يأتي اللون البنيوي في الفراشات من الضوء وليس من صبغة كيميائية.','extended','B2','CEFR-J'],
  ['versatile','adjective','متعدد الاستخدامات','Nature provides versatile solutions that work across many applications.','توفر الطبيعة حلولاً متعددة الاستخدامات تعمل في تطبيقات كثيرة.','core','B2','CEFR-J'],
  ['iteration','noun','تكرار / نسخة','Each design iteration brings the product closer to natural perfection.','يُقرّب كل تكرار للتصميم المنتج من الكمال الطبيعي.','extended','B2','AWL'],
  ['phenomenon','noun','ظاهرة','Bioluminescence is a natural phenomenon now used in medical imaging.','الإضاءة الحيوية ظاهرة طبيعية تُستخدم الآن في التصوير الطبي.','core','B2','AWL'],
  ['algorithm','noun','خوارزمية','Ant colony algorithms now solve complex logistics problems efficiently.','تحل خوارزميات مستعمرات النمل مشاكل لوجستية معقدة بكفاءة.','core','B2','NAWL'],
  ['synthesis','noun','تركيب / تخليق','Nature performs chemical synthesis at room temperature without waste.','تقوم الطبيعة بالتركيب الكيميائي في درجة حرارة الغرفة دون نفايات.','extended','B2','AWL'],
  ['evolution','noun','تطور','Millions of years of evolution have produced perfect natural designs.','أنتجت ملايين السنين من التطور تصاميم طبيعية مثالية.','core','B2','AWL'],
  ['habitat','noun','بيئة / موطن','Studying animal habitats reveals design principles for human buildings.','تكشف دراسة بيئات الحيوانات عن مبادئ تصميم للمباني البشرية.','core','B2','CEFR-J'],
  ['spectrum','noun','طيف','Butterfly wings manipulate the light spectrum to create vivid colors.','تتلاعب أجنحة الفراشات بالطيف الضوئي لإنشاء ألوان زاهية.','extended','B2','CEFR-J'],
  ['ventilation','noun','تهوية','Termite mound ventilation systems inspired passive building cooling.','ألهمت أنظمة تهوية تلال النمل التبريد السلبي للمباني.','extended','B2','CEFR-J'],
  ['capillary','adjective','شعيري','Capillary action in plants inspired new water transport technologies.','ألهمت الخاصية الشعرية في النباتات تقنيات نقل مياه جديدة.','mastery','C1','CEFR-J'],
  ['biomaterial','noun','مادة حيوية','Biomaterials from nature are being used in medical implants.','تُستخدم المواد الحيوية من الطبيعة في الزرعات الطبية.','extended','B2','NAWL'],
  ['replicate','verb','يستنسخ / يكرر','Scientists aim to replicate the self-healing properties of human skin.','يهدف العلماء إلى استنساخ خصائص الشفاء الذاتي لجلد الإنسان.','core','B2','AWL'],
  ['camouflage','noun','تمويه','Military camouflage technology was directly inspired by animal coloring.','استُلهمت تقنية التمويه العسكري مباشرة من تلوّن الحيوانات.','core','B2','CEFR-J'],
  ['echolocation','noun','تحديد الموقع بالصدى','Bat echolocation inspired the development of sonar navigation systems.','ألهم تحديد الموقع بالصدى لدى الخفافيش تطوير أنظمة ملاحة السونار.','extended','C1','CEFR-J'],
  ['metamorphosis','noun','تحوّل','Studying insect metamorphosis inspires transformable robot designs.','تُلهم دراسة تحوّل الحشرات تصاميم الروبوتات القابلة للتحول.','mastery','C1','CEFR-J'],
  ['photonic','adjective','ضوئي','Photonic crystals in beetle shells inspired new display technologies.','ألهمت البلورات الضوئية في أصداف الخنافس تقنيات عرض جديدة.','mastery','C1','CEFR-J'],
  ['iridescent','adjective','متقزّح / لامع','The iridescent colors of peacock feathers come from nanostructures.','تأتي الألوان المتقزّحة لريش الطاووس من البنى النانوية.','mastery','C1','CEFR-J'],
];

async function run() {
  const client = await pool.connect();
  try {
    const before = await client.query(`SELECT COUNT(*) AS cnt FROM vocab_staging_l4`);
    console.log('Before:', before.rows[0].cnt, 'words');

    const u1c = await insertBatch(client, U1_MORE, 1, 2);
    console.log(`U1 more: ${u1c} inserted (batch 2)`);

    const u2c = await insertBatch(client, U2, 2, 3);
    console.log(`U2: ${u2c} inserted (batch 3)`);

    const u3c = await insertBatch(client, U3, 3, 4);
    console.log(`U3: ${u3c} inserted (batch 4)`);

    const u4c = await insertBatch(client, U4, 4, 5);
    console.log(`U4: ${u4c} inserted (batch 5)`);

    const after = await client.query(`SELECT recommended_unit, COUNT(*) AS cnt FROM vocab_staging_l4 GROUP BY recommended_unit ORDER BY recommended_unit`);
    console.log('\n=== Per-unit totals ===');
    after.rows.forEach(r => console.log(`U${r.recommended_unit}: ${r.cnt}`));

    const total = await client.query(`SELECT COUNT(*) AS cnt FROM vocab_staging_l4`);
    console.log('\nTotal staged:', total.rows[0].cnt);
  } finally {
    client.release();
    pool.end();
  }
}

run().catch(e => console.error(e));
