const { Pool } = require('pg');
const pool = new Pool({ host: 'aws-1-eu-central-1.pooler.supabase.com', port: 5432, database: 'postgres', user: 'postgres.nmjexpuycmqcxuxljier', password: 'Ali-al-ahmad2000', ssl: { rejectUnauthorized: false } });

async function insertBatch(client, words, unitNumber, batchId) {
  let inserted = 0;
  for (const w of words) {
    try {
      await client.query(
        `INSERT INTO public.vocab_staging_l4 (word, pos, definition_ar, example_en, example_ar, recommended_tier, cefr_level, source_list, recommended_unit, batch_id) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) ON CONFLICT (word) DO NOTHING`,
        [w[0], w[1], w[2], w[3], w[4], w[5], w[6], w[7], unitNumber, batchId]
      );
      inserted++;
    } catch(e) { console.error(`Error "${w[0]}":`, e.message); }
  }
  return inserted;
}

const BATCH_ID = 31;

const u1 = [
["institutional review board","noun phrase","مجلس المراجعة المؤسسية","The institutional review board approved the clinical trial protocol.","وافق مجلس المراجعة المؤسسية على بروتوكول التجربة السريرية.","mastery","C1","COCA"],
["ethics committee","noun phrase","لجنة الأخلاقيات","The ethics committee reviewed the research proposal thoroughly.","راجعت لجنة الأخلاقيات مقترح البحث بدقة.","extended","C1","COCA"],
["informed consent form","noun phrase","نموذج الموافقة المستنيرة","Every participant must sign an informed consent form before enrollment.","يجب على كل مشارك توقيع نموذج الموافقة المستنيرة قبل التسجيل.","mastery","C1","COCA"],
["data safety monitoring board","noun phrase","مجلس مراقبة سلامة البيانات","The data safety monitoring board recommended continuing the trial.","أوصى مجلس مراقبة سلامة البيانات بمواصلة التجربة.","mastery","C1","AWL"],
["adverse event reporting","noun phrase","الإبلاغ عن الأحداث الضارة","Adverse event reporting is mandatory in all clinical studies.","الإبلاغ عن الأحداث الضارة إلزامي في جميع الدراسات السريرية.","mastery","C1","COCA"],
["serious adverse event","noun phrase","حدث ضار خطير","A serious adverse event led to the suspension of the trial.","أدى حدث ضار خطير إلى تعليق التجربة.","extended","B2","COCA"],
["dose-limiting toxicity","noun phrase","السمية المحددة للجرعة","Dose-limiting toxicity was observed at the highest dose level.","لوحظت السمية المحددة للجرعة عند أعلى مستوى جرعة.","mastery","C1","COCA"],
["maximum tolerated dose","noun phrase","الجرعة القصوى المحتملة","Researchers determined the maximum tolerated dose in phase I.","حدد الباحثون الجرعة القصوى المحتملة في المرحلة الأولى.","mastery","C1","COCA"],
["recommended phase II dose","noun phrase","الجرعة الموصى بها للمرحلة الثانية","The recommended phase II dose was established after escalation.","تم تحديد الجرعة الموصى بها للمرحلة الثانية بعد التصعيد.","mastery","C1","AWL"],
["pharmacokinetics study","noun phrase","دراسة الحرائك الدوائية","A pharmacokinetics study measured drug absorption rates.","قاست دراسة الحرائك الدوائية معدلات امتصاص الدواء.","extended","B2","COCA"],
["pharmacodynamics study","noun phrase","دراسة الديناميكا الدوائية","The pharmacodynamics study assessed the drug's effect on tumor markers.","قيّمت دراسة الديناميكا الدوائية تأثير الدواء على علامات الورم.","extended","B2","COCA"],
["bioequivalence trial","noun phrase","تجربة التكافؤ الحيوي","A bioequivalence trial compared the generic to the branded drug.","قارنت تجربة التكافؤ الحيوي الدواء الجنيس بالدواء ذي العلامة التجارية.","mastery","C1","AWL"],
["non-inferiority trial","noun phrase","تجربة عدم الدونية","The non-inferiority trial showed the new treatment was not worse.","أظهرت تجربة عدم الدونية أن العلاج الجديد ليس أسوأ.","mastery","C1","AWL"],
["superiority trial","noun phrase","تجربة التفوق","A superiority trial aims to prove one treatment is better.","تهدف تجربة التفوق إلى إثبات أن علاجاً أفضل من آخر.","extended","B2","COCA"],
["futility analysis","noun phrase","تحليل الجدوى العلاجية","Futility analysis indicated the trial would not reach significance.","أشار تحليل الجدوى العلاجية إلى أن التجربة لن تحقق دلالة إحصائية.","mastery","C1","AWL"],
["interim analysis","noun phrase","التحليل المرحلي","An interim analysis was conducted after enrolling half the patients.","أُجري التحليل المرحلي بعد تسجيل نصف المرضى.","extended","B2","COCA"],
["adaptive trial design","noun phrase","تصميم التجربة التكيفي","Adaptive trial design allows modifications based on accumulating data.","يسمح تصميم التجربة التكيفي بإجراء تعديلات بناءً على البيانات المتراكمة.","mastery","C1","AWL"],
["basket trial","noun phrase","تجربة السلة","A basket trial tests one drug across multiple tumor types.","تختبر تجربة السلة دواءً واحداً عبر أنواع متعددة من الأورام.","mastery","C1","COCA"],
["umbrella trial","noun phrase","التجربة المظلية","An umbrella trial evaluates multiple therapies in one disease.","تُقيّم التجربة المظلية علاجات متعددة في مرض واحد.","mastery","C1","COCA"],
["platform trial","noun phrase","تجربة المنصة","A platform trial can add or drop treatment arms dynamically.","يمكن لتجربة المنصة إضافة أو إسقاط أذرع العلاج ديناميكياً.","mastery","C1","AWL"],
["master protocol","noun phrase","البروتوكول الرئيسي","The master protocol governs all sub-studies within the trial.","يحكم البروتوكول الرئيسي جميع الدراسات الفرعية ضمن التجربة.","extended","B2","COCA"],
["companion diagnostic","noun phrase","التشخيص المرافق","A companion diagnostic identifies patients likely to respond.","يحدد التشخيص المرافق المرضى المرجح استجابتهم.","mastery","C1","COCA"],
["theranostics approach","noun phrase","نهج التشخيص العلاجي","The theranostics approach combines diagnosis and therapy in one agent.","يجمع نهج التشخيص العلاجي بين التشخيص والعلاج في عامل واحد.","mastery","C1","AWL"],
["precision oncology","noun phrase","طب الأورام الدقيق","Precision oncology tailors treatment based on genomic profiling.","يُخصص طب الأورام الدقيق العلاج بناءً على التنميط الجينومي.","extended","B2","COCA"],
["liquid biopsy","noun phrase","الخزعة السائلة","Liquid biopsy detects tumor fragments in a blood sample.","تكشف الخزعة السائلة عن شظايا الورم في عينة الدم.","extended","B2","COCA"],
["circulating tumor DNA","noun phrase","الحمض النووي الورمي الدوار","Circulating tumor DNA levels correlated with treatment response.","ارتبطت مستويات الحمض النووي الورمي الدوار بالاستجابة للعلاج.","mastery","C1","COCA"],
["cell-free DNA","noun phrase","الحمض النووي الحر من الخلايا","Cell-free DNA analysis enables non-invasive prenatal screening.","يتيح تحليل الحمض النووي الحر من الخلايا الفحص غير الجراحي قبل الولادة.","mastery","C1","COCA"],
["minimal residual disease","noun phrase","الحد الأدنى من المرض المتبقي","Minimal residual disease negativity predicts long-term remission.","يتنبأ سلبية الحد الأدنى من المرض المتبقي بالهدأة طويلة الأمد.","mastery","C1","AWL"],
["chimeric antigen receptor","noun phrase","مستقبل المستضد الخيمري","Chimeric antigen receptor T-cell therapy revolutionized blood cancer treatment.","أحدث علاج الخلايا التائية بمستقبل المستضد الخيمري ثورة في علاج سرطان الدم.","mastery","C1","COCA"],
["bispecific antibody","noun phrase","الجسم المضاد ثنائي النوعية","A bispecific antibody engages two different targets simultaneously.","يستهدف الجسم المضاد ثنائي النوعية هدفين مختلفين في آن واحد.","mastery","C1","COCA"],
["antibody-drug conjugate","noun phrase","اقتران الجسم المضاد بالدواء","The antibody-drug conjugate delivers chemotherapy directly to cancer cells.","يوصل اقتران الجسم المضاد بالدواء العلاج الكيميائي مباشرة إلى الخلايا السرطانية.","mastery","C1","COCA"],
["immune checkpoint inhibitor","noun phrase","مثبط نقطة التفتيش المناعية","An immune checkpoint inhibitor unleashes the body's anti-tumor response.","يُطلق مثبط نقطة التفتيش المناعية استجابة الجسم المضادة للورم.","extended","B2","COCA"],
["programmed death ligand","noun phrase","رابطة الموت المبرمج","Programmed death ligand expression guides immunotherapy selection.","يوجه التعبير عن رابطة الموت المبرمج اختيار العلاج المناعي.","mastery","C1","AWL"],
["cytotoxic T lymphocyte","noun phrase","الخلية اللمفاوية التائية السامة","Cytotoxic T lymphocytes directly kill virus-infected cells.","تقتل الخلايا اللمفاوية التائية السامة الخلايا المصابة بالفيروس مباشرة.","extended","B2","COCA"],
["regulatory T cell","noun phrase","الخلية التائية التنظيمية","Regulatory T cells suppress excessive immune responses.","تثبط الخلايا التائية التنظيمية الاستجابات المناعية المفرطة.","extended","B2","COCA"]
];

const u2 = [
["hydrothermal plume","noun phrase","عمود حراري مائي","The hydrothermal plume rose hundreds of meters above the vent.","ارتفع العمود الحراري المائي مئات الأمتار فوق الفوهة.","mastery","C1","COCA"],
["black smoker chimney","noun phrase","مدخنة المدخن الأسود","A black smoker chimney emits superheated mineral-rich fluid.","تنبعث من مدخنة المدخن الأسود سوائل شديدة الحرارة غنية بالمعادن.","mastery","C1","COCA"],
["white smoker chimney","noun phrase","مدخنة المدخن الأبيض","White smoker chimneys produce cooler, lighter-colored emissions.","تنتج مدخنات المدخن الأبيض انبعاثات أبرد وأفتح لوناً.","mastery","C1","COCA"],
["metalliferous sediment","noun phrase","رواسب معدنية","Metalliferous sediment accumulates near hydrothermal vents.","تتراكم الرواسب المعدنية بالقرب من الفوهات الحرارية المائية.","mastery","C1","AWL"],
["polymetallic nodule","noun phrase","عقيدة متعددة المعادن","Polymetallic nodules contain manganese, nickel, and cobalt.","تحتوي العقيدات متعددة المعادن على المنغنيز والنيكل والكوبالت.","mastery","C1","COCA"],
["cobalt-rich crust","noun phrase","قشرة غنية بالكوبالت","Cobalt-rich crusts form on seamount flanks over millions of years.","تتشكل القشور الغنية بالكوبالت على جوانب الجبال البحرية عبر ملايين السنين.","mastery","C1","AWL"],
["massive sulfide deposit","noun phrase","ترسب كبريتيدي كتلي","Massive sulfide deposits are rich in copper and zinc.","الترسبات الكبريتيدية الكتلية غنية بالنحاس والزنك.","extended","B2","COCA"],
["seafloor spreading center","noun phrase","مركز انتشار قاع البحر","New oceanic crust forms at the seafloor spreading center.","تتشكل القشرة المحيطية الجديدة في مركز انتشار قاع البحر.","extended","B2","COCA"],
["mid-ocean ridge","noun phrase","حافة وسط المحيط","The mid-ocean ridge extends across the Atlantic floor.","تمتد حافة وسط المحيط عبر قاع المحيط الأطلسي.","extended","B2","COCA"],
["transform fault","noun phrase","صدع تحويلي","A transform fault offsets segments of the mid-ocean ridge.","يُزيح الصدع التحويلي أجزاء من حافة وسط المحيط.","extended","B2","COCA"],
["subduction zone","noun phrase","منطقة الاندساس","Earthquakes are common along the subduction zone boundary.","الزلازل شائعة على طول حدود منطقة الاندساس.","extended","B2","COCA"],
["accretionary prism","noun phrase","منشور التراكم","The accretionary prism consists of scraped-off oceanic sediments.","يتكون منشور التراكم من رواسب محيطية مكشوطة.","mastery","C1","AWL"],
["forearc basin","noun phrase","حوض أمام القوس","Sediments accumulate in the forearc basin between trench and arc.","تتراكم الرواسب في حوض أمام القوس بين الخندق والقوس.","mastery","C1","AWL"],
["back-arc basin","noun phrase","حوض خلف القوس","A back-arc basin forms behind a volcanic island arc.","يتشكل حوض خلف القوس وراء قوس الجزر البركانية.","mastery","C1","AWL"],
["marginal sea","noun phrase","بحر هامشي","The South China Sea is classified as a marginal sea.","يُصنف بحر الصين الجنوبي كبحر هامشي.","extended","B2","COCA"],
["abyssal plain","noun phrase","سهل سحيق","The abyssal plain is the flattest region on Earth.","السهل السحيق هو أكثر المناطق استواءً على الأرض.","extended","B2","COCA"],
["continental rise","noun phrase","المرتفع القاري","The continental rise lies between the slope and the abyssal plain.","يقع المرتفع القاري بين المنحدر والسهل السحيق.","extended","B2","COCA"],
["continental slope","noun phrase","المنحدر القاري","The continental slope descends steeply from the shelf edge.","ينحدر المنحدر القاري بشدة من حافة الجرف.","extended","B2","COCA"],
["submarine canyon","noun phrase","وادٍ بحري","A submarine canyon channels sediment to the deep ocean floor.","ينقل الوادي البحري الرواسب إلى قاع المحيط العميق.","extended","B2","COCA"],
["turbidity current","noun phrase","تيار عكر","A turbidity current can travel at high speeds downslope.","يمكن لتيار عكر أن ينتقل بسرعات عالية أسفل المنحدر.","mastery","C1","COCA"],
["contourite drift","noun phrase","انجراف المحيطي الكنتوري","Contourite drifts are shaped by deep-water bottom currents.","تتشكل الانجرافات المحيطية الكنتورية بفعل تيارات القاع العميقة.","mastery","C1","AWL"],
["pelagic ooze","noun phrase","وحل بلاجي","Pelagic ooze covers vast areas of the deep-sea floor.","يغطي الوحل البلاجي مساحات شاسعة من قاع البحر العميق.","mastery","C1","COCA"],
["siliceous ooze","noun phrase","وحل سيليسي","Siliceous ooze is composed mainly of diatom and radiolarian shells.","يتكون الوحل السيليسي أساساً من أصداف الدياتومات والشعاعيات.","mastery","C1","AWL"],
["calcareous ooze","noun phrase","وحل كلسي","Calcareous ooze dominates shallower regions of the ocean floor.","يهيمن الوحل الكلسي على المناطق الأقل عمقاً من قاع المحيط.","mastery","C1","AWL"],
["red clay","noun phrase","طين أحمر","Red clay accumulates extremely slowly in the deepest basins.","يتراكم الطين الأحمر ببطء شديد في أعمق الأحواض.","extended","B2","COCA"],
["manganese nodule","noun phrase","عقيدة المنغنيز","Manganese nodules grow at a rate of millimeters per million years.","تنمو عقيدات المنغنيز بمعدل ملليمترات لكل مليون سنة.","mastery","C1","COCA"],
["phosphorite deposit","noun phrase","ترسب الفوسفوريت","Phosphorite deposits are mined for agricultural fertilizer.","تُستخرج ترسبات الفوسفوريت لإنتاج الأسمدة الزراعية.","mastery","C1","AWL"],
["evaporite deposit","noun phrase","ترسب تبخري","Evaporite deposits form when enclosed seas evaporate completely.","تتشكل الترسبات التبخرية عندما تتبخر البحار المغلقة بالكامل.","extended","B2","COCA"],
["brine pool","noun phrase","بركة ملحية","A brine pool on the seafloor has distinct surface tension.","تمتلك البركة الملحية في قاع البحر توتراً سطحياً مميزاً.","mastery","C1","COCA"],
["cold seep","noun phrase","تسرب بارد","Cold seeps release methane and hydrogen sulfide into the water.","تُطلق التسربات الباردة الميثان وكبريتيد الهيدروجين في الماء.","mastery","C1","COCA"],
["methane hydrate","noun phrase","هيدرات الميثان","Methane hydrate is an ice-like substance found in marine sediments.","هيدرات الميثان مادة شبيهة بالجليد توجد في الرواسب البحرية.","extended","B2","COCA"],
["gas chimney","noun phrase","مدخنة غازية","A gas chimney is a vertical zone of gas migration in sediments.","المدخنة الغازية منطقة عمودية لهجرة الغاز في الرواسب.","mastery","C1","AWL"],
["pockmark","noun","حفرة قاعية","Pockmarks on the seabed indicate past fluid escape events.","تشير الحفر القاعية في قاع البحر إلى أحداث تسرب سوائل سابقة.","mastery","C1","COCA"],
["mud volcano","noun phrase","بركان طيني","A mud volcano erupts fluidized sediment from deep below.","ينفث البركان الطيني رواسب مميعة من الأعماق.","extended","B2","COCA"],
["fluid venting","noun phrase","تنفيس السوائل","Active fluid venting supports unique chemosynthetic communities.","يدعم تنفيس السوائل النشط مجتمعات تركيبية كيميائية فريدة.","mastery","C1","AWL"]
];

const u3 = [
["climate-smart agriculture","noun phrase","الزراعة الذكية مناخياً","Climate-smart agriculture integrates adaptation and mitigation strategies.","تدمج الزراعة الذكية مناخياً استراتيجيات التكيف والتخفيف.","extended","B2","COCA"],
["conservation agriculture","noun phrase","الزراعة الحافظة","Conservation agriculture minimizes soil disturbance and maintains cover.","تقلل الزراعة الحافظة من اضطراب التربة وتحافظ على الغطاء.","extended","B2","COCA"],
["regenerative agriculture","noun phrase","الزراعة التجديدية","Regenerative agriculture focuses on restoring degraded soil health.","تركز الزراعة التجديدية على استعادة صحة التربة المتدهورة.","extended","B2","COCA"],
["agroforestry system","noun phrase","نظام الحراجة الزراعية","An agroforestry system combines trees with crops on the same land.","يجمع نظام الحراجة الزراعية بين الأشجار والمحاصيل على نفس الأرض.","mastery","C1","COCA"],
["silvopasture system","noun phrase","نظام الرعي الحرجي","A silvopasture system integrates trees, forage, and livestock.","يدمج نظام الرعي الحرجي الأشجار والأعلاف والماشية.","mastery","C1","AWL"],
["alley cropping","noun phrase","الزراعة بين الأزقة","Alley cropping places rows of trees between strips of crops.","تضع الزراعة بين الأزقة صفوف أشجار بين شرائط المحاصيل.","mastery","C1","AWL"],
["windbreak planting","noun phrase","زراعة مصدات الرياح","Windbreak planting reduces soil erosion on exposed fields.","تقلل زراعة مصدات الرياح من تآكل التربة في الحقول المكشوفة.","extended","B2","COCA"],
["riparian buffer","noun phrase","منطقة عازلة نهرية","A riparian buffer filters runoff before it reaches the stream.","تُرشح المنطقة العازلة النهرية الجريان السطحي قبل وصوله إلى المجرى.","mastery","C1","COCA"],
["vegetative filter strip","noun phrase","شريط ترشيح نباتي","Vegetative filter strips trap sediment and nutrients from runoff.","تحتجز أشرطة الترشيح النباتي الرواسب والمغذيات من الجريان السطحي.","mastery","C1","AWL"],
["grassed waterway","noun phrase","مجرى مائي مُعشب","A grassed waterway prevents gully erosion in farm fields.","يمنع المجرى المائي المُعشب تآكل الأخاديد في الحقول الزراعية.","mastery","C1","COCA"],
["terracing system","noun phrase","نظام المصاطب","The terracing system converts steep slopes into level planting areas.","يحول نظام المصاطب المنحدرات الشديدة إلى مناطق زراعة مستوية.","extended","B2","COCA"],
["contour bunding","noun phrase","تسوير كنتوري","Contour bunding slows water flow across hillside fields.","يبطئ التسوير الكنتوري تدفق المياه عبر حقول التلال.","mastery","C1","AWL"],
["check dam","noun phrase","سد تثبيتي","A check dam reduces water velocity in drainage channels.","يقلل السد التثبيتي سرعة الماء في قنوات الصرف.","extended","B2","COCA"],
["farm pond","noun phrase","بركة مزرعية","The farm pond stores rainwater for irrigation during dry spells.","تخزن البركة المزرعية مياه الأمطار للري خلال فترات الجفاف.","extended","B2","COCA"],
["percolation tank","noun phrase","خزان ترشيح","A percolation tank recharges groundwater through infiltration.","يعيد خزان الترشيح تغذية المياه الجوفية من خلال التسرب.","mastery","C1","AWL"],
["recharge well","noun phrase","بئر إعادة تغذية","A recharge well injects treated water directly into the aquifer.","يحقن بئر إعادة التغذية المياه المعالجة مباشرة في طبقة المياه الجوفية.","mastery","C1","AWL"],
["drip fertigation","noun phrase","التسميد بالتنقيط","Drip fertigation delivers nutrients precisely through the irrigation system.","يوصل التسميد بالتنقيط المغذيات بدقة عبر نظام الري.","mastery","C1","COCA"],
["foliar feeding","noun phrase","التغذية الورقية","Foliar feeding corrects micronutrient deficiencies rapidly.","تصحح التغذية الورقية نقص العناصر الدقيقة بسرعة.","extended","B2","COCA"],
["integrated nutrient management","noun phrase","الإدارة المتكاملة للمغذيات","Integrated nutrient management combines organic and inorganic sources.","تجمع الإدارة المتكاملة للمغذيات بين المصادر العضوية وغير العضوية.","mastery","C1","AWL"],
["site-specific nutrient management","noun phrase","إدارة المغذيات الموقعية","Site-specific nutrient management optimizes fertilizer for each field zone.","تحسّن إدارة المغذيات الموقعية الأسمدة لكل منطقة في الحقل.","mastery","C1","AWL"],
["variable rate application","noun phrase","التطبيق بمعدل متغير","Variable rate application adjusts inputs based on spatial data.","يُعدّل التطبيق بمعدل متغير المدخلات بناءً على البيانات المكانية.","mastery","C1","COCA"],
["precision seeding","noun phrase","البذر الدقيق","Precision seeding places each seed at the optimal spacing.","يضع البذر الدقيق كل بذرة على المسافة المثلى.","extended","B2","COCA"],
["controlled traffic farming","noun phrase","الزراعة بحركة مرور محكومة","Controlled traffic farming confines machinery to permanent wheel tracks.","تحصر الزراعة بحركة مرور محكومة الآلات في مسارات عجلات دائمة.","mastery","C1","AWL"],
["relay cropping","noun phrase","الزراعة التتابعية","Relay cropping plants the next crop before harvesting the current one.","تزرع الزراعة التتابعية المحصول التالي قبل حصاد الحالي.","mastery","C1","COCA"],
["ratoon cropping","noun phrase","زراعة الخلفة","Ratoon cropping harvests regrowth from the previous crop's stubble.","تحصد زراعة الخلفة النمو المتجدد من بقايا المحصول السابق.","mastery","C1","AWL"],
["mixed cropping","noun phrase","الزراعة المختلطة","Mixed cropping grows two or more crops simultaneously in a field.","تزرع الزراعة المختلطة محصولين أو أكثر في آن واحد في الحقل.","extended","B2","COCA"],
["sequential cropping","noun phrase","الزراعة المتعاقبة","Sequential cropping grows crops one after another in the same year.","تزرع الزراعة المتعاقبة المحاصيل واحداً تلو الآخر في نفس العام.","extended","B2","COCA"],
["multistory cropping","noun phrase","الزراعة متعددة الطبقات","Multistory cropping utilizes vertical space with layered canopies.","تستغل الزراعة متعددة الطبقات الفضاء العمودي بمظلات متدرجة.","mastery","C1","AWL"],
["boundary planting","noun phrase","الزراعة الحدودية","Boundary planting marks farm edges while providing useful products.","تحدد الزراعة الحدودية حدود المزرعة مع توفير منتجات مفيدة.","extended","B2","COCA"],
["live fence","noun phrase","سياج حي","A live fence uses growing plants to enclose livestock areas.","يستخدم السياج الحي نباتات نامية لتسييج مناطق الماشية.","extended","B2","COCA"],
["fodder bank","noun phrase","مخزن العلف","A fodder bank provides supplementary feed during the dry season.","يوفر مخزن العلف غذاءً تكميلياً خلال موسم الجفاف.","mastery","C1","COCA"],
["seed multiplication","noun phrase","إكثار البذور","Seed multiplication programs ensure adequate supply of improved varieties.","تضمن برامج إكثار البذور إمداداً كافياً من الأصناف المحسنة.","extended","B2","COCA"],
["participatory plant breeding","noun phrase","تربية النبات التشاركية","Participatory plant breeding involves farmers in variety selection.","تشرك تربية النبات التشاركية المزارعين في اختيار الأصناف.","mastery","C1","AWL"],
["marker-assisted selection","noun phrase","الانتخاب بمساعدة الواسمات","Marker-assisted selection accelerates crop improvement cycles.","يسرّع الانتخاب بمساعدة الواسمات دورات تحسين المحاصيل.","mastery","C1","AWL"],
["genomic selection","noun phrase","الانتخاب الجينومي","Genomic selection predicts breeding values from genome-wide markers.","يتنبأ الانتخاب الجينومي بالقيم الوراثية من واسمات على مستوى الجينوم.","mastery","C1","AWL"]
];

const u4 = [
["structural hierarchy","noun phrase","التسلسل الهيكلي","Structural hierarchy enables strength at multiple length scales.","يتيح التسلسل الهيكلي القوة عبر مقاييس طول متعددة.","mastery","C1","COCA"],
["hierarchical architecture","noun phrase","العمارة الهرمية","Bone derives toughness from its hierarchical architecture.","يستمد العظم متانته من عمارته الهرمية.","mastery","C1","AWL"],
["fractal branching","noun phrase","التفرع الكسوري","Fractal branching maximizes surface area in lung tissue.","يزيد التفرع الكسوري مساحة السطح في أنسجة الرئة.","mastery","C1","COCA"],
["self-similar structure","noun phrase","بنية ذاتية التشابه","A self-similar structure repeats its pattern at every scale.","تكرر البنية ذاتية التشابه نمطها عند كل مقياس.","mastery","C1","AWL"],
["multi-scale design","noun phrase","التصميم متعدد المقاييس","Multi-scale design bridges nano and macro properties.","يربط التصميم متعدد المقاييس بين الخصائص النانوية والكبرى.","extended","B2","COCA"],
["gradient property","noun phrase","خاصية تدريجية","A gradient property varies smoothly across the material thickness.","تتغير الخاصية التدريجية بسلاسة عبر سمك المادة.","mastery","C1","AWL"],
["functionally graded material","noun phrase","مادة متدرجة وظيفياً","A functionally graded material transitions from ceramic to metal.","تنتقل المادة المتدرجة وظيفياً من السيراميك إلى المعدن.","mastery","C1","AWL"],
["anisotropic material","noun phrase","مادة متباينة الخواص","An anisotropic material has direction-dependent mechanical properties.","للمادة متباينة الخواص خصائص ميكانيكية تعتمد على الاتجاه.","extended","B2","COCA"],
["orthotropic laminate","noun phrase","صفيحة متعامدة الخواص","An orthotropic laminate has three mutually perpendicular symmetry planes.","للصفيحة متعامدة الخواص ثلاثة مستويات تناظر متعامدة.","mastery","C1","AWL"],
["quasi-isotropic layup","noun phrase","تركيب شبه متساوي الخواص","A quasi-isotropic layup distributes fibers evenly in all directions.","يوزع التركيب شبه متساوي الخواص الألياف بالتساوي في جميع الاتجاهات.","mastery","C1","AWL"],
["sandwich panel","noun phrase","لوحة شطيرية","A sandwich panel combines stiff skins with a lightweight core.","تجمع اللوحة الشطيرية بين أغلفة صلبة ولب خفيف الوزن.","extended","B2","COCA"],
["honeycomb core","noun phrase","لب عسل النحل","A honeycomb core provides high stiffness-to-weight ratio.","يوفر لب عسل النحل نسبة عالية من الصلابة إلى الوزن.","extended","B2","COCA"],
["foam core","noun phrase","لب رغوي","A foam core is used in lightweight composite panels.","يُستخدم اللب الرغوي في الألواح المركبة خفيفة الوزن.","extended","B2","COCA"],
["balsa core","noun phrase","لب خشب البلسا","Balsa core offers excellent shear strength for marine composites.","يوفر لب خشب البلسا مقاومة قص ممتازة للمركبات البحرية.","mastery","C1","COCA"],
["corrugated core","noun phrase","لب مموج","A corrugated core enhances energy absorption during impact.","يعزز اللب المموج امتصاص الطاقة أثناء الصدمة.","extended","B2","COCA"],
["truss core","noun phrase","لب جمالوني","A truss core transfers loads efficiently through strut elements.","ينقل اللب الجمالوني الأحمال بكفاءة عبر عناصر الدعامة.","mastery","C1","AWL"],
["lattice structure","noun phrase","بنية شبكية","A lattice structure can be optimized for specific load paths.","يمكن تحسين البنية الشبكية لمسارات أحمال محددة.","extended","B2","COCA"],
["octet truss","noun phrase","جمالون ثماني","The octet truss achieves near-theoretical strength in micro-architectures.","يحقق الجمالون الثماني قوة قريبة من النظرية في البنى المعمارية الدقيقة.","mastery","C1","AWL"],
["diamond lattice","noun phrase","شبكة ماسية","A diamond lattice mimics the atomic structure of carbon crystals.","تحاكي الشبكة الماسية البنية الذرية لبلورات الكربون.","mastery","C1","COCA"],
["gyroid surface","noun phrase","سطح جايرويدي","The gyroid surface appears in butterfly wing scales and block copolymers.","يظهر السطح الجايرويدي في حراشف أجنحة الفراشات والبوليمرات المشتركة.","mastery","C1","AWL"],
["triply periodic minimal surface","noun phrase","سطح أدنى ثلاثي الدورية","A triply periodic minimal surface divides space into labyrinthine channels.","يقسم السطح الأدنى ثلاثي الدورية الفضاء إلى قنوات متاهية.","mastery","C1","AWL"],
["Schwarz P surface","noun phrase","سطح شوارز بي","The Schwarz P surface is a classic example of a minimal surface.","سطح شوارز بي مثال كلاسيكي على السطح الأدنى.","mastery","C1","AWL"],
["Schoen gyroid","noun phrase","جايرويد شوين","The Schoen gyroid partitions space without self-intersection.","يقسم جايرويد شوين الفضاء دون تقاطع ذاتي.","mastery","C1","AWL"],
["auxetic metamaterial","noun phrase","مادة فوقية أوكسيتية","An auxetic metamaterial expands laterally when stretched.","تتمدد المادة الفوقية الأوكسيتية جانبياً عند شدها.","mastery","C1","COCA"],
["negative Poisson ratio","noun phrase","نسبة بواسون سالبة","A negative Poisson ratio causes counter-intuitive deformation behavior.","تسبب نسبة بواسون السالبة سلوك تشوه غير بديهي.","mastery","C1","AWL"],
["re-entrant structure","noun phrase","بنية داخلية العودة","A re-entrant structure achieves auxetic behavior through inward-folding cells.","تحقق البنية داخلية العودة سلوكاً أوكسيتياً عبر خلايا مطوية للداخل.","mastery","C1","AWL"],
["rotating rigid unit","noun phrase","وحدة صلبة دوارة","Rotating rigid units produce auxetic response through geometric rotation.","تنتج الوحدات الصلبة الدوارة استجابة أوكسيتية عبر دوران هندسي.","mastery","C1","AWL"],
["chiral auxetic","noun phrase","أوكسيتي لولبي","A chiral auxetic relies on node rotation rather than re-entrant geometry.","يعتمد الأوكسيتي اللولبي على دوران العقدة بدلاً من هندسة العودة.","mastery","C1","AWL"],
["acoustic metamaterial","noun phrase","مادة فوقية صوتية","An acoustic metamaterial can block or redirect sound waves.","يمكن للمادة الفوقية الصوتية حجب أو إعادة توجيه الموجات الصوتية.","extended","B2","COCA"],
["electromagnetic metamaterial","noun phrase","مادة فوقية كهرومغناطيسية","An electromagnetic metamaterial manipulates light at subwavelength scales.","تتحكم المادة الفوقية الكهرومغناطيسية بالضوء عند مقاييس دون الطول الموجي.","mastery","C1","AWL"],
["mechanical metamaterial","noun phrase","مادة فوقية ميكانيكية","A mechanical metamaterial achieves unusual stiffness or flexibility.","تحقق المادة الفوقية الميكانيكية صلابة أو مرونة غير عادية.","extended","B2","COCA"],
["thermal metamaterial","noun phrase","مادة فوقية حرارية","A thermal metamaterial guides heat flow in desired directions.","توجه المادة الفوقية الحرارية تدفق الحرارة في اتجاهات مطلوبة.","mastery","C1","AWL"],
["programmable metamaterial","noun phrase","مادة فوقية قابلة للبرمجة","A programmable metamaterial changes properties in response to stimuli.","تغير المادة الفوقية القابلة للبرمجة خصائصها استجابة للمحفزات.","mastery","C1","COCA"],
["reconfigurable structure","noun phrase","بنية قابلة لإعادة التشكيل","A reconfigurable structure adapts its shape for different functions.","تكيّف البنية القابلة لإعادة التشكيل شكلها لوظائف مختلفة.","extended","B2","COCA"],
["deployable mechanism","noun phrase","آلية قابلة للنشر","A deployable mechanism unfolds from a compact stowed configuration.","تتكشف الآلية القابلة للنشر من تشكيل مدمج مطوي.","mastery","C1","AWL"]
];

const u5 = [
["migration governance","noun phrase","حوكمة الهجرة","Migration governance requires coordination among multiple agencies.","تتطلب حوكمة الهجرة تنسيقاً بين وكالات متعددة.","extended","B2","COCA"],
["global compact for migration","noun phrase","الميثاق العالمي للهجرة","The global compact for migration was adopted in 2018.","اعتُمد الميثاق العالمي للهجرة في عام 2018.","extended","B2","AWL"],
["global compact on refugees","noun phrase","الميثاق العالمي بشأن اللاجئين","The global compact on refugees emphasizes responsibility sharing.","يؤكد الميثاق العالمي بشأن اللاجئين على تقاسم المسؤولية.","extended","B2","AWL"],
["refugee convention","noun phrase","اتفاقية اللاجئين","The refugee convention defines who qualifies for international protection.","تحدد اتفاقية اللاجئين من يستحق الحماية الدولية.","extended","B2","COCA"],
["protocol relating to status","noun phrase","بروتوكول يتعلق بالوضع","The protocol relating to status removed geographic restrictions.","أزال البروتوكول المتعلق بالوضع القيود الجغرافية.","mastery","C1","AWL"],
["complementary protection","noun phrase","الحماية التكميلية","Complementary protection covers people outside the refugee definition.","تغطي الحماية التكميلية الأشخاص خارج تعريف اللاجئ.","mastery","C1","AWL"],
["temporary protection directive","noun phrase","توجيه الحماية المؤقتة","The temporary protection directive was activated for the first time in 2022.","فُعّل توجيه الحماية المؤقتة لأول مرة في عام 2022.","mastery","C1","AWL"],
["qualification directive","noun phrase","توجيه التأهيل","The qualification directive sets standards for refugee status determination.","يضع توجيه التأهيل معايير لتحديد وضع اللاجئ.","mastery","C1","AWL"],
["reception conditions directive","noun phrase","توجيه شروط الاستقبال","The reception conditions directive guarantees minimum housing standards.","يضمن توجيه شروط الاستقبال الحد الأدنى من معايير السكن.","mastery","C1","AWL"],
["asylum procedures directive","noun phrase","توجيه إجراءات اللجوء","The asylum procedures directive harmonizes processing across member states.","يوحد توجيه إجراءات اللجوء المعالجة عبر الدول الأعضاء.","mastery","C1","AWL"],
["Dublin regulation","noun phrase","نظام دبلن","The Dublin regulation determines which state examines an asylum claim.","يحدد نظام دبلن أي دولة تنظر في طلب اللجوء.","extended","B2","COCA"],
["safe country of origin","noun phrase","بلد المنشأ الآمن","Applicants from a safe country of origin face accelerated processing.","يواجه المتقدمون من بلد المنشأ الآمن معالجة مسرعة.","mastery","C1","AWL"],
["safe third country concept","noun phrase","مفهوم البلد الثالث الآمن","The safe third country concept allows transfer of asylum seekers.","يسمح مفهوم البلد الثالث الآمن بنقل طالبي اللجوء.","mastery","C1","AWL"],
["internal flight alternative","noun phrase","بديل الفرار الداخلي","An internal flight alternative means protection exists elsewhere in the home country.","يعني بديل الفرار الداخلي وجود حماية في مكان آخر في بلد المنشأ.","mastery","C1","AWL"],
["well-founded fear","noun phrase","خوف له ما يبرره","A well-founded fear of persecution is central to refugee claims.","الخوف الذي له ما يبرره من الاضطهاد محوري في طلبات اللجوء.","extended","B2","COCA"],
["particular social group","noun phrase","فئة اجتماعية معينة","Membership in a particular social group can ground a refugee claim.","يمكن أن تؤسس العضوية في فئة اجتماعية معينة طلب لجوء.","mastery","C1","AWL"],
["political opinion","noun phrase","رأي سياسي","Persecution based on political opinion is a recognized ground.","الاضطهاد القائم على الرأي السياسي سبب معترف به.","extended","B2","COCA"],
["race discrimination","noun phrase","تمييز عنصري","Race discrimination remains a basis for asylum claims worldwide.","يظل التمييز العنصري أساساً لطلبات اللجوء حول العالم.","extended","B2","COCA"],
["nationality discrimination","noun phrase","تمييز على أساس الجنسية","Nationality discrimination targets individuals based on citizenship status.","يستهدف التمييز على أساس الجنسية الأفراد بناءً على وضع المواطنة.","extended","B2","COCA"],
["religion discrimination","noun phrase","تمييز ديني","Religion discrimination forces many to flee their home countries.","يجبر التمييز الديني كثيرين على الفرار من بلدانهم.","extended","B2","COCA"],
["non-penalization principle","noun phrase","مبدأ عدم المعاقبة","The non-penalization principle protects refugees who enter irregularly.","يحمي مبدأ عدم المعاقبة اللاجئين الذين يدخلون بصورة غير نظامية.","mastery","C1","AWL"],
["family unity principle","noun phrase","مبدأ وحدة الأسرة","The family unity principle prevents separation of refugee families.","يمنع مبدأ وحدة الأسرة فصل عائلات اللاجئين.","extended","B2","AWL"],
["best interest of child","noun phrase","المصلحة الفضلى للطفل","The best interest of the child guides all decisions on minors.","توجه المصلحة الفضلى للطفل جميع القرارات المتعلقة بالقاصرين.","extended","B2","COCA"],
["age-disputed minor","noun phrase","قاصر متنازع على عمره","An age-disputed minor undergoes age assessment procedures.","يخضع القاصر المتنازع على عمره لإجراءات تقييم العمر.","mastery","C1","AWL"],
["vulnerability assessment","noun phrase","تقييم الضعف","A vulnerability assessment identifies individuals needing special support.","يحدد تقييم الضعف الأفراد الذين يحتاجون دعماً خاصاً.","extended","B2","COCA"],
["special procedural guarantee","noun phrase","ضمانة إجرائية خاصة","A special procedural guarantee ensures fair treatment for vulnerable applicants.","تضمن الضمانة الإجرائية الخاصة معاملة عادلة للمتقدمين الضعفاء.","mastery","C1","AWL"],
["legal aid provision","noun phrase","توفير المساعدة القانونية","Legal aid provision is essential for meaningful access to asylum.","توفير المساعدة القانونية ضروري للوصول الفعلي إلى اللجوء.","extended","B2","COCA"],
["interpretation service","noun phrase","خدمة الترجمة الفورية","An interpretation service must be provided during asylum interviews.","يجب توفير خدمة الترجمة الفورية خلال مقابلات اللجوء.","extended","B2","COCA"],
["country guidance","noun phrase","التوجيه القطري","Country guidance notes inform decision-makers about conditions abroad.","تُعلم مذكرات التوجيه القطري صانعي القرار بالأوضاع في الخارج.","mastery","C1","AWL"],
["fresh claim","noun phrase","طلب جديد","A fresh claim presents new evidence not previously considered.","يقدم الطلب الجديد أدلة لم يُنظر فيها سابقاً.","mastery","C1","COCA"],
["subsequent application","noun phrase","طلب لاحق","A subsequent application must contain significant new elements.","يجب أن يحتوي الطلب اللاحق على عناصر جديدة مهمة.","mastery","C1","AWL"],
["accelerated procedure","noun phrase","إجراء مسرّع","An accelerated procedure applies to manifestly unfounded claims.","ينطبق الإجراء المسرّع على الطلبات الظاهرة البطلان.","mastery","C1","AWL"],
["border procedure","noun phrase","إجراء حدودي","A border procedure processes claims at the point of entry.","يعالج الإجراء الحدودي الطلبات عند نقطة الدخول.","extended","B2","AWL"],
["admissibility procedure","noun phrase","إجراء المقبولية","An admissibility procedure screens claims before full examination.","يفرز إجراء المقبولية الطلبات قبل الفحص الكامل.","mastery","C1","AWL"],
["manifestly unfounded","adjective phrase","ظاهر البطلان","A manifestly unfounded claim lacks any credible basis.","يفتقر الطلب ظاهر البطلان إلى أي أساس موثوق.","mastery","C1","AWL"]
];

const u6 = [
["account abstraction wallet","noun phrase","محفظة تجريد الحساب","An account abstraction wallet enables gasless transactions for users.","تتيح محفظة تجريد الحساب معاملات بدون رسوم غاز للمستخدمين.","mastery","C1","COCA"],
["social recovery wallet","noun phrase","محفظة الاسترداد الاجتماعي","A social recovery wallet lets trusted contacts restore access.","تتيح محفظة الاسترداد الاجتماعي لجهات الاتصال الموثوقة استعادة الوصول.","mastery","C1","COCA"],
["multi-party computation wallet","noun phrase","محفظة الحوسبة متعددة الأطراف","A multi-party computation wallet splits keys across several parties.","تقسم محفظة الحوسبة متعددة الأطراف المفاتيح عبر عدة أطراف.","mastery","C1","AWL"],
["threshold signature scheme","noun phrase","مخطط توقيع العتبة","A threshold signature scheme requires a minimum number of signers.","يتطلب مخطط توقيع العتبة حداً أدنى من الموقعين.","mastery","C1","AWL"],
["distributed validator technology","noun phrase","تقنية المدقق الموزع","Distributed validator technology spreads staking across multiple nodes.","توزع تقنية المدقق الموزع التخزين عبر عقد متعددة.","mastery","C1","COCA"],
["liquid staking derivative","noun phrase","مشتق التخزين السائل","A liquid staking derivative represents staked assets in tradeable form.","يمثل مشتق التخزين السائل الأصول المخزنة في شكل قابل للتداول.","mastery","C1","COCA"],
["restaking middleware","noun phrase","برمجية إعادة التخزين الوسيطة","Restaking middleware allows validators to secure additional protocols.","تسمح برمجية إعادة التخزين الوسيطة للمدققين بتأمين بروتوكولات إضافية.","mastery","C1","AWL"],
["actively validated service","noun phrase","خدمة مُدققة بفاعلية","An actively validated service leverages restaked ETH for security.","تستفيد الخدمة المُدققة بفاعلية من الإيثر المُعاد تخزينه للأمان.","mastery","C1","AWL"],
["eigenpod operator","noun phrase","مشغل إيغنبود","An eigenpod operator manages restaking infrastructure on Ethereum.","يدير مشغل إيغنبود البنية التحتية لإعادة التخزين على إيثريوم.","mastery","C1","COCA"],
["withdrawal credential","noun phrase","بيانات اعتماد السحب","The withdrawal credential determines where staking rewards are sent.","تحدد بيانات اعتماد السحب وجهة إرسال مكافآت التخزين.","extended","B2","COCA"],
["validator lifecycle","noun phrase","دورة حياة المدقق","The validator lifecycle includes activation, attestation, and exit phases.","تشمل دورة حياة المدقق مراحل التفعيل والتصديق والخروج.","extended","B2","COCA"],
["activation queue","noun phrase","طابور التفعيل","Validators wait in the activation queue before going live.","ينتظر المدققون في طابور التفعيل قبل البدء.","extended","B2","COCA"],
["exit queue","noun phrase","طابور الخروج","The exit queue manages orderly departure of validators.","يدير طابور الخروج المغادرة المنظمة للمدققين.","extended","B2","COCA"],
["churn limit","noun phrase","حد الدوران","The churn limit caps how many validators enter or exit per epoch.","يحد حد الدوران من عدد المدققين الذين يدخلون أو يخرجون لكل حقبة.","mastery","C1","AWL"],
["effective balance","noun phrase","الرصيد الفعال","The effective balance determines a validator's influence on consensus.","يحدد الرصيد الفعال تأثير المدقق على الإجماع.","extended","B2","COCA"],
["inactivity leak","noun phrase","تسرب الخمول","An inactivity leak penalizes offline validators during finality failure.","يعاقب تسرب الخمول المدققين غير المتصلين أثناء فشل النهائية.","mastery","C1","AWL"],
["correlation penalty","noun phrase","عقوبة الارتباط","A correlation penalty increases with the number of simultaneous slashings.","تزداد عقوبة الارتباط مع عدد عمليات القطع المتزامنة.","mastery","C1","AWL"],
["attestation reward","noun phrase","مكافأة التصديق","Validators earn an attestation reward for confirming block validity.","يحصل المدققون على مكافأة التصديق لتأكيد صحة الكتلة.","extended","B2","COCA"],
["proposal reward","noun phrase","مكافأة الاقتراح","The proposal reward compensates the validator who produces a block.","تعوض مكافأة الاقتراح المدقق الذي ينتج كتلة.","extended","B2","COCA"],
["sync committee","noun phrase","لجنة المزامنة","A sync committee enables light clients to verify the chain.","تمكّن لجنة المزامنة العملاء الخفيفين من التحقق من السلسلة.","mastery","C1","AWL"],
["random beacon","noun phrase","منارة عشوائية","The random beacon generates unpredictable values for validator selection.","تولد المنارة العشوائية قيماً غير متوقعة لاختيار المدققين.","mastery","C1","COCA"],
["RANDAO reveal","noun phrase","كشف راندو","Each RANDAO reveal contributes to the collective randomness source.","يساهم كل كشف راندو في مصدر العشوائية الجماعي.","mastery","C1","AWL"],
["epoch boundary","noun phrase","حدود الحقبة","Finality checkpoints occur at each epoch boundary.","تحدث نقاط تفتيش النهائية عند كل حدود حقبة.","extended","B2","COCA"],
["slot duration","noun phrase","مدة الفتحة الزمنية","Each slot duration is exactly twelve seconds on the beacon chain.","مدة كل فتحة زمنية اثنتا عشرة ثانية بالضبط على سلسلة المنارة.","extended","B2","COCA"],
["beacon chain","noun phrase","سلسلة المنارة","The beacon chain coordinates validators in proof-of-stake Ethereum.","تنسق سلسلة المنارة المدققين في إيثريوم إثبات الحصة.","extended","B2","COCA"],
["execution layer","noun phrase","طبقة التنفيذ","The execution layer processes transactions and smart contract logic.","تعالج طبقة التنفيذ المعاملات ومنطق العقود الذكية.","extended","B2","COCA"],
["consensus layer","noun phrase","طبقة الإجماع","The consensus layer handles validator duties and block finality.","تتولى طبقة الإجماع واجبات المدقق ونهائية الكتل.","extended","B2","COCA"],
["engine API","noun phrase","واجهة برمجة المحرك","The engine API connects the execution and consensus clients.","تربط واجهة برمجة المحرك عملاء التنفيذ والإجماع.","mastery","C1","COCA"],
["builder API","noun phrase","واجهة برمجة البناء","The builder API separates block building from block proposing.","تفصل واجهة برمجة البناء بناء الكتل عن اقتراحها.","mastery","C1","AWL"],
["relay protocol","noun phrase","بروتوكول الترحيل","A relay protocol mediates between builders and proposers.","يتوسط بروتوكول الترحيل بين البنّائين والمقترحين.","mastery","C1","COCA"],
["MEV-boost architecture","noun phrase","بنية تعزيز القيمة القصوى القابلة للاستخراج","MEV-boost architecture outsources block construction to specialized builders.","تُسند بنية تعزيز القيمة القصوى القابلة للاستخراج بناء الكتل إلى بنّائين متخصصين.","mastery","C1","AWL"],
["block builder","noun phrase","بنّاء الكتل","A block builder assembles the most profitable transaction bundle.","يجمع بنّاء الكتل حزمة المعاملات الأكثر ربحية.","extended","B2","COCA"],
["block proposer","noun phrase","مقترح الكتل","The block proposer selects the winning block from builders.","يختار مقترح الكتل الكتلة الفائزة من البنّائين.","extended","B2","COCA"],
["payload delivery","noun phrase","تسليم الحمولة","Payload delivery transfers the assembled block to the proposer.","ينقل تسليم الحمولة الكتلة المجمّعة إلى المقترح.","mastery","C1","AWL"],
["blob sidecar","noun phrase","ملحق البيانات الثنائية الكبيرة","A blob sidecar carries large data payloads for rollup transactions.","يحمل ملحق البيانات الثنائية الكبيرة حمولات بيانات ضخمة لمعاملات التجميع.","mastery","C1","AWL"]
];

const u7 = [
["elaboration likelihood model","noun phrase","نموذج احتمالية التفصيل","The elaboration likelihood model explains two routes to persuasion.","يشرح نموذج احتمالية التفصيل مسارين للإقناع.","extended","B2","COCA"],
["central route processing","noun phrase","المعالجة عبر المسار المركزي","Central route processing involves careful evaluation of arguments.","تتضمن المعالجة عبر المسار المركزي تقييماً دقيقاً للحجج.","mastery","C1","AWL"],
["peripheral route processing","noun phrase","المعالجة عبر المسار المحيطي","Peripheral route processing relies on superficial cues like attractiveness.","تعتمد المعالجة عبر المسار المحيطي على إشارات سطحية كالجاذبية.","mastery","C1","AWL"],
["heuristic-systematic model","noun phrase","النموذج الاستدلالي المنهجي","The heuristic-systematic model describes parallel processing modes.","يصف النموذج الاستدلالي المنهجي أنماط معالجة متوازية.","mastery","C1","AWL"],
["sufficiency threshold","noun phrase","عتبة الكفاية","People process more deeply when below their sufficiency threshold.","يعالج الناس بعمق أكبر عندما يكونون دون عتبة الكفاية.","mastery","C1","AWL"],
["defense motivation","noun phrase","دافع الدفاع","Defense motivation leads to biased processing of threatening information.","يؤدي دافع الدفاع إلى معالجة متحيزة للمعلومات المهددة.","mastery","C1","COCA"],
["accuracy motivation","noun phrase","دافع الدقة","Accuracy motivation promotes open-minded evaluation of evidence.","يعزز دافع الدقة التقييم المنفتح للأدلة.","mastery","C1","COCA"],
["impression motivation","noun phrase","دافع الانطباع","Impression motivation drives people to adopt socially acceptable positions.","يدفع دافع الانطباع الناس لتبني مواقف مقبولة اجتماعياً.","mastery","C1","COCA"],
["dual process theory","noun phrase","نظرية العملية المزدوجة","Dual process theory distinguishes automatic from deliberate thinking.","تميز نظرية العملية المزدوجة بين التفكير التلقائي والمتعمد.","extended","B2","COCA"],
["system one thinking","noun phrase","تفكير النظام الأول","System one thinking operates quickly and with little conscious effort.","يعمل تفكير النظام الأول بسرعة وبجهد واعٍ قليل.","extended","B2","COCA"],
["system two thinking","noun phrase","تفكير النظام الثاني","System two thinking requires deliberate attention and mental energy.","يتطلب تفكير النظام الثاني انتباهاً متعمداً وطاقة ذهنية.","extended","B2","COCA"],
["bounded rationality","noun phrase","العقلانية المحدودة","Bounded rationality recognizes cognitive limits on decision-making.","تعترف العقلانية المحدودة بالحدود المعرفية على اتخاذ القرار.","extended","B2","COCA"],
["satisficing behavior","noun phrase","سلوك الاكتفاء","Satisficing behavior accepts good-enough options instead of the best.","يقبل سلوك الاكتفاء بخيارات جيدة كفاية بدلاً من الأفضل.","mastery","C1","AWL"],
["maximizing behavior","noun phrase","سلوك التعظيم","Maximizing behavior exhaustively searches for the optimal choice.","يبحث سلوك التعظيم بشكل شامل عن الخيار الأمثل.","mastery","C1","AWL"],
["regret theory","noun phrase","نظرية الندم","Regret theory predicts choices based on anticipated emotional outcomes.","تتنبأ نظرية الندم بالخيارات بناءً على النتائج العاطفية المتوقعة.","mastery","C1","COCA"],
["prospect theory","noun phrase","نظرية التوقع","Prospect theory shows that losses loom larger than equivalent gains.","تُظهر نظرية التوقع أن الخسائر تبدو أكبر من المكاسب المعادلة.","extended","B2","COCA"],
["reference point","noun phrase","نقطة المرجع","The reference point determines whether an outcome feels like a gain or loss.","تحدد نقطة المرجع ما إذا كانت النتيجة تُشعر بالربح أو الخسارة.","extended","B2","COCA"],
["loss domain","noun phrase","نطاق الخسارة","In the loss domain people tend to be risk-seeking.","في نطاق الخسارة يميل الناس إلى المخاطرة.","mastery","C1","AWL"],
["gain domain","noun phrase","نطاق الربح","In the gain domain people generally prefer certainty.","في نطاق الربح يفضل الناس عموماً اليقين.","mastery","C1","AWL"],
["certainty effect","noun phrase","تأثير اليقين","The certainty effect overweights outcomes that are guaranteed.","يُفرط تأثير اليقين في ترجيح النتائج المضمونة.","mastery","C1","AWL"],
["isolation effect","noun phrase","تأثير العزل","The isolation effect simplifies choices by ignoring shared components.","يبسط تأثير العزل الخيارات بتجاهل المكونات المشتركة.","mastery","C1","AWL"],
["reflection effect","noun phrase","تأثير الانعكاس","The reflection effect reverses risk preferences across gain and loss domains.","يعكس تأثير الانعكاس تفضيلات المخاطرة عبر نطاقي الربح والخسارة.","mastery","C1","AWL"],
["endowment effect","noun phrase","تأثير الامتلاك","The endowment effect makes people value what they own more highly.","يجعل تأثير الامتلاك الناس يقدرون ما يملكونه بشكل أعلى.","extended","B2","COCA"],
["status quo bias mechanism","noun phrase","آلية تحيز الوضع الراهن","The status quo bias mechanism explains preference for current arrangements.","تشرح آلية تحيز الوضع الراهن تفضيل الترتيبات الحالية.","mastery","C1","AWL"],
["omission bias","noun phrase","تحيز الإغفال","Omission bias leads people to prefer inaction over action with equal risk.","يدفع تحيز الإغفال الناس لتفضيل عدم الفعل على الفعل بخطر متساوٍ.","mastery","C1","COCA"],
["default effect","noun phrase","تأثير الخيار الافتراضي","The default effect shows that pre-selected options are rarely changed.","يُظهر تأثير الخيار الافتراضي أن الخيارات المحددة مسبقاً نادراً ما تُغيّر.","extended","B2","COCA"],
["decoy effect","noun phrase","تأثير الطُعم","The decoy effect shifts preference by introducing an inferior option.","يغير تأثير الطُعم التفضيل بإدخال خيار أدنى.","extended","B2","COCA"],
["attraction effect","noun phrase","تأثير الجذب","The attraction effect increases choice share of the dominating option.","يزيد تأثير الجذب حصة الاختيار للخيار المهيمن.","mastery","C1","AWL"],
["compromise effect","noun phrase","تأثير الحل الوسط","The compromise effect favors middle options in a choice set.","يفضل تأثير الحل الوسط الخيارات الوسطى في مجموعة الاختيارات.","mastery","C1","AWL"],
["similarity effect","noun phrase","تأثير التشابه","The similarity effect reduces share for options that resemble each other.","يقلل تأثير التشابه حصة الخيارات المتشابهة.","mastery","C1","AWL"],
["phantom decoy","noun phrase","طُعم وهمي","A phantom decoy is unavailable but still influences choice.","الطُعم الوهمي غير متاح لكنه يؤثر على الاختيار.","mastery","C1","COCA"],
["dominated alternative","noun phrase","بديل مهيمَن عليه","A dominated alternative is worse on all attributes than another option.","البديل المهيمَن عليه أسوأ في جميع الصفات من خيار آخر.","mastery","C1","AWL"],
["asymmetric dominance","noun phrase","الهيمنة غير المتماثلة","Asymmetric dominance explains why adding a decoy changes preferences.","تفسر الهيمنة غير المتماثلة سبب تغيير إضافة طُعم للتفضيلات.","mastery","C1","AWL"],
["context effect","noun phrase","تأثير السياق","A context effect alters judgment based on surrounding options.","يغير تأثير السياق الحكم بناءً على الخيارات المحيطة.","extended","B2","COCA"],
["range-frequency theory","noun phrase","نظرية المدى والتكرار","Range-frequency theory predicts how people judge stimuli in context.","تتنبأ نظرية المدى والتكرار بكيفية حكم الناس على المحفزات في السياق.","mastery","C1","AWL"]
];

const u8 = [
["automated fingerprint identification system","noun phrase","نظام التعرف الآلي على البصمات","The automated fingerprint identification system searches millions of records.","يبحث نظام التعرف الآلي على البصمات في ملايين السجلات.","extended","B2","COCA"],
["combined DNA index system","noun phrase","نظام فهرس الحمض النووي المشترك","The combined DNA index system links crime scene profiles to offenders.","يربط نظام فهرس الحمض النووي المشترك ملفات مسرح الجريمة بالجناة.","mastery","C1","COCA"],
["integrated ballistic identification system","noun phrase","نظام تحديد المقذوفات المتكامل","The integrated ballistic identification system matches bullet markings.","يطابق نظام تحديد المقذوفات المتكامل علامات الرصاص.","mastery","C1","AWL"],
["national integrated ballistic information network","noun phrase","شبكة معلومات المقذوفات الوطنية المتكاملة","The national integrated ballistic information network connects labs nationwide.","تربط شبكة معلومات المقذوفات الوطنية المتكاملة المختبرات على مستوى البلاد.","mastery","C1","AWL"],
["paintData query system","noun phrase","نظام استعلام بيانات الطلاء","The paintData query system identifies vehicle paint layer sequences.","يحدد نظام استعلام بيانات الطلاء تسلسلات طبقات طلاء المركبات.","mastery","C1","AWL"],
["international forensic automotive paint database","noun phrase","قاعدة بيانات طلاء السيارات الجنائية الدولية","The international forensic automotive paint database aids hit-and-run investigations.","تساعد قاعدة بيانات طلاء السيارات الجنائية الدولية في تحقيقات حوادث الفرار.","mastery","C1","AWL"],
["glass evidence reference database","noun phrase","قاعدة بيانات مرجعية لأدلة الزجاج","The glass evidence reference database stores refractive index measurements.","تخزن قاعدة بيانات مرجعية لأدلة الزجاج قياسات معامل الانكسار.","mastery","C1","AWL"],
["ignitable liquid reference collection","noun phrase","مجموعة مرجعية للسوائل القابلة للاشتعال","The ignitable liquid reference collection aids arson case analysis.","تساعد المجموعة المرجعية للسوائل القابلة للاشتعال في تحليل قضايا الحرق المتعمد.","mastery","C1","AWL"],
["mass spectral library","noun phrase","مكتبة أطياف الكتلة","The mass spectral library enables rapid compound identification.","تتيح مكتبة أطياف الكتلة تحديد المركبات بسرعة.","extended","B2","COCA"],
["infrared spectral library","noun phrase","مكتبة الأطياف تحت الحمراء","An infrared spectral library matches unknown materials to known spectra.","تطابق مكتبة الأطياف تحت الحمراء مواد مجهولة بأطياف معروفة.","extended","B2","COCA"],
["Raman spectral library","noun phrase","مكتبة أطياف رامان","A Raman spectral library identifies substances without sample preparation.","تحدد مكتبة أطياف رامان المواد دون تحضير العينة.","mastery","C1","AWL"],
["fiber reference collection","noun phrase","مجموعة مرجعية للألياف","The fiber reference collection contains thousands of textile samples.","تحتوي المجموعة المرجعية للألياف على آلاف عينات النسيج.","mastery","C1","AWL"],
["explosive reference database","noun phrase","قاعدة بيانات مرجعية للمتفجرات","The explosive reference database catalogs chemical signatures of explosives.","تفهرس قاعدة بيانات مرجعية للمتفجرات التوقيعات الكيميائية للمتفجرات.","mastery","C1","AWL"],
["controlled substance reference","noun phrase","مرجع المواد الخاضعة للرقابة","A controlled substance reference provides certified drug standards.","يوفر مرجع المواد الخاضعة للرقابة معايير دوائية معتمدة.","extended","B2","COCA"],
["reference material certificate","noun phrase","شهادة المادة المرجعية","A reference material certificate states certified property values.","تذكر شهادة المادة المرجعية قيم الخصائص المعتمدة.","mastery","C1","AWL"],
["measurement uncertainty","noun phrase","عدم يقين القياس","Measurement uncertainty quantifies doubt about any analytical result.","يحدد عدم يقين القياس الشك حول أي نتيجة تحليلية.","extended","B2","COCA"],
["expanded uncertainty","noun phrase","عدم اليقين الموسع","Expanded uncertainty provides a confidence interval for the measurement.","يوفر عدم اليقين الموسع فاصل ثقة للقياس.","mastery","C1","AWL"],
["coverage factor","noun phrase","عامل التغطية","A coverage factor of two gives approximately 95% confidence.","يعطي عامل تغطية قدره اثنان ثقة تقارب 95%.","mastery","C1","AWL"],
["type A evaluation","noun phrase","تقييم النوع أ","Type A evaluation uses statistical analysis of repeated observations.","يستخدم تقييم النوع أ التحليل الإحصائي للملاحظات المتكررة.","mastery","C1","AWL"],
["type B evaluation","noun phrase","تقييم النوع ب","Type B evaluation uses non-statistical methods like calibration data.","يستخدم تقييم النوع ب طرقاً غير إحصائية كبيانات المعايرة.","mastery","C1","AWL"],
["combined standard uncertainty","noun phrase","عدم اليقين القياسي المجمع","Combined standard uncertainty merges all individual uncertainty components.","يدمج عدم اليقين القياسي المجمع جميع مكونات عدم اليقين الفردية.","mastery","C1","AWL"],
["sensitivity coefficient","noun phrase","معامل الحساسية","The sensitivity coefficient shows how input changes affect the result.","يُظهر معامل الحساسية كيف تؤثر تغيرات المدخلات على النتيجة.","mastery","C1","COCA"],
["measurand definition","noun phrase","تعريف الكمية المقيسة","A clear measurand definition is the first step in any measurement.","تعريف واضح للكمية المقيسة هو الخطوة الأولى في أي قياس.","mastery","C1","AWL"],
["traceability chain","noun phrase","سلسلة التتبع","A traceability chain links laboratory measurements to international standards.","تربط سلسلة التتبع قياسات المختبر بالمعايير الدولية.","extended","B2","COCA"],
["calibration certificate","noun phrase","شهادة المعايرة","A calibration certificate documents instrument performance parameters.","توثق شهادة المعايرة معايير أداء الجهاز.","extended","B2","COCA"],
["proficiency test result","noun phrase","نتيجة اختبار الكفاءة","A proficiency test result demonstrates laboratory analytical competence.","تُظهر نتيجة اختبار الكفاءة كفاءة المختبر التحليلية.","extended","B2","AWL"],
["z-score evaluation","noun phrase","تقييم الدرجة المعيارية","A z-score evaluation flags results deviating from the consensus.","يُعلّم تقييم الدرجة المعيارية النتائج المنحرفة عن الإجماع.","mastery","C1","AWL"],
["En number","noun phrase","رقم إي إن","The En number assesses agreement between two measurement results.","يُقيّم رقم إي إن التوافق بين نتيجتي قياس.","mastery","C1","AWL"],
["interlaboratory comparison","noun phrase","مقارنة بين المختبرات","An interlaboratory comparison verifies measurement consistency across labs.","تتحقق المقارنة بين المختبرات من اتساق القياس عبر المختبرات.","extended","B2","COCA"],
["method validation protocol","noun phrase","بروتوكول التحقق من الطريقة","A method validation protocol outlines all required performance tests.","يحدد بروتوكول التحقق من الطريقة جميع اختبارات الأداء المطلوبة.","mastery","C1","AWL"],
["selectivity study","noun phrase","دراسة الانتقائية","A selectivity study confirms the method measures only the target analyte.","تؤكد دراسة الانتقائية أن الطريقة تقيس المادة المستهدفة فقط.","mastery","C1","AWL"],
["linearity study","noun phrase","دراسة الخطية","A linearity study tests proportionality across the measurement range.","تختبر دراسة الخطية التناسب عبر نطاق القياس.","mastery","C1","AWL"],
["accuracy study","noun phrase","دراسة الدقة","An accuracy study compares measured values to certified reference values.","تقارن دراسة الدقة القيم المقاسة بالقيم المرجعية المعتمدة.","extended","B2","COCA"],
["precision study","noun phrase","دراسة الإحكام","A precision study evaluates repeatability and reproducibility.","تقيّم دراسة الإحكام التكرارية والاستنساخية.","extended","B2","COCA"],
["robustness study","noun phrase","دراسة المتانة","A robustness study tests method performance under varied conditions.","تختبر دراسة المتانة أداء الطريقة تحت ظروف متنوعة.","mastery","C1","AWL"]
];

const u9 = [
["Harris matrix","noun phrase","مصفوفة هاريس","A Harris matrix diagrams the sequence of archaeological deposits.","ترسم مصفوفة هاريس تسلسل الطبقات الأثرية.","mastery","C1","COCA"],
["stratigraphic sequence","noun phrase","التسلسل الطبقي","The stratigraphic sequence reveals the site's chronological history.","يكشف التسلسل الطبقي التاريخ الزمني للموقع.","extended","B2","COCA"],
["interface surface","noun phrase","سطح بيني","An interface surface represents a period of erosion or activity.","يمثل السطح البيني فترة من التعرية أو النشاط.","mastery","C1","AWL"],
["period grouping","noun phrase","تجميع الفترات","Period grouping organizes contexts into broader chronological phases.","يُنظم تجميع الفترات السياقات في مراحل زمنية أوسع.","mastery","C1","AWL"],
["phase assignment","noun phrase","تعيين المرحلة","Phase assignment links individual contexts to defined site periods.","يربط تعيين المرحلة السياقات الفردية بفترات الموقع المحددة.","mastery","C1","AWL"],
["single context recording","noun phrase","تسجيل السياق الفردي","Single context recording documents each deposit as a separate unit.","يوثق تسجيل السياق الفردي كل ترسب كوحدة منفصلة.","mastery","C1","AWL"],
["context sheet","noun phrase","ورقة السياق","A context sheet records soil type, color, and inclusions.","تسجل ورقة السياق نوع التربة ولونها ومحتوياتها.","extended","B2","COCA"],
["section drawing","noun phrase","رسم مقطعي","A section drawing shows the vertical profile of excavated deposits.","يُظهر الرسم المقطعي المقطع العمودي للطبقات المنقبة.","extended","B2","COCA"],
["plan drawing","noun phrase","رسم مسطح","A plan drawing records features as seen from directly above.","يسجل الرسم المسطح المعالم كما تُرى من الأعلى مباشرة.","extended","B2","COCA"],
["elevation drawing","noun phrase","رسم واجهي","An elevation drawing documents standing walls and vertical structures.","يوثق الرسم الواجهي الجدران القائمة والهياكل العمودية.","extended","B2","COCA"],
["finds register","noun phrase","سجل اللقى","The finds register catalogs every artifact with its context number.","يفهرس سجل اللقى كل قطعة أثرية برقم سياقها.","mastery","C1","COCA"],
["environmental sample","noun phrase","عينة بيئية","An environmental sample preserves seeds and other organic remains.","تحفظ العينة البيئية البذور والبقايا العضوية الأخرى.","extended","B2","COCA"],
["flotation recovery","noun phrase","الاستخلاص بالتعويم","Flotation recovery separates light organic material from soil.","يفصل الاستخلاص بالتعويم المواد العضوية الخفيفة عن التربة.","mastery","C1","AWL"],
["wet sieving","noun phrase","الغربلة الرطبة","Wet sieving washes soil through mesh to recover small finds.","تغسل الغربلة الرطبة التربة عبر الشبكة لاستخلاص اللقى الصغيرة.","extended","B2","COCA"],
["dry sieving","noun phrase","الغربلة الجافة","Dry sieving sorts excavated soil without the addition of water.","تفرز الغربلة الجافة التربة المنقبة دون إضافة الماء.","extended","B2","COCA"],
["heavy residue","noun phrase","رواسب ثقيلة","Heavy residue from flotation contains bone fragments and pottery.","تحتوي الرواسب الثقيلة من التعويم على شظايا عظام وفخار.","mastery","C1","COCA"],
["light fraction","noun phrase","الجزء الخفيف","The light fraction from flotation yields charred plant remains.","ينتج الجزء الخفيف من التعويم بقايا نباتية متفحمة.","mastery","C1","AWL"],
["magnetic susceptibility","noun phrase","القابلية المغناطيسية","Magnetic susceptibility detects areas of past burning activity.","تكشف القابلية المغناطيسية مناطق نشاط الاحتراق السابق.","mastery","C1","COCA"],
["soil micromorphology","noun phrase","مورفولوجيا التربة الدقيقة","Soil micromorphology examines thin sections under a polarizing microscope.","تفحص مورفولوجيا التربة الدقيقة المقاطع الرقيقة تحت مجهر استقطابي.","mastery","C1","AWL"],
["thin section petrography","noun phrase","بتروغرافيا المقاطع الرقيقة","Thin section petrography identifies mineral composition of ceramics.","تحدد بتروغرافيا المقاطع الرقيقة التركيب المعدني للخزف.","mastery","C1","AWL"],
["ceramic fabric analysis","noun phrase","تحليل نسيج الخزف","Ceramic fabric analysis reveals clay source and manufacturing technique.","يكشف تحليل نسيج الخزف مصدر الطين وتقنية التصنيع.","mastery","C1","AWL"],
["temper identification","noun phrase","تحديد المادة المقسية","Temper identification classifies non-plastic inclusions added to clay.","يصنف تحديد المادة المقسية الشوائب غير البلاستيكية المضافة للطين.","mastery","C1","AWL"],
["firing temperature","noun phrase","درجة حرارة الحرق","Firing temperature affects the color and hardness of pottery.","تؤثر درجة حرارة الحرق على لون وصلابة الفخار.","extended","B2","COCA"],
["kiln atmosphere","noun phrase","جو الفرن","Kiln atmosphere determines the final color of the ceramic body.","يحدد جو الفرن اللون النهائي لجسم الخزف.","mastery","C1","AWL"],
["oxidizing atmosphere","noun phrase","جو مؤكسد","An oxidizing atmosphere produces red and orange pottery tones.","ينتج الجو المؤكسد درجات فخار حمراء وبرتقالية.","extended","B2","COCA"],
["reducing atmosphere","noun phrase","جو مختزل","A reducing atmosphere yields grey and black surface colors.","ينتج الجو المختزل ألوان سطح رمادية وسوداء.","extended","B2","COCA"],
["surface treatment","noun phrase","معالجة السطح","Surface treatment enhances the appearance and durability of vessels.","تعزز معالجة السطح مظهر ومتانة الأوعية.","extended","B2","COCA"],
["slip application","noun phrase","تطبيق الطلاء الطيني","Slip application coats the vessel with a thin clay layer.","يغطي تطبيق الطلاء الطيني الوعاء بطبقة طين رقيقة.","mastery","C1","AWL"],
["burnishing technique","noun phrase","تقنية الصقل","A burnishing technique polishes the surface to a smooth sheen.","تصقل تقنية الصقل السطح إلى لمعان ناعم.","mastery","C1","COCA"],
["incised decoration","noun phrase","زخرفة محفورة","Incised decoration cuts patterns into the clay before firing.","تحفر الزخرفة المحفورة أنماطاً في الطين قبل الحرق.","mastery","C1","COCA"],
["stamped decoration","noun phrase","زخرفة مختومة","Stamped decoration impresses repeated motifs onto wet clay.","تطبع الزخرفة المختومة زخارف متكررة على الطين الرطب.","mastery","C1","COCA"],
["applied decoration","noun phrase","زخرفة مضافة","Applied decoration attaches clay strips or pellets to the vessel.","تلصق الزخرفة المضافة شرائط أو كريات طينية بالوعاء.","mastery","C1","AWL"],
["painted decoration","noun phrase","زخرفة مطلية","Painted decoration adds pigment designs to the ceramic surface.","تضيف الزخرفة المطلية تصاميم صبغية إلى سطح الخزف.","extended","B2","COCA"],
["glazed surface","noun phrase","سطح مزجج","A glazed surface is waterproof and easy to clean.","السطح المزجج مقاوم للماء وسهل التنظيف.","extended","B2","COCA"],
["vitrification point","noun phrase","نقطة التزجج","The vitrification point is where clay becomes fully glass-like.","نقطة التزجج هي حيث يصبح الطين شبيهاً بالزجاج تماماً.","mastery","C1","AWL"]
];

const u10 = [
["polypharmacy assessment","noun phrase","تقييم تعدد الأدوية","A polypharmacy assessment reviews all medications for necessity.","يراجع تقييم تعدد الأدوية جميع الأدوية من حيث الضرورة.","extended","B2","COCA"],
["medication reconciliation","noun phrase","مصالحة الأدوية","Medication reconciliation compares prescribed drugs across care settings.","تقارن مصالحة الأدوية العقاقير الموصوفة عبر مواقع الرعاية.","extended","B2","COCA"],
["Beers criteria","noun phrase","معايير بيرز","Beers criteria list potentially inappropriate medications for older adults.","تسرد معايير بيرز الأدوية التي قد تكون غير مناسبة لكبار السن.","mastery","C1","COCA"],
["STOPP criteria","noun phrase","معايير ستوب","STOPP criteria identify prescriptions that should be discontinued.","تحدد معايير ستوب الوصفات التي يجب إيقافها.","mastery","C1","AWL"],
["START criteria","noun phrase","معايير ستارت","START criteria highlight medications that should be initiated.","تسلط معايير ستارت الضوء على الأدوية التي يجب البدء بها.","mastery","C1","AWL"],
["anticholinergic burden","noun phrase","العبء المضاد للكولين","High anticholinergic burden increases risk of cognitive decline.","يزيد العبء العالي المضاد للكولين من خطر التدهور المعرفي.","mastery","C1","COCA"],
["drug interaction checker","noun phrase","مدقق التفاعلات الدوائية","A drug interaction checker flags potentially dangerous combinations.","يُعلّم مدقق التفاعلات الدوائية التركيبات الخطرة المحتملة.","extended","B2","COCA"],
["therapeutic drug monitoring","noun phrase","المراقبة العلاجية للأدوية","Therapeutic drug monitoring adjusts doses to maintain safe blood levels.","تعدل المراقبة العلاجية للأدوية الجرعات للحفاظ على مستويات دم آمنة.","mastery","C1","COCA"],
["dose adjustment","noun phrase","تعديل الجرعة","Dose adjustment is essential when organ function declines.","تعديل الجرعة ضروري عند تراجع وظائف الأعضاء.","extended","B2","COCA"],
["renal dose adjustment","noun phrase","تعديل الجرعة الكلوية","Renal dose adjustment prevents drug accumulation in kidney impairment.","يمنع تعديل الجرعة الكلوية تراكم الدواء في القصور الكلوي.","mastery","C1","AWL"],
["hepatic dose adjustment","noun phrase","تعديل الجرعة الكبدية","Hepatic dose adjustment accounts for impaired drug metabolism.","يأخذ تعديل الجرعة الكبدية في الاعتبار ضعف استقلاب الدواء.","mastery","C1","AWL"],
["geriatric dosing","noun phrase","جرعات كبار السن","Geriatric dosing starts low and titrates slowly to effect.","تبدأ جرعات كبار السن منخفضة وتُعاير ببطء حتى التأثير.","extended","B2","COCA"],
["deprescribing protocol","noun phrase","بروتوكول إلغاء الوصفة","A deprescribing protocol guides safe withdrawal of unnecessary medications.","يوجه بروتوكول إلغاء الوصفة الانسحاب الآمن من الأدوية غير الضرورية.","mastery","C1","AWL"],
["medication tapering","noun phrase","تخفيض تدريجي للدواء","Medication tapering reduces doses gradually to avoid withdrawal.","يقلل التخفيض التدريجي للدواء الجرعات بالتدريج لتجنب الانسحاب.","extended","B2","COCA"],
["withdrawal syndrome","noun phrase","متلازمة الانسحاب","Withdrawal syndrome can occur after abrupt medication cessation.","يمكن أن تحدث متلازمة الانسحاب بعد التوقف المفاجئ عن الدواء.","extended","B2","COCA"],
["rebound phenomenon","noun phrase","ظاهرة الارتداد","The rebound phenomenon causes symptom recurrence after stopping treatment.","تسبب ظاهرة الارتداد عودة الأعراض بعد إيقاف العلاج.","mastery","C1","COCA"],
["discontinuation syndrome","noun phrase","متلازمة التوقف","Discontinuation syndrome includes dizziness and mood changes.","تشمل متلازمة التوقف الدوخة وتغيرات المزاج.","mastery","C1","COCA"],
["adverse drug reaction","noun phrase","تفاعل دوائي ضار","An adverse drug reaction requires immediate clinical assessment.","يتطلب التفاعل الدوائي الضار تقييماً سريرياً فورياً.","extended","B2","COCA"],
["pharmacovigilance system","noun phrase","نظام اليقظة الدوائية","A pharmacovigilance system monitors drug safety after market approval.","يراقب نظام اليقظة الدوائية سلامة الأدوية بعد الموافقة على تسويقها.","mastery","C1","AWL"],
["yellow card scheme","noun phrase","نظام البطاقة الصفراء","The yellow card scheme collects reports of suspected drug reactions.","يجمع نظام البطاقة الصفراء تقارير عن تفاعلات دوائية مشتبه بها.","mastery","C1","COCA"],
["MedWatch report","noun phrase","تقرير ميد ووتش","A MedWatch report documents serious adverse events in the United States.","يوثق تقرير ميد ووتش الأحداث الضارة الخطيرة في الولايات المتحدة.","mastery","C1","COCA"],
["Uppsala Monitoring Centre","noun phrase","مركز أوبسالا للمراقبة","The Uppsala Monitoring Centre coordinates global pharmacovigilance data.","ينسق مركز أوبسالا للمراقبة بيانات اليقظة الدوائية العالمية.","mastery","C1","AWL"],
["signal detection","noun phrase","كشف الإشارات","Signal detection identifies potential new safety concerns from data.","يحدد كشف الإشارات مخاوف السلامة الجديدة المحتملة من البيانات.","extended","B2","COCA"],
["disproportionality analysis","noun phrase","تحليل عدم التناسب","Disproportionality analysis compares observed to expected reporting rates.","يقارن تحليل عدم التناسب معدلات الإبلاغ الملاحظة بالمتوقعة.","mastery","C1","AWL"],
["proportional reporting ratio","noun phrase","نسبة الإبلاغ التناسبية","The proportional reporting ratio flags drugs with excess adverse events.","تُعلّم نسبة الإبلاغ التناسبية الأدوية ذات الأحداث الضارة المفرطة.","mastery","C1","AWL"],
["reporting odds ratio","noun phrase","نسبة أرجحية الإبلاغ","The reporting odds ratio measures association between drug and event.","تقيس نسبة أرجحية الإبلاغ الارتباط بين الدواء والحدث.","mastery","C1","AWL"],
["information component","noun phrase","مكون المعلومات","The information component uses Bayesian methods for signal detection.","يستخدم مكون المعلومات طرقاً بايزية لكشف الإشارات.","mastery","C1","AWL"],
["empirical Bayes","noun phrase","بايز التجريبي","Empirical Bayes methods stabilize estimates with small sample sizes.","تُثبّت طرق بايز التجريبي التقديرات مع أحجام العينات الصغيرة.","mastery","C1","AWL"],
["multi-item gamma Poisson shrinker","noun phrase","مُقلّص غاما بواسون متعدد العناصر","The multi-item gamma Poisson shrinker detects safety signals in databases.","يكشف مُقلّص غاما بواسون متعدد العناصر إشارات السلامة في قواعد البيانات.","mastery","C1","AWL"],
["temporal pattern discovery","noun phrase","اكتشاف الأنماط الزمنية","Temporal pattern discovery reveals time-dependent adverse effects.","يكشف اكتشاف الأنماط الزمنية التأثيرات الضارة المعتمدة على الوقت.","mastery","C1","AWL"],
["sequence symmetry analysis","noun phrase","تحليل تناظر التسلسل","Sequence symmetry analysis detects drug-induced events using prescription data.","يكشف تحليل تناظر التسلسل الأحداث المستحثة بالأدوية باستخدام بيانات الوصفات.","mastery","C1","AWL"],
["self-controlled case series","noun phrase","سلسلة حالات ذاتية الضبط","A self-controlled case series compares risk within the same individual.","تقارن سلسلة الحالات ذاتية الضبط الخطر ضمن نفس الفرد.","mastery","C1","AWL"],
["case-crossover design","noun phrase","تصميم التقاطع الحالاتي","A case-crossover design compares exposures before the event to control periods.","يقارن تصميم التقاطع الحالاتي التعرضات قبل الحدث بفترات الضبط.","mastery","C1","AWL"],
["prescription event monitoring","noun phrase","مراقبة أحداث الوصفات","Prescription event monitoring tracks outcomes in newly prescribed patients.","تتتبع مراقبة أحداث الوصفات النتائج لدى المرضى الموصوف لهم حديثاً.","mastery","C1","AWL"],
["modified prescription event monitoring","noun phrase","مراقبة أحداث الوصفات المعدلة","Modified prescription event monitoring uses electronic health records.","تستخدم مراقبة أحداث الوصفات المعدلة السجلات الصحية الإلكترونية.","mastery","C1","AWL"]
];

const u11 = [
["building performance simulation","noun phrase","محاكاة أداء المبنى","Building performance simulation predicts energy use before construction.","تتنبأ محاكاة أداء المبنى باستهلاك الطاقة قبل البناء.","extended","B2","COCA"],
["EnergyPlus engine","noun phrase","محرك إنرجي بلس","The EnergyPlus engine models heating, cooling, and lighting loads.","يحاكي محرك إنرجي بلس أحمال التدفئة والتبريد والإضاءة.","mastery","C1","COCA"],
["TRNSYS simulation","noun phrase","محاكاة ترنسيس","TRNSYS simulation models transient thermal behavior of buildings.","تحاكي محاكاة ترنسيس السلوك الحراري العابر للمباني.","mastery","C1","AWL"],
["ESP-r model","noun phrase","نموذج إي إس بي آر","The ESP-r model handles complex multi-zone thermal simulations.","يتعامل نموذج إي إس بي آر مع محاكاة حرارية معقدة متعددة المناطق.","mastery","C1","AWL"],
["IES-VE software","noun phrase","برنامج آي إي إس في إي","IES-VE software provides integrated environmental analysis.","يوفر برنامج آي إي إس في إي تحليلاً بيئياً متكاملاً.","mastery","C1","COCA"],
["DesignBuilder interface","noun phrase","واجهة ديزاين بيلدر","The DesignBuilder interface simplifies EnergyPlus model creation.","تبسط واجهة ديزاين بيلدر إنشاء نماذج إنرجي بلس.","mastery","C1","COCA"],
["OpenStudio platform","noun phrase","منصة أوبن ستوديو","The OpenStudio platform supports parametric energy modeling.","تدعم منصة أوبن ستوديو النمذجة الطاقوية البارامترية.","mastery","C1","COCA"],
["Ladybug Tools","noun phrase","أدوات ليدي بج","Ladybug Tools integrate environmental analysis into Grasshopper.","تدمج أدوات ليدي بج التحليل البيئي في غراسهوبر.","mastery","C1","COCA"],
["Honeybee plugin","noun phrase","إضافة هني بي","The Honeybee plugin enables daylight and energy simulation in Rhino.","تتيح إضافة هني بي محاكاة ضوء النهار والطاقة في راينو.","mastery","C1","AWL"],
["Dragonfly extension","noun phrase","ملحق دراغن فلاي","The Dragonfly extension scales building analysis to district level.","يوسع ملحق دراغن فلاي تحليل المبنى إلى مستوى الحي.","mastery","C1","AWL"],
["Urban Weather Generator","noun phrase","مولد الطقس الحضري","The Urban Weather Generator adjusts weather data for urban heat islands.","يعدل مولد الطقس الحضري بيانات الطقس لجزر الحرارة الحضرية.","mastery","C1","AWL"],
["ENVI-met simulation","noun phrase","محاكاة إنفي ميت","ENVI-met simulation models microclimate interactions in urban spaces.","تحاكي محاكاة إنفي ميت تفاعلات المناخ المحلي في الفضاءات الحضرية.","mastery","C1","AWL"],
["PALM model","noun phrase","نموذج بالم","The PALM model simulates atmospheric boundary layer processes.","يحاكي نموذج بالم عمليات طبقة الحدود الجوية.","mastery","C1","AWL"],
["CitySim platform","noun phrase","منصة سيتي سيم","The CitySim platform estimates urban building energy demand.","تُقدّر منصة سيتي سيم الطلب على طاقة المباني الحضرية.","mastery","C1","AWL"],
["Urban Building Energy Model","noun phrase","نموذج طاقة المباني الحضرية","An Urban Building Energy Model aggregates thousands of buildings.","يجمع نموذج طاقة المباني الحضرية آلاف المباني.","mastery","C1","AWL"],
["district energy system","noun phrase","نظام طاقة المنطقة","A district energy system serves multiple buildings from a central plant.","يخدم نظام طاقة المنطقة مبانٍ متعددة من محطة مركزية.","extended","B2","COCA"],
["combined heat and power","noun phrase","الطاقة الحرارية والكهربائية المشتركة","Combined heat and power systems achieve over 80% fuel efficiency.","تحقق أنظمة الطاقة الحرارية والكهربائية المشتركة كفاءة وقود تتجاوز 80%.","extended","B2","COCA"],
["absorption chiller","noun phrase","مبرد امتصاصي","An absorption chiller uses waste heat to produce cooling.","يستخدم المبرد الامتصاصي الحرارة المهدورة لإنتاج التبريد.","mastery","C1","COCA"],
["desiccant cooling","noun phrase","التبريد بالمجففات","Desiccant cooling removes humidity before air enters the space.","يزيل التبريد بالمجففات الرطوبة قبل دخول الهواء إلى الفضاء.","mastery","C1","AWL"],
["evaporative cooling tower","noun phrase","برج تبريد تبخيري","An evaporative cooling tower rejects heat through water evaporation.","يطرد برج التبريد التبخيري الحرارة من خلال تبخر الماء.","extended","B2","COCA"],
["ice thermal storage","noun phrase","تخزين حراري بالجليد","Ice thermal storage shifts cooling production to off-peak hours.","يحول التخزين الحراري بالجليد إنتاج التبريد إلى ساعات خارج الذروة.","mastery","C1","AWL"],
["chilled water storage","noun phrase","تخزين المياه المبردة","Chilled water storage reduces peak electrical demand for cooling.","يقلل تخزين المياه المبردة ذروة الطلب الكهربائي للتبريد.","mastery","C1","COCA"],
["hot water storage","noun phrase","تخزين الماء الساخن","Hot water storage buffers solar thermal output for evening use.","يخزن تخزين الماء الساخن إنتاج الطاقة الشمسية الحرارية للاستخدام المسائي.","extended","B2","COCA"],
["seasonal thermal energy storage","noun phrase","تخزين الطاقة الحرارية الموسمي","Seasonal thermal energy storage saves summer heat for winter use.","يحفظ تخزين الطاقة الحرارية الموسمي حرارة الصيف لاستخدام الشتاء.","mastery","C1","AWL"],
["borehole thermal energy storage","noun phrase","تخزين الطاقة الحرارية بالآبار","Borehole thermal energy storage uses deep wells as heat reservoirs.","يستخدم تخزين الطاقة الحرارية بالآبار آباراً عميقة كخزانات حرارية.","mastery","C1","AWL"],
["aquifer thermal energy storage","noun phrase","تخزين الطاقة الحرارية بالخزانات الجوفية","Aquifer thermal energy storage injects warm water underground.","يحقن تخزين الطاقة الحرارية بالخزانات الجوفية مياهاً دافئة تحت الأرض.","mastery","C1","AWL"],
["pit thermal energy storage","noun phrase","تخزين الطاقة الحرارية بالحفر","Pit thermal energy storage fills large insulated pits with hot water.","يملأ تخزين الطاقة الحرارية بالحفر حفراً كبيرة معزولة بالماء الساخن.","mastery","C1","AWL"],
["tank thermal energy storage","noun phrase","تخزين الطاقة الحرارية بالخزانات","Tank thermal energy storage uses insulated steel or concrete tanks.","يستخدم تخزين الطاقة الحرارية بالخزانات خزانات فولاذية أو خرسانية معزولة.","mastery","C1","AWL"],
["solar district heating","noun phrase","تدفئة منطقية شمسية","Solar district heating serves entire neighborhoods with solar thermal energy.","تخدم التدفئة المنطقية الشمسية أحياءً بأكملها بالطاقة الشمسية الحرارية.","extended","B2","COCA"],
["fifth generation district heating","noun phrase","تدفئة منطقية من الجيل الخامس","Fifth generation district heating operates at near-ambient temperatures.","تعمل التدفئة المنطقية من الجيل الخامس عند درجات حرارة قريبة من المحيطة.","mastery","C1","AWL"],
["ambient loop system","noun phrase","نظام الحلقة المحيطة","An ambient loop system exchanges heat bidirectionally between buildings.","يتبادل نظام الحلقة المحيطة الحرارة ثنائي الاتجاه بين المباني.","mastery","C1","AWL"],
["bidirectional network","noun phrase","شبكة ثنائية الاتجاه","A bidirectional network allows buildings to share excess heat.","تسمح الشبكة ثنائية الاتجاه للمباني بمشاركة الحرارة الزائدة.","extended","B2","COCA"],
["prosumer building","noun phrase","مبنى منتج مستهلك","A prosumer building both generates and consumes energy.","ينتج المبنى المنتج المستهلك الطاقة ويستهلكها في آن واحد.","mastery","C1","COCA"],
["energy community","noun phrase","مجتمع طاقوي","An energy community collectively manages local energy resources.","يدير المجتمع الطاقوي الموارد الطاقوية المحلية بشكل جماعي.","extended","B2","COCA"],
["peer-to-peer energy trading","noun phrase","تداول الطاقة من نظير إلى نظير","Peer-to-peer energy trading lets neighbors buy and sell electricity directly.","يتيح تداول الطاقة من نظير إلى نظير للجيران شراء وبيع الكهرباء مباشرة.","mastery","C1","AWL"]
];

const u12 = [
["habitable zone calculator","noun phrase","حاسبة المنطقة الصالحة للسكن","A habitable zone calculator estimates stellar liquid water boundaries.","تُقدّر حاسبة المنطقة الصالحة للسكن حدود الماء السائل النجمية.","mastery","C1","COCA"],
["kopparapu limits","noun phrase","حدود كوبارابو","Kopparapu limits refine habitable zone boundaries with updated climate models.","تُحسّن حدود كوبارابو حدود المنطقة الصالحة للسكن بنماذج مناخية محدثة.","mastery","C1","AWL"],
["conservative habitable zone","noun phrase","المنطقة الصالحة للسكن المحافظة","The conservative habitable zone uses stringent climate thresholds.","تستخدم المنطقة الصالحة للسكن المحافظة عتبات مناخية صارمة.","mastery","C1","AWL"],
["optimistic habitable zone","noun phrase","المنطقة الصالحة للسكن المتفائلة","The optimistic habitable zone extends boundaries based on empirical limits.","توسع المنطقة الصالحة للسكن المتفائلة الحدود بناءً على حدود تجريبية.","mastery","C1","AWL"],
["recent Venus limit","noun phrase","حد الزهرة الحديث","The recent Venus limit marks the inner edge of the empirical zone.","يحدد حد الزهرة الحديث الحافة الداخلية للمنطقة التجريبية.","mastery","C1","AWL"],
["runaway greenhouse limit","noun phrase","حد الاحتباس الحراري الجامح","The runaway greenhouse limit defines where oceans would completely evaporate.","يحدد حد الاحتباس الحراري الجامح أين ستتبخر المحيطات بالكامل.","mastery","C1","COCA"],
["maximum greenhouse limit","noun phrase","حد الاحتباس الحراري الأقصى","The maximum greenhouse limit sets the outer edge of the habitable zone.","يحدد حد الاحتباس الحراري الأقصى الحافة الخارجية للمنطقة الصالحة للسكن.","mastery","C1","AWL"],
["early Mars limit","noun phrase","حد المريخ المبكر","The early Mars limit suggests Mars was once within the habitable zone.","يشير حد المريخ المبكر إلى أن المريخ كان يوماً ضمن المنطقة الصالحة للسكن.","mastery","C1","AWL"],
["empirical habitable zone","noun phrase","المنطقة الصالحة للسكن التجريبية","The empirical habitable zone uses Venus and Mars as boundary markers.","تستخدم المنطقة الصالحة للسكن التجريبية الزهرة والمريخ كعلامات حدودية.","extended","B2","COCA"],
["spectral habitable zone","noun phrase","المنطقة الصالحة للسكن الطيفية","The spectral habitable zone varies with host star spectral type.","تتغير المنطقة الصالحة للسكن الطيفية مع النوع الطيفي للنجم المضيف.","mastery","C1","AWL"],
["tidal habitable zone","noun phrase","المنطقة الصالحة للسكن المدية","The tidal habitable zone considers tidal heating effects on habitability.","تأخذ المنطقة الصالحة للسكن المدية في الاعتبار تأثيرات التسخين المدي على السكنى.","mastery","C1","AWL"],
["eccentric habitable zone","noun phrase","المنطقة الصالحة للسكن الإهليلجية","An eccentric habitable zone accounts for non-circular planetary orbits.","تراعي المنطقة الصالحة للسكن الإهليلجية المدارات الكوكبية غير الدائرية.","mastery","C1","AWL"],
["binary habitable zone","noun phrase","المنطقة الصالحة للسكن الثنائية","A binary habitable zone maps livable regions around two-star systems.","ترسم المنطقة الصالحة للسكن الثنائية المناطق الصالحة للعيش حول نظم النجمين.","mastery","C1","AWL"],
["circumstellar habitable zone","noun phrase","المنطقة الصالحة للسكن حول النجم","The circumstellar habitable zone is the classic definition of the Goldilocks region.","المنطقة الصالحة للسكن حول النجم هي التعريف الكلاسيكي لمنطقة غولديلوكس.","extended","B2","COCA"],
["circumplanetary habitable zone","noun phrase","المنطقة الصالحة للسكن حول الكوكب","A circumplanetary habitable zone could exist around gas giant moons.","يمكن أن توجد منطقة صالحة للسكن حول الكوكب حول أقمار العمالقة الغازية.","mastery","C1","AWL"],
["galactic habitable zone","noun phrase","المنطقة الصالحة للسكن المجرية","The galactic habitable zone excludes the dangerous galactic center.","تستبعد المنطقة الصالحة للسكن المجرية مركز المجرة الخطير.","extended","B2","COCA"],
["continuously habitable zone","noun phrase","المنطقة الصالحة للسكن المستمرة","The continuously habitable zone remains livable over billions of years.","تبقى المنطقة الصالحة للسكن المستمرة صالحة للحياة على مدار مليارات السنين.","mastery","C1","AWL"],
["habitable zone lifetime","noun phrase","عمر المنطقة الصالحة للسكن","The habitable zone lifetime determines how long life can develop.","يحدد عمر المنطقة الصالحة للسكن المدة التي يمكن فيها للحياة أن تتطور.","mastery","C1","AWL"],
["water loss limit","noun phrase","حد فقدان الماء","The water loss limit marks where a planet's water escapes to space.","يحدد حد فقدان الماء أين يتسرب ماء الكوكب إلى الفضاء.","extended","B2","COCA"],
["hydrogen greenhouse","noun phrase","الاحتباس الهيدروجيني","A hydrogen greenhouse could warm planets beyond the traditional habitable zone.","يمكن للاحتباس الهيدروجيني تدفئة كواكب خارج المنطقة الصالحة للسكن التقليدية.","mastery","C1","AWL"],
["volcanic hydrogen","noun phrase","الهيدروجين البركاني","Volcanic hydrogen outgassing could maintain surface warmth on distant planets.","يمكن لانبعاث الهيدروجين البركاني الحفاظ على دفء السطح على كواكب بعيدة.","mastery","C1","COCA"],
["outgassing rate","noun phrase","معدل الانبعاث الغازي","The outgassing rate determines atmospheric composition over time.","يحدد معدل الانبعاث الغازي التركيب الجوي عبر الزمن.","extended","B2","COCA"],
["magma ocean","noun phrase","محيط الصهارة","A magma ocean covers the surface of newly formed rocky planets.","يغطي محيط الصهارة سطح الكواكب الصخرية المتشكلة حديثاً.","extended","B2","COCA"],
["steam atmosphere","noun phrase","غلاف جوي بخاري","A steam atmosphere results from complete ocean evaporation.","ينتج الغلاف الجوي البخاري عن التبخر الكامل للمحيط.","extended","B2","COCA"],
["desiccated planet","noun phrase","كوكب مجفف","A desiccated planet has lost all its surface water permanently.","فقد الكوكب المجفف كل مياهه السطحية بشكل دائم.","mastery","C1","AWL"],
["ocean planet","noun phrase","كوكب محيطي","An ocean planet is entirely covered by a global water layer.","الكوكب المحيطي مغطى بالكامل بطبقة مائية عالمية.","extended","B2","COCA"],
["water world","noun phrase","عالم مائي","A water world may lack exposed land for silicate weathering cycles.","قد يفتقر العالم المائي إلى أرض مكشوفة لدورات تجوية السيليكات.","extended","B2","COCA"],
["hycean planet","noun phrase","كوكب هايسي","A hycean planet has a hydrogen atmosphere over a global ocean.","يمتلك الكوكب الهايسي غلافاً جوياً هيدروجينياً فوق محيط عالمي.","mastery","C1","AWL"],
["super-Earth","noun phrase","أرض فائقة","A super-Earth has a mass between one and ten Earth masses.","تمتلك الأرض الفائقة كتلة بين واحد وعشر كتل أرضية.","extended","B2","COCA"],
["mini-Neptune","noun phrase","نبتون مصغر","A mini-Neptune has a thick gaseous envelope around a rocky core.","يمتلك نبتون المصغر غلافاً غازياً سميكاً حول نواة صخرية.","extended","B2","COCA"],
["sub-Neptune","noun phrase","دون نبتون","A sub-Neptune occupies the size gap between Earth and Neptune.","يشغل دون نبتون فجوة الحجم بين الأرض ونبتون.","extended","B2","COCA"],
["mega-Earth","noun phrase","أرض عملاقة","A mega-Earth is a massive rocky planet exceeding ten Earth masses.","الأرض العملاقة كوكب صخري ضخم يتجاوز عشر كتل أرضية.","mastery","C1","AWL"],
["super-puff","noun phrase","المنتفخ الفائق","A super-puff has extremely low density for its size.","يمتلك المنتفخ الفائق كثافة منخفضة للغاية بالنسبة لحجمه.","mastery","C1","COCA"],
["ultra-hot Jupiter","noun phrase","مشتري فائق الحرارة","An ultra-hot Jupiter has dayside temperatures exceeding 2000 Kelvin.","تتجاوز درجات حرارة الجانب النهاري للمشتري فائق الحرارة 2000 كلفن.","extended","B2","COCA"],
["warm Neptune","noun phrase","نبتون دافئ","A warm Neptune orbits closer than our Neptune but farther than hot Jupiters.","يدور نبتون الدافئ أقرب من نبتون لدينا لكن أبعد من المشتريات الحارة.","extended","B2","COCA"]
];

async function main() {
  const client = await pool.connect();
  try {
    const units = [
      { num: 1, data: u1 },
      { num: 2, data: u2 },
      { num: 3, data: u3 },
      { num: 4, data: u4 },
      { num: 5, data: u5 },
      { num: 6, data: u6 },
      { num: 7, data: u7 },
      { num: 8, data: u8 },
      { num: 9, data: u9 },
      { num: 10, data: u10 },
      { num: 11, data: u11 },
      { num: 12, data: u12 }
    ];

    let totalInserted = 0;
    for (const u of units) {
      const count = await insertBatch(client, u.data, u.num, BATCH_ID);
      console.log(`Unit ${u.num}: ${count} words inserted (${u.data.length} provided)`);
      totalInserted += count;
    }
    console.log(`\nTotal inserted: ${totalInserted}`);

    // Query final totals
    console.log('\n--- Final DB Totals ---');
    for (const u of units) {
      const res = await client.query(
        `SELECT COUNT(*) as cnt FROM public.vocab_staging_l4 WHERE batch_id=$1 AND recommended_unit=$2`,
        [BATCH_ID, u.num]
      );
      console.log(`Unit ${u.num}: ${res.rows[0].cnt} rows`);
    }
    const totalRes = await client.query(
      `SELECT COUNT(*) as cnt FROM public.vocab_staging_l4 WHERE batch_id=$1`,
      [BATCH_ID]
    );
    console.log(`Overall batch ${BATCH_ID}: ${totalRes.rows[0].cnt} rows`);
  } finally {
    client.release();
    await pool.end();
  }
}

main().catch(e => { console.error(e); process.exit(1); });
