const { Pool } = require('pg');
const pool = new Pool({ host: 'aws-1-eu-central-1.pooler.supabase.com', port: 5432, database: 'postgres', user: 'postgres.nmjexpuycmqcxuxljier', password: 'Ali-al-ahmad2000', ssl: { rejectUnauthorized: false } });

async function insertBatch(client, words, unitNumber, batchId) {
  let inserted = 0;
  for (const w of words) {
    try {
      await client.query(
        `INSERT INTO public.vocab_staging_l4 (word, pos, definition_ar, example_en, example_ar, recommended_tier, cefr_level, source_list, recommended_unit, batch_id) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) ON CONFLICT (word) DO NOTHING`,
        [w[0], w[1], w[2], w[3], w[4], w[5], w[6], w[7], unitNumber, batchId]
      );
      inserted++;
    } catch(e) { console.error(`Error "${w[0]}":`, e.message); }
  }
  return inserted;
}

const BATCH_ID = 28;

// ========== UNIT 3: Food Security (30 words) ==========
const u3 = [
  ["agroecology","noun","علم الزراعة البيئية","Agroecology integrates ecological principles into farming systems.","يدمج علم الزراعة البيئية المبادئ البيئية في النظم الزراعية.","core","B2","COCA"],
  ["permaculture","noun","الزراعة المستدامة","Permaculture designs mimic natural ecosystems for food production.","تحاكي تصاميم الزراعة المستدامة النظم البيئية الطبيعية لإنتاج الغذاء.","core","B2","COCA"],
  ["food desert","noun","صحراء غذائية","Many urban areas are classified as food deserts due to lack of grocery stores.","تُصنَّف كثير من المناطق الحضرية كصحارى غذائية بسبب نقص المتاجر.","core","B2","COCA"],
  ["food mile","noun","ميل غذائي","Reducing food miles lowers the carbon footprint of our diet.","يقلل تقليص الأميال الغذائية من البصمة الكربونية لغذائنا.","extended","B2","COCA"],
  ["locavore","noun","آكل محلي","A locavore prefers food grown within a hundred-mile radius.","يفضل الآكل المحلي الطعام المزروع ضمن دائرة نصف قطرها مئة ميل.","mastery","C1","COCA"],
  ["agribusiness","noun","أعمال زراعية تجارية","Large agribusinesses dominate global grain markets.","تهيمن الشركات الزراعية الكبرى على أسواق الحبوب العالمية.","core","B2","AWL"],
  ["agronomist","noun","مهندس زراعي","The agronomist recommended drought-resistant crop varieties.","أوصى المهندس الزراعي بأصناف محاصيل مقاومة للجفاف.","extended","C1","COCA"],
  ["horticulturist","noun","متخصص في البستنة","The horticulturist grafted two apple tree varieties together.","قام المتخصص في البستنة بتطعيم صنفين من أشجار التفاح معاً.","extended","C1","COCA"],
  ["entomophagy","noun","أكل الحشرات","Entomophagy is promoted as a sustainable protein source.","يُروَّج لأكل الحشرات كمصدر مستدام للبروتين.","mastery","C1","COCA"],
  ["aquaculture pond","noun","بركة استزراع مائي","The aquaculture pond yields two tons of tilapia per cycle.","تنتج بركة الاستزراع المائي طنين من البلطي لكل دورة.","extended","B2","COCA"],
  ["prawn hatchery","noun","مفرخة قريدس","The prawn hatchery supplies larvae to coastal farms.","تزود مفرخة القريدس المزارع الساحلية باليرقات.","mastery","C1","COCA"],
  ["seaweed farm","noun","مزرعة أعشاب بحرية","The seaweed farm stretches across five hectares of shallow water.","تمتد مزرعة الأعشاب البحرية عبر خمسة هكتارات من المياه الضحلة.","extended","B2","COCA"],
  ["mushroom substrate","noun","ركيزة زراعة الفطر","Straw is the most common mushroom substrate for oyster varieties.","القش هو الركيزة الأكثر شيوعاً لزراعة فطر المحار.","mastery","C1","COCA"],
  ["vermiculture","noun","زراعة الديدان","Vermiculture converts organic waste into nutrient-rich compost.","تحوّل زراعة الديدان النفايات العضوية إلى سماد غني بالمغذيات.","extended","C1","COCA"],
  ["earthworm casting","noun","مسبوكات دودة الأرض","Earthworm castings improve soil structure and water retention.","تحسّن مسبوكات دودة الأرض بنية التربة واحتباس الماء.","mastery","C1","COCA"],
  ["humus","noun","دبال","Humus is the dark organic matter that enriches fertile soil.","الدبال هو المادة العضوية الداكنة التي تُغني التربة الخصبة.","core","B2","COCA"],
  ["topsoil depletion","noun","استنزاف التربة السطحية","Topsoil depletion threatens long-term agricultural productivity.","يهدد استنزاف التربة السطحية الإنتاجية الزراعية طويلة الأمد.","core","B2","AWL"],
  ["subsoil compaction","noun","انضغاط التربة التحتية","Heavy machinery causes subsoil compaction that restricts root growth.","تسبب الآلات الثقيلة انضغاط التربة التحتية مما يقيّد نمو الجذور.","extended","C1","COCA"],
  ["waterlogging","noun","تشبع التربة بالماء","Waterlogging after heavy rains destroyed the wheat crop.","أدى تشبع التربة بالماء بعد الأمطار الغزيرة إلى تدمير محصول القمح.","core","B2","COCA"],
  ["salinity intrusion","noun","تسرب الملوحة","Salinity intrusion contaminates freshwater aquifers in coastal regions.","يلوث تسرب الملوحة طبقات المياه الجوفية العذبة في المناطق الساحلية.","extended","C1","COCA"],
  ["deficit irrigation","noun","ري ناقص","Deficit irrigation saves water while maintaining acceptable crop yields.","يوفر الري الناقص الماء مع الحفاظ على غلة محاصيل مقبولة.","extended","C1","AWL"],
  ["supplemental irrigation","noun","ري تكميلي","Supplemental irrigation bridges the gap during dry spells.","يسد الري التكميلي الفجوة خلال فترات الجفاف.","core","B2","COCA"],
  ["drip line","noun","خط تنقيط","Each drip line delivers water directly to the plant root zone.","يوصل كل خط تنقيط الماء مباشرة إلى منطقة جذور النبات.","core","B2","COCA"],
  ["sprinkler head","noun","رأس رشاش","A damaged sprinkler head caused uneven water distribution.","تسبب رأس الرشاش التالف في توزيع غير متساوٍ للمياه.","core","B1","COCA"],
  ["center pivot","noun","ري محوري مركزي","Center pivot systems irrigate circular fields visible from satellites.","تروي أنظمة الري المحوري المركزي حقولاً دائرية مرئية من الأقمار الصناعية.","extended","B2","COCA"],
  ["furrow irrigation","noun","ري بالأخاديد","Furrow irrigation channels water along parallel trenches between crop rows.","يوجه الري بالأخاديد الماء عبر خنادق متوازية بين صفوف المحاصيل.","core","B2","COCA"],
  ["raised bed","noun","حوض مرتفع","Raised beds warm up faster in spring and improve drainage.","تسخن الأحواض المرتفعة أسرع في الربيع وتحسن الصرف.","core","B1","COCA"],
  ["companion planting","noun","زراعة مرافقة","Companion planting pairs tomatoes with basil to repel pests.","تجمع الزراعة المرافقة الطماطم مع الريحان لطرد الآفات.","core","B2","COCA"],
  ["mycology","noun","علم الفطريات","Mycology research has revealed fungi networks that support tree health.","كشف بحث علم الفطريات عن شبكات فطرية تدعم صحة الأشجار.","extended","C1","COCA"],
  ["crop rotation","noun","دورة زراعية","Crop rotation prevents nutrient depletion and breaks pest cycles.","تمنع الدورة الزراعية استنزاف المغذيات وتكسر دورات الآفات.","core","B2","NAWL"]
];

// ========== UNIT 4: Biomimicry (25 words) ==========
const u4 = [
  ["biomimetic","adjective","محاكٍ للطبيعة","Biomimetic materials replicate the self-healing properties of bone.","تستنسخ المواد المحاكية للطبيعة خصائص العظام في الترميم الذاتي.","core","B2","COCA"],
  ["bioinspired","adjective","مستوحى من الطبيعة","Bioinspired robotics draws on insect locomotion patterns.","تستمد الروبوتات المستوحاة من الطبيعة أنماط حركة الحشرات.","core","B2","COCA"],
  ["echolocation","noun","تحديد الموقع بالصدى","Bats use echolocation to navigate and hunt in total darkness.","تستخدم الخفافيش تحديد الموقع بالصدى للتنقل والصيد في الظلام التام.","core","B2","COCA"],
  ["thermoregulation","noun","تنظيم حراري","Elephants rely on their large ears for thermoregulation.","تعتمد الفيلة على آذانها الكبيرة في التنظيم الحراري.","extended","C1","COCA"],
  ["bioluminescence","noun","إضاءة حيوية","Deep-sea creatures use bioluminescence to attract prey.","تستخدم كائنات أعماق البحر الإضاءة الحيوية لجذب الفرائس.","core","B2","COCA"],
  ["electroreception","noun","استقبال كهربائي","Sharks possess electroreception to detect prey hidden in sand.","تمتلك أسماك القرش استقبالاً كهربائياً لكشف الفرائس المختبئة في الرمال.","mastery","C1","COCA"],
  ["magnetoreception","noun","استقبال مغناطيسي","Magnetoreception enables migratory birds to sense Earth's magnetic field.","يمكّن الاستقبال المغناطيسي الطيور المهاجرة من استشعار المجال المغناطيسي للأرض.","mastery","C1","COCA"],
  ["proprioception","noun","حس استقبال ذاتي","Proprioception allows us to touch our nose with our eyes closed.","يسمح لنا الحس الاستقبالي الذاتي بلمس أنفنا وعيوننا مغلقة.","extended","C1","COCA"],
  ["mechanoreceptor","noun","مستقبل ميكانيكي","Mechanoreceptors in spider legs detect the slightest vibration.","تكشف المستقبلات الميكانيكية في أرجل العنكبوت أدنى اهتزاز.","mastery","C1","COCA"],
  ["compound eye","noun","عين مركبة","A dragonfly's compound eye contains up to thirty thousand lenses.","تحتوي عين اليعسوب المركبة على ما يصل إلى ثلاثين ألف عدسة.","core","B2","COCA"],
  ["iridescence","noun","تقزح لوني","The iridescence of a peacock feather inspired new display technology.","ألهم التقزح اللوني لريشة الطاووس تقنيات عرض جديدة.","extended","C1","COCA"],
  ["structural color","noun","لون بنيوي","Structural color arises from light interacting with nanoscale patterns.","ينشأ اللون البنيوي من تفاعل الضوء مع أنماط نانوية.","extended","B2","COCA"],
  ["photonic crystal","noun","بلورة فوتونية","Photonic crystals in butterfly wings produce vivid blue hues.","تنتج البلورات الفوتونية في أجنحة الفراشات ألواناً زرقاء زاهية.","mastery","C1","COCA"],
  ["thin-film interference","noun","تداخل الأغشية الرقيقة","Thin-film interference creates rainbow patterns on soap bubbles.","يُنشئ تداخل الأغشية الرقيقة أنماطاً قوس قزحية على فقاعات الصابون.","mastery","C1","COCA"],
  ["anti-reflective coating","noun","طلاء مضاد للانعكاس","Moth-eye nanostructures inspired modern anti-reflective coatings on lenses.","ألهمت بنى عين العثة النانوية الطلاءات الحديثة المضادة للانعكاس.","extended","B2","COCA"],
  ["superhydrophobic","adjective","فائق الكراهية للماء","Superhydrophobic surfaces cause water droplets to roll off instantly.","تتسبب الأسطح فائقة الكراهية للماء في تدحرج قطرات الماء فوراً.","extended","C1","COCA"],
  ["directional adhesion","noun","التصاق اتجاهي","Gecko feet achieve directional adhesion through millions of tiny setae.","تحقق أقدام الوزغة التصاقاً اتجاهياً عبر ملايين الشعيرات الدقيقة.","mastery","C1","COCA"],
  ["shape memory alloy","noun","سبيكة ذاكرة الشكل","Shape memory alloys return to their original form when heated.","تعود سبائك ذاكرة الشكل إلى شكلها الأصلي عند تسخينها.","extended","C1","COCA"],
  ["self-healing polymer","noun","بوليمر ذاتي الترميم","Self-healing polymers can repair micro-cracks without human intervention.","يمكن للبوليمرات ذاتية الترميم إصلاح الشقوق الدقيقة دون تدخل بشري.","extended","C1","COCA"],
  ["gecko adhesion","noun","التصاق الوزغة","Gecko adhesion relies on van der Waals forces at the nanoscale.","يعتمد التصاق الوزغة على قوى فان دير فالس على المستوى النانوي.","core","B2","COCA"],
  ["lotus effect","noun","تأثير اللوتس","The lotus effect describes how micro-bumps repel water and dirt.","يصف تأثير اللوتس كيف تطرد النتوءات الدقيقة الماء والأوساخ.","core","B2","COCA"],
  ["sharkskin riblet","noun","حزوز جلد القرش","Sharkskin riblets reduce drag on aircraft fuselage surfaces.","تقلل حزوز جلد القرش المقاومة على أسطح هياكل الطائرات.","mastery","C1","COCA"],
  ["kingfisher beak","noun","منقار صائد السمك","The kingfisher beak shape inspired the front of the Shinkansen bullet train.","ألهم شكل منقار صائد السمك مقدمة قطار شينكانسن فائق السرعة.","core","B2","COCA"],
  ["termite mound ventilation","noun","تهوية تل النمل الأبيض","Termite mound ventilation inspired passive cooling in the Eastgate Centre.","ألهمت تهوية تل النمل الأبيض التبريد السلبي في مركز إيستغيت.","core","B2","COCA"],
  ["self-cleaning surface","noun","سطح ذاتي التنظيف","Self-cleaning surfaces reduce maintenance costs on skyscraper windows.","تقلل الأسطح ذاتية التنظيف تكاليف صيانة نوافذ ناطحات السحاب.","core","B2","COCA"]
];

// ========== UNIT 5: Migration (30 words) ==========
const u5 = [
  ["transmigration","noun","هجرة عبر الحدود","Government-sponsored transmigration relocated millions to less populated islands.","نقلت الهجرة عبر الحدود برعاية حكومية الملايين إلى جزر أقل سكاناً.","extended","C1","COCA"],
  ["circular mobility","noun","تنقل دائري","Circular mobility allows workers to return home between seasonal contracts.","يسمح التنقل الدائري للعمال بالعودة إلى ديارهم بين العقود الموسمية.","extended","C1","AWL"],
  ["frontier worker","noun","عامل حدودي","A frontier worker crosses the border daily for employment.","يعبر العامل الحدودي الحدود يومياً من أجل العمل.","core","B2","COCA"],
  ["cross-border trader","noun","تاجر عابر للحدود","Cross-border traders move goods between neighboring markets informally.","ينقل التجار العابرون للحدود البضائع بين الأسواق المتجاورة بشكل غير رسمي.","core","B2","COCA"],
  ["debt bondage","noun","عبودية الدين","Debt bondage traps migrant workers in exploitative conditions.","تحاصر عبودية الدين العمال المهاجرين في ظروف استغلالية.","core","B2","COCA"],
  ["kafala system","noun","نظام الكفالة","The kafala system ties a worker's legal status to a single employer.","يربط نظام الكفالة الوضع القانوني للعامل بصاحب عمل واحد.","core","B2","COCA"],
  ["exit permit","noun","إذن خروج","Some countries require an exit permit before nationals can travel abroad.","تشترط بعض الدول إذن خروج قبل أن يسافر المواطنون إلى الخارج.","core","B2","COCA"],
  ["biometric passport","noun","جواز سفر بيومتري","A biometric passport stores fingerprint and facial data on a chip.","يخزن جواز السفر البيومتري بيانات البصمة والوجه على شريحة.","core","B2","COCA"],
  ["visa waiver","noun","إعفاء من التأشيرة","The visa waiver program allows short visits without a formal visa.","يسمح برنامج الإعفاء من التأشيرة بزيارات قصيرة دون تأشيرة رسمية.","core","B1","COCA"],
  ["bilateral agreement","noun","اتفاقية ثنائية","A bilateral agreement governs labor migration between the two nations.","تحكم اتفاقية ثنائية هجرة العمالة بين الدولتين.","core","B2","AWL"],
  ["readmission agreement","noun","اتفاقية إعادة القبول","The readmission agreement obliges both states to accept returned nationals.","تُلزم اتفاقية إعادة القبول كلتا الدولتين بقبول المواطنين المعادين.","extended","C1","COCA"],
  ["voluntary return","noun","عودة طوعية","Voluntary return programs offer travel assistance and reintegration support.","تقدم برامج العودة الطوعية مساعدة سفر ودعم إعادة الاندماج.","core","B2","COCA"],
  ["removal order","noun","أمر ترحيل","The court issued a removal order after the asylum claim was denied.","أصدرت المحكمة أمر ترحيل بعد رفض طلب اللجوء.","extended","B2","COCA"],
  ["deportation flight","noun","رحلة ترحيل","Activists protested the deportation flight at the airport terminal.","احتج ناشطون على رحلة الترحيل في صالة المطار.","extended","B2","COCA"],
  ["immigration detention","noun","احتجاز هجرة","Immigration detention centres hold individuals pending status determination.","تحتجز مراكز احتجاز الهجرة أفراداً بانتظار تحديد وضعهم.","core","B2","COCA"],
  ["asylum interview","noun","مقابلة لجوء","The asylum interview assesses the credibility of the applicant's claim.","تقيّم مقابلة اللجوء مصداقية ادعاء مقدم الطلب.","core","B2","COCA"],
  ["credibility assessment","noun","تقييم المصداقية","Credibility assessment is the most contested part of refugee determination.","يُعد تقييم المصداقية الجزء الأكثر إثارة للجدل في تحديد صفة اللاجئ.","extended","C1","AWL"],
  ["country of origin information","noun","معلومات بلد المنشأ","Adjudicators consult country of origin information to verify claims.","يستشير المحكّمون معلومات بلد المنشأ للتحقق من الادعاءات.","extended","C1","COCA"],
  ["push factor","noun","عامل طرد","War and famine are common push factors driving emigration.","الحرب والمجاعة عوامل طرد شائعة تدفع إلى الهجرة.","core","B1","COCA"],
  ["pull factor","noun","عامل جذب","Higher wages act as a powerful pull factor for migrants.","تعمل الأجور المرتفعة كعامل جذب قوي للمهاجرين.","core","B1","COCA"],
  ["intervening obstacle","noun","عائق وسيط","Deserts and seas serve as intervening obstacles in migration routes.","تعمل الصحارى والبحار كعوائق وسيطة في طرق الهجرة.","extended","B2","COCA"],
  ["step migration","noun","هجرة تدريجية","Step migration describes the move from village to town to city.","تصف الهجرة التدريجية الانتقال من القرية إلى البلدة إلى المدينة.","extended","B2","COCA"],
  ["transit migration","noun","هجرة عبور","Transit migration through Libya often involves dangerous desert crossings.","تتضمن هجرة العبور عبر ليبيا غالباً عبوراً صحراوياً خطيراً.","extended","C1","COCA"],
  ["climate refugee","noun","لاجئ مناخي","Rising sea levels may create millions of climate refugees.","قد يخلق ارتفاع مستوى البحر ملايين اللاجئين المناخيين.","core","B2","COCA"],
  ["environmental migrant","noun","مهاجر بيئي","Environmental migrants flee drought, floods, and land degradation.","يفر المهاجرون البيئيون من الجفاف والفيضانات وتدهور الأراضي.","core","B2","COCA"],
  ["seasonal worker","noun","عامل موسمي","Seasonal workers harvest fruit during the summer months.","يحصد العمال الموسميون الفاكهة خلال أشهر الصيف.","core","B1","NAWL"],
  ["guest worker program","noun","برنامج العمالة الوافدة","The guest worker program recruits nurses from developing countries.","يستقطب برنامج العمالة الوافدة ممرضين من الدول النامية.","core","B2","COCA"],
  ["smuggling network","noun","شبكة تهريب","The police dismantled a smuggling network operating across three borders.","فككت الشرطة شبكة تهريب تعمل عبر ثلاث حدود.","extended","B2","COCA"],
  ["trafficking victim","noun","ضحية اتجار بالبشر","Support services helped the trafficking victim rebuild her life.","ساعدت خدمات الدعم ضحية الاتجار بالبشر في إعادة بناء حياتها.","core","B2","COCA"],
  ["non-refoulement","noun","عدم الإعادة القسرية","The principle of non-refoulement prohibits returning refugees to danger.","يحظر مبدأ عدم الإعادة القسرية إعادة اللاجئين إلى الخطر.","extended","C1","COCA"]
];

// ========== UNIT 6: Cryptocurrency (65 words) ==========
const u6 = [
  ["tokenomics","noun","اقتصاد الرموز","Tokenomics determines the supply schedule and incentive structure of a coin.","يحدد اقتصاد الرموز جدول العرض وهيكل الحوافز للعملة.","core","B2","COCA"],
  ["interoperability","noun","قابلية التشغيل البيني","Interoperability allows different blockchains to exchange data seamlessly.","تتيح قابلية التشغيل البيني لسلاسل الكتل المختلفة تبادل البيانات بسلاسة.","core","B2","AWL"],
  ["custodian","noun","أمين حفظ","A regulated custodian stores digital assets on behalf of clients.","يحفظ أمين الحفظ المنظم الأصول الرقمية نيابة عن العملاء.","core","B2","COCA"],
  ["multisig wallet","noun","محفظة متعددة التوقيعات","A multisig wallet requires approval from multiple key holders.","تتطلب المحفظة متعددة التوقيعات موافقة من عدة حاملي مفاتيح.","extended","C1","COCA"],
  ["deflationary token","noun","رمز انكماشي","A deflationary token burns a portion of each transaction fee.","يحرق الرمز الانكماشي جزءاً من كل رسوم معاملة.","extended","C1","COCA"],
  ["whitelist","noun","قائمة بيضاء","Only addresses on the whitelist can participate in the presale.","فقط العناوين المدرجة في القائمة البيضاء يمكنها المشاركة في البيع المسبق.","core","B2","COCA"],
  ["slippage","noun","انزلاق سعري","High slippage occurs when a large order moves the market price.","يحدث الانزلاق السعري العالي عندما يحرك أمر كبير سعر السوق.","extended","B2","COCA"],
  ["arbitrageur","noun","مراجح","An arbitrageur profits from price differences across exchanges.","يربح المراجح من فروق الأسعار بين البورصات.","extended","C1","COCA"],
  ["whale","noun","حوت (مستثمر كبير)","A single whale moved ten thousand bitcoin to a cold wallet.","نقل حوت واحد عشرة آلاف بيتكوين إلى محفظة باردة.","core","B1","COCA"],
  ["order book","noun","سجل الأوامر","The order book displays all pending buy and sell orders.","يعرض سجل الأوامر جميع أوامر الشراء والبيع المعلقة.","core","B2","COCA"],
  ["candlestick chart","noun","مخطط الشموع","Each candlestick chart bar shows open, high, low, and close prices.","يُظهر كل عمود في مخطط الشموع أسعار الافتتاح والأعلى والأدنى والإغلاق.","core","B2","COCA"],
  ["staking reward","noun","مكافأة التخزين","Staking rewards compensate validators for securing the network.","تعوض مكافآت التخزين المدققين عن تأمين الشبكة.","core","B2","COCA"],
  ["validator node","noun","عقدة تحقق","Each validator node verifies transactions and proposes new blocks.","تتحقق كل عقدة تحقق من المعاملات وتقترح كتلاً جديدة.","extended","C1","COCA"],
  ["gas limit","noun","حد الغاز","Setting the gas limit too low causes a transaction to fail.","يؤدي تعيين حد الغاز المنخفض جداً إلى فشل المعاملة.","extended","B2","COCA"],
  ["block height","noun","ارتفاع الكتلة","Block height indicates the number of blocks mined since genesis.","يشير ارتفاع الكتلة إلى عدد الكتل المعدنة منذ كتلة البداية.","extended","C1","COCA"],
  ["epoch","noun","حقبة (في سلسلة الكتل)","The network adjusts difficulty at the end of each epoch.","تعدل الشبكة الصعوبة في نهاية كل حقبة.","extended","B2","COCA"],
  ["attestation","noun","تصديق","Validators submit an attestation to confirm the latest block is valid.","يقدم المدققون تصديقاً لتأكيد صحة أحدث كتلة.","extended","C1","AWL"],
  ["delegator","noun","مفوِّض","A delegator stakes tokens through a chosen validator.","يخزن المفوِّض الرموز عبر مدقق مختار.","extended","C1","COCA"],
  ["overcollateralized loan","noun","قرض مفرط الضمان","An overcollateralized loan requires depositing more value than borrowed.","يتطلب القرض مفرط الضمان إيداع قيمة أكبر مما يتم اقتراضه.","extended","C1","COCA"],
  ["liquidation threshold","noun","عتبة التصفية","When collateral drops below the liquidation threshold, the position is closed.","عندما ينخفض الضمان دون عتبة التصفية يُغلق المركز.","extended","C1","COCA"],
  ["composability","noun","قابلية التركيب","Composability lets developers combine DeFi protocols like building blocks.","تتيح قابلية التركيب للمطورين الجمع بين بروتوكولات التمويل اللامركزي كلبنات بناء.","mastery","C1","COCA"],
  ["programmable money","noun","نقود قابلة للبرمجة","Smart contracts enable programmable money that executes rules automatically.","تمكّن العقود الذكية النقود القابلة للبرمجة التي تنفذ القواعد تلقائياً.","core","B2","COCA"],
  ["censorship-resistant","adjective","مقاوم للرقابة","Bitcoin is designed to be censorship-resistant and borderless.","صُمم البيتكوين ليكون مقاوماً للرقابة وعابراً للحدود.","core","B2","COCA"],
  ["self-custodial wallet","noun","محفظة ذاتية الحفظ","A self-custodial wallet gives users full control over their private keys.","تمنح المحفظة ذاتية الحفظ المستخدمين سيطرة كاملة على مفاتيحهم الخاصة.","extended","C1","COCA"],
  ["cold storage","noun","تخزين بارد","Exchanges keep most funds in cold storage for security.","تحتفظ البورصات بمعظم الأموال في تخزين بارد للأمان.","core","B2","COCA"],
  ["hot wallet","noun","محفظة ساخنة","A hot wallet stays connected to the internet for quick trades.","تبقى المحفظة الساخنة متصلة بالإنترنت لإجراء صفقات سريعة.","core","B2","COCA"],
  ["hardware wallet","noun","محفظة أجهزة","A hardware wallet stores private keys on a secure offline device.","تخزن محفظة الأجهزة المفاتيح الخاصة على جهاز آمن غير متصل.","core","B2","COCA"],
  ["seed phrase","noun","عبارة الاسترداد","Never share your seed phrase with anyone to protect your funds.","لا تشارك عبارة الاسترداد أبداً مع أي شخص لحماية أموالك.","core","B1","COCA"],
  ["mnemonic","noun","فن الإستذكار","The twelve-word mnemonic generates all private keys in the wallet.","تولّد كلمات الاستذكار الاثنتا عشرة جميع المفاتيح الخاصة في المحفظة.","extended","C1","COCA"],
  ["deterministic wallet","noun","محفظة حتمية","A deterministic wallet derives all keys from a single master seed.","تشتق المحفظة الحتمية جميع المفاتيح من بذرة رئيسية واحدة.","mastery","C1","COCA"],
  ["signing key","noun","مفتاح التوقيع","The signing key authorizes transactions without exposing the master key.","يصرح مفتاح التوقيع بالمعاملات دون كشف المفتاح الرئيسي.","extended","C1","COCA"],
  ["public ledger","noun","سجل عام","Every bitcoin transaction is recorded on a public ledger.","تُسجَّل كل معاملة بيتكوين في سجل عام.","core","B2","COCA"],
  ["immutable record","noun","سجل غير قابل للتغيير","Blockchain provides an immutable record of every transaction.","توفر سلسلة الكتل سجلاً غير قابل للتغيير لكل معاملة.","core","B2","COCA"],
  ["peer discovery","noun","اكتشاف الأقران","Peer discovery protocols help new nodes find others on the network.","تساعد بروتوكولات اكتشاف الأقران العقد الجديدة في العثور على غيرها.","mastery","C1","COCA"],
  ["gossip protocol","noun","بروتوكول النميمة","A gossip protocol spreads transaction data across all network nodes.","ينشر بروتوكول النميمة بيانات المعاملات عبر جميع عقد الشبكة.","mastery","C1","COCA"],
  ["transaction throughput","noun","إنتاجية المعاملات","High transaction throughput is essential for mainstream payment adoption.","تعد إنتاجية المعاملات العالية ضرورية لاعتماد المدفوعات على نطاق واسع.","extended","C1","AWL"],
  ["finality","noun","نهائية المعاملة","Proof-of-stake chains achieve finality within a few seconds.","تحقق سلاسل إثبات الحصة نهائية المعاملة في ثوانٍ قليلة.","extended","C1","COCA"],
  ["liveness guarantee","noun","ضمان الحيوية","A liveness guarantee ensures the network keeps processing transactions.","يضمن ضمان الحيوية استمرار الشبكة في معالجة المعاملات.","mastery","C1","COCA"],
  ["economic security","noun","أمن اقتصادي","Economic security in proof-of-stake grows with the value of staked tokens.","ينمو الأمن الاقتصادي في إثبات الحصة مع قيمة الرموز المخزنة.","core","B2","AWL"],
  ["slashing penalty","noun","عقوبة القطع","A slashing penalty destroys part of a misbehaving validator's stake.","تدمر عقوبة القطع جزءاً من حصة المدقق المخالف.","extended","C1","COCA"],
  ["hash function","noun","دالة تجزئة","A hash function converts any input into a fixed-length output.","تحوّل دالة التجزئة أي مدخل إلى مخرج ثابت الطول.","core","B2","COCA"],
  ["merkle root","noun","جذر ميركل","The merkle root summarizes all transactions in a single block.","يلخص جذر ميركل جميع المعاملات في كتلة واحدة.","mastery","C1","COCA"],
  ["block header","noun","رأس الكتلة","The block header contains the hash, timestamp, and nonce.","يحتوي رأس الكتلة على التجزئة والطابع الزمني والرقم العشوائي.","extended","C1","COCA"],
  ["orphan block","noun","كتلة يتيمة","An orphan block is valid but not included in the main chain.","الكتلة اليتيمة صالحة لكنها غير مضمنة في السلسلة الرئيسية.","extended","C1","COCA"],
  ["ASIC miner","noun","معدِّن بدارات متكاملة","An ASIC miner outperforms general hardware in bitcoin mining.","يتفوق المعدِّن بالدارات المتكاملة على الأجهزة العامة في تعدين البيتكوين.","extended","C1","COCA"],
  ["GPU mining","noun","تعدين بالمعالج الرسومي","GPU mining is more flexible than ASIC mining for altcoins.","يعد التعدين بالمعالج الرسومي أكثر مرونة من تعدين الدارات المتكاملة للعملات البديلة.","extended","B2","COCA"],
  ["mining pool","noun","تجمع تعدين","A mining pool combines hash power from many participants.","يجمع تجمع التعدين قوة التجزئة من مشاركين كثيرين.","core","B2","COCA"],
  ["block explorer","noun","مستكشف الكتل","A block explorer lets anyone view transaction details on-chain.","يتيح مستكشف الكتل لأي شخص عرض تفاصيل المعاملات على السلسلة.","core","B2","COCA"],
  ["transaction hash","noun","تجزئة المعاملة","Paste the transaction hash into the explorer to track your transfer.","الصق تجزئة المعاملة في المستكشف لتتبع تحويلك.","core","B2","COCA"],
  ["gas price","noun","سعر الغاز","Users bid a higher gas price to prioritize their transactions.","يقدم المستخدمون سعر غاز أعلى لتحظى معاملاتهم بالأولوية.","core","B2","COCA"],
  ["bridge protocol","noun","بروتوكول الجسر","A bridge protocol transfers tokens between Ethereum and Polygon.","ينقل بروتوكول الجسر الرموز بين إيثريوم وبوليغون.","extended","C1","COCA"],
  ["wrapped asset","noun","أصل مغلف","A wrapped asset represents a foreign token on a host chain.","يمثل الأصل المغلف رمزاً أجنبياً على سلسلة مضيفة.","extended","C1","COCA"],
  ["yield aggregator","noun","مجمّع العائدات","A yield aggregator automatically moves funds to the highest-return pool.","ينقل مجمّع العائدات الأموال تلقائياً إلى التجمع الأعلى عائداً.","extended","C1","COCA"],
  ["liquidity provider","noun","مزود سيولة","A liquidity provider deposits token pairs into a decentralized pool.","يودع مزود السيولة أزواج الرموز في تجمع لامركزي.","core","B2","COCA"],
  ["automated market maker","noun","صانع سوق آلي","An automated market maker uses algorithms instead of order books.","يستخدم صانع السوق الآلي خوارزميات بدلاً من سجلات الأوامر.","extended","C1","COCA"],
  ["bonding curve","noun","منحنى الربط","The bonding curve sets the token price based on total supply.","يحدد منحنى الربط سعر الرمز بناءً على إجمالي العرض.","mastery","C1","COCA"],
  ["governance token","noun","رمز حوكمة","Governance token holders vote on protocol upgrades and fee changes.","يصوّت حاملو رموز الحوكمة على ترقيات البروتوكول وتغييرات الرسوم.","core","B2","COCA"],
  ["utility token","noun","رمز منفعة","A utility token grants access to a specific service on the platform.","يمنح رمز المنفعة حق الوصول إلى خدمة محددة على المنصة.","core","B2","COCA"],
  ["security token","noun","رمز أمان (ورقة مالية رقمية)","A security token represents ownership of a real-world asset.","يمثل رمز الأمان ملكية أصل حقيقي.","core","B2","COCA"],
  ["fintech","noun","تقنية مالية","Fintech startups are disrupting traditional banking services.","تعطّل شركات التقنية المالية الناشئة الخدمات المصرفية التقليدية.","core","B2","COCA"],
  ["bullish sentiment","noun","شعور تفاؤلي","Bullish sentiment drove bitcoin above fifty thousand dollars.","دفع الشعور التفاؤلي البيتكوين فوق خمسين ألف دولار.","core","B2","COCA"],
  ["bearish trend","noun","اتجاه هبوطي","A bearish trend persisted throughout the second quarter.","استمر الاتجاه الهبوطي طوال الربع الثاني.","core","B2","COCA"],
  ["collateral ratio","noun","نسبة الضمان","The protocol requires a collateral ratio of at least one hundred fifty percent.","يشترط البروتوكول نسبة ضمان لا تقل عن مئة وخمسين بالمئة.","extended","C1","COCA"],
  ["mining rig","noun","جهاز تعدين","He built a mining rig with six graphics cards in his garage.","بنى جهاز تعدين بست بطاقات رسومية في مرآبه.","core","B2","COCA"],
  ["smart contract audit","noun","تدقيق العقد الذكي","A smart contract audit identifies vulnerabilities before deployment.","يحدد تدقيق العقد الذكي الثغرات قبل النشر.","extended","C1","COCA"]
];

// ========== UNIT 7: Crowd Psychology (50 words) ==========
const u7 = [
  ["groupthink","noun","تفكير جماعي","Groupthink led the committee to ignore dissenting evidence.","أدى التفكير الجماعي بالمجلس إلى تجاهل الأدلة المعارضة.","core","B2","COCA"],
  ["deindividuation","noun","فقدان الفردية","Deindividuation in crowds reduces personal accountability.","يقلل فقدان الفردية في الحشود المسؤولية الشخصية.","extended","C1","COCA"],
  ["social loafing","noun","تكاسل اجتماعي","Social loafing increases when individual contributions cannot be measured.","يزداد التكاسل الاجتماعي عندما لا يمكن قياس المساهمات الفردية.","core","B2","COCA"],
  ["diffusion of responsibility","noun","تشتت المسؤولية","Diffusion of responsibility explains why large groups often fail to act.","يفسر تشتت المسؤولية سبب فشل المجموعات الكبيرة في التصرف غالباً.","extended","C1","COCA"],
  ["bystander effect","noun","تأثير المتفرج","The bystander effect delayed emergency calls during the incident.","أخّر تأثير المتفرج الاتصالات الطارئة أثناء الحادثة.","core","B2","COCA"],
  ["pluralistic ignorance","noun","جهل تعددي","Pluralistic ignorance occurs when everyone privately disagrees but stays silent.","يحدث الجهل التعددي عندما يختلف الجميع سراً لكنهم يبقون صامتين.","mastery","C1","COCA"],
  ["normative influence","noun","تأثير معياري","Normative influence drives conformity to avoid social rejection.","يدفع التأثير المعياري للامتثال لتجنب الرفض الاجتماعي.","extended","C1","AWL"],
  ["informational influence","noun","تأثير معلوماتي","Informational influence is strongest when the situation is ambiguous.","يكون التأثير المعلوماتي أقوى عندما يكون الموقف غامضاً.","extended","C1","AWL"],
  ["charismatic leader","noun","قائد كاريزمي","A charismatic leader can mobilize masses through emotional rhetoric.","يستطيع القائد الكاريزمي حشد الجماهير من خلال الخطاب العاطفي.","core","B2","COCA"],
  ["cult of personality","noun","عبادة الشخصية","The dictator cultivated a cult of personality through state media.","بنى الدكتاتور عبادة الشخصية من خلال وسائل الإعلام الحكومية.","core","B2","COCA"],
  ["bandwagon effect","noun","تأثير العربة","The bandwagon effect explains surging popularity of trending products.","يفسر تأثير العربة الشعبية المتصاعدة للمنتجات الرائجة.","core","B2","COCA"],
  ["spiral of silence","noun","لولب الصمت","The spiral of silence suppresses minority viewpoints in public discourse.","يقمع لولب الصمت وجهات نظر الأقلية في الخطاب العام.","extended","C1","COCA"],
  ["overton window","noun","نافذة أوفرتون","The overton window shifted, making the once-radical policy mainstream.","تحولت نافذة أوفرتون مما جعل السياسة المتطرفة سابقاً سائدة.","mastery","C1","COCA"],
  ["moral disengagement","noun","فك الارتباط الأخلاقي","Moral disengagement allows individuals to commit harm without guilt.","يسمح فك الارتباط الأخلاقي للأفراد بإلحاق الضرر دون شعور بالذنب.","extended","C1","COCA"],
  ["dehumanization","noun","نزع الإنسانية","Dehumanization of the enemy is a precursor to atrocities.","يُعد نزع الإنسانية عن العدو مقدمة لارتكاب الفظائع.","core","B2","COCA"],
  ["ingroup bias","noun","تحيز الجماعة الداخلية","Ingroup bias leads people to favour members of their own group.","يقود تحيز الجماعة الداخلية الناس إلى تفضيل أعضاء جماعتهم.","extended","C1","COCA"],
  ["outgroup hostility","noun","عداء تجاه الجماعة الخارجية","Outgroup hostility intensifies during periods of economic scarcity.","يشتد العداء تجاه الجماعة الخارجية خلال فترات الشح الاقتصادي.","extended","C1","COCA"],
  ["cognitive dissonance","noun","تنافر معرفي","Cognitive dissonance arises when actions contradict deeply held beliefs.","ينشأ التنافر المعرفي عندما تتعارض الأفعال مع المعتقدات الراسخة.","core","B2","COCA"],
  ["self-justification","noun","تبرير ذاتي","Self-justification prevents people from admitting their mistakes.","يمنع التبرير الذاتي الناس من الاعتراف بأخطائهم.","core","B2","COCA"],
  ["social proof","noun","دليل اجتماعي","Online reviews provide social proof that influences purchase decisions.","توفر المراجعات عبر الإنترنت دليلاً اجتماعياً يؤثر على قرارات الشراء.","core","B2","COCA"],
  ["anchoring bias","noun","تحيز الإرساء","Anchoring bias causes negotiators to fixate on the first number offered.","يجعل تحيز الإرساء المفاوضين يتمسكون بأول رقم يُعرض.","extended","C1","COCA"],
  ["framing effect","noun","تأثير التأطير","The framing effect changes preferences depending on how options are presented.","يغير تأثير التأطير التفضيلات بحسب طريقة عرض الخيارات.","core","B2","AWL"],
  ["availability heuristic","noun","استدلال التوفر","The availability heuristic makes people overestimate the risk of plane crashes.","يجعل استدلال التوفر الناس يبالغون في تقدير خطر تحطم الطائرات.","extended","C1","COCA"],
  ["sunk cost fallacy","noun","مغالطة التكلفة الغارقة","The sunk cost fallacy kept investors pouring money into a failing project.","أبقت مغالطة التكلفة الغارقة المستثمرين يضخون أموالاً في مشروع فاشل.","core","B2","COCA"],
  ["loss aversion","noun","كره الخسارة","Loss aversion makes people feel losses twice as strongly as equivalent gains.","يجعل كره الخسارة الناس يشعرون بالخسائر ضعف شعورهم بالمكاسب المعادلة.","core","B2","COCA"],
  ["status quo bias","noun","تحيز الوضع الراهن","Status quo bias discourages switching even when better options exist.","يثبط تحيز الوضع الراهن التحويل حتى عند وجود خيارات أفضل.","extended","C1","COCA"],
  ["learned helplessness","noun","عجز مكتسب","Learned helplessness develops after repeated exposure to uncontrollable events.","يتطور العجز المكتسب بعد التعرض المتكرر لأحداث لا يمكن السيطرة عليها.","core","B2","COCA"],
  ["self-fulfilling prophecy","noun","نبوءة تحقق ذاتها","Low teacher expectations can become a self-fulfilling prophecy for students.","يمكن أن تصبح توقعات المعلم المنخفضة نبوءة تحقق ذاتها للطلاب.","core","B2","COCA"],
  ["halo effect","noun","تأثير الهالة","The halo effect causes attractive people to be judged more favourably.","يجعل تأثير الهالة الأشخاص الجذابين يُحكم عليهم بشكل أكثر إيجابية.","core","B2","COCA"],
  ["priming effect","noun","تأثير التهيئة","A priming effect altered participants' word choices in the experiment.","غيّر تأثير التهيئة اختيارات المشاركين للكلمات في التجربة.","extended","C1","COCA"],
  ["nudge theory","noun","نظرية الوكز","Nudge theory designs choices to steer people toward healthier behaviour.","تصمم نظرية الوكز الخيارات لتوجيه الناس نحو سلوك أصح.","core","B2","COCA"],
  ["choice architecture","noun","هندسة الاختيار","Choice architecture determines which option is the default on a form.","تحدد هندسة الاختيار الخيار الافتراضي في الاستمارة.","extended","C1","COCA"],
  ["behavioral economics","noun","اقتصاد سلوكي","Behavioral economics combines psychology and economics to explain irrational decisions.","يجمع الاقتصاد السلوكي علم النفس والاقتصاد لتفسير القرارات غير العقلانية.","core","B2","AWL"],
  ["emotional contagion","noun","عدوى عاطفية","Emotional contagion spreads laughter through a crowded room within seconds.","تنشر العدوى العاطفية الضحك في غرفة مزدحمة خلال ثوانٍ.","extended","C1","COCA"],
  ["social facilitation","noun","تسهيل اجتماعي","Social facilitation improves performance on simple tasks in front of an audience.","يحسن التسهيل الاجتماعي الأداء في المهام البسيطة أمام الجمهور.","extended","C1","COCA"],
  ["audience effect","noun","تأثير الجمهور","The audience effect made the athlete perform at a higher level.","جعل تأثير الجمهور الرياضي يؤدي بمستوى أعلى.","core","B2","COCA"],
  ["free rider problem","noun","مشكلة الراكب المجاني","The free rider problem undermines collective funding for public goods.","تقوض مشكلة الراكب المجاني التمويل الجماعي للمنافع العامة.","core","B2","AWL"],
  ["tragedy of the commons","noun","مأساة المشاعات","Overfishing illustrates the tragedy of the commons in ocean resources.","يوضح الصيد الجائر مأساة المشاعات في الموارد البحرية.","core","B2","COCA"],
  ["consensus building","noun","بناء التوافق","Consensus building requires patient negotiation among diverse stakeholders.","يتطلب بناء التوافق تفاوضاً صبوراً بين أصحاب مصلحة متنوعين.","core","B2","AWL"],
  ["devil's advocate","noun","محامي الشيطان","Appointing a devil's advocate prevents premature group agreement.","يمنع تعيين محامي الشيطان الاتفاق الجماعي المبكر.","core","B2","COCA"],
  ["tipping cascade","noun","تتابع انقلابي","A tipping cascade can transform fringe ideas into mainstream movements.","يمكن للتتابع الانقلابي تحويل الأفكار الهامشية إلى حركات سائدة.","mastery","C1","COCA"],
  ["critical mass","noun","كتلة حرجة","A protest needs critical mass before it can force policy change.","يحتاج الاحتجاج إلى كتلة حرجة قبل أن يفرض تغييراً في السياسة.","core","B2","COCA"],
  ["threshold model","noun","نموذج العتبة","The threshold model predicts when individuals join collective action.","يتنبأ نموذج العتبة بموعد انضمام الأفراد إلى الفعل الجماعي.","mastery","C1","COCA"],
  ["opinion leader","noun","قائد رأي","Opinion leaders shape public attitudes through media appearances.","يشكّل قادة الرأي المواقف العامة عبر ظهورهم الإعلامي.","core","B2","COCA"],
  ["early adopter","noun","متبنٍّ مبكر","Early adopters influence mainstream acceptance of new technology.","يؤثر المتبنون المبكرون في القبول السائد للتقنية الجديدة.","core","B2","COCA"],
  ["moral panic","noun","ذعر أخلاقي","Media coverage amplified the moral panic over youth violence.","ضخمت التغطية الإعلامية الذعر الأخلاقي حول عنف الشباب.","core","B2","COCA"],
  ["mass hysteria","noun","هستيريا جماعية","Mass hysteria spread after the false emergency broadcast.","انتشرت الهستيريا الجماعية بعد بث الطوارئ الكاذب.","core","B2","COCA"],
  ["boiling frog metaphor","noun","استعارة الضفدع المغلي","The boiling frog metaphor warns against ignoring gradual threats.","تحذر استعارة الضفدع المغلي من تجاهل التهديدات التدريجية.","extended","C1","COCA"],
  ["prisoner's dilemma","noun","معضلة السجين","The prisoner's dilemma illustrates why rational actors may not cooperate.","توضح معضلة السجين لماذا قد لا يتعاون الفاعلون العقلانيون.","core","B2","COCA"],
  ["rationalization","noun","عقلنة (تبرير)","Rationalization helps people maintain a positive self-image after errors.","تساعد العقلنة الناس في الحفاظ على صورة ذاتية إيجابية بعد الأخطاء.","core","B2","COCA"]
];

// ========== UNIT 11: Sustainable Architecture (100 words) ==========
const u11 = [
  ["passive house","noun","منزل سلبي","A passive house maintains comfort with minimal active heating.","يحافظ المنزل السلبي على الراحة بأقل تدفئة فعالة.","core","B2","COCA"],
  ["net-zero building","noun","مبنى صافي الصفر","A net-zero building produces as much energy as it consumes annually.","ينتج المبنى صافي الصفر طاقة بقدر ما يستهلكه سنوياً.","core","B2","COCA"],
  ["mass timber","noun","خشب كتلي","Mass timber construction reduces embodied carbon compared to steel.","يقلل البناء بالخشب الكتلي الكربون المتضمن مقارنة بالفولاذ.","core","B2","COCA"],
  ["cross-laminated timber","noun","خشب متقاطع الطبقات","Cross-laminated timber panels can replace concrete floor slabs.","يمكن لألواح الخشب متقاطع الطبقات أن تحل محل بلاطات الخرسانة.","extended","C1","COCA"],
  ["hempcrete","noun","خرسانة القنب","Hempcrete is a lightweight insulating material made from hemp fibers.","خرسانة القنب مادة عازلة خفيفة مصنوعة من ألياف القنب.","extended","C1","COCA"],
  ["rammed earth wall","noun","جدار تراب مدكوك","A rammed earth wall provides thermal mass and natural aesthetics.","يوفر جدار التراب المدكوك كتلة حرارية وجماليات طبيعية.","extended","C1","COCA"],
  ["cob construction","noun","بناء الطوب اللبن","Cob construction mixes clay, sand, and straw into monolithic walls.","يمزج بناء الطوب اللبن الطين والرمل والقش في جدران متراصة.","mastery","C1","COCA"],
  ["straw bale insulation","noun","عزل بالات القش","Straw bale insulation achieves excellent thermal performance at low cost.","يحقق العزل ببالات القش أداءً حرارياً ممتازاً بتكلفة منخفضة.","extended","C1","COCA"],
  ["adobe brick","noun","طوب لبن","Adobe bricks dry in the sun and require no kiln firing.","يجف الطوب اللبن في الشمس ولا يحتاج إلى حرق في فرن.","core","B2","COCA"],
  ["compressed earth block","noun","كتلة تراب مضغوط","Compressed earth blocks are stronger and more uniform than adobe.","كتل التراب المضغوط أقوى وأكثر انتظاماً من اللبن.","extended","C1","COCA"],
  ["ferrocement","noun","إسمنت مسلح بالشبك","Ferrocement uses thin wire mesh embedded in cement morite.","يستخدم الإسمنت المسلح بالشبك شبكة سلكية رقيقة مدمجة في مونة الإسمنت.","mastery","C1","COCA"],
  ["bamboo reinforcement","noun","تسليح بالخيزران","Bamboo reinforcement replaces steel rebar in low-cost housing projects.","يحل التسليح بالخيزران محل حديد التسليح في مشاريع الإسكان منخفضة التكلفة.","extended","B2","COCA"],
  ["reclaimed timber","noun","خشب مستعاد","Reclaimed timber gives new buildings character while reducing waste.","يمنح الخشب المستعاد المباني الجديدة طابعاً مميزاً مع تقليل النفايات.","core","B2","COCA"],
  ["pervious concrete","noun","خرسانة نفاذة","Pervious concrete allows rainwater to percolate into the ground below.","تسمح الخرسانة النفاذة لمياه الأمطار بالتسرب إلى الأرض أسفلها.","extended","C1","COCA"],
  ["bioswale","noun","مجرى حيوي","A bioswale filters stormwater runoff using plants and soil layers.","يرشح المجرى الحيوي مياه العواصف باستخدام النباتات وطبقات التربة.","extended","C1","COCA"],
  ["rain garden","noun","حديقة مطرية","The rain garden captures roof runoff and recharges groundwater.","تلتقط الحديقة المطرية مياه الأسقف وتعيد شحن المياه الجوفية.","core","B2","COCA"],
  ["constructed wetland","noun","أرض رطبة مشيّدة","A constructed wetland treats wastewater through natural biological processes.","تعالج الأرض الرطبة المشيدة مياه الصرف عبر عمليات بيولوجية طبيعية.","extended","C1","COCA"],
  ["greywater recycling","noun","إعادة تدوير المياه الرمادية","Greywater recycling reuses sink and shower water for irrigation.","تعيد إعادة تدوير المياه الرمادية استخدام مياه الأحواض والدش للري.","core","B2","COCA"],
  ["blackwater treatment","noun","معالجة المياه السوداء","On-site blackwater treatment eliminates the need for sewer connections.","تلغي معالجة المياه السوداء في الموقع الحاجة إلى وصلات الصرف.","extended","C1","COCA"],
  ["composting toilet","noun","مرحاض تسميدي","A composting toilet converts human waste into usable fertilizer.","يحوّل المرحاض التسميدي الفضلات البشرية إلى سماد صالح للاستخدام.","extended","B2","COCA"],
  ["low-flow fixture","noun","تجهيزات منخفضة التدفق","Low-flow fixtures reduce water consumption by up to sixty percent.","تقلل التجهيزات منخفضة التدفق استهلاك المياه بنسبة تصل إلى ستين بالمئة.","core","B2","COCA"],
  ["dual flush valve","noun","صمام تدفق مزدوج","A dual flush valve offers two water volumes for different needs.","يوفر صمام التدفق المزدوج حجمين من المياه لاحتياجات مختلفة.","core","B1","COCA"],
  ["tankless water heater","noun","سخان ماء فوري","A tankless water heater only heats water on demand.","يسخن سخان الماء الفوري الماء عند الطلب فقط.","core","B2","COCA"],
  ["heat recovery ventilator","noun","مهوئ استرداد الحرارة","A heat recovery ventilator captures warmth from exhaust air.","يلتقط مهوئ استرداد الحرارة الدفء من هواء العادم.","extended","C1","COCA"],
  ["energy recovery ventilator","noun","مهوئ استرداد الطاقة","An energy recovery ventilator transfers both heat and moisture.","ينقل مهوئ استرداد الطاقة الحرارة والرطوبة معاً.","extended","C1","COCA"],
  ["ground-source heat pump","noun","مضخة حرارة أرضية","A ground-source heat pump exploits stable underground temperatures.","تستغل مضخة الحرارة الأرضية درجات الحرارة المستقرة تحت الأرض.","extended","C1","COCA"],
  ["air-source heat pump","noun","مضخة حرارة هوائية","An air-source heat pump extracts warmth from outdoor air in winter.","تستخلص مضخة الحرارة الهوائية الدفء من الهواء الخارجي شتاءً.","core","B2","COCA"],
  ["radiant floor heating","noun","تدفئة أرضية مشعة","Radiant floor heating distributes warmth evenly across the room.","توزع التدفئة الأرضية المشعة الدفء بالتساوي عبر الغرفة.","core","B2","COCA"],
  ["chilled beam","noun","عارضة مبرّدة","A chilled beam cools a room using convection around cold-water pipes.","تبرّد العارضة المبردة الغرفة باستخدام الحمل الحراري حول أنابيب الماء البارد.","mastery","C1","COCA"],
  ["displacement ventilation","noun","تهوية إزاحية","Displacement ventilation supplies cool air at floor level and exhausts warm air above.","توفر التهوية الإزاحية هواءً بارداً عند مستوى الأرض وتطرد الهواء الدافئ أعلاه.","extended","C1","COCA"],
  ["night purge ventilation","noun","تهوية تطهير ليلية","Night purge ventilation flushes out daytime heat to pre-cool the building.","تطرد تهوية التطهير الليلية حرارة النهار لتبريد المبنى مسبقاً.","extended","C1","COCA"],
  ["stack ventilation","noun","تهوية مدخنية","Stack ventilation drives airflow upward through vertical shafts.","تدفع التهوية المدخنية الهواء للأعلى عبر مجاري عمودية.","extended","C1","COCA"],
  ["wind catcher","noun","ملقف هواء","A traditional wind catcher channels breezes into buildings in arid climates.","يوجه ملقف الهواء التقليدي النسائم إلى المباني في المناخات الجافة.","core","B2","COCA"],
  ["solar chimney","noun","مدخنة شمسية","A solar chimney uses heated air to create natural draft ventilation.","تستخدم المدخنة الشمسية الهواء الساخن لخلق تهوية سحب طبيعية.","core","B2","COCA"],
  ["trombe wall","noun","جدار ترومب","A trombe wall absorbs sunlight and slowly radiates heat indoors.","يمتص جدار ترومب ضوء الشمس ويشع الحرارة ببطء إلى الداخل.","extended","C1","COCA"],
  ["thermal mass","noun","كتلة حرارية","Thick concrete walls provide thermal mass that stabilizes indoor temperatures.","توفر الجدران الخرسانية السميكة كتلة حرارية تثبّت درجات الحرارة الداخلية.","core","B2","COCA"],
  ["phase change material","noun","مادة متغيرة الطور","Phase change materials store and release heat during melting and solidifying.","تخزن المواد المتغيرة الطور الحرارة وتطلقها أثناء الانصهار والتصلب.","mastery","C1","COCA"],
  ["vacuum insulation panel","noun","لوح عزل مفرّغ","Vacuum insulation panels offer ten times the R-value of fiberglass.","توفر ألواح العزل المفرّغ عشرة أضعاف قيمة المقاومة الحرارية للألياف الزجاجية.","mastery","C1","COCA"],
  ["aerogel insulation","noun","عزل هلام هوائي","Aerogel insulation is the lightest solid insulator known to science.","عزل الهلام الهوائي أخف عازل صلب معروف للعلم.","mastery","C1","COCA"],
  ["cellulose insulation","noun","عزل سليلوزي","Cellulose insulation is made from recycled newspaper treated with borate.","يُصنع العزل السليلوزي من صحف معاد تدويرها معالجة بالبورات.","core","B2","COCA"],
  ["mineral wool insulation","noun","عزل صوف معدني","Mineral wool insulation resists fire and does not absorb moisture.","يقاوم عزل الصوف المعدني الحريق ولا يمتص الرطوبة.","core","B2","COCA"],
  ["reflective radiant barrier","noun","حاجز إشعاعي عاكس","A reflective radiant barrier in the attic reduces summer heat gain.","يقلل الحاجز الإشعاعي العاكس في العلية اكتساب الحرارة صيفاً.","extended","C1","COCA"],
  ["cool roof","noun","سقف بارد","A cool roof reflects sunlight and lowers air-conditioning demand.","يعكس السقف البارد أشعة الشمس ويخفض الطلب على التكييف.","core","B2","COCA"],
  ["vegetated roof","noun","سقف مزروع","A vegetated roof reduces stormwater runoff and insulates the building.","يقلل السقف المزروع جريان مياه العواصف ويعزل المبنى.","core","B2","COCA"],
  ["intensive green roof","noun","سقف أخضر مكثف","An intensive green roof supports trees and walking paths.","يدعم السقف الأخضر المكثف الأشجار وممرات المشاة.","extended","C1","COCA"],
  ["extensive green roof","noun","سقف أخضر خفيف","An extensive green roof uses shallow soil and drought-tolerant plants.","يستخدم السقف الأخضر الخفيف تربة ضحلة ونباتات متحملة للجفاف.","extended","C1","COCA"],
  ["building-integrated photovoltaic","noun","خلايا كهروضوئية مدمجة في المبنى","Building-integrated photovoltaics replace conventional roof tiles.","تحل الخلايا الكهروضوئية المدمجة محل بلاط الأسقف التقليدي.","extended","C1","COCA"],
  ["solar thermal collector","noun","مجمّع حراري شمسي","A solar thermal collector heats water for domestic use.","يسخن المجمع الحراري الشمسي الماء للاستخدام المنزلي.","core","B2","COCA"],
  ["evacuated tube collector","noun","مجمّع أنابيب مفرّغة","An evacuated tube collector performs well even in cold climates.","يعمل مجمّع الأنابيب المفرّغة بكفاءة حتى في المناخات الباردة.","mastery","C1","COCA"],
  ["daylight harvesting","noun","حصاد ضوء النهار","Daylight harvesting dims electric lights when natural light is sufficient.","يخفت حصاد ضوء النهار الإضاءة الكهربائية عندما يكون الضوء الطبيعي كافياً.","extended","C1","COCA"],
  ["light shelf","noun","رف ضوئي","A light shelf bounces sunlight deeper into the interior of a room.","يعكس الرف الضوئي أشعة الشمس إلى عمق أكبر داخل الغرفة.","extended","B2","COCA"],
  ["light tube","noun","أنبوب ضوئي","A light tube channels daylight from the roof into windowless rooms.","ينقل الأنبوب الضوئي ضوء النهار من السقف إلى الغرف بلا نوافذ.","core","B2","COCA"],
  ["electrochromic glazing","noun","زجاج كهروكرومي","Electrochromic glazing tints automatically to control solar gain.","يتلون الزجاج الكهروكرومي تلقائياً للتحكم في الكسب الشمسي.","mastery","C1","COCA"],
  ["low-emissivity coating","noun","طلاء منخفض الانبعاثية","Low-emissivity coatings reflect infrared heat back into the room.","تعكس الطلاءات منخفضة الانبعاثية حرارة الأشعة تحت الحمراء إلى الغرفة.","extended","C1","COCA"],
  ["argon-filled glazing","noun","زجاج مملوء بالأرغون","Argon-filled glazing reduces heat transfer between glass panes.","يقلل الزجاج المملوء بالأرغون انتقال الحرارة بين ألواح الزجاج.","extended","C1","COCA"],
  ["triple glazing","noun","زجاج ثلاثي","Triple glazing is standard in Scandinavian passive houses.","الزجاج الثلاثي معيار في المنازل السلبية الاسكندنافية.","core","B2","COCA"],
  ["curtain wall system","noun","نظام الجدار الستاري","A curtain wall system is a non-structural facade hung from the frame.","نظام الجدار الستاري واجهة غير إنشائية معلقة على الهيكل.","extended","C1","COCA"],
  ["kinetic facade","noun","واجهة حركية","A kinetic facade adjusts louvers in response to sun position.","تضبط الواجهة الحركية الشرائح استجابة لموقع الشمس.","mastery","C1","COCA"],
  ["responsive facade","noun","واجهة استجابية","A responsive facade adapts its opacity to changing weather conditions.","تكيّف الواجهة الاستجابية عتامتها مع الظروف الجوية المتغيرة.","mastery","C1","COCA"],
  ["double-skin facade","noun","واجهة مزدوجة الجلد","A double-skin facade creates a ventilated cavity that buffers noise and heat.","تنشئ الواجهة مزدوجة الجلد تجويفاً مهوّى يخفف الضوضاء والحرارة.","extended","C1","COCA"],
  ["U-value","noun","قيمة يو (معامل الانتقال الحراري)","A lower U-value means better insulating performance.","تعني قيمة يو الأقل أداء عزل أفضل.","core","B2","COCA"],
  ["R-value","noun","قيمة آر (المقاومة الحرارية)","Insulation with a high R-value slows heat flow more effectively.","يبطئ العزل بقيمة آر عالية تدفق الحرارة بفعالية أكبر.","core","B2","COCA"],
  ["thermal bridging","noun","جسر حراري","Thermal bridging at steel connections causes condensation and heat loss.","يسبب الجسر الحراري عند وصلات الفولاذ تكاثفاً وفقدان حرارة.","extended","C1","COCA"],
  ["blower door test","noun","اختبار باب المنفاخ","A blower door test measures air leakage through the building envelope.","يقيس اختبار باب المنفاخ تسرب الهواء عبر غلاف المبنى.","extended","C1","COCA"],
  ["infrared thermography","noun","تصوير حراري بالأشعة تحت الحمراء","Infrared thermography reveals hidden insulation gaps in walls.","يكشف التصوير الحراري بالأشعة تحت الحمراء فجوات العزل المخفية في الجدران.","extended","C1","COCA"],
  ["energy modeling","noun","نمذجة الطاقة","Energy modeling predicts annual consumption before construction begins.","تتنبأ نمذجة الطاقة بالاستهلاك السنوي قبل بدء البناء.","core","B2","AWL"],
  ["daylight modeling","noun","نمذجة الإضاءة الطبيعية","Daylight modeling optimizes window placement for uniform illumination.","تحسّن نمذجة الإضاءة الطبيعية موضع النوافذ لتحقيق إضاءة متساوية.","extended","C1","COCA"],
  ["bioclimatic design","noun","تصميم مناخي حيوي","Bioclimatic design aligns building orientation with local climate patterns.","يوائم التصميم المناخي الحيوي توجيه المبنى مع أنماط المناخ المحلي.","core","B2","COCA"],
  ["microclimate analysis","noun","تحليل المناخ المحلي الدقيق","Microclimate analysis maps wind speed and temperature across the site.","يرسم تحليل المناخ المحلي الدقيق خريطة سرعة الرياح ودرجة الحرارة عبر الموقع.","extended","C1","AWL"],
  ["urban heat island","noun","جزيرة حرارة حضرية","The urban heat island effect raises city temperatures several degrees above rural areas.","يرفع تأثير جزيرة الحرارة الحضرية درجات حرارة المدينة عدة درجات فوق المناطق الريفية.","core","B2","COCA"],
  ["albedo effect","noun","تأثير البياض","The albedo effect determines how much sunlight a surface reflects.","يحدد تأثير البياض مقدار ضوء الشمس الذي يعكسه السطح.","extended","C1","COCA"],
  ["mean radiant temperature","noun","متوسط درجة الحرارة المشعة","Mean radiant temperature affects thermal comfort more than air temperature alone.","يؤثر متوسط درجة الحرارة المشعة على الراحة الحرارية أكثر من حرارة الهواء وحدها.","mastery","C1","COCA"],
  ["adaptive comfort model","noun","نموذج الراحة التكيفي","The adaptive comfort model allows wider temperature ranges in naturally ventilated buildings.","يسمح نموذج الراحة التكيفي بنطاقات حرارة أوسع في المباني ذات التهوية الطبيعية.","mastery","C1","COCA"],
  ["natural ventilation design","noun","تصميم التهوية الطبيعية","Natural ventilation design exploits wind and buoyancy to move fresh air.","يستغل تصميم التهوية الطبيعية الرياح والطفو لتحريك الهواء النقي.","core","B2","COCA"],
  ["cross ventilation","noun","تهوية عرضية","Cross ventilation requires openings on opposite walls of a room.","تتطلب التهوية العرضية فتحات على جدران متقابلة من الغرفة.","core","B2","COCA"],
  ["buoyancy-driven ventilation","noun","تهوية مدفوعة بالطفو","Buoyancy-driven ventilation rises warm air out through high-level openings.","تصعد التهوية المدفوعة بالطفو الهواء الدافئ عبر فتحات علوية.","extended","C1","COCA"],
  ["Venturi effect","noun","تأثير فنتوري","The Venturi effect accelerates airflow through narrow building passages.","يسرّع تأثير فنتوري تدفق الهواء عبر ممرات المبنى الضيقة.","extended","C1","COCA"],
  ["pressure coefficient","noun","معامل الضغط","Pressure coefficients on the facade determine wind-driven ventilation rates.","تحدد معاملات الضغط على الواجهة معدلات التهوية بفعل الرياح.","mastery","C1","COCA"],
  ["building energy rating","noun","تصنيف طاقة المبنى","A building energy rating informs buyers about expected utility costs.","يبلّغ تصنيف طاقة المبنى المشترين عن تكاليف المرافق المتوقعة.","core","B2","COCA"],
  ["energy performance certificate","noun","شهادة أداء الطاقة","An energy performance certificate is mandatory for property sales in the EU.","شهادة أداء الطاقة إلزامية لبيع العقارات في الاتحاد الأوروبي.","core","B2","COCA"],
  ["nearly zero-energy building","noun","مبنى شبه صفري الطاقة","EU regulations require all new buildings to be nearly zero-energy by 2030.","تشترط لوائح الاتحاد الأوروبي أن تكون جميع المباني الجديدة شبه صفرية الطاقة بحلول 2030.","extended","C1","COCA"],
  ["BREEAM certification","noun","شهادة بريام","BREEAM certification evaluates the environmental performance of buildings.","تقيّم شهادة بريام الأداء البيئي للمباني.","core","B2","COCA"],
  ["LEED certification","noun","شهادة ليد","LEED certification ranks buildings from Certified to Platinum level.","تصنف شهادة ليد المباني من مستوى معتمد إلى مستوى بلاتيني.","core","B2","COCA"],
  ["WELL certification","noun","شهادة ويل","WELL certification focuses on occupant health and well-being in buildings.","تركز شهادة ويل على صحة ورفاهية شاغلي المباني.","extended","B2","COCA"],
  ["Passivhaus standard","noun","معيار باسيف هاوس","The Passivhaus standard limits annual heating demand to fifteen kilowatt-hours per square meter.","يحد معيار باسيف هاوس الطلب السنوي للتدفئة بخمسة عشر كيلوواط ساعة لكل متر مربع.","extended","C1","COCA"],
  ["operative temperature","noun","درجة الحرارة التشغيلية","Operative temperature combines air temperature and radiant temperature into one metric.","تجمع درجة الحرارة التشغيلية حرارة الهواء والحرارة المشعة في مقياس واحد.","mastery","C1","COCA"],
  ["psychrometric chart","noun","مخطط سيكرومتري","A psychrometric chart plots air temperature against humidity for HVAC design.","يرسم المخطط السيكرومتري حرارة الهواء مقابل الرطوبة لتصميم أنظمة التكييف.","mastery","C1","COCA"],
  ["conductive heat transfer","noun","انتقال الحرارة بالتوصيل","Conductive heat transfer passes energy through solid materials.","ينقل انتقال الحرارة بالتوصيل الطاقة عبر المواد الصلبة.","core","B2","COCA"],
  ["convective heat transfer","noun","انتقال الحرارة بالحمل","Convective heat transfer moves warmth through fluid or air movement.","ينقل انتقال الحرارة بالحمل الدفء عبر حركة السوائل أو الهواء.","core","B2","COCA"],
  ["radiative exchange","noun","تبادل إشعاعي","Radiative exchange between surfaces affects comfort in large open spaces.","يؤثر التبادل الإشعاعي بين الأسطح على الراحة في المساحات المفتوحة الكبيرة.","extended","C1","COCA"],
  ["evaporative cooling","noun","تبريد تبخيري","Evaporative cooling is most effective in hot dry climates.","يكون التبريد التبخيري أكثر فعالية في المناخات الحارة الجافة.","core","B2","COCA"],
  ["zero-carbon construction","noun","بناء صفري الكربون","Zero-carbon construction eliminates emissions across the entire building lifecycle.","يلغي البناء صفري الكربون الانبعاثات عبر دورة حياة المبنى بأكملها.","core","B2","COCA"],
  ["recycled steel aggregate","noun","ركام فولاذ معاد تدويره","Recycled steel aggregate reduces the environmental cost of new concrete.","يقلل ركام الفولاذ المعاد تدويره التكلفة البيئية للخرسانة الجديدة.","extended","C1","COCA"],
  ["flat plate collector","noun","مجمّع لوحي مسطح","A flat plate collector is the simplest type of solar water heater.","المجمّع اللوحي المسطح أبسط أنواع سخانات المياه الشمسية.","extended","B2","COCA"],
  ["spray foam insulation","noun","عزل رغوة رذاذية","Spray foam insulation seals gaps and provides both insulation and air barrier.","يسد عزل الرغوة الرذاذية الفجوات ويوفر عزلاً وحاجز هواء معاً.","core","B2","COCA"],
  ["cable-net facade","noun","واجهة شبكة كابلات","A cable-net facade supports large glass panels with minimal framing.","تدعم واجهة شبكة الكابلات ألواح زجاجية كبيرة بأقل إطار ممكن.","mastery","C1","COCA"],
  ["thermal comfort zone","noun","منطقة الراحة الحرارية","The thermal comfort zone varies by culture, clothing, and activity level.","تختلف منطقة الراحة الحرارية حسب الثقافة والملابس ومستوى النشاط.","core","B2","COCA"],
  ["heat balance equation","noun","معادلة التوازن الحراري","The heat balance equation accounts for all gains and losses in a room.","تحسب معادلة التوازن الحراري جميع المكاسب والخسائر في الغرفة.","mastery","C1","COCA"]
];

// ========== UNIT 12: Exoplanets (95 words) ==========
const u12 = [
  ["transit method","noun","طريقة العبور","The transit method detects planets by measuring dips in starlight.","تكشف طريقة العبور الكواكب عبر قياس انخفاضات في ضوء النجم.","core","B2","COCA"],
  ["radial velocity method","noun","طريقة السرعة الشعاعية","The radial velocity method measures a star's wobble caused by an orbiting planet.","تقيس طريقة السرعة الشعاعية تذبذب النجم الناجم عن كوكب يدور حوله.","core","B2","COCA"],
  ["direct imaging","noun","تصوير مباشر","Direct imaging captures faint light reflected by distant exoplanets.","يلتقط التصوير المباشر الضوء الخافت المنعكس من الكواكب الخارجية البعيدة.","core","B2","COCA"],
  ["gravitational microlensing","noun","عدسة جاذبية دقيقة","Gravitational microlensing amplifies starlight when a planet passes in front.","تضخم العدسة الجاذبية الدقيقة ضوء النجم عندما يمر كوكب أمامه.","extended","C1","COCA"],
  ["transit timing variation","noun","تغير توقيت العبور","Transit timing variations reveal unseen companion planets.","تكشف تغيرات توقيت العبور كواكب مرافقة غير مرئية.","extended","C1","COCA"],
  ["transmission spectroscopy","noun","مطيافية الإرسال","Transmission spectroscopy analyzes starlight filtered through a planet's atmosphere.","تحلل مطيافية الإرسال ضوء النجم المرشح عبر غلاف الكوكب الجوي.","extended","C1","COCA"],
  ["emission spectroscopy","noun","مطيافية الانبعاث","Emission spectroscopy detects heat radiated directly by the planet.","تكشف مطيافية الانبعاث الحرارة المشعة مباشرة من الكوكب.","extended","C1","COCA"],
  ["phase curve","noun","منحنى الطور","A phase curve maps brightness changes as a planet orbits its star.","يرسم منحنى الطور تغيرات السطوع أثناء دوران الكوكب حول نجمه.","extended","C1","COCA"],
  ["secondary eclipse","noun","كسوف ثانوي","A secondary eclipse occurs when the planet passes behind its host star.","يحدث الكسوف الثانوي عندما يمر الكوكب خلف نجمه المضيف.","extended","C1","COCA"],
  ["limb darkening","noun","تعتيم الحافة","Limb darkening makes the edges of a star appear dimmer than its center.","يجعل تعتيم الحافة حواف النجم تبدو أخفت من مركزه.","mastery","C1","COCA"],
  ["transit depth","noun","عمق العبور","Transit depth indicates the ratio of the planet's area to the star's area.","يشير عمق العبور إلى نسبة مساحة الكوكب إلى مساحة النجم.","extended","C1","COCA"],
  ["semi-major axis","noun","نصف المحور الأكبر","The semi-major axis defines the average distance between a planet and its star.","يحدد نصف المحور الأكبر المسافة المتوسطة بين الكوكب ونجمه.","core","B2","COCA"],
  ["orbital period","noun","دورة مدارية","Earth's orbital period around the Sun is approximately 365 days.","تبلغ الدورة المدارية للأرض حول الشمس حوالي 365 يوماً.","core","B1","COCA"],
  ["orbital inclination","noun","ميل مداري","Orbital inclination determines whether a transit is visible from Earth.","يحدد الميل المداري ما إذا كان العبور مرئياً من الأرض.","extended","C1","COCA"],
  ["Hill sphere","noun","كرة هيل","A moon must orbit within its planet's Hill sphere to remain gravitationally bound.","يجب أن يدور القمر ضمن كرة هيل لكوكبه ليبقى مرتبطاً جاذبياً.","mastery","C1","COCA"],
  ["Roche limit","noun","حد روش","A moon that crosses the Roche limit will be torn apart by tidal forces.","سيتمزق القمر الذي يعبر حد روش بفعل قوى المد والجزر.","extended","C1","COCA"],
  ["tidal locking","noun","قفل مدّي","Tidal locking keeps one hemisphere of the planet permanently facing its star.","يبقي القفل المدّي نصف كرة الكوكب مواجهاً لنجمه بشكل دائم.","core","B2","COCA"],
  ["synchronous rotation","noun","دوران متزامن","Synchronous rotation means the planet's day equals its orbital year.","يعني الدوران المتزامن أن يوم الكوكب يساوي سنته المدارية.","extended","C1","COCA"],
  ["mean-motion resonance","noun","رنين الحركة المتوسطة","Mean-motion resonance stabilizes the orbits of adjacent planets.","يثبّت رنين الحركة المتوسطة مدارات الكواكب المتجاورة.","mastery","C1","COCA"],
  ["Lagrange point","noun","نقطة لاغرانج","The James Webb Telescope orbits the Sun at Lagrange point two.","يدور تلسكوب جيمس ويب حول الشمس عند نقطة لاغرانج الثانية.","extended","C1","COCA"],
  ["protoplanetary disk","noun","قرص كوكبي أولي","A protoplanetary disk of gas and dust surrounds a young star.","يحيط قرص كوكبي أولي من الغاز والغبار بنجم فتي.","core","B2","COCA"],
  ["debris disk","noun","قرص حطام","A debris disk contains rocky fragments left over from planet formation.","يحتوي قرص الحطام على شظايا صخرية متبقية من تكوّن الكواكب.","extended","C1","COCA"],
  ["planetesimal","noun","كُوَيكب أولي","Planetesimals collide and merge to build larger planetary bodies.","تتصادم الكويكبات الأولية وتندمج لبناء أجرام كوكبية أكبر.","extended","C1","COCA"],
  ["core accretion model","noun","نموذج التراكم اللبّي","The core accretion model explains how rocky cores attract gas envelopes.","يفسر نموذج التراكم اللبّي كيف تجذب النوى الصخرية أغلفة غازية.","extended","C1","COCA"],
  ["disk instability model","noun","نموذج عدم استقرار القرص","The disk instability model proposes that gas giants form by gravitational collapse.","يقترح نموذج عدم استقرار القرص أن العمالقة الغازية تتشكل بالانهيار الجاذبي.","mastery","C1","COCA"],
  ["T Tauri star","noun","نجم تي ثوري","A T Tauri star is a young star still contracting toward the main sequence.","نجم تي ثوري نجم فتي لا يزال يتقلص نحو التسلسل الرئيسي.","mastery","C1","COCA"],
  ["main sequence star","noun","نجم التسلسل الرئيسي","Our Sun is a main sequence star that fuses hydrogen into helium.","شمسنا نجم تسلسل رئيسي يدمج الهيدروجين إلى هيليوم.","core","B2","COCA"],
  ["red giant phase","noun","طور العملاق الأحمر","In the red giant phase, a star expands hundreds of times its original size.","في طور العملاق الأحمر يتمدد النجم مئات المرات من حجمه الأصلي.","core","B2","COCA"],
  ["white dwarf remnant","noun","بقايا القزم الأبيض","A white dwarf remnant is the dense core left after a star sheds its outer layers.","بقايا القزم الأبيض هي اللب الكثيف المتبقي بعد أن يطرح النجم طبقاته الخارجية.","core","B2","COCA"],
  ["planetary nebula","noun","سديم كوكبي","A planetary nebula glows as ultraviolet light ionizes the expelled gas.","يتوهج السديم الكوكبي عندما يؤين الضوء فوق البنفسجي الغاز المطرود.","extended","C1","COCA"],
  ["stellar wind","noun","رياح نجمية","Stellar wind strips atmospheres from close-orbiting exoplanets.","تجرّد الرياح النجمية الأغلفة الجوية من الكواكب القريبة المدار.","core","B2","COCA"],
  ["coronal mass ejection","noun","قذف كتلة إكليلية","A coronal mass ejection can disable satellites and damage power grids.","يمكن للقذف الكتلي الإكليلي تعطيل الأقمار الصناعية وإتلاف شبكات الكهرباء.","extended","C1","COCA"],
  ["stellar flare","noun","توهج نجمي","A powerful stellar flare can erode a planet's ozone layer.","يمكن لتوهج نجمي قوي أن يآكل طبقة أوزون الكوكب.","core","B2","COCA"],
  ["stellar metallicity","noun","معدنية نجمية","Higher stellar metallicity correlates with a greater frequency of rocky planets.","ترتبط المعدنية النجمية الأعلى بتكرار أكبر للكواكب الصخرية.","extended","C1","COCA"],
  ["nucleosynthesis","noun","تخليق نووي","Nucleosynthesis inside stars forges elements heavier than hydrogen and helium.","يصنع التخليق النووي داخل النجوم عناصر أثقل من الهيدروجين والهيليوم.","extended","C1","COCA"],
  ["spectroscopic binary","noun","ثنائي مطيافي","A spectroscopic binary is detected through periodic Doppler shifts in its spectrum.","يُكشف الثنائي المطيافي عبر انزياحات دوبلر الدورية في طيفه.","mastery","C1","COCA"],
  ["eclipsing binary","noun","ثنائي كسوفي","An eclipsing binary reveals stellar radii from its light curve dips.","يكشف الثنائي الكسوفي أنصاف أقطار النجوم من انخفاضات منحنى ضوئه.","mastery","C1","COCA"],
  ["transit photometry","noun","قياس ضوئي عبوري","Transit photometry requires extremely precise brightness measurements.","يتطلب القياس الضوئي العبوري قياسات سطوع دقيقة للغاية.","extended","C1","COCA"],
  ["mass-radius relation","noun","علاقة الكتلة-نصف القطر","The mass-radius relation distinguishes rocky planets from gas-dominated worlds.","تميّز علاقة الكتلة-نصف القطر الكواكب الصخرية من العوالم الغازية.","extended","C1","COCA"],
  ["interior structure model","noun","نموذج البنية الداخلية","An interior structure model predicts layers of rock, ice, and metal inside a planet.","يتنبأ نموذج البنية الداخلية بطبقات الصخر والجليد والمعدن داخل الكوكب.","mastery","C1","COCA"],
  ["equation of state","noun","معادلة الحالة","The equation of state relates pressure, temperature, and density of planetary material.","تربط معادلة الحالة الضغط والحرارة وكثافة المادة الكوكبية.","mastery","C1","COCA"],
  ["adiabatic gradient","noun","تدرج كظوم","The adiabatic gradient describes how temperature changes with depth without heat exchange.","يصف التدرج الكظوم كيف تتغير الحرارة مع العمق دون تبادل حراري.","mastery","C1","COCA"],
  ["volcanic outgassing","noun","تفريغ غازي بركاني","Volcanic outgassing released the gases that formed Earth's early atmosphere.","أطلق التفريغ الغازي البركاني الغازات التي شكلت غلاف الأرض الجوي المبكر.","core","B2","COCA"],
  ["atmospheric escape","noun","هروب جوي","Atmospheric escape gradually strips light gases from small planets.","يجرّد الهروب الجوي تدريجياً الغازات الخفيفة من الكواكب الصغيرة.","core","B2","COCA"],
  ["Jeans escape","noun","هروب جينز","Jeans escape occurs when individual gas molecules reach escape velocity.","يحدث هروب جينز عندما تبلغ جزيئات الغاز الفردية سرعة الإفلات.","mastery","C1","COCA"],
  ["hydrodynamic escape","noun","هروب هيدروديناميكي","Hydrodynamic escape can strip an entire atmosphere in a few million years.","يمكن للهروب الهيدروديناميكي تجريد غلاف جوي كامل في بضعة ملايين سنة.","mastery","C1","COCA"],
  ["photodissociation","noun","تفكك ضوئي","Photodissociation breaks water molecules into hydrogen and oxygen in the upper atmosphere.","يفكك التفكك الضوئي جزيئات الماء إلى هيدروجين وأكسجين في الغلاف الجوي العلوي.","extended","C1","COCA"],
  ["extreme ultraviolet radiation","noun","أشعة فوق بنفسجية متطرفة","Extreme ultraviolet radiation from young stars drives rapid atmospheric loss.","تدفع الأشعة فوق البنفسجية المتطرفة من النجوم الفتية فقداناً جوياً سريعاً.","extended","C1","COCA"],
  ["differential rotation","noun","دوران تفاضلي","Differential rotation means a star's equator spins faster than its poles.","يعني الدوران التفاضلي أن خط استواء النجم يدور أسرع من قطبيه.","extended","C1","COCA"],
  ["stellar dynamo","noun","دينامو نجمي","The stellar dynamo generates magnetic fields through internal convection currents.","يولّد الدينامو النجمي حقولاً مغناطيسية عبر تيارات الحمل الداخلية.","mastery","C1","COCA"],
  ["convection zone","noun","منطقة الحمل","Energy in the convection zone moves outward via rising hot plasma.","تنتقل الطاقة في منطقة الحمل للخارج عبر بلازما ساخنة صاعدة.","core","B2","COCA"],
  ["radiative zone","noun","منطقة إشعاعية","Photons in the radiative zone take thousands of years to reach the surface.","تستغرق الفوتونات في المنطقة الإشعاعية آلاف السنين للوصول إلى السطح.","extended","C1","COCA"],
  ["proton-proton chain","noun","سلسلة بروتون-بروتون","The proton-proton chain is the dominant fusion process in Sun-like stars.","سلسلة بروتون-بروتون هي عملية الاندماج المهيمنة في نجوم شبيهة بالشمس.","extended","C1","COCA"],
  ["CNO cycle","noun","دورة سي إن أو","The CNO cycle dominates energy production in stars hotter than the Sun.","تهيمن دورة سي إن أو على إنتاج الطاقة في نجوم أسخن من الشمس.","mastery","C1","COCA"],
  ["triple-alpha process","noun","عملية ألفا الثلاثية","The triple-alpha process fuses helium into carbon inside red giant stars.","تدمج عملية ألفا الثلاثية الهيليوم إلى كربون داخل نجوم العملاق الأحمر.","mastery","C1","COCA"],
  ["brown dwarf","noun","قزم بني","A brown dwarf is too small to sustain hydrogen fusion.","القزم البني صغير جداً للحفاظ على اندماج الهيدروجين.","core","B2","COCA"],
  ["methane absorption band","noun","نطاق امتصاص الميثان","A methane absorption band in the spectrum identifies gas-rich atmospheres.","يحدد نطاق امتصاص الميثان في الطيف الأغلفة الجوية الغنية بالغاز.","extended","C1","COCA"],
  ["water absorption feature","noun","سمة امتصاص الماء","A water absorption feature in the infrared confirms water vapor presence.","تؤكد سمة امتصاص الماء في الأشعة تحت الحمراء وجود بخار الماء.","extended","C1","COCA"],
  ["cloud deck","noun","طبقة سحب","A thick cloud deck on Venus traps heat through a runaway greenhouse effect.","تحبس طبقة السحب السميكة على الزهرة الحرارة عبر تأثير الدفيئة الجامح.","core","B2","COCA"],
  ["silicate cloud","noun","سحابة سيليكاتية","Silicate clouds form in the scorching atmospheres of hot Jupiters.","تتشكل السحب السيليكاتية في الأغلفة الجوية الحارقة للمشتريات الساخنة.","mastery","C1","COCA"],
  ["iron cloud","noun","سحابة حديدية","Iron clouds condense at temperatures above two thousand Kelvin on ultra-hot exoplanets.","تتكاثف السحب الحديدية عند حرارات فوق ألفي كلفن على الكواكب فائقة الحرارة.","mastery","C1","COCA"],
  ["phosphine detection","noun","كشف الفوسفين","Phosphine detection on Venus sparked debate about possible microbial life.","أثار كشف الفوسفين على الزهرة جدلاً حول حياة ميكروبية محتملة.","extended","C1","COCA"],
  ["biosignature gas","noun","غاز مؤشر حيوي","A biosignature gas like oxygen may indicate biological activity on an exoplanet.","قد يشير غاز مؤشر حيوي كالأكسجين إلى نشاط بيولوجي على كوكب خارجي.","core","B2","COCA"],
  ["ozone layer detection","noun","كشف طبقة الأوزون","Ozone layer detection in an exoplanet atmosphere would strengthen the case for life.","سيعزز كشف طبقة الأوزون في غلاف كوكب خارجي قضية وجود الحياة.","extended","C1","COCA"],
  ["methane biosignature","noun","مؤشر حيوي للميثان","A methane biosignature combined with oxygen strongly suggests biological origin.","يشير مؤشر حيوي للميثان مع الأكسجين بقوة إلى أصل بيولوجي.","extended","C1","COCA"],
  ["carbon dioxide absorption","noun","امتصاص ثاني أكسيد الكربون","Carbon dioxide absorption at 4.3 microns is detectable by space telescopes.","يمكن رصد امتصاص ثاني أكسيد الكربون عند 4.3 ميكرون بتلسكوبات فضائية.","core","B2","COCA"],
  ["Rayleigh scattering","noun","تبعثر رايلي","Rayleigh scattering gives Earth's sky its blue color.","يمنح تبعثر رايلي سماء الأرض لونها الأزرق.","core","B2","COCA"],
  ["Mie scattering","noun","تبعثر مي","Mie scattering from aerosols produces the white haze near the horizon.","ينتج تبعثر مي من الهباء الجوي الضباب الأبيض قرب الأفق.","extended","C1","COCA"],
  ["geometric albedo","noun","بياض هندسي","Geometric albedo measures the fraction of light reflected directly back to the observer.","يقيس البياض الهندسي نسبة الضوء المنعكس مباشرة إلى الراصد.","extended","C1","COCA"],
  ["Bond albedo","noun","بياض بوند","Bond albedo accounts for all wavelengths and angles of reflected light.","يحسب بياض بوند جميع أطوال الموجة وزوايا الضوء المنعكس.","mastery","C1","COCA"],
  ["equilibrium temperature","noun","درجة حرارة التوازن","Equilibrium temperature estimates a planet's surface temperature from stellar input alone.","تقدّر درجة حرارة التوازن حرارة سطح الكوكب من المدخلات النجمية فقط.","core","B2","COCA"],
  ["instellation flux","noun","تدفق الإشعاع النجمي","Instellation flux measures the stellar energy received per unit area of the planet.","يقيس تدفق الإشعاع النجمي الطاقة النجمية المستقبلة لكل وحدة مساحة من الكوكب.","mastery","C1","COCA"],
  ["stellar effective temperature","noun","درجة الحرارة الفعالة للنجم","Stellar effective temperature determines the peak wavelength of emitted light.","تحدد درجة الحرارة الفعالة للنجم الطول الموجي الذروي للضوء المنبعث.","extended","C1","COCA"],
  ["habitable zone inner edge","noun","الحافة الداخلية للمنطقة الصالحة للسكن","The habitable zone inner edge is where a runaway greenhouse begins.","الحافة الداخلية للمنطقة الصالحة للسكن حيث يبدأ الاحتباس الحراري الجامح.","extended","C1","COCA"],
  ["runaway greenhouse effect","noun","تأثير الدفيئة الجامح","A runaway greenhouse effect evaporated all oceans on early Venus.","أدى تأثير الدفيئة الجامح إلى تبخر جميع محيطات الزهرة المبكرة.","core","B2","COCA"],
  ["moist greenhouse state","noun","حالة الدفيئة الرطبة","In a moist greenhouse state, water vapor rises to the stratosphere and is lost.","في حالة الدفيئة الرطبة يرتفع بخار الماء إلى طبقة الستراتوسفير ويُفقد.","mastery","C1","COCA"],
  ["maximum greenhouse limit","noun","حد الدفيئة الأقصى","The maximum greenhouse limit marks the outer boundary of the habitable zone.","يحدد حد الدفيئة الأقصى الحدود الخارجية للمنطقة الصالحة للسكن.","mastery","C1","COCA"],
  ["circumstellar habitable zone","noun","المنطقة الصالحة للسكن حول النجم","The circumstellar habitable zone is where liquid water can exist on a planet's surface.","المنطقة الصالحة للسكن حول النجم حيث يمكن أن توجد مياه سائلة على سطح الكوكب.","core","B2","COCA"],
  ["hydrogen sulfide band","noun","نطاق كبريتيد الهيدروجين","A hydrogen sulfide band was detected in the atmosphere of Uranus.","رُصد نطاق كبريتيد الهيدروجين في غلاف أورانوس الجوي.","mastery","C1","COCA"],
  ["water vapor spectrum","noun","طيف بخار الماء","The water vapor spectrum shows strong features in the near-infrared.","يُظهر طيف بخار الماء سمات قوية في الأشعة تحت الحمراء القريبة.","extended","B2","COCA"],
  ["accretion disk","noun","قرص تراكمي","An accretion disk feeds material onto a growing protostar.","يغذي القرص التراكمي المادة إلى نجم أولي ينمو.","core","B2","COCA"],
  ["starspot","noun","بقعة نجمية","A large starspot can mimic a planetary transit signal.","يمكن لبقعة نجمية كبيرة محاكاة إشارة عبور كوكبي.","extended","C1","COCA"],
  ["galactic chemical evolution","noun","التطور الكيميائي المجري","Galactic chemical evolution enriches each stellar generation with heavier elements.","يغني التطور الكيميائي المجري كل جيل نجمي بعناصر أثقل.","mastery","C1","COCA"],
  ["open star cluster","noun","عنقود نجمي مفتوح","An open star cluster contains young stars born from the same molecular cloud.","يحتوي العنقود النجمي المفتوح على نجوم فتية ولدت من نفس السحابة الجزيئية.","core","B2","COCA"],
  ["globular cluster","noun","عنقود كروي","A globular cluster orbits the galaxy and contains hundreds of thousands of old stars.","يدور العنقود الكروي حول المجرة ويحتوي على مئات الآلاف من النجوم القديمة.","extended","C1","COCA"],
  ["protoplanet","noun","كوكب أولي","A protoplanet grows by sweeping up material from the surrounding disk.","ينمو الكوكب الأولي بجمع المادة من القرص المحيط.","extended","C1","COCA"],
  ["chromospheric emission","noun","انبعاث كروموسفيري","Chromospheric emission lines indicate the magnetic activity level of a star.","تشير خطوط الانبعاث الكروموسفيري إلى مستوى النشاط المغناطيسي للنجم.","mastery","C1","COCA"],
  ["carbon monoxide detection","noun","كشف أول أكسيد الكربون","Carbon monoxide detection helps constrain atmospheric chemistry models.","يساعد كشف أول أكسيد الكربون في تقييد نماذج الكيمياء الجوية.","extended","C1","COCA"],
  ["oxygen biosignature","noun","مؤشر حيوي للأكسجين","An oxygen biosignature alone is not definitive proof of life.","ليس المؤشر الحيوي للأكسجين وحده دليلاً قاطعاً على الحياة.","core","B2","COCA"],
  ["transit duration","noun","مدة العبور","Transit duration depends on orbital speed and the star's diameter.","تعتمد مدة العبور على السرعة المدارية وقطر النجم.","core","B2","COCA"]
];

async function main() {
  const client = await pool.connect();
  try {
    const units = [
      { num: 3, words: u3 },
      { num: 4, words: u4 },
      { num: 5, words: u5 },
      { num: 6, words: u6 },
      { num: 7, words: u7 },
      { num: 11, words: u11 },
      { num: 12, words: u12 },
    ];
    let totalInserted = 0;
    for (const u of units) {
      const count = await insertBatch(client, u.words, u.num, BATCH_ID);
      console.log(`U${u.num}: inserted ${count}/${u.words.length}`);
      totalInserted += count;
    }
    console.log(`\nTotal inserted: ${totalInserted}`);

    // Query final totals
    console.log('\n--- Final vocab_staging_l4 totals ---');
    for (const u of units) {
      const res = await client.query('SELECT COUNT(*) FROM public.vocab_staging_l4 WHERE recommended_unit = $1', [u.num]);
      console.log(`U${u.num}: ${res.rows[0].count} words`);
    }
    const total = await client.query('SELECT COUNT(*) FROM public.vocab_staging_l4');
    console.log(`Overall total: ${total.rows[0].count} words`);
  } finally {
    client.release();
    await pool.end();
  }
}

main().catch(e => { console.error(e); process.exit(1); });
