-- Migration: 033_seed_irregular_verbs
-- Description: Seed 150 irregular verbs into curriculum_irregular_verbs
-- Levels 1-6 with Arabic meanings, example sentences, and categories

INSERT INTO curriculum_irregular_verbs
  (level, difficulty_order, base, past, past_participle, meaning_ar, example_sentence, category)
VALUES
  -- ============================================================
  -- LEVEL 1: Most common daily verbs (30 verbs)
  -- ============================================================
  (1, 1,  'go',     'went',     'gone',      'يذهب',    'I go to school every morning.',                    'general'),
  (1, 2,  'come',   'came',     'come',      'يأتي',    'She came home late last night.',                   'general'),
  (1, 3,  'eat',    'ate',      'eaten',     'يأكل',    'We ate lunch at a small restaurant.',              'general'),
  (1, 4,  'drink',  'drank',    'drunk',     'يشرب',    'He drank a glass of water after the run.',         'general'),
  (1, 5,  'see',    'saw',      'seen',      'يرى',     'I saw a beautiful sunset yesterday.',              'general'),
  (1, 6,  'make',   'made',     'made',      'يصنع',    'She made a delicious cake for the party.',         'general'),
  (1, 7,  'take',   'took',     'taken',     'يأخذ',    'He took the bus to work this morning.',            'travel'),
  (1, 8,  'give',   'gave',     'given',     'يعطي',    'They gave me a wonderful gift.',                   'general'),
  (1, 9,  'get',    'got',      'gotten',    'يحصل على', 'I got a new job last week.',                       'business'),
  (1, 10, 'have',   'had',      'had',       'يملك',    'We had a great time at the park.',                 'general'),
  (1, 11, 'do',     'did',      'done',      'يفعل',    'She did her homework before dinner.',              'academic'),
  (1, 12, 'say',    'said',     'said',      'يقول',    'He said he would arrive by noon.',                 'general'),
  (1, 13, 'know',   'knew',     'known',     'يعرف',    'I knew the answer to the question.',               'academic'),
  (1, 14, 'think',  'thought',  'thought',   'يفكر',    'She thought carefully before making a decision.',  'general'),
  (1, 15, 'find',   'found',    'found',     'يجد',     'We found a great hotel near the beach.',           'travel'),
  (1, 16, 'tell',   'told',     'told',      'يخبر',    'He told me the truth about what happened.',        'general'),
  (1, 17, 'feel',   'felt',     'felt',      'يشعر',    'I felt happy when I heard the good news.',         'general'),
  (1, 18, 'put',    'put',      'put',       'يضع',     'She put the books on the shelf.',                  'general'),
  (1, 19, 'run',    'ran',      'run',       'يركض',    'He ran five kilometers this morning.',             'general'),
  (1, 20, 'sit',    'sat',      'sat',       'يجلس',    'We sat together in the front row.',                'general'),
  (1, 21, 'stand',  'stood',    'stood',     'يقف',     'They stood in line for two hours.',                'general'),
  (1, 22, 'write',  'wrote',    'written',   'يكتب',    'She wrote a long letter to her friend.',           'academic'),
  (1, 23, 'read',   'read',     'read',      'يقرأ',    'I read an interesting book last weekend.',         'academic'),
  (1, 24, 'speak',  'spoke',    'spoken',    'يتكلم',   'He spoke fluent English at the conference.',       'academic'),
  (1, 25, 'buy',    'bought',   'bought',    'يشتري',   'We bought fresh vegetables from the market.',      'general'),
  (1, 26, 'bring',  'brought',  'brought',   'يحضر',    'She brought flowers to the dinner party.',         'general'),
  (1, 27, 'teach',  'taught',   'taught',    'يُعلّم',   'He taught mathematics for twenty years.',          'academic'),
  (1, 28, 'learn',  'learnt',   'learnt',    'يتعلم',   'I learnt to swim when I was six years old.',       'academic'),
  (1, 29, 'sleep',  'slept',    'slept',     'ينام',    'The baby slept through the entire night.',         'general'),
  (1, 30, 'wake',   'woke',     'woken',     'يستيقظ',  'She woke up early to catch the train.',            'general'),

  -- ============================================================
  -- LEVEL 2: Common past tense (30 verbs)
  -- ============================================================
  (2, 1,  'choose',     'chose',      'chosen',      'يختار',    'He chose the blue shirt for the interview.',        'general'),
  (2, 2,  'drive',      'drove',      'driven',      'يقود',     'She drove to the airport in heavy traffic.',        'travel'),
  (2, 3,  'draw',       'drew',       'drawn',       'يرسم',     'The artist drew a portrait of the old man.',        'general'),
  (2, 4,  'fall',       'fell',       'fallen',      'يسقط',     'He fell off his bicycle and hurt his knee.',        'general'),
  (2, 5,  'fly',        'flew',       'flown',       'يطير',     'We flew from London to Tokyo last summer.',         'travel'),
  (2, 6,  'forget',     'forgot',     'forgotten',   'ينسى',     'I forgot my passport at the hotel.',               'travel'),
  (2, 7,  'grow',       'grew',       'grown',       'ينمو',     'The company grew rapidly in the last decade.',      'business'),
  (2, 8,  'hide',       'hid',        'hidden',      'يخفي',     'The children hid behind the large tree.',           'general'),
  (2, 9,  'hold',       'held',       'held',        'يمسك',     'She held the baby gently in her arms.',             'general'),
  (2, 10, 'keep',       'kept',       'kept',        'يحتفظ',    'He kept all the old letters in a box.',             'general'),
  (2, 11, 'leave',      'left',       'left',        'يغادر',    'They left the office at five o''clock.',            'business'),
  (2, 12, 'lose',       'lost',       'lost',        'يخسر',     'Our team lost the final match by one goal.',        'general'),
  (2, 13, 'meet',       'met',        'met',         'يقابل',    'I met my old friend at the coffee shop.',           'general'),
  (2, 14, 'pay',        'paid',       'paid',        'يدفع',     'She paid the bill with her credit card.',           'business'),
  (2, 15, 'ride',       'rode',       'ridden',      'يركب',     'He rode his horse along the river bank.',           'travel'),
  (2, 16, 'ring',       'rang',       'rung',        'يرنّ',     'The phone rang three times before she answered.',   'general'),
  (2, 17, 'rise',       'rose',       'risen',       'يرتفع',    'The sun rose over the mountains at dawn.',          'general'),
  (2, 18, 'send',       'sent',       'sent',        'يرسل',     'He sent the report to his manager by email.',       'business'),
  (2, 19, 'show',       'showed',     'shown',       'يُظهر',    'She showed us around the new office building.',     'business'),
  (2, 20, 'sing',       'sang',       'sung',        'يغني',     'The choir sang beautifully at the ceremony.',       'general'),
  (2, 21, 'swim',       'swam',       'swum',        'يسبح',     'We swam in the clear blue sea all afternoon.',      'travel'),
  (2, 22, 'throw',      'threw',      'thrown',      'يرمي',     'He threw the ball across the entire field.',        'general'),
  (2, 23, 'understand', 'understood', 'understood',  'يفهم',     'She understood the lesson after reading it twice.', 'academic'),
  (2, 24, 'wear',       'wore',       'worn',        'يرتدي',    'He wore a formal suit to the wedding.',             'general'),
  (2, 25, 'win',        'won',        'won',         'يفوز',     'She won first prize in the science competition.',   'academic'),
  (2, 26, 'catch',      'caught',     'caught',      'يمسك',     'The goalkeeper caught the ball with one hand.',      'general'),
  (2, 27, 'build',      'built',      'built',       'يبني',     'They built a new bridge over the river.',           'business'),
  (2, 28, 'break',      'broke',      'broken',      'يكسر',     'He broke the window with a baseball.',              'general'),
  (2, 29, 'spend',      'spent',      'spent',       'ينفق',     'We spent the whole weekend at the countryside.',    'travel'),
  (2, 30, 'sell',       'sold',       'sold',        'يبيع',     'She sold her old car for a good price.',            'business'),

  -- ============================================================
  -- LEVEL 3: Intermediate (25 verbs)
  -- ============================================================
  (3, 1,  'arise',  'arose',    'arisen',    'ينشأ',       'A new problem arose during the meeting.',              'business'),
  (3, 2,  'bear',   'bore',     'borne',     'يتحمّل',     'She bore the pain without complaining.',                'general'),
  (3, 3,  'beat',   'beat',     'beaten',    'يهزم',       'Our team beat the champions in the semifinals.',        'general'),
  (3, 4,  'begin',  'began',    'begun',     'يبدأ',       'The concert began at eight o''clock sharp.',            'general'),
  (3, 5,  'bite',   'bit',      'bitten',    'يعضّ',       'The dog bit the postman on his leg.',                   'general'),
  (3, 6,  'blow',   'blew',     'blown',     'ينفخ',       'The wind blew the leaves across the yard.',             'general'),
  (3, 7,  'breed',  'bred',     'bred',      'يُربّي',     'The farmer bred horses on his large estate.',           'general'),
  (3, 8,  'burn',   'burnt',    'burnt',     'يحرق',       'She burnt the toast while reading the newspaper.',      'general'),
  (3, 9,  'burst',  'burst',    'burst',     'ينفجر',      'The balloon burst with a loud pop.',                    'general'),
  (3, 10, 'cost',   'cost',     'cost',      'يكلّف',      'The new laptop cost more than I expected.',             'business'),
  (3, 11, 'cut',    'cut',      'cut',       'يقطع',       'He cut the paper into small pieces.',                   'general'),
  (3, 12, 'deal',   'dealt',    'dealt',     'يتعامل',     'She dealt with the complaint professionally.',          'business'),
  (3, 13, 'dig',    'dug',      'dug',       'يحفر',       'They dug a deep hole to plant the tree.',               'general'),
  (3, 14, 'feed',   'fed',      'fed',       'يُطعم',      'She fed the birds every morning in the garden.',        'general'),
  (3, 15, 'fight',  'fought',   'fought',    'يقاتل',      'The soldiers fought bravely to defend the city.',       'general'),
  (3, 16, 'freeze', 'froze',    'frozen',    'يتجمّد',     'The lake froze completely during the harsh winter.',    'general'),
  (3, 17, 'hang',   'hung',     'hung',      'يعلّق',      'She hung the painting above the fireplace.',            'general'),
  (3, 18, 'hear',   'heard',    'heard',     'يسمع',       'I heard a strange noise coming from the attic.',        'general'),
  (3, 19, 'hurt',   'hurt',     'hurt',      'يؤذي',       'He hurt his ankle while playing football.',             'general'),
  (3, 20, 'kneel',  'knelt',    'knelt',     'يركع',       'She knelt down to tie her shoelace.',                   'general'),
  (3, 21, 'lead',   'led',      'led',       'يقود',       'He led the team to victory in the tournament.',         'business'),
  (3, 22, 'lie',    'lay',      'lain',      'يستلقي',     'She lay on the sofa and fell asleep.',                  'general'),
  (3, 23, 'mean',   'meant',    'meant',     'يعني',       'I meant to call you but I forgot.',                     'general'),
  (3, 24, 'quit',   'quit',     'quit',      'يستقيل',     'He quit his job to start his own company.',             'business'),
  (3, 25, 'shake',  'shook',    'shaken',    'يهزّ',       'The earthquake shook the entire building.',             'general'),

  -- ============================================================
  -- LEVEL 4: Upper-intermediate (25 verbs)
  -- ============================================================
  (4, 1,  'bind',      'bound',     'bound',      'يربط',       'She bound the documents together with a clip.',       'business'),
  (4, 2,  'bleed',     'bled',      'bled',       'ينزف',       'His finger bled after the paper cut.',                 'general'),
  (4, 3,  'cling',     'clung',     'clung',      'يتمسّك',     'The child clung to her mother in the crowd.',          'general'),
  (4, 4,  'creep',     'crept',     'crept',      'يزحف',       'The cat crept silently toward the mouse.',             'general'),
  (4, 5,  'flee',      'fled',      'fled',       'يفرّ',       'The refugees fled the country during the war.',        'general'),
  (4, 6,  'fling',     'flung',     'flung',      'يقذف',       'He flung the door open in excitement.',                'general'),
  (4, 7,  'forbid',    'forbade',   'forbidden',  'يمنع',       'The school forbade the use of phones in class.',       'academic'),
  (4, 8,  'grind',     'ground',    'ground',     'يطحن',       'She ground the coffee beans fresh every morning.',     'general'),
  (4, 9,  'knit',      'knitted',   'knitted',    'يحيك',       'My grandmother knitted a warm scarf for me.',          'general'),
  (4, 10, 'lean',      'leant',     'leant',      'يميل',       'He leant against the wall while waiting.',             'general'),
  (4, 11, 'leap',      'leapt',     'leapt',      'يقفز',       'The deer leapt over the fence gracefully.',            'general'),
  (4, 12, 'lend',      'lent',      'lent',       'يُقرض',      'The bank lent him money to buy a house.',              'business'),
  (4, 13, 'mow',       'mowed',     'mown',       'يجزّ',       'He mowed the lawn every Saturday morning.',            'general'),
  (4, 14, 'overcome',  'overcame',  'overcome',   'يتغلب على',  'She overcame her fear of public speaking.',            'academic'),
  (4, 15, 'overthrow', 'overthrew', 'overthrown', 'يُطيح',      'The people overthrew the corrupt government.',         'academic'),
  (4, 16, 'preset',    'preset',    'preset',     'يضبط مسبقاً','He preset the oven temperature before cooking.',      'general'),
  (4, 17, 'prove',     'proved',    'proven',     'يُثبت',      'The scientist proved the theory with new data.',       'academic'),
  (4, 18, 'sew',       'sewed',     'sewn',       'يخيط',       'She sewed a beautiful dress for the ceremony.',        'general'),
  (4, 19, 'shed',      'shed',      'shed',       'يسكب',       'She shed tears of joy at the wedding.',                'general'),
  (4, 20, 'shine',     'shone',     'shone',      'يُشرق',      'The sun shone brightly on the summer day.',            'general'),
  (4, 21, 'shoot',     'shot',      'shot',       'يطلق النار', 'The hunter shot the arrow at the target.',             'general'),
  (4, 22, 'shrink',    'shrank',    'shrunk',     'يتقلّص',     'The shirt shrank after being washed in hot water.',    'general'),
  (4, 23, 'sink',      'sank',      'sunk',       'يغرق',       'The old boat sank during the terrible storm.',         'travel'),
  (4, 24, 'slide',     'slid',      'slid',       'ينزلق',      'The children slid down the icy hill.',                 'general'),
  (4, 25, 'sow',       'sowed',     'sown',       'يزرع',       'The farmer sowed seeds in the spring.',                'general'),

  -- ============================================================
  -- LEVEL 5: Advanced (20 verbs)
  -- ============================================================
  (5, 1,  'abide',     'abode',      'abode',      'يلتزم',       'We must abide by the rules of the institution.',       'academic'),
  (5, 2,  'behold',    'beheld',     'beheld',     'يشاهد',       'They beheld the magnificent view from the summit.',    'travel'),
  (5, 3,  'beseech',   'besought',   'besought',   'يتوسّل',      'She besought the judge for mercy.',                    'general'),
  (5, 4,  'broadcast', 'broadcast',  'broadcast',  'يبثّ',        'The station broadcast the news live.',                 'business'),
  (5, 5,  'cast',      'cast',       'cast',       'يُلقي',       'The fisherman cast his net into the sea.',             'general'),
  (5, 6,  'dwell',     'dwelt',      'dwelt',      'يسكن',        'They dwelt in a small village by the river.',          'general'),
  (5, 7,  'foresee',   'foresaw',    'foreseen',   'يتوقع',       'Nobody foresaw the sudden change in the market.',      'business'),
  (5, 8,  'forsake',   'forsook',    'forsaken',   'يتخلّى عن',   'He forsook his comfortable life to help others.',      'general'),
  (5, 9,  'offset',    'offset',     'offset',     'يُعوّض',      'The gains offset the losses from last quarter.',       'business'),
  (5, 10, 'outdo',     'outdid',     'outdone',    'يتفوق على',   'She outdid all her classmates in the exam.',           'academic'),
  (5, 11, 'overrun',   'overran',    'overrun',    'يجتاح',       'Weeds overran the abandoned garden.',                  'general'),
  (5, 12, 'partake',   'partook',    'partaken',   'يشارك في',    'Everyone partook in the celebration feast.',           'general'),
  (5, 13, 'plead',     'pleaded',    'pleaded',    'يترافع',      'The lawyer pleaded the case before the jury.',         'business'),
  (5, 14, 'redo',      'redid',      'redone',     'يعيد عمل',    'She redid the entire report to fix the errors.',      'business'),
  (5, 15, 'relay',     'relayed',    'relayed',    'ينقل',        'He relayed the message to the rest of the team.',     'business'),
  (5, 16, 'repay',     'repaid',     'repaid',     'يسدّد',       'He repaid the loan ahead of schedule.',               'business'),
  (5, 17, 'undertake', 'undertook',  'undertaken', 'يتعهّد',      'The company undertook a major renovation project.',   'business'),
  (5, 18, 'withstand', 'withstood',  'withstood',  'يصمد أمام',   'The old bridge withstood the force of the flood.',    'general'),
  (5, 19, 'uphold',    'upheld',     'upheld',     'يؤيّد',       'The court upheld the original decision.',             'academic'),
  (5, 20, 'undergo',   'underwent',  'undergone',  'يخضع لـ',     'He underwent surgery to repair his shoulder.',        'general'),

  -- ============================================================
  -- LEVEL 6: Rare / literary (20 verbs)
  -- ============================================================
  (6, 1,  'beset',        'beset',        'beset',        'يحاصر',        'The travelers were beset by unexpected difficulties.', 'academic'),
  (6, 2,  'bet',          'bet',          'bet',          'يراهن',        'He bet all his savings on the final race.',             'general'),
  (6, 3,  'bid',          'bid',          'bid',          'يُزايد',       'She bid a high price for the antique painting.',        'business'),
  (6, 4,  'cleave',       'clove',        'cloven',       'يشقّ',         'The axe clove the log in a single strike.',             'general'),
  (6, 5,  'forecast',     'forecast',     'forecast',     'يتنبّأ',       'The analyst forecast a rise in oil prices.',            'business'),
  (6, 6,  'foretell',     'foretold',     'foretold',     'يتنبّأ بـ',    'The oracle foretold the fall of the kingdom.',          'academic'),
  (6, 7,  'inlay',        'inlaid',       'inlaid',       'يُطعّم',       'The craftsman inlaid the table with gold patterns.',    'general'),
  (6, 8,  'interweave',   'interwove',    'interwoven',   'يتشابك',       'The author interwove several storylines in the novel.', 'academic'),
  (6, 9,  'mislead',      'misled',       'misled',       'يُضلّل',       'The false advertisement misled many customers.',        'business'),
  (6, 10, 'misunderstand','misunderstood','misunderstood','يُسيء الفهم',  'She misunderstood the instructions on the form.',      'academic'),
  (6, 11, 'outbid',       'outbid',       'outbid',       'يُزايد أكثر',  'A rival company outbid us for the contract.',          'business'),
  (6, 12, 'outgrow',      'outgrew',      'outgrown',     'يتجاوز حجم',   'The child outgrew his shoes within two months.',       'general'),
  (6, 13, 'outshine',     'outshone',     'outshone',     'يتفوق على',    'Her performance outshone everyone else on stage.',     'academic'),
  (6, 14, 'overdo',       'overdid',      'overdone',     'يُبالغ في',    'He overdid the exercise and strained his muscles.',    'general'),
  (6, 15, 'overhear',     'overheard',    'overheard',    'يسمع بالصدفة', 'She overheard their private conversation by accident.', 'general'),
  (6, 16, 'override',     'overrode',     'overridden',   'يتجاوز',       'The manager overrode the system to approve the order.','business'),
  (6, 17, 'overtake',     'overtook',     'overtaken',    'يتجاوز',       'The smaller firm overtook its rivals in market share.', 'business'),
  (6, 18, 'slay',         'slew',         'slain',        'يقتل',         'The knight slew the dragon in the ancient tale.',       'academic'),
  (6, 19, 'stride',       'strode',       'stridden',     'يخطو بثبات',   'She strode confidently into the boardroom.',           'business'),
  (6, 20, 'wring',        'wrung',        'wrung',        'يعصر',         'She wrung the wet cloth before hanging it up.',         'general')

ON CONFLICT (base) DO NOTHING;
