-- Migration 086: Restructure curriculum_pronunciation for unit-level drill sets
-- Table has 0 rows, safe to restructure completely

-- Add new columns for structured pronunciation drills
ALTER TABLE curriculum_pronunciation
  ALTER COLUMN word DROP NOT NULL,
  ADD COLUMN IF NOT EXISTS focus_type text,
  ADD COLUMN IF NOT EXISTS title_en text,
  ADD COLUMN IF NOT EXISTS title_ar text,
  ADD COLUMN IF NOT EXISTS description_ar text,
  ADD COLUMN IF NOT EXISTS content jsonb DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now();

-- Add comment for clarity
COMMENT ON TABLE curriculum_pronunciation IS 'Per-unit pronunciation drill sets (1 per unit, 72 total). Content generated by Claude API.';
