-- Vocab cleanup tracking columns (idempotent)
ALTER TABLE curriculum_vocabulary
  ADD COLUMN IF NOT EXISTS regenerated_at           TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS cleanup_run_id           TEXT,
  ADD COLUMN IF NOT EXISTS original_example_sentence TEXT;

COMMENT ON COLUMN curriculum_vocabulary.regenerated_at IS
  'Timestamp when example_sentence was regenerated by vocab cleanup (Phase 0 / Tier 2/3).';
COMMENT ON COLUMN curriculum_vocabulary.cleanup_run_id IS
  'Identifies which cleanup run regenerated this row. Format: vocab-cleanup-YYYY-MM-DD-XXXXXXXX.';
COMMENT ON COLUMN curriculum_vocabulary.original_example_sentence IS
  'Pre-cleanup value of example_sentence. Never null if regenerated_at is set.';
