-- ─────────────────────────────────────────────────────────────────────────────
-- Retention System — Block 5 (Module 1 — Daily Practice Partner)
-- ─────────────────────────────────────────────────────────────────────────────
-- Branching dialogue engine. Each scenario has a tree of turns; student tap →
-- get AI line (text + optional audio) → record voice → Whisper transcribe →
-- rule-based eval picks next branch → loop until terminal turn.
--
-- ZERO runtime Claude call. Whisper IS allowed (existing fn). ElevenLabs
-- audio is pre-generated by Claude Code at build time (deferred — text-only
-- + browser TTS fallback in this commit).

-- ─── 1. retention_personas ──────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.retention_personas (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  slug text UNIQUE NOT NULL,
  name_en text NOT NULL,
  name_ar text NOT NULL,
  voice_id text,
  avatar_url text,
  personality_description text,
  language_register text DEFAULT 'casual' CHECK (language_register IN ('casual','professional','formal')),
  created_at timestamptz NOT NULL DEFAULT now()
);

-- ─── 2. retention_scenarios ─────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.retention_scenarios (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  slug text UNIQUE NOT NULL,
  persona_id uuid NOT NULL REFERENCES public.retention_personas(id) ON DELETE CASCADE,
  title_en text NOT NULL,
  title_ar text NOT NULL,
  setting_en text NOT NULL,
  goal_en text NOT NULL,
  difficulty text NOT NULL CHECK (difficulty IN ('easy','medium','challenging')),
  target_level text NOT NULL CHECK (target_level IN ('L1','L2','L3','L4','L5')),
  estimated_minutes smallint DEFAULT 5,
  target_vocab text[],
  target_grammar text[],
  active boolean DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS retention_scenarios_pick_idx
  ON public.retention_scenarios (target_level, difficulty, active);

-- ─── 3. retention_dialogue_turns ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.retention_dialogue_turns (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  scenario_id uuid NOT NULL REFERENCES public.retention_scenarios(id) ON DELETE CASCADE,
  turn_number smallint NOT NULL,
  parent_turn_id uuid REFERENCES public.retention_dialogue_turns(id) ON DELETE CASCADE,
  branch_label text,
  ai_text_en text NOT NULL,
  ai_audio_path text,
  expected_response_type text NOT NULL CHECK (expected_response_type IN (
    'yes_no','open','description','opinion','question_back','closing'
  )),
  expected_vocab text[],
  min_words smallint DEFAULT 3,
  is_terminal boolean DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS retention_dialogue_turns_scenario_idx
  ON public.retention_dialogue_turns (scenario_id, turn_number);
CREATE INDEX IF NOT EXISTS retention_dialogue_turns_parent_idx
  ON public.retention_dialogue_turns (parent_turn_id);

-- ─── 4. retention_feedback_templates ────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.retention_feedback_templates (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  scenario_id uuid REFERENCES public.retention_scenarios(id) ON DELETE CASCADE,
  trigger_condition jsonb NOT NULL,
  template_ar text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- ─── 5. retention_dialogue_attempts (expand Block 2 stub) ───────────────────
ALTER TABLE public.retention_dialogue_attempts
  ADD COLUMN IF NOT EXISTS scenario_id uuid REFERENCES public.retention_scenarios(id) ON DELETE SET NULL;
ALTER TABLE public.retention_dialogue_attempts
  ADD COLUMN IF NOT EXISTS started_at timestamptz DEFAULT now();
ALTER TABLE public.retention_dialogue_attempts
  ADD COLUMN IF NOT EXISTS branch_path uuid[] DEFAULT '{}';
ALTER TABLE public.retention_dialogue_attempts
  ADD COLUMN IF NOT EXISTS total_speaking_seconds integer DEFAULT 0;
ALTER TABLE public.retention_dialogue_attempts
  ADD COLUMN IF NOT EXISTS vocab_hit_count integer DEFAULT 0;
ALTER TABLE public.retention_dialogue_attempts
  ADD COLUMN IF NOT EXISTS vocab_hit_pct numeric(5,2);
ALTER TABLE public.retention_dialogue_attempts
  ADD COLUMN IF NOT EXISTS feedback_template_id uuid REFERENCES public.retention_feedback_templates(id) ON DELETE SET NULL;
ALTER TABLE public.retention_dialogue_attempts
  ADD COLUMN IF NOT EXISTS xp_awarded integer DEFAULT 0;
ALTER TABLE public.retention_dialogue_attempts
  ADD COLUMN IF NOT EXISTS transcript jsonb DEFAULT '[]'::jsonb;

CREATE INDEX IF NOT EXISTS retention_dialogue_attempts_scenario_idx
  ON public.retention_dialogue_attempts (scenario_id);

-- ─── 6. RLS ─────────────────────────────────────────────────────────────────
ALTER TABLE public.retention_personas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.retention_scenarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.retention_dialogue_turns ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.retention_feedback_templates ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS retention_personas_read ON public.retention_personas;
CREATE POLICY retention_personas_read ON public.retention_personas
  FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS retention_personas_admin_write ON public.retention_personas;
CREATE POLICY retention_personas_admin_write ON public.retention_personas
  FOR ALL TO authenticated
  USING (EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role = 'admin'))
  WITH CHECK (EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role = 'admin'));

DROP POLICY IF EXISTS retention_scenarios_read ON public.retention_scenarios;
CREATE POLICY retention_scenarios_read ON public.retention_scenarios
  FOR SELECT TO authenticated USING (active = true OR EXISTS (
    SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role IN ('admin','trainer')
  ));
DROP POLICY IF EXISTS retention_scenarios_admin_write ON public.retention_scenarios;
CREATE POLICY retention_scenarios_admin_write ON public.retention_scenarios
  FOR ALL TO authenticated
  USING (EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role = 'admin'))
  WITH CHECK (EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role = 'admin'));

DROP POLICY IF EXISTS retention_turns_read ON public.retention_dialogue_turns;
CREATE POLICY retention_turns_read ON public.retention_dialogue_turns
  FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS retention_turns_admin_write ON public.retention_dialogue_turns;
CREATE POLICY retention_turns_admin_write ON public.retention_dialogue_turns
  FOR ALL TO authenticated
  USING (EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role = 'admin'))
  WITH CHECK (EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role = 'admin'));

DROP POLICY IF EXISTS retention_feedback_read ON public.retention_feedback_templates;
CREATE POLICY retention_feedback_read ON public.retention_feedback_templates
  FOR SELECT TO authenticated USING (true);

-- Dialogue attempts: students can INSERT + UPDATE their own (for in-progress saves)
DROP POLICY IF EXISTS retention_dialogue_attempts_student_insert ON public.retention_dialogue_attempts;
CREATE POLICY retention_dialogue_attempts_student_insert ON public.retention_dialogue_attempts
  FOR INSERT TO authenticated WITH CHECK (student_id = auth.uid());
DROP POLICY IF EXISTS retention_dialogue_attempts_student_update ON public.retention_dialogue_attempts;
CREATE POLICY retention_dialogue_attempts_student_update ON public.retention_dialogue_attempts
  FOR UPDATE TO authenticated USING (student_id = auth.uid())
  WITH CHECK (student_id = auth.uid());
