-- Reading word glossary — offline EN→AR dictionary for the reading section.
-- Goal: every word a student taps in a reading passage resolves to an Arabic
-- meaning from STATIC data (no Claude / no runtime AI). curriculum_vocabulary
-- only covers ~2,679 of the 7,232 distinct passage tokens (and only exact,
-- lowercase forms — so inflections like "celebrations" miss). This table fills
-- the gap, keyed by the EXACT lowercased token as it appears in passages, so the
-- runtime lookup is an exact hit with no fragile lemmatization.
--
-- Rows are assembled offline from: inflected-form→base-meaning maps, the legacy
-- vocab_cache, and fresh translations generated by Claude Code at build time.

CREATE TABLE IF NOT EXISTS public.reading_glossary (
  word            text PRIMARY KEY,           -- exact lowercased token
  meaning_ar      text NOT NULL,
  part_of_speech  text,
  base_form       text,                        -- non-null when this is an inflected form
  source          text NOT NULL DEFAULT 'generated', -- lemma | cache | generated
  created_at      timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.reading_glossary IS
  'Offline EN→AR glossary for reading word-tap popups. Keyed by exact lowercased passage token. No runtime AI.';

ALTER TABLE public.reading_glossary ENABLE ROW LEVEL SECURITY;

-- Any authenticated user may read the dictionary.
DROP POLICY IF EXISTS reading_glossary_read ON public.reading_glossary;
CREATE POLICY reading_glossary_read ON public.reading_glossary
  FOR SELECT TO authenticated USING (true);

-- Writes only via service role (seed loader / future admin tooling).
DROP POLICY IF EXISTS reading_glossary_service_write ON public.reading_glossary;
CREATE POLICY reading_glossary_service_write ON public.reading_glossary
  FOR ALL TO service_role USING (true) WITH CHECK (true);
